### ISSUE TITLE
Crashing due to no ram

### ISSUE THREAD

**Issue by JerichoTitan** [scalda/FoolCraft#10]
I keep trying to play foolcraft on the curse launcher but it keeps crashing due to not having enough ram but I only have a few apps open so I don't know what to do

OS:mac

**Comment by Devious-Hat** [comment]
How much ram do you have allocated?
It needs a minimum of 4.5GB of RAM but its recommend to have 6GB.

**Comment by JerichoTitan** [comment]
not entirely sure because every other modpack works

**Comment by krisraynes** [comment]
Yep i raised mine to 6gb too (via Curse Profile settings)

**Comment by JerichoTitan** [comment]
I've fixed the problem
