### ISSUE TITLE
internal exception: java.io.ioexception: an existing connection was forcibly closed by remote host

### ISSUE THREAD

**Issue by szfi** [scalda/FoolCraft#100]
Not sure what is happening. I was playing for maybe roughly about 1-2 hours and then server crashed and i now can't play. I am hosting the server.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.0.155-universal.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.4.92-universal.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.12.jar)
  IvToolkit (IvToolkit-1.3.2.1-1.10.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.201-universal.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.3.0.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.233-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 3/26/17 12:41 PM
Description: Exception ticking world

io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:637)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:880)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:230)
	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:195)
	at net.minecraftforge.fml.common.network.FMLEmbeddedChannel.generatePacketFrom(FMLEmbeddedChannel.java:69)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.getEntitySpawningPacket(FMLNetworkHandler.java:132)
	at net.minecraft.entity.EntityTrackerEntry.func_151260_c(EntityTrackerEntry.java:482)
	at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:371)
	at net.minecraft.entity.EntityTracker.func_85172_a(EntityTracker.java:382)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:161)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.robrit.moofluids.common.entity.EntityFluidCow.writeSpawnData(EntityFluidCow.java:350)
	at net.minecraftforge.fml.common.network.internal.FMLMessage$EntitySpawnMessage.toBytes(FMLMessage.java:216)
	at net.minecraftforge.fml.common.network.internal.FMLRuntimeCodec.encodeInto(FMLRuntimeCodec.java:42)
	at net.minecraftforge.fml.common.network.internal.FMLRuntimeCodec.encodeInto(FMLRuntimeCodec.java:32)
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:73)
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:637)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:880)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:230)
	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:195)
	at net.minecraftforge.fml.common.network.FMLEmbeddedChannel.generatePacketFrom(FMLEmbeddedChannel.java:69)
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.getEntitySpawningPacket(FMLNetworkHandler.java:132)
	at net.minecraft.entity.EntityTrackerEntry.func_151260_c(EntityTrackerEntry.java:482)
	at net.minecraft.entity.EntityTrackerEntry.func_73117_b(EntityTrackerEntry.java:371)
	at net.minecraft.entity.EntityTracker.func_85172_a(EntityTracker.java:382)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:161)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['GemzyDesigns'/275, l='world', x=-388.87, y=94.99, z=298.39]]
	Chunk stats: ServerChunkCache: 569 Drop: 0
	Level seed: -4382639109462120826
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-220,64,258), Chunk: (at 4,4,2 in -14,16; contains blocks -224,0,256 to -209,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 184144 game time, 186476 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 4715 (now: false), thunder time: 84788 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 943649632 bytes (899 MB) / 2249719808 bytes (2145 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xmx4G -Xmx4G
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.32 Powered by Forge 12.18.3.2254 113 mods loaded, 113 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2254-universal.jar) 
	UCHIJAAAA	Forge{12.18.3.2254} [Minecraft Forge] (forge-1.10.2-12.18.3.2254-universal.jar) 
	UCHIJAAAA	ivtoolkit{1.3.2.1-1.10} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{2.1.3.201} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.201-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.6.233-universal.jar) 
	UCHIJAAAA	infinitylib{1.10.2-0.7.0} [InfinityLib] (infinitylib-0.7.0.jar) 
	UCHIJAAAA	agricraft{2.0.0-0.7.0-a12} [AgriCraft] (agricraft-2.0.0-0.7.0-a12.jar) 
	UCHIJAAAA	JEI{3.14.7.416} [Just Enough Items] (jei_1.10.2-3.14.7.416.jar) 
	UCHIJAAAA	appleskin{1.0.5} [AppleSkin] (AppleSkin-mc1.10.2-1.0.5.jar) 
	UCHIJAAAA	architecturecraft{1.7.1} [ArchitectureCraft] (ArchitectureCraft-1.7.1-mc1.10.2.jar) 
	UCHIJAAAA	Avaritia{1.10.2-2.0.5} [Avaritia] (Avaritia-1.10.2-2.0.5.jar) 
	UCHIJAAAA	avaritiaadditions{1.3} [Avaritia Additions] (avaritiaadditions-1.3.jar) 
	UCHIJAAAA	baconators{3.0.5} [Baconators] (baconators-1.10.2-3.0.5.jar) 
	UCHIJAAAA	Baubles{1.3.9} [Baubles] (Baubles-1.10.2-1.3.9.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2162} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2162-universal.jar) 
	UCHIJAAAA	blockarmor{2.3} [Block Armor] (BlockArmor-1.10.2-2.3.jar) 
	UCHIJAAAA	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.6.233} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.6.233-universal.jar) 
	UCHIJAAAA	cofhcore{4.1.0} [CoFH Core] (CoFHCore-1.10.2-4.1.0.155-universal.jar) 
	UCHIJAAAA	brandonscore{2.1.4} [Brandon's Core] (BrandonsCore-1.10.2-2.1.4.92-universal.jar) 
	UCHIJAAAA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJAAAA	chancecubes{1.10.2-2.3.4.171} [Chance Cubes] (ChanceCubes-1.10.2-2.3.4.171.jar) 
	UCHIJAAAA	ChestTransporter{2.5.9} [Chest Transporter] (ChestTransporter-1.10.2-2.5.9.jar) 
	UCHIJAAAA	CodeChickenCore{2.4.0.101} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.101-universal.jar) 
	UCHIJAAAA	ChickenChunks{2.2.0.52} [ChickenChunks] (ChickenChunks-1.10.2-2.2.0.52-universal.jar) 
	UCHIJAAAA	chickens{4.3.2} [Chickens] (chickens-4.3.2.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.8.12} [Chisel] (Chisel-MC1.10.2-0.0.8.12.jar) 
	UCHIJAAAA	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UCHIJAAAA	chiselsandbits{12.12} [Chisels & Bits] (chiselsandbits-12.12.jar) 
	UCHIJAAAA	cyclopscore{0.9.3} [Cyclops Core] (CyclopsCore-1.9.4-0.9.3.jar) 
	UCHIJAAAA	colossalchests{1.5.0} [Colossal Chests] (ColossalChests-1.10.2-1.5.0.jar) 
	UCHIJAAAA	one_point_twelve_concrete{v 1.0} [1.12 Concrete] (concreteMod-v1.0.jar) 
	UCHIJAAAA	cookingforblockheads{4.2.39} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.39.jar) 
	UCHIJAAAA	craftingtweaks{6.1.16} [Crafting Tweaks] (CraftingTweaks_1.10.2-6.1.16.jar) 
	UCHIJAAAA	MineTweaker3{3.0.16} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.16.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJAAAA	props{2.3.6.1} [Decocraft] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJAAAA	draconicevolution{2.0.8} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.8.177-universal.jar) 
	UCHIJAAAA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	UCHIJAAAA	embers{0.104} [Embers] (embers-0.104.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.3.3.jar) 
	UCHIJAAAA	fakeblocks{1.0.0} [FakeBlocks] (FakeBlocks 1.0.0.jar) 
	UCHIJAAAA	FastLeaveDecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.3.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCHIJAAAA	Waila{1.8.11-B25_1.10.2} [Waila] (Hwyla-1.8.11-B25_1.10.2.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.4.4.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.4.3.jar) 
	UCHIJAAAA	gravestone{1.5.12} [Gravestone] (GraveStone Mod 1.5.12.jar) 
	UCHIJAAAA	hatchery{0.2.10} [Hatchery] (hatchery-1.10.2-0.2.10.jar) 
	UCHIJAAAA	hermitron{0.1.9-beta} [Hermitron] (hermitron-1.10.2-0.1.9-beta.jar) 
	UCHIJAAAA	ichunutil{6.1.1} [iChunUtil] (iChunUtil-1.10.2-6.1.1.jar) 
	UCHIJAAAA	InventoryPets{1.4.9} [Inventory Pets] (inventorypets-1.10-1.4.9.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAA	iskalliumreactors{0.3.6-beta} [Iskallium Reactors] (iskalliumreactors-1.10.2-0.3.6-beta.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
	UCHIJAAAA	lootbags{2.3.2} [Loot Bags] (LootBags-1.10.2-2.3.2.jar) 
	UCHIJAAAA	loottweaker{0.0.4} [LootTweaker] (LootTweaker-1.10.2-0.0.4.jar) 
	UCHIJAAAA	malisiscore{1.10.2-4.3.0} [MalisisCore] (malisiscore-1.10.2-4.3.0.jar) 
	UCHIJAAAA	malisisdoors{1.10.2-5.2.0} [MalisisDoors] (malisisdoors-1.10.2-5.2.0.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJAAAA	RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
	UCHIJAAAA	MCA{1.10.2-5.2.3} [Minecraft Comes Alive] (MCA-1.10.2-5.2.3-universal.jar) 
	UCHIJAAAA	mtrm{1.2.1.20} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.10.2-1.2.1.20.jar) 
	UCHIJAAAA	natura{1.10.2-4.1.0.24} [Natura] (natura-1.10.2-4.1.0.24.jar) 
	UCHIJAAAA	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.3.500} [Tinkers' Construct] (TConstruct-1.10.2-2.6.3.jar) 
	UCHIJAAAA	moarsigns{4.2.2.8} [MoarSigns] (MoarSigns-1.10.2-4.2.2.8.jar) 
	UCHIJAAAA	mob_grinding_utils{0.1.8.16} [mob_grinding_utils] (MobGrindingUtils-0.1.8.16.jar) 
	UCHIJAAAA	examplemod{1.0} [Example Mod] (Modifiable-Armor-2-1.10.2-2.0.2.jar) 
	UCHIJAAAA	modifiable_armor{2.0.2} [Modifiable Armor 2] (Modifiable-Armor-2-1.10.2-2.0.2.jar) 
	UCHIJAAAA	mtlib{@VERSION@} [MTLib] (MTLib-1.0.1.jar) 
	UCHIJAAAA	modtweaker{2.0.10} [Mod Tweaker] (ModTweaker2-2.0.10.jar) 
	UCHIJAAAA	morechickens{1.0.11} [More Chickens] (MoreChickens-1.10.2-1.0.11.jar) 
	UCHIJAAAA	moreplayermodels{1.10.2} [MorePlayerModels] (MorePlayerModels_1.10.2(11nov16).jar) 
	UCHIJAAAA	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UCHIJAAAA	mw{1.8.1} [Modern Warfare] (mw-1.8.1_mc1.10.2.jar) 
	UCHIJAAAA	mysticalagriculture{1.4.4} [Mystical Agriculture] (mysticalagriculture[1.10.2]-1.4.4a.jar) 
	UCHIJAAAA	nethercore{1.10.2-2.0.3} [Nether Core] (nethercore-1.10.2-2.0.3.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	thermalfoundation{2.0.3} [Thermal Foundation] (ThermalFoundation-1.10.2-2.0.3.77-universal.jar) 
	UCHIJAAAA	plustic{3.1} [PlusTiC] (plustic-3.1.jar) 
	UCHIJAAAA	reccomplex{1.2.9.1-1.10} [Recurrent Complex] (RecurrentComplex-1.2.9.1-1.10.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.6.1} [Storage Drawers] (StorageDrawers-1.10.2-3.6.1.jar) 
	UCHIJAAAA	refinedstorage{1.2.24} [Refined Storage] (refinedstorage-1.2.24.jar) 
	UCHIJAAAA	rftools{5.88} [RFTools] (rftools-1.1x-5.88.jar) 
	UCHIJAAAA	roguelike{1.5.9} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.9.jar) 
	UCHIJAAAA	shadowmc{3.6.1} [ShadowMC] (ShadowMC-1.10.2-3.6.1.jar) 
	UCHIJAAAA	SimpleLabels{0.0.1} [SimpleLabels] (simplelabels-1-10.2-0.0.3.jar) 
	UCHIJAAAA	simplyconveyors{1.4.1} [Simply Conveyors] (SimplyConveyors-1.4.2.jar) 
	UCHIJAAAA	SleepingBag{1.4.0} [Sleeping Bag] (SleepingBag-1.10.2-1.4.0.jar) 
	UCHIJAAAA	subcommonlib{1.1.3.0} [Subaraki's Common Library] (sublib-1.10.2-1.1.3.0.jar) 
	UCHIJAAAA	thermalexpansion{5.0.3} [Thermal Expansion] (ThermalExpansion-1.10.2-5.0.3.86-universal.jar) 
	UCHIJAAAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJAAAA	tp{1.1.0} [Tiny Progressions] (tinyprogressions-1.10.2-1.1.0.jar) 
	UCHIJAAAA	torchmaster{1.0} [TorchMaster] (torchmaster_1.10.2-1.1.1.14.jar) 
	UCHIJAAAA	Translocator{2.1.3.52} [Translocator] (Translocators-1.10.2-2.1.3.52-universal.jar) 
	UCHIJAAAA	ts2k16{1.0.3} [Twerk-Sim 2K16] (TS2K16-1.0.3.jar) 
	UCHIJAAAA	usefulnullifiers{1.3.4} [Useful Nullifiers] (usefulnullifiers-1.3.4.jar) 
	UCHIJAAAA	VeinMiner{0.35.3_1.9-a46c1b0} [Vein Miner] (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.35.3_1.9-a46c1b0} [Mod Support] (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) 
	UCHIJAAAA	vc{4.24.0} [ViesCraft] (ViesCraft-1.10.X-4.24.0.jar) 
	UCHIJAAAA	wailafeatures{0.3.1.13} [WAILA Features] (WAILA-features-1.10.2-0.3.1.13.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.213.jar) 
	UCHIJAAAA	wawla{2.3.1.213} [What Are We Looking At] (Wawla-1.10.2-2.3.1.213.jar) 
	UCHIJAAAA	waystones{2.0.12} [Waystones] (Waystones_1.10.2-2.0.12.jar) 
	UCHIJAAAA	weaponcaseloot{4.0.2} [WeaponCaseLoot] (weaponcaseloot-1.10.2-4.0.2.jar) 
	UCHIJAAAA	Woot{1.10.2-1.2.6} [Woot] (woot-1.10.2-1.2.6.jar) 
	UCHIJAAAA	xpplus{1.0} [XP-Plus] (xpplus-1.01.jar) 
	UCHIJAAAA	moofluids{1.10.2-1.7.02.12b} [Moo Fluids] (MooFluids-1.10.2-1.7.02.12b.jar) 
	Loaded coremods (and transformers): 
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.0.155-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
Brandon's Core (BrandonsCore-1.10.2-2.1.4.92-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.12.jar)
  team.chisel.common.asm.ChiselTransformer
IvToolkit (IvToolkit-1.3.2.1-1.10.jar)
  
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.201-universal.jar)
  codechicken.nei.asm.NEITransformer
MalisisCorePlugin (malisiscore-1.10.2-4.3.0.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.233-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	NotEnoughItems Invalid Fingerprint Reports: 
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	ChickenChunks Invalid Fingerprint Reports: 
	Translocator Invalid Fingerprint Reports: 
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['GemzyDesigns'/275, l='world', x=-388.87, y=94.99, z=298.39]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by scalda** [comment]
It's a bad moo fluid cow
