### ISSUE TITLE
Bonsai Trees not outputting

### ISSUE THREAD

**Issue by ajdjyt** [scalda/FoolCraft#1003]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [X] I am requesting help with installing or running the pack

## Issue Description
In Iskall's 2nd episode of FC3 he shows that bonsai trees auto output to chests below them.
but when i tried this in my FC3 world they don't output to  a chest below them :(

## Reproduce Steps
place a chest under a bonsai tree and observe that it doesnt auto output

## Additional Information
![image](https://user-images.githubusercontent.com/26516505/40275724-e5095204-5c15-11e8-9b01-d31bb75ecd38.png)
also is spice of life supposed to be in the pack?

**Comment by SableP** [comment]
Unless I'm seeing your picture wrong, those are ordinary Bonsai pots, you need to update them to Hopping Bonsai pots for them to output to a chest.

**Comment by Mrbysco** [comment]
As said above. You need the Hopping varient of the Bonsai Pots. Normal Bonsai Pots do not auto output.

For future Foolcraft 3 related issues please use the new Github page: https://github.com/scalda/Foolcraft_3/issues
