### ISSUE TITLE
FC2 world crashes FC3 server

### ISSUE THREAD

**Issue by jagdtigger** [scalda/FoolCraft#1004]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Server Crashing while startup after updating to FC3.

## Reproduce Steps
Installed fresh mcforge server(forge-1.12.2-14.23.3.2655), then in absence of a server pack i used files from the client pack and added tinkers construct(TConstruct-1.12.2-2.10.0.81) then copied over the world from the FC2 server. After startup it asks confirmation a few times then crashes. Start it again and it starts but after i connect and shows the terrain around me after a few sec the server crashes...

## Additional Information
Logs of first start:
https://www.dropbox.com/s/8ketprmqqek82y2/debug.log?dl=0
https://www.dropbox.com/s/orgxew6ztiaquwr/latest.log?dl=0
https://www.dropbox.com/s/lvfbk9x930ypi4l/crash-2018-05-20_12.01.31-server.txt?dl=0

Logs of second run:
https://www.dropbox.com/s/9icdrx8bzuwr9n2/latest.log?dl=0
https://www.dropbox.com/s/6izeoi0n71qmdzk/debug.log?dl=0
https://www.dropbox.com/s/loztwrmwk70kpyf/crash-2018-05-20_12.16.17-server.txt?dl=0

**Comment by Mrbysco** [comment]
You're not supposed to use a FC2 world on FC3 as they're complete different packs.

**Comment by Mrbysco** [comment]
For a few reasons:

1. FC2 and FC3 are built on different MC versions, 1.11 and higher forced people to make items/block names lowercase due to this many of the 1.10 mods are not compatible.
2. A lot of FC2 mods were removed or massively changed. Due to this many blocks/items no longer exist.

**Comment by jagdtigger** [comment]
What a bummer :( . Thanks for the help, then i can prep myself for a major grind after my exams are over... :/

**Comment by Mrbysco** [comment]
For future Foolcraft 3 related issues please use the new Github page: https://github.com/scalda/Foolcraft_3/issues
