### ISSUE TITLE
using /give kicks you?

### ISSUE THREAD

**Issue by ajdjyt** [scalda/FoolCraft#1005]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [X] I am requesting help with installing or running the pack

## Issue Description
when i tried to use /give in my single player world i got kicked from the world to the main menu

## Reproduce Steps
use /give and type
"/give @p " and then try to press tab twice 

## Additional Information
[latest.log](https://github.com/scalda/FoolCraft/files/2020447/latest.log)

**Comment by Mrbysco** [comment]
For future Foolcraft 3 related issues please use the new Github page: https://github.com/scalda/Foolcraft_3/issues
