### ISSUE TITLE
Ham and Pineapple Pizza has no "Nutrients: Grain" in it.

### ISSUE THREAD

**Issue by Yadokingu** [scalda/FoolCraft#1006]
Foolcraft 3 v1.0.0

All the other Pizzas from Pam's have grain in them, on account of the dough being used in them. This one is also made from dough, but has no "Nutrients: Grain" in it.
Since it's a config option, I hope this is the right place to report this.

**Comment by Mrbysco** [comment]
Foolcraft 3 issues should be reported to the new Github page: https://github.com/scalda/Foolcraft_3/issues
