### ISSUE TITLE
2 different 'flowers' on top of one another

### ISSUE THREAD

**Issue by NanoGalactic** [scalda/FoolCraft#1007]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
in a highlands biome, i saw a "Pam's harverstcraft" bush, and on top of that, the upper half of a vanilla sunflower.

## Reproduce Steps
wandering around the world

## Additional Information
https://imgur.com/gallery/hOULhUa

**Comment by spike11302000** [comment]
i have noticed that also when traveling my world

**Comment by Mrbysco** [comment]
For Foolcraft 3 issues please report to the appropriate github.
https://github.com/scalda/Foolcraft_3/issues
