### ISSUE TITLE
Textures disappearing 

### ISSUE THREAD

**Issue by Temutschin** [scalda/FoolCraft#1008]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

I recently downloaded Foolcraft 3 at first having problems with game crashes so i used fixes to use the latest version of Java. after that the crashes were almost gone but the main issue is me loosing textures, mainly mob textures and vanilla chest textures disappear after some time. The blocks/mobs are there and do damage /can be used but after some time they loose their texture 

<!-- ADDITIONAL INFORMATION - Please post any crash reports, screenshots, etc. here. 
https://imgur.com/a/Jfjz9tA

**Comment by Temutschin** [comment]
https://imgur.com/a/Jfjz9tA images before and after restart, like i said at first all is normal like it should be and after some time some of the textures went missing

**Comment by Mrbysco** [comment]
You're reporting to the wrong Github.
https://github.com/scalda/Foolcraft_3/issues

**Comment by Temutschin** [comment]
ok thanks, i'll lock again in the other hub and eventually post there
