### ISSUE TITLE
Can't craft unstable ingot

### ISSUE THREAD

**Issue by Mundbjerg8** [scalda/FoolCraft#1009]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
It is not possible to craft an unstable ingot. I AM using a vanilla crafting table. My guess is that it doesn't work because vanilla crafting tables can keep their inventory in FC3

## Reproduce Steps
Craft an unstable ingot in a crafting table. Iron, stick and diamond. Doesn't work.

## Additional Information
https://imgur.com/gallery/YgWxWfZ

**Comment by Mrbysco** [comment]
You're reporting to the wrong Github.
https://github.com/scalda/Foolcraft_3/issues
