### ISSUE TITLE
Iskallium Reactors crafting recipe conflicts

### ISSUE THREAD

**Issue by NiSiSuinegEht** [scalda/FoolCraft#101]
Making the steel ingots with 8 iron surrounding a block of coal only yields 4 ingots of Thermal Foundation steel, and not the 9 Iskallium Reactors steel as stated in JEI.  These ingots cannot be crafted into a steel block using the 3x3 recipe, and can only be cast into a block via the Tinker's Construct smeltery.  The block produced is a Chisel "Caution" textured steel block that cannot be crafted with until chiseled into either a Railcraft or Thermal Foundation block, where it can then be turned back into Thermal Foundation ingots.

As of now, without manually editing configuration files, some of the blocks required for an Iskallium Reactor cannot be crafted.

EDIT:

After some quick poking around, it seems these recipes were removed and overridden in the MineTweaker recipe script intentionally.  Is there some reason that Iskallium Reactor crafting was broken in such a manner?  Is there another intended way to craft the required components of the multiblock?

**Comment by scalda** [comment]
I'm sorry but all blocks for the reactor can be crafted. Please provide
screen shoots of the problems

**Comment by scalda** [comment]
i can't see what you mean by the crafting is broken? it was made like this to fit the pack better

**Comment by scalda** [comment]
These are the recipes that should be showing for you in JEI

<img src=https://i.gyazo.com/ea48ff26b5fba6feb6b84c7ea22e7866.png>
<img src=https://i.gyazo.com/27a548e64d454b5ef682ca536c43fba2.png>
<img src=https://i.gyazo.com/015070a4acbccc12c6c57a93b4d8e7f8.png>
<img src=https://i.gyazo.com/4794763afe0db9e9b3dbb8179e420ce5.png>
