### ISSUE TITLE
Autocrafting in Refined Storage using Slice N' Splice only makes Skeletal Contractor

### ISSUE THREAD

**Issue by NolanPMC** [scalda/FoolCraft#1010]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
While using autocrafting with refined storage, any time I try to make something in it (Resonant Ender, Z-logic controller, etc) it will only try to make a Skeletal Contractor. This issue occurs even when the Skeletal Contractor recipe isn't in the crafter hooked up to the Slice n' Splice.

## Reproduce Steps
Set up Autocrafting for any of the Slice N' Splice recipes and then use the autocrafting

## Additional Information
(Screenshots of the process)
![image](https://user-images.githubusercontent.com/39675105/40587924-328e075e-6193-11e8-9aba-e5ab821fec0f.png)
![image](https://user-images.githubusercontent.com/39675105/40587925-4209df32-6193-11e8-903e-bd0c35cb2e58.png)
![image](https://user-images.githubusercontent.com/39675105/40587930-5b04603e-6193-11e8-9c6d-dac17820e0f0.png)

**Comment by Mrbysco** [comment]
For Foolcraft 3 issues please report to the appropriate github.
https://github.com/scalda/Foolcraft_3/issues
