### ISSUE TITLE
iChisel deletes stacks when chiseling 

### ISSUE THREAD

**Issue by rosso4001** [scalda/FoolCraft#1012]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When I use the iChisel (Chisel Mod) on stacks of cobblestone and shift click the chisel all option. It deletes the whole stack and leaves only 1 item per stack chiselled. 
(Also works with glass.)

 

## Reproduce Steps
Craft an iChisel
Collect several stacks of cobblestone.
Hold shift and chisel all stacks.
Stacks of items will be deleted and will be replaced with a single item.

## Additional Information

https://imgur.com/j0U3NEK
https://imgur.com/nzd6FtL

**Comment by Mrbysco** [comment]
For Foolcraft 3 issues please report to the appropriate github.
https://github.com/scalda/Foolcraft_3/issues
