### ISSUE TITLE
Foolcraft 3 Crashing Unexpected error java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by rosso4001** [scalda/FoolCraft#1013]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I was flying through the nether with a Flux-infused jetplate when my game crashed.
Every time I try to restart my world, It crashes shortly after start up.

## Additional Information

Crash report: https://pastebin.com/sdCHPuEy
I think the issue the crash report recomends is to: "Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)" but, I did't want to remove a mod without really knowing what I was doing. also looking 1.12.2 Foam fix Lawful doesn't exist.

**Comment by CaptainMorrow** [comment]
As above, I've also crashed shortly after updating to 1.1.0 on the twitch launcher.  Simply hit an Enderman and jumped into water.  World now crash upon loading:
"The game crashed whilst unexpected error
Error: java.lang.UnsupportedOperationException"
...Sorry apart from that I can't seem to open a crash report in the launcher...

**Comment by Mrbysco** [comment]
For Foolcraft 3 issues please report to the appropriate github.
https://github.com/scalda/Foolcraft_3/issues
