### ISSUE TITLE
Crashes when logging in

### ISSUE THREAD

**Issue by TrueSandwich** [scalda/FoolCraft#1014]
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I am in the nether and I crash every time I load up the world. When I set the render distance to 2, It loads the world around me perfectly, but if I turn up the render distance, I crash. This leads me to believe that it is a block somewhere in the nether around me that is causing the crash.

## Reproduce Steps
I am unsure of how this issue could be reproduced in a world besides mine.

## Additional Information
Crash report - https://pastebin.com/k8CQ6dFR

**Comment by dmiller2606** [comment]
I'm getting the same crash but i'm in the overworld, can't load into the world at all anymore. Looks like it's being caused by some thaumcraft particles. Not sure though.

**Comment by TrueSandwich** [comment]
My bad, I thought this was fora all Foolcraft issues
