### ISSUE TITLE
Crash in Nether (Foolcraft 3)

### ISSUE THREAD

**Issue by hexangle** [scalda/FoolCraft#1015]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x] I am requesting help with installing or running the pack

## Issue Description
when in the nether my game crashes directly and I dont know what is causing it.
(It is in Foolcraft 3)

**Comment by Mrbysco** [comment]
This is fixed by updating to 1.1.1
