### ISSUE TITLE
Malis' Door Factory Bug

### ISSUE THREAD

**Issue by FallenStargazer** [scalda/FoolCraft#1016]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
The Malis' Doors door factory block eats blocks used for the materials when trying to divide them up

## Reproduce Steps
Upon right or left clicking and dragging with the items to be used for the door materials, the blocks instantly vanish from the factory, as well as inventory

**Comment by Mrbysco** [comment]
For Foolcraft 3 issues please report to the appropriate github.
https://github.com/scalda/Foolcraft_3/issues
