### ISSUE TITLE
Low tps

### ISSUE THREAD

**Issue by yamy19** [scalda/FoolCraft#1017]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Yes the server I'm currently apart of I've been working with them to try to fix the tps we recently updated to the latest version of the modpack before we where getting a stabel 17-20 tps now since we've updated it's at a constant 4-5 tps we have lowers the render distance to 4 as perviously suggested from an old thread but to no luck.

## Reproduce Steps
It's just a constant thing

## Additional Information

https://m.imgur.com/sXFoOhm?r

Server specs
2x xeon E5620
64gb ddr3
about 8tb mechanical drive storage
256gb ssd

**Comment by Mrbysco** [comment]
For Foolcraft 3 issues please report to the appropriate github.
https://github.com/scalda/Foolcraft_3/issues
