### ISSUE TITLE
Can't get out of bed

### ISSUE THREAD

**Issue by nyanneko92** [scalda/FoolCraft#102]
Sometimes when I sleep in a vanilla bed it will act like I have gotten out of the bed but will keep me in the sleeping screen. I cannot click "leave bed" or hit ESC to close and reload the game. I can "/home" and it will teleport me there but will keep me in the sleep screen. The only way I have found to fix this is by closing out the whole screen and reloading everything.

**Comment by Bazizanab** [comment]
This is a vanilla bug that is continually made worse by modded clients. If you teleport (using waystones, waypoints on JourneyMap, or any other means) it will cause you to be stuck in your bed. To bypass this bug, log out of your single player world and log back in before you sleep to be safe. This is the method I have been using, and I have had a lot of success with it. DO NOTE: any method that lets you "sleep" (bed inventory pet, sleeping bag item, normal MC bed, etc) will experience this issue. Besides the re-logging solution, you can use commands to set the time to 0, which is essentially the beginning of the day, or another method if you discover one that I have forgotten.

I recommend to the dev team to add the [BedBugs mod](https://mods.curse.com/mc-mods/minecraft/254508-bed-bugs) if they're able to, but I personally tried adding it and it would crash the client when trying to forcefully kick me from my bed. Maybe a workaround can be achieved.

**Comment by scalda** [comment]
to get out of a bed when you are stuck please do /ftb kickme

this is a vanilla bug, the bedbugs mod doesn't work

**Comment by neoc666** [comment]
It's ridiculous that they don't just fix this.
