### ISSUE TITLE
Angel Ring currently Uncrafteable

### ISSUE THREAD

**Issue by xGarionx** [scalda/FoolCraft#1021]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Since the recipe change of the Angel Ring the crafting of it doesnt work anymore (others on the server were able to craft it with cursed lasso and golden lasso empty), but its uncraftable right now with bats (difently vanilla bats) and ghasts. I suspect the meta data of the damage value to be the issue of both items (i testet the jetpack with empty rf, full rf and make actually a compleltly new additional one to rule it out, since a smiliar issue occured once in another modpack were the jetpack were the issue)

## Reproduce Steps
- setup the extendet crafting station
- supply it with rf
- setup the pedestals (that are registered)
- try to craft the angelring with the listed ingriedients

**Comment by Mrbysco** [comment]
Try version 1.3.0.

For Foolcraft 3 issues please report to the appropriate github.
https://github.com/scalda/Foolcraft_3/issues
