### ISSUE TITLE
Astral Sorcery Attunement Step Assist not working

### ISSUE THREAD

**Issue by Jaciii** [scalda/FoolCraft#1023]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I work with the Astral Sorcery mod and attuned myself with Vicio, and a perk you can get is step assist (Hiking Boots), but it doesn't work.

## Reproduce Steps
Attune myself with Vicio and get the step assist perk (Hiking Boots)

**Comment by Mrbysco** [comment]
For Foolcraft 3 issues please report to the appropriate github. https://github.com/scalda/Foolcraft_3/issues
