### ISSUE TITLE
Multiplayer Server has some mods not working (Vein miner, hats, and graves)

### ISSUE THREAD

**Issue by PhantomHero** [scalda/FoolCraft#1024]
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
When trying to play on a local multiplayer server with a friend when we try to use vein miner it only breaks the block we break, when we try to get hats from mobs we dont collect them, and when we die no gravestone is left behind. (We didnt get any further than this exploring what did and didnt work as we tried to restart the server) I know mods are working as we had JEI and the journey map, alongside some other UI mods, but any gameplay mods we found didnt seem to work. 

## Reproduce Steps
Extracted server zip, ran forge-1.12.2... joined server

**Comment by Mrbysco** [comment]
For Foolcraft 3 issues please report to the appropriate github.
https://github.com/scalda/Foolcraft_3/issues
