### ISSUE TITLE
Iskalium reactors crafting bug?

### ISSUE THREAD

**Issue by svennieke** [scalda/FoolCraft#103]
![2017-03-26_21 46 07](https://cloud.githubusercontent.com/assets/7694658/24336180/d3f6d78c-128a-11e7-9ad9-744a0ac7e66e.png)

as you can see in the screenshot the steel block costs 8 steel and one iskalium and only gains 1 steel block, not sure if this is a bug or if this is intentional.

**Comment by scalda** [comment]
this is intentional. but thanks for playing
