### ISSUE TITLE
Can't load the pack

### ISSUE THREAD

**Issue by BeeryBush** [scalda/FoolCraft#105]
Whenever I try to load the pack it crashes at 3/7 5/5 loading entity radar... every single time.. really want to play it but I dont know whats going on here.

**Comment by HazDS** [comment]
Please you supply and crash logs and OS/Version of Java you are using?

**Comment by BeeryBush** [comment]
It doesnt give me a crash log it just gives me and error message saying that there was a problem and that I windows will notify me and all that jaz, and I just updated java but it's doing the exact same thing still.

**Comment by BeeryBush** [comment]
It doesn't actually crash the launcher or anthing, just right when it gets to the entity radar it gives me an error message saying "Java(TM) Platform SE Binary has stopped working A problem caused the program to stop working correctly, Windows will close the program and notify you if there's a solution available."

**Comment by Azure549** [comment]
I have been getting stuck at the same place as well getting Java Platform SE Binary to crash at 3/7 5/5 Entity Renderer. The only additional info I got out of the error in the problem details is this:

  Problem Event Name:	APPCRASH
  Application Name:	javaw.exe
  Application Version:	8.0.25.18
  Application Timestamp:	54345ca0
  Fault Module Name:	StackHash_c41d
  Fault Module Version:	6.1.7601.18247
  Fault Module Timestamp:	521eaf24
  Exception Code:	c0000374
  Exception Offset:	00000000000c4102
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	4105
  Additional Information 1:	c41d
  Additional Information 2:	c41d2d88e4f827edaf418d89330b34d2
  Additional Information 3:	c34c
  Additional Information 4:	c34cf76b4b3a494173f075eda53718e8

Past this I have tried uninstalling and reinstalling and messing with mods and it seems to work after I remove Enderzoo but I figure I would need that to get onto a sever. If there any other crash logs in the curse folder I have yet to find it so this is all I got.
Misc info:
Windows 7
Java version 8 update 121
Used both 4 gigs and 6 gigs of memory

**Comment by BeeryBush** [comment]
Yeah I think it's enderzoo that's messing it up.. once I removed it everything was working fine, but you can't join any servers.... no other mods I removed made it work either, so its got to be enderzoo,

**Comment by Azure549** [comment]
Some additional information, I can get Enderzoo working if i disable iChunUtil and Mob Dismemberment. Not sure if it means these 2 mods are conflicting or not.

**Comment by Azure549** [comment]
Hey BeeryBush, just looked through some solved cases and found this one: 
https://github.com/scalda/FoolCraft/issues/58
It seems to be the same as our so try some solutions from it since it seems updating your drivers works in fixing this.

**Comment by scalda** [comment]
the solution is to update your computers graphics drivers for it to work
