### ISSUE TITLE
Game crashed while changing body type

### ISSUE THREAD

**Issue by connerthecrafty** [scalda/FoolCraft#106]
Hello! I was messing around, and went to change my body type into one of the fluid cows, when i pressed it, the whole game crashed. It's probably not a major bug, but I just though I'd let you know 👍

**Comment by CriticalMole** [comment]
This is something wrong in the compaitibility of More Player models and other mods, and is not fixable in the config file.
Right now our only options are to leave in there with the bug or remove the mod enitrely.

**Comment by scalda** [comment]
not a pack bug please report to the mod author
