### ISSUE TITLE
Can't step from pathblock onto halfslab

### ISSUE THREAD

**Issue by KamiKuzi** [scalda/FoolCraft#108]
I have experienced the issue that you can't make the step from a pathblock onto a halfslab. Same issue with stepping from halfslab onto a block with carpet on it. Seems you can't make the step if it's more than a half block height difference. Pack Version is 1.2.1
![2017-03-27_20 17 45](https://cloud.githubusercontent.com/assets/26722061/24371264/9649578e-132a-11e7-9d61-d2ce18fcbc0c.png)

**Comment by Drago109** [comment]
i'm fairly sure that is normal minecraft and not the pack

**Comment by KamiKuzi** [comment]
Nope. Just double checked in 1.10.2 and 1.11.2 Vanilla. Works fine there. And testing with snow layers you can walk up onto 11/16 blocks max.

**Comment by EldonSurefoot** [comment]
Bug is present from Pack Version 1.0 (or that's as far back as the public releases go at least)

**Comment by Jo-Mamma75** [comment]
@KamiKuzi @EldonSurefoot 
Does this issue persist in 1.2.2 of the pack?

**Comment by EldonSurefoot** [comment]
Still there in 1.2.2,  yep.

**Comment by EldonSurefoot** [comment]
Just done a bit of testing, the problem seems to be Modifiable Armor 2.0. The issue goes away without it, and is there if it is the only mod loaded. I'm reporting the issue over there now.

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
