### ISSUE TITLE
Roguelike Dungeons not working

### ISSUE THREAD

**Issue by BigBeastBrady** [scalda/FoolCraft#110]
Roguelike dungeons are not working on my server or client side. I tried to reinstall and nothing works. I'm just trying to get it to work because it adds a lot of fun to the pack! Would like to know how to fix so I can start my server for my friends!

**Comment by DDzwiedziu** [comment]
I can confirm this. They don't spawn in SMP.

^(I'm not sure about fun-to-reward ratio, which was low when exploring RLD in modpacks)

**Comment by CriticalMole** [comment]
the default config has them quite rare, in your client side configs you can change the spawn rate, and for setting up a server you can alos change them, but they do indeed work with the standard settings.
