### ISSUE TITLE
Nether ores turns to coal

### ISSUE THREAD

**Issue by birkendorfen** [scalda/FoolCraft#112]
Some nether ores turns to coal when mined.

![image](https://cloud.githubusercontent.com/assets/26726174/24380404/70eb4986-134b-11e7-8539-aaa278905e82.png)

**Comment by neoc666** [comment]
For me that's a purely 'visual' bug: It seems to be just WAILA. If I mine it, I get what I expect (I guess emerald in this case).

**Comment by scalda** [comment]
this is a visual bug which is fixed in the next update of the mod
