### ISSUE TITLE
I can't procreate

### ISSUE THREAD

**Issue by NuclearHotPocket** [scalda/FoolCraft#113]
![2017-03-27_15 39 17](https://cloud.githubusercontent.com/assets/26726349/24381250/2fd62a16-1304-11e7-8036-f1d29825dd3a.png)
![2017-03-27_15 39 26](https://cloud.githubusercontent.com/assets/26726349/24381252/31c92260-1304-11e7-9816-f819fbedf443.png)
![2017-03-27_15 39 30](https://cloud.githubusercontent.com/assets/26726349/24381256/368c87ce-1304-11e7-8670-339b26445881.png)
This is an interesting bug, I can't get a baby...

**Comment by Nathan-stanley** [comment]
I believe the baby is in her inventory.

**Comment by NuclearHotPocket** [comment]
I took a screenshot of her inventory
![2017-03-29_15 05 48](https://cloud.githubusercontent.com/assets/26726349/24478847/61acb7ec-1491-11e7-8d9a-6ca2e689ff12.png)
I did this after hitting the button

**Comment by Jo-Mamma75** [comment]
@NuclearHotPocket 
Have you attempted to post this issue on the Minecraft Comes Alive [Github](https://github.com/WildBamaBoy/minecraft-comes-alive/issues)?

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
