### ISSUE TITLE
Vein Miner works sometimes(solved)

### ISSUE THREAD

**Issue by fluxabiliti909** [scalda/FoolCraft#114]
For some reason vein miner only works when it feels like it. It feels like 90% of the time it refuses to actually vein mine the resource I ask it to mine. It has all the ores and blocks in the configs as well as all the tools. What do I do????

**Comment by bogger33** [comment]
it won't work if it's still vein mining something else

**Comment by fluxabiliti909** [comment]
I know that but I will be caving and try to mine resources as I see them and it doesn't work. I can't tell if its a bug or something else

**Comment by itzmes** [comment]
same issue it started when i reinstalled the modpack then veinminer has not work sence

**Comment by neoc666** [comment]
Switch to [Ore Excavation](https://minecraft.curseforge.com/projects/ore-excavation), it's much better maintained. You can just install it with Curse.
