### ISSUE TITLE
Can't load since latest update

### ISSUE THREAD

**Issue by Inzult54312** [scalda/FoolCraft#115]
Basically the title. I try and load the game and I get this error. 
 
GAME CRASH

An unexpected issue occurred and the game has crashed. 
  
I get nothing else, just that. Since the last update, I can't play. I even tweeted at Iskall.

**Comment by scalda** [comment]
Have you got a crash report please?

**Comment by BeeryBush** [comment]
Same thing is happening to me, no one seems to want to respond to me though..

**Comment by Inzult54312** [comment]
> Have you got a crash report please?  
 
@scalda No, I wasn't given one.

**Comment by lebh** [comment]
@Inzult54312  well I would look to see if you have any conflicting mods in the pack, the same thing happen to me, cause I had 2 foamfix in the mod folder, and you can also check if there is any crash report in the crash-reports folder in the modpack it dosent always pop-up with a crash report

**Comment by Inzult54312** [comment]
@lebh That worked! I had another foamfix some how.
