### ISSUE TITLE
Illuminati Pet is a ticking timebomb

### ISSUE THREAD

**Issue by Mrbysco** [scalda/FoolCraft#117]
The illuminati pet has the ability to summon random craft able items, cool.
But once it tries to give you XP Plus' ItemSpeedCard (and probably every XP Plus item) it crashes your client and you will be unable to join the world unless you edit the item out of your inventory.

https://pastebin.com/LCM4kpkk See crash log.

Looking at XPPlus' code it points at a tag which the summoning of the item probably didn't give it. Making it crash.

**Comment by pokeba** [comment]
Fix should be released soon :]

**Comment by pokeba** [comment]
Fixed in update 1.02 of XP-Plus.

**Comment by CriticalMole** [comment]
Thanks Pokeba, we will be updating as many mods as possible in the next update

**Comment by scalda** [comment]
Will be fixed in 1.3
