### ISSUE TITLE
can't take damage while in a team.

### ISSUE THREAD

**Issue by magicWithLobster** [scalda/FoolCraft#118]
When i join a team I can't take any damage. I neither get the extra ten harts from obsidian armor.

**Comment by Jo-Mamma75** [comment]
@magicWithLobster 
Has this issue persisted or ever been resolved?

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
