### ISSUE TITLE
(Recipe Conflict) Scythe and Sickle

### ISSUE THREAD

**Issue by Mrbysco** [scalda/FoolCraft#119]
There's currently a recipe conflict between Tiny Progressions Scythe and Thermal Foundation's Sickle.
I know you people already disabled Extra Utilities Sickle that would conflict.

Sadly Scythe's are using the same recipe as you can see in these images.

![2017-03-28_17 35 04](https://cloud.githubusercontent.com/assets/9308260/24413872/10863780-13dd-11e7-9cb1-dd2701f8ad3c.png)

![2017-03-28_17 36 03](https://cloud.githubusercontent.com/assets/9308260/24413884/183d57b0-13dd-11e7-9427-7cf6e84a54af.png)

![2017-03-28_17 35 07](https://cloud.githubusercontent.com/assets/9308260/24413886/1aad4884-13dd-11e7-9f17-ff6ab660fc77.png)

**Comment by scalda** [comment]
Will be fixed in 1.3
