### ISSUE TITLE
[Suggestion] Angel Ring to Bauble

### ISSUE THREAD

**Issue by rrasmuuus** [scalda/FoolCraft#120]
There is a mod which allows you to convert your Angel Ring to a Bauble ring so you can put it on your ring slot. Would be cool if this was added to Fool Craft
Here is the link to the mod: [Angel Ring to Bauble](https://minecraft.curseforge.com/projects/angel-ring-to-bauble)

**Comment by Jo-Mamma75** [comment]
We are already considering this mod for a future update.  Thanks for the suggestion.

**Comment by scalda** [comment]
added to the new version
