### ISSUE TITLE
Colossal chests voiding items

### ISSUE THREAD

**Issue by Nathan-stanley** [scalda/FoolCraft#122]
I noticed recently, after destroying one of my machines, that the colossal chests were voiding a huge amount of the items I was pumping into them. It had voided my machines I mined (global traveler) and draconium, and a lot of things while I was in the nether. I have my area chunk loaded, making this even more confusing. I have no clue how much I've lost, but its definitely quite a problem.

**Comment by Nathan-stanley** [comment]
I just realized it's the only not chunk loaded part of my base... Still, those machines I destroyed were destroyed while I was in my base, and within 30 blocks of the chest.

**Comment by Jo-Mamma75** [comment]
Were you using the Global Traveler (from PlusTiC) and trying to break a machine from Extra Utilities 2?  If that's the case, the issue has already been reported to Landmaster on the PlusTiC Github.  See [here](https://github.com/Landmaster/PlusTiC/issues/15).

**Comment by Nathan-stanley** [comment]
No, I broke an Ender IO machine. Also, I found that almost everything I had broken in the past hour or so were voided. Only things that stacked with items already in the system survived (e.g. if there was 34 string in the system and 3 were added, the string was not voided, but if there weren't blaze rods, the blaze rods were voided)

**Comment by scalda** [comment]
For the time being use a normal chest bound to the pick and then use a conduit or something to transfer from the bound chest to the colossal chest.

**Comment by Landmaster** [comment]
If I'm correct, this should be fixed starting in PlusTiC 4.2.0.0.
