### ISSUE TITLE
Ender IO & Chickens/Hatchery communication.

### ISSUE THREAD

**Issue by Kittenonthek3ys** [scalda/FoolCraft#124]
Hey Scalda (and team)

I seem to have a bit of an issue with Ender IO cables and the Chickens/Hatchery mods communicating.

I've placed the Nesting Pens on top of the Item Conduits, and after a while they will stop taking things out of the pens, and into the chest I've connected it with. It will then just start backing up inside the pens.

If i then break and replace the conduits under the pens, they will start pulling again.

And then stop again after a while.

Feel free to poke me on Discord, if you want to come take a look at my setup if i didn't explain myself well enough :) 

-Mrs_Mibbins

**Comment by Kittenonthek3ys** [comment]
A foot not.

Sometimes i get kicked off the server, restart my client - when i log back in - it sometimes have resolved itself and starts pulling again :)

**Comment by scalda** [comment]
It's a problem with the loading and unloading of chunks with FTBU
