### ISSUE TITLE
World Loading Issue

### ISSUE THREAD

**Issue by Nathan-stanley** [scalda/FoolCraft#128]
When loading my worlds, occasionally it gets stuck on the "loading world" screen. I checked task manager, to see if it was even doing anything, and found that it wasn't even using my CPU at all. I have plenty of allocated ram as well (6 GB).

**Comment by Senophoe** [comment]
Happens to me and another friend who plays FoolCraft too. And only on FoolCraft.

**Comment by scalda** [comment]
please provide the log so we can see what the issue is.

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
