### ISSUE TITLE
Mod Request - Uncrafting Table

### ISSUE THREAD

**Issue by Omegapsychosis** [scalda/FoolCraft#129]
Can we get a mod to uncraft items? We get a lot of block armour that would be more useful in it's component forms. 

I found this one as an option on curse that uses XP - https://mods.curse.com/mc-mods/minecraft/254993-jglrxavpoks-uncrafting-table

**Comment by scalda** [comment]
Won't be added sadly due to the abuse of the block armor in the loot tables
