### ISSUE TITLE
JEI UI Bug

### ISSUE THREAD

**Issue by st3v1sh** [scalda/FoolCraft#13]
When I do the hotkey for hiding the JEI UI, it works as intended, but when I exit and re-renter the inventory, half the UI appears again.

![jei ui bug](https://cloud.githubusercontent.com/assets/26508217/24077845/05574ed4-0c31-11e7-83a3-e473e1c6a1f7.gif)

**Comment by Jo-Mamma75** [comment]
It could just be a bug with JEI.  Have you looked at their Github for the same issue?

**Comment by st3v1sh** [comment]
I've upgraded to the new version of FoolCraft. Just tried isolating the mod **jei_1.10.2-3.14.7.416** and ran it with **forge-12.18.3.2254**.

It works fine when isolated from the other mods, but it still doesn't work as intended inside the modpack.

I think the problem is in the mod **NotEnoughItems-1.10.2-2.1.3.201-universal** and its dependents **CodeChickenCore-1.10.2-2.4.0.101-universal** and **CodeChickenLib-1.10.2-2.5.6.233-universal**. When isolating those mods, the UI problem emerges.

I'm going to post this issue onto the NEI GitHub if it's not already there. I'm not sure if this should be closed since it's not really related to a problem with the modpack anymore, so I'll leave it open for an admin to close it.
