### ISSUE TITLE
[Suggestion] Profile ore distribution with JustEnoughResources

### ISSUE THREAD

**Issue by Senophoe** [scalda/FoolCraft#131]
JustEnoughResources has a feature that shows the ore generation graphs in game, but is not currently used by FoolCraft. The feature allows the player to know the correct height for specific ore generation. The figure below shows an in-game example for Iron Ore.

http://puu.sh/mDbxo/3fe211158a.png

You have to use the JustEnoughResources command **/profile [chunk amount] [dimensions]**. In our case, that would be something like **/profile 10000 all** to profile 10000 chunks of each dimension.

Finally, a world-gen.json file will be generated inside .../config/jeresources. Just make sure this file is there, and when you launch the game again you'll be able to see those graphs when looking up ores on NEI.

The idea here is to profile a decent ammount of chunks and make the world-gen.json file available for everyone on the next possible update of FoolCraft.

**Comment by scalda** [comment]
Thank you for the suggestion, i have now made this file and it will be included in 1.3. this must of changed recently as i knew it use to do it automatically
