### ISSUE TITLE
4 seeds not working with Agricraft

### ISSUE THREAD

**Issue by Mrbysco** [scalda/FoolCraft#132]
Blizz, Blitz, Basalz and Manyullyn seeds (Mystical Agriculture) when searching don't show a use other than the "Seed Reprocessor"
They can't be scanned and can't be placed on crop sticks.

(They do work on normal farmland, it's just them not working with Agricraft probably due to missing jsons for them)

As far as I can see those are the only ones not working with Agricraft.

**Comment by Jo-Mamma75** [comment]
Thanks for letting us know.  I'll put it on the list for a future update.

**Comment by scalda** [comment]
These are added in the next release thanks for letting us know
