### ISSUE TITLE
Biomes O'Plenty issue

### ISSUE THREAD

**Issue by MorrieMiner** [scalda/FoolCraft#134]
I haven't seen anyone else post this issue so it might just be me, I'm playing on a single player world and I have just spent maybe 2-3 hours exploring with an angel ring looking for a cool place to set up my main base and I began to realise that I haven't come across a single non-vanilla biome. I have checked the mod list and inventory and I can see that it's there as there are Biome O'Plenty signs and stuff but no new biomes. I don't know what to make of it. Any suggestions?

**Comment by scalda** [comment]
Did you choose bop when made your sp world?

**Comment by MorrieMiner** [comment]
I did not. The problem is me :( Thanks anyway scalda
