### ISSUE TITLE
Make getting dyes easier - script included!

### ISSUE THREAD

**Issue by foxanthony1** [scalda/FoolCraft#136]
This allows using ore dictionary dyes to get the colored eggs.

//Colored Eggs
recipes.remove(<chickens:colored_egg>);
recipes.remove(<chickens:colored_egg:1>);
recipes.remove(<chickens:colored_egg:2>);
recipes.remove(<chickens:colored_egg:3>);
recipes.remove(<chickens:colored_egg:4>);
recipes.remove(<chickens:colored_egg:11>);
recipes.remove(<chickens:colored_egg:15>);
recipes.remove(<chickens:colored_egg:10>);
recipes.remove(<chickens:colored_egg:12>);
recipes.remove(<chickens:colored_egg:13>);
recipes.remove(<chickens:colored_egg:14>);
recipes.remove(<chickens:colored_egg:5>);
recipes.remove(<chickens:colored_egg:6>);
recipes.remove(<chickens:colored_egg:7>);
recipes.remove(<chickens:colored_egg:8>);
recipes.remove(<chickens:colored_egg:9>);

recipes.addShaped(<chickens:colored_egg>, [[<ore:dyeBlack>, <ore:dyeBlack>, <ore:dyeBlack>], [<ore:dyeBlack>, <minecraft:egg>, <ore:dyeBlack>], [<ore:dyeBlack>, <ore:dyeBlack>, <ore:dyeBlack>]]);
recipes.addShaped(<chickens:colored_egg:1>, [[<ore:dyeRed>, <ore:dyeRed>, <ore:dyeRed>], [<ore:dyeRed>, <minecraft:egg>, <ore:dyeRed>], [<ore:dyeRed>, <ore:dyeRed>, <ore:dyeRed>]]);
recipes.addShaped(<chickens:colored_egg:2>, [[<ore:dyeGreen>, <ore:dyeGreen>, <ore:dyeGreen>], [<ore:dyeGreen>, <minecraft:egg>, <ore:dyeGreen>], [<ore:dyeGreen>, <ore:dyeGreen>, <ore:dyeGreen>]]);
recipes.addShaped(<chickens:colored_egg:3>, [[<ore:dyeBrown>, <ore:dyeBrown>, <ore:dyeBrown>], [<ore:dyeBrown>, <minecraft:egg>, <ore:dyeBrown>], [<ore:dyeBrown>, <ore:dyeBrown>, <ore:dyeBrown>]]);
recipes.addShaped(<chickens:colored_egg:4>, [[<ore:dyeBlue>, <ore:dyeBlue>, <ore:dyeBlue>], [<ore:dyeBlue>, <minecraft:egg>, <ore:dyeBlue>], [<ore:dyeBlue>, <ore:dyeBlue>, <ore:dyeBlue>]]);
recipes.addShaped(<chickens:colored_egg:11>, [[<ore:dyeYellow>, <ore:dyeYellow>, <ore:dyeYellow>], [<ore:dyeYellow>, <minecraft:egg>, <ore:dyeYellow>], [<ore:dyeYellow>, <ore:dyeYellow>, <ore:dyeYellow>]]);
recipes.addShaped(<chickens:colored_egg:15>, [[<ore:dyeWhite>, <ore:dyeWhite>, <ore:dyeWhite>], [<ore:dyeWhite>, <minecraft:egg>, <ore:dyeWhite>], [<ore:dyeWhite>, <ore:dyeWhite>, <ore:dyeWhite>]]);
recipes.addShaped(<chickens:colored_egg:10>, [[<ore:dyeLime>, <ore:dyeLime>, <ore:dyeLime>], [<ore:dyeLime>, <minecraft:egg>, <ore:dyeLime>], [<ore:dyeLime>, <ore:dyeLime>, <ore:dyeLime>]]);
recipes.addShaped(<chickens:colored_egg:12>, [[<ore:dyeLightBlue>, <ore:dyeLightBlue>, <ore:dyeLightBlue>], [<ore:dyeLightBlue>, <minecraft:egg>, <ore:dyeLightBlue>], [<ore:dyeLightBlue>, <ore:dyeLightBlue>, <ore:dyeLightBlue>]]);
recipes.addShaped(<chickens:colored_egg:13>, [[<ore:dyeMagenta>, <ore:dyeMagenta>, <ore:dyeMagenta>], [<ore:dyeMagenta>, <minecraft:egg>, <ore:dyeMagenta>], [<ore:dyeMagenta>, <ore:dyeMagenta>, <ore:dyeMagenta>]]);
recipes.addShaped(<chickens:colored_egg:14>, [[<ore:dyeOrange>, <ore:dyeOrange>, <ore:dyeOrange>], [<ore:dyeOrange>, <minecraft:egg>, <ore:dyeOrange>], [<ore:dyeOrange>, <ore:dyeOrange>, <ore:dyeOrange>]]);
recipes.addShaped(<chickens:colored_egg:5>, [[<ore:dyePurple>, <ore:dyePurple>, <ore:dyePurple>], [<ore:dyePurple>, <minecraft:egg>, <ore:dyePurple>], [<ore:dyePurple>, <ore:dyePurple>, <ore:dyePurple>]]);
recipes.addShaped(<chickens:colored_egg:6>, [[<ore:dyeCyan>, <ore:dyeCyan>, <ore:dyeCyan>], [<ore:dyeCyan>, <minecraft:egg>, <ore:dyeCyan>], [<ore:dyeCyan>, <ore:dyeCyan>, <ore:dyeCyan>]]);
recipes.addShaped(<chickens:colored_egg:7>, [[<ore:dyeLightGray>, <ore:dyeLightGray>, <ore:dyeLightGray>], [<ore:dyeLightGray>, <minecraft:egg>, <ore:dyeLightGray>], [<ore:dyeLightGray>, <ore:dyeLightGray>, <ore:dyeLightGray>]]);
recipes.addShaped(<chickens:colored_egg:8>, [[<ore:dyeGray>, <ore:dyeGray>, <ore:dyeGray>], [<ore:dyeGray>, <minecraft:egg>, <ore:dyeGray>], [<ore:dyeGray>, <ore:dyeGray>, <ore:dyeGray>]]);
recipes.addShaped(<chickens:colored_egg:9>, [[<ore:dyePink>, <ore:dyePink>, <ore:dyePink>], [<ore:dyePink>, <minecraft:egg>, <ore:dyePink>], [<ore:dyePink>, <ore:dyePink>, <ore:dyePink>]]);

**Comment by scalda** [comment]
Thanks added to the next pack version. but please when MT scripts are done please include the < > around the item names as i just had to go through and add them all
