### ISSUE TITLE
Veinminer issue

### ISSUE THREAD

**Issue by TheRealLeftShark** [scalda/FoolCraft#137]
I found a issue with the FoolCraft pack and the owner of veinminer has been told about it already having the + in the name of the VeinMiner-1.9-0.35.3.595+a46c1b0.jar file is causing issues with players connecting to servers the + needs to be changed to not have the + in the name for it to work properly and let everyone connect properly the file name needs to be changed in the server files and the modpack aswell

**Comment by scalda** [comment]
this has been rectified for the next pack version. thanks again

**Comment by TheRealLeftShark** [comment]
You said this would be fixed in the next version the version just dropped and its not fixed it still has the + in the name

**Comment by Whazaaaaa** [comment]
I'd like to point out that there is still a '+' in 1.3.2 and im still having problems with veinminer.
