### ISSUE TITLE
WeaponCaseLoot Bow's 

### ISSUE THREAD

**Issue by XxShadowX** [scalda/FoolCraft#138]
Enchanted a weaponcaseloot bow with infinity. Attempt to fire the bow and client crashes. 

client crashlog here : https://hastebin.com/qupozaxuje.scala

**Comment by WinterGrave** [comment]
Checking the issue

**Comment by WinterGrave** [comment]
Fixed on version 4.0.3

**Comment by scalda** [comment]
this will be in the next version of foolcraft thank you winter
