### ISSUE TITLE
Can't sleep

### ISSUE THREAD

**Issue by ftrocchi** [scalda/FoolCraft#140]
Mod pack worked fine for about a day.  Now every time anyone on the server tries to sleep through the night they can't get out of bed.

We've tried beds and sleeping bags, multiple people on the server and only one.  No matter what we do, we can't get out of bed.

Time advances, as we can see it change to day.  The Leave Bed button is still shown but we does nothing when we click on it.  

Any suggestions?

**Comment by Mrbysco** [comment]
That's a known vanilla bug. There isn't much a modpack can do other than implementing the Bed Bugs mod that adds a kick button. 
Kicking the player is the only thing to do when you got the issue. There's no fix afaik.

**Comment by scalda** [comment]
This has already been posted on this issue tracker please read the closed
issues or the wiki before posting.

But for future reference just do /ftb kickme when stuck in a bed
