### ISSUE TITLE
[Suggestion] Custom recipe to create Quarried Stone from Railcraft

### ISSUE THREAD

**Issue by Mrbysco** [scalda/FoolCraft#142]
At the moment the only way to get quarried stone is to find it in worldgen.
I'd like to ask if there could be a recipe added perhaps using a mixture of marble essence and something else.

**Comment by TheRealLeftShark** [comment]
heres the recipe i made for it i feel like its pretty fair recipes.addShaped(<railcraft:generic:9> * 4, [[<mysticalagriculture:marble_essence>, <mysticalagriculture:marble_essence>, <mysticalagriculture:marble_essence>], [<mysticalagriculture:marble_essence>, <minecraft:stone>, <mysticalagriculture:marble_essence>], [<mysticalagriculture:marble_essence>, <mysticalagriculture:marble_essence>, <mysticalagriculture:marble_essence>]]);

**Comment by scalda** [comment]
thanks added for the next version
