### ISSUE TITLE
Suggestion: fix the spawn rates on certain blocks

### ISSUE THREAD

**Issue by orion74656** [scalda/FoolCraft#144]
Can we increase the spawn rates on Diorite, Granite, Marble and Limestone? All four blocks are valid building blocks that people may want to use and their lack of (or low-rate) spawning dissuades people from using them. I don't feel people's options should be limited like they are. 

Is it possible to make them more like Quarried Stone? Rare but large veins? That way they can still be obtained.

I understand that granite and diorite have vanilla recipes, but people may want to use diorite before they've gotten to the nether (or before they get the machines to make it), and thus they can't use it. Also, marble and limestone can be made via mystical agriculture, but you need the blocks to make the seeds and if you can't find the blocks, you can't make the seeds.

Can we look into finding a happy medium for this?

**Comment by scalda** [comment]
Unfortunately we won't be increasing the rates, granite/diorite/andersite can all be made via TE. as for the marble and limestone you will need to find the first blocks to be able to make the seeds.
