### ISSUE TITLE
[Suggestions] More Tweaks & Iskallium Generation

### ISSUE THREAD

**Issue by Senophoe** [scalda/FoolCraft#145]
**Tweaks:**

Inventory Pets: Change **B:"Show Update Message"** from true to false.

Invetory Tweaks: Change **enableConfigLoadedMesssage** from false to true. This was a typo by Kobata. Setting this config to true will actually disable the greeting message shown in in-game chat ("InvTweaks: Configuration Loaded.").

**Iskallium Generation:**

Iskallium Ore is currently generated only on Overworld. Since it's far more rare than any other ores, players are encouraged to mine in that dimension. By the point you get enough Iskallium Ores to build a decent reactor, you have so many resources that ores aren't a problem anymore. And because of that, mining on the Deep Dark is strongly discouraged.

Since FoolCraft aims to reward exploration, the suggestion here is to make Iskallium Ores generate on the Deep Dark too. In order to do that, it's necessary to make Iskallium Ore generation be handled by CoFH, just like every other ore in the pack. The code below can be used. Just put it in another .json inside config/cofh/world. 

```
{
  "populate": {
    "IskalliumOre": {
      "distribution": "uniform",
      "generator": {
        "block": "iskalliumreactors:iskallium_stone_ore",
        "material": "stone",
        "cluster-size": 1
      },
      "chunkChance": 25,
      "cluster-count": 1,
      "min-height": 2,
      "max-height": 16,
      "retrogen": false,
      "biome": "all",
      "dimension": {
        "restriction": "blacklist",
        "value": [
          -1,
          1
        ]
      }
    }
  }
}
```
This will generate Iskallium Ore between layers 2 and 16 of the Deep Dark and Overworld. The only parameter that needs tweaking is **"chunkChance"**. It makes the ore generation happen only once every 25 chunks (something similar to the weight configuration from the iskalliumreactors.cfg). The thing is... Iskallium Ore is actually more rare than that, so a bigger number should be used.

You can compare the generations using the /profile command from Just Enough Resources

**Comment by scalda** [comment]
First 2 points have been addressed and will be in the next pack update thank you.

as for the iskallium i need to hear back from iskall regarding this

**Comment by scalda** [comment]
iskallium deep dark gen won't be added
