### ISSUE TITLE
veinminer not working on server

### ISSUE THREAD

**Issue by lionfirewire** [scalda/FoolCraft#146]
hi i setup a server and it works fine but for some reason veinminer doesnt work also modern warfare doesnt seem to work forgive me if this is addressed some where else

**Comment by scalda** [comment]
Need more information as what you have put doesn't explain anything

**Comment by SirDizarm** [comment]
Sometimes you have to hold "shift" or the correct key a few seconds for it to veinmine, and a few tries to make it do so. The same issue i have with magazines not working together with the gun they are supposed to go with. But its not a big issue so i don't mind.

**Comment by lionfirewire** [comment]
sorry for the lack for the information but i sorta found out what it was ok so the thing is now that i load up the server through a .bat file and none of the mods get loaded but when i run the forge.jar that works it makes everything work on the server veinminer modernwarfare everything so now my question is how do i run the server with a bat file. i want to run the server through the bat file because that is how i add more ram if im not mistaken if there is another way to add 8 gigs of ram id really appreciate the help
