### ISSUE TITLE
Most chests generated in world are empty

### ISSUE THREAD

**Issue by Cat09** [scalda/FoolCraft#148]
Specifically, it seems that all the recurrent complex structures that generate are empty. The town's blacksmith, mill, and inn buildings have loot in them, however the trading post - type structure and almost all the others inside and outside of villages seem to be empty.
Something to do whith these lines?
`# Resource Expression that will be applied to each loading inventory generator, determining if it should be set to 'active'. [default: ]
    S:inventoryGeneratorGenerationMatcher=`
`    # Resource Expression that will be applied to each loading inventory generator, determining if it should be loaded. [default: ]
    S:inventoryGeneratorLoadMatcher=`
is this just an issue on my end?

**Comment by CriticalMole** [comment]
This is on our to do list and will make it into a future update
