### ISSUE TITLE
Can't Install the modpack

### ISSUE THREAD

**Issue by GrekoGrex** [scalda/FoolCraft#15]
Whenever I try to install the pack on curse, an error just shows up, stoping me from dowloading the file.
I hope someone can help me with me this. The error was:
.
"Failed to get mod loader from manifest!"

**Comment by yzimmermann** [comment]
same error here

**Comment by CriticalMole** [comment]
have you relaunched the curse client and tried again?

**Comment by yzimmermann** [comment]
yeah that works now 👍 thanks
