### ISSUE TITLE
Game crashes after launching and while playing

### ISSUE THREAD

**Issue by preflora** [scalda/FoolCraft#151]
I apologize if this isn't the right place to be posting this but this is a repeated problem I am having. After getting to the launcher and clicking 'Play' the game opens and then crashes immediately and has this error message on the screen: [https://pastebin.com/df2vDbDq](url) . I know I have also had problems when trying to play the modpack from the twitch desktop app it says I do not have java installed which is not true so I reinstall it and then it works, maybe this is related? I have been able to fix this problem by reinstalling the whole modpack/minecraft but then the next day it will be crashing at the same place again. Even with the modpack working I also crash randomly when playing, the whole game will freeze and then I have to force quit it. I can try and attach that error message as well if that would be helpful I don't have it at this moment.

**Comment by Jo-Mamma75** [comment]
@preflora ,
Have you resolved this issue already?  If not, have you tried following the steps to setup the instance in MultiMC?

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
