### ISSUE TITLE
Getting Stuck in Sleeping-bag

### ISSUE THREAD

**Issue by irobinson107** [scalda/FoolCraft#157]
5-10% of the time when use sleeping-bag,  getting stuck in Sleeping Screen (Leave Bed).  Cannot Exit, ESC, Teleport, etc.  Have to quit game and reload.

**Comment by hansikul** [comment]
i have the same problem

**Comment by CriticalMole** [comment]
Unfortunately this is a 1.10 bug regarding sleeping, it happens in normal beds aswell and there isnt really anything we can do :(

**Comment by remco082000** [comment]
There is an mod called Bed Bugs, it will allow you to kick yourself from the server (or quit single player world).

**Comment by CriticalMole** [comment]
no need when ftb lets you use /ftb kickme
