### ISSUE TITLE
Game crashes when i look at decocraft items

### ISSUE THREAD

**Issue by hansikul** [scalda/FoolCraft#158]
when i hover my mouse over decocraft items or have them in a storage drawer it crashes my minecraft game, not sure what to do here.
i made a loot bag opener and i stored all the loot in storage drawers so i could sort out what i wanted and didn't want, so some decocraft items got in the storage drawers and crashed my game, thankfully, thankfully! when i reloaded the world the game went back in save so i could get back in again but now i have a full diamond chest with decocraft items i cant even open without crashing........

**Comment by Mrbysco** [comment]
Could you provide a crash log?
That would make it easier for the modpack creators to fix the issue.
Without a log they won't be able to know what's causing the issue

**Comment by hansikul** [comment]
is this correct?
that`s the only thing i could find from todays date.
sorry if its wrong i am just tierd and confused....
[operation_log.txt](https://github.com/scalda/FoolCraft/files/888667/operation_log.txt)

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
