### ISSUE TITLE
[suggestion] add the MmmMmmMmmMmm mod?

### ISSUE THREAD

**Issue by svennieke** [scalda/FoolCraft#159]
i think this mod might be useful to know how much damage your tool does against a mob with or without armor, got the idea beacuse of Docm's latest video where he was wondering how much damage the weaponcase thingy bow did

https://mods.curse.com/mc-mods/minecraft/225738-mmmmmmmmmmmm

**Comment by Jo-Mamma75** [comment]
Taking suggestion under consideration.  Will let you know if approved or declined.
Thanks for the suggestion.

**Comment by scalda** [comment]
Sorry this will not be added.

**Comment by svennieke** [comment]
ok, thanks for telling :D
