### ISSUE TITLE
RANDOM GAME CRASH AND WORLD CORRUPTION AND CAUSING A WINDOWS 10 BSOD

### ISSUE THREAD

**Issue by ajdjyt** [scalda/FoolCraft#162]
Please Help ME ! 
I started up foolcraft this morning at around 10:00 am and i loaded up my world i was watching iskall's latest foolcraft video while it was loading so i was mid the video and then all of a sudden my laptop BlueSOD's and i get an error code that says INVALID_IO_BOOST_STATE right  Im like what the !@$# just happened and my laptop restarts i open up event viewer and i find out the size of my log files is too big so nothing got logged so i don't know what happened but i think Foolcraft caused it and when i load foolcraft back up my world is missing from the list i checked my saves folder and no files in there were missing I think my world got corrupted and i only have a backup of the 28th of march so please help me  and now a days i have been getting texture problems i can play just fine but there are these weird patches like way points on my screen sometimes huge and sometimes small if you could help me recover my world i would highly appreciate it and the log file is down below
[2017-04-02-2.log.gz](https://github.com/scalda/FoolCraft/files/888374/2017-04-02-2.log.gz)
i have been playing for a week without hiccups and i am very outraged please help me 
my laptops specs are
8 GB RAM 1600 Mhz
1 TB HDD
 Intel Core i3-5005-U @ 2.00 GHz - 64 Bit (im Using The Integrated Graphics - Intel 5500)  
And Windows 10 64 Bit Build 1507 (im A bit Behind I hate Updating Windows! MY RAM Got Corrupted  once! while windows was updating)
EDIT: I remember my world got saved yesterday in the backups folder in the foolcraft directory so Im OK But this is a huge error anyways so please fix this in the next update
and Im playing on a laptop Maybe part of the fact
EDIT 2: also i am using a USB mouse plugged into a USB 3.0 port on the side of my laptop so maybe foolcraft tried to grab my mouse while it was lagging and behind the laptops time (see the log files)
so this triggered windows 10's Bug Check Which  Caused Foolcraft OR the Javaw.exe to exit causing my laptop TO BSOD And Restart Which Caused My World To Corrupt.

I guess.

**Comment by Poke1650** [comment]
Can you send the crash log that is a .txt file

**Comment by ajdjyt** [comment]
Look I sent the file in a zip

**Comment by ajdjyt** [comment]
Unzip it in winrar

**Comment by ajdjyt** [comment]
It's the games logs

**Comment by ajdjyt** [comment]
I sent the zip as I started foolcraft again quite a few times again and the latest.txt file was not that of the time when the game crashes and I'm sorry to respond to your so late

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
