### ISSUE TITLE
Can't break blocks

### ISSUE THREAD

**Issue by DraconicSavage** [scalda/FoolCraft#163]
I recently got foolcraft, however when I play in survival I can't break blocks, and in creative when I do they become a ghost block. I doubt the problem is lag, considering I have 6GB of RAM allocated to minecraft. The only thing I've done since downloading the mods is remove some of them, (FakeBlocks,  GooglyEyes, Hemitron, MorePlayerModels, Baconators, RogueLikeDungeons, StorageDrawers and CustomMainMenu). The main thing that comes to my mind that could affect this is VeinMiner, but I'm not sure. If you have a fix, please contact me on discord, my username is DraconicSavage#5720. Thank you!

**Comment by Bolly12321** [comment]
Try reinstalling  all of FoolCraft on Curse and don't remove any mods this time round. Then test breaking blocks again.

**Comment by ajdjyt** [comment]
you removed fatal mods to worlds like fakeblocks

**Comment by scalda** [comment]
@DraconicSavage please try using the full modpack and then report back

**Comment by DraconicSavage** [comment]
I fixed the issue shortly after I had it with some trouble shooting in Iskall's discord server. The problem was that I didn't run it with the curse launcher, I just downloaded every mod that I wanted and there were either some mod config issues or removing a critical mod in this pack. Thanks for the help, though! @scalda @ajdjyt @Bolly12321
