### ISSUE TITLE
Refined storage controller crashes my world

### ISSUE THREAD

**Issue by siredim** [scalda/FoolCraft#164]
Hello,

I have been trying to set up a refined storage in my world, but as soon as i put the controller down in my world, the whole thing freezes and crashes. I can't start my world anymore, because it crashes right away again.

Here is the crash log it gave me:
[crash-2017-04-02_18.44.53-server.txt](https://github.com/scalda/FoolCraft/files/888511/crash-2017-04-02_18.44.53-server.txt)

Question:  how can i make the world load again without crashing?  i would like to continue playing there.

**Comment by ajdjyt** [comment]
use mcedit 2.0

**Comment by scalda** [comment]
thermal expansion energycell crash please report to mod author
