### ISSUE TITLE
TPS Lag Extra Ultilities Transfer Node

### ISSUE THREAD

**Issue by Bolly12321** [scalda/FoolCraft#165]
Hey

The past few days my server has been getting extreme TPS lag (ranging 5-9tps) from the Extra Utilities Transfer Node 'Minecraft::tickTileEntity - XU2:TileTransferHolder'. I am curious if anyone else has been getting this same issue and if there will be a fix in a coming update.

Thanks

Bolly

**Comment by CriticalMole** [comment]
this would be an issue for extra utilities mod, not the modpack

**Comment by scalda** [comment]
What criticalmole said
