### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by jakexrocker** [scalda/FoolCraft#166]
I am missing Thermal Foundation textures, i have tried reinstalling pack, different worlds can't figure out the problem, its not just thermal, there are a couple mods. Don't know what to do.

**Comment by Mrbysco** [comment]
Could you give more information?
What blocks/items? could you show?

**Comment by CriticalMole** [comment]
if you are talking about items you have gotten as loot from lootbags and chest loot, we are aware of the issue and it should be fixed in 1.3

**Comment by jakexrocker** [comment]
Yeah, its mostly with stuff i have gotten out of loot bags, but for instance i can't craft any Thermal Expansion machines, because all the textures are blank, they have names. just not texture.

**Comment by jakexrocker** [comment]
Same with Weapon cases, they are inis too.

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
