### ISSUE TITLE
Game Crash.

### ISSUE THREAD

**Issue by Ibraheem650** [scalda/FoolCraft#167]
Can't play on my main fool craft world,it just crashes and here's the crash log:https://pastebin.com/RfAGw2Bi

**Comment by scalda** [comment]
this is a mech user crash you will need to remove via mcedit. this item is disabled in the next version of the pack

**Comment by mummsword** [comment]
Ok so what item will be available to use to automate use of fluid cows?

**Comment by legodude17** [comment]
I believe it will be Progressive Automation something.
