### ISSUE TITLE
Screenshots are black

### ISSUE THREAD

**Issue by cyrilrbt** [scalda/FoolCraft#168]
I'm running version 1.2.1 of Foolcraft, playing on a server, and all the screenshots I take (in game, with F2) are black. I am running obs multiplatform (latest version), it might be related.

**Comment by Jo-Mamma75** [comment]
Strange. I run it via MultiMC and have no issues taking screenshots but I'm not using OBS either.  Have you tried it without running OBS?

**Comment by cyrilrbt** [comment]
I ran some tests, and once the foolcraft window has been captured by obs, the screenshots are black. I can fix the issue by closing obs and restarting the game. I run minecraft windowed mode, 1600x900, and capture in obs as game capture.

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
