### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by gizmobrat** [scalda/FoolCraft#170]
I have tried a few times to launch FoolCraft but it keeps crashing on: 

The game crashed whilst initializing game
Error: java.lang.OutOfMemoryError: GC overhead limit exceeded 

Edit here is the log:  [crash_log.txt](https://github.com/scalda/FoolCraft/files/891460/crash_log.txt)

**Comment by scalda** [comment]
that means you have run out of ram allocation so please up the amount
