### ISSUE TITLE
extra utils/mech user & entity crash

### ISSUE THREAD

**Issue by Boog84** [scalda/FoolCraft#172]
mechanical user clicking on fluid cow threw my world into a crash loop 

[crash-2017-04-03_18.33.33-server.txt](https://github.com/scalda/FoolCraft/files/891656/crash-2017-04-03_18.33.33-server.txt)

**Comment by Jo-Mamma75** [comment]
It's not the MechUser on the cow that's the problem. Were you by chance standing in front of it when it crashed?  That's generally what's been happening.  Easiest thing to do is change the config file for ExtraUtilites and disable the Mechanical User, start the world back up and then turn it back on.
We have an alternative cow milking solution coming in 1.3 so keep an eye out for that update.

**Comment by Jo-Mamma75** [comment]
Just tested it.  It is because of MCA (Minecraft Comes Alive).  Disabled that mod and the Mechanical User works just fine.
Again though, we have an alternative solution coming in 1.3.

**Comment by Boog84** [comment]
All fixed! Thanks!
