### ISSUE TITLE
[Suggestion] More tweaks.

### ISSUE THREAD

**Issue by Senophoe** [scalda/FoolCraft#174]
**Colossal Chests:**
Change _B:general.analytics_ from true to false.
Change _B:general.versionChecker_ from true to false.

**Code Chicken Core:**
Change _checkUpdates_ from true to false.

**Cyclops Core:**
Change _B:general.analytics_ from true to false.
Change _B:general.versionChecker_ from true to false.

**Inventory Pets:**
Change _B:"Disable All Pet Crafting"_ from false to true. As Iskall said, recipes weren't supposed to be in the modpack. They were meant to be found on clouds, dungeons, and Artifact Lootbags.

**Inventory Tweaks:**
Change _enableConfigLoadedMesssage_ from false to true. This will disable the "InvTweaks config loaded" message on chat after world selection.

**NEI:**
Change _checkUpdates_ from true to false.

**Translocators:**
Change _clientUpdateCheck_ from true to false.

**Comment by scalda** [comment]
thanks this is now implemented
