### ISSUE TITLE
Glitch after respawning

### ISSUE THREAD

**Issue by NeutronDemise** [scalda/FoolCraft#175]
Sometimes and not all the time when I die there are 2 of me and I get teleported back between the two and I can't move. The only way I seem to be able to fix this is to restart my game. I don't have any more information on it and I am sorry about that

**Comment by Cat09** [comment]
this is an odd error... are you using any special launcher that spoofs user names or UUID perhaps? there could be a mod issue wherin something is using the players UUID, and something else is going by player name. just a shot in the dark though.

**Comment by NeutronDemise** [comment]
I used the curse launcher which updated to the twitch launcher if that means anything I haven't died in the modpack after getting supremium armor so I don't know if it happens anymore after the update to twitch

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
