### ISSUE TITLE
Cannot get past loading screen

### ISSUE THREAD

**Issue by tigerblade117** [scalda/FoolCraft#176]
Can't get past the loading screen whatsoever on my friend's computer. It moves so slowly the entire time, and if it even gets to 7/7, it will hang there. It's a 64bit system, running java 8, and it has 4 gigabytes of ram allocated via the curse launcher. We have tried loads of solutions, but nothing has allowed us to play. Please help me. 

Occasionally, the minecraft launcher will get past 50% completion. It doesn't seem to stop at any specific points, but when it does stop, the game stops responding and I am left with no other options but to close the game via task manager.

**Comment by scalda** [comment]
you need to up the amount of ram to either 5.5 or 6 gb

**Comment by Mcshadowdrag** [comment]
this modpack can be played with 2.5gb of ram the problem is with one of the configs, which causes world instability and or corruption

**Comment by tigerblade117** [comment]
@Mcshadowdrag 
Do you know which config this is? We're still having the issue, unfortunately.

**Comment by yahaq** [comment]
here's what i did. i skipped using curse launcher. i copied all the mod files, config files, scripts from the curse foolcraft instance to my minecraft installation folder and launched foolcraft. i can load the world but the fps still sucks. so i removed mods like biome o plenty, moar signs and few others which i am not interested in. i guess i removed around 15 mods, but atleast i can play a lite version of foolcraft now. although my world is not spawning chickens from the chickens mod and i am yet to figure out that part. i have 4 gigs of RAM  on a 64 bit system.

**Comment by ajdjyt** [comment]
You need to allocate 6 Gigs of Ram as the mod version 1.2.2 uses 5.4 Gigs of Ram On my 8GBs of Ram
