### ISSUE TITLE
Server issue? molten_brass registered twice

### ISSUE THREAD

**Issue by GuiltyDragun** [scalda/FoolCraft#177]
I'm trying to set up a server for my friends and I. We are all running the 1.2.2 version of the pack and i updated the server config files, but now no one can connect. 
this is the message we are all getting.
Connection Lost
Internal Exception: java.lang.IllegalArgumentException: The name tconstruct:molten_brass has been registered twice, for Block{null} and Block{tconstruct:molten_brass}.

**Comment by scalda** [comment]
best thing to do is to redo the configs, as nothing was changed in 1.2.2 with the tinkers config

**Comment by GuiltyDragun** [comment]
Thanks for getting back to me so quickly! I dont know what was happening but we all restarted out clients one more time and it started working.

**Comment by scalda** [comment]
ok thanks
