### ISSUE TITLE
Augmentation for Thermal Expansion

### ISSUE THREAD

**Issue by Morphosiz** [scalda/FoolCraft#178]
Is the augmentations for Thermal Expansion available? Because I can't seem to find the augmentation tabs on the machines to put in my augmentations

**Comment by Mrbysco** [comment]
I thought the same thing.
Turns out you need to upgrade your machine in order to unlock augmentation slots.

**Comment by Morphosiz** [comment]
Oh? How do you upgrade them?

**Comment by Mrbysco** [comment]
They are called Upgrade Kits
