### ISSUE TITLE
Cave Stalagmites 

### ISSUE THREAD

**Issue by ThomasGrillo1701** [scalda/FoolCraft#180]
I'm on the latest version of Foolcraft, running a high end PC with Nvidia GTX 970, with Windows 10.
I'm not seeing the stalagmites in any of the caves I've explored. Is this a biome specific feature?

Thanks.

**Comment by Jo-Mamma75** [comment]
You need to set Biomes O' Plenty as the world type.  FoolCraft v1.3 and higher will have that set as the default single player option.

**Comment by ThomasGrillo1701** [comment]
Thanks, I'll be sure to do that.
