### ISSUE TITLE
Ender Dragon drops 2 Dragon Eggs

### ISSUE THREAD

**Issue by janf3** [scalda/FoolCraft#183]
Hello.

is the Ender Dragon supposed to drop 2 Dragon Eggs?

I originally thought it was a cross-mod bug but couldn't reproduce it in any custom instance.
Ultimately I found removing the dragon egg from the custom loot table results in only one Dragon Egg being given. 

Since I'm not too familiar with LootTweaker and custom loot tables I wasn't sure this is intended or not.

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
