### ISSUE TITLE
Textures shaking

### ISSUE THREAD

**Issue by amanzno** [scalda/FoolCraft#184]
After upgrading to the latest version 1.2.2
I entered the game and noticed the blocks that are further away from me shaking
This had already happened when I upgraded from version 1.1 to 1.2
Already tried to open the game with and without optifine.
Have any tips to solve this?

To correct, I started a new game the first time.

**Comment by Mrbysco** [comment]
This is an issue that happened before. And it hasn't gone unnoticed.
Should look something like this: https://www.youtube.com/watch?v=hRtY9-wXnow
and it's known https://twitter.com/ScaldaGaming/status/847201825174507520

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
