### ISSUE TITLE
Blocks are not breaking

### ISSUE THREAD

**Issue by Morphosiz** [scalda/FoolCraft#185]
Hey, just want to check, after the update yesterday, I have been experiencing some issues with Foolcraft. Blocks are not breaking, instead, when you break them, they reappear and only breaks after some time. I have restarted the client, my computer, increased allocation of memory to the game, but none of it has work. Is the issue something to do with my cpu or the pack?

**Comment by Cat09** [comment]
this sounds like server lag, but for it to be specifically after an update is interesting. it's possible there is a specific block that's causing issues after the fact? if you have a game log available, look for something spamming errors.

**Comment by Morphosiz** [comment]
I found the problem, it was a huge pile of xp orbs lying underground. Thanks for the help.
