### ISSUE TITLE
Balance issues

### ISSUE THREAD

**Issue by LittleBunnyRabb** [scalda/FoolCraft#186]
Hey, after playing on the FoolCraft server for a while I noticed some things that were quite unbalanced. Wither farming is quite a popular thing and it can be really OP if its done correctly. The withers drop supremium essence and quite a lot of it... so that removes the need of really looking in to Mystical Agriculture because you can basically skip the whole thing and go straight for the best. I think the drops should still exist but they should be rare like really small chance of getting it. With that supremium essence you can also make tier 5 draconium seeds... and if you automate it it can provide you with a huge amount of draconium so that you can progress in the late game mod really quickly... I also noticed that getting wither heads is also way to easy with the mob grinding mod (dont know the name sry), because you can upgrade it with beheading and if you combine that with lets say wither skeletons and you get yet again a huge amount of head drops. GJ on the mod pack! :)

**Comment by Jo-Mamma75** [comment]
Putting it on the list for 1.3.
Thanks for pointing out how OP it is.

**Comment by Cat09** [comment]
wither farming is a really powerful method in a lot of modpacks, prehaps wither-proof blocks could be harder to get at? While the pack isn't really designed for difficulty, having a nice progression curve is very nice

**Comment by Morphosiz** [comment]
If you want to talk about this way, then the use of chickens for the draconium and awaken draconium is really OP too

**Comment by LittleBunnyRabb** [comment]
Oh don't even start talking about how OP chickens are haha

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
