### ISSUE TITLE
Lexica Botania; 2 versions, larger one inaccessible 

### ISSUE THREAD

**Issue by abrosvii** [scalda/FoolCraft#187]
I noticed there is loads more Botania content in JEI than is described in my Lexica Botania.  The first entry for Lexica Botania only includes 1 school of knowledge, Minecraftian.  The second book has the same crafting recipe and doesn't appear to be acquirable by loot, therefore making the Elven and Relic knowledge inaccessible.

![2017-04-05_12 54 52](https://cloud.githubusercontent.com/assets/26933376/24717367/36e4880e-1a00-11e7-9106-7f5b09133123.png)

If the first entry for Lexica Botania were to be removed in an update it would likely fix this so that the Elven and Relic knowledge can be had for foolcraft players.  I am hoping this can be done.

**Comment by CriticalMole** [comment]
play the mod through by following the intial book, it will guide you through the process which will lead to the second book
