### ISSUE TITLE
Wither Doesn't Drop Nether Star 1.2.2

### ISSUE THREAD

**Issue by MyNameBeMrRandom** [scalda/FoolCraft#189]
As title suggests the wither does not drop the nether star in 1.2.2

**Comment by scalda** [comment]
ok thanks will look into this

**Comment by Jo-Mamma75** [comment]
Cannot reproduce this issue during testing.  Ran 64 Withers and got 64 Stars.
Could be something in your setup.

**Comment by Bennyboy1695** [comment]
I can confirm this is happening to us on version 1.3.2 of the pack.
