### ISSUE TITLE
How do I install the modpack?

### ISSUE THREAD

**Issue by JoostVisser7** [scalda/FoolCraft#19]
Can't find the folder I need to put the stuff in, where is it? (Windows 10)

**Comment by CriticalMole** [comment]
are you using curse?

**Comment by Omegaz00** [comment]
iam using curse and dowloaded the mod  pack but how do i install it ?

**Comment by CriticalMole** [comment]
you dont need to download the pack from the Curse website.
In your Curse Client go to the minecraft section, then browse all modpacks, search for FoolCraft and then hit install, it is really as simple as that

**Comment by Rlemke1101** [comment]
i get a compressed file and then there isnt a .jar file

**Comment by Rlemke1101** [comment]
[FoolCraft-1.1.zip](https://github.com/scalda/FoolCraft/files/856772/FoolCraft-1.1.zip)

**Comment by CriticalMole** [comment]
thats if you go to the website... you need to install via the curse client as described above

**Comment by Rlemke1101** [comment]
oh im sorry i didnt see that. thank you so much
