### ISSUE TITLE
Fattally missing blocks or items

### ISSUE THREAD

**Issue by AustinPin** [scalda/FoolCraft#190]
I cant join my friends on their server, i try to log in and it just says that i am fattally missing blocks or items, i have about 8 gigabites of ram, and a beast computer in itself, anything that i do just makes me leave the game and put that error up.

**Comment by RavenXp** [comment]
did you update your profile from 1.21 to 1.2.2?  Ran into the same issue with my client if there's a disparity between the two, my guess is your friends server is not set up to 1.2.2 yet.

**Comment by scalda** [comment]
you need to make sure the server and client are both on 1.2.2
