### ISSUE TITLE
Water flowing onto Mystical Agriculture crops = crash?

### ISSUE THREAD

**Issue by OmegaX123** [scalda/FoolCraft#191]
I was playing on a server a little bit ago, and attempting to use the 'bucket of water over lava' method to create obsidian for a project. The water flowed onto my field of Mystical Agriculture wheat crops, and the server crashed.

Addendum/correction: Either this is a multiplayer-only issue, or not an issue at all and the server crash was a coincidence. Attempted to repeat the issue in singleplayer, with no success.

**Comment by scalda** [comment]
this is an issue with mca
