### ISSUE TITLE
Suggestion - ComputerCraft

### ISSUE THREAD

**Issue by Lorenzo0404** [scalda/FoolCraft#194]
I suggest ComputerCraft because it makes things easier to control. It also guarantees that potentially dangerous machines can be controlled. Eg- Draconic Evolution Reactor (If not monitored blows up and has a blast diameter of 256 Blocks.

**Comment by Jo-Mamma75** [comment]
Probably not but I'll bring it up in discussion with the DevTeam.  Mostly because, for the purposes of YouTube, ComputerCraft is boring.  Not to say that Iskall or anyone else will say "no" but I wouldn't count on a "yes" either.

**Comment by Jo-Mamma75** [comment]
Asked Iskall about this and he decided against it.
Thanks for the suggestion though.
