### ISSUE TITLE
Can't update the server to 1.2.2

### ISSUE THREAD

**Issue by RavenXp** [scalda/FoolCraft#195]
Every time I copy over the config files to the server and start it up, the server hangs up midway through startup.  Let it sit that way for about 20 minutes before giving up.  Not sure if I messed something up in the paste or there;s a special trick to do it.  I know the server normally takes about 3-5 min to startup and be usable with the 1.2.1 version.  Copy of the console follows.

https://pastebin.com/6wkw9k4V

**Comment by scalda** [comment]
you need to run /fml confirm when it gets to the point it isn't running any more, as you can see from the top of that log it has missing items so you need to confirm with forge that you are willing to go ahead with them missing
