### ISSUE TITLE
Game crash when loading world.

### ISSUE THREAD

**Issue by IAmKedde** [scalda/FoolCraft#196]
I was making a fluid cow farm, and my game crashed after i configured one of the mechanical users to entity and then threw a bucket in there, i might have been standing on top of it and that is probably why its crashing. The mechanical user trying to use a bucket on a player. 
I cant play in that world anymore and that makes me kind of sad, please help.

**Comment by EverlastingLace** [comment]
Literally the same thing happened to me. Placed the mechanical user, added a bucket, started to turn around and the game crashed.  Created a new world, and had no issues loading it. only had 2 mechanical users placed

[crash-2017-04-06_19.24.25-server.txt](https://github.com/scalda/FoolCraft/files/904226/crash-2017-04-06_19.24.25-server.txt)

**Comment by IAmKedde** [comment]
i dont think i could describe my situation any better, that is exactly what happened to me, second mechanical user, but in the bucket turned around and bam! crashed.

**Comment by Cat09** [comment]
take a look at some of the other crash issues, this is a known bug with workarounds to get your game working described in some of those threads.
I'm not sure if there is another way to auto-milk cows, but if there is... it's going to be safer than the mechanical user, since the game crashes every time it tries to use a bucket on a player

**Comment by IAmKedde** [comment]
if its a known bug then why dont they patch it? or would that be too complicated

**Comment by Cat09** [comment]
it is a bug in the extra utilities mod, and the pack creators cannot fix it without disabling the block in the config files, which would definitely be a shame - given how useful it still is. I believe that the mod creator is aware of the issue.

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
