### ISSUE TITLE
Game freezes at the same point on loadup

### ISSUE THREAD

**Issue by Wernt0** [scalda/FoolCraft#199]
Every time I load the pack up, it freezes on the same point
![freeze](https://cloud.githubusercontent.com/assets/26972528/24764119/4d75fd28-1aeb-11e7-8979-2e6694c695a4.png)

I don't know why it is doing this, I have allocated 6GB of RAM to it and have updated it to the latest version and still no fix.

It will be most appreciated if anyone could tell me a fix to this.

**Comment by Cat09** [comment]
a pastebin of any logs from the time you're trying to boot minecraft would be helpful in diagnosing your issue, without them there's not much help that can be given

**Comment by qwsxedcrfv** [comment]
I think I have the same problem. Tried messing with various configs, and copied the files over to the default launcher, but it still doesn't work. Got the pastebin, please let me know what I can do. [https://pastebin.com/qXaHd4H0](url)

**Comment by Jo-Mamma75** [comment]
@Wernt0 
What version of the pack?  What launcher?  How much RAM do you have allocated to the instance?  What steps have you attempted to correct the problem?

**Comment by qwsxedcrfv** [comment]
It happens in all versions, I've tested with anywhere from 4G to 8G, and it hasn't worked. I believe this is the same problem as issue #97

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
