### ISSUE TITLE
VeinMiner

### ISSUE THREAD

**Issue by st3v1sh** [scalda/FoolCraft#2]
VeinMiner isn't working in this version. 

I'm holding the [ ` ] button and breaking the block, but the tree isn't going down. This is the same with stone and dirt. In the videos from the creators, they were able to veinmine stone and wood.

![veinminerbug](https://cloud.githubusercontent.com/assets/26508217/24074359/70995b28-0bdd-11e7-80de-7b6a01117b59.gif)

**Comment by scalda** [comment]
Vein miner is fixed to shift if you want to change it to something else you will need to change the config file to allow this

**Comment by st3v1sh** [comment]
Wow! Thanks for the fast reply. I will try this

**Comment by st3v1sh** [comment]
Thanks, this works. Here's a picture for future references

![image](https://cloud.githubusercontent.com/assets/26508217/24074439/c632cb40-0bde-11e7-899c-6e9959c0f474.png)
