### ISSUE TITLE
Bugs?

### ISSUE THREAD

**Issue by matko000** [scalda/FoolCraft#20]
Trying to put lapis in a compacting drawer, crashes the game. Aluminium does not work properly in compacting drawers (ingots and nuggets fit in one drawer, blocks don't, while blocks go into a compacting drawer, but don't show ingots and nuggets). The coal nuggets/tiny coal does not fit in a compacting drawer with coal.
I am quite sure the problem is not on my end.

**Comment by CriticalMole** [comment]
I cannot reproduce the Lapis problem although I know of similar happening with other blocks in other packs, if you hopper your first item into the drawer it should work fine after that... At least untill a proper fix can be found.
Seems to be that a few recipes have gotten lost somewhere, I have added the fixes for this for the next release.

**Comment by scalda** [comment]
Hi these issues have now been fixed and address thank you for the bug report
