### ISSUE TITLE
Invasive Redwood Duplication

### ISSUE THREAD

**Issue by Abigai1** [scalda/FoolCraft#200]
Hi I planted a single 7x7 redwood "tree" which grew, but also planted more saplings all around itself, which also grow or drop as saplings over water. the single tree has expanded from one 7x7 tree to a 14x30 monster now, the saplings are invading the rest of my grove, and replant themselves faster than I can pick them up myself. I don't want my base destroyed by a redwood monster -- help!!

~ Abigai1

**Comment by CriticalMole** [comment]
vein miner?

**Comment by Abigai1** [comment]
I was not able to vein mine the entire tree - only about 1/3 up the trunk -- I was able to remove all of the base of the tree but not high enough to reach the canopy.  Even after that, saplings were still auto-planting themselves in a radius around the tree faster than I could pick them up -- The situation seeming dire, I decided to log out and unload the chunk until a larger group of us can get on and work together to remove everything.

**Comment by CriticalMole** [comment]
it may be convoulted but the apprach I would take is to build a layer of cobble or another substance that the saplings cannot plant in then vein mine the trees as approrpiate the sapplings should stay on the cobble layer, once cleared then vein mine the cobble

**Comment by Abigai1** [comment]
OK thanks! Recruiting forces for a full scale assault -- hopefully we will record the great battle of the tree...

**Comment by Jo-Mamma75** [comment]
I didn't think we had anything in the pack that would auto-plant saplings.  Do we?  If we do, it may be worthwhile to disable that feature in whatever config file goes with it.

**Comment by Abigai1** [comment]
Hey CriticalMole, One of my team finally got a video posted of the battle against the tree-- the saplings totally plant themselves and multiply. https://youtu.be/8NOMakznEYk?t=149 
This video is cued up at some of the duplication footage. 

In the end the one 7x7 redwood saplings, grew into 8 full redwood trees next to each other. We trashed more saplings and wood than we could count
