### ISSUE TITLE
Mystical Agriculture: Some Ingot Recipes Not Present.

### ISSUE THREAD

**Issue by FatalSociety** [scalda/FoolCraft#201]
As of right now i can't craft; Copper, Lead, Silver, and Steel. Also all the other ones that work craft into thermal foundation ingots; however, tin ingots craft into Railcraft ingots. I know this isn't really a big deal just really annoying when you a have two different types. To note: i do not have all the seeds from Mystical Agriculture; therefor i don't know if there is more then the ones listed above. 

![2017-04-06_18 49 58](https://cloud.githubusercontent.com/assets/26984526/24778744/4ac6fe4c-1afa-11e7-8157-bedd6ffefb2b.png)
![2017-04-06_18 53 35](https://cloud.githubusercontent.com/assets/26984526/24778774/751818fc-1afa-11e7-8b71-20c984957e7a.png)
![2017-04-06_18 53 43](https://cloud.githubusercontent.com/assets/26984526/24778778/763611a8-1afa-11e7-872f-1ccf83f17e0e.png)
![2017-04-06_18 53 52](https://cloud.githubusercontent.com/assets/26984526/24778779/773b35f6-1afa-11e7-9ee9-22a58c19991d.png)
![2017-04-06_18 54 06](https://cloud.githubusercontent.com/assets/26984526/24778782/789e45be-1afa-11e7-8897-736251f821bd.png)

**Comment by CriticalMole** [comment]
This should be fixed in the next update

**Comment by FatalSociety** [comment]
Thank you, 
     
     CriticalMole for your fast response, Your Ghost now has a spot in my great hall of death build:)
