### ISSUE TITLE
Multicraft server can't find .Jar file

### ISSUE THREAD

**Issue by Mangroth** [scalda/FoolCraft#203]
I've recently been attempting to roll my server over to the FoolCraft modpack on my multicraft server hosted through cubedhost. When attempting to restart my server, it is unable to find the .Jar file.

I contacted my server support, and they responded with the following message:

"Unfortunately, due to the way the FoolCraft modpack was put together by the pack authors on Curse, our system has been having trouble downloading the latest update"

I went through the provider's instructions for manually installing the modpack on my server, and downloaded the provided "server files" packet that you offer. It seems that the included Jar files are not capable of getting the server to run foolcraft.

Your help would be appreciated.

Thanks!

**Comment by Jo-Mamma75** [comment]
The 1.2.2 update was a bit rushed.  Hopefully we will have this corrected in 1.3.

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
