### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by matthewas** [scalda/FoolCraft#204]
The game crashed whilst tesselating block in world
Error: java.lang.RuntimeException: No OpenGL context found in the current thread.

**Comment by Cat09** [comment]
A larger section of crash log is going to be needed to be able to figure out what's causing it

**Comment by matthewas** [comment]
I've managed to restore a backup lost a few things but I have my world back so I'm happy. still don't know what the error was. just hope it doesn't happen again.... thanks for the reply tho :)
