### ISSUE TITLE
Illuminati pet stuck at 2:30 since update 1.2.2

### ISSUE THREAD

**Issue by remco082000** [scalda/FoolCraft#205]
Since the 1.2.2 update, the illuminati pet timer has been risen to 5 minutes. But at 2:30 it stops. (See a couple of lines in my game output:
[20:36:35] [Client thread/INFO]: [CHAT] Illuminati Pet is on cooldown. Time remaining 2:30.
[20:36:37] [Client thread/INFO]: [CHAT] Illuminati Pet is on cooldown. Time remaining 2:30.
[20:36:38] [Client thread/INFO]: [CHAT] Illuminati Pet is on cooldown. Time remaining 2:30.
[20:36:40] [Client thread/INFO]: [CHAT] Illuminati Pet is on cooldown. Time remaining 2:30.
It is my favorite pet, so i hope it gets fixed soon. ;)

**Comment by remco082000** [comment]
After lowering the time in the config file to 4 minutes makes it get stuck at 1:30.
So it will always get stuck after 2:30 ?

**Comment by Jo-Mamma75** [comment]
The config file does not seem to want to honor the setting of 5 minutes even though it clearly states that is an acceptable number.  The cool-down needs to be set at a max of 2.5 minutes but not clear on if that is an option or if it has to be a whole number.  For the time being, change your config to 2.5 minutes or less and it should be fine.

**Comment by CriticalMole** [comment]
Will be fixed in 1.3

**Comment by Jo-Mamma75** [comment]
Also addressed issue on Inventory-Pets Github as Issue [#160](https://github.com/capnkirok/Inventory-Pets/issues/160).

**Comment by Jo-Mamma75** [comment]
@remco082000 
Just an update on this issue.  The mod author of Inventory Pets has taken a look at the issue and is planning to resolve it in the next update.

**Comment by remco082000** [comment]
Thanks for helping!
