### ISSUE TITLE
my game crashed after i placed down a mechanical user and configured it.

### ISSUE THREAD

**Issue by hansikul** [scalda/FoolCraft#206]
i placed it down then configured it to `use on entity` (i think thats what its caled) thats when it crashed.

The game crashed whilst ticking block entity
The game crashed whilst ticking block entity
Error: java.lang.RuntimeException: Error while interacting with block minecraft:air with null. Method:ENTITY  Button:RIGHT_CLICK

**Comment by Jo-Mamma75** [comment]
Known issue.  Has to do with MechUser in "Entity" mode and we believe MCA (Minecraft Comes Alive).  The easiest solution is to edit you player data with NBTExplorer and move the players position to get away from the MechUser.  That or disable MechUsers in the ExU2 config file or disable the MCA mod entirely.

**Comment by Jo-Mamma75** [comment]
See response in https://github.com/scalda/FoolCraft/issues/208

Duplicate issue.  Please close.
