### ISSUE TITLE
Crash when putting a thermal expansion energy core next to iskallian reactor

### ISSUE THREAD

**Issue by bloodsbody** [scalda/FoolCraft#207]
The crash occurs when placing a full energy core with the side facing the power tap of the iskallian reactor set to output. Not sure if this is an issue with the modpack or one of the mods being compatible with thew other, but here is the crash report. 
[crash-2017-04-07_18.22.30-server.txt](https://github.com/scalda/FoolCraft/files/907001/crash-2017-04-07_18.22.30-server.txt) (Note version of pack is 1.2.2)

**Comment by Jo-Mamma75** [comment]
It's a known issue.  Winter_Grave is aware of it and has the issue on his Github.  No known solution at this time.

**Comment by legodude17** [comment]
Workaround: use EnderIO Ref zairus/IskalliumReactors#7

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
