### ISSUE TITLE
Block Armor + Storage Drawers

### ISSUE THREAD

**Issue by Tuddis** [scalda/FoolCraft#209]
Block Armor + Storage Drawers don't seams to work together that good
trying to make the "Framing Table" from Storage Drawers mod but it makes a helmet from "Block Armor" mod instead.
any one gotta a solution for it

**Comment by CriticalMole** [comment]
Should be fixed in 1.3

**Comment by Jo-Mamma75** [comment]
As an alternative, you can craft the framing drawer by using two different types of trim blocks.  It won't try to craft the helmet that way.
