### ISSUE TITLE
Wont Launch and Server How To

### ISSUE THREAD

**Issue by EvilDrAaron** [scalda/FoolCraft#21]
Hi, I was wondering two things. First of all, with the new curse/twitch launcher, It says "This app can't run on your pc" How would I run it, with or without curse. Second, I was wondering how to setup a server with FoolCraft. Thank you!

**Comment by yzimmermann** [comment]
also interested in creating a server .. but button "download server" redirects to the wrong files?

**Comment by scalda** [comment]
you need to click on the version you want and the server files are in that

**Comment by yzimmermann** [comment]
Are you sure? In my pack i get 3 files:

overrides
manifest.json
modlist.html

**Comment by scalda** [comment]
click on the name not the download button. and it will bring you to a new page, where when you scroll down abit you will see additional files and the server files are there

**Comment by yzimmermann** [comment]
i look stupid now :D ill try it :)

**Comment by yzimmermann** [comment]
That works! Case closed thanks :)
