### ISSUE TITLE
Blitz, Blizz and Basalz seeds incompatible with agricraft cropsticks

### ISSUE THREAD

**Issue by enmac** [scalda/FoolCraft#210]
Was playing around in creative, noticed these mystical agriculture seeds (Blizz/Blitz/Basalz) are incompatible with agricraft - cannot be planted using crop sticks, no growth options to get them to 10/10/10 ;)

**Comment by CriticalMole** [comment]
Fixed in 1.3

**Comment by Jo-Mamma75** [comment]
Duplicate of [https://github.com/scalda/FoolCraft/issues/132](url)
Leave open until v1.3 is released to public.
