### ISSUE TITLE
Fatally missing blocks and items

### ISSUE THREAD

**Issue by timothydrip** [scalda/FoolCraft#211]
When I try to join a server on 1.10.2 it has the Connection lost error of " Fatally missing blocks and items " 
I have searched up how to fix this and still have no idea.

**Comment by RavenXp** [comment]
Probably a disparity between the foolcraft versions of your client and the server your trying to connect to.  MAke sure which version of foolcraft the server is using then use that version for your client.

**Comment by Jo-Mamma75** [comment]
@timothydrip has this been resolved?

**Comment by EternalDeiwos** [comment]
I'm also running into this. It seems that agricraft-2.0.0-0.7.0 has disappeared off of Curse. Even if I copy it out of the Foolcraft 2.1.1 server files and into my client & server mods directories I get the above error.

**Comment by EternalDeiwos** [comment]
To repeat what I said on twitter: "it would be nice to have server files to see which versions to use".

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda

**Comment by xxlilylolzxx** [comment]
Same but on foolcraft 3. how do i fix it

**Comment by Mrbysco** [comment]
@xxlilylolzxx Stop updating foolcraft before checking if a server updated.
Most likely the server has not updated yet
