### ISSUE TITLE
World keeps crashing...

### ISSUE THREAD

**Issue by FormidableGamer** [scalda/FoolCraft#213]
I tried vein mining out a section for a base so i can store my fluid cows/modded chickens, and when i did, the world crashed and now i cant even open it without it crashing again.. help?
![error](https://cloud.githubusercontent.com/assets/27087062/24831570/dde85316-1c61-11e7-8823-e80a0759fa7e.PNG)

**Comment by Mrbysco** [comment]
A crash log would be nice

**Comment by CakeArmy** [comment]
@Mrbysco Is correct. Were you using mechanical users? Those cause crashes when on entity with a bucket.

**Comment by Jo-Mamma75** [comment]
@FormidableGamer 
Please provide a crash log via [Pastebin](https://pastebin.com/)

**Comment by CakeArmy** [comment]
I'm assuming you did not setup the cow farm yet and crashed just on veinmine? See  issue https://github.com/scalda/FoolCraft/issues/234 when I get a reply from them there it'll most likely have a solution for you too.

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
