### ISSUE TITLE
Can't Place Modded Blocks

### ISSUE THREAD

**Issue by iliketreees** [scalda/FoolCraft#214]
All regular mine craft blocks i can place down like wood and dirt, but when i try like a way stone it disperses into to nothing, I am on a FoolCraft Server to. 

Please help

**Comment by Jo-Mamma75** [comment]
Is this issue only happening to you or does it happen to other players on the server?

**Comment by CakeArmy** [comment]
@iliketreees Was the server running cauldron / whatever the equivalent is today which means you can connect without mods / without appropriate mods? Also, what jo75 said would be useful information, and if you know- are you running an edited version of the pack? is the server running edited version of the pack? @iliketreees

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
