### ISSUE TITLE
10x output for Flatcolored Blocks

### ISSUE THREAD

**Issue by foxanthony1** [scalda/FoolCraft#215]
Tweaked config to give 10x output and make it more Fool friendly. It's tempting to go with 20x, but I'll leave that up to you.

[flatcoloredblocks.cfg](https://hastebin.com/hakuxufusi.css)

**Comment by foxanthony1** [comment]
Duplicate? There isn't another issue, open or closed, that has the term "flatcolored" in it.

**Comment by CriticalMole** [comment]
wrong tag

**Comment by Jo-Mamma75** [comment]
Discussed with Dev Team and decided to deny the request.
Thank you for your suggestion.  We appreciate the feedback.
