### ISSUE TITLE
Grid power bug

### ISSUE THREAD

**Issue by Ignoratio** [scalda/FoolCraft#216]
The first time I set down a culinary generator from EU2 it wouldn't run because it said I needed something like 1500 grid power to run. Upon restarting my world, I had a few thousand Grid Power available. I have no GP generation set up. Upon running the culinary generator with some cucumber salad, my GP used and max numbers rapidly rose to the numbers pictured. To test it, I spawned in an angel ring and some speed upgrades for the culinary generator, and they function with the proper values, and make use of this massively bugged grid power.
![2017-04-08](https://cloud.githubusercontent.com/assets/27098407/24832787/2d028366-1c7d-11e7-9d1b-da8a6d69fd4f.png)
![2017-04-08 1](https://cloud.githubusercontent.com/assets/27098407/24832788/31cf0770-1c7d-11e7-9673-ace92d786e86.png)
![2017-04-08 2](https://cloud.githubusercontent.com/assets/27098407/24832789/36939474-1c7d-11e7-9369-8637fc89e79b.png)
![2017-04-08 3](https://cloud.githubusercontent.com/assets/27098407/24832791/4464e9e0-1c7d-11e7-9af8-10e912152f74.png)

I just tested this in a separate world and found no such issue. I tried to replicate it by running a culinary generator, but had no issue.
![2017-04-08 4](https://cloud.githubusercontent.com/assets/27098407/24832816/d8aa0ffe-1c7d-11e7-8560-c98a6bb085e3.png)

**Comment by Jo-Mamma75** [comment]
Xisuma had the same issue.  You will need NBTEditor to help fix this.    In the player data file there is a section called "ForgeData" then under it is an "XU2" section with an entry for "Frequency".  Remove the entire "XU2" section, go back in-game, break anything that you have producing or using GP and replace them and you should be fine.
There is an issue for this on the ExtraUtilities Github (https://github.com/rwtema/extrautilities/issues/1428) if you want to reference it.  No telling when RWTema and company will get around to addressing it.

**Comment by Vypir** [comment]
Why is this closed? It's still an issue on Single Player worlds.
