### ISSUE TITLE
Crashes Before I Can Play

### ISSUE THREAD

**Issue by GllitchMachine** [scalda/FoolCraft#22]
Everytime I try to play foolcraft it crashes on the mod/forge screen where it loads mods. It usually crashes on the 7th stage(usually between 1-10) I have put 6000 mbs of ram and redownloaded it many times but it keeps crashing. Any help?

**Comment by GllitchMachine** [comment]
Okay, now it also says that after the crash
"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MalisisDoors (malisisdoors)"
Should i delete malisis doors?

**Comment by CriticalMole** [comment]
do you have optifine installed and if so which version?

**Comment by scalda** [comment]
are you on a laptop or desktop?

**Comment by yzimmermann** [comment]
I have a similar problem .. the minecraft screen comes up but if i want to join a world it loads forever and than crashes

**Comment by GllitchMachine** [comment]
desktop

**Comment by GllitchMachine** [comment]
and i have the latest optifine or 1.10.2

**Comment by CriticalMole** [comment]
change to D6 the latest one is buggy with a load of modpacks

**Comment by GllitchMachine** [comment]
i got D6, but now it crashed and it says this
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RFTools (rftools)
I cant view the report

**Comment by GllitchMachine** [comment]
I dont know if optifine will help because it is a pregame problem not ingame

**Comment by GllitchMachine** [comment]
Also, it says i already have a game running when i dont

**Comment by GllitchMachine** [comment]
![game_running](https://cloud.githubusercontent.com/assets/26530467/24170874/528bc934-0e50-11e7-88e4-dfdc81dd3591.png)

**Comment by GllitchMachine** [comment]
If this is a curse issue, since i have also been having problems with other modpacks, should i try manually downloading it and using MultiMC?
