### ISSUE TITLE
Player Data Corrups after Crafting 2 Spicific items

### ISSUE THREAD

**Issue by LlamaMilk** [scalda/FoolCraft#220]
Hey there, i play foolcraft alot and when i was making the haste module from XP-Plus mod everything went actually fine for a while, but then i was making one for a friend of mine on a server and when i had 2 in my inventory my game crashed an my player data got corrupt because i couldn't join the server because i had those items still in my inventory. 
The only solution to fix it and get me on the server again is resetting my player data so i lost all my items waypoint waystone points etc.

I hope you guys can fix this bug Thank you.

**Comment by Jo-Mamma75** [comment]
Sounds like an issue that needs to go on the [XP-Plus Github](https://github.com/Poke1650/XP-Plus/issues)
As far as resetting your player data, it could have probably been saved by editing it with NBTExplorer.

**Comment by Jo-Mamma75** [comment]
@LlamaMilk 
Since you seem to be incapable of posting on the XP-Plus Github, I took the liberty of doing it for you.
https://github.com/Poke1650/XP-Plus/issues/7

**Comment by Jo-Mamma75** [comment]
@LlamaMilk 
According to Poke1650 in https://github.com/Poke1650/XP-Plus/issues/7 this issue should be resolved with version 1.02 of XP-Plus and as such should be fixed in FoolCraft v1.3.
