### ISSUE TITLE
[Bug] Conflicting Recipe: Vanilla Golden Apple - TinyProgressions Golden Apple

### ISSUE THREAD

**Issue by TheonlyTazz** [scalda/FoolCraft#222]
so the TinyProgressions Golden Apple overwrites the Vanilla one

but you need the Vanilla one for FusionCrafting on Draconic Evolution, to add the Basic Upgrades to your items. The TinyProgression Golden Apple doesnt work with that, making it rather hard to upgrade your stuff
as you can only find the Vanilla Golden Apple in Lootbags/dungeons

-Tazz

**Comment by Jo-Mamma75** [comment]
Will be fixed in 1.3 update.  Adding the NoMoreRecipeConflicts mod.

**Comment by Jo-Mamma75** [comment]
Adding additional recipe via Minetweaker to re-enable vanilla golden apple recipe.  Recipe was removed by Tiny Progressions mod.
