### ISSUE TITLE
Ender IO Breaks after using Waystone to teleport between another dimension to an overworld waypoint.

### ISSUE THREAD

**Issue by Bazizanab** [scalda/FoolCraft#223]
This has been happening multiple times: in a singleplayer world, I use Waystones mod to travel to the end, and upon return I will observe multiple occurrences:

- Capacitor banks are instantly drained.
- Conduit lines are broken: no energy/items are transported along the line. When clicking on the arrow part of the conduit connection to an inventory to view its connections, nothing is shown. It only says "Item Conduit connection to: <cardinal direction of the connection. If the inventory is below the conduit, it says "down." If the connection is above the conduit, it says "up.">
- Solar panels become bugged in that they will show their efficiency, but not produce any power.

Quitting to title fixes the issues with solar panels and capacitor banks (no power, but now accepting power.) Conduits now show the outputs and where they can receive items, but they do not recognize any connections on an unedited line. I need to break a conduit to "update" the line.

The picture shows the solar panel being bugged and not generating power, even when the efficiency is 67%.
![2017-04-09_08 33 52](https://cloud.githubusercontent.com/assets/26697907/24837327/fce2b02e-1cff-11e7-985f-db965fbf5ebe.png)

**Comment by SirLong92** [comment]
This is caused by zoneing into a loaded chunk connect to the chunk in which the conduits are in. which causes them to stop working correctly

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
