### ISSUE TITLE
Chicken Glitch

### ISSUE THREAD

**Issue by CBell74** [scalda/FoolCraft#226]
Every time I logout and back on the chickens I have bread reset and end up in pen. losing all progression on them.  Specifically bone chicken/orange chicken. I put them in nesting pen, hatch higher levels and replace. But next time I log in I am back to the 2 base chickens

**Comment by CBell74** [comment]
The seeds I am growing with crop sticks seem to be doing this as well.

**Comment by CriticalMole** [comment]
is this on a server or in a single player world?

**Comment by CBell74** [comment]
Single player.

**Comment by Jo-Mamma75** [comment]
How much free hard drive space do you have?

**Comment by CBell74** [comment]
600 Gig

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
