### ISSUE TITLE
Odd creeper behavior

### ISSUE THREAD

**Issue by bcoov** [scalda/FoolCraft#228]
Since the 1.2.2 version release of Foolcraft, I've started seeing creepers bookin' it across the wilderness. They'll move at a very high speed (about the speed of a player sprint) and completely ignore players. They always seem to be locked onto a specific location off in the distance and do everything they can to reach that spot. The AI seems a little out of whack too as they will occasionally run around in twitchy circles before continuing on their grand quest.

This is on a single player world with only the Foolcraft pack installed. The world file was edited some in MCEdit (I forgot to enable Biomes o' plenty before seeding it), but I don't think that would've caused this behavior.

**Comment by Jo-Mamma75** [comment]
Do you have an Ocelot Pet in your inventory?

**Comment by bcoov** [comment]
I do, but it's not on my active bar which I think it has to be to gain the effect (for example, I don't have nightvision as well). I do LAN games with my wife and she's seen the same behavior without an ocelot pet. We also have a tamed ocelot (cat) inside our base/house set to sit right now, but I've seen the same behavior underground in caves miles away from there (creepers just charging into corners and getting stuck).

**Comment by Jo-Mamma75** [comment]
We've seen similar behavior on the Patron servers.  Two players followed a creeper hauling butt and it went over 2000 blocks toward a player with an Ocelot Pet only to run away from the player once it got there.

**Comment by bcoov** [comment]
Will do. I'll update as soon as I get the chance to check it out.

**Comment by Jo-Mamma75** [comment]
@bcoov 
I just came across this on the mod author's Github while looking for another issue.
https://github.com/capnkirok/Inventory-Pets/issues/91
I'm going to go ahead and close this issue not so much as a "bug" but more of an "unexpected feature".

**Comment by bcoov** [comment]
Oh interesting. Guess the ocelot pet is just a bit more OP than I thought 😛
