### ISSUE TITLE
Not Starting

### ISSUE THREAD

**Issue by Friccadillies** [scalda/FoolCraft#229]
I recently tried opening foolcraft, and it worked fine, but when opening it started loading a 'Entity Renderer' and then crashed. I assigned 4 gigs of memory to it, and tried a newer version, but it always crashes on the entity render.

**Comment by Jo-Mamma75** [comment]
Remove Optifine if you have it and allocate at least 5.5GB of RAM if not 6GB.  It will help tremendously.

**Comment by Friccadillies** [comment]
I was not using optifine, and I allocated 6 gigs to it and it didn't work. Could you point me to a page on allocating more RAM? I may be doing it wrong.

**Comment by Cat09** [comment]
it depends on the launcher you're using, I'm not familiar with the curse launcher, which I assume you're using though. A logfile posted to pastebin might help someone diagnose for you aswell.

**Comment by Friccadillies** [comment]
I am using the curse launcher. When it crashes, it just says: Windows has detected this program has stopped working. Ans then an okay button. It never came up with a change log. I wonder if there is an entity my computer doesnt like, as it crashes at the entity renderer...

**Comment by Jo-Mamma75** [comment]
Right-Click the instance in Curse and go to "View Profile", click the little "..." icon at the top right corner and go to "Profile Options".  Uncheck the box next to "Use System Setting" under the Memory Settings and slide the slider to 6,144MB (or as close as you can get it).  Click the "Okay" button at the bottom and then click the "Back" button in the top left corner and try it again.

**Comment by Friccadillies** [comment]
Interesting, but it still is stopping at entity renderer. :/

**Comment by Friccadillies** [comment]
I tried placing some of the mods into my mods folder, however, it still stopped at entity renderer, so it must be a problem with one of the mods, not the launcher.

**Comment by Friccadillies** [comment]
I wonder if it is a problem with my computer/settings. I tried to play forever stranded and it had the same issue.

**Comment by Cat09** [comment]
I'd recommend trying to find driver updates, for graphics at least. it may also be a good idea to check java version

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
