### ISSUE TITLE
Mining Fatigue, Slowness, hunger and jumpboost effects

### ISSUE THREAD

**Issue by juliouscm** [scalda/FoolCraft#23]
Hi, I tried to install optifine and after restarting the client couldn't get it to load. So I remove it and now I have Mining Fatigue, Slowness, hunger and jumpboost effects active and don't know how to get rid of them. Night vision I think is because of the Ocelot Pet from Inventory Pets.
![2017-03-19_23 23 36](https://cloud.githubusercontent.com/assets/270908/24087937/2e05d5ce-0cfb-11e7-8d77-6ed59ae26a5e.png)

**Comment by scalda** [comment]
either drink milk to clear them, or do the command /effect clear

**Comment by juliouscm** [comment]
Had tried the command and won't let me run it. And just traveled for a while to find a cow and the milk didn't worked either.

![2017-03-20_08 58 20](https://cloud.githubusercontent.com/assets/270908/24100737/e645e80e-0d4b-11e7-96e8-5bfe15a63e96.png)

**Comment by pokeba** [comment]
If you are playing solo, open your world to Lan and enable cheat mode. You should be able to use the command then.

**Comment by juliouscm** [comment]
I ran the command and didn't work either but I decided to kill myself so I put every item from the inventory into the some chest and Hermitrons and found out that it was the Copper Chest Transporters that give you the effect when transporting chests! Thanks for all the help!!!
