### ISSUE TITLE
Absorption Hopper not picking up items

### ISSUE THREAD

**Issue by Together2929** [scalda/FoolCraft#230]
I just crafted a absorption hopper from mob grinding utils and it is not picking up items near it. I have tried breaking it and replacing it and nothing seems to be working.

**Comment by CakeArmy** [comment]
@Together2929 Does it have direct line of sight to the object? Is the inventory of the hopper full?

**Comment by Together2929** [comment]
Yer it does. I have tried throwing items right next to it and they weren't getting picked up. The inventory is also completely empty.

**Comment by ajdjyt** [comment]
Give it an upgrade and check

**Comment by Together2929** [comment]
That didn't work. But Thanks

**Comment by legodude17** [comment]
Try running only mob grinding utils, and if it stills doesn't work report it to mob grinding utils

**Comment by datitisev** [comment]
This happened to me once. Suddenly all Mob Grinding Utils items stopped working for a few irl days. The mob grinder wouldn't inflict any damage to anything.
After a few days, it started working again, but I did nothing to fix it.

**Comment by legodude17** [comment]
May have been an update to the mod?

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
