### ISSUE TITLE
Modern Warfare

### ISSUE THREAD

**Issue by Morphosiz** [scalda/FoolCraft#231]
Hey guys, just want to check, is there any way to get steel dust for the steel ingots required in modern warfare? Tried playing around with the steel ingots from thermal foundation but nothing is working

**Comment by colin500** [comment]
no sadly i private messaged the owner hoping for a response soon...

**Comment by Morphosiz** [comment]
alright! thank you for the initiative!

**Comment by RavenXp** [comment]
Check out Doc's most recent vid, he shows how to get the modern warfare ingots till they fix it in 1.3

**Comment by Morphosiz** [comment]
I tried how he does it, putting steel ingots from thermal foundation into the furnace, nothing happens.
![image](https://cloud.githubusercontent.com/assets/26901937/24858309/5a658072-1e1e-11e7-8585-a5e53f2a187e.png)

**Comment by colin500** [comment]
hmm...is it a vanilla furnace?

**Comment by Morphosiz** [comment]
yes, it is a vanilla furnance

**Comment by colin500** [comment]
reinstall modpack? (backup world!!!)

**Comment by Morphosiz** [comment]
nah, it's fine. I will just wait for the next update, i will work on something else for the time being. Thanks a lot!

**Comment by colin500** [comment]
yep 😄 i hope this works on the kookykraft server because i really want to make ammo for my docannator.

**Comment by Morphosiz** [comment]
ikr, that op gun from doc's loot bag

**Comment by colin500** [comment]
lol are yuo going to leave this open or are you going to closes this?

**Comment by Morphosiz** [comment]
i think i will close it. Thanks for the help guys!
