### ISSUE TITLE
So, about that changelog...

### ISSUE THREAD

**Issue by Cat09** [scalda/FoolCraft#232]
`Changelog`

`HOTFIX: updated stuff and things`

`for servers just replace your current config folder with the folder in this file`

It would be really nice if there was something a little more detailed, I personally would like having all the configs and mod versions on github so that most of the changes were auto-archived. I understand if that's not desirable though

**Comment by TheonlyTazz** [comment]
It's basically only changing loottables and disabling the inventory pets from being craftable

**Comment by chland** [comment]
As I wrote on Reddit, they basically changed the things iskall mentioned in one of his episodes:

- Loot-Recycler no longer accepts cobblestone, planks or logs
- Loot-Bags were changed (Artifact-Bags no longer contain inventory-pets, they were moved to a new bag-type)
- April-Fools pet has been disabled
- Crafting recipes for all pets were disabled
- Inventory Pets should now eat more often !? (not sure)
- Veinminer: Blocklimt reduced to 800 (4172 before), radius reduced to 20 (209 before)
- Iskallium no longer drops from legendary bags but only from (non-craftable) Artifact-Lootbags (which now have a way lower dropchance than before)

**Comment by Jo-Mamma75** [comment]
Cat09,
chland answered the question perfectly.  We were rushed to get the 1.2.2 update out and didn't take the time to write up a proper changelog.  We will try to be more attentive to detail in subsequent updates.
