### ISSUE TITLE
loot bags problems

### ISSUE THREAD

**Issue by colin500** [scalda/FoolCraft#233]
so idk if you can fix this but when using spongeforge lootbags do not drop and chickens in pens do not drop there items except eggs feathers and manure but if you could fix this that would be great heres a little article about how to fix locally maybe you could fix in the modpack you know your stuffz
https://github.com/SpongePowered/SpongeForge/issues/1391

**Comment by Jo-Mamma75** [comment]
I apologize for the delay in getting back to you.  Unfortunately, we have no plans to support Sponge because it is buggy.
