### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by KingHorse2015** [scalda/FoolCraft#235]
Server crashed yesterday for no reason, what could be the problem?
It ended in Killed

https://pastebin.com/ADX311qY

**Comment by CakeArmy** [comment]
@KingHorse2015 I might be missing something but this isn't a server log? Killed would most likely be a message from Forge or Multicraft. Most likely multicraft where the server was not responding or it tried to stop and the server would not shut down. Anyways, can I get a full log?

**Comment by KingHorse2015** [comment]
Sure, but what I shared was the last 4 minutes of the log.
I have seen more messages about out of memory, because I was giving the My servers more ram, then the machine had.

**Comment by KingHorse2015** [comment]
@CakeArmy This is the server log, have xxxx private data. 
[2017-04-09-1.txt](https://github.com/scalda/FoolCraft/files/913648/2017-04-09-1.txt)

**Comment by CakeArmy** [comment]
Click clear log if you are using multicraft.  Just send me the part from
where it has problems, im on my phone so the whole log will be hard for me.

**Comment by KingHorse2015** [comment]
Currently I have added a swap file to my virtual private server, seems to be give it some more breathe room.

**Comment by CakeArmy** [comment]
@KingHorse2015 So its working but unstable? Please tag me so I get an email notification.

**Comment by KingHorse2015** [comment]
@CakeArmy It is working, and stable after adding this swap file. Thanks for the help

**Comment by KingHorse2015** [comment]
@CakeAmy may have to take a look at a mod that auto restarts the server for a memory clear. Still a random crash, because of out of memory.

**Comment by KingHorse2015** [comment]
@CakeArmy Here the Java Crash report: It is a long one....

Generated by java, not from forge.
https://pastebin.com/cyM6gNu1

**Comment by CakeArmy** [comment]
I might be wrong... I used google to translate the amount of ram available from the server into gigabytes (not bit) and I got 0.24232(presumably it continues).
1) Do you not have enough ram installed?

2) Do you have enough ram DEDICATED? 

3) Are you using that ram somewhere else? 

4) 
Uninstall Java
Install from this link: https://www.java.com/en/download/
Make sure the 64bit downloads
I think chrome still has issues with it, so use internet lagplorer or edgy information stealer TM by Microsoft. 

Come back to me with the answers to the questions.

**Comment by KingHorse2015** [comment]
@CakeArmy thanks for the thinking so far

1. Server has a Total of 7,61GB ram + 1Gb swap memory
2. 7gb dedicated to the Mc server
3. Is a ubuntu server with ubuntu desktop installed. Uses only 600 mb of ram
4. Will do that later today

**Comment by CakeArmy** [comment]
@kinghorse carful, not sure if that detects the OS?  Only ever used Debian jessie.

**Comment by CakeArmy** [comment]
Also not sure if it needs Java? That is from a server or client?

**Comment by KingHorse2015** [comment]
@CakeArmy This all from the server I rent in France.
Ovh vps cloud 3

**Comment by CakeArmy** [comment]
Cool.

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
