### ISSUE TITLE
Enderdragon whitelist in woot

### ISSUE THREAD

**Issue by Henri1992** [scalda/FoolCraft#236]
Hello,

When playing on a server, draconic evolution can be bad to work with, if there are like 3 or 4 players looking to kill the dragon, over and over again. Woot has the ability to farm enderdragons, it is a config setting that is used in FTB Beyond, can we get that config setting in FoolCraft? 

The config goes like this: 
# config.Woot:globalAllowEnderDragon
    B:globalAllowEnderDragon=true

It could be that beyond is using a newer version, where it is a thing. But if it can be enabled in foolcraft, will it?

Cheers!

**Comment by Jo-Mamma75** [comment]
Discussed with the rest of the team and we decided against it.
Thank you for suggesting it though.  We appreciate the feedback.
