### ISSUE TITLE
foolcraft server tutorial please

### ISSUE THREAD

**Issue by samtheasianman** [scalda/FoolCraft#238]
I've been trying to make a server for a few days now and I now have no clue what I am doing so if someone could maybe explain in steps or something I'll be really grateful.

**Comment by colin500** [comment]
what server host are you using or is it from your network?

**Comment by RavenXp** [comment]
Well, kinda depoends on your hosting company and how they choose to handle custom .jar files.  example, I use ggservers to host, I had to put the forge libraries and the foolcraft jar files into it's own folder to get it to run.

**Comment by samtheasianman** [comment]
Is there an easier way besides my own network?

**Comment by CakeArmy** [comment]
yes @samtheasianman I recommend using a host, I use TheMinecraftHosting or something like that. If you do use them I have an affiliate link and cake15 for 15% off or something (no sponsor, just really like them and asked for coupon codes to give out). Anyways, if you give me how you want to host it I can either send you a video or detailed instructions.

**Comment by Jo-Mamma75** [comment]
This may help.
http://bfy.tw/nYM
Closing issue.

**Comment by steelbucks** [comment]
@RavenXp Hello,

I happened to see you talking about hosting a FoolCraft server on ggservers? I just bought a server today and couldn't figure out how to set it up. Would you mind showing me how you did it?

Best reguards,
steelbucks
