### ISSUE TITLE
Mechanical User Cow Farm

### ISSUE THREAD

**Issue by CakeArmy** [scalda/FoolCraft#239]
Hai, before I watched iskall's video on NOT making a cow farm with mechanical users, I did so. And there goes my server. Tried using MCEdit but can't figure it out (yes, I did google and watch tutorials to no avail). I'm not sure what to do?

**Comment by ajdjyt** [comment]
MOVE Extrautils2.jar from the mods folder to somewhere else then start foolcraft then load your world ok then replace the block where the mechanical users were and if you had a lot of stuff from extrautilities2 then R.I.P Ok Then close foolcraft then add extrautilities2 back to the mods folder then start foolcraft again and enjoy :)

**Comment by colin500** [comment]
If you need me to i can get on later and Edit it in mcedit where ever you placed the block in MCedit it usually is a black and purple texture but on the bottom it says what it is.

**Comment by Jo-Mamma75** [comment]
Assigned to:  Jo_Mamma75

CakeArmy,
You can more easily edit the "extrautils2.cfg" file located in "\Instances\FoolCraft\config" folder and change the line "B:User=true" to "B:User=false".  This will remove all Mechanical Users from the world as the chunks load.
Let us know if you need any additional assistance.

**Comment by CakeArmy** [comment]
Sweet, works perfectly! Thanks!
