### ISSUE TITLE
Items disappear from crafting bench

### ISSUE THREAD

**Issue by CBell74** [scalda/FoolCraft#24]
Lost some items when exiting from crafting bench
you can see issue at aproximately 11:00 minute mark in video

https://youtu.be/0wj7vDOu6tE

**Comment by scalda** [comment]
Thanks for the report i can reproduce this but not sure on a fix at the moment.

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
