### ISSUE TITLE
How To Open Foolcraft on Mac

### ISSUE THREAD

**Issue by TrainGame** [scalda/FoolCraft#240]
I don't know how to open fool craft.

**Comment by KingHorse2015** [comment]
Install technic launcher -> put this https://www.technicpack.net/modpack/foolcraftoptimze.994508 in de search box -> hit install and enjoy! Current version 1.2.2

**Comment by scalda** [comment]
If you use the technic launcher then you will not get support from us as in turn it has been reported to techic as it was not authorized by us to be posted on there

**Comment by KingHorse2015** [comment]
Understood, Only to make live easy for people on mac an ubuntu. (and windows).

**Comment by CakeArmy** [comment]
@KingHorse2015 you can get curse on Mac, whats the problem? Anyone running Ubuntu should know how to play MC on there anyways...

**Comment by Cat09** [comment]
there is a utility to download a curse modpack's mods based off the config download from curse, you can use that for multiMC

**Comment by jolbol1** [comment]
Just scrolling by this, I'm confused. 

I too use a mac and the Curse (Twitch) launcher is available for mac, and can load Foolcraft, So just use that.

**Comment by datitisev** [comment]
I use the Curse launcher on Mac and it works just fine as well.

**Comment by KingHorse2015** [comment]
I didn't know that curse was also available on mac, because I didn't saw a button for it. 

Still prefer technic :)

**Comment by TheDR80** [comment]
Does curse allow you to save your game? I played earlier and tried to go back on and there was nothing there. I've been trying to install on my pc and it's not working. Can't get the mod to show up once I start the game.

**Comment by Jo-Mamma75** [comment]
Asked and answered a couple of times.  Closing issue.

**Comment by CakeArmy** [comment]
Still stealing other people's work m8.
