### ISSUE TITLE
putting infinity enchantment on weaponcase bows 

### ISSUE THREAD

**Issue by mcvite80** [scalda/FoolCraft#242]
I just put infinity enchantment on a weaponcase bow, pulled the first shot and as soon as I let it fire it crashed my world, tried it a few times after and same thing, tried it again on a different weaponcase bow and same problem. could you please check this, as I've lost both my best bows, guess I'll have to make a tinkers bow after all.

**Comment by WinterGrave** [comment]
This was fixed on version: weaponcaseloot-1.10.2-4.0.3
@scalda please update for next pack version.

**Comment by colin500** [comment]
may i ask how much longer before next update? @WinterGrave I can't wait for the bug fixes :)
thanks,
Colin

**Comment by WinterGrave** [comment]
No idea about the pack update but should be soon, I'll take care to do as much as possible to fix to what my mods concern :D

**Comment by colin500** [comment]
ok thanks :) 
-Colin
