### ISSUE TITLE
Missing cave detail

### ISSUE THREAD

**Issue by ThomasGrillo1701** [scalda/FoolCraft#244]
I'm running latest version Foolcraft. I can not find any stalagmites in caves. I've tried uninstalling, and re-installing Foolcraft 6 times, and still can't find any of the cave detail seen in iskall85's, and other producer's videos.

**Comment by Mrbysco** [comment]
Did you select the BiomesOPlenty worldtype?

**Comment by ThomasGrillo1701** [comment]
Didn't know I had to do that manually. I thought all that was setup automagically. I'll go into the mod list, and see if I can't turn that on. Will advise, later. Thanks.

**Comment by Jo-Mamma75** [comment]
BOP is going to be set as the default setting as of 1.3.
Closing issue.

**Comment by ThomasGrillo1701** [comment]
Ok, thanks for heads up. I see the issue is now closed. Thanks for the assist.

**Comment by Jo-Mamma75** [comment]
Yup.  No problem.  It was also a duplicate issue https://github.com/scalda/FoolCraft/issues/180
I just noticed.
