### ISSUE TITLE
More valid food for Baconators

### ISSUE THREAD

**Issue by chland** [scalda/FoolCraft#245]
Somebody over at Reddit asked if it was possible to add more valid food-items to the Baconators, and I think thats a good idea.

Here is my take on it. Its roughly based on what SkyFactory3 uses but i changed a few things. 

[baconators.cfg.txt](https://github.com/scalda/FoolCraft/files/915963/baconators.cfg.txt)

**Comment by Jo-Mamma75** [comment]
I've already done this and it will be in the 1.3 update.
I will leave this issue open until the update is released.
