### ISSUE TITLE
Inv pets that eat raw meat don't eat raw mutton 

### ISSUE THREAD

**Issue by TimTheDim** [scalda/FoolCraft#246]
I know that it's for the spider pet not sure with other pets that eat raw meat (E.G. cheetah pet)
this doesn't bother me too much but i hope it gets fixed soon 
thanks :D

**Comment by chland** [comment]
It works for the cheetah pet, but I guess thats something that must be reported over at the Inventory-Pets bug-tracker as it can't be fixed by changing the config-files (as far as i can see)

**Comment by Jo-Mamma75** [comment]
Going to close this issue as it belongs on the Inventory-Pets Github.  Please post it [there](https://github.com/capnkirok/Inventory-Pets/issues).
Thank you.
