### ISSUE TITLE
Renaming Hermitrons 

### ISSUE THREAD

**Issue by BirdiePlays** [scalda/FoolCraft#247]
When you rename a hermitron with an anvil, it comes up fine with the name but when you place it down and pick it back up, it loses it's name. This is what happened with shulker boxes in the past. So can you please fix this please. Thank you

**Comment by Jo-Mamma75** [comment]
If you will recall, being able to name items in an anvil and place them was a feature added in 1.11.2 not 1.10.2.  This pack runs on 1.10.2.

It is possible that @WinterGrave may be able to come up with something but no promises.  I'll let him chime in at this point.

**Comment by WinterGrave** [comment]
Done on version 0.2.12, enjoy!
