### ISSUE TITLE
Mod Suggestion: Cosmetic Armor Reworked

### ISSUE THREAD

**Issue by orion74656** [scalda/FoolCraft#248]
A lot of people have been saying that they wished they could turn their armor invisible, kinda like you can do with Botania armor. This mod will give them that ability.

https://mods.curse.com/mc-mods/minecraft/237307-cosmetic-armor-reworked

**Comment by Jo-Mamma75** [comment]
Placed into "for consideration".

**Comment by AlexBarbulescu** [comment]
Would be a nice thing to add for 1.3 :)

**Comment by CakeArmy** [comment]
I believe you can put armor in the painter from enderIO and glass?

**Comment by scalda** [comment]
Sorry this will not be added.
