### ISSUE TITLE
Translocators/colossal chests

### ISSUE THREAD

**Issue by Hoff2567** [scalda/FoolCraft#249]
Moving items into or out of colossal chests with translocators causes MASSIVE (tps drops to less than 1) lag. Seems to be an interaction only between the two though I haven't tried too many other inventories yet. Thinking translocators have issues with multiblocks.

**Comment by CakeArmy** [comment]
@Hoff2567 @Jo-Mamma75 This is not just with translocators. I was using EnderIO conduits with max speed upgrades and sometimes it would take items out, sometimes not. While it would work, it would work for a little while and then stop until I either updated the inventory on the receiving end, the conduit, or the colossal chest. I think this should be submitted to the Colossal chest author though.

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
