### ISSUE TITLE
Can't start up the game after launch

### ISSUE THREAD

**Issue by gustors** [scalda/FoolCraft#25]
It just said this and then crashes:

"Loading - Initializing mods Phase 2
   4/7
Initialization - RFTools
  100/125"

**Comment by scalda** [comment]
have you got a crash report at all?

**Comment by gustors** [comment]
no, non that i can find at the moment. Am trying to find one.

**Comment by gustors** [comment]
It seems the problem has been fixed when i re:installed it. Probably just a file getting corrupt for RFTools
