### ISSUE TITLE
Scalda Help Please

### ISSUE THREAD

**Issue by PEPEISBAE** [scalda/FoolCraft#250]
Hi, i'm trying to make a foolcraft server for me and my friends but i don't know how the ip for the server is and if i need to port forward or not scalda please help me.

**Comment by PEPEISBAE** [comment]
And if i open the forge file there happens nothing.

**Comment by colin500** [comment]
im guessing this is on your network?

**Comment by PEPEISBAE** [comment]
yes it is.

**Comment by colin500** [comment]
ok yes you do need to port forward for this to go outside of your house/network
for the ip ithink it is your ip if you just search on google public ip address i think that is it but im unsure.

**Comment by PEPEISBAE** [comment]
Ok so i need just to open the server and then search for my ip and thats it because the last time that i tried that i didn't work but i shall try

**Comment by colin500** [comment]
What didn't work?

**Comment by Jo-Mamma75** [comment]
@PEPEISBAE 
This may help.
http://bfy.tw/nYM
