### ISSUE TITLE
Moving SP map to MP crashes the server

### ISSUE THREAD

**Issue by AlexBarbulescu** [scalda/FoolCraft#252]
Long story short I tried to move my single player map to multiplayer server and resulted in a server crash when I try to login. Pack version 1.2.2
Crash report https://hastebin.com/qigomezega.sql

**Comment by scalda** [comment]
you need to allocate more ram to your server

**Comment by AlexBarbulescu** [comment]
I seem to have fixed it today, was looking in the log and found this like 

> Caused by: java.lang.NullPointerException
	at com.robrit.moofluids.common.entity.EntityFluidCow.writeSpawnData(EntityFluidCow.java:350)

Moved out of chunk where the fluid Cows were, saved SP map added it to the server, map worked. Went into the chunk were the cows were and it corrupted once again.
One way to fix that either kill the cows or just place them in a animal bag/net and place them again when you are in the chunk.
After chunk unload/load you might stumble upon half the FluidCows to be missing :)

**Comment by scalda** [comment]
`Memory: 595080648 bytes (567 MB) / 2073034752 bytes (1977 MB) up to 3817865216 bytes (3641 MB)`

this line from your log you posted above is saying you are using a max 3.5GB allowed to the MC server

**Comment by AlexBarbulescu** [comment]
well.. don't know, using AMP panel, still posted the fix I did above.
The problem wasn't when I started the server, crash was when I logged onto the server.

**Comment by nonyo22** [comment]
wait did the mod pack and server update

**Comment by ponduzn** [comment]
Im having the same issue it seems:
https://hastebin.com/qijohupuxa.sql

I also moved my world from SP to a MP server. v1.2.2

Tried removing the fluid cows, tanks, and mechanical users, in MCedit, did not help!

Any ideas ?

**Comment by nonyo22** [comment]
wait was the server updated

**Comment by AlexBarbulescu** [comment]
@ponduzn load the map in SP, move far away from the area out of chunk you are currently, save the map, and use it in MP, probably you didn't remove all the cows from were you are currently causing the problem.

**Comment by scalda** [comment]
only other thing to do is remove the moo fluids mod and then restart the server

**Comment by nonyo22** [comment]
wait how did your server crash

**Comment by ponduzn** [comment]
@AlexBarbulescu Thanks for advice! just tried that, and did not help unfortunately, i was able to start the server in mp after i moved my character, but crashed instantly as i went back to my base, checked in SP for fluid cows, none was to be seen anywhere, seems i managed to remove them in MCedit, but maby 1 stray one were stuck\bugged somewhere outside my base, as the server crashed as i was going to explore. However, removing the moo fluid mod as @scalda suggested, worked perfectly. Hope this will be fixed in next update, hopefully! Thanks guys.

**Comment by nonyo22** [comment]
whats the server ip

**Comment by legodude17** [comment]
@nonyo22 none of your comments were helpful. Please stop making those unhelpful comments.

**Comment by nonyo22** [comment]
ok
