### ISSUE TITLE
Foolcraft game crashing, whilst loading

### ISSUE THREAD

**Issue by Vordal** [scalda/FoolCraft#254]
my game of foolcraft crashes whilst trying to load the game, I think it may be because of the ExtraUtilities mechanical user i used for fluid cow farming
[crash-2017-04-13_09.22.49-server.txt](https://github.com/scalda/FoolCraft/files/918848/crash-2017-04-13_09.22.49-server.txt)

thanks for you help in advance

**Comment by TheonlyTazz** [comment]
https://github.com/scalda/FoolCraft/issues/239

**Comment by Jo-Mamma75** [comment]
Thank you @TheonlyTazz for answering @Vordal 
This is a duplicate issue.  Please refer to #239
