### ISSUE TITLE
RandomThings

### ISSUE THREAD

**Issue by chland** [scalda/FoolCraft#255]
While I'm not a big fan of adding too many mods, i guess it would be nice if the RandomThings-mod would be added.

Mostly because of the Entity Detector, the Online Detector and the Item Collectors (stuff like the Nature-Core, the Beans, etc. could probably be disabled).

Especially the Detectors are nice to have as they can be used to toggle stuff depending on where the player is or if he is even online at all.

**Comment by scalda** [comment]
Sorry this is one mod that won't make it into the pack, iskall has already said no to it during development
