### ISSUE TITLE
Mod Suggestion: Malisis blocks

### ISSUE THREAD

**Issue by Hoff2567** [scalda/FoolCraft#256]
https://minecraft.curseforge.com/projects/malisisblocks

Honestly not sure why it's not already in with Malisis doors. Extremely useful blocks both for fun and legitimate builds.

**Comment by Jo-Mamma75** [comment]
I have posted in the Dev Discord for consideration.  Will let you know of the answer.

**Comment by Jo-Mamma75** [comment]
Your suggestion was discussed and we have decided to decline your request.
We thank you for the submission.
