### ISSUE TITLE
Iskallium Reactors Ore Issue

### ISSUE THREAD

**Issue by dxn000** [scalda/FoolCraft#26]
I've been exploring around the world and I don't seem to have any Iskallium. I do find a block that I believe is suppose to be the ore but I have no tip on in and it has white square boarders on the inside, when I mine it nothing happens.

**Comment by Jo-Mamma75** [comment]
That's not the Iskallium Ore.  That's something from ExtraUtils2 and is supposed to drop something like a "Moonstone" or something along those lines.  The Iskallium Ore spawns down around diamond level and is extremely rare.  If you're playing this in single player and want to find it more easily try changing the config file for Iskallium Reactors to increase the spawn rate of the ore.

**Comment by dxn000** [comment]
rgr ty :)
