### ISSUE TITLE
sever ip not working

### ISSUE THREAD

**Issue by nonyo22** [scalda/FoolCraft#262]
i tryed 4 times already but the ip adress 108.166.190.58:25565 will not register as a proper ip. the ip was working fine yesterday so i am very confused if anyone haves a answer to this situation please let me know. i just want to play.

**Comment by legodude17** [comment]
What is the error message?

**Comment by nonyo22** [comment]
java.connectexception: connection refused: no further information

**Comment by legodude17** [comment]
Are you sure you used the right address?

**Comment by nonyo22** [comment]
yes its 108.166.190.58:25565 right

**Comment by legodude17** [comment]
Does the place you are connecting to have a firewall? Do you have a proxy?

**Comment by nonyo22** [comment]
how do i check

**Comment by legodude17** [comment]
Depends on where the server is running.

**Comment by nonyo22** [comment]
what do you mean

**Comment by nonyo22** [comment]
it runns on minecraft right

**Comment by legodude17** [comment]
Like, is it on a computer you own? Or on a minecraft server provider? Or a on a friends computer?

**Comment by Poke1650** [comment]
How is this relevant to Foolcraft?

**Comment by legodude17** [comment]
I was giving them the benefit of the doubt.

**Comment by nonyo22** [comment]
sorry my computer just went though an updated

**Comment by nonyo22** [comment]
its my own computer

**Comment by nonyo22** [comment]
@legodude17

**Comment by Jo-Mamma75** [comment]
Not even remotely close to being our problem and you completely ignored the issue template.

**Comment by nonyo22** [comment]
wait this is a problem i am having and trying to get help on

**Comment by Poke1650** [comment]
@nonyo22 This problem is not caused by Foolcraft. Please contact an administrator of the server you are trying to connect to.
