### ISSUE TITLE
Can't find modded chickens in my worlds

### ISSUE THREAD

**Issue by Cinnamonster** [scalda/FoolCraft#263]
## SUGGESTION/HELP
- [] I would like to propose an additional mod, config change, custom recipe, etc.
- [] I am requesting help with installing or running the pack

## Issue Description
I'm creating a lot of worlds, but there are none of the modded chickens from the mod, Chickens. I find roosters all over the place, but none of the chickens (Flint Chicken, Sand Chicken, Lava Chicken, etc). I checked the config files,  and the chickens all seem to be enabled. There are also no problems with creating and hatching the dyed chickens (bone white, black, etc). The only way I know how to get them is from loot bags, which I will try. But I would still like to know what the issue is so I can fix it.

## Reproduce Steps
1. Create a new world.
2. Search a lot of the locations in the world, including the Nether.
3. Find none of the modded chickens from Chickens.
4. Try another modpack that also has Chickens.
5. Find them easily.

**Comment by legodude17** [comment]
That's odd, I recently found a whole lot of chickens in my world. How far did you search?

**Comment by Cinnamonster** [comment]
Thousands of blocks. Many, many thousands, and through dozens of biomes, both modded and vanilla.

**Comment by legodude17** [comment]
That's really strange. What world type did you use?

**Comment by Cinnamonster** [comment]
Biomes o' Plenty. Gotta have those modded biomes. The people at the FoolCraft server did too, and they found chickens.

**Comment by legodude17** [comment]
Yeah. How about you try a Vanilla world. That is the one I am playing in a and I found plenty of chickens.

**Comment by Cinnamonster** [comment]
I will soon. But I'm still going to keep my fancy BOP world and get the chickens from loot bags. It'll all be fine in the end.

**Comment by legodude17** [comment]
Fun! I wish you good luck.

**Comment by Cinnamonster** [comment]
Thanks! Loot bag generators are pure awesomeness.

**Comment by Jo-Mamma75** [comment]
I've had the best luck finding the chickens in Savanna biomes thus far.  Don't know what to tell you though.
Seems to work fine for loads of other people.

**Comment by kamyu2** [comment]
From looking at the Chickens code, the mod is hardcoded for vanilla biomes only.  They simply cannot spawn in any Biomes O Plenty biome (or any other modded biome).  The author even has an open issue directly saying as much.  But if you can find the elusive vanilla biome in a BOP world, it should have Chickens.
