### ISSUE TITLE
Help Wanted - Technic Launcher

### ISSUE THREAD

**Issue by Wallywalborn** [scalda/FoolCraft#265]
## SUGGESTION/HELP
- [] I would like to propose an additional mod, config change, custom recipe, etc.
- [X] I am requesting help with installing or running the pack

## Issue Description
 When running with the Technic Launcher the forge does not load the mods. Looking through the mods file i do not see Forge listed. What am I doing wrong?

**Comment by legodude17** [comment]
The Technic Launcher version is unofficial and not supported. Please use Curse/Twitch.

**Comment by Wallywalborn** [comment]
I would but I am not sure how to do it through that. I have a Twitch Account but it doesn't really say how to load it. Thank you for the fast response though.

**Comment by Poke1650** [comment]
Download the launcher here: https://mods.curse.com/client and try to connect using a Curse account if Twitch does not work

**Comment by Jo-Mamma75** [comment]
Thanks @Poke1650 
@Wallywalborn , Poke is right. The version on Technic Launcher is unofficial and should not be used.  The pack has been reported to them to be taken down but so far it has not.

**Comment by Wallywalborn** [comment]
Alright I got it working, I appreciate all the help.
