### ISSUE TITLE
Modern Warfare bugs

### ISSUE THREAD

**Issue by AirForce101HD** [scalda/FoolCraft#267]
## SUGGESTION/HELP
- [] I would like to propose an additional mod, config change, custom recipe, etc.
- [] I am requesting help with installing or running the pack

## Issue Description
When I use a gun from Modern Warfare in Creative mod or survival, it comes with message "no magazine" even if I have magazine in my inventory and also pressing "m" for customization does not work.

## Reproduce Steps
Get gun from NEI/JEI or craft it and ammo does not work.

## Additional Information
Screenshots - http://imgur.com/a/zwovl

**Comment by colin500** [comment]
Did you change your keys for reload/have you reloaded the gun?

**Comment by AirForce101HD** [comment]
Reloading and other functions of the mod do not work and I have tried changing the keys.

**Comment by Jo-Mamma75** [comment]
This "should" be resolved in 1.3 of FoolCraft as it contains an update to Modern Warfare that is supposed to address these issues.  I will mark it as resolved for the time being but not close it until we've had time to test it.
