### ISSUE TITLE
I can't open modpacks on my Curse Launcher

### ISSUE THREAD

**Issue by CostDeathYT** [scalda/FoolCraft#268]
<!-->
I have two options that could work for me to play Foolcraft
- Move Foolcraft for Technic Launcher aswell
- Send me the mods folder for Foolcraft and I make an instance at MultiMC

**Comment by scalda** [comment]
Take a look at the wiki for multimc instructions. If you move to technic we
won't support issues

On 14 Apr 2017 12:41, "CostDeathYT" <notifications@github.com> wrote:

I have two options that could work for me to play Foolcraft

   - Move Foolcraft for Technic Launcher aswell
   - Send me the mods folder for Foolcraft and I make an instance at MultiMC

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/scalda/FoolCraft/issues/268>, or mute the thread

**Comment by MinerSass670** [comment]
I have this problem as well. My java crashes every time I try to load Foolcraft or any 1.10 modpack really. Have tried reinstalling and uninstalling java, still nothing. I already posted on the forum about this, but due to me being unactive (sorry) the thread was closed already.

**Comment by TheonlyTazz** [comment]
Did you guys download the x64 version of java? Also allocate enough ram

**Comment by TheonlyTazz** [comment]
Srry for the double post;
But on curses website u can download the modules directly
Foolcraft 1.2.2
https://mods.curse.com/modpacks/minecraft/262803-foolcraft/2402562

**Comment by CostDeathYT** [comment]
TheonlyTazz Yeah I tried that but the mods folder doesn't come with it :/ If anyone could leave the mods folder I would be forever grateful!

**Comment by CostDeathYT** [comment]
Scalda to create a modpack in multimc the mods folder is required

**Comment by scalda** [comment]
Correct, go and read the multimc install guide on the wiki here

**Comment by CostDeathYT** [comment]
I didnt know there was a Foolcraft wiki, how do I access it?

**Comment by CostDeathYT** [comment]
Nvm I dont use github a lot so I got confused, found it! Thanks

**Comment by CostDeathYT** [comment]
https://github.com/scalda/FoolCraft/wiki/MultiMC-Guide
Here's the link for anyone who needs it

**Comment by MinerSass670** [comment]
For me MultiMC didn't work. I'll try to add even more RAM althought I have done it already and reinstall java. I'll let you know if it works or not.

**Comment by MinerSass670** [comment]
Just in case it helps I'll send the crash report.


Problem Event Name:	APPCRASH
  Application Name:	javaw.exe
  Application Version:	8.0.1210.13
  Application Timestamp:	584f5d7e
  Fault Module Name:	StackHash_51bf
  Fault Module Version:	6.1.7601.18798
  Fault Module Timestamp:	5507b864
  Exception Code:	c0000374
  Exception Offset:	00000000000bf922
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1061
  Additional Information 1:	51bf
  Additional Information 2:	51bf0f413302ea864d15886f465722c0
  Additional Information 3:	2971
  Additional Information 4:	2971e9cc7926d31411933c3fe6b5a407

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
