### ISSUE TITLE
Forge is not recognising the mod

### ISSUE THREAD

**Issue by Subblitsz** [scalda/FoolCraft#27]
Hello,

I installed Forge, via the 1.10.2 installer, and then I put the mod into the "mod" folder in /.minecraft but when I go to open Minecraft, in the mods section, I don't see Foolcraft. Been trying to sort this out all day but cannot find a reason as to why it isn't been recognise, please help. I want to play the mod pack :)

**Comment by pokeba** [comment]
Use Curse, it will install everything for you

**Comment by Arkian85** [comment]
What does "use Curse" mean? Having same issuse as Subblitsz... Been using mods off and on for a while, never had any issuses till now.

**Comment by pokeba** [comment]
I was talking about the Curse launcher but it's being rebranded as Twitch App. You can still get it here: https://app.twitch.tv/ and connect using a Curse account. 

Then you'll need to go into setting -> Minecraft and check Mod Management.
After that go in the minecraft tab on the left (It's a creeper face), Browse all modpacks and search Foolcraft, click Install and voila!
