### ISSUE TITLE
Suggestion: Add Recipes for Limestone and Marble

### ISSUE THREAD

**Issue by TheonlyTazz** [scalda/FoolCraft#270]
## SUGGESTION/HELP
- [X] I would like to propose an additional mod, config change, custom recipe, etc.
- [] I am requesting help with installing or running the pack

On our Server we have banned the Quantum Quarry (As the Owner said it causes lag (can someone confirm this?).
for this i have created a custom recipe for both Limestone and Marble as they arent in the Worldgen in the overworld

//Adding Recipes for Limestone and Marble

recipes.addShaped(<chisel:limestone>, [[<minecraft:cobblestone>, <minecraft:sand>], [<minecraft:sand>, <minecraft:cobblestone>]]);
recipes.addShaped(<chisel:limestone>, [[<minecraft:sand>, <minecraft:cobblestone>], [<minecraft:cobblestone>, <minecraft:sand>]]);

recipes.addShaped(<chisel:marble>, [[<minecraft:stone>, <minecraft:stone:3>], [<minecraft:stone:3>, <minecraft:stone>]]);
recipes.addShaped(<chisel:marble>, [[<minecraft:stone:3>, <minecraft:stone>], [<minecraft:stone>, <minecraft:stone:3>]]);

maybe we can consider adding this to the pack for some more building bloks which can only be limited obtained

**Comment by CriticalMole** [comment]
There are Marble and Limestone seeds in mystical agriculture which produce the blocks, the blocks are also in the Trash Bags.
As a result of this we will not be implementing traditional recipes for them
