### ISSUE TITLE
Loading world, buidling terrain problem

### ISSUE THREAD

**Issue by Gongiey** [scalda/FoolCraft#272]
## SUGGESTION/HELP
- [] I would like to propose an additional mod, config change, custom recipe, etc.
- [X] I am requesting help with installing or running the pack

## 1. Load up Foolcraft through the Curse/Twitch laucher
     2. Load up my survival world
     3. Then the problem accures

## Here is the crash log: https://pastebin.com/DFuW27zU
      I also tried to run the world on a server. Here is the crash report for the server: 
      https://pastebin.com/XCmAKzJQ

**Comment by legodude17** [comment]
Try removing all of your enderchests with MCEdit. It appears to be a problem with EnderStorage.

**Comment by Gongiey** [comment]
Would it maybe help to disable to mod entierly?

**Comment by Gongiey** [comment]
I disabled the enderstorage mod, and the world loaded up just fine. Thank you very much legodude17 👍

**Comment by legodude17** [comment]
@Gongiey you are welcome, maybe you could report it on the CBProject github? (https://github.com/TheCBProject/Feedback)

**Comment by Gongiey** [comment]
Yep, will do.

**Comment by CakeArmy** [comment]
@Gongiey As a side note, I would add more ram if you could. You currently have 3GB assigned and it will cause issues as you explore and do more complex machinery.

**Comment by Gongiey** [comment]
Ok, thank you too @CakeArmy. Do you think 5 gb is enough?

**Comment by Jo-Mamma75** [comment]
Asked and answered.  Thank you @legodude17 and @CakeArmy for the assist.
Going to close this issue.  Make sure you post an issue on the Ender Storage Github @Gongiey .
