### ISSUE TITLE
Grid is Overloaded! New to GP

### ISSUE THREAD

**Issue by Br0k3nWings** [scalda/FoolCraft#273]
## SUGGESTION/HELP
- [] I would like to propose an additional mod, config change, custom recipe, etc.
- [] I am requesting help with installing or running the pack

## Issue Description
I had earlier created the Resonator (from Extra Utilties 2) without knowing why. As I learned more about this modpack
 I wanted to make Stoneburnt using the resonator but the device says the GRID IS OVERLOADED. I have no other devices that use GP power. I even created a manual hand mill to power the  resonator but did not succeed. My game (when looking at a GP powered device) is reporting that grid power is at 4872831/15 and NO POWER USED/Generated.
I don't know if it would be helpful to mention that I have only crafted/used power devices from Ender IO and Refined Storage mods.
![2017-04-14_15 13 16](https://cloud.githubusercontent.com/assets/27521372/25057503/5a7944ae-2125-11e7-8aff-a45333c010e9.png)
![2017-04-14_15 13 28](https://cloud.githubusercontent.com/assets/27521372/25057502/5a792744-2125-11e7-9843-9db620aeb9a3.png)

## Reproduce Steps

I find it interesting that in the local player creative world game save I made to learn and test out I do not have this problem. It is only in the local player survival world game save.

**Comment by Br0k3nWings** [comment]
recently I was searching Google for the terms "what does Power Overload do extra utilties", and I found a forum on FTB that offered the solution in a link ...

"Seems something screwed up. I had the same problem. The solution is to go into your world folder and delete/rename the XU2SaveData.dat file.

For instance the path to it: C:\Users<USERNAME>\Documents\Curse\Minecraft\Instances<PACKNAME>\saves<WORLDNAME>\data\XU2SaveData.dat"

URL: https://www.reddit.com/r/feedthebeast/comments/5qvlp0/extra_utilities_2_grid_is_overloaded/

So I tried renaming the .DAT file and it worked. I want to leave this information for anyone else using Foolcraft who might encounter the same issue.

**Comment by kenijey** [comment]
we are still experiencing this issue. why don't you fix this? @RWTema
