### ISSUE TITLE
Refined storage is causing loading issues

### ISSUE THREAD

**Issue by Pr0ti0us** [scalda/FoolCraft#274]
## SUGGESTION/HELP
- [] I would like to propose an additional mod, config change, custom recipe, etc.
- [] I am requesting help with installing or running the pack

## Issue Description
Everything seems to work right until I open my refined storage crafting grid. Once i look in it i see no items and if i leave the crafting grid GUI I'm unable to look in chests or even a work bench. AS well unable to access anything with a GUI such as a sag mill or seed analyser. It also stops the warp stone from opening its warp selections list.

My own theroy atm is that its creating a issue were the game stops loading gui's do to it failing to load up the refined storage correctly.

## Reproduce Steps

load in open refined storage crafting grid

## Additional Information
 no crash report to submit yet

**Comment by CakeArmy** [comment]
@Pr0ti0us How are you storing items? Colossal chest? Do you have stable power? Is your RS system receiving stable power? Try opening the controller and see if it maintains a decent level of RS (RS power)
If you are using colossal chests, is your interface connected to a core or a colossal interface?

**Comment by Pr0ti0us** [comment]
im using a disk array and 64k drives. i havent actualy bothered to hook it up to my big chest yet. as for pwer yes it has stable power its connected to 3 vibrant banks that are in tern connected to solar arrays from, ender io. THe arrays generate more  then enough power to run the system and charge the banks. I realise this seems like over kill but i didnt want it to loose power at night.

**Comment by CakeArmy** [comment]
Not overkill at all @Pr0ti0us 
I am about to load into a single player world to test this right now. Did this happen after placing a specific  item in the system such as a magnet/dislocator that is activated?

**Comment by Pr0ti0us** [comment]
honestly the only thign that i had been doing before this happened was 10/10/10'ing some seeds. So unless crop sticks effect refined storage i cant think of what can of caused this.

**Comment by Pr0ti0us** [comment]
the issue seems to be soley in that world so im not sure what to do. I new world doesnt have the issue with refined storage.  Flying  around im seeing bad chunks like a desert with a ocean biome chunk and vice versa. So im wonderin if its less the issue i thought and more related to world creation.

**Comment by CakeArmy** [comment]
You want to send me the world? If you do send me coordinates to the base and Ill check it out, see what I can find. Tell me if you need help finding the world file. Personally, I would compress the file and send me a dropbox link. No mediafire or money-generating link please :)

**Comment by CakeArmy** [comment]
I haven't found any world-creation issues other than normal but have seen complaints. Normal is chunks not loading until a relog occurs.

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
