### ISSUE TITLE
Can't Relog to my server after changed setting on mechanical user

### ISSUE THREAD

**Issue by Hydrogor** [scalda/FoolCraft#275]
Error: java.lang.RuntimeException: Error while interacting with block minecraft:air with 1xitem.hatchetDiamond@8. Method:ENTITY Button:RIGHT_CLICK

## SUGGESTION/HELP
- [] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

**Comment by CakeArmy** [comment]
Were you standing in front of it?

**Comment by Jo-Mamma75** [comment]
Among known issues with Mechanical User and most likely Minecraft Comes Alive.  Either disable MCA or disable the MechUser (which will be disabled by default in 1.3).
Closing as duplicate.
Thanks again for the assist @CakeArmy  :)
