### ISSUE TITLE
Chicken Bug/Loading Bug

### ISSUE THREAD

**Issue by FuriusEnderKill** [scalda/FoolCraft#276]
I tried to use a chicken I bred to make a powered spawner. I made the powered spawner and the chickens were able to spawn but they were only log, sand, flint, and bone chickens. It wasnt the actual chicken I put in there. :( 
Also when I play for about more than 30 minutes the game has "Hiccups" or freezes for like 5 seconds every 30 seconds. Its annoying. I do have refined storage and I dont kow if that is causing problems?

Help me scalda or someone else... Please

**Comment by legodude17** [comment]
I think the chicken problem would be with the Chickens mod and enderio. For the other problem, do you have an RS system? If so, does it have enough power?

**Comment by CriticalMole** [comment]
to make a powered spawner you are meant to have a soul vial of the animal to combine with the broken spawner, thing is chickens are blacklisted in soul vials so in theory you shouldnt even be able to maake an Ender IO powered spawner

**Comment by Jo-Mamma75** [comment]
@FuriusEnderKill read what @CriticalMole said.
Also, the next time you post in here, leave the template in place and use it.  It's there for a reason not just our own personal amusement.
