### ISSUE TITLE
Server issue: Mod rejections [FMLMod:VeinMiner{0.35.3_1.9-a46c1b0}]

### ISSUE THREAD

**Issue by FrilledFish** [scalda/FoolCraft#277]
## SUGGESTION/HELP
- [] I would like to propose an additional mod, config change, custom recipe, etc.
- [] I am requesting help with installing or running the pack

## Issue Description
After some time, randomly the server decides to begin posting this on connection: "Mod rejections [FMLMod:VeinMiner{0.35.3_1.9-a46c1b0}]". This can be fixed by restarting the server, but it is not a permanent fix as it can randomly start again. The problem can start without anyone on the server.

## Reproduce Steps
Create a server from scratch. Let it run. Join the server.
The time varies greatly between multiple days to just after a restart.

## Additional Information
[20:52:24] NAME lost connection: Mod rejections [FMLMod:VeinMiner{0.35.3_1.9-a46c1b0}]

I am using Sponge on the server
I am using a non-standard config, but it also happens with the one shipped with the server.
Yes, it is a server problem. Nobody can get on the server after the first rejection.

Between 1 player joining the server and 1 player getting the problem when connecting, below is the pastebin:
https://pastebin.com/YdWnWBzQ

I can send you an unedited file, if this doesn't help.

**Comment by FrilledFish** [comment]
I found it on veinminer's github.
https://github.com/portablejim/VeinMiner/issues/95
Seems like it has something to do with the version numbers. Possible fix, delete the + from the both server and client mod files name.

**Comment by Jo-Mamma75** [comment]
Sorry it's something outside of our control.  As @FrilledFish commented, it's a known issue and the more people who complain to PortableJim the more likely he is to fix it.
Closing issue on our end.
