### ISSUE TITLE
Getting stuck in a bed

### ISSUE THREAD

**Issue by Cinnamonster** [scalda/FoolCraft#279]
## SUGGESTION/HELP
- [X] I would like to propose an additional mod, config change, custom recipe, etc.
- [] I am requesting help with installing or running the pack

## Issue Description
Sometimes, when I sleep in a bed, my character suddenly shifts. The "Leave Bed" button no longer works, and I can't press escape to quit the game. The only way to fix the game is to go to my computer's Task Manager and purposefully crash the game. I have downloaded the latest version of 1.10.2 Bed Bugs mod to help resolve this, but tampering with the pack feels wrong, others may have the same issue, and it's probably best that it's an included mod in the pack.

## Reproduce Steps
1. Sleep in a bed.
2. Wait until the process is completed.
3. The perspective shifts and I'm now stuck.
4. Crash the game just to get out of it.

**Comment by CriticalMole** [comment]
it is a 1.10 core bug, your only option really is /ftb kickme
