### ISSUE TITLE
iChisel crashing client

### ISSUE THREAD

**Issue by AlhiraK** [scalda/FoolCraft#28]
It started with me trying to use the iChisel in my Creative testing world.

http://pastebin.com/5575HXCD
http://pastebin.com/PtkbAPHQ

Third time my Creative world crashed then on startup.

http://pastebin.com/eZ1TPTJa

Jumped onto my Survival world in between to check it, everything normal. Back to Survival i can get in. Cleared my inventory and tried normal diamond chisel, works like a charm. iChisel: again crash.

http://pastebin.com/JqUArnqD

**Comment by scalda** [comment]
well this is very strange as the recipe is disabled so how did you get it?
it's disabled for this very reason

**Comment by AlhiraK** [comment]
As i said in Creative mode. Just typed in "chisel" into the inventory search bar.

**Comment by scalda** [comment]
You crash reports are pointing to a rendering issue please remove optifine and try again

**Comment by AlhiraK** [comment]
http://pastebin.com/NK49t5mu

It also crashes without OptiFine. Could there be a general render issue in this pack? I already had it occur twice that i explore my survival world and suddenly chunks stopped loading. I am standing in front of pure white then. Didn´t go that far to test if this is related to OptiFine though.

**Comment by scalda** [comment]
Are you using the ichisel when you get this crash? as the crash is from the gui being open

**Comment by AlhiraK** [comment]
I can´t use it. I have the iChisel in my hotbar and rightclick. The very same second the game crashes. I don´t even see the gui.

**Comment by scalda** [comment]
this is why the recipe for the ichisel is disabled it is a major bug, nothing to do with the mod pack as the recipe is disabled in survival for this very reason. please report to the mod author as it is there bug not ours
