### ISSUE TITLE
Extreme LAG when world is loaded

### ISSUE THREAD

**Issue by BlueScorpionZ** [scalda/FoolCraft#280]
## SUGGESTION/HELP
- [] I would like to propose an additional mod, config change, custom recipe, etc.
- [X] I am requesting help with installing or running the pack

## Issue Description
After the world loads there is major lag. It was running fine then logged in one day and it started.

## Reproduce Steps

Log out and back in same issue. Lowered visual settings, no change. Also created a brand new world just in case and same issue.

## Additional Information

I have 8,192mb of ram allocated.

Please, any help would be greatly appreciated.

**Comment by SteamMonkey** [comment]
when you said you created a brand new world you just made a new world, i.e. nothing built in it, and it lagged when you loaded it up? 

Does the lag not clear up shortly after? World generation and chunk loading with some of the mods in this pack will cause some pretty dramatic lag on some systems. It should clear up after it's finished loading though. 

Also, drop your ram allocation to around 6Gb. If you give it that much, it'll try to use it and it can't, however a memory leak CAN and that will tax your computer quite a bit. You want to float near the magic number that the pack requires and that's just above 5000mb, giving it 6 seemed to be a sweet spot for me, personally.

**Comment by scalda** [comment]
Please install this [mod](https://github.com/nallar/TickProfiler) to allow you to profile the server. please follow this [instructions](https://github.com/nallar/TickProfiler/wiki) to use the correct commands. As this type of crash is something in your world taking a long time to tick which in turn makes the server stop itself
