### ISSUE TITLE
Mystical Agriculture cow seed's don't work with ArgiCraft

### ISSUE THREAD

**Issue by mcvite80** [scalda/FoolCraft#281]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

**Comment by Jo-Mamma75** [comment]
I will test this tonight while trying to finish up the remainder of testing for 1.3.
Thanks for letting us know.

**Comment by Jo-Mamma75** [comment]
Just tested it first thing after my pack loaded and it seems to be fine.  Perhaps try reinstalling the pack.  It's possible the config files and JSON files for Agricraft didn't download correctly.
Closing this issue.
