### ISSUE TITLE
Railcraft Blast Furnace Recipe won't work?

### ISSUE THREAD

**Issue by Navy1227** [scalda/FoolCraft#282]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Whenever I attempt to create a blast furnace block, to create the Blast Furnace multiblock structure, the recipes, as provided by the railcraft wiki, fail to work. There is additionally no recipe to be found on JEI/NEI after doing a search, leading me to believe that the recipe is simply disabled.

## Reproduce Steps
-Place items in to crafting grid in appropriate format
-No results

## Additional Information
https://youtu.be/07lMAeauYMg
**I am new to this pack** so if this is simply disabled for sake of the pack then I apologize for this post, however this is the only true way that I know of how to get steel when Railcraft is involved with the pack. If there is intended to be another way, could someone just inform me of that?

I have checked the server's configuration files to no true avail, the "Factory" module is enabled. I have even cross-checked the config files of Railcraft from this pack with another pack that has it and works on, to no avail there either. 
https://i.gyazo.com/131073eb1900b23e4b74298a621983aa.png

**Comment by Navy1227** [comment]
Is this supposed to be one of the solutions to getting Railcraft Steel? https://youtu.be/DCMXipbpGxc - What do we do if we don't play with Tinker's construct though? Are we forced to use it to get steel?

**Comment by Twonkk** [comment]
Can confirm this issue with server files 1.2.1 single and MP..

**Comment by Jo-Mamma75** [comment]
The Railcraft config files are not honored very well (if at all sometimes).  The mod author has not updated the mod since last November.  I have tried to contact him a couple times about this issue.  A lot of the items in Railcraft have been disabled by the Dev Team.
Closing issue as wontfix because it is something outside of our control.
