### ISSUE TITLE
FoolCraft Initially Loads Bad Chunks

### ISSUE THREAD

**Issue by janagyjr** [scalda/FoolCraft#284]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Incomplete chunk loads is how I can best describe it. It has happened in dimension -1 (the nether) and dimension 0 (Overworld). I first encountered it after a buddy and I went into a nearby dungeon. I was heading home via slime boots and sling when I 'ran into' bad chunks. I was completely glitching (twitching, moving very slowly, etc.). The shape of the chunk was irregular but once free, the chunks would completely unload. I don't know if this is an issue with roguelike dungeons manifesting after completing two and half levels of the dungeon, or something unrelated. 

## Reproduce Steps
Load new world (1.2.2) on a server, run around on it for a few days/weeks, do a dungeon, sling yourself around with the slime sling and boots. I really don't know how to reproduce it, but it is fairly easy to avoid once free of the bad chunks.

**Comment by Jo-Mamma75** [comment]
Happens a lot in modded Minecraft.  I assume it clears up if you log out (or close your game) and then go back into it.

**Comment by CakeArmy** [comment]
@Jo-Mamma75 Is correct. This is with any pack. I am assuming you mean the chunk itself wont load, or will be black. Relog, and if you cannot (because you cant open the pause menu because of teleportation) ask an admin or friend to /kick you from the game, or run /kickme in chat.

**Comment by janagyjr** [comment]
Not really. This is the first time I've encountered this issue in modded minecraft (not that I'm a seasoned pro, <6 months under my belt). I've run DW20's modpack, I've run on packs created by myself and others (my own pack is almost 160 mods), and the only glitch issues I've run into is with anvils (1.7.10 packs) and doors.

If this is a common occurrence though, I'm sorry for bringing it up.

**Comment by CakeArmy** [comment]
Can I get a server log?

**Comment by janagyjr** [comment]
I'll grab it next time it happens.

**Comment by datitisev** [comment]
I was able to fix this in a single player world by just changing the render distance once I was near a bad chunk. They immediately loaded.

**Comment by legodude17** [comment]
Maybe try `F3+a` to reload chunks?

**Comment by datitisev** [comment]
`F3 + A` never personally worked for me, only changing the render distance.

**Comment by CakeArmy** [comment]
Is this resolved? @janagyjr

**Comment by janagyjr** [comment]
Sorry I haven't responded lately, work has been keeping me super busy and I haven't played much in several days. Mark it how you want, if I have further issues I'll reply with an attached server log.

**Comment by CakeArmy** [comment]
Please do. Not a problem. Attach log and timestamps would be awesome

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda

**Comment by Col44446** [comment]
HEY Scalda I am in 1.3 and it still does the bad chunks
