### ISSUE TITLE
Lead essense is unusable

### ISSUE THREAD

**Issue by Peter0507** [scalda/FoolCraft#285]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Well you cant make lead with lead essense or enything for that matter

**Comment by Peter0507** [comment]
i also noticed that steel and copper essence donsen't work either

**Comment by TheonlyTazz** [comment]
Duplicate

https://github.com/scalda/FoolCraft/issues/141
