### ISSUE TITLE
Server struggling recently (server tick took too long)

### ISSUE THREAD

**Issue by CakeArmy** [scalda/FoolCraft#286]
- [ X] I am running the latest version of FoolCraft
- [ X] I am running FoolCraft via Curse/Twitch Launcher
- [ X] I can reproduce this issue consistently
     - [ ] In single player
     - [X ] In multiplayer
- [ X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ X] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [X ] I am requesting help with installing or running the pack

## Issue Description
"server tick took too long" (see pastebin)

## Reproduce Steps
Every hour or so, sometime multiple times in a row occurs. Nothing special happens before/after. 

## Additional Information
https://pastebin.com/yqQkPKnD
I can provide the crash FILE itself, but it essentially is the same thing.

**Comment by CakeArmy** [comment]
This may be a late game lag type of thing although I do not have any farms running, I just use Woot.

**Comment by TheonlyTazz** [comment]
Maybe posting a bigger log would help... Because this can't show information why it's lagging

**Comment by CakeArmy** [comment]
Will do, the whole other part of the log is saying it's behind and mods
posting info but it was all normal and expected info. Will post tomorrow

**Comment by SteamMonkey** [comment]
A few quick tips on things that impact server performance:

Refined Storage systems hooked up to Colossal Chests, especially large colossal chests. This causes an inordinate amount of stress on the server. 

GP updates in force loaded chunks that haven't been properly loaded by a player. Ex: You have a GP network in your chunk loaded base, you log out away from your base and then log back in but do not return to your base. You then do something that changes the status of your GP network. Using an angel ring, running a machine, etc. I haven't figured out exactly how to replicate this 100% of the time, but returning to my base and loading the chunks the 'normal' way (i.e. being there) seems to resolve it when it does happen. Also, it's best to have all of your GP generation in a single chunk if possible. 

Storage Drawers: Massive storage drawer arrays will cause some serious strain when players are near them, but for server strain, large arrays connected to a drawer controller that are being updated rapidly (i.e. theres a lot of items going in and out all the time) appears to cause a lot of strain on server resources. Also, connecting large drawer arrays to RS, specifically with a lot of compacting drawers seems to have an impact as well.

**Comment by scalda** [comment]
Please install this [mod](https://github.com/nallar/TickProfiler) to allow you to profile the server. please follow this [instructions](https://github.com/nallar/TickProfiler/wiki) to use the correct commands. As this type of crash is from something in your world taking a long time to tick which in turn makes the server stop itself
