### ISSUE TITLE
Mystical Agriculture seeds and Ender IO Farming station/Dimensional Transciever

### ISSUE THREAD

**Issue by apsolutions** [scalda/FoolCraft#287]
If raise any 10/10/10 mystical agriculture seed and use the farming station to harvest them you do get 10/10/10 seeds in the inner seeds inventory of the farming station but when the seeds gets send by an Ender IO dimensional transceiver you get 1/1/1 seeds

Edit:
Tried to check where were the seed going back to 1/1/1 and notice that in the farming station's right inventory slots you are getting 1/1/1 seeds

**Comment by CakeArmy** [comment]
I believe there is a special farming station for the magic crops, the original mod, which I belive is compatible with this newer mod. It is not however in the pack. I know this doesn't help you very much... sorry. Not sure what to say? Was this using crop sticks?

**Comment by apsolutions** [comment]
The farming station doesn't seem to be compatible with crop sticks, tried for a minute or two but it didn't replant the seed where the crop sticks are

**Comment by apsolutions** [comment]
Did some more test and when you have a 10/10/10 crop in farmland and you break it with your fist it will give you back a 1/1/1, tried also with agricraft tools but still get 1/1/1, the only way to get back the 10/10/10 seed seems to be using crop sticks

**Comment by SteamMonkey** [comment]
This isn't a bug that'll get fixed here unfortunately. It should be posted to EIO's page. There 'was' an alternative EIO Farming station that worked with cropstick style crops, I'm not entirely sure it's been maintained or brought up to 1.10. I believe the admins are adding a solution for automating crops in the 1.3 version of Foolcraft. Stay tuned.

**Comment by scalda** [comment]
ender io farming station does not work with agricraft, there is a new mod being added in 1.3 that can be used to farm the agricraft crops
