### ISSUE TITLE
FoolCraft Modpack turned into Vanilla

### ISSUE THREAD

**Issue by SlainZai** [scalda/FoolCraft#293]
I'm running FoolCraft Via technic Launcher
I tried the modpack in a single player world and when i check my creative/survival inventory, it's just like vanilla and everything too ( vanilla blocks, mobs, etc,..) . Please help !

**Comment by Jo-Mamma75** [comment]
FoolCraft is not available via the Technic Launcher.  The person who posted it on Technic did so WITHOUT the permission the Pack Developers.  If you want to continue using that launcher, as far as I'm concerned, you are not playing FoolCraft.  If you want help from this Github:
#1  Use the Curse Launcher
#2  Use the Template provided when you create an issue
