### ISSUE TITLE
Crashing at RF tools in loading screen!!

### ISSUE THREAD

**Issue by Wynnecool0070** [scalda/FoolCraft#294]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
Every time i start up the launcher everything goes fine UNTIL it hits RF tools for the second time then it crashes, other people have complained(Additional Information) PS: This always occurs.

## Reproduce Steps
1.Open the launcher
2.Start playing (Normally)
3.Crashes at launcher(RF tools)

## Additional Information
Other people complaining on subredit:
https://www.reddit.com/r/Foolcraft/comments/61ya2i/setup_hangs_on_rftools/

**Comment by CriticalMole** [comment]
Just to get the obvious out of the way, how much RAM have you got assigned to the Pack?

**Comment by Wynnecool0070** [comment]
I have 7gb but that wasn't the problem. got it fixed, turns out it was just a graphics driver error
This fixed it: . http://nvidia.custhelp.com/app/answers/detail/a_id/4378/
thx anyway

**Comment by Jo-Mamma75** [comment]
Closing issue as resolved.
