### ISSUE TITLE
Redstone paste mod

### ISSUE THREAD

**Issue by Mrtenz** [scalda/FoolCraft#295]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I would like to suggest the redstone paste mod by FiberOptic ([Curse](https://minecraft.curseforge.com/projects/redstone-paste)). This would be very useful as an alternative to the Ender IO redstone conduits, since these do not work with all blocks, resturbed mob spawners for example.

**Comment by Jo-Mamma75** [comment]
It's already on the list to be considered.
Thanks for the submission/suggestion.

**Comment by CakeArmy** [comment]
Love this suggestion. Is project red still a thing? I would like more redstone options.

**Comment by scalda** [comment]
Sorry this will not be added.
