### ISSUE TITLE
Cant get to the End in mapmode "The Great wall"

### ISSUE THREAD

**Issue by Roffelsauce** [scalda/FoolCraft#296]
Everything is working fine, well except getting to the end.. I need to get to the end for the quarry, but I cant..

I hope you can add a work around for this because im really enjoying this(your) modpack sofar.
Keep modding!
 
Roffelsauce,

**Comment by Jo-Mamma75** [comment]
So I have a really confused look on my face right now and just muttering "uhhhh.....waht?"
Are you sure you're even posting in the right Github?  And you wiped out the contents of the template form.

**Comment by Roffelsauce** [comment]
I wasnt sure how do use the template sorry..

And yes im 100% sure, Im talking about the worldtype: Great Wall. Its like skyfactory. But then with the foolcraftmods ofc. Like I stated before I cant get to the end, am I overlooking something or is the mod "lacking"?. I hope you understand now.

Kind regards Roffelsauce

**Comment by Pr0ti0us** [comment]
great wall mod setting is a world setting i believe introduced in extra utilites 2. Im actualy under the impression that its not actualy finished.

@Roffelsauce have you tried gm1 and that way if not add in exnihlo mod to your pack and it has the end cake recipe used in skyfactory.

**Comment by Roffelsauce** [comment]
@Pr0ti0us thx so much! I hadnt figured out that it was a extra utilities mod. And yeah it might not be finished, not sure. I am pretty far tho, got myself a full set of draconic armor(via chickens). Tho I got cheats turned off :/ (Otherwise I would take the easy way out) & I tried Exnihlo mod but I couldnt seem to find a 1.10.2 version.. Im talking about the Astris modpack then.(that one contains the end cake)

**Comment by Roffelsauce** [comment]
@Pr0ti0us @Jo-Mamma75 I found Ex Nihilo Omnia, plus the correct download, so its fixed now :) Thankyou both 
Hope you both find alot of diamonds!

**Comment by Jo-Mamma75** [comment]
@Roffelsauce Apologies. Man I had absolutely no idea what you were on about at first.  Yes, if there is something like that happening that has to do with a specific mod in the pack, the best thing to do is to notify us like you did but also go post that issue in the mod's Github.
