### ISSUE TITLE
RFTools Dimensions mod

### ISSUE THREAD

**Issue by ThunderTNT33** [scalda/FoolCraft#299]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I would like to suggest the [RFTools Dimensions Mod](https://mods.curse.com/mc-mods/minecraft/240950-rftools-dimensions). This would be a nice extension for the already included RFTools mod.

**Comment by Jo-Mamma75** [comment]
It was considered during the initial phase of pack development but then decided against.  Although a decent addition to single player world with a responsible player using it, not usually a good idea for multiplayer purposes.  You're more than welcome to add it yourself but we wouldn't be much help in supporting you if you have problems.
Thank you for the suggestion and by all means don't let this discourage you from making future recommendations.  We appreciate the feedback and hearing what the community wants to see in the pack.
