### ISSUE TITLE
Server - World loads in standard minecraft not foolcraft

### ISSUE THREAD

**Issue by webtyphoon** [scalda/FoolCraft#3]
Hi there,
I setup a server and did not change anything inside the server.prop file except the ip and port. Everything workes fine but the world (in foolcraft folder) loads just the normal minecraft content:
- normal vilagers
- no hermitron items in world

also the draconic stuff will not charge up - also when I wear the creative capacitor, its not charging.

Is this problem known?

**Comment by HazDS** [comment]
Hey webtyphoon

I've just started a server from the v1.0 server files and got the below, I'd suggest redownloading the files if things are missing?

http://imgur.com/a/iaHwF

**Comment by webtyphoon** [comment]
Hi HazDS, 
thx for going into this.

Ok, I'll try it later (6-7h) and give feedback.

**Comment by webtyphoon** [comment]
So. DLd the files again and tried it on my computer and on the server. Both generates just a normal minecraft world.

On my computer:
1. DL of the pack
2. eula - true
3. start of minecraft_server.1.10.2.jar
4. Server starts and world will generate in foolcraft folder

On my server I just have to change from minecraft_server.1.10.2.jar to minecraft_server.jar and also change the ip/port in server.properties

Did I forget to change something for this pack?

Cheers,
Steve

**Comment by webtyphoon** [comment]
Something strange:
I started forge-1.10.2-12.18.3.2254-universal.jar on my computer. It loads more files and folders. After intalling all that the server starts and I can play foolcraft local.

I pushed all the files via ftp on my server and tried it with forge-1.10.2-12.18.3.2254-universal.jar name-change to minecraft_server.jar -> the server do not start

but when I just change the mc_server.1.10.2.jar into mc_server.jar (as I done it before) -> server starts but when I join the game it's just vanilla.

**Comment by scalda** [comment]
you need to use the forge jar to run the pack otherwise you will just get vanilla

**Comment by webtyphoon** [comment]
Rock'n'Roll! 
Don't know what my server had yesterday... either it was on saturday night live modus or it was drunk of to much RAM-colada ... 

Thx to pointing me again to the forge jar. Yesterday I saw nothing in the server console but today it loads all the stuff and I can login o_O

Sorry when I claimed ur time and 1000times thx for the help.

Have a relaxed sunday @all,
Steve
