### ISSUE TITLE
Framerate drops

### ISSUE THREAD

**Issue by INTRUDER74** [scalda/FoolCraft#30]
This may be just an issue with my computer, but when I load the pack up, everything is fine, except for when I join a world, my framerate drops every 3 or 4 seconds to zero. It freezes like that for about 4-5 seconds at a time.

 I don't usually have an issue running modpacks of the same or even greater sizes, and I can't really play. Again, it might be my computer, but it's unlikely...

**Comment by Lph369** [comment]
I have the same problem, it makes the modpack un-playable

**Comment by smtdm** [comment]
I have the same problem. i have noticed that minecraft uses around 80% of the dedicated ram memory. And every time the ram-usage drops the game freezes for a couple of seconds. Giving minecraft more ram seems to do nothing, it still uses 80% of it.

**Comment by Subblitsz** [comment]
I'm also having FPS issues, where it freezes every 3-4 seconds, and I have a beastly pc. Also have 16gb ram, so I'm not quite sure why this is happening. :S

**Comment by DBBlueDeath** [comment]
I had the same problem, but managed to fix it: Change the max memory setting in your launcher. I had 4GB by default, changed it to 6GB and the game now runs smoothly instead of the constant hanging. (More technically, change the "-Xmx4096M" parameter to "-Xmx6144M")

**Comment by INTRUDER74** [comment]
Thanks for the help everyone!
