### ISSUE TITLE
Biome's O' Plenty doesn't appear to be working

### ISSUE THREAD

**Issue by DigitalSketch** [scalda/FoolCraft#300]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I'm not having any luck finding any of the "Biome O' Plenty" biomes, or the ores in the mod.  After travelling 10,000+ blocks in a bunch of directions, I put down a builder's block and just had it clear out an area at max size.  It produced no ores from the mod.  I don't see any errors in the crash report.  

## Reproduce Steps
Not sure, just don't see any Biome O' Plenty stuff :)

**Comment by mithrandir13** [comment]
Same for me... turns out I missed that you need to select the BoP world type at the initial world creation screen. Maybe the same for you?

**Comment by DigitalSketch** [comment]
ugh probably

**Comment by DigitalSketch** [comment]
Yup that was it... had no idea!   I'm going to attempt to back it up, delete the rca files I want to try to regen, and change the level.dat file and see if that does anything :)

**Comment by Jo-Mamma75** [comment]
Glad you guys got it resolved.  Thanks for the assist @mithrandir13 .

**Comment by DigitalSketch** [comment]
Yup, thanks!  Resetting the regions gave me the biomes.. still not seeing any of the ores, were they disabled?
