### ISSUE TITLE
Missing recipe ViesCraft

### ISSUE THREAD

**Issue by LittleBunnyRabb** [scalda/FoolCraft#302]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

There is no recipe for the mythic airship frame from ViesCraft.

**Comment by scalda** [comment]
Hi, the recipe is actually disabled in the mod by default, But we have added the item as a level 5 rouge-like dungeon loot

**Comment by LittleBunnyRabb** [comment]
I know now i talked with Jo about it :)
