### ISSUE TITLE
Looking up recipes for items without recipe crashes my game.

### ISSUE THREAD

**Issue by remco082000** [scalda/FoolCraft#303]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When I try to look up the recipe of an item without a recipe in JEI, my game crashes. 
In this crash I tried to look up the recipe of the sheep pet. Also tested with end portal frame, I crashed.

## Reproduce Steps
Left-clicking or pressing R on an item in JEI that doesn't have any recipe.

## Additional Information
Crash Report:
https://pastebin.com/BPaMSXnw

**Comment by legodude17** [comment]
Can you give an example of an item that causes this?

**Comment by remco082000** [comment]
@legodude17 As stated in the post, I tested it with the Chicken Pet and End Portal Frame.

**Comment by Jo-Mamma75** [comment]
I do recall some issues with JEI and crashing.  I believe (don't hold me to it) that has been resolved in the FoolCraft 1.3 update coming out within the next few days (hopefully if our testing goes well).

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda

**Comment by remco082000** [comment]
The problem has been solved. Thanks.
Remco
