### ISSUE TITLE
Crash after world loads

### ISSUE THREAD

**Issue by skye006** [scalda/FoolCraft#304]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
Everytime I load up a world, it works for about 5 seconds but then crashes.

## Reproduce Steps
Create a new world and run it.

## Additional Information
[https://pastebin.com/4HfJy5Jy]

**Comment by legodude17** [comment]
Did you allocate enough RAM to the game?

**Comment by skye006** [comment]
I've got around 8gb allocated i believe

**Comment by Jo-Mamma75** [comment]
Tell me about your system specs.  One of the first things that I find when searching Google for your problem is [this](http://www.minecraftforum.net/forums/support/unmodified-minecraft-client/2627432-1-9-1-10-faqs-read-before-posting).  Does the information there apply to your situation?

**Comment by skye006** [comment]
I've got an Intel(R) Core(TM) i7-4710HQ CPU with 12.0GB of RAM with a 64-bit Operating System. For games I have an additional graphics card, NVIDIA GTX860M, that I run with games, including Minecraft.

**Comment by scalda** [comment]
Since you have a mobile GPU I assume on a laptop, you need to make such that Minecraft is using that GPU and not your internal CPU-GPU. you need to set this in the Nvidia control panel.

Considering this closed as this is not a pack problem but a hardware problem.

**Comment by skye006** [comment]
@scalda although it is not a pack problem are you still able to help me out? it seems to happen with all 1.10.2 packs but is fine when its 1.7.10. As far as i know, I'm running 1.10.2 on my NVIDIA card
