### ISSUE TITLE
forge-1.10.2-12.18.3.2254-universal wont run plz help

### ISSUE THREAD

**Issue by joransyoghurt** [scalda/FoolCraft#305]
I made a foolcraft server on version 1.2 but

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [X ] I am requesting help with installing or running the pack

## Issue Description

when i try to launch forge-1.10.2-12.18.3.2254-universal it wont run, only the spinning loading circle near my mouse appears for a split second (i unpacked the winrar file in my serverfolder)

**Comment by legodude17** [comment]
Where did you download it from?

**Comment by joransyoghurt** [comment]
from here https://minecraft.curseforge.com/projects/foolcraft/files/2397065

**Comment by CakeArmy** [comment]
So you are trying to ru n a server, and it wont run. Okay. Are you booting off the correct jar file? There should be two jars, minecraft_server (or similar) and forge-1.10.2(or similiar). Make sure to boot off the correct one. @joransyoghurt

**Comment by joransyoghurt** [comment]
@yes, the minecraft_server.1.10.2 executable jar file is vanilla and forge-1.10.2-12.18.3.2254-universal executable jar file is the server but i wont start @CakeArmy @legodude17

**Comment by legodude17** [comment]
I meant where did you download the forge file from?

**Comment by joransyoghurt** [comment]
it is included in the winrar file it got from the site i provided earlier @legodude17

**Comment by KingHorse2015** [comment]
@joransyoghurt Windows or Linux?

**Comment by joransyoghurt** [comment]
windows @KingHorse2015

**Comment by KingHorse2015** [comment]
@joransyoghurt Any logs generated? Java process using much cpu and ram in taskmanager?

**Comment by joransyoghurt** [comment]
no, it wont even start @KingHorse2015 double click only makes a loading circle appear for a split second and no logs

**Comment by joransyoghurt** [comment]
how? @scalda

**Comment by KingHorse2015** [comment]
@joransyoghurt right click in expoler -> new -> text document

Paste from scalda

Save as start.bat, other file types selected instead of .txt

**Comment by KingHorse2015** [comment]
@joransyoghurt in the folder where the forge files are :)

**Comment by joransyoghurt** [comment]
ok, i made a tekst doc, with:

title=start

java -server -Xms128M -Xmx6144M -jar forge-1.10.2-12.18.3.2254-universal.jar nogui

pause

and named it:

start.bat

**Comment by KingHorse2015** [comment]
@joransyoghurt double click on it, should popup a black window.

**Comment by joransyoghurt** [comment]
no its still a tekst doc.

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Within the new server files there is a start file.

Regards

Scalda

**Comment by joransyoghurt** [comment]
i searched for the file but i cant find them could you provide a link @scalda

**Comment by CakeArmy** [comment]
Aight. Do you still need a start.bat? I'll link you one...
