### ISSUE TITLE
Background environment flashing 

### ISSUE THREAD

**Issue by Ravalli03** [scalda/FoolCraft#306]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

I'm new to modding world and not sure/can't find information on this if this is a bug of modded minecraft or the pack. 

After playing for about a week now without issues, the world has started a flicker in like the leaf blocks, trees, etc.  It's like they are flashing. It doesn't do it within the few chunks around  the player, just in the distance of 4 to 5 chucks around. I have my memory set to just a bit over 6gb and have plenty of HD space. I don't have much running besides a small RS system, and a few power generators, all under ground. I have gone well over 10k blocks with nothing running and still get the bug. I have also tried changing my settings and didn't help. If this is a known issue, that can be fixed, please let me know.

**Comment by remco082000** [comment]
I think this is an similar post, see #184

**Comment by Ravalli03** [comment]
Repeat post
