### ISSUE TITLE
Crafting Recipe conflict

### ISSUE THREAD

**Issue by lolman2810** [scalda/FoolCraft#307]
## SUGGESTION/HELP
- [x ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Framing bench for storage drawers can not be crafted as oak trim armor from block armor also uses the crafting recipe for helmet

## Reproduce Steps
open jei and +click over required items for framing bench, oak trim helmet is displayed
same in crafting benches/refined storage etc

## Additional Information
although i have seen this reported (unanswered)on reddit, i cant see it here in open or closed issues, so just in case you didnt know
![2017-04-19_22 50 56](https://cloud.githubusercontent.com/assets/27427396/25203843/bb8be392-2552-11e7-805e-b2ee8c328f2b.png)
![2017-04-19_22 50 59](https://cloud.githubusercontent.com/assets/27427396/25203842/bb8b26b4-2552-11e7-8125-446c1e4f04f3.png)

**Comment by TheonlyTazz** [comment]
Duplicate:
https://github.com/scalda/FoolCraft/issues/125

**Comment by KingHorse2015** [comment]
@lolman2810 use two types of trims, in the meantime.
