### ISSUE TITLE
Joy2key incompatible 

### ISSUE THREAD

**Issue by MrScritchy** [scalda/FoolCraft#308]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I am using a nyko air flo ex controller and its native program for button mapping and alternatively joy2key. It worked once and it works with vanilla minecraft, just not with the mod

## Reproduce Steps
Opening my nyko airflo ex (and joy2key;not at the same time) it allows me to control the mouse and all the assigned buttons. Then when opening the mod through twitch it does not allow me to use the controller when the minecraft instance is opened

**Comment by scalda** [comment]
Sorry but this is not something we can help with or willing to help with sorry
