### ISSUE TITLE
Cannot make charged draconium blocks

### ISSUE THREAD

**Issue by GuiltyDragun** [scalda/FoolCraft#310]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I am trying to summon the ender dragon. It requires charged draconium blocks, not awakened draconium blocks. The issue is that i cannot get the charged blocks by putting them into the energy infuser. It will not accept the draconium blocks into its inventory for charging. Am i doing it wrong?

## Reproduce Steps
Trying to put draconium blocks into the energy infuser should not work. The infuser wont accept the blocks into its inventory.

**Comment by legodude17** [comment]
Charged Draconium blocks are not in draconic evolution for 1.10. You can summon the ender dragon with 4 end crystals.

**Comment by GuiltyDragun** [comment]
ah cool tyvm :)
