### ISSUE TITLE
Crashing At RFTools on start up

### ISSUE THREAD

**Issue by IntheRaccon** [scalda/FoolCraft#311]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x] I am requesting help with installing or running the pack

## Issue Description
When loading the Mod pack from the curse launcher I stops and crashes when it is in Initializing mods Phase 2 - Initialization RFTools when i looked at the game output it has a fatal error says "Module JEI did not load due to issue: Mod with modid: jei was not found" 

## Reproduce Steps
All i have done is follow the basic download and play steps.

## Additional Information
https://pastebin.com/e70CXaNT 
has only warnings and error lines

**Comment by legodude17** [comment]
Try redownloading the pack.

**Comment by IntheRaccon** [comment]
Trued redownloading the pack did not work.

**Comment by Jo-Mamma75** [comment]
Yeah, it sounds like for some reason the pack isn't downloading correctly @IntheRaccon .
Best thing to do is to remove the profile from Curse/Twitch, go to your instances folder and make sure it is in fact completely gone and try it again.

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
