### ISSUE TITLE
World Crashes upon loading

### ISSUE THREAD

**Issue by tlarson25** [scalda/FoolCraft#314]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x] I am requesting help with installing or running the pack

## Additional Information
https://pastebin.com/16LPd9kT This is the crash report

**Comment by legodude17** [comment]
This issue appears to be caused by a Loot Bag Opener somehow. Try disabling the mod or removing your lootbag opener(s). If that fixes it, report it to the LootBags mod.

**Comment by Jo-Mamma75** [comment]
A lot of these "ticking block entity" crashes seem to have MCA at the root of the probem.  The crash log doesn't show it but I bet that's ultimately what caused it.  As @legodude17 said, try to MCEdit the world again and remove the block at coords (246,61,364) and you should be good.  Report back if not.

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda
