### ISSUE TITLE
Faulty FTB Util. Claimed Chunks Bug?

### ISSUE THREAD

**Issue by Yofreaky** [scalda/FoolCraft#315]
I'm playing single player and am very grateful for everyone's help on the sleeping issue, a day ago however I just started using a bed pet in the air to instantly turn it to day.

Anyway my new issue is chunk loading, i know none of the block version of the chunk loaders are craftable. I've claimed my base in FTB Utils. (I think is what it's from) and shift clicked to make it chunk load, however it doesn't seem to chunkload even though it says it's a loaded chunk. I noticed when I was skull hunting n the nether with angel wings and fell because of not having gp. (I don't use any extra things that use gp) I also noticed from not getting any mob drops from my spawner or items from my quarry from being away from it. You guys are great and know what you're doing. Any fixes?

**Comment by MrLeKent** [comment]
i have problems with the chunkloading too. only fix i found is to use a "chickenchunk" chunkloader. had to cheat it it in either because the recipe is disabled

**Comment by scalda** [comment]
In the next version 1.3 the ftb chunkloading will be disabled and chicken chunks reenabled
