### ISSUE TITLE
Railcraft Rebar/MCA Needle conflict

### ISSUE THREAD

**Issue by CaptainTransportation** [scalda/FoolCraft#317]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Railcraft rebar has a conflict with MCA's needle.  The recipe is a diagonal string of iron.  There is an alternative, but I think this could be easily fixed in FoolCraft 1.3.0.

## Reproduce Steps
Attempt to craft Railcraft rebar.

**Comment by Jo-Mamma75** [comment]
This should be resolved in 1.3.  NoMoreRecipeConflicts has been added to the pack.
