### ISSUE TITLE
MalisisDoors

### ISSUE THREAD

**Issue by ElectricBlue1** [scalda/FoolCraft#318]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.0.155-universal.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.4.92-universal.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.12.jar)
  IvToolkit (IvToolkit-1.3.2.1-1.10.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.201-universal.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.3.0.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.233-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.1-anarchy.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 4/21/17 5:21 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MalisisDoors (malisisdoors)
Caused by: java.lang.ExceptionInInitializerError
	at net.malisis.doors.MalisisDoors.postInit(MalisisDoors.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:810)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:334)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassCastException: [I cannot be cast to [F
	at net.malisis.core.renderer.font.MinecraftFont.setFields(MinecraftFont.java:91)
	at net.malisis.core.renderer.font.MinecraftFont.<init>(MinecraftFont.java:68)
	at net.malisis.core.renderer.font.MalisisFont.<clinit>(MalisisFont.java:73)
	... 37 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 978710088 bytes (933 MB) / 4039639040 bytes (3852 MB) up to 8351383552 bytes (7964 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8960m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2254 Optifine OptiFine_1.10.2_HD_U_D7 130 mods loaded, 130 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2254.jar) 
	UCHIJ	Forge{12.18.3.2254} [Minecraft Forge] (forge-1.10.2-12.18.3.2254.jar) 
	UCHIJ	ivtoolkit{1.3.2.1-1.10} [IvToolkit] (minecraft.jar) 
	UCHIJ	NotEnoughItems{2.1.3.201} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.201-universal.jar) 
	UCHIJ	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJ	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJ	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.6.233-universal.jar) 
	UCHIJ	infinitylib{1.10.2-0.7.0} [InfinityLib] (infinitylib-0.7.0.jar) 
	UCHIJ	agricraft{2.0.0-0.7.0-a12} [AgriCraft] (agricraft-2.0.0-0.7.0-a12.jar) 
	UCHIJ	JEI{3.14.7.416} [Just Enough Items] (jei_1.10.2-3.14.7.416.jar) 
	UCHIJ	appleskin{1.0.5} [AppleSkin] (AppleSkin-mc1.10.2-1.0.5.jar) 
	UCHIJ	architecturecraft{1.7.1} [ArchitectureCraft] (ArchitectureCraft-1.7.1-mc1.10.2.jar) 
	UCHIJ	Avaritia{1.10.2-2.0.5} [Avaritia] (Avaritia-1.10.2-2.0.5.jar) 
	UCHIJ	avaritiaadditions{1.3} [Avaritia Additions] (avaritiaadditions-1.3.jar) 
	UCHIJ	baconators{3.0.5} [Baconators] (baconators-1.10.2-3.0.5.jar) 
	UCHIJ	MineTweaker3{3.0.16} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.16.jar) 
	UCHIJ	base{1.10.2-1.2.4} [B.A.S.E] (base-1.10.2-1.2.4.jar) 
	UCHIJ	Baubles{1.3.9} [Baubles] (Baubles-1.10.2-1.3.9.jar) 
	UCHIJ	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar) 
	UCHIJ	BiomesOPlenty{5.0.0.2162} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2162-universal.jar) 
	UCHIJ	blockarmor{2.3} [Block Armor] (BlockArmor-1.10.2-2.3.jar) 
	UCHIJ	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UCHIJ	CodeChickenLib{2.5.6.233} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.6.233-universal.jar) 
	UCHIJ	cofhcore{4.1.0} [CoFH Core] (CoFHCore-1.10.2-4.1.0.155-universal.jar) 
	UCHIJ	brandonscore{2.1.4} [Brandon's Core] (BrandonsCore-1.10.2-2.1.4.92-universal.jar) 
	UCHIJ	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJ	chancecubes{1.10.2-2.3.4.171} [Chance Cubes] (ChanceCubes-1.10.2-2.3.4.171.jar) 
	UCHIJ	ChestTransporter{2.5.9} [Chest Transporter] (ChestTransporter-1.10.2-2.5.9.jar) 
	UCHIJ	CodeChickenCore{2.4.0.101} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.101-universal.jar) 
	UCHIJ	ChickenChunks{2.2.0.52} [ChickenChunks] (ChickenChunks-1.10.2-2.2.0.52-universal.jar) 
	UCHIJ	chickens{4.3.2} [Chickens] (chickens-4.3.2.jar) 
	UCHIJ	chisel{MC1.10.2-0.0.8.12} [Chisel] (Chisel-MC1.10.2-0.0.8.12.jar) 
	UCHIJ	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UCHIJ	chiselsandbits{12.12} [Chisels & Bits] (chiselsandbits-12.12.jar) 
	UCHIJ	clumps{1.0.5} [Clumps] (Clumps-1.0.5.jar) 
	UCHIJ	cyclopscore{0.9.3} [Cyclops Core] (CyclopsCore-1.9.4-0.9.3.jar) 
	UCHIJ	colossalchests{1.5.0} [Colossal Chests] (ColossalChests-1.10.2-1.5.0.jar) 
	UCHIJ	one_point_twelve_concrete{v 1.0} [1.12 Concrete] (concreteMod-v1.0.jar) 
	UCHIJ	cookingforblockheads{4.2.39} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.39.jar) 
	UCHIJ	craftingtweaks{6.1.16} [Crafting Tweaks] (CraftingTweaks_1.10.2-6.1.16.jar) 
	UCHIJ	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.16.jar) 
	UCHIJ	cropdusting{0.6} [CropDusting] (CropDusting-0.6-[1.9.4-1.10-1.10.2].jar) 
	UCHIJ	CustomMainMenu{2.0.2} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.2.jar) 
	UCHIJ	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJ	props{2.3.6.1} [Decocraft] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJ	draconicevolution{2.0.8} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.8.177-universal.jar) 
	UCHIJ	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	UCHIJ	embers{0.104} [Embers] (embers-0.104.jar) 
	UCHIJ	endercore{1.10.2-0.4.1.65-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.65-beta.jar) 
	UCHIJ	Waila{1.8.11-B25_1.10.2} [Waila] (Hwyla-1.8.11-B25_1.10.2.jar) 
	UCHIJ	EnderIO{1.10.2-3.1.179} [Ender IO] (EnderIO-1.10.2-3.1.179.jar) 
	UCHIJ	EnderStorage{2.2.1.103} [EnderStorage] (EnderStorage-1.10.2-2.2.1.103-universal.jar) 
	UCHIJ	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UCHIJ	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.3.3.jar) 
	UCHIJ	fakeblocks{1.0.0} [FakeBlocks] (FakeBlocks 1.0.0.jar) 
	UCHIJ	FastLeaveDecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.3.jar) 
	UCHIJ	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCHIJ	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.1-anarchy.jar) 
	UCHIJ	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.4.4.jar) 
	UCHIJ	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.4.3.jar) 
	UCHIJ	googlyeyes{6.0.0} [GooglyEyes] (GooglyEyes-1.10.2-6.0.0.jar) 
	UCHIJ	gravestone{1.5.12} [Gravestone] (GraveStone Mod 1.5.12.jar) 
	UCHIJ	hatchery{0.2.10} [Hatchery] (hatchery-1.10.2-0.2.10.jar) 
	UCHIJ	hermitron{0.2.10} [Hermitron] (hermitron-1.10.2-0.2.10.jar) 
	UCHIJ	ichunutil{6.1.1} [iChunUtil] (iChunUtil-1.10.2-6.1.1.jar) 
	UCHIJ	InventoryPets{1.4.9} [Inventory Pets] (inventorypets-1.10-1.4.9.jar) 
	UCHIJ	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJ	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJ	iskalliumreactors{0.3.7-beta} [Iskallium Reactors] (iskalliumreactors-1.10.2-0.3.7-beta.jar) 
	UCHIJ	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
	UCHIJ	loottweaker{0.0.4} [LootTweaker] (LootTweaker-1.10.2-0.0.4.jar) 
	UCHIJ	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJ	lootbags{2.3.2} [Loot Bags] (LootBags-1.10.2-2.3.2.jar) 
	UCHIJ	malisiscore{1.10.2-4.3.0} [MalisisCore] (malisiscore-1.10.2-4.3.0.jar) 
	UCHIE	malisisdoors{1.10.2-5.2.0} [MalisisDoors] (malisisdoors-1.10.2-5.2.0.jar) 
	UCHIJ	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJ	RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
	UCHIJ	MCA{1.10.2-5.2.3} [Minecraft Comes Alive] (MCA-1.10.2-5.2.3-universal.jar) 
	UCHIJ	mtrm{1.2.1.20} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.10.2-1.2.1.20.jar) 
	UCHIJ	natura{1.10.2-4.1.0.24} [Natura] (natura-1.10.2-4.1.0.24.jar) 
	UCHIJ	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCHIJ	tconstruct{1.10.2-2.6.3.500} [Tinkers' Construct] (TConstruct-1.10.2-2.6.3.jar) 
	UCHIJ	moarsigns{4.2.2.8} [MoarSigns] (MoarSigns-1.10.2-4.2.2.8.jar) 
	UCHIJ	mobdismemberment{6.0.0} [MobDismemberment] (MobDismemberment-1.10.2-6.0.0.jar) 
	UCHIJ	mob_grinding_utils{0.1.8.16} [mob_grinding_utils] (MobGrindingUtils-0.1.8.16.jar) 
	UCHIJ	examplemod{1.0} [Example Mod] (Modifiable-Armor-2-1.10.2-2.0.2.jar) 
	UCHIJ	modifiable_armor{2.0.2} [Modifiable Armor 2] (Modifiable-Armor-2-1.10.2-2.0.2.jar) 
	UCHIJ	mtlib{@VERSION@} [MTLib] (MTLib-1.0.1.jar) 
	UCHIJ	modtweaker{2.0.10} [Mod Tweaker] (ModTweaker2-2.0.10.jar) 
	UCHIJ	morechickens{1.0.11} [More Chickens] (MoreChickens-1.10.2-1.0.11.jar) 
	UCHIJ	moreloottables{0.2.1} [More Loot Tables] (moreloottables-1.10.2-0.2.1.jar) 
	UCHIJ	moreplayermodels{1.10.2} [MorePlayerModels] (MorePlayerModels_1.10.2(11nov16).jar) 
	UCHIJ	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UCHIJ	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.10.2.jar) 
	UCHIJ	mw{1.8.1} [Modern Warfare] (mw-1.8.1_mc1.10.2.jar) 
	UCHIJ	mysticalagriculture{1.4.4} [Mystical Agriculture] (mysticalagriculture[1.10.2]-1.4.4a.jar) 
	UCHIJ	nethercore{1.10.2-2.0.3} [Nether Core] (nethercore-1.10.2-2.0.3.jar) 
	UCHIJ	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJ	thermalfoundation{2.0.3} [Thermal Foundation] (ThermalFoundation-1.10.2-2.0.3.77-universal.jar) 
	UCHIJ	plustic{3.1} [PlusTiC] (plustic-3.1.jar) 
	UCHIJ	reccomplex{1.2.9.1-1.10} [Recurrent Complex] (RecurrentComplex-1.2.9.1-1.10.jar) 
	UCHIJ	StorageDrawers{1.10.2-3.6.1} [Storage Drawers] (StorageDrawers-1.10.2-3.6.1.jar) 
	UCHIJ	refinedstorage{1.2.24} [Refined Storage] (refinedstorage-1.2.24.jar) 
	UCHIJ	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	UCHIJ	rftools{5.88} [RFTools] (rftools-1.1x-5.88.jar) 
	UCHIJ	roguelike{1.5.9} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.9.jar) 
	UCHIJ	shadowmc{3.6.1} [ShadowMC] (ShadowMC-1.10.2-3.6.1.jar) 
	UCHIJ	SimpleLabels{0.0.1} [SimpleLabels] (simplelabels-1-10.2-0.0.3.jar) 
	UCHIJ	simplyconveyors{1.4.1} [Simply Conveyors] (SimplyConveyors-1.4.2.jar) 
	UCHIJ	SleepingBag{1.4.0} [Sleeping Bag] (SleepingBag-1.10.2-1.4.0.jar) 
	UCHIJ	subcommonlib{1.1.3.0} [Subaraki's Common Library] (sublib-1.10.2-1.1.3.0.jar) 
	UCHIJ	thermalexpansion{5.0.3} [Thermal Expansion] (ThermalExpansion-1.10.2-5.0.3.86-universal.jar) 
	UCHIJ	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJ	tp{1.1.0} [Tiny Progressions] (tinyprogressions-1.10.2-1.1.0.jar) 
	UCHIJ	torchmaster{1.0} [TorchMaster] (torchmaster_1.10.2-1.1.1.14.jar) 
	UCHIJ	Translocator{2.1.3.52} [Translocator] (Translocators-1.10.2-2.1.3.52-universal.jar) 
	UCHIJ	usefulnullifiers{1.3.4} [Useful Nullifiers] (usefulnullifiers-1.3.4.jar) 
	UCHIJ	VeinMiner{0.35.3_1.9-a46c1b0} [Vein Miner] (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) 
	UCHIJ	VeinMinerModSupport{0.35.3_1.9-a46c1b0} [Mod Support] (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) 
	UCHIJ	vc{4.24.0} [ViesCraft] (ViesCraft-1.10.X-4.24.0.jar) 
	UCHIJ	wailafeatures{0.3.1.13} [WAILA Features] (WAILA-features-1.10.2-0.3.1.13.jar) 
	UCHIJ	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJ	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.213.jar) 
	UCHIJ	wawla{2.3.1.213} [What Are We Looking At] (Wawla-1.10.2-2.3.1.213.jar) 
	UCHIJ	waystones{2.0.12} [Waystones] (Waystones_1.10.2-2.0.12.jar) 
	UCHIJ	weaponcaseloot{4.0.2} [WeaponCaseLoot] (weaponcaseloot-1.10.2-4.0.2.jar) 
	UCHIJ	Woot{1.10.2-1.2.6} [Woot] (woot-1.10.2-1.2.6.jar) 
	UCHIJ	xpplus{1.0} [XP-Plus] (xpplus-1.01.jar) 
	UCHIJ	moofluids{1.10.2-1.7.02.12b} [Moo Fluids] (MooFluids-1.10.2-1.7.02.12b.jar) 
	Loaded coremods (and transformers): 
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.0.155-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
Brandon's Core (BrandonsCore-1.10.2-2.1.4.92-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.12.jar)
  team.chisel.common.asm.ChiselTransformer
IvToolkit (IvToolkit-1.3.2.1-1.10.jar)
  
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.201-universal.jar)
  codechicken.nei.asm.NEITransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
MalisisCorePlugin (malisiscore-1.10.2-4.3.0.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.233-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.1-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4459' Renderer: 'Intel(R) HD Graphics'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	NotEnoughItems Invalid Fingerprint Reports: 
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	ChickenChunks Invalid Fingerprint Reports: 
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                  * An unsupportted RF API is installed (1.7.10R1.3.1 from (guessing) jar:file:/C:/Users/phili/Documents/Curse/Minecraft/Instances/FoolCraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/CoFHAPIProps.class).
                    Ender IO needs at least 1.4.0 and will NOT work with older versions.
                  * Our API got loaded from MoarSigns-1.10.2-4.2.2.8.jar. That's unexpected.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/phili/Documents/Curse/Minecraft/Instances/FoolCraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/phili/Documents/Curse/Minecraft/Instances/FoolCraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/phili/Documents/Curse/Minecraft/Instances/FoolCraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/phili/Documents/Curse/Minecraft/Instances/FoolCraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/phili/Documents/Curse/Minecraft/Instances/FoolCraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/phili/Documents/Curse/Minecraft/Instances/FoolCraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/phili/Documents/Curse/Minecraft/Instances/FoolCraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/phili/Documents/Curse/Minecraft/Instances/FoolCraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/phili/Documents/Curse/Minecraft/Instances/FoolCraft/mods/BrandonsCore-1.10.2-2.1.4.92-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash. Scroll up!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	EnderStorage Invalid Fingerprint Reports: 
	Translocator Invalid Fingerprint Reports: 
	OptiFine Version: OptiFine_1.10.2_HD_U_D7
	Render Distance Chunks: 4
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.1.0 - Build 9.17.10.4459
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 2

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

##  1) I download the reccent version of Foolcraft
      2) I run the pack
      3) I crash with Malisis Doors

**Comment by Jo-Mamma75** [comment]
Do me a favor.  Go back and edit your original post.  Delete the crash log and go pastebin it and post the link here.
Go have a look at [this page](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2076338-malisisdoors-1-10-2-5-2-0-1-11-2-6-1-0-15-02-2017) and see if anything helps.
**NOTE**
You may actually have to spend some time reading.  Don't mean to sound like an ass but you would be surprised the number of times we point people in a direction and they won't help themselves.

**Comment by scalda** [comment]
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda

**Comment by ElectricBlue1** [comment]
1.3 isn't on curse for me. The update goes to 1.2.2

**Comment by scalda** [comment]
Sorry i had to pull 1.3

**Comment by ElectricBlue1** [comment]
Ok, do you know when it'll be back up

**Comment by john-sp** [comment]
I am also getting this error and I am version 5.3.0 doors and 4.3.0 core 
crash report - https://pastebin.com/Th1SWHfd
