### ISSUE TITLE
Texture glitch with painted fused quartz

### ISSUE THREAD

**Issue by LittleBunnyRabb** [scalda/FoolCraft#319]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Hi
When you place the painted fused quartz with the wand from Better Builders Wands, the painted fused quartz become normal again and the texture glitches in to that black-purple texture.

**Comment by LittleBunnyRabb** [comment]
That only happens with that wand with the wand from EU2 its fine

**Comment by Jo-Mamma75** [comment]
I'll look into it.

**Comment by scalda** [comment]
The wands don't use the nbt tag that makes the item the same.

Bug with betterbuilderswands. not the pack so closing this issue

Regards

Scalda

**Comment by LittleBunnyRabb** [comment]
Ty
