### ISSUE TITLE
foolcraft freezes on world gen screen

### ISSUE THREAD

**Issue by bilblock** [scalda/FoolCraft#32]
I can play hermitpack with curse launcher but when I try to play foolcraft after I press create new world it just stays on that screen forever with high cpu load and I eventually have to kill java in task manage to get out.  running win 10 with geforce gv-n75toc graphic card.  never turned crash report before so sorry if I haven't given enough info. just very excited to play fool craft!

**Comment by krisraynes** [comment]
it does indeed take a long time to generate a SP world , you might want to increase the Ram to 6gb in Foolcraft Profile settings in Curse ( right-click Foolcraft icon and select View Profile ) ... otherwise if you don't have much physical Ram , try joining a server ... good luck

**Comment by bilblock** [comment]
thanks I'll try that and let you know how it goes!

**Comment by bilblock** [comment]
Gave it 5 gigs as I only have 6 all together and it worked thanks a lot!
Happy fool crafting!
