### ISSUE TITLE
Iskallium reacters

### ISSUE THREAD

**Issue by CatPaw11** [scalda/FoolCraft#320]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Hi so I added 8 mods to my foolcraft and when i went to make an Iscallium reacter and placed down the power tap i crashed and when ever i joind i was kicked again ad everyone crashes who goes near it

Mods Added

Ars Magica
BiblioCraft
Darkroleplay
Darkroleplay core
immersive engineering
neather portal fix
roots
vending

[crash-2017-04-20_18.25.07-client.txt](https://github.com/scalda/FoolCraft/files/948984/crash-2017-04-20_18.25.07-client.txt)

**Comment by scalda** [comment]
Hi,

The crash is due to the Darkroleplay mod. I will assign @WinterGrave to this issue to see if perhaps there is a fix that he can do to make this compatible.

Regards

Scalda

**Comment by WinterGrave** [comment]
I need to do a nullcheck, will work on it for next mod version

**Comment by scalda** [comment]
Will be fixed in next mod update
