### ISSUE TITLE
Responing in head after death...

### ISSUE THREAD

**Issue by R3kandH4V0k** [scalda/FoolCraft#321]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Whenever myself in singleplayer or anyone in my multiplayer server dies, we respond and all we can see  is the inside of our players head and if we left click we get booted. we have tried having players kill us again and also doing the /kill command and nothing happens. we have to relog to fix the issue.

## Reproduce Steps
simple die by mob/player/or /kill command
![2017-04-22_12 08 00](https://cloud.githubusercontent.com/assets/26939945/25306115/d3bbbeca-2754-11e7-911b-2d7a070bcd69.png)
![2017-04-22_12 08 06](https://cloud.githubusercontent.com/assets/26939945/25306114/d3b8dd72-2754-11e7-80d0-d9cf2f6e3961.png)
![2017-04-22_12 08 10](https://cloud.githubusercontent.com/assets/26939945/25306113/d3b84092-2754-11e7-942f-8c7041cf8425.png)

**Comment by ajdjyt** [comment]
i think you mean that all of you are re spawning in the same spot and getting stuck there

**Comment by scalda** [comment]
We haven't come across this in any of our testing. can you provide more information?

**Comment by R3kandH4V0k** [comment]
This was strange it was happening uptil 1.3 came out. I just updated and it stop doing it. So i guess it had something to do with 1.2 versions
