### ISSUE TITLE
Crash upon launch

### ISSUE THREAD

**Issue by patcat127** [scalda/FoolCraft#322]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Every time I open my main world I crash to desktop.  I have gone back and destroyed all mechanical users, and it did nothing.

## Reproduce Steps
1. Launch FoolCraft 1.3
2. Select and open your world.
3. Congratulations! You have crashed to desktop.  (Or not, but I do)

## Additional Information

https://pastebin.com/3HWzeH7j
(I hope that I did that right, first time using Pastebin)

**Comment by patcat127** [comment]
FRIK I FOUND THE CLOSED ISSUE BUTTON SORRY DEVS

**Comment by patcat127** [comment]
I realized the issue I found was for a previous version.  I shall say this world worked fine in FoolCraft version 1.2.2.  I appreciate your help.

**Comment by scalda** [comment]
There is no clear reason why this is crashing. Is this via single player or a server?

**Comment by patcat127** [comment]
Single Player.

**Comment by scalda** [comment]
1.3.1 is under review, please once available can you check again and let me know how it goes. thanks in advance

**Comment by scalda** [comment]
Hi, i have found the bug that was causing the world errors and 1.3.2 is uploading now and under review. please BACKUP your world first before updating.

Thanks in advance

Scalda
