### ISSUE TITLE
Crash When Launching World FoolCraft 1.3

### ISSUE THREAD

**Issue by CommanderRoss** [scalda/FoolCraft#323]
I backed up my world so and updated to foolcraft 1.3 and now but it crashes when the world loads so i cannot play on the latest version :(

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack
i know how to use world edit and all that so if something needs to be removed tell me and i can remove it

## Additional Information
https://pastebin.com/cK0r4Rh8

i can run the world in 1.2.2 but not 1.3

**Comment by patcat127** [comment]
I just reported this issue dude.  Make the Dev's job easier and close this issue.

**Comment by CommanderRoss** [comment]
oh ok i looked for about 10 minutes must of missed it

**Comment by scalda** [comment]
This is a crash with a botania hourglass you will have to edit the world via mcedit or remove the item prior to updating

**Comment by scalda** [comment]
Also I have reopened this @patcat127 as it is a different issue to yours

**Comment by scalda** [comment]
1.3.1 is under review, please once available can you check again and let me know how it goes. thanks in advance

**Comment by scalda** [comment]
Hi, i have found the bug that was causing the world errors and 1.3.2 is uploading now and under review. please BACKUP your world first before updating.

Thanks in advance

Scalda
