### ISSUE TITLE
Crash for me to Foolcraft 1.30

### ISSUE THREAD

**Issue by mrmitac** [scalda/FoolCraft#324]
## SUGGESTION/HELP
- [x ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Additional Information
https://pastebin.com/v3fHDA7Z

**Comment by scalda** [comment]
This is a moo fluid crash, this happens when you had a mod installed that registered a fluid and the cows had entered one into there nbt data.

but you have added mods so i can't say what fluid is missing as we haven't removed any fluids between 1.2.2 and 1.3

**Comment by mrmitac** [comment]
Only mod i have installed is AromaBackup. Forgot to inform you that I also received this error message when I started saving the world. (If that could be helpful)

>  "Forge Mod Loader detected that the backup level.dat is being used. This may happen due to a bug or corruption, continuing can damage your world beyond repair or lose data/progress. It's recommended to create a world backup before continuing."

**Comment by scalda** [comment]
yes i have got to push a 1.3.1 hotfix out

**Comment by scalda** [comment]
Can you delete your nei folder in the root directory and try again?

**Comment by scalda** [comment]
1.3.1 is under review, please once available can you check again and let me know how it goes. thanks in advance

**Comment by scalda** [comment]
1.3.1 is under review, please once available can you check again and let me know how it goes. thanks in advance

**Comment by mrmitac** [comment]
Same crash in 1.31

**Comment by scalda** [comment]
ok yours is a moo fluid cow issue, you will need to mcedit out the cows in your worls

**Comment by mrmitac** [comment]
OK

**Comment by mrmitac** [comment]
Uninstalled moo fluid mod, then i have a "new" crash

https://pastebin.com/Vw9qEzj8

Backing my Foolcraft to 1.2.2 and continues playing there

**Comment by scalda** [comment]
Hi, i have found the bug that was causing the world errors and 1.3.2 is uploading now and under review. please BACKUP your world first before updating.

Thanks in advance

Scalda

**Comment by mrmitac** [comment]
Still crashing for me. 1.3.2 :(
Can you help me out what I can do ?

https://pastebin.com/ckaB8D3m

**Comment by scalda** [comment]
yeah a moo fluid crash. you will have to mcedit out all the fluid cows in your world. sorry

**Comment by mrmitac** [comment]
Solved the problem. Started in 1.2.2 caught all cows in an animal net. Started the saved world in 1.3.2 released the cows again and it worked. Also had to install embers mod again to avoid crashing. (My base is partly made up of rocks from the fashion)

**Comment by scalda** [comment]
ok that's great yeah sorry about removing embers but we removed it because they have abandoned support for 1.10.2

**Comment by mrmitac** [comment]
And it have molten downstone as liquid so maybe the was caused it to crash, because it was removed ?

**Comment by scalda** [comment]
yes that would be a problem
