### ISSUE TITLE
Save corruption by 1.3

### ISSUE THREAD

**Issue by bswan** [scalda/FoolCraft#325]
<!-->
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.

Latest save buckup here: https://drive.google.com/file/d/0B3CQPxjwHzrtQnpRemhMaHdXUGs/view?usp=sharing - Before update.

Lot's of blocks gone wrong :)

**Comment by scalda** [comment]
is that backup before you updated?

**Comment by notmark** [comment]
I just upgraded my server and client to 1.3 and every block I placed in 1.2 has been replaced or destroyed. Power conduits are now storage tanks, mob fans are now blocks of energetic alloy, GP water mills are now blocks of clay, collossal chests completely replaced by weird stair blocks, drums replaced by clay blocks, waystone's destroyed, all traces of my two refined storage systems are gone. All power generators and capacitors gone. Etc, etc. I have it backed up, thankfully, but is this sort of thing an expected result? I'll most likely start a new world. But it sucks to lose all my progress when moving to 1.3

**Comment by scalda** [comment]
did you get any warnings when you started your world?

**Comment by bswan** [comment]
Yeah, something about level.dat Can provide exact text, if you need it

**Comment by scalda** [comment]
what forge version are you running?

it should be 12.18.3.2281

**Comment by notmark** [comment]
Here's my latest.log: https://pastebin.com/uL8RJDzj

**Comment by bswan** [comment]
Yeah, I have 12.18.3.2281

**Comment by scalda** [comment]
Yep this is a problem with simply conveyors, i am going to have to roll the mod back
and release a 1.3.1

**Comment by notmark** [comment]
More like "not so simply" conveyors ;p

**Comment by bswan** [comment]
Thank's, guys!

**Comment by scalda** [comment]
1.3.1 is under review, please once availible can you check again and let me no how it goes. thanks in advance

**Comment by notmark** [comment]
Will do

**Comment by notmark** [comment]
Is this a client side only update or is there an update needed for the server too?

**Comment by scalda** [comment]
server is still uploading

**Comment by notmark** [comment]
Same result with 1.3.1 server and 1.3.1 client: http://prntscr.com/ezljhp That's supposed to be chiseled cobble and a refined storage crafting grid directly in front of me. 

latest.log from server: https://pastebin.com/Sz8RjQs1

**Comment by bswan** [comment]
![image](https://cloud.githubusercontent.com/assets/1019928/25307903/50a499cc-27b2-11e7-8e48-e0fb16293597.png)
Same again :(

**Comment by notmark** [comment]
Here's my 1.2.2 server world, not the corrupted one. https://www.dropbox.com/s/3ilfltgh14enbc9/FoolCraft_world_1.2.1.rar?dl=0

Might help with tracking down the issue in 1.3

**Comment by scalda** [comment]
thanks
