### ISSUE TITLE
Crash When Launching World FoolCraft 1.3

### ISSUE THREAD

**Issue by Sancho558** [scalda/FoolCraft#326]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Whenever I open the world,I hear an item sucking in to my inventory and then the game crashes.I have looked at other posts,but none of the fixes worked.

## Additional Information
Crash report:
https://pastebin.com/671q2iSW

**Comment by scalda** [comment]
bad block at this location

> Details:
    Name: FluxPlug // sonar.flux.common.tileentity.TileEntityPlug
    Block type: ID #2228 (tile.rftools.storage_terminal // mcjty.rftools.blocks.storage.StorageTerminalBlock)
    Block data value: 1 / 0x1 / 0b0001
    Block location: World: (-40,120,3179), Chunk: (at 8,7,11 in -3,198; contains blocks -48,0,3168 to -33,255,3183), Region: (-1,6; contains chunks -32,192 to -1,223, blocks -512,0,3072 to -1,255,3583)
    Actual block type: ID #2228 (tile.rftools.storage_terminal // mcjty.rftools.blocks.storage.StorageTerminalBlock)
    Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1804)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

**Comment by scalda** [comment]
Can you delete your nei folder in the root directory and try again?

**Comment by Sancho558** [comment]
Sure,Ill try. Thanks

**Comment by scalda** [comment]
1.3.1 is under review, please once available can you check again and let me know how it goes. thanks in advance

**Comment by Sancho558** [comment]
Tried deleting the Flux Plug trough McEdit,but it kept crushing every time. 
Also seems like deleting nei folder also does'nt help. Maybe I should try removing the whole FluxNetworks mod?

**Comment by scalda** [comment]
Hi, i have found the bug that was causing the world errors and 1.3.2 is uploading now and under review. please BACKUP your world first before updating.

Thanks in advance

Scalda
