### ISSUE TITLE
FoolCraft 1.3 Server setup

### ISSUE THREAD

**Issue by FatesSolder** [scalda/FoolCraft#327]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I am trying to change my server to the 1.3 update and have been unable to do so after downloading and extracting the 1.3 files into the server folder and the Minecraft file locations set by the foolcraft pack via twitch app is there a way to update my local server to the 1.3 version? i am still currently using the server files from 1.2.1 and added the revised files from the 1.3 zip. i try to log onto the server but get rejected due to too many mods compared to the server. currently i am doing a fresh install of everything to see if that fixes it if so i will let you know
Thank you for any feedback
-Fate

**Comment by scalda** [comment]
all you need to do is replace the files/folders from the server files zip and update you client via curse

**Comment by scalda** [comment]
Can you delete your nei folder in the root directory and try again?

**Comment by FatesSolder** [comment]
thank you for the feed back. the server file for the 1.3 was not up when i was trying. it is up now, if any other issues arise i will let you know

**Comment by scalda** [comment]
1.3.1 is under review, please once available can you check again and let me know how it goes. thanks in advance

**Comment by FatesSolder** [comment]
before joining my server under where the latency is shown has a red x while hovering over it displays "incompatible FML modded server 127 mods present"  i have not added any mods to the pack in any way. after joining server i get the following message " mod rejections [FMLMod:simplyconveyors{3.0.3}] " and forced to go back to server list

**Comment by scalda** [comment]
have you got 1.3.1 on both server and client

**Comment by FatesSolder** [comment]
yes to both

**Comment by FatesSolder** [comment]
no change with deletion of NEI folder say rejection returns while trying to join server

**Comment by FatesSolder** [comment]
in server file mod folder contains SimplyConveyors-1.10.2-3.0.3.jar while client mod folder contains SimplyConveyors-1.4.2.jar i will try copying the client version to the server mod folder and try again

**Comment by scalda** [comment]
thats odd as the uploaded version 1.3.1 server files have the same file that matches the client

**Comment by FatesSolder** [comment]
issue resolved now the red x is gone green check in its place not exactly sure why on my end it had two different version of the jar file for simply conveyors

**Comment by scalda** [comment]
ok, is your world ok?

**Comment by FatesSolder** [comment]
world had blocks changed out but no big deal to me i created a new world for the server. only a few friends of mine play on it from time to time anyway they can restart and be just fine with it thanks for the quick assistance by the way. looking forward to future updates

**Comment by scalda** [comment]
Ok sorry to hear that you have had to reset the world. can you close this if you think you are sorted now thanks
