### ISSUE TITLE
Game Crashing when loading world in 1.3 update

### ISSUE THREAD

**Issue by MisfitBC** [scalda/FoolCraft#328]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When loading my world the game crashes right as the world is about to load. I removed all mechanical uses before upgrading to 1.3.

## Additional Information

[crash_report.txt](https://github.com/scalda/FoolCraft/files/949161/crash_report.txt)

**Comment by scalda** [comment]
Can you delete your nei folder in the root directory and try again?

**Comment by scalda** [comment]
1.3.1 is under review, please once availible can you check again and let me no how it goes. thanks in advance

**Comment by Kregus** [comment]
I was having the same issue, as noted in the first crash report.

I removed the NEI folder from the world folder, and I had previously removed Pam's, loaded my world, removed the mod blocks with fml, then readded the mod and reloaded.
Seemingly the same error in a different area of my world.

The second report is after I removed the folder as scalda said and re-added Pam's.

[crash-Before mod and folder removal.txt](https://github.com/scalda/FoolCraft/files/949197/crash-Before.mod.and.folder.removal.txt)
[crash-after mod readd and folder removal.txt](https://github.com/scalda/FoolCraft/files/949198/crash-after.mod.readd.and.folder.removal.txt)

**Comment by scalda** [comment]
> -- Block being ticked --
Details:
	Block: minecraft:flowing_water[level=0]
	Block location: World: (158,60,-329), Chunk: (at 14,3,7 in 9,-21; contains blocks 144,0,-336 to 159,255,-321), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:744)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:218)

**Comment by Kregus** [comment]
I'll go edit my world, see if that fixes it, thanks and wow

**Comment by MIsiftBC** [comment]
game is still crashing right as it would load. new crash report [https://pastebin.com/index/K4BiKQtV](url)

**Comment by Kregus** [comment]
It looks like my world was just corrupt, every time I filled in the ticking block there was a new one, Thanks again scalda.

**Comment by MIsiftBC** [comment]
Sorry here is the new crash report 
[K4BiKQtV.txt](https://github.com/scalda/FoolCraft/files/949239/K4BiKQtV.txt)

**Comment by scalda** [comment]
looks like a pams sapling @MIsiftBC

**Comment by scalda** [comment]
Hi, i have found the bug that was causing the world errors and 1.3.2 is uploading now and under review. please BACKUP your world first before updating.

Thanks in advance

Scalda
