### ISSUE TITLE
Connect Lost / Server Crash

### ISSUE THREAD

**Issue by irobinson107** [scalda/FoolCraft#33]
I had my server host "NodeCraft" install V1.1 of FollCraft and it load into the world and crahes immediatly with the below error.

![mc error 032017](https://cloud.githubusercontent.com/assets/26558518/24127407/c37638e2-0daa-11e7-8b15-fdf61db9ccef.png)

**Comment by scalda** [comment]
please provide crash report from the server and client?

**Comment by irobinson107** [comment]
Hi Scalda, 




Here is what I got back from the hosting company.  Thoughts.




There aren't actually any "crash reports" in the traditional sense. The only error in the console when you attempt to join is "[21:05:15] [Netty Epoll Server IO #9/ERROR] [FML]: NetworkDispatcher exception" which is unfortunately too ambiguous to isolate to a specific mod. One or more of the mods on the server appears to be forcefully closing your connection though.

 


On Mar 21, 2017, at 09:09 AM, Scalda <notifications@github.com> wrote:






please provide crash report from the server and client?

**Comment by scalda** [comment]
ok so it's a connection issue. sorry but we can't help you out with this

**Comment by irobinson107** [comment]
Hi Scala, 





I do not know what that means.  Could you please elaborate, so I can inform the hosting company of what they needs to changed.  Thank you. 


 


On Mar 21, 2017, at 01:26 PM, Scalda <notifications@github.com> wrote:






Closed #33.
