### ISSUE TITLE
Botania mod crashes my multiplayer server running 1.3.1

### ISSUE THREAD

**Issue by PSILONCRAFT** [scalda/FoolCraft#331]
[crash-2017-04-22_20.45.56-server.txt](https://github.com/scalda/FoolCraft/files/949208/crash-2017-04-22_20.45.56-server.txt)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## -- Block entity being ticked --
Details:
	Name: botania:lightRelay // vazkii.botania.common.block.tile.TileLightRelay
	Block type: ID #445 (tile.spreader // vazkii.botania.common.block.mana.BlockSpreader)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (242,68,143), Chunk: (at 2,4,15 in 15,8; contains blocks 240,0,128 to 255,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #445 (tile.spreader // vazkii.botania.common.block.mana.BlockSpreader)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

**Comment by scalda** [comment]
you will need to mcedit the block out

**Comment by PSILONCRAFT** [comment]
ok

**Comment by scalda** [comment]
Hi, i have found the bug that was causing the world errors and 1.3.2 is uploading now and under review. please BACKUP your world first before updating.

Thanks in advance

Scalda
