### ISSUE TITLE
Save game corruption, 1.3.1

### ISSUE THREAD

**Issue by Morbinator** [scalda/FoolCraft#332]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [X] I am requesting help with installing or running the pack

I have updated from 1.2.2 straight to 1.3.1 and my save game now no longer loads properly.  Other than chests etc, every block I have placed has been changed to another block.  (i.e. my colossal chest is now a box of prismarine bricks and my fertilised dirt has simply disappeared.)

I have loaded the save in 1.2.2 again with no issues, tried deleting all instances of foolcraft, reinstalled 1.3.1 and restored my save and still having exactly the same problem.

**Comment by SpeedySpy52** [comment]
I'm having the exact same issue. The question now is: do I restart my world to play on the new update, which is desperately needed for bug fixes, or do I not update?

**Comment by scalda** [comment]
Yeah there seems to be issues with some worlds but not others, we aren't 100% sure what is happening

**Comment by Morbinator** [comment]
This is no longer an issue for me as I have messed up whilst trying reinstalling agan and I have lost my sve now, so need to start again anyway.  I'm sure others will still want their saves back though!

**Comment by SpeedySpy52** [comment]
The issue might only occur when jumping from 1.2.2 to 1.3.1, skipping 1.3 entirely

**Comment by onerail** [comment]
Same issue. Blocks have either disappeared, been substituted, or show errors. Completely broken my base.

**Comment by scalda** [comment]
i'm sorry to hear that @Morbinator 

@SpeedySpy52 and @onerail look like it's only affecting certain worlds. if you could send me a copy of the backed up worlds i may be able to find a link

**Comment by TonsillarRat6** [comment]
it happens to me too, and having to restart really turns me of playing, I just got past the grindy early game shall I send a backup of my world ?

**Comment by scalda** [comment]
yes can i have a backup please and go back to 1.2.2 til we can work it out.

**Comment by TonsillarRat6** [comment]
the file is too big to attach to this comment, even when compressed, so here is a wetransfer link https://we.tl/dNoIifFxp9

**Comment by scalda** [comment]
thanks downloading now

**Comment by SpeedySpy52** [comment]
https://www.dropbox.com/s/cbz2lxpkqqtrvv7/world%20-%20pre1.3backup.rar?dl=0
My world backup, VERY glad I did this. If I try updating with the backup again, I wonder if it will get corrupted again?
Worth a try.

**Comment by CommanderRoss** [comment]
I am also having this problem most of the items are replaced with items from mostly enderio

**Comment by onerail** [comment]
​
 2017-04-22-00-53-40.zip
<https://drive.google.com/file/d/0BxAukZb9v0K8SEptSWJiNjgza2s/view?usp=drive_web>
​ Hi scalda,

Thank you for your time, I know you.guys work hard on this. Attached is the
most recent available backup. It did the same thing in 1.3.1 and 1.3. I
just finished reinstalling 1.2.2 and will make sure it works in there.
Thanks for your help.

**Comment by Sancho558** [comment]
Because of switched blocks,I'm running the game at 2 Fps. Gotta wait for a fix I guess.

**Comment by scalda** [comment]
Hi, i have found the bug that was causing the world errors and 1.3.2 is uploading now and under review. please BACKUP your world first before updating.

Thanks in advance

Scalda

**Comment by onerail** [comment]
You're my hero scalda. Thank you.
