### ISSUE TITLE
FoolCraft 1.3.1 crashes when loading world 

### ISSUE THREAD

**Issue by Hubbzy** [scalda/FoolCraft#334]
FOOLCRAFT MODPACK CRASHING WHEN LOADING THE WORLD
- [x ] I am running the latest version of FoolCraft
- [x ] I am running FoolCraft via Curse/Twitch Launcher
- [ x] I can reproduce this issue consistently
     - [x ] In single player
     - [ ] In multiplayer
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
Started modpack freshly due to pack loading crashes,successfully loaded and crashes when loading my world from 1.2.1 version of the modpack.Help.

## Reproduce Steps
I made a new pack folder,a fresh start.Load up the pack and put my backed up save from 1.2.1 to 1.3.1 world.World starts loading and comes to 0%,then crashes.

## Additional Information
CRASH INFO
https://pastebin.com/mD02bpvY

**Comment by scalda** [comment]
you will need to mcedit this block

> -- Block entity being ticked --
Details:
    Name: blockConduitBundleTileEntity // crazypants.enderio.conduit.TileConduitBundle
    Block type: ID #974 (tile.blockConduitBundle // crazypants.enderio.conduit.BlockConduitBundle)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (1070,64,1676), Chunk: (at 14,4,12 in 66,104; contains blocks 1056,0,1664 to 1071,255,1679), Region: (2,3; contains chunks 64,96 to 95,127, blocks 1024,0,1536 to 1535,255,2047)
    Actual block type: ID #978 (tile.blockReservoir // crazypants.enderio.machine.reservoir.BlockReservoir)
    Actual block data value: 0 / 0x0 / 0b0000

**Comment by Hubbzy** [comment]
Thank you sir for your quick response! Will try right now!

**Comment by scalda** [comment]
Hi, i have found the bug that was causing the world errors and 1.3.2 is uploading now and under review. please BACKUP your world first before updating.

Thanks in advance

Scalda
