### ISSUE TITLE
1.3.1 Crash on world load

### ISSUE THREAD

**Issue by Drache91** [scalda/FoolCraft#337]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description

I've recently upgraded from 1.2.2 to 1.3.1.
Now when i load my world I get about one frame and then the game crashes.

## Additional Information

https://pastebin.com/Hv2LkNh9

I've had the same crash before and already deleted the flowing water entity above the currently "crashing" one. 
Now it says it ticked the block below (also a flowing water entity)
```
-- Block being ticked --
Details:
	Block: minecraft:flowing_water[level=8]
	Block location: World: (2143,61,5280), Chunk: (at 15,3,0 in 133,330; contains blocks 2128,0,5280 to 2143,255,5295), Region: (4,10; contains chunks 128,320 to 159,351, blocks 2048,0,5120 to 2559,255,5631)
```

As of now this issue might be identical to issue #334 and possibly issue #336

**Comment by Drache91** [comment]
Also removed that other water block, now it's gravel.
```
-- Block being ticked --
Details:
	Block: minecraft:gravel
	Block location: World: (2321,62,5166), Chunk: (at 1,3,14 in 145,322; contains blocks 2320,0,5152 to 2335,255,5167), Region: (4,10; contains chunks 128,320 to 159,351, blocks 2048,0,5120 to 2559,255,5631)
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:744)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:218)
```

https://pastebin.com/z9aE8Ykk

Also issue #338 seems to have an identical issue.

**Comment by CakeArmy** [comment]
Reverse to 1.2.2. 1.3.1/1.3 is removed.

**Comment by Drache91** [comment]
Yes, I did that.

**Comment by scalda** [comment]
Hi, i have found the bug that was causing the world errors and 1.3.2 is uploading now and under review. please BACKUP your world first before updating.

Thanks in advance

Scalda
