### ISSUE TITLE
Foolcraft 1.3.1 RFTools crashes game launch

### ISSUE THREAD

**Issue by JinxsoMC** [scalda/FoolCraft#339]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
New install of Foolcraft 1.3.1 (Tried several installs).   When loading in Phase 2 at RFTools the game crashes back to launcher without generating any error in the logfiles.   

Running 6GB Memory on the launch, I have tried with less and way more (32GB).  No change.

## Reproduce Steps

Fresh install with latest launcher and the latest version as of right now 1.3.1.   Loading goes forward until the RFTools (or just after, without a generated error hard to tell if it is the next mod).   Crash back to launcher everytime.

**Comment by scalda** [comment]
can you send me the client log please?

**Comment by JinxsoMC** [comment]
Sure thing.  I have included both the launcher and the Foolcraft log.
[Uploading launcher_log.txt…]()



[Uploading Foolcraftlatest.txt…]()

**Comment by Jo-Mamma75** [comment]
Update to 1.3.2 and report back please.
