### ISSUE TITLE
Crashing on Startup

### ISSUE THREAD

**Issue by Steadmum** [scalda/FoolCraft#340]
Crashing on Startup. Single player not on Server

- [ x] I am running the latest version of FoolCraft
- [ x] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [x ] In single player
     - [ ] In multiplayer
- [x ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Additional Information
I dont know how to get you the crash report. This is all I know how to do.

The game crashed whilst exception ticking world
The game crashed whilst exception ticking world
Error: java.lang.NoClassDefFoundError: net/minecraft/world/World$2

**Comment by scalda** [comment]
go back to 1.2.2, 1.3 has been pulled

**Comment by Steadmum** [comment]
Tried this. It loaded last nights save, but over half the build was missing including my computer system, all Drawers and resources. Although it has last nights date on it the games loaded is about 3 weeks old.

**Comment by Steadmum** [comment]
Did this, loaded the saved backup I had with last nights date. Loaded brilliantly, except for the fact that it wasn't the game as I saved it last night.
All my storage Drawers are gone, my computer system , all their contents, all progress on the chicken breeding mod and extensive landscaping. It seems to have rolled the game back about 2 weeks/ 25 hours of game play.

Really sad, I love this pack, but this is the second time I have lost so many hours of work, I really don't think I can face reworking all that I'd done again.



Sent from my iPad

On 22 Apr 2017, at 22:22, Scalda <notifications@github.com<mailto:notifications@github.com>> wrote:


go back to 1.2.2, 1.3 has been pulled

**Comment by CakeArmy** [comment]
@Steadmum You can add a mod called Aroma's Backup. Backs up by default every 1 hour, but can be configured to be shorter. I am wondering why you didn't have backups in the first place?

**Comment by scalda** [comment]
you should have backups as FTBU does it every 2 hours and saves the last 4 backups

**Comment by Steadmum** [comment]
Thank You Scalda for not giving up on me. I was so upset.
I am 61years old and started playing Minecraft just 2 years ago when I took early retirement due to ill health. I love Iskall's packs and feel the game offers a real creative outlet for me. I felt like an artist might feel if someone had destroyed a painting.

I have managed to load a game that is just 3 days - about 10 hours out of date, but all the major builds are there and all I have to do is re-breed all the bloody chickens again.

Thank you again for not giving up on me, it must be chaos there with all those posts about crashing, and of course you now have to work out why.

You are doing a fantastic job.

Pauline Steadman 😊 (smiling again thanks to you)



Sent from my iPad

On 23 Apr 2017, at 09:16, Scalda <notifications@github.com<mailto:notifications@github.com>> wrote:


you should have backups as FTBU does it every 2 hours and saves the last 4 backups

**Comment by scalda** [comment]
@Steadmum Thankyou for the lovely reply it has really put a smaile on my face. I am glad you have got it working again i will now close this issue
