### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Betasurfarn** [scalda/FoolCraft#342]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

I¨'m trying to install a fresh copy of Foolcraft on the Twitch launcher. I get 

Addon install error
Twitch´encountered a problem during this operation
Error:
File in manifest is not available from the server

I'm able to install other packs

**Comment by Betasurfarn** [comment]
Saw too late that 1.3 was pulled

**Comment by CakeArmy** [comment]
Yeah. I just saw it was pulled myself. I didn't know the issues were that bad. If you guys need help hit me up. I loaded a 1.3.1 world and it was fine..

**Comment by scalda** [comment]
loading a clean world is fine it's existing worlds

**Comment by Jo-Mamma75** [comment]
Closing this issue.
