### ISSUE TITLE
Missing Crafting Recipe = Oak Wood Irrigation Channel

### ISSUE THREAD

**Issue by CakeArmy** [scalda/FoolCraft#343]
## SUGGESTION/HELP
- [ X] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When making an irrigation channel with oak planks, it shows a recipe both in the crafting grid and & jei, but when you click to craft it, it dissapears (manual crafting. Doesnt let you make pattern) Dark Oak works though..

**Comment by Jo-Mamma75** [comment]
That's so weird. I know I tried that during testing for 1.3.  We will look into it.
Thank you for letting us know.

**Comment by CakeArmy** [comment]
Also, you cant put sprinklers on the full block of the irrigation block things. I like those better because they produce less lag. Also, I think the EnderIO Agricraft station might be updated? Also, I think this is a better builders wand button but when using a wand on stuff like the irrigation channels it removes the metadata, which means the type of wood is reset.

**Comment by scalda** [comment]
Hi, i have found the bug that was causing the world errors and 1.3.2 is uploading now and under review. please BACKUP your world first before updating.

Thanks in advance

Scalda
