### ISSUE TITLE
See Through Iskallium Reactors Version 1.2.2

### ISSUE THREAD

**Issue by CakeArmy** [scalda/FoolCraft#344]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
You can see deco-craft stuff through iskallium reactors. I dont use deco-craft and the only thing I have is the dog house and you can see the roof through it.  Image below 

## Additional Information

![2017-04-22_18 31 24](https://cloud.githubusercontent.com/assets/13841599/25309753/2a660a3e-278a-11e7-9087-be42a6475b77.png)
![2017-04-22_18 33 28](https://cloud.githubusercontent.com/assets/13841599/25309755/363b7eca-278a-11e7-8eba-c4f986c3a6bd.png)

**Comment by WinterGrave** [comment]
This is a Vanilla bug, it would be the same if you put vanilla glass and vanilla slime blocks or particles and water

**Comment by scalda** [comment]
What winter said closing issue now
