### ISSUE TITLE
Actually Additions cause world loading to be stuck at "building terrain"

### ISSUE THREAD

**Issue by rosareven** [scalda/FoolCraft#345]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
The mod "Actually Additions" causes world loading to get stuck at "Building Terrain". Removing the mod from the pack resumes the game.

## Reproduce Steps
1. Install Actually Additions from Twitch;
2. Either load an existing world or create a new world

**Comment by scalda** [comment]
sorry but this mod is not added by us so we won't be supporting this issue
