### ISSUE TITLE
Open World FoolCraft crash

### ISSUE THREAD

**Issue by ML98** [scalda/FoolCraft#346]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
I was standing right on top of a Mechanical User with my paper and cobalt hammer in it. I opened the GUI and activated it to see if it was hitting me, then the game crashed and now I can't open it again.
I don't know if it is a problem related to the mod or the pack itself, but I hope you'll be able to fix this because i's pretty annoying.
Thank you so much if you're going to read this.

## Reproduce Steps

Just open the world after standing on top of a working mechanical user

**Comment by MrLeKent** [comment]
Remove the mechanical user with mcedit or load a backup. its a known issue.
