### ISSUE TITLE
Server crashing after updating to 1.3.1

### ISSUE THREAD

**Issue by LeBeast** [scalda/FoolCraft#347]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
After updating to version 1.3.1 the server crashes when i join the game. It has something to do with the world as it's was made in version 1.2. When i load up a freshly generated world it works fine.

## Additional Information

https://pastebin.com/vaXUKF3Z   <--- A pastebin of the crash report

**Comment by DeathSaintfool** [comment]
they took out 1.3.1 so i dont know how you manged to get 1.3.1

**Comment by scalda** [comment]
Hi, i have found the bug that was causing the world errors and 1.3.2 is uploading now and under review. please BACKUP your world first before updating.

Thanks in advance

Scalda

**Comment by LeBeast** [comment]
Still Crashes Server After I Updated  :/

**Comment by LeBeast** [comment]
Server is still crashing though after updating and everything :/
