### ISSUE TITLE
GAME CRASH

### ISSUE THREAD

**Issue by ajdjyt** [scalda/FoolCraft#348]
Scalda Thank You For The Support , I Will Report As Much As I Can
 
 

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description 
the issue caused a blue screen with the code "INVALID_IO_BOOST_STATE" I think what happened was there was a major time lapse between the game ticks and real time as you will see in the log this issue took place when i was using 1.2.1  , It Caused World Corruption, Also At The Same Time While Playing I Was Getting Graphic Twerk-age , That is i would see black patches or rainbow patches on certain areas anywhere i went.

## Reproduce Steps
I Do Not Know How TO reproduce the issue as it was very random and happened when my world was just loaded in maybe a couple of minuites after
 

## Additional Information
the issue caused a blue screen with the code "INVALID_IO_BOOST_STATE" I think what happened was there was a major time lapse between the game ticks and real time as you will see in the log this issue took place when i was using 1.2.1  , It Caused World Corruption, Also At The Same Time While Playing I Was Getting Graphic Twerk-age , That is i would see black patches or rainbow patches on certain areas anywhere i went (this is not a graphic card issue as i am playing on a laptop Using Integrated Graphics And The Game Worked Properly Without Any Issues For A While Except For One Time , I "THINK" This IS A "KNOWN ISSUE" . " MECHANICAL USERS" DO I NEED TO SAY ANYMORE ) The Log Attached Below
[2017-04-02-2.log.gz](https://github.com/scalda/FoolCraft/files/949837/2017-04-02-2.log.gz)
Yes This Issue IS OLD BUT IT CAN HAPPEN AGAIN Since I Don't know what to copy AND paste from my old issue/thread i'll just tell you the issue number that is 162
Also I Cant upgrade to 1.3 OR 1.3.1 AS TWITCH OR THE CURSE LAUNCHER DOESN'T WANT TO LET ME !!! (I tried RESTARTING TWITCH ,MY LAPTOP , MY ROUTER , AND SWITCHING TO MY BACKUP CELLULAR NETWORK , :( None Of Them Worked)

**Comment by FeikoJoosten** [comment]
I'm not going to be able to help you out with the issues, not that familiar with MC crashlogs and stuff like that. But on the issue regarding Foolcraft 1.3 or 1.3.1, they took version 1.3 & 1.3.1 down since they kept giving crashes for a lot of people, so they decided to take it down.

**Comment by ajdjyt** [comment]
ok thnx for the fast reply

**Comment by scalda** [comment]
Hi, i have found the bug that was causing the world errors and 1.3.2 is uploading now and under review. please BACKUP your world first before updating.

Thanks in advance

Scalda

**Comment by ajdjyt** [comment]
OK Thanks !!!
