### ISSUE TITLE
Still Crashing After reverting back to 1.2.2

### ISSUE THREAD

**Issue by kKel1** [scalda/FoolCraft#349]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I updated to 1.3 and the game kept crashing on 'PM Description: Exception ticking world java.lang.NoClassDefFoundError: net/minecraft/world/World$2'. I reverted back to 1.2.2 and am still experiencing the same error.

## Additional Information
[crash-2017-04-23_14.05.25-server.txt](https://github.com/scalda/FoolCraft/files/949981/crash-2017-04-23_14.05.25-server.txt)

**Comment by scalda** [comment]
Hi, i have found the bug that was causing the world errors and 1.3.2 is uploading now and under review. please BACKUP your world first before updating.

Thanks in advance

Scalda
