### ISSUE TITLE
Crash while loading @ CoFH core

### ISSUE THREAD

**Issue by darkfae83** [scalda/FoolCraft#35]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CoFH Core (cofhcore)
 updated java, allocated 6 gig ram , reinstalled pack, added better FPS and still cant get it to run. Cant even get the crash report i would really like to play the pack. No i dont have a laptop

thanks for any help

**Comment by scalda** [comment]
Please provide the crash report?

**Comment by darkfae83** [comment]
New launcher doesn't allow me to get the crash report

**Comment by CriticalMole** [comment]
right click on teh instance thumbnail, select open folder there should be a crash reports folder
