### ISSUE TITLE
Refined Storage Causes Thousands of Unexplained Tileentities Lagging Server  1.2.2  and 1.3.2

### ISSUE THREAD

**Issue by theaardvarker** [scalda/FoolCraft#350]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

When I start the server thousands of tileentities are loaded.  No one is on, and ftbu is completely disabled to make sure no chunks are claimed.  The number of tileentities fluctuates erratically and the tps will drop to one a lot.  Even stranger, a couple of time the dimension the quantum quarries operate in has a couple of times generated over 10k tileentities and only been fixed by deleting the dimension file and regenerating it.  Unfortunately, I only have evidence of the overworld lagging.   Also, at spawn, there is no machinery loaded in.  The issue did not happen the first couple of weeks the server was up and has only been observed in this world file.  The server has is hosted and has 5 gb of ram.  It loads other maps without lag.    

## Reproduce Steps

Start server and wait.

## Additional Information

I've installed tick profiler.  

Profile e logs when I'm the only one on sitting at spawn:
https://pastebin.com/29ghd5E5

Profile e and tps commands right after the server is started with no one connected:
https://pastebin.com/kf02dVHw

Some profile s logs with me connected to the server and sitting at spawn:
https://pastebin.com/HqhYYJZJ

**Comment by CakeArmy** [comment]
@theaardvarker That is refined storage asfar as I can tell. I see external storage bus'es being used. I assume you are connected to a colossal chest?

**Comment by theaardvarker** [comment]
@CakeArmy There was a previous issue with colossal chests by themselves bringing down tps so everyone switched to storage drawers.

**Comment by CakeArmy** [comment]
@theaardvarker so what is the external storage connected to?

**Comment by theaardvarker** [comment]
@CakeArmy Storage drawer controllers.

**Comment by CakeArmy** [comment]
How large is/are the storage drawer arrays?

**Comment by CakeArmy** [comment]
And the problem is lag? If there is just tons of tile entities that may not be a problem. Are you lagging?

**Comment by theaardvarker** [comment]
@CakeArmy They are pretty large, probably a couple of hundred upgraded drawers.  It is enough to store all drops from lootbags and quarries.  And there is lag even with no players online.  With players online it is basically unplayable.  There is constantly the server can't keep up message in the console and the tps is erratic.  I'm suspicious of the tile entities because they increase and fluctuate so much.  In the second pastebin link it shows it switching between 15k and 30k tile entities with no one oe the server and the same chunks loaded in both instances.

**Comment by Hoff2567** [comment]
Do me a favor. Back up your world first then try starting it with pam's harvestcraft removed.

**Comment by theaardvarker** [comment]
@Hoff2567 Okay, I did that.  Unfortunately, I am still getting all of the same issues.

**Comment by theaardvarker** [comment]
This is a cleaner illustration of the ever-increasing tileentities.  No one is one the server moving around and no claimed chunks exist.  

https://pastebin.com/EPYd7g6Y

I have no clue why it's going from 14 thousand to 72 thousand out of nowhere and I think that probably does contribute to the massive lag that ensues as soon as anyone logs on.

Any help is appreciated.

**Comment by theaardvarker** [comment]
A little update on the issue.  I backed up the world and removed refined storage.  The tileentities are now constant at about 1000 and the lag is gone.  It is refined storage causing this.  I also just updated the server to 1.3.2 and the issue persists so the update to refined storage did not fix this.

**Comment by theaardvarker** [comment]
Still having problems in 1.3.2.  Gotten worse.  @scalda

**Comment by scalda** [comment]
Please take a look at the profiling tool on the wiki as that will help you to diagnose the problem better
