### ISSUE TITLE
Quantum Quarry Dimension Exception

### ISSUE THREAD

**Issue by ajdjyt** [scalda/FoolCraft#352]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
While was building a 17x17 Colossal Chest In  A Ravine Under A Village The Game All Of a Sudden Crashed And Now Whenever I Try To Start The World Again Within A Minute I See The Words "shutting down server" on my screen  , so i have a look at the latest.log file and find that apparently when the game was unloading save chunks for the quantum quarry dimension it got an unexpected exception which caused the Exit Of my world The Log is below 
[latest.txt](https://github.com/scalda/FoolCraft/files/950773/latest.txt)

## Reproduce Steps
I THINK IT IS REPRODUCIBLE but i dont know how to  

## Additional Information
[latest.txt](https://github.com/scalda/FoolCraft/files/950774/latest.txt)

**Comment by scalda** [comment]
Please provide the crash report found here in your filesystem `C:\Users\AJ DJ\Documents\Curse\Minecraft\Instances\FoolCraft\crash-reports\crash-2017-04-23_20.37.31-client.txt`

**Comment by ajdjyt** [comment]
OK Here you go scalda

[crash-2017-04-23_20.37.31-client.txt](https://github.com/scalda/FoolCraft/files/951971/crash-2017-04-23_20.37.31-client.txt)

**Comment by scalda** [comment]
it's your colossalchest thats the issue

**Comment by ajdjyt** [comment]
ok

**Comment by ajdjyt** [comment]
so how do i remove it because my world logs out automatically just after a minuite of loading the world in

**Comment by scalda** [comment]
try the 1.3.2 pack update, and if it still crashes you will have to use mcedit to delete the blocks of the chest

**Comment by colin500** [comment]
MC Edit?( all modded blocks will have the broken block texture though just look at their name)

**Comment by scalda** [comment]
in the crash report you will find the block location of the block in question so you can goto those coords and then select the blocks and delete them

**Comment by ajdjyt** [comment]
mc edit for me crashes whenever i use it on modded blocks with a gl error

**Comment by scalda** [comment]
use the legacy version

**Comment by ajdjyt** [comment]
and i was in the process of building the colossal chest so every time the world loads i load right next to the unfinished 17x17 colossal chest, could it be the 9x9 one i have a few blocks above

**Comment by ajdjyt** [comment]
Im using mcedit 2.0 ,if there is a legacy version kindly tell me where to download it

**Comment by scalda** [comment]
you would have to look at the coords for the block in question from the crash report to know which one

**Comment by ajdjyt** [comment]
Ok thnx

**Comment by ajdjyt** [comment]
im updating to 1.3.2 as we talk

**Comment by ajdjyt** [comment]
thnx for all the help

**Comment by scalda** [comment]
you are very welcome please let me know how it goes.

**Comment by ajdjyt** [comment]
ok

**Comment by CakeArmy** [comment]
Also real quick, the first letter of every word Does Not Have To Be Written Like This, Just Nouns And The Beginning Of Sentences For Simplicitys Sake

**Comment by ajdjyt** [comment]
Sorry for replying so late scalda but it is working now {look at my capitalization for cakes, sake)
