### ISSUE TITLE
continuation, forge-1.10.2-12.18.3.2254-universal wont run

### ISSUE THREAD

**Issue by joransyoghurt** [scalda/FoolCraft#353]
forge-1.10.2-12.18.3.2254-universal wont run

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
I made a earlier thread but that got closed down because of 1.3 but that one isnt on twitch yet,
and I want a server for 1.2 i got a screen with this on from my start,bat file from the previous mentoined thread 
<img width="1280" alt="info" src="https://cloud.githubusercontent.com/assets/27782005/25340029/bd395f98-2904-11e7-978e-bd5fe18f1fbe.png">

**Comment by Mrtenz** [comment]
Make sure you have all files in the /libraries folder.

**Comment by scalda** [comment]
Hi, i have found the bug that was causing the world errors and 1.3.2 is uploading now and under review. please BACKUP your world first before updating.

Thanks in advance

Scalda

**Comment by Mrtenz** [comment]
@scalda This is not a world corruption issue, the /libraries folder or files in the folder are missing.

**Comment by joransyoghurt** [comment]
I dont have a libraries folder in my server folder
<img width="1280" alt="info2" src="https://cloud.githubusercontent.com/assets/27782005/25341786/4c6635c4-290a-11e7-9300-8663fd46ac63.png">

**Comment by scalda** [comment]
Yes and the libraries folder is in the new server files i have just uploaded for 1.3.2

**Comment by joransyoghurt** [comment]
but I cant download 1.3 only 1.3.2,

**Comment by scalda** [comment]
thats because 1.3.2 is the only 1.3 version there is

**Comment by joransyoghurt** [comment]
but its only a patch not the full mod... @scalda

**Comment by scalda** [comment]
[1.3.2 server files here](https://minecraft.curseforge.com/projects/foolcraft/files/2411320)

**Comment by joransyoghurt** [comment]
but what do i need to do with those files? @scalda

**Comment by colin500** [comment]
well i would think extract the .zip

**Comment by joransyoghurt** [comment]
i did that and got the overrides manifest and modlist nothing more

**Comment by colin500** [comment]
whats inside them?, i see the modlist is a html document.

**Comment by joransyoghurt** [comment]
it shows links to the websites of the mods in the pack

**Comment by colin500** [comment]
ok but the overrides folder?

**Comment by joransyoghurt** [comment]
its holds only one mod foamfix and the config has alot of stuff but not a java executable

**Comment by joransyoghurt** [comment]
yes

**Comment by colin500** [comment]
im not sure but @scalda does @joransyoghurt just replace the old foamfix with the new one from 1.3.2?

**Comment by joransyoghurt** [comment]
the only other full version of the mod 1.2...... there is no 1.3 only 1.3.2

**Comment by colin500** [comment]
i would think you would just replace the old foamfix with that one but im unsure.

**Comment by joransyoghurt** [comment]
replace what..... i dont have a 1.3 server only 1.2 that wont start

**Comment by scalda** [comment]
Please use the link I provided that goes straight to the page to download the server files it is 177MB in size

**Comment by joransyoghurt** [comment]
but that file has no way to start a server only overrides modlist and a manifest @scalda

**Comment by joransyoghurt** [comment]
this is what i get from the link you provided.

and the 1.3.2. is the file i unziped and is still in the folder
<img width="1280" alt="info3" src="https://cloud.githubusercontent.com/assets/27782005/25344807/8538ee7e-2913-11e7-9176-841226d6ebc5.png">

**Comment by scalda** [comment]
And that is 177MB in size

**Comment by joransyoghurt** [comment]
yes

**Comment by joransyoghurt** [comment]
I fixed the server file issue i mixed server and mod files srry, but now i have the this:

Mod rejections [FMLMod:simplyconveyors{1.4.1}

**Comment by scalda** [comment]
ok i am uploading a new set of files for the server looks like there was a oversight on my part with the wrong mod version. will post link when done

**Comment by scalda** [comment]
[1.3.2 hotfix server files](https://minecraft.curseforge.com/projects/foolcraft/files/2411360)
