### ISSUE TITLE
Foolcraft 1.3.2 SimplyConveyors version mismatch

### ISSUE THREAD

**Issue by cyrilrbt** [scalda/FoolCraft#354]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

The server download for Foolcraft 1.3.2 has SimplyConveyors 1.4.2, but the client has 1.4.1.

## Reproduce Steps

1. Download the 1.3.2 server files
1. Run the server
1. Install the 1.3.2 client
1. Try connecting to the server
1. Get an error message about version mismatched

## Additional Information

I tried replacing the mod in my server's `mods/` by deleting 1.4.2 and putting 1.4.1, but it doesn't seem to fix the issue.

**Comment by cauliflower69** [comment]
You need version SimplyConveyors-1.10.2-3.0.3

**Comment by scalda** [comment]
ok i am uploading a new set of files for the server looks like there was an oversight on my part with the wrong mod version.

**Comment by cyrilrbt** [comment]
Awesome, thanks!

**Comment by scalda** [comment]
NP
