### ISSUE TITLE
Copper Essence not implemented/Agricraft problems

### ISSUE THREAD

**Issue by BIG-G99** [scalda/FoolCraft#355]
- [X] I am running the latest version of FoolCraft
- [X] I am running FoolCraft via Curse/Twitch Launcher
- [X] I can reproduce this issue consistently
     - [ ] In single player
     - [X] In multiplayer
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Copper essence has no use. 
Copper seeds have been grown up to 10/10/10 using a standard Agricraft setup, however at this point in time there seems to be no uses with the resulting copper essence. 
Also while on the subject of seeds and Agricraft - Manyullyn seeds also do not appear to work with crop sticks. The seeds can be placed down on tilled dirt with no crop sticks - but once crop sticks are placed it seems we are unable to then plant the seed - therefore these seeds can not be bred.

**Comment by scalda** [comment]
what version of the pack are you using?

**Comment by BIG-G99** [comment]
Foolcraft ver 1.2.2,

**Comment by scalda** [comment]
please update to 1.3.2

**Comment by BIG-G99** [comment]
OK no problem, will do so and report back, thanks.

**Comment by BIG-G99** [comment]
All seems to be good with the updated version of the pack after a quick test. Keep up the good work and thanks for the speedy reply. Will update you further if we find any further problems. Thanks again.
