### ISSUE TITLE
queries and questions

### ISSUE THREAD

**Issue by Pr0ti0us** [scalda/FoolCraft#356]
This is more of a question then a issue but as my farms use the mechanical user i have to ask why it was disabled in the new update.?

**Comment by Kerellian** [comment]
It randomly causes the world to corrupt, depending on the setting of the unit and if there is an issue of when it gets an entity infront/on it that the game crashes

**Comment by Pr0ti0us** [comment]
hm i may not update then my farm is dependant on it to harvest

**Comment by Kerellian** [comment]
they added a new Mod pack to handle this . Progressive automation . it can harvest as well i believe

**Comment by scalda** [comment]
yes progressive automation was added to be able to milk the moo fluid cows and also farm the agricraft crops

**Comment by Pr0ti0us** [comment]
thx good to know
