### ISSUE TITLE
World Crashes Upon Startup

### ISSUE THREAD

**Issue by Morphosiz** [scalda/FoolCraft#357]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [X] I am requesting help with installing or running the pack

## Issue Description
After updating the new patch, I logged in. It crashes even before the world could load.

## Additional Information
The game crashed whilst exception ticking world The game crashed whilst exception ticking world Error: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

As for the crash report, I tried clicking the view crash report button on the minecraft launcher but nothing appears.
![image](https://cloud.githubusercontent.com/assets/26901937/25350781/d5b1668e-2958-11e7-83ef-8e9edc50299c.png)

**Comment by fabri2000779** [comment]
it happend the same to me, server start but when someone log in after some minutes server crash for the same problem, so i downgrade again to 1.2.2

**Comment by Morphosiz** [comment]
Well, it's big patch, I am not surprise there will be issues

**Comment by fabri2000779** [comment]
@Morphosiz the problem isnt the partch at all, the dev are news so they appear to be new on this theme, sorry if i offend one of the devs here but i have a big community and i dont have time to errors and they make alot of mistakes with these new version.

The best example that i can give you is FTB Beyond, this pack is on alpha basicaly but never i get problems updating my server and they make alot of changes with every update. Im kinda angry with the foolcraft dev because well i decide too update and boom alot of problems come

**Comment by Morphosiz** [comment]
Well, first of all, the dev team may be new, that's fine. Everybody got to start somewhere, am I right? We are humans, we make mistakes. Yes, you have a big community, but you are not the only one with it. I am sure many of the fools on the foolcraft series have their own as well as many people out there. If you don't have time to let them figure out what went wrong, then may be you should reconsider your current position. I am sure the people in your community will be able to accept that the pack currently have issues if you explain it to them.  Cheers

**Comment by Morphosiz** [comment]
I have faith in iskall and his dev team. Give them some time to solve the issue.

**Comment by fabri2000779** [comment]
@Morphosiz yeah its okay and im not saying that they do a bad pack, to be honest is one of the best packs that i played the only that i that i cant recommend to them is be more careful and test more the comming update

**Comment by Furgl** [comment]
Could you please attach the crash report file? You can find it by going to the FoolCraft profile in the Curse/Twitch launcher, clicking the '...' button in the top right, then Open Folder, and it should be in the crash-reports folder from there.

**Comment by fabri2000779** [comment]
[crash-2017-04-24_12.51.17-server.txt](https://github.com/scalda/FoolCraft/files/952835/crash-2017-04-24_12.51.17-server.txt)
that is my server crash report

**Comment by scalda** [comment]
This is a moo fluid cows crash, please see here for what this person did to fix it in his world. [here](https://github.com/scalda/FoolCraft/issues/324)

**Comment by fabri2000779** [comment]
@scalda so i want to ask, do you have planned another update soon, i want to know because i want to see if update or wait, what do you recommend me, and my other question is there isnt another way to fix this because my map size is like 8GB so it is heavy to download do mcedit and reupload that going to take me much time, there is another way? you think is possible that the next update you can fix this error?

**Comment by scalda** [comment]
sadly with moo fluids there is no fix other than that due to the fact it registers the fluids that forge add and there is one that seems to have changed the name and this is causing the crash with them.

**Comment by Morphosiz** [comment]
Well, good freaking job fabric, you came here and hijacked my issue and cause the admin to close the threat without solving my issue

**Comment by Morphosiz** [comment]
Next time, get your own freaking thread, heading a community and yet so freaking desperate? One hell of a useless person

**Comment by fabri2000779** [comment]
@Morphosiz sorry for that man, @scalda the problem isnt resolve. he probably going to re open it

**Comment by Morphosiz** [comment]
Sorry for the outburst just now @fabri2000779. So what did you do in response to the problem?

**Comment by fabri2000779** [comment]
@Morphosiz tomorrow i going to put the foolcraft server to maintenance to fix this proble, if you read up the solution is use mcedit and kill all the cows of the world, give me your complete crash report to take a look to see if you have the same problem

**Comment by Morphosiz** [comment]
@fabri2000779, yes I saw. Alright will do so later.

**Comment by Morphosiz** [comment]
Thank you

**Comment by Morphosiz** [comment]
[crash-2017-04-25_01.43.51-server.txt](https://github.com/scalda/FoolCraft/files/953693/crash-2017-04-25_01.43.51-server.txt)
That's my crash report

**Comment by fabri2000779** [comment]
@Morphosiz you have the same crash that my so you can fix it with mcedit

**Comment by Morphosiz** [comment]
@fabri2000779 I tried using mcedit, but all I am seeing is pink blocks with question marks. And my fluid cows are not there. What should I do to get past that?

**Comment by fabri2000779** [comment]
@Morphosiz i made a new ticket for you

**Comment by Morphosiz** [comment]
Alright thank you

**Comment by fabri2000779** [comment]
@Morphosiz well to be honest the mcedit didnt resolve my problem so i reset the world, hope that the next update they be more careful

**Comment by Morphosiz** [comment]
But did you manage to load the modded blocks in mcedit?

**Comment by fabri2000779** [comment]
@Morphosiz ohh i understand what you mean, yeah it is normal that the blocks in mc edit had the ? simbol so dont worry with that

**Comment by Morphosiz** [comment]
But my fluid cows are not there as well, although when I click on the area where the cows are at, the entity data appears

**Comment by Morphosiz** [comment]
I went to do some research, it may be due to the dawnstone fluid cow from the embers mod that is causing the crash

**Comment by fabri2000779** [comment]
@Morphosiz try killing all the entities

**Comment by Morphosiz** [comment]
I tried to remove individual entity, it gives me an error report

**Comment by fabri2000779** [comment]
could you give me your error report?

**Comment by Morphosiz** [comment]
MCEdit version: 2.0.0-beta7
Python version: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
Platform: win32
System version: Windows-8.1-6.3.9600
Processor: Intel64 Family 6 Model 69 Stepping 1, GenuineIntel

Obtained a GL context with this format:
Valid: True
Version: 4.5
Hardware Accelerated: True
Depth buffer: True, 24
Double buffer: True
Rendering profile: PySide.QtOpenGL.QGLFormat.OpenGLContextProfile.CompatibilityProfile

Driver info:
GL_VERSION: 4.5.0 NVIDIA 373.06 (4, 5)
GL_VENDOR: 'NVIDIA Corporation'
GL_RENDERER: 'GeForce 820M/PCIe/SSE2'

------

Unhandled Exception

Traceback (most recent call last):
  File "mcedit2\widgets\inspector\__init__.py", line 267, in removeEntity (self is a InspectorWidget)
  File "mceditlib\worldeditor.py", line 83, in remove (self is a EntityListProxy)
  File "_abcoll.py", line 689, in remove (self is a TAG_List)(named Entities)
  File "_abcoll.py", line 628, in index (self is a TAG_List)(named Entities)
ValueError
