### ISSUE TITLE
lag/stuttering server (portforwarded server)

### ISSUE THREAD

**Issue by joransyoghurt** [scalda/FoolCraft#359]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
I just made a server on foolcraft and the game lags and stutters alot the frames are fine (except when i die) but the lag is not in breaking blocks but when moving and other mobs or players and when i load new chunks the game sometimes times out (maybe a RAM or memory problem?) (and how do I allocate more RAM or memory to the server)

**Comment by joransyoghurt** [comment]
@scalda help

**Comment by fabri2000779** [comment]
i have the same issue and im in a dedicate server 8GB RAM with a i7-4600

**Comment by scalda** [comment]
please take a look at the tps server profiling on the wiki
