### ISSUE TITLE
Hermitron Dupe Glitch

### ISSUE THREAD

**Issue by djbruno1** [scalda/FoolCraft#36]
open a hermitron box
have your hotbar full then a non stackable item in your inventory (not hotbar) 
place the item you want duped below it (not hotbar)
shift on non stackable then drag to item (must be stackable if wanted to be duped)
its now a stack of 64

**Comment by scalda** [comment]
please update to 1.1 version of the pack?

**Comment by scalda** [comment]
Fixed in 1.1 version of the pack
