### ISSUE TITLE
No Prices in machines Currency Mod

### ISSUE THREAD

**Issue by remco082000** [scalda/FoolCraft#360]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When I look in the vending machine/exchange machine, you can't see the price of the item. (Currency Mod

## Reproduce Steps
Make a vending/exchange machine, place it down, set up the shop and look at the item. You won't be able to see the price.

## Additional Information
![image](https://cloud.githubusercontent.com/assets/22686088/25356280/e8f4b896-2939-11e7-85af-6019166a6108.png)

**Comment by legodude17** [comment]
Did you add the Currency Mod? AFAIK it is not in the pack.

**Comment by remco082000** [comment]
No, I didn't add the mod myself @legodude17

**Comment by Ravalli03** [comment]
@legodude17, it was added to the pack in 1.3.2 version

**Comment by legodude17** [comment]
@Ravalli03 ah ok.

**Comment by BeardlessBrady** [comment]
{Currency Mod Creator} Let me look into this. This was a prior issue with NEI not implementing tooltip changes correctly

**Comment by BeardlessBrady** [comment]
It seems to be an issue with NEI (Again). They fixed it on the 1.11 version but not the 1.10.
I've noticed a few modders posting issues to their tracker, and Ill let them know again. Hopefully will be fixed soon. Sorry for the issue

**Comment by scalda** [comment]
Thanks @BeardlessBrady

**Comment by scalda** [comment]
Mod issue.
