### ISSUE TITLE
Railcraft update to 10.1

### ISSUE THREAD

**Issue by Mrtenz** [scalda/FoolCraft#361]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I would like Railcraft to be updated to 10.1(.1), because it adds a lot of the features that Railcraft for Minecraft 1.7 had.

Here is a video showing the new Railcraft stuff: https://www.youtube.com/watch?v=iG3Dv5wxTu4

## Reproduce Steps
-

## Additional Information
-

**Comment by chland** [comment]
Uhm? Railcraft is already part of the pack.

**Comment by Mrtenz** [comment]
Currently it is using Railcraft 10.0, like I said I would like it to be updated to 10.1.

**Comment by scalda** [comment]
Yeah it was released just before the release of 1.3.2 so didn't have time to test but it is on our list to be updated

**Comment by chland** [comment]
Ah, sorry - didn't realize you meant updating from 10.0 to 10.1

**Comment by scalda** [comment]
on our list to update in 1.4
