### ISSUE TITLE
Can't add Optifine in new version.

### ISSUE THREAD

**Issue by Zepatt** [scalda/FoolCraft#362]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
My computer isn't too good, so I always use Optifine mod to be able to have more options in the video settings and be able to get more fps while playing. Optifine mod allows me to get better performance and I have been using that mod before in the Foolcraft 1.2.2 version. When I tried to put Optifine into this new version of Foolcraft, my game keeps crashing and doesn't allow me to play until I don't delete Optifine from the mod folder. This is a big deal to me as I went from having smooth 40-60 fps to getting fps from 10-30.

## Reproduce Steps
Download Optifine 1.10.2 version, put it in Foolcrafts mod folder, launch the game and you will get a message saying that there was a crash.

## Additional Information
For some reason when I press "View crash report" it doesn't show anything, but I still screenshoted this in case it helps.

**Comment by chland** [comment]
What version of Optifine are you trying to use? I just tested OptiFine 1.10.2 HD U D7 and it worked.

**Comment by Zepatt** [comment]
I am using OptiFine 1.10.2 HD U D4, Im gonna try the D7, see if that makes a difference.

**Comment by scalda** [comment]
Optifine d7 is the version you need for 1.3.2
