### ISSUE TITLE
Compacting drawers. my bone blocks turned into pressure plates lol

### ISSUE THREAD

**Issue by ANTdentarg** [scalda/FoolCraft#364]
This is not an issue with foolcraft.

This has to do with how storage drawers assigns item IDs to compacting drawers.
Just a warning to those that don't know. when you add/remove item IDs from the id list, the compacting drawers' item may change. You'll need to empty (withdraw what should be there, not what shouldn't) the drawer, then put it all back to fix.

Updated from 1.2.2 to 1.3.2

**Comment by scalda** [comment]
<img src=https://gyazo.com/20cb29624c36e3cf70623a20eea24b3a.png>

**Comment by ANTdentarg** [comment]
that's good to know about tiny progressions. Did they have iron nuggets too? Because I had a compacting drawer for iron where the nuggets turned into a progressive automation "wither upgrade".

**Comment by scalda** [comment]
Could be

**Comment by scalda** [comment]
Tiny progression issue with the change of ids sorry
