### ISSUE TITLE
Clicking full changelog on 1.3.2 sends 404 error

### ISSUE THREAD

**Issue by CakeArmy** [scalda/FoolCraft#365]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When clicking full changelog under the 1.3.2 release you get a 404 error from github.

**Comment by ANTdentarg** [comment]
https://github.com/scalda/FoolCraft/blob/master/ChangeLogs/FoolCraft_ChangeLog.pdf

**Comment by CakeArmy** [comment]
I already know the changes. Just pointing it out...

**Comment by CakeArmy** [comment]
Thanks anyways

**Comment by scalda** [comment]
Yeah the link was changed, i think it got updated to the correct link lat last night gmt time
