### ISSUE TITLE
Doors everywhere?

### ISSUE THREAD

**Issue by Jinxhoney1113** [scalda/FoolCraft#366]
- [x ] I am running the latest version of FoolCraft
- [ x] I am running FoolCraft via Curse/Twitch Launcher
- [ x] I can reproduce this issue consistently
     - [x ] In single player
     - [ ] In multiplayer
- [ x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.

## Issue Description
So, I updated foolcraft today, was super excited, then for some reason it was being super slow, going from 60 fps to 0, I didn't have that issue in the previous version, got frustrated and walked away, came back reloaded my game and every where there was doors. on all the trees, on ground, just doors everywhere, my slime island turned into seared bricks and now i have a crash that said 
The game crashed whilst tesselating block model
 Please help?! I have no clue why it is doing this and am really unsure how to fix it. 
Everything was running amazing in the previous version. 

## Reproduce Steps Not a clue, was lagging

![2017-04-24_16 30 36](https://cloud.githubusercontent.com/assets/27980582/25363313/658243fa-290e-11e7-9b52-e8322e5e332e.png)
![2017-04-24_16 30 57](https://cloud.githubusercontent.com/assets/27980582/25363311/657ecc98-290e-11e7-99be-ddff936849b5.png)
![2017-04-24_16 31 03](https://cloud.githubusercontent.com/assets/27980582/25363309/657d3bb2-290e-11e7-9d98-da2a85d35689.png)
![2017-04-24_16 31 13](https://cloud.githubusercontent.com/assets/27980582/25363312/6581e5fe-290e-11e7-9ed7-f4b3ae96562d.png)
The picture above this text used to be blueberry bushes
![2017-04-24_16 31 36](https://cloud.githubusercontent.com/assets/27980582/25363310/657dab4c-290e-11e7-8741-92f77569b38e.png)
![2017-04-24_16 31 43](https://cloud.githubusercontent.com/assets/27980582/25363314/65844754-290e-11e7-993b-a0747627f0ab.png)
The pic above and below are what used to be my slime island
![2017-04-24_16 34 45](https://cloud.githubusercontent.com/assets/27980582/25363315/65a75e4c-290e-11e7-80b0-0ba812054679.png)
This was a cloud that held one of the pets.
[crash-2017-04-24_16.34.52-client.txt](https://github.com/scalda/FoolCraft/files/953500/crash-2017-04-24_16.34.52-client.txt)

 I exited, then when i came back bam doors everywhere.

**Comment by scalda** [comment]
Is this in the new version of the pack 1.3.2. as this issue with the world corrupting was fixed, so unless somehow you have the old blockarmor.cfg file. i'm not sure what to suggest.

as for the crash that's a rendering issue remove optifine and reload the pack and it won't crash with that again

**Comment by Jinxhoney1113** [comment]
This is the new version, it wasn't acting so, wonky before I updated. It had a few bugs, but nothing like this. If I uninstall, foolcraft completely and reinstall, will it get rid of all of the old files?

**Comment by scalda** [comment]
have you not got a backup from 1.2.2?

**Comment by Jinxhoney1113** [comment]
lol, of course not that would be the easy solution. I am gonna be honest and say, I am just learning all of the technical side of running a modded game. I have no clue how to remove optifine, I had (until yesterday and had to figure it out) no clue where curse even put the save game and screen shot files. I used to have someone who would help me with all of this, but that is no longer an option for me. I'm trying really hard to figure this stuff out. It is coming to me slowly, but, when everything goes wrong, like it did yesterday, I have no clue what the heck to do. I am sure that there is a back up somewhere, (I have noticed while playing foolcraft that it backs up the world.) But I don't know where that is kept, or if that was affected by what happened yesterday. I will say I was smart in starting a new world with the 1.3.2 version, because I knew y'all were gonna make a ton of changes. I just need some advice/help/guidance. Because I just don't get why it all went sideways yesterday. Like I don't understand why I would be having rendering issues all of the sudden, when I had none before I updated the pack, and now I am having the same issues on smaller, much less complex packs too. So, yeah, please any help would be appreciated.

**Comment by legodude17** [comment]
The backups should be in the same directory as the screenshots directory in a backup directory.
