### ISSUE TITLE
World Corruption update from 1.3.1 to 1.3.2

### ISSUE THREAD

**Issue by thesequoiad** [scalda/FoolCraft#367]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When updating from 1.3.1 to 1.3.2 almost all of my blocks I have placed have been replaced with other blocks.  I tried it again from backup and it occurred again.

Attached is my Save.
[Setpoint 6_1-20170424-195327.zip](https://github.com/scalda/FoolCraft/files/953554/Setpoint.6_1-20170424-195327.zip)

**Comment by scalda** [comment]
when you started the world did it give you a warning about the level.dat file being bad?

**Comment by scalda** [comment]
also 1.3 and 1.3.1 were removed as they were bad. Have you added other mods to your instance?

**Comment by thesequoiad** [comment]
Yes it did.

**Comment by scalda** [comment]
ok you need to go back to 1.2.2, and then so you can see the world is all fine then you can update to 1.3.2 with whatever mod additions you have added? but if it gives you the same message again you will need to delete the blockarmor config file from the config folder

**Comment by thesequoiad** [comment]
Scalda,

Thanks for the hard work you put into this.  Since  created the world in
1.3.1 and I only have a few hours in this world I'll restart again in a few
day once the newest builds show they are stable...

If I can I'll try to and resolve it with what you suggested.

Regards,
Darryn Sullivan

**Comment by janf3** [comment]
Something seems to have messed up the block/item IDs in 1.3.2
I upgraded my world from 1.2.2 to 1.3.2 and the Iron nuggets (#5113) in my compacting drawer turned into Bloodwood chestplates (#5113). Tantalum Ingots (#8426) in my Refined Storage system are now Willow Trap Doors (#8426) among other things.

Foolcraft 1.2.2
![2017-04-25_20 45 41](https://cloud.githubusercontent.com/assets/15951093/25402422/f710707c-29f8-11e7-9e51-a940ac54e2ee.png)
Foolcraft 1.3.2
![2017-04-25_20 45 35](https://cloud.githubusercontent.com/assets/15951093/25402405/e82a48a8-29f8-11e7-8763-e33fc96f9d96.png)

**Comment by PSILONCRAFT** [comment]
Have the same issue

**Comment by scalda** [comment]
This is due to tiny progressions, modern warfare, simply conveyors all have done a mass rewrite of their item names sorry
