### ISSUE TITLE
Mod Suggestion for conflicting items/blocks

### ISSUE THREAD

**Issue by colin500** [scalda/FoolCraft#368]
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [ ] In single player
     - [ ] In multiplayer
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

https://mods.curse.com/mc-mods/minecraft/238123-stimmedcow-nomorerecipeconflict#t1:other-downloads
Helpful for conflicting recipes :}

**Comment by scalda** [comment]
please use pack version 1.3.2 as this is in there. thanks again for the report
