### ISSUE TITLE
Storage Drawers compacting drawer crashes Client

### ISSUE THREAD

**Issue by krisraynes** [scalda/FoolCraft#37]
(wood drawers work fine though)

**Comment by scalda** [comment]
can you provide a crash report please?

**Comment by CriticalMole** [comment]
what are you putting into the compacting drawer?
there is a common issue (in multiple packs) that an item may crash you when placed in for the first time, but if you hopper that item into it the first time then lock the drawer, you wont have any crashes putting stuff in the future
