### ISSUE TITLE
Unable to open world.

### ISSUE THREAD

**Issue by Morphosiz** [scalda/FoolCraft#370]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
The world crashes upon loading

## Reproduce Steps
Open the world, load up. Crashes upon entering the world

## Additional Information
[crash-2017-04-25_20.52.09-server.txt](https://github.com/scalda/FoolCraft/files/955100/crash-2017-04-25_20.52.09-server.txt)
That is my crash report

**Comment by scalda** [comment]
moo fluids crash please search the other issues open/closed regarding this and solutions

**Comment by Morphosiz** [comment]
Alright,  thank you scalda!
