### ISSUE TITLE
[Question] Updating to 1.3.2-Hotfix (server.properties)

### ISSUE THREAD

**Issue by lolman2810** [scalda/FoolCraft#371]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
i am about to update my server from 1.2.2 to 1.3.2-Hotfix and i have a question regarding the server.properties included in the download. ( https://minecraft.curseforge.com/projects/foolcraft/files/24113600 )

should i omit this from the upload? i would assume this will override my current one and replace settings which shouldn't be changed.
i.e.
spawn protection
seed
dificulty
motd

im sure this is an obvious question so i apologize for that but i want to make sure this update goes without problems

**Comment by scalda** [comment]
yes just omit the server properties file and use the one you already have

**Comment by lolman2810** [comment]
thanks scalda
