### ISSUE TITLE
help a noob server admin plz

### ISSUE THREAD

**Issue by joransyoghurt** [scalda/FoolCraft#373]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
I just made a server on foolcraft and the game lags and stutters/freezes alot the frames are fine (except when i die) but the lag is not in breaking blocks but when moving and other mobs or players or entities and when i load new chunks the game sometimes times out (maybe a RAM or memory problem?) (and how do I allocate more RAM or memory to the server)

**Comment by scalda** [comment]
what os are you using?
how are you starting the server?

**Comment by scalda** [comment]
duplicate #363

**Comment by joransyoghurt** [comment]
im using windows 10 and i start via forge-1.10.2-12.18.3.2281-universal executable jar file
