### ISSUE TITLE
Game fully loads then crashes.

### ISSUE THREAD

**Issue by jgerbert1983** [scalda/FoolCraft#374]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

It does it every time I try to load my world.

Latest crash report: https://pastebin.com/vxeqMrmc
I can provide 3 more from the 4 times total that it crashed on me if needed.

**Comment by Mrtenz** [comment]
TheRoBrit/Moo-Fluids#46

**Comment by scalda** [comment]
Looks like it has been reported to the mod dev. the problem is that there is a fluid registered in the config file that is no longer in the pack but it still tries and uses it. which in turn gives you the crash
