### ISSUE TITLE
1.3.2 Slimey Generator does not generate RF/does not accept slime blocks as fuel

### ISSUE THREAD

**Issue by korbiin** [scalda/FoolCraft#376]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

1. Slimey Generators no longer generate RF.  
2. Slimey Generators no longer accept Slime Blocks as fuel.

## Reproduce Steps

1. Craft or spawn in a Slimey Generator (Extra Utils 2).
2. Add slime ball (green, blue, purple, etc..)
3. Nothing happens.  No RF is generated.

- Slimey generators have no upgrades.
- Have more than enough Grid Power.

**Comment by ANTdentarg** [comment]
from ExtraUtilities2 1.4 changelog.

Slime generators now require '4 slime + a bucket of milk' to generate RF.

sorry.

**Comment by Jo-Mamma75** [comment]
Asked and answered.
