### ISSUE TITLE
Massive tps lag, refined storage takes long time to react to interactions (singleplayer)

### ISSUE THREAD

**Issue by Spacecow12** [scalda/FoolCraft#377]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
At somepoint without changing a thing im having massive tps lagg, running minimal farms and machines. Refined storages takes a long time for interactions.

**Comment by legodude17** [comment]
How much RAM did you give FoolCraft?

**Comment by Spacecow12** [comment]
11.5GB

**Comment by legodude17** [comment]
@Spacecow12 Try something more like 5-6 GB.

**Comment by Spacecow12** [comment]
You would think giving it less RAM would solve the problem?

**Comment by legodude17** [comment]
Maybe, also did you say what you assigned in the Curse launcher or what your computer has?

**Comment by Spacecow12** [comment]
Assigned 10.5 in the launcher computer has 16 GB, 11.5 was wrong excuse me.

**Comment by janf3** [comment]
Javas memory management and garbage collection can cause lag/hangs/freezes in itself.  So yes, giving it less RAM can improve your general experience. 10GB+ is way too much for any modded Minecraft - for FoolCraft something between 4-6GB is perfectly enough.

**Comment by Spacecow12** [comment]
It's not so much freezing or hangs its more the interaction with refined storage for example seems to have most issues with it...

**Comment by Spacecow12** [comment]
Assigned 6.5 GB of RAM, yet when i run the "/cofh tps" command it gives me high overworld TPS (so the world where is my farms and machines which are mostly offline)

**Comment by legodude17** [comment]
@Spacecow12 Then what is the problem? High TPS is good, it should be around 20.

**Comment by Spacecow12** [comment]
Sorry i meant high MS so basically like 60ish all the time, it takes a very long time for an interaction to happen with refined storage

**Comment by scalda** [comment]
please take a look at the wiki at the tps profiling part to help diagnose your problems
