### ISSUE TITLE
JEI Hating On "P"

### ISSUE THREAD

**Issue by ElectricBlue1** [scalda/FoolCraft#378]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Steps
     1) I go into inventory
     2) I click on JEI search bar
     3) I press P, and the gui shows up

**Comment by CakeArmy** [comment]
Its a control for enchanting or potions or something. Go into controls.

**Comment by AirForce101HD** [comment]
It happens with Utility/Cheat mode enabled.

**Comment by FeikoJoosten** [comment]
It's indeed easiliy 'fixable' by just changing the controls.

**Comment by CakeArmy** [comment]
Change your controlls

**Comment by Jo-Mamma75** [comment]
Asked and answered.
