### ISSUE TITLE
Missing item recipies and some items not functioning 

### ISSUE THREAD

**Issue by danf27** [scalda/FoolCraft#380]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

golden bag of holding not able to craft also golden lasso. also mob masher and fans seemed to have stropped functioning properly

**Comment by Ravalli03** [comment]
I have been using the mob masher and fans, without any problems. Maybe I can help you with those. What exactly is not working with them?

**Comment by Syntasu** [comment]
Golden bag is not craftable from the Refined Storage terminal because it needs XP. Try crafting it via the normal vanilla workbench. Same goes for the golden lasso. Every recipe that requires XP is not craftable from a RS grid.

**Comment by danf27** [comment]
Thank you for your help and suggestions I will give them a try

**Comment by Jo-Mamma75** [comment]
Asked and answered.
