### ISSUE TITLE
Stop milking players! Or is it refined storage?

### ISSUE THREAD

**Issue by CakeArmy** [scalda/FoolCraft#381]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Aight so I upgraded the progressive automation farmer to be a big range, put the milking upgrade in it, put 16 buckets in it, stepped over it and bye-bye! server crash. Now I am looking through the console and it says the Refined storage "Tile Controller" was "throw an exception trying to write" It might be a coincidence it is the timing but I am not sure. I had a bunch of autocrafting going, a bunch of fluid cells. I have to do 10 at a time because when trying to craft the disks fluid or item, you can't do more than 10 for some reason? It says circular loop even through I checked and there isnt. 

## Additional Information

https://pastebin.com/4zuDmzsS <--- server log
https://pastebin.com/bgThxpVi <--- crash report

**Comment by CakeArmy** [comment]
On a side note, I am getting spammed with 25.04 20:46:32 [Server] Server thread/WARN Skipping Entity with id

**Comment by legodude17** [comment]
Does this happen consistently when you step over it.

**Comment by scalda** [comment]
no response since april 26th so closing
