### ISSUE TITLE
[Mod Request] Wireless Crafting Grid

### ISSUE THREAD

**Issue by CakeArmy** [scalda/FoolCraft#382]
## SUGGESTION/HELP
- [X ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack
I would really love to have a wireless crafting grid rather than bringing network transmitters and receivers at all of my different bases (I separate things so lag doesn't build up). 
The mod can be found at
https://minecraft.curseforge.com/projects/wireless-crafting-grid

**Comment by GothCartel** [comment]
Enderio has a wireless crafting grid on its top tier inventory panel

**Comment by Jo-Mamma75** [comment]
This is already something we have in our suggestion box and are looking into.  No decision has been made yet.
