### ISSUE TITLE
testing out builds in a new world but nothing happens

### ISSUE THREAD

**Issue by tony453** [scalda/FoolCraft#383]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
every time im in my alt world testing out builds/items the machine would stop working and like everything would stop working.

## Reproduce Steps
going into creative mode doing somethings then going back to normal mode

**Comment by legodude17** [comment]
Do you have a game log or something?

**Comment by tony453** [comment]
ill reproduce the issue again and ill check the "lastest" log file yea?

**Comment by legodude17** [comment]
Yeah

**Comment by Jo-Mamma75** [comment]
What machines stop working?  I noticed on our dev server if I turned off the daylight cycle, the absorption hopper and mob mashers stopped working which was kind of weird.

**Comment by scalda** [comment]
no response since may 3rd so closing, if the issue is still persisting then please open a new issue and reference this one
