### ISSUE TITLE
foolcraft laggy/ stuttering server plz help

### ISSUE THREAD

**Issue by joransyoghurt** [scalda/FoolCraft#384]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
I made a server but is laggy and stuttering the frames also lower alot when i load new chuncks.
it is not that i need to wait for blocks that i mined to appear on the ground but when i see other entities walking they freeze for a aplit second and move on the happens with blocks also when I load some chuncks my server times out
 

## Additional Information
OS: windows 10,
i start the server via: forge-1.10.2-12.18.3.2281-universal executable jar file

**Comment by legodude17** [comment]
How much RAM does the server have?

**Comment by joransyoghurt** [comment]
how do i check that? @legodude17  @scalda

**Comment by legodude17** [comment]
It depends on the server. How did you set up the server?

**Comment by joransyoghurt** [comment]
uhm..... im very new at hosting servers so i followed a guide and asked some people... so could you be more specific plz

**Comment by fabri2000779** [comment]
@joransyoghurt are you paying a hosting or you are hosting on your PC?

**Comment by joransyoghurt** [comment]
hosting on my pc  @fabri2000779  @legodude17

**Comment by fabri2000779** [comment]
@joransyoghurt how many players normally is on in the server? you probably are using the default amount of RAM(4GB) so try to edit .bat file to put like 6GB RAM, probably that resolve your problem

**Comment by joransyoghurt** [comment]
around 3-4 players how do i change the RAM from 4 to 6 in the .bat?

**Comment by fabri2000779** [comment]
Edit your start.bat and put something like this or just edit.
@echo off
java -Xms6144M -Xmx6144M -jar YOURJARNAME.jar nogui
pause

**Comment by joransyoghurt** [comment]
ok i tried and it fixed some lag i had with the breaking of blocks, frame rate when i die and the freezing mobs, but i stil rubberband and mobs are still laggy and my server says this: cant keep up, did the system time change or is the server overloaded? running 9449  ms behind, skipping 188 tickets @fabri2000779  @legodude17  @scalda

**Comment by fabri2000779** [comment]
Looks like it is your CPU, which CPU do you have to your server and do you play in the same computer that you are hosting your server?

**Comment by joransyoghurt** [comment]
i host and play on the same pc (i had a hermitpack that worked fine)
cpu: intel core i7 6700k cpu @ 3.40ghz 3408 mhz 4 cores

**Comment by fabri2000779** [comment]
try to do this:
Clean the entities in your world, you can do it with mcedit or just add a plugin to your server.
if that doesnt work try to tell you to yours players that dont explore more for a while if the server stop skipping ticks /lag you probably will need to dedicate a CPU to your server

**Comment by joransyoghurt** [comment]
ok, i havent done much with this server so there are not that many chuncks loaded, we are just a few chuncks away from spawn but i have a old pc with i believe a i5 would that be good enough?

**Comment by fabri2000779** [comment]
what do you mean sorry, you mean host the server in another pc?

**Comment by joransyoghurt** [comment]
yes to host the server on the older pc with the i5 cpu @fabri2000779

**Comment by fabri2000779** [comment]
yeah it works and how much ram can you dedicate for the server?

**Comment by legodude17** [comment]
I would suggest 5-6GB.

**Comment by joransyoghurt** [comment]
do you know a program with wich i could acces my server via internet or something like that?

**Comment by fabri2000779** [comment]
You can use Multicraft panel that is one of the best panel for minecraft servers

**Comment by joransyoghurt** [comment]
but i have server on my pc i didnt buy one, I need a program so I can acces my server pc via my gaming pc
@fabri2000779  @legodude17

**Comment by fabri2000779** [comment]
that depend alot of your hardware, how many program are you running, more program running = more process = more resources that take the pc @joransyoghurt
