### ISSUE TITLE
Game crashed, what can i do about it?

### ISSUE THREAD

**Issue by LlamaMilk** [scalda/FoolCraft#385]
I was just flying around the world and minecraft just shut down and gave this error message:
The game crashed whilst tesselating block in world
Error: java.lang.ArrayIndexOutOfBoundsException: 64.

Does anyone know what to do about it?

**Comment by legodude17** [comment]
Please use the issue template, it is there for a reason. Also, do you have optifine installed?

**Comment by LlamaMilk** [comment]
Yeah i have, but i figured out its because the update the chunk is glitched.
