### ISSUE TITLE
Add Blood Magic to the pack

### ISSUE THREAD

**Issue by nielshenriksen** [scalda/FoolCraft#386]
## SUGGESTION/HELP
- [x ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Please add Blood Magic to the pack - Its one of my favorite mods.

**Comment by OmegaX123** [comment]
I like this suggestion - and Woot has the Blood Magic upgrades so it kind of makes sense. It seems that this modpack is a little light on the magic side (even after adding Natural Pledge) even though its description points out that it's heavily both tech- and magic-based, and Blood Magic is one of the better (stable or mostly-stable) magic mods out there other than Botania and the addons for it.

**Comment by Jo-Mamma75** [comment]
We've considered and dismissed Blood Magic in the past during the initial development of the pack due to how overused it has been in other mod packs.  I agree that with Embers gone, the pack is seriously lacking magical mods.  We are looking for some lesser know but stable alternatives.
