### ISSUE TITLE
Mod Suggestion: Mystical Agridations

### ISSUE THREAD

**Issue by Pr0ti0us** [scalda/FoolCraft#387]
suggesting a add on for mystical agriculture its called mystical agridations. its avaible thru curse/twitch.

**Comment by legodude17** [comment]
Please use the issue template, it is there for a reason.

**Comment by Jo-Mamma75** [comment]
As much as I don't appreciate you deleting the template for creating a new issue I will say that this suggestion is already under consideration.  I am closing the issue.
