### ISSUE TITLE
[1.3.2] Server crash during startup: Caught exception from LibrarianLib Stage 2 (librarianliblate)

### ISSUE THREAD

**Issue by AriinPHD** [scalda/FoolCraft#389]
## SUGGESTION/HELP
- [x] I am requesting help with installing or running the pack
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.

## Issue Description
After upgrading the server from version 1.2.2 (1.2.1 with 1.2.2 config...) to version 1.3.2, the server refuses to start. It crashes consistently with the following type of error:
[21:35:52] [Server thread/ERROR]: Encountered an unexpected exception net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from LibrarianLib Stage 2 (librarianliblate)

TROUBLESHOOTING: Thinking we did something wrong during the upgrade process we started two completely new server instances on two different systems. Both instances crashes with this error, at the same place. Consistently. The new instances were run several times, first using the old world and then it was attempted letting the server generate its own new world instead. Neither worked.

NOTE: Reverting back to 1.2.2 works fine. Server (on version 1.2.2 (1.2.1 with 1.2.2 config...)) starts normally without error.

## Reproduce Steps
1. Download the server files and extract them into an empty folder.
2. Launch the server using the provided start.bat file.
3. Server crashes during phase 2, before any files - such as eula.txt or the world - are generated.

## Additional Information

latest.log : https://pastebin.com/1Wz8yeDR
crash-2017-04-26_21.35.52-server.txt : https://pastebin.com/Kr5aaaFG

I hope the issue isn't with LibrarianLib 1.10.1 itself because this seems to be the latest version publicly available... :-\

Sincerely,
//Ariin

**Comment by legodude17** [comment]
Ref TeamWizardry/LibrarianLib#33

**Comment by CharlesVu** [comment]
Probably dupe of #363

**Comment by AriinPHD** [comment]
Thanks @legodude17 and @CharlesVu for referring to both #33 and #363 which both seem to be discussing this very issue. Perhaps close this (#389)?

**Comment by mcdodge34** [comment]
Is there a solution right now, can we update something to fix this, just curious cause I really wanna start an adventure in FoolCraft, but I can't without a standalone server running.

**Comment by CharlesVu** [comment]
Ticket is still open, so no. (you can probably roll back to 1.2.2)

**Comment by mcdodge34** [comment]
That is what I was afraid to do, wanted the new version to start, looks like I'm going to have to use an older version for now, but something tells me it won't take long before we see an update, just unsure how an error like this could have been not flagged before release, if the server can't even start, but its another story, now to get the 1.2.2 version and finally start my adventures and avoiding using the Mechanical user since it cause serious problems.

**Comment by mcdodge34** [comment]
I did some investigations, perhaps it could help you out, the mod that cause the crash is actually LibrarianLib which NaturalPledge need to work, if you remove both, the server starts normally without any problems.

**Comment by AriinPHD** [comment]
Closing. Issue is marked as bug and being tracked in #363. <-Go there. Shoo, shoo.
