### ISSUE TITLE
Custom Trees from Recurrent Complex break tree-farms

### ISSUE THREAD

**Issue by chland** [scalda/FoolCraft#39]
RC hooks into the spawning-code of vanilla saplings - that way you can get custom trees from them... unfortunatly, this breaks most tree-farms. 

_For example_: setup a farming-station from EnderIO, fill it with oak-saplings and bone-meal and watch what happens. It will use up tons of bone meal and only grow a single tree every couple of minutes. Unfortunatly, that single tree will be a giant oak which will be so huge, that the station won't be able to chop it down completely and you'll end up with floating logs and leafs.

The only way to fix this is seems to be by editing **reccomplex.cfg** and change the "**saplingTriggerChance**" from **1.0** to **0**. That way, saplings will act normally (you will still get special trees during world-gen but you won't be able to grow them using saplings).

**Comment by CriticalMole** [comment]
Should be in the next release
