### ISSUE TITLE
Something to harvest AgriCraft crops.

### ISSUE THREAD

**Issue by bhopahk** [scalda/FoolCraft#390]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I know that Progressive Automation was added and that allows for AgriCraft crops to be harvested with a Planter, but that does not appear to work. I am assuming that it is related to Sponge and this likely should go to them as well, but another way to automatically harvest AgriCraft crops would be nice since mechanical user is disabled. My problem is that I have yet to find another mod which adds a block to harvest AgriCraft crops. Maybe a mod to replace the mechanical user would work as well. 

## Reproduce Steps
Any setup with the planter which I have tried has worked perfectly fine in single player but when I go to multiplayer, it harvests the crops, but the produce just disappears.

**Comment by Maudslay** [comment]
I've also noticed this and hasn't been sorted for awhile, players on a server that i play on have the same issue. Bump

**Comment by legodude17** [comment]
This is sponges fault I am pretty sure. Does it work on a pure forge server?

**Comment by bhopahk** [comment]
I have not gotten a chance to test it on a server without forge that's why I did not say with certainty that it is sponge.

**Comment by Jo-Mamma75** [comment]
It does indeed work just fine on a pure forge server.  We have 7 servers running the pack and no problems with any of them.  I'm sorry, but this is something we cannot help you with as you are running the pack in an unsupported environment.
