### ISSUE TITLE
Replace Veinminer ?

### ISSUE THREAD

**Issue by Bennyboy1695** [scalda/FoolCraft#391]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
So as a previous issue has said about and my server has constantly been getting the issue, i propose removing veinminer and replacing it with oreexcavation as they are basically the same thing but oreexcavation doesn't have the issue with people getting mod rejections from it.

Other issue talking about veinminer is - #137 

## Additional Information

OreExcavation is here - https://minecraft.curseforge.com/projects/ore-excavation

**Comment by fabri2000779** [comment]
that can be great hope that they make the change

**Comment by Jo-Mamma75** [comment]
That's something we will take under consideration.
Thank you for the suggestion.

**Comment by Ravalli03** [comment]
I agree,  it has more options, and has undo

**Comment by bhopahk** [comment]
I second this. The mod rejection issue is quite frustrating and it has been disabled on our server to prevent allow people to play but that just causes more people to be mad :/

**Comment by Brigadon** [comment]
oops, re-reported. Same issue with new upload.

**Comment by bhopahk** [comment]
@Whazaaaaa I saw that issue and followed its trail all the way to the sponge git but it has not been resolved and that has not fixed it. We asked players to do that change and did it ourselves but still got the issue.

**Comment by scalda** [comment]
This is a problem with you running the pack with sponge.

**Comment by Bennyboy1695** [comment]
I never even said i was using sponge. I am but its not causing the issue, sponge doesn't do anything to the mod names and mod rejections. Plus i got the same issue in a purely Forge server.

**Comment by fabri2000779** [comment]
@Bennyboy1695 you would need to diseable the mod, there isnt a fix man

**Comment by Bennyboy1695** [comment]
@fabri2000779 i know, thats why i suggested changing to another mod thats basically veinminer 😛

**Comment by fabri2000779** [comment]
@Bennyboy1695 hope that they take the suggestion
