### ISSUE TITLE
Ghost Players causing players to be unable to connect

### ISSUE THREAD

**Issue by thefinaldegree** [scalda/FoolCraft#392]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I have just updated to 1.3.2 last night. The server was running for approx. 10 hours before players started reconnecting.
The first few players seemed to be able to connect just fine and were able to play.
One or two had some lag issues but we thought it was just their computers (they had the least-powerful computers on the server so it made sense at the time). Soon (within 1-2 hours) the issue spread to other players and shortly after that it was affecting all players and nobody could connect.

The connection message seems to just give the player's UUID and nothing more but the local client claims the player timed out.

## Reproduce Steps
Start the server and leave running for some time (unsure of the shortest time).
Have players connect and eventually the ghost players will start showing up. (2-3 ghost players will stop others from connecting)

## Additional Information
Server Logs: [https://pastebin.com/wp7vvKgK](https://pastebin.com/wp7vvKgK)
I am running the server through AMP (previously known as McMyAdmin) on the latest version:
"AMP Release 'TN/SR0'  v1.4.6.9, built 2017-03-31 19:33"

I can provide any further data or even a login to the server's management portal if this helps.

**Comment by thefinaldegree** [comment]
Happened again, here's the logs for this time: https://pastebin.com/gBMf8AXi

**Comment by GothCartel** [comment]
Having similar issue server being hosted by mcpro.. players lagging out, disconnecting but still showing as being connected. Unable to be kicked by server console, only way to fix issue is to stop and restart server

**Comment by thefinaldegree** [comment]
Happened-ish again. Most of the players on the server have stopped playing until this is fixed because it makes it completely unplayable.
This time the server (while sitting idle) starting eating more and more RAM until it hit the 25GB (25600MB) limit I had set in AMP.
I attempted to connect and immediately timed out, which left a ghost player connected.
Server Logs: https://pastebin.com/KC0YAKqB

**Comment by thefinaldegree** [comment]
And another time: https://pastebin.com/Jb2MLGUR

**Comment by WinterGrave** [comment]
Hi, just letting you know this issue also happens on my community server, nothing relevant that I find on the logs but will be investigating to help

**Comment by thefinaldegree** [comment]
@WinterGrave @GothCartel Hey guys, I think I managed to fix this issue by downloading the server's world and running it in SSP. Then while in SSP I flew around to all the different areas that were previously being chunk-loaded bt FTB (the map icon next to the inventory) and manually unclaimed the ones that were chunk-loading.

You should give that a go and see if it helps.
