### ISSUE TITLE
Glitchy Leaves

### ISSUE THREAD

**Issue by WyvernTime** [scalda/FoolCraft#394]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Randomly from time to time the leaves on trees are glitchy. They wobble up and down at a fast pace.

**Comment by Ravalli03** [comment]
This has been reported already, but how many mega torches do you have? This may not be the cause, but I had the gitchy leaves issue and after I moved my base, it wasnt doing it. I started placing mega torches around close to each other, and noticed the glitch came right back, I then took them all down but 1, right away and it went away I haven't tested it to see if that was actually the cause.

**Comment by Ravalli03** [comment]
#184

**Comment by Ravalli03** [comment]
Actually 184 has been closed. @scalda, this is still an issue with 1.3.2

**Comment by WyvernTime** [comment]
I have no mega torches.

**Comment by GothCartel** [comment]
Same issue as well, either with or without optifine, no mega torches in area

**Comment by janf3** [comment]
If you mean what I think you do, try turning Mipmap Levels to OFF in the Minecraft Video Settings

**Comment by Ravalli03** [comment]
@janf3, i'll try that. I also noticed doc was having the same issues in one of his videos. What's werid it does it randomly

**Comment by scalda** [comment]
Turn your mipmapping off in your videos settings, the game will lock up for a bit while it changes it's settings
