### ISSUE TITLE
Server logs - 'Skipping Entity with id' every 20 seconds

### ISSUE THREAD

**Issue by slavella** [scalda/FoolCraft#395]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
Roughly every 15-20 seconds my server is getting flooded with '[Server thread/WARN]: Skipping Entity with id' entries. I believe this is causing the server to lag and often players are getting disconnected for no reason.

## Reproduce Steps
Simply running my server will reproduce this issue.

## Additional Information
see pastebin for example of the issue in my log file - **https://pastebin.com/Rrpkrsbz**

**Comment by thefinaldegree** [comment]
I too am seeing this error. You can see it in my server logs: #392

**Comment by GothCartel** [comment]
Im having the same issue as well, has been since the first edition in fact, either with or without optifine

**Comment by TheBartimusPrime** [comment]
Just started getting this on my server as well

**Comment by scalda** [comment]
this is due to the mobs being removed that had entities in them so as the server loads chunks that they were in they will get skipped on the chunk load as they no longer exist in the pack

**Comment by TheBartimusPrime** [comment]
So is there a fix?
