### ISSUE TITLE
Progressive Automation Animal Farmer doesnt work under ground.

### ISSUE THREAD

**Issue by Boxedsolutions** [scalda/FoolCraft#396]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [*] I am requesting help with installing or running the pack

## Issue Description
When placing the farmer on the surface with grass around it works, but when moving the fluid cows down in the basement it doesnt milk them. 

## Reproduce Steps
* Craft an Animal Farmer get some fluid cows. 
* Compare the results when Animal Farmer is placed on the surface or if its underground.
* I thought it might had been that the Animal Farmer needed sunlight but still not working when digging a hole to the surface.

## Additional Information
It Might be a Progressive Automation issue.

**Comment by Boxedsolutions** [comment]
Found the solution myself. When you have the animal farm underground, you have to have it on the same level as the cows. But if you are on the surface you can dig the animal farm down. 

So it must bee something that the mod Author will have to check.

**Comment by Jo-Mamma75** [comment]
So obviously not something that we can fix.  Have you posted an issue in the Progressive Automation Github?
