### ISSUE TITLE
1.3.2 Refined Storage Transmitters Cause Lag Because of Interaction with Something in the Pack

### ISSUE THREAD

**Issue by theaardvarker** [scalda/FoolCraft#397]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Putting network transmitters down with a large refined storage system in any singleplayer or multipalyer world causing increasing tileentities and tanks the tps.  I've tested this in several singleplayer and multiplayer worlds. The issue does not happen when refined storage is the only mod installed.  Something in the pack is conflicting.  The author of refined storage speculates that something is causing the chunk to be continually reloaded.  

## Reproduce Steps
Put lots of items in the storage can be any item, and set up network transmitters.  Then wait for a while and come back and look at the low tps and high tileentities.

## Additional Information

https://github.com/raoulvdberge/refinedstorage/issues/1185

**Comment by Ravalli03** [comment]
I also have this issue. As soon as I put in a transmitter for a system I have in the nether, starting getting lag. I didn't have any lag before. I ended up setting up a wireless redstone signal with Rftools to only have it on when I need it, which helps alot with the lag.

**Comment by legodude17** [comment]
Do you have any chunk loading setup?

**Comment by theaardvarker** [comment]
@legodude17 No.

**Comment by scalda** [comment]
you need to make sure the network receivers and transmitters are chunk loaded or they will cause issues. it states on the RS website that they need to be chunk loaded

**Comment by theaardvarker** [comment]
@scalda It happens when the whole setup is at spawn and I am sitting in the chunks.  I didn't put a chunkloader at the location, but they aren't being unloaded.
