### ISSUE TITLE
[MOD REQUEST] Add Controlling mod to help with keybindings?

### ISSUE THREAD

**Issue by EldonSurefoot** [scalda/FoolCraft#398]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
There are quite a few mods in this pack that have their own keybindings. It can be difficult to tell what is conflicting with what, unless you include this mod (or another like it that I don't know about).

https://minecraft.curseforge.com/projects/controlling

**Comment by Jo-Mamma75** [comment]
I will add it to the list of suggested mods.
Thank you for the suggestion.
