### ISSUE TITLE
Avarita Neutron Pile Dupe bug

### ISSUE THREAD

**Issue by Theophidian** [scalda/FoolCraft#399]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
The Neutron Compressor does not allow any auto extraction aside from vanilla hoppers.  When using a chest, a string of hoppers and Neutron Compressors, more Piles of Neutrons appear in the chest than the Compressors produce.

## Reproduce Steps
1) Place a chest
2) Place a row of three hoppers so items from the 3rd hopper go through the other hoppers and then into the chest
3) place a single Neutron Compressor on each of the three hoppers (I believe the Compressors need a clear line of sight to the sky, but I did not test)
4) Wait until a single Pile of Neutrons is produced by each Compressor
5) Observe that each hopper has a single Pile of Neutrons in each slot and the Compressors each have a red zero in their inventory slot
6) manually extract a single Pile of Neutrons from the hopper farthest from the chest
7) observe that there is a single Pile of Neutrons in the player inventory and 4 in the chest
<p/>
<b>Note:</b> When performing this test with 10 hoppers and Neutron Compressors, 18 Piles will be put in the chest.  These are the only numbers I tested with

**Comment by CakeArmy** [comment]
Vacuum Chest / Absorption hopper does the same. I will be using this on my server because there is no other way to pipe out the neutronium (tried everything, importer, transfer node, conduit, translocators...

**Comment by scalda** [comment]
This has been fixed in the latest version of the mod but sadly we can't update to it as avarita additions haven't been updated yet but as soon  as it is both mods will be updated
