### ISSUE TITLE
[Suggestion] Add Iron Backpacks

### ISSUE THREAD

**Issue by warcollar** [scalda/FoolCraft#40]
The lack of a good portable storage system is not very pleasant for exploration as you have to keep returning to base to offload items you have collected.

Iron Backpacks appears to be a reasonable method of mobile storage and the suggestion is to add it to the modpack.

**Comment by Omegapsychosis** [comment]
I believe there are many options already in the pack that do this exact thing. EU2 Bag of Holding, Hermitron cases, ender storage chest/pouches. You can also shift-right click a chest in your base with a tinkers tool to auto transfer mined blocks back to the base to help reduce inventory clutter.

**Comment by CriticalMole** [comment]
Don;t forget the RFTools Tablet which can hold 300 stacks of items

**Comment by CriticalMole** [comment]
We are happy with the amount of portable storage already in the game, like those listed above and don't feel Iron Backpacks is rquired
