### ISSUE TITLE
Currency mod exchange machine turns into a lag machine

### ISSUE THREAD

**Issue by GothCartel** [scalda/FoolCraft#400]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

Placed down an exchange machine from currency mod and had massive amounts of lag both server and fps lag dropping to 3 fps. I was in creative mode trying to set up a bank for the server so we could trade using the currency. No crashes just becomes unplayable until the exchange machine is removed.

Literally just placing an exchange machine.

**Comment by legodude17** [comment]
What is the latest game log when this happens?

**Comment by GothCartel** [comment]
alas I don't have the log and I cant place the thing again at the moment to check as I have players on the server at the moment and I don't really want to ruin their night with an unplayable server as the 'bank' is in the spawn chunks

**Comment by BeardlessBrady** [comment]
Hey, Ill look into fixing the issue {Currency creator}.

**Comment by BeardlessBrady** [comment]
Question: Does it happen with the vending machine as well or just the exchange machine?

**Comment by GothCartel** [comment]
Havent actually placed the vending machine will test it later this evening after work and let you know



Sent from my Samsung Galaxy S6 - powered by Three


-------- Original message --------

**Comment by BeardlessBrady** [comment]
It most likely will, I am looking into the problem. When I fix it do you mind if I contact you to test the build and see if it is fixed on your end?

**Comment by GothCartel** [comment]
Sure no probs.. I have a pretty robust server running.. kinda spent a bit too much on it oops.. so if it breaks the one we are using it will probably break other peoples

On 29 Apr 2017 09:07, BeardlessBrady <notifications@github.com> wrote:

It most likely will, I am looking into the problem. When I fix it do you mind if I contact you to test the build and see if it is fixed on your end?

**Comment by GothCartel** [comment]
Just tested both the exchange and vending machine with myself and another player.. dropped from a steady 120fps to 4 with both of the items placed individually



Sent from my Samsung Galaxy S6 - powered by Three


-------- Original message --------

**Comment by BeardlessBrady** [comment]
Assumed as much. Looking into it

**Comment by BeardlessBrady** [comment]
Hey Goth, is there a better way we could speak, discord or skype? I want to isolate and fix this issue but its hard to do so when I can't tell if its working or not (Since It doesnt effect my fps much or at all).

**Comment by BeardlessBrady** [comment]
I added you, get in touch :)

**Comment by GothCartel** [comment]
Issue seems to have fixed itself, may have been linked to the chickenchunks lag from the strange unknown entity being created.. Brady kindly came onto the server and had a look and its all good so far so I am closing the issue and in our case classing it as fixed.. Thanks Brady :)
