### ISSUE TITLE
(Suggestion) Update More chickens to 1.1.3

### ISSUE THREAD

**Issue by Ravalli03** [scalda/FoolCraft#401]
## SUGGESTION/HELP
- [ x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Additional Information

Would like to request More chickens Mod to be updated to 1.1.3 as it has added 20+ new chickens. 

minecraft.curseforge.com/projects/more-chickens/files/2412696

**Comment by Maudslay** [comment]
I also think this should be updated because it'll introduce new fixes in the mod and bring in the new API which is amazing and Bump

**Comment by Jo-Mamma75** [comment]
Wait for version 1.4 of the pack.
