### ISSUE TITLE
Client memory leaks when connected to a server

### ISSUE THREAD

**Issue by Hoff2567** [scalda/FoolCraft#402]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description

Pack runs perfectly fine with no leak whatsoever in a single player world but on a server clients java ram and/or virtual ram leaks as high as 32GB. The leak is slow initially, ~0.5MB every few seconds but as more players are on the server the leak can quickly go to 2-5MB a second.

## Reproduce Steps

Install the pack on a server and client then join the server with the client. 

## Additional Information

The server has TickProfiler and DiscordChat installed on it but I have tried removing both as well as connecting with a client that has both installed. Additionally I have tried running the pack without BlockArmor and NEI in attempts to fix it to no avail.

**Comment by Murder9** [comment]
I have the same problem, I get about an hour worth of playtime on the server then my memory jumps to around 10Gb and my game crashes. I have 14Gb of ram installed with 5Gb Allocated to MC. I am running on a modified version of Foolcraft. But seens how this post already exists i don't think that is the extra mods.

**Comment by Ostert** [comment]
Looks like i'm getting the same issue on my single player. After a few hours with the game up, things start crashing because of low memory. Foolcraft is set up to use 5 gigs of memory. And my computer has 16Gigs  total. This did not happen before i updated to 1.3.3.

**Comment by McSassyK** [comment]
I'm having the same issue on my server. Memory keeps going up and up until I get an out of memory error and the server crashes. I have 6 gb of memory on my server and only two people playing on it. Restarting the server knocks it back down to around 3.5 gb but after a couple of hours it's right back up there again. Constant server restarts only way to keep playing on 1.3.3.

**Comment by Rahjja** [comment]
Same with me. No one seems to be responding to these memory issues. Have any of you found a solution elsewhere?

**Comment by scalda** [comment]
This is really strange as we run 7 foolcraft servers and don't have this problem at all

more information like OS, added mods, and any other information would be very helpful

**Comment by scalda** [comment]
We have found the mod that is memory leaking please try 1.4.4 beta and see how it goes, if you don't want togo beta just remove more player models from the pack

**Comment by guestds** [comment]
can you try finding a way to fix the leaks while not removing MPM please?

**Comment by scalda** [comment]
Sorry, but it was mpm that was causing all the memory leaks that are now. this is why it has been removed from the pack permanently. sorry for the inconvenience
