### ISSUE TITLE
old save dont have all the new blocks after update to 1.3.2

### ISSUE THREAD

**Issue by TheGiliEllen** [scalda/FoolCraft#403]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
i just updated to the lates version of foolcraft and i wanted to continue my old save, so i copued the folder from the save file to the new version saves folder, but when i tried to open it it said : "forge mod loder detected missing blocks/items/ there are 416 missing blocks and items in this save, if you continue these missing blocks\items will get removed. " and then a list of blocks. is ther any way to continue with my old save and not restart the game? i searched anywhere for an answer and i couldn't find it, sorry if this was answered before... waiting for your help.

## Reproduce Steps

it gives you two options of yes and no, if you press no, the world won't start and you go back to the main menu.

**Comment by Ravalli03** [comment]
You can still hit yes and your save will be fine. Some mods were removed during the update, embers, railcraft ore, etc. You just will no longer have those items, if you had any of them to begin with.

**Comment by Ravalli03** [comment]
If you go to the change log of version 1.3, you can see what was removed or disabled.

**Comment by TheGiliEllen** [comment]
thank you!

**Comment by Ravalli03** [comment]
If it worked, you should close this issue.
