### ISSUE TITLE
Ender Dragon drops 2 dragon eggs

### ISSUE THREAD

**Issue by janf3** [scalda/FoolCraft#406]
- [x] I am running the latest version of FoolCraft
- [ ] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
This is a re-file of #183
In 1.3.2 the Ender Dragon still drops 2 dragon eggs

## Reproduce Steps
spawn the dragon, kill the dragon (-:

## Additional Information

removing or commenting out the line `main.addItemEntry(<minecraft:dragon_egg>, 100);` in "scripts/04-Loot-entitiesbossdragon.zs" solves the issue

**Comment by datitisev** [comment]
You can see this in docm77's video at https://youtu.be/CF1_6FM8ZE0?t=7m50s

**Comment by Ravalli03** [comment]
It's not a bug. It is dropping 2 eggs due to Draconic Evolution, which is working as intended. Eggs are used for DE crafting.

**Comment by janf3** [comment]
Draconic Evolution doesn't make the dragon drop 2 eggs. It just makes the dragon drop one every time a dragon is killed. If you deactivate LootTweaker in your Foolcraft instance you will find that the dragon only drops one egg.

**Comment by Ravalli03** [comment]
I get what you mean, was thinking you would get 2 eggs the 1st time killing it, 1 from MC, 1 from DE, but it's dropping 2 everytime.

**Comment by scalda** [comment]
Fixed for 1.4
