### ISSUE TITLE
Agricraft missing dependant mods

### ISSUE THREAD

**Issue by shadowtam** [scalda/FoolCraft#408]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I updated to the newest version today and when I tried to run the game and as its loading I get the error: AgriCraft is missing mods it depends on. Include the following mods or remove AgriCraft. infinitylib 1.10.2-0.8.0 or above

## Reproduce Steps
Play Foolcraft from Twitch lancher

## Additional Information
[http://imgur.com/a/8ePSv](url)

**Comment by Hoff2567** [comment]
Install the pack fresh. Infinitylib 0.80 is already in the pack.

**Comment by Jo-Mamma75** [comment]
Asked and answered.
