### ISSUE TITLE
Client Crash - Rendering Ingredient - AgriCraft?

### ISSUE THREAD

**Issue by inctor** [scalda/FoolCraft#409]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

Client crashing when searching in JEI after typing the letters EN.

- Start up a server
- Remove NaturalPledge and LibraryLib as they cause server crash in 1.3.2
- On the client, go to JEI and search for "EN"
- Client crashes

Pastebin: https://pastebin.com/W8RLmgzy

**Comment by phantomora** [comment]
i was having the same issues. i changed from jei to nei havent had a problem since.

**Comment by legodude17** [comment]
Try reporting this to both JEI and agricraft.

**Comment by scalda** [comment]
I can not reproduce this
