### ISSUE TITLE
RFtools builder doesnt work when put in quarry card

### ISSUE THREAD

**Issue by Spacecow12** [scalda/FoolCraft#411]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [X ] I am requesting help with installing or running the pack

## Issue Description
Whenever i put the RFtools on quarry mode (with a clearing quarry card) configured as a solid box, yet it doesnt seem to appear as a solid box and the builder doesnt quarry anything.

## Reproduce Steps
Set region, power builder and give redstone signal

**Comment by janf3** [comment]
The preview ghost blocks never form a solid box, they only give you the outline of the area.
Make sure there is an inventory e.g. chest above the builder to put the mined blocks in. 

For testing I would disable (no red cross) the voiding of blocks.

**Comment by scalda** [comment]
mob issue. closing
