### ISSUE TITLE
[MOD REQUEST] Flux Networks

### ISSUE THREAD

**Issue by SaddYT** [scalda/FoolCraft#413]
Flux networks allows for wireless RF and simplicity in it's fullest!
This also adds the possibility for a sort of addition to multiplayer.

https://minecraft.curseforge.com/projects/flux-networks

**Comment by Ravalli03** [comment]
Ender io and a few other mods in the pack have wireless rf

**Comment by SaddYT** [comment]
its just a bit better with networks and stuffs.

**Comment by CakeArmy** [comment]
+1 agree

**Comment by Jo-Mamma75** [comment]
Already in the list of mods to be considered. In fact, I think this particular issue is a duplicate as it was suggested a long time ago.  We just haven't had time to test it in the pack yet.  I'm going to close this issue for now but know that it is something we are considering.
