### ISSUE TITLE
Loot in Roguelike Dungeons is "broken" (Fix included)

### ISSUE THREAD

**Issue by chland** [scalda/FoolCraft#414]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

All chests in Roguelike Dungeons only contain vanilla-loot.

## Reproduce Steps

Create a new world, find a dungeon, go to the lowest level, and open the chests.

**Comment by chland** [comment]
OK, I figured out whats wrong. Two of the JSON-files contain invalid data.

In **_loot_level4.json**:

`> {"data"` : {"name" : "vc:frames/airshipframe", "meta" : 26}, "weight" : 1}

(unknown item) and in **_loot_all_levels.json**:

> {"data" : {"name" : "embers:ingotDawnstone", "min" : 1, "max" : 3}, "weight" : 1},

(again, unknown item). If you remove these lines, Dungeons will generate as expected.

**Comment by Jo-Mamma75** [comment]
This is already addressed and fixed in 1.3.3 which is now available.
As for the custom dungeon themes, those were done by Greymerk specifically for this pack.
