### ISSUE TITLE
Server issue : Doors and Veinminer

### ISSUE THREAD

**Issue by Masonic64** [scalda/FoolCraft#415]
Doors and vein miner

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x] I am requesting help with installing or running the pack

Hi all, First of what a great mudpack and thanks to Scalda and co for putting it together ! My issues are doors wont open/close and vein miner doesn't activate. Ive made sure its on in the mod settings and the above 2 issues actually working in my single player world, just not when I run the server :(
## Reproduce Steps Ive set up a server and I have those 2 issues and my pal also set one up and had the same 2 issues. very odd.(he remoted into my machine and set mine up by the way. So it could be something to do with the way he set it up  Any assistance will be hugely appreciated :)

It also mentions on the foolcraft splash screen that I do have 135 mods loaded. I also tried to disable then re-enable vein miner in game but the disable button seemed to be ..disabled :0_

**Comment by Jo-Mamma75** [comment]
So you run this on a server on your local system?  Are you using the latest version of the pack (1.3.3) and the server files located on CurseForge?  Is this happening in the spawn chunks only (more specifically in the spawn protection radius)?  A little more information would be helpful.
