### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by SM011** [scalda/FoolCraft#416]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## https://pastebin.com/vdZciUTC
http://imgur.com/a/kjZig

**Comment by legodude17** [comment]
Try reinstalling the pack.

**Comment by janf3** [comment]
I remember a similar issue on OS X two years ago or so where it wouldn't go past a certain point.

You can try disable the Loader/Splashscreen in `FoolCraft/config/splash.properties`
Open that file with a text editor like Notepad and set `enabled=false`

**Comment by Jo-Mamma75** [comment]
You only have 4GB of RAM allocated to the instance.  We recommend a minimum of 5.5GB if not 6GB to run properly.

**Comment by scalda** [comment]
also try 1.4.4 of the pack as we have found a mod that was seriously having memory leaks. closing for now
