### ISSUE TITLE
Typing in JEI

### ISSUE THREAD

**Issue by DarkPvPer1** [scalda/FoolCraft#417]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Ever Time i type in JEI I Crash
https://pastebin.com/BdebC1E0

**Comment by legodude17** [comment]
You should probably report this to JEI.

**Comment by DarkPvPer1** [comment]
Okay
