### ISSUE TITLE
save not loadable

### ISSUE THREAD

**Issue by BamiFaka** [scalda/FoolCraft#418]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
My world is not loadable from the minecraft launcher, but is still present in the saves folder

## Reproduce Steps
 1.Open my singleplayer option from the minecraft launcher.
2. Show my saves folder for the modpack

## Additional Information
![naamloos 2](https://cloud.githubusercontent.com/assets/28227876/25566411/57d1985e-2dd8-11e7-81e5-1861a8425409.png)
![naamloos](https://cloud.githubusercontent.com/assets/28227876/25566412/57d983de-2dd8-11e7-8972-1226c4ff10b3.png)

**Comment by LittleDevil76** [comment]
I have the same problem... Is there anyone who knows why the 'saves' are gone from the list..?

**Comment by Ravalli03** [comment]
Are you using twitch to play? If you use the vanilla launcher, it won't show your saves

**Comment by LittleDevil76** [comment]
It is just as Mr. BamiFaka explained at the top.

**Comment by BamiFaka** [comment]
Yes Mr. Ravalli03, I use twitch to play. When I lauch the modpack from twitch I get redirected to the ''vanilla laucher'' which shows my Forge profile. But it is no use for me, I've accepted my loss and started again. But for anyone who is encountering the same problem, please leave feedback and tips!

**Comment by Jo-Mamma75** [comment]
It's possible that your level.dat file became corrupted.  What all is inside the save folders?
