### ISSUE TITLE
world crashes upon load

### ISSUE THREAD

**Issue by Infectedstar** [scalda/FoolCraft#419]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
everything seems fine untill I try to join my world. for a split second I can see the my world like it loaded properly and everything 's fine, but straight after that my minecraft crashes and I go back to the launch minecraft window and I need to load everything again.

## Additional Information

https://pastebin.com/gm7zA5E3

**Comment by fabri2000779** [comment]
this issue start happening when you update your game of 1.2.2 to 1.3.2 right?

**Comment by Infectedstar** [comment]
yes

**Comment by fabri2000779** [comment]
try this possible solution for your problem https://github.com/scalda/FoolCraft/issues/324

**Comment by Infectedstar** [comment]
k so I will try capturing all the cows in my base with animal nets and removing molten dewstone. I'll let you know how it went.

**Comment by fabri2000779** [comment]
the solution is use mcedit and remove all the cows in the map

**Comment by Infectedstar** [comment]
caught all of the cows in animal nets, removed all of the ember mod's things from my base and storage. Joined the world and it didn't crash

**Comment by Infectedstar** [comment]
Thank you guys very much for this 1.3.2 update. Your work is very much appreciated. Love you very much for doing such a great job. Keep it up. #Iskalllove all of the devs are amazing <3
