### ISSUE TITLE
A ton of lag

### ISSUE THREAD

**Issue by Bloodyassault2001** [scalda/FoolCraft#42]
so i installed your pack and i have a decent computer with like 8 gb of ram, a nvidia geforce 960M and a I7 core, i even installed optifine and tried to set the settings on really low, that didnt work either. i really like this pack and want to play it. can someone help me?

**Comment by scalda** [comment]
how much ram have you assigned to MC?

**Comment by CriticalMole** [comment]
also chec your optifine version, D6 is the best one for FoolCraft right now from what I have seen

**Comment by Bloodyassault2001** [comment]
how can i set ram to mc?

**Comment by Bloodyassault2001** [comment]
oh i found it, im gonna try with more ram and optifine!

**Comment by Bloodyassault2001** [comment]
thnx for the suggestions it tuns a lot smoother now
