### ISSUE TITLE
Structures in Villages are randomly burning down | Trapdoors open by default

### ISSUE THREAD

**Issue by TheRealDadbeard** [scalda/FoolCraft#420]
- [x] I am running the latest version of FoolCraft
- [ ] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

Title. I don't know what i going on. Anyone had have that same issue? I've had it most of the time and it mainly affects the mills and they burn completely down.
I have to say I added some mods but i couldn't wrap my head around it how those could have a such severe effect....

Added Mods: 

- Quark 
- Iron Backpacks 
- BetterHUD 
- BetterFPS 
- Mr. Crayfish Furnitures 
- Chunkgen 
- Classic Combat 
- Item Physics 
- Iron Chest

Walk into any village.

**Comment by legodude17** [comment]
I would guess it is lightning strikes.

**Comment by TheRealDadbeard** [comment]
On most of the villages i encounter and when it is daylight with no rain nothing at all??

**Comment by Jo-Mamma75** [comment]
Unfortunately we can't really help you as you have added additional mods to the pack and we have no idea what effect they would have on it.  You guys are more than welcome to continue the discussion but I am closing this issue as unsupported.
