### ISSUE TITLE
World unplayable, low tps need fix

### ISSUE THREAD

**Issue by Spacecow12** [scalda/FoolCraft#421]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [X ] I am requesting help with installing or running the pack

## Issue Description
Lately i have made a post about TPS lag well it reached a point now where basically the world is unplayable. I have no idea what causes this i turned off all machines and farms yet still i have this problem. 

## Reproduce Steps
Log into my world and it starts

## Additional Information
6GB of RAM allocated

**Comment by fabri2000779** [comment]
try to use mcedit and clear all the entities

**Comment by theaardvarker** [comment]
If you have refined storage wireless transmitters, get rid of them.

**Comment by Spacecow12** [comment]
Entity count is like 60ish in my base and dont have ant wireless transmitters

**Comment by HisServant77** [comment]
I'm having the same issue, I believe. Whereas the world before was running smoothly, after updating the world freezes every second. Even new world's created, have the same issue.

**Comment by ashvathaman** [comment]
Any solutions? I'm have the same problem.

**Comment by fabri2000779** [comment]
can i ask guys, do you have spongeforge?

**Comment by Jo-Mamma75** [comment]
Do you have a Refined Storage system?  If so, have you tried to cycle through the redstone control options in the controller upon logging into the world?  Do you have loads of items in a Colossal Chest?  Other than uncontrolled farms and improper overflow protection, those are the things we see the most on our Patron servers that cause TPS issues.

**Comment by Spacecow12** [comment]
Yes i have a refined storge system, no i dont have colossal chest and i have enough storage capacity for all farms running (if they are running) using 64k storage disks and vast storage units

**Comment by HisServant77** [comment]
Wish that would solve the issue with me too, but remember that for me it also affects completely newly created worlds, without any tech or building or even menu opening happening

**Comment by scalda** [comment]
|Have any one ran this with tickprofiler to find out if there is a issue. Also more information would be nice like: computer specs and such

**Comment by scalda** [comment]
Has there been any progress on this issue?
