### ISSUE TITLE
OreGen in 1.3.2 broken?

### ISSUE THREAD

**Issue by ChromeMystic** [scalda/FoolCraft#422]
## SUGGESTION/HELP
- [X] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I upgraded the server to 1.3.2. Shortly after i used the chunkgen mod to pregenerate the map (about 4k blocks in each direction) to help with serverlag.
We noticed two things:
- There are multiple ores from Modern Warfare in the world, that cannot be properly processed (don't work in most machines and furnaces,...)
- Iskallium seems to be missing. Since it is so rare, i cannot be sure of this though.

## Reproduce Steps
I have generated multiple additional chunks and the problem persisted.

## Additional Information
I propose to check the configs for oregen, and add recipes to change the ores to their thermal foundation counterpart. Also it would be a good idea to add ore regen to the world in order to recreate the missing

**Comment by ChromeMystic** [comment]
Of course, 5 minutes after posting here, we found an iskallium, so it is only the modern warfare ores that spawn wrong

**Comment by Ravalli03** [comment]
Im guessing a config was changed, as I no longer see modern warfare ore neither, and all the ore/ingots I did have, are also gone. I looked at the change log, and see railcraft ore was removed, but nothing about Modern Warfare changes. I haven't tried to make anything to see if that type of ore is required. I know you can smelt steel to turn it into modern warfare steel.
