### ISSUE TITLE
Crash when opening lootbag in bag opener

### ISSUE THREAD

**Issue by ChromeMystic** [scalda/FoolCraft#423]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Loot bags cannot be opened by hand, don't seem to properly drop from mobs (at least not the pet bags) and when added to a bag opener the server crashes. The server cannot be restarted without instant crash.

## Reproduce Steps
Server instant crashes whenever adding a bag to the Opener

**Comment by ChromeMystic** [comment]
I disabled the lootbag mod on serverside, and the server came back

**Comment by legodude17** [comment]
Could you upload the full crash log to https://gist.github.com/ and post the link here?

**Comment by ChromeMystic** [comment]
https://gist.github.com/ChromeMystic/bb219a8e014a9c8a8f1a6ea4c50490bb there you go, the first was the crash when i added the lootbag, the second was crash when i tried to restart the server

**Comment by legodude17** [comment]
I would say you should file it with LootBags.

**Comment by Jo-Mamma75** [comment]
@ChromeMystic 
Disabling the mod on the server would have wiped out the Lootbag Opener.  From the coordinates of the block, it looks to be very close to where spawn would be.  I would imagine that it was either inside the spawn chunks or was being force loaded by a chunk/spot loader.
As for what caused the problem I couldn't tell you.  We've had loads of crashes here and there for "ticking block entities" but I've never seen a Lootbag Opener cause it.
For future reference, if your server crashes with a "Ticking Block Entity" crash, do the following:
- Shut down the server
- Edit the forge.cfg file in the config folder
- Change the following to entries
B:removeErroringEntities=true
B:removeErroringTileEntities=true
- Save the forge.cfg file
- Start the server
If everything comes back up, it should change the block/machine/item that caused the issue into something else (don't recall what it is).  Afterwards, shut the server back down and change those two settings back to "false".

I'm going to go ahead and close this issue as it seems you have already resolved it and I imagine that like other similar crashes, it is a transient issue and not something we can really "fix".
