### ISSUE TITLE
(Suggestion) Humbly suggest that LittleTiles mod be added

### ISSUE THREAD

**Issue by StagHunter** [scalda/FoolCraft#425]
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack
## Issue Description
I normally wouldn't make suggestions like this as it is your pack and therefore none of my business what you do with it, but I'm truly taken aback by the mod LittleTiles and I would therefore like to respectfully suggest that it be considered for the pack. I realize that there is quite a bit of redundancy with chisel and bits although there is added functionality over chisel and bits with regards to functioning doors, storage etc. 
## Additional Information
Obviously if there are reasons for not having the mod in the pack, or for favoring chisel and bits that I am not aware of I apologize for wasting time with this suggestion.
P.S. A great thank you from me for your continued work and maintenance on this pack as it is a wonderful and truly fun and enjoyable pack to play. Really one of the best Minecraft packs I've played to date. Well done!

**Comment by Jo-Mamma75** [comment]
I do recall looking at this mod once before.  I agree it has a lot of potential.  I will bring it up again for consideration.
I'm going to go ahead and close this issue but I have added it to our #for-consideration channel in the pack dev Discord.
Thanks for the suggestion.
