### ISSUE TITLE
Cannot Launch, Crashes at RFTools

### ISSUE THREAD

**Issue by johnkski** [scalda/FoolCraft#427]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

When launching, in mod initialization phase two, RFTools pauses and then the launcher crashes reading:
Java(TM) Platform SE binary has stopped working

Happens every launch with RFTools enabled

**Comment by ShaunM-M** [comment]
I have the same issue on my desktop however on my laptop it launches fine.
I managed to grab a screen capture on the exact moment that RFTool fails for me along with the crash acknowledgement.
![screenshot_2017-05-02-12-14-15](https://cloud.githubusercontent.com/assets/19577251/25615860/730a355e-2f31-11e7-9a0e-e546dcde8ae7.png)

![screenshot_2017-05-02-12-14-32](https://cloud.githubusercontent.com/assets/19577251/25615907/b2e699a6-2f31-11e7-9886-2c3c25161eec.png)

**Comment by TheRedDragon98** [comment]
I have the same issue on my desktop however on my laptop it launches fine.
I managed to grab a screen capture on the exact moment that RFTool fails for me along with the crash acknowledgement.
![screenshot_2017-05-02-12-14-15](https://cloud.githubusercontent.com/assets/19577251/25615860/730a355e-2f31-11e7-9a0e-e546dcde8ae7.png)

![screenshot_2017-05-02-12-14-32](https://cloud.githubusercontent.com/assets/19577251/25615907/b2e699a6-2f31-11e7-9886-2c3c25161eec.png)

**Comment by johnkski** [comment]
I actually solved this issue by updating my video drivers, feeling kinda dumb but I hope that helps

**Comment by TheRedDragon98** [comment]
Okay, I didn't think about that. I updated to the new windows 10 Creators version and my drivers done an update then, and that was before the crash. My laptop hasn't had the Creators update yet so I though it could have been that.
