### ISSUE TITLE
Crashing upon world load

### ISSUE THREAD

**Issue by macmansteele** [scalda/FoolCraft#428]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Allow world to load through launcher and crashes after world has blink into existence

https://pastebin.com/hZ0u2JF5

**Comment by legodude17** [comment]
Remove all of the Fluid Cows.

**Comment by macmansteele** [comment]
Thank you for the reply.  I've downloaded MCedit and watched some videos on how to use it.  I've been flying around and I don't see any fluid cows.  Because of the issue would they show up as pink question marks?  Is there a way to find them in mass fly to them and remove them?  I've found a ton of regular cows and removed some of them.  In theory I should be able to do this if I can find them.

**Comment by cauliflower69** [comment]
Delete the mod from your mod folder

**Comment by lilti** [comment]
I have this exact same issue. I have invested a lot of time building a fluid cow setup so it would be pretty disappointing to delete them all. Does anyone know if there is a fix coming soon?

**Comment by Jo-Mamma75** [comment]
@macmansteele Have you already given up on us?  Have a look at what I posted in #423 .  This may also help in your case.  Not sure.  We have run into that same issue again when updating due to Moo Fluids and some liquids that were removed from the game.  Report back and let me know either way.

**Comment by macmansteele** [comment]
Sorry for the slow response.  Removing the fluid cows mod did the job for me.    Thank you.
