### ISSUE TITLE
Constant Pig Sounds for ALL players

### ISSUE THREAD

**Issue by ftrocchi** [scalda/FoolCraft#430]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Starting yesterday (5/1) there are pig sounds that play randomly all the time.  No pigs are around.  The only way to turn it off is to turn off the "player" sounds volume, which isn't acceptable.  It is very annoying, and I'm not sure what is causing it.  

All players on the server are experiencing the issue.  

## Reproduce Steps
Easy to reproduce.. it is always doing it.  Not sure what caused it in the first place though, so I do not have those steps.

## Additional Information
No crashes happen, and I have checked all logs I can find.  Nothing looks out of the ordinary, or deals with 'pig'.  Also hard to take a screenshot of sound.

Thanks

**Comment by ashvathaman** [comment]
If you take a screenshot of one player, you can see a pig face

**Comment by ftrocchi** [comment]
We checked if anyone was wearing anything pig related.  Also anything pig related in inventories... like baconator.  Nothing.

I fixed my situation by completely blowing away everything and then reinstalling, so now I am able to play without being annoyed, and without waiting for someone to get back to me on the issue.

All that said, the issue would still exist and thus should not be closed.

**Comment by fabri2000779** [comment]
try to do a clean installation of the server modpack and save your world

**Comment by scalda** [comment]
This is the first time I have heard of this it might have been a bad sound file in the install when you did it. without more information and this being the only issue on this i am going to close it. if it comes back please open a new issue with as much info as possible

**Comment by Fasteroid** [comment]
As of just now, our All the mods 3 server is now experiencing this problem. After a quick look through the internet it seems this is the ONLY description of this problem in existence. I get that it's not the Foolcraft modpack, but our issue is EXACTLY the same and there does not seem to be an obvious fix. Help would be greatly appreciated (as I have absolutely no idea where to start in a modpack with 239 mods)

**Comment by Fasteroid** [comment]
Our ATM3 server is having the same issue. One player sees pig noses on everyone (including themselves) and EVERYONE ON THE SERVER hears pig sounds at random intervals. I am on the brink of insanity here PLEASE tell me there's a better way than just doing a fresh install.
