### ISSUE TITLE
Wither Doesn't Drop Nether Star 1.3.2

### ISSUE THREAD

**Issue by ashvathaman** [scalda/FoolCraft#431]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When I update the modpack from 1.2 to the latest version, the wither mob farm only drops 3 superium essence

## Additional Information

The Curse Launcher don't copy the Scripts folder

**Comment by legodude17** [comment]
Are you sure that the nether star didn't just get destroyed by something?

**Comment by Hathgar** [comment]
I am having this issue as well. There is nothing around that could of destroyed mine for sure.

**Comment by ashvathaman** [comment]
The problem seems to be the Curse Launcher. When I update again, the script folder copy has all the scripts, including the wither Drop table. That fix the issue
