### ISSUE TITLE
game crashed and will not start again

### ISSUE THREAD

**Issue by daenarys99** [scalda/FoolCraft#433]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## The game crashed whilst exception ticking world
Error: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[crash-2017-05-02_20.53.06-server.txt](https://github.com/scalda/FoolCraft/files/972308/crash-2017-05-02_20.53.06-server.txt)

## Reproduce Steps

##I am running 1.3.2
 I have also experience huge lag spikes where the game stops for up to a minute in between times when it runs fine. This time it did this twice in a row and finally crashed out and now it crashes while trying to enter the world.
Thanks for your time

**Comment by cauliflower69** [comment]
It's an issue with moo fluid cows.

https://github.com/TheRoBrit/Moo-Fluids/issues/46

**Comment by Jo-Mamma75** [comment]
We're waiting for an update from Moo Fluids.  Only thing to do is to temporarily disable Moo Fluids to get rid of all the entities or MCEdit and remove the ones in your area.  Don't know off the top of my head which cow it is that's causing your problem.

**Comment by daenarys99** [comment]
Thanks a bunch! disabling moo fluids worked.
