### ISSUE TITLE
#SUGGESTION Add Immersive Engineering

### ISSUE THREAD

**Issue by supertommyhd** [scalda/FoolCraft#434]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Can Immersive engineering be added to foolcraft? there aren't that many huge tech mods in the modpack, but Immersive engineering feels just right.  It has tons of multi blocks, cool conveyers,  innovative cables, and much more!
Please consider adding this mod.

**Comment by scalda** [comment]
Sorry this will not be added.
