### ISSUE TITLE
World crashes after opening

### ISSUE THREAD

**Issue by JerichoTitan** [scalda/FoolCraft#435]
- [ x
[crash-2017-05-04_00.38.55-server.txt](https://github.com/scalda/FoolCraft/files/975221/crash-2017-05-04_00.38.55-server.txt)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

**Comment by Bazingu** [comment]
Crashing because of fluidcows, remove the mod and try again?

same issue here.
https://github.com/scalda/FoolCraft/issues/433

**Comment by JerichoTitan** [comment]
ok got it
