### ISSUE TITLE
Unable to update to 1.3.3

### ISSUE THREAD

**Issue by ajdjyt** [scalda/FoolCraft#436]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When I click update to 1.3.3 on twitch i get an errror saying Missing Manifest in mod loader

**Comment by fabri2000779** [comment]
this looks like is a problem of your Twitch client try re-installing it and if that dont work try this: refresh your twitch laucnher with f5 too many times and try download the modpack, sound stupid but this issue was reported on r/feedthebeast and that was the solution

**Comment by ajdjyt** [comment]
Somehow nobody closed this thread and I am at 1.3.3 so I am closing this thread
