### ISSUE TITLE
Tinker's Station Client Side Crash

### ISSUE THREAD

**Issue by janagyjr** [scalda/FoolCraft#437]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
The tinker's crafting station causes a client side crash when you right click it with an object in hand (I've done it with carrots, others have had other vanilla items).

## Reproduce Steps
1) Get wood
2) Craft work bench, then turn into tinker's station
3) right click on tinker's station to open gui with a carrot in hand
4) ....
5) Crash

**Comment by legodude17** [comment]
Please provide a crash log
