### ISSUE TITLE
Illuminati pet block creation crashed client 1.3.2

### ISSUE THREAD

**Issue by superon** [scalda/FoolCraft#438]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
i used the illuminati pet to spawn an item that crashed my client upon instance, i'm not sure what the block is called but i remember it was something "glass"

## Reproduce Steps
login=crash

## Additional Information
https://pastebin.com/zj5YvnKa

**Comment by ajdjyt** [comment]
From What I see ( don't quote me on that though) i think it is something to do with ender io or an entity

**Comment by superon** [comment]
idk so could be wrong but i feel if it were an entity other people would also crash, which is not the case (this is on a server, i neglected to include that info in the opening post)...  either way i'd prefer to be offered a solution, so far i'm considering asking the server owner to nbt edit my inventory to rid of all glass related items or maybe try to find a "null" resource pack as i'm reading the issue as "Description: Rendering screen"

**Comment by superon** [comment]
i think i've found the issue... appeared to be the pet spawned a "thickened glass (bordered) helmet" which doesn't have a texture, i attempted to find if the graphics setting need changing for this (it only happens on the macOS, so i fixed it by running in windows and deleting the offending item), tried spawning one in with "give", failed... also tried to simply craft one and failed:/  illuminati pet says "cartable items" so looks like there's an issue with that mod, idk...

**Comment by ajdjyt** [comment]
the only fix i see is to tell the server owner to move the pet from your inventory to a chest or delete it completely from your inventory
and to get rid of the glass

**Comment by superon** [comment]
turns out the simpler solution so far is to kill the player with the item in question and login with windows to retrieve and rid it, also optional to create a suicide booth to automate this process;)   appears everyone on the server (everyone that's tested it at least) crashes with this render error.  moving this to the block armor page too as it seems now more relevant there right now:)

**Comment by Jo-Mamma75** [comment]
We have a fix/work-around for this coming out in a future update of the pack.  It was giving you something from Block Armor if I had to place money on it.
You can edit the player data file with NBTExplorer to remove the offending item.

**Comment by scalda** [comment]
Been fixed in later versions of the pack
