### ISSUE TITLE
Issue when updating from 1.2 to 1.3.2

### ISSUE THREAD

**Issue by dbhol** [scalda/FoolCraft#439]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

**Comment by legodude17** [comment]
There doesn't appear to be an error in the log.

**Comment by dbhol** [comment]
Ok well the server wont start when i try to start it up... :/

**Comment by dbhol** [comment]
Never mind. I have now resolved my issue. Found that all i needed to do was enter /fml confirm to the console and then it continued to start the server
