### ISSUE TITLE
Changelog says foamfix is updated to newest version but actually is not

### ISSUE THREAD

**Issue by TheRealDadbeard** [scalda/FoolCraft#440]
## SUGGESTION/HELP
- [ x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

Title. Just thought it was weird.

**Comment by Sharpy84** [comment]
this might explain why everyone on my server has insane ram use after the 1.3 update, after a few hours clients have 13-15gb ram use, i also tried a clean install of the pack but it still installs the old version so i am going to manually update my client to see what happens

**Comment by fabri2000779** [comment]
this is to ask for suggestion, help or just report bugs if you dont have any plz dont post here also if you have a problem make us know

**Comment by TheRealDadbeard** [comment]
Were else should I post any issue if this literally is the only place i can post anything about that modpack?!

**Comment by fabri2000779** [comment]
If you have a issue fill the rest of the form also provide the complete crash report

**Comment by scalda** [comment]
Foamfix was swapped out from the Anarchy version to the lawful version and at the time of release for 1.3 it was the latest. it will be updated again for 1.4 to the latest we are testing 1.4 atm

closing for now as it's not a real issue with the pack
