### ISSUE TITLE
Suggestion | Add Tinker I/O mod.

### ISSUE THREAD

**Issue by FeikoJoosten** [scalda/FoolCraft#442]
## SUGGESTION/HELP
- [x ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

I would like to suggest adding the mod Tinker I/O to make it easier to convert the fluids from the fluid cows to ingots/blocks.

## Additional Information

Using Tinker I/O will make it so much easier (and quite fast as well) to convert your fluids from the fluid cows to the desired ingot/block. I would suggest adding this mod to make it a lot easier for everyone to automate the fluid to ingot process. 

[Tinker I/O Mod](https://minecraft.curseforge.com/projects/tinker-i-o)

How to set things up
1. Use the Animal farmer from Progressive Automation to milk the cow.
2. Put the bucket you got from the Animal farmer inside an Ender io tank.
3. Push the fluid to the smart output block from Tinker I/O
4. Push the ingot/block to your system.

**Comment by Ravalli03** [comment]
+1

**Comment by TheonlyTazz** [comment]
you could also use a Tinkersconstruct Basin and pump the liquid in there, and then pump the block out into your system

**Comment by FeikoJoosten** [comment]
The smart output block will keep a fluid buffer, so keepig track of the excess fluids won't be a pain. It's also extremely fast compared to the tinkers setup. Just give it a try (;

**Comment by FeikoJoosten** [comment]
@scalda Any info on why it's closed? (Guessing due to the fact fluid cows is being taken out of the modpack, at least it was disabled for the hermits).
