### ISSUE TITLE
Hermitron Leaderboard messes up Inventory

### ISSUE THREAD

**Issue by TheonlyTazz** [scalda/FoolCraft#443]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When opening the Hermitron Leaderboard your Inventory bugs out, Relogging fixes it

## Reproduce Steps
Place down a Hermitron Leaderboard block, take off your armor, open the Leaderboard.
close it again, and press E. your inventory is all messed up

**Comment by TheonlyTazz** [comment]
Any info about this?

**Comment by scalda** [comment]
Try the latest version and report back please

**Comment by WinterGrave** [comment]
It will be fixed on pack version 1.4.6
