### ISSUE TITLE
Issues sleeping in 1.3.3

### ISSUE THREAD

**Issue by Morbinator** [scalda/FoolCraft#444]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

Since upgrading to 1.3.3, I have been having a problem where anytime I sleep, in a sleeping bag or bed, I can't get out of either of them and have to restart the game to continue.  Pressing leave bed does not work, it's like i try to get out, but am put straight back into the bed or bag.

Tried several times in bed and sleeping bag

**Comment by Morbinator** [comment]
This seems to have resolved itself, not been working for 3 or 4 days, but now working.

**Comment by Ravalli03** [comment]
This is a vanilla bug that comes and goes, next time you get stuck just use /ftb kickme, it will take you to the menu instead of having to reload the pack
