### ISSUE TITLE
Unable To Load The Pack BUG (botanicaladdons)

### ISSUE THREAD

**Issue by GenBlazkow** [scalda/FoolCraft#446]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Everything is updated. not even loaded into the main game and the crash comes from this error on minecraft latest launcher this is what it says

"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Natural Pledge (botanicaladdons)"

## Reproduce Steps

1. load up Twitch Launcher
2. Go to Minecraft
3. Launch FoolCraft Mob Pack
4. Loads up minecraft Launcher
5. Click play on the launcher for foolcraft
6. Loads up 
7. Crashes with Errors as seen in the log i have added to the post

## Additional Information

[latestlog.txt](https://github.com/scalda/FoolCraft/files/980969/latestlog.txt)

**Comment by GenBlazkow** [comment]
Oh i also had to disable Avaritia1.10+ and the addon mod for it as it also crashes

**Comment by GenBlazkow** [comment]
help anyone?

**Comment by GenBlazkow** [comment]
I would like some help some time soon please @scalda

**Comment by scalda** [comment]
you have answered your own problem in the original post

"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Natural Pledge (botanicaladdons)".

try a clean install of the pack and report back please

**Comment by GenBlazkow** [comment]
I only just done that and it still does the same thing even with the disabled mods that are broken

**Comment by scalda** [comment]
please see #330 for response
