### ISSUE TITLE
Cache doesn't break

### ISSUE THREAD

**Issue by sicnarf5845f** [scalda/FoolCraft#449]
Bug
Caches don't break

When placed, a cache will not break with a pickaxe or a crescent hammer like the CoFH wiki says.

1) Place a regular cache on the ground
2) Attempt to break with any type of pickaxe (mine was a tinker's pick with too many modifiers to reproduce exactly)
3) cache doesn't break

**Comment by TheonlyTazz** [comment]
you need to use a wrench to pop them from the ground. not foolcraft related.

**Comment by legodude17** [comment]
It is shift right click
