### ISSUE TITLE
MultiMc and Foolcraft: A match made in heaven???

### ISSUE THREAD

**Issue by Zevidrex** [scalda/FoolCraft#45]
So if anyone was around for my last thread I basically cannot use the twitch app to load this modpack. Sad!

But, there may be hope in MultiMc. As previously stated by scalda the godking, Downloading server files and then using multimc may help linux users load the modpack. I'm not sure how though. I tried sticking the entire thing in as and instance and the thing complains about there not being an instance.cfg. Odd. I noticed however that the server files had several jar files with individual mods inside it but multimc will only work with zip files. 

I had an epiphany when I realized that forge _could_ possibly read these jar files. So i stuck the whole list inside mods and ran forge. It complained about apples or something. Missing dependencies or something. 

No idea what im doing anymore whoops

**Comment by scalda** [comment]
https://github.com/scalda/FoolCraft/wiki/MultiMC-Guide

**Comment by Zevidrex** [comment]
Thank you! I will now direct this to fellow linux users :D
