### ISSUE TITLE
Minecraft comes alive mod problem

### ISSUE THREAD

**Issue by Explorer132** [scalda/FoolCraft#450]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

  I have just started playing foolcraft off of the technic launcher and it seems that Minecraft comes alive is not working properly. the main problem is that i can not give any of the villagers gifts or rings, I am able to interact in ways such as talking and having them follow me. The config file outside of the game in the mods menu is also unresponsive, in the game or main menu options, there is no mention of the mod anywhere. After extensive searching of youtube and other support sites, I have been unable to find this problem anywhere else. If anyone has had or is currently having this problem on the technic launcher version or any version, please comment, thanks.

**Comment by TheonlyTazz** [comment]
as far as i know, the modpack from the Technic launcher is a "false" copy and not supported by the modpacks creator. Please download it via the Curse/Twitch Launcher instead
