### ISSUE TITLE
Server stopping/failing during start.bat launch

### ISSUE THREAD

**Issue by Kyanite-Princess** [scalda/FoolCraft#451]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
When launching the batch file to run the server, it gets about ½-¾ the way through before the server stops due to an error.

## Reproduce Steps
Occurs every time batch is ran. does it in both 1.3.2 and 1.3.3 servers.

## Additional Information
https://pastebin.com/WezStA5v

**Comment by fabri2000779** [comment]
okay try to do this: download the modpack in curse/twitch app, start the modpack and confirm that the modpack start conrrectly, close and open the the foolcraft folder(it is locate in C:\user\documents\Curse\Minecraft\instance\Foolcraft} you will copy the mod folderand configs one and replace it on your server files
