### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by ramboshammakh** [scalda/FoolCraft#453]
Hello, im a non premium minecraft user (cracked) i cant use the curse launcher to update to latest fool craft version i have downloaded the first version 1.0 but i couldnt update it anymore if u could be kind to give me a link to download the server files
@scalda

**Comment by TheonlyTazz** [comment]
i doubt that the people here are supporting warez. i guess your out of luck

**Comment by ramboshammakh** [comment]
found it on curse @TheonlyTazz 
https://addons-origin.cursecdn.com/files/2415/364/FoolCraft%20-%20Server%20files%20-%201.3.3.zip

**Comment by TheonlyTazz** [comment]
still not cool to use warez

**Comment by scalda** [comment]
we will not support cracked clients. thanks for the issue
