### ISSUE TITLE
SMP Crash Interdimenstional Upgrade Refined Storage

### ISSUE THREAD

**Issue by ToXiiKD34th** [scalda/FoolCraft#454]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I am trying to get interdimensional upgrade to work with refined storage system in the nether. and when i hook it up it crashes and then i can't load in the world.
i hooked up the transmitter and receiver correctly and it still does not work.

## Additional Information
https://pastebin.com/de1aDymj

**Comment by Ravalli03** [comment]
Do you have both sides chunk loaded? I had an issue when doing the same, but didn't have the main system chuck loaded.

**Comment by scalda** [comment]
you need to make sure both the transmitter and receiver are chunks loaded
