### ISSUE TITLE
Withers Wont drop nether stars or custom lootbags

### ISSUE THREAD

**Issue by tyler489** [scalda/FoolCraft#456]
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
I saw this issue reported twice I cant Get withers to drop Netherstars on this multiplayer server i have all the scripts added by hand https://gyazo.com/179f6e16a32fc3432b1b44c666ad6738 and they still wont drop nether stars

## Reproduce Steps
Kill a wither.

## Additional Information
None

**Comment by tyler489** [comment]
Im going to say its a Spongeforge issue as it works correctly in singleplayer

**Comment by fabri2000779** [comment]
I can confirm you that is a Spongeforge bug when i used it i had this bug too when i remove sponge forge it fixed so your solution is remove spongeforge or kill the wither on the nether that works too

**Comment by scalda** [comment]
Basicly what the others have said above, Spongforge is very buggy which is very sad as we need something like it in the modded world.

Thanks for posting
