### ISSUE TITLE
No mechanical User

### ISSUE THREAD

**Issue by kernalcorn** [scalda/FoolCraft#457]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
A simple issue where the mechanical user just doesn't exist within my game, Something similar happened previously where the entire hatchery mod seemed to disappear but when I updated the pack it was back. Updating the pack doesn't seem to bring the mechanical user back though.

## Reproduce Steps
I do not know the source of the issue so i don't know how to recreate it.

**Comment by FeikoJoosten** [comment]
This is done intenionally since the Mechanical User was creating crashes. If you had read the changelist you would've known about this. Please close this.

**Comment by kernalcorn** [comment]
Thank you, and sorry for the trouble. It has been closed.
