### ISSUE TITLE
Some icons are colored blocks in JEI. In NEI they are fine.

### ISSUE THREAD

**Issue by TheRealDadbeard** [scalda/FoolCraft#458]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

Some icons are not showing up right in JEI. If i switch to NEI they are fine but it overlaps some GUI elements in machines.

## Reproduce Steps

![2017-05-09_19 39 33](https://cloud.githubusercontent.com/assets/23340600/25865371/f61b090c-34f2-11e7-992d-1661043cabe6.png)

**Comment by scalda** [comment]
Yes this is a problem with modern warfare, sadly
