### ISSUE TITLE
How much ram is ideal for server to run this pack ?

### ISSUE THREAD

**Issue by 8ong8ong** [scalda/FoolCraft#46]
I have a 8 GB server which i run FTB beyond no issues. My Friend loaded Foolcraft on her server which has 6 GB ram. we seem to be having a few issues running the pack. mainly people are timing out trying to connect to the server. we dont believe its a issue with the server unless its lacking ram, We think its maybe a pack issue. Any ideas would be appreciated.

Thanks

**Comment by scalda** [comment]
Well I have iskalls server running on 6GB ram and that runs fine

**Comment by 8ong8ong** [comment]
Thanks for the reply. appreciated :)

**Comment by scalda** [comment]
no problem
