### ISSUE TITLE
100% cpu and memory usage after running the server for a while

### ISSUE THREAD

**Issue by Yogen88** [scalda/FoolCraft#461]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

I'm hosting a foolcraft server on Centos 7 with latest java 64 bit with arguments:
java -d64 -server -Xms1024m -Xmx7g -jar forge-1.10.2-12.18.3.2281-universal.jar nogui
I'm running this script as other user with command:
sudo nice -n -10 su -c ./run.sh mcserver

The server has the following specs:
8gb ram, 32gb ssd space, 2 vcores 2,4 ghz

The server runs fine, until we leave it for a few hours idle. Then it starts to consume 100% cpu and all of the ram it can and becomes unresponsive to any input, sometimes not even pingable, needless to say, can't join.

Main problem here is that the logs are not showing me anything which would point to the source of the problem other than the "Can't keep up! Did the system time change, or is the server overloaded?" messages and some "Skipping Entity with id" messages without an actual id specified.

Leave the server idle for a few hours and it gets more and more overloaded on it's own. Seems like some kind of leak.

end of server logs:
https://pastebin.com/SKXZ8KWz

Some early remote profiling data:
hotspots:
http://prntscr.com/f6qn1s

Please if you know of ways that would help me pinpoint the issue, every lil bit is much appreciated!

**Comment by janf3** [comment]
It's rather normal for MC/FTB server performance to drop over time. That is why most servers have a scheduled restart once a day ~ some even more frequent.

One thing I would check is if the RAM and vCores are guaranteed and not some "max" value depending on other customers VPS activity. It would also be interesting to know the actual physical CPU powering the server.

**Comment by Yogen88** [comment]
Yeah, the RAM and vCores performance is not guaranteed on the current service I'm using sadly, that's why I'm considering a change to a cloud based resource allocation solution to improve the server's stability. Regarding your suggestion I've modified the server to run as a systemd service instead with an hourly scheduled restart. This seems to fix the problem for now, thanks. Furthermore if there are any tools that would help me profile/debug the issue that is causing the server to stall after a few hours that would be awesome. I'd be really happy to contribute to the development of the modpack. I've been trying to use tickprofiler mod and YourKit remote profiling tool to try to identify any leaks without any success so far. Sometimes the stalled state seems to disappear after a while (when the server is still pingable, but the connection times out) so i'm starting to think its more likely an issue related to the VPS as you've said.

**Comment by scalda** [comment]
This is sadly sounding like a hardware issue more than a pack issue, i would advise you to get dedicated hardware or at least a server that has dedicated resources for yourself and not shared
