### ISSUE TITLE
none of the mods will work for me

### ISSUE THREAD

**Issue by milenion** [scalda/FoolCraft#463]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

**Comment by FeikoJoosten** [comment]
Please provide more information regarding the issue.

**Comment by milenion** [comment]
when i download the mod pack it does not have any mods in the pack and won't work in the mods folder.

**Comment by Ravalli03** [comment]
I see you didn't check the box saying you use Curse/twitch, which is the only official/supported version.

**Comment by milenion** [comment]
how do i get it than?

**Comment by emkat** [comment]
You have to download it through the curse/twitch launcher. There is a fake version on technic.

**Comment by milenion** [comment]
can you give me the URL? plezz

**Comment by legodude17** [comment]
https://minecraft.curseforge.com/projects/foolcraft/

**Comment by legodude17** [comment]
It is on the front page

**Comment by milenion** [comment]
now it keeps crashing!

**Comment by legodude17** [comment]
Did you run it correctly?

**Comment by milenion** [comment]
ya

**Comment by legodude17** [comment]
Look through the open issues to find one like yours and comment on it.

**Comment by milenion** [comment]
now it is not crashing now it is just freezing.

**Comment by milenion** [comment]
what do i do

**Comment by scalda** [comment]
We need more information to be able to help you with this issue

**Comment by Jo-Mamma75** [comment]
@milenion Did you ever get this sorted?  If not, please let us know so we can try to help.  If it is resolved, please close this issue otherwise I will close it.
