### ISSUE TITLE
Getting a server crash when client tries to join on version 1.3.2 and (1.3.3 currently installed on Server and Client).  Server hosting says it is on faulty interaction between the Net Code and Moo Fluids.  Has this been seen before.

### ISSUE THREAD

**Issue by irobinson107** [scalda/FoolCraft#464]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

**Comment by irobinson107** [comment]
[crash-2017-05-12_00.13.00-server.txt](https://github.com/scalda/FoolCraft/files/994817/crash-2017-05-12_00.13.00-server.txt)

**Comment by scalda** [comment]
you have a bad fluid cow which i would assume is a dawn stone fluid cow the way to fix is 

1. purge all old region files which mean we would have to get a list of all bases and other things you want to keep
2. edit all region files to remove that specific cow if it exists. chances are they only exist in a handful of those files out of all region files
3. remove Moo Fluids from the server
