### ISSUE TITLE
Memory leak in 1.3.3

### ISSUE THREAD

**Issue by bcoov** [scalda/FoolCraft#467]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Since upgrading to 1.3.3, the modpack has been exhibiting a memory leak. After fully loading up and entering a world, Foolcraft uses ~6 Gb of memory, but steadily increases over time until it crashes the game due to an "out of memory" error (see below).

## Reproduce Steps
Start Foolcraft and play for about 30 min - 1 hour.

## Additional Information

ERROR DUMP:
----------------
(unneeded lines snipped. Normal game output...)
[22:32:03] [Client thread/INFO] [inventorytweaks]: Automatic stack replacement.
[22:32:15] [Client thread/INFO] [inventorytweaks]: Automatic stack replacement.
[22:32:24] [Client thread/INFO] [inventorytweaks]: Automatic stack replacement.
[22:32:44] [Client thread/INFO] [inventorytweaks]: Automatic stack replacement.
[22:35:09] [Client thread/INFO] [inventorytweaks]: Automatic stack replacement.
[22:39:05] [Client thread/ERROR]: ########## GL ERROR ##########
[22:39:05] [Client thread/ERROR]: @ Post render
[22:39:05] [Client thread/ERROR]: 1285: Out of memory
[22:39:06] [Client thread/ERROR]: ########## GL ERROR ##########
[22:39:06] [Client thread/ERROR]: @ Post render
[22:39:06] [Client thread/ERROR]: 1285: Out of memory
\#
\# A fatal error has been detected by the Java Runtime Environment:
\#
\#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000069880737, pid=16248, tid=0x0000000000003674
\#
\# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
\# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode windows-amd64 compressed oops)
\# Problematic frame:
\# C  [atio6axx.dll+0xf90737]
\#
\# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
\#
\# An error report file with more information is saved as:
\# F:\Users\...\Documents\Curse\Minecraft\Instances\FoolCraft\hs_err_pid16248.log
\#
\# If you would like to submit a bug report, please visit:
\#   http://bugreport.java.com/bugreport/crash.jsp
\# The crash happened outside the Java Virtual Machine in native code.
\# See problematic frame for where to report the bug.
\#
AL lib: (EE) alc_cleanup: 1 device not closed
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0

Link to additional error log (referenced at end of log above):
https://pastebin.com/jKGSXyjJ

My system has 16 Gb of RAM, which should be more than enough memory to run Foolcraft. I've also set the Curse/Twitch client to limit it to 6 Gb of RAM usage, which it seems to ignore. My wife runs Foolcraft on half the amount of RAM (8 Gb) with no leaking issues (same version of FC). I have tried doing a full reinstall of FC through the Twitch client (no effect), and tried switching the launcher to use the "jar" launcher, which seemed to make the leak less severe.

The only additional mod included alongside the pre-installed pack is BetterFPS, which was there since 1.2.

Java version is 1.8.0_131

**Comment by Ostert** [comment]
Im getting the same probem on a Single player world. Minecraft set to use 7GB. System has total 32GB memory. Log from after the point i had loged on: https://pastebin.com/0nhmQ0TB
No added mods installed. This time i loged on and just stod afk, the game crashed after about 5 hours.

**Comment by McSassyK** [comment]
I'm having the same problem since upgrading to 1.3.3. Keep increasing memory settings for Minecraft (currently at 6gb) but no matter what I increase it to, it just keeps going up and up until I get an "out of memory" error. No additional mods installed - just the standard Foolcraft pack.

**Comment by scalda** [comment]
This is a strange issue as it only seems to effect random people not everyone and i'm not sure what to suggest to be able to fix it. and chance you all can send me more information regarding your systems?

**Comment by McSassyK** [comment]
I'm running 1.3.3, no extra mods, on a StickyPiston server. I'm not super smart about tech stuff so not sure what other info would be helpful. Would be willing to whitelist you on our server if you wanted to check anything out.

**Comment by scalda** [comment]
#518 #515

**Comment by bcoov** [comment]
Some additional info if it helps: for troubleshooting, I tried creating a new profile for 1.3.2 (last version with no issue), complete with reinstallation of the modpack. Memory leaking still existed there, but wasn't as severe  (took longer), although hadn't existed in 1.3.2 before.

I can't provide system info right now, but I can add it in later today.

**Comment by scalda** [comment]
ok thanks

a lot of the mods have been updated in 1.4 so we are hoping that a lot of the memory issues will go away but until agricraft is fixed not a lot of testing can be done server side

**Comment by bcoov** [comment]
System info update:

CPU - AMD FX 8350 8-core
RAM - 16 Gb
GPU - Radeon HD 7850
Windows 10 Pro 64-bit (10.0, Build 15063)
HD1 (OS) - 128 Gb SSD
HD2 (Storage) - 300 Gb HDD
Java - Running with Java 8 (have also tried Java 7)

FoolCraft installed using the Curse Client (now Twitch App). Game is set to use max of 6 Gb of RAM in Twitch settings. I've launched FoolCraft using the new launcher as well as the original jar launcher.

That is all the system info I can think of that might help, but let me know if you need more. I also saw that 1.4 Beta is out, so I'll give that version a try as soon as I get the chance.

**Comment by scalda** [comment]
yeah try 1.4 client side as there is a bug with it running on a server at the moment and let me know how you get on

**Comment by jheiv** [comment]
For me, the leak issue remained with the 1.4.1 beta release.  The leak was especially evident when the player inventory was showing.  I ended up cloning the profile and slowly removing mods until the leak seemed to stop.  The last two I removed were More Player Models (which might make some sense, as the leak seemed more aggressive when the inventory was showing) and GooglyEyes.  To be fair, I removed quite a few other mods as well[1], (though none seemed to fix the problem like removing MPM/GE did) so take it with a grain of salt.  However, disabling one or both of More Player Models/GooglyEyes may be worth a shot.  If it helps, I'm sure the modpack devs would appreciate letting them know.

[1] The full list of mods I disabled was: Block Armor, Googly Eyes, LibrarianLib (and its dependent Natural Pledge), and Fake Blocks.

**Comment by Jo-Mamma75** [comment]
It did and I tested it on my end as well.
Thank you for doing the leg work on this.  We are recommending that mod to be removed from the pack.  However, I have posted an issue with the mod author and will give him/her a little time to respond.

**Comment by jheiv** [comment]
No problem, glad it helped.  Before I got your response I ended up profiling the memory usage of the java process with and without MPM enabled.  The results below are from two 20+ minute runs, one with and one without MPM (so YMMV).  Note that these numbers far exceed the limits I specified for the JVM, so it's likely a leak with JNI code (the mod seems closed source so I can't help any further).  Hopefully this addresses #518 and is likely the cause of #478 (and #402 ?)

http://imgur.com/a/iXFsF

Cheers.

**Comment by bcoov** [comment]
Finally got around to trying things out. I pulled out More Player Models based on the suggestions and FoolCraft's total RAM usage barely rose more than 2% after a few hours of playtime. Just wanted to add another confirmation to the pile, thanks @jheiv !
