### ISSUE TITLE
Inventory management

### ISSUE THREAD

**Issue by McSassyK** [scalda/FoolCraft#468]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
The golden bags of holding randomly vanish from my inventory. Sometimes they reappear, sometimes not. They also like to throw themselves randomly on the ground when I move them from one inventory slot to the other. Have gone back to using Hermitron cases for extra inventory space because they're so unreliable for our server and for me in singleplayer.

Would humbly like to suggest the addition of other inventory management options, such as the extended inventory in HermitPack and the sacks from that pack, which worked fantastic. Seems like we're tied to either Hermitrons or the golden sacks of holding in this pack. Thank you!

## Reproduce Steps
Uncertain how to reproduce except to play the game and use golden bags of holding?

## Additional Information
This issue doesn't crash the game. There are no crash reports.

**Comment by Ravalli03** [comment]
Moving the bag while it's open will caused it to disappear. To get it back, just open and close your invertory, and it will toss it in front of you as you pointed out.  Another bag that works is ender pouches, which can be color coded.

**Comment by Ravalli03** [comment]
I do agree with adding another choice, I have been using Iron backpacks that works great and the bags can be upgradable. Maybe that mod can be considered?

**Comment by McSassyK** [comment]
I don't think I was trying to move them while open but maybe I just didn't realize I was doing that. Thanks for the advice :)

**Comment by scalda** [comment]
since Tema hasn't shown much interest in fixing issues in ExU2, I would recommend stopping using Golden Bags and instead, use an RFTools Storage Tablet or an Ender Pouch. the Ender Pouch can and should be linked to a private Ender Chest, can be renamed and I believe Soulbound whereas that doesn't work on the Golden Bag as it should
