### ISSUE TITLE
Foolcraft 1.3.3 server crashe Need help !! 

### ISSUE THREAD

**Issue by moails** [scalda/FoolCraft#471]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x] I am requesting help with installing or running the pack

## Issue Description
I'm trying to set up a server so me and my friend can play together but when i start the start.bat it get to the 3/4 and crashes... The other issue i have is that the server doc seems to be missing some info like the IP part so i can put mine..Does it update when the server fully start? Anyway i'll put the crashe report down bellow. Help plz :) ! (i'm a noob at hosting :) )
[crash-2017-05-13_22.49.47-server.txt](https://github.com/scalda/FoolCraft/files/999067/crash-2017-05-13_22.49.47-server.txt)

## Additional Information
[crash-2017-05-13_22.49.47-server.txt](https://github.com/scalda/FoolCraft/files/999068/crash-2017-05-13_22.49.47-server.txt)

**Comment by legodude17** [comment]
Please paste the crash log in gist.github.com and paste the link here

**Comment by scalda** [comment]
this is a LibrarianLib Stage 2 crash you would have to remove that and naturalpledge which is sad as i don't understand why it crashes on some systems and not others

**Comment by mcdodge34** [comment]
Testing this with the brand new 1.4.3 version on 4 different PC (3 real PC and 1 virtualbox) I get this exact same crash, when I remove the NaturalPledge and LibrarianLib mod, it works straight again.
