### ISSUE TITLE
NEI crashes FoolCraft after typing certain letters like T and G

### ISSUE THREAD

**Issue by Silmenume** [scalda/FoolCraft#472]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When typing a search into the search bar of NEI the game freezes for a few seconds and then crashes to desktop.  It does not happen when I type the crashing letter but when I type any letter after it.  FREX typing T is fine.  But if I type any other letter, in this particular instance - O - as I was searchin Torch, the game freezes, the cursor turns into the Windows blue circle for a second or three and then the game crashes.  This happens every time.  There are other letters but I don't have my list with me, idiot that I am.

## Reproduce Steps
Go into the search bar of NEI and enter T and O.  This is guaranteed to create a crash on 4 different computers connected to my server.

## Additional Information
Below is a link to my crash report.
[https://pastebin.com/ty2mi80X](url)
The url isn't working correct so I will plain text the web address to my paste bin.  Sorry.
https://pastebin.com/ty2mi80X

**Comment by Silmenume** [comment]
Addenda - 

All of the following letters cause a crash when typing into the NEI search bar. S, T, G, L, C, O, H, W, I.

Also clicking on the arrow buttons at the top of NEI also cause the game to crash.

Since I could I reinstalled my client side with no improvements.

Help.  That game is rapidly becoming utterly unplayable.

Thanks!

**Comment by legodude17** [comment]
You crash report link is broken.

**Comment by melbellrocks** [comment]
We were having this issue on a server I play on so I decided to try some testing.  I installed a server with Foolcraft locally and am unable to reproduce the crashes.  I'm wondering if reinstalling the server files will fix this problem?  I am currently unable to test on the server I play on until I get in touch with the owner, but maybe Silmenume can try that?

**Comment by melbellrocks** [comment]
We were able to completely reinstall the modpack on our server and it did not fix our issue.  The temp fix we found was to blacklist the Agricraft mod from JEI so that no Agricraft items show up in JEI.

**Comment by Silmenume** [comment]
I have only had the most scant success with the problem.  We too have reinstalled the several a couple of times to little effect.  The best we've had it delete the instance locally, reinstall it, launch it, ruthlessly pare down the key bindings and then enter the server.  Then for maybe an hour, an hour and a half, we can play but once the game crashes once even just entering my inventory or right clisking on a block causes the game to crash out.  The only way of fixing the problem is to delete the instance and start over again.

Is the Agricraft blacklist at least a stable fix?  Please let me know.

**Comment by melbellrocks** [comment]
I have been playing for several hours now with no crashing.  Please note the blacklist change must be done client side as well, so everyone who plays will also have to edit their config.  Kinda sucks but better than not being able to play.

**Comment by scalda** [comment]
i don't understand why this is doing this i run 7 foolcraft servers with over 100 players and not seen ths once

**Comment by melbellrocks** [comment]
If it helps I was able to run the pack just fine on a Windows server, but our host uses Linux servers and that's where the crashes happened.  Not sure if you are running your servers on Linux or Windows but it might be a starting place.

**Comment by scalda** [comment]
Ours all run on Linux and not had this problem with anyone as far as we are
aware off

**Comment by Jo-Mamma75** [comment]
@Silmenume 
Are you still having this same issue?

**Comment by Silmenume** [comment]
Sadly the pack was so unstable that I had to stop playing it altogether.

Has there been a change that I should be aware of?  I'll be happy to give
it a try if so.
