### ISSUE TITLE
Constantly getting lagspikes every minute or longer if more RAM is allocated

### ISSUE THREAD

**Issue by Mario3264** [scalda/FoolCraft#474]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I get lagspikes every minute or so, allocating more RAM increases time between lagspikes, but it is not very playable with constant lagspikes. If I don't allocate more RAM, the game will sometimes crash while loading.

## Reproduce Steps
Start a singleplayer world

## Additional Information
PC Specs:
Intel i3-4160 (3591.43 MHz)
8 GB of DDR3 RAM (798.1 MHz)
Intel HD Graphics 4400 (598 MHz)

Version: FoolCraft 1.3.3

**Comment by legodude17** [comment]
How much RAM did you allocate? Recommended is 4-5 GB

**Comment by Mario3264** [comment]
I tried allocating 4 GB of RAM, but lagspikes still happen in a singleplayer world. Sometimes the game crashes while loading if less RAM is allocated.

**Comment by ajdjyt** [comment]
you have to allocate 6GB mario3264 there is no other way i think,  im playing on the same config as you only my cpu is I3 2048 Mhz
And my 8GB rams is 1600mhz
And i have intel hd graphics 5500

**Comment by scalda** [comment]
Hi this is due to your graphics, you really need a dedicated GPU to be able to play modded Minecraft to the fullest so this is relying on your ram and CPU a lot to be able to render everything correctly.

you also need to have at least 5.5gb ram allocated to foolcraft

**Comment by Mario3264** [comment]
Thanks for the help, I don't think there is another way but allocating more ram
