### ISSUE TITLE
Server Crash 1.3.3

### ISSUE THREAD

**Issue by carrode** [scalda/FoolCraft#476]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description can't run the server files of the pack. have downloaded a number of times
i have replaced the mod and config folders from a single player download which works but no luck.
any ideas on how to fix otherwise i and my friends are stuck on v1.2.2.
Thanks.

## Reproduce Steps -just download and run server file

.https://pastebin.com/Q56AmYYT

**Comment by legodude17** [comment]
Try removing LibrarianLib and Natural Pledge

**Comment by carrode** [comment]
Removed those two files and yes got the server running and copied over my 1.2.2 world and got to play for about 1 hour before i got multiple CTD while either typing a search in NEI or the last one was right clicking on the Refined Storage grid. hoping i can get back in later on tonight when i finish work if not it'll be back to 1.2.2. will provide crash reports if i have any, oh by the way it was just a client crash, server seems to be unaffected.
Thanks again for the help.
