### ISSUE TITLE
FoolCraft Constantly crashing mid-game

### ISSUE THREAD

**Issue by tzimm16** [scalda/FoolCraft#478]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

I am running the lasted FoolCraft and play single player only. Since the last update I am having contstant crashes. I don't know where to do a crash report so do not have that. There is no certain mod being used when it crashes, it simply shuts down and pops up with Your Game has Crashed, Sorry.  It can happen when there are a lot of mobs, it can happen when I am by myself, it can happen while I am digging, building, going through my inventory, walking. There is no one reason I have tracked that causes this. I read that some one had the golden bags of holding disappear from their inventory. I had all my inventory including the golden bags I had disappear and not come back. I was not moving them while open and they did not fall to the ground. This was the entire inventory. I was in the nether at the time.

I am just a novice game player and know nothing of code or what to look for.

**Comment by tzimm16** [comment]
Ok, just played and it happened again. I was moving items to my chest from my inventory. I took a screenshot and the log.
![2017-05-15](https://cloud.githubusercontent.com/assets/28720103/26087019/3b8c14f4-39a3-11e7-9063-cc8e78f7872e.png)
![2017-05-15 1](https://cloud.githubusercontent.com/assets/28720103/26087022/3f8f53e0-39a3-11e7-89bf-717ad94ec5ad.png)

**Comment by FeikoJoosten** [comment]
For starters, please provide the full log.txt using pastebin.
Also, I'm guessing your computer isn't 'powerfull' enough looking at the logs so far, but we'd require more information first.

**Comment by tzimm16** [comment]
I apologize, I have no clue about most of this stuff. I just purchased a new computer that I was told would run the mods I wanted . I am not sure how to find the full log.txt using pastebin. Can I get some help with this information. Thank you.


________________________________

**Comment by FeikoJoosten** [comment]
The log is located in the folder "logs" which is locted in the install directory of Foolcraft. 

Just use file with the latest timestamp. 

The open that .txt file copy all the contents of that file and paste it in a pastie on pastebin. This is to prevent huge amount of text on this page.

**Comment by tzimm16** [comment]
Thank you. I have had the flu so have not had a chance to reply.


________________________________

**Comment by tzimm16** [comment]
https://pastebin.com/96iLM5fp

Here is my latest log. I did recently purchase a new computer with a good graphics card for game play. it is an Aspire E 15.

I am not tech savvy with this stuff so I just ask for your patience. Thank you!

**Comment by ajdjyt** [comment]
start twitch open settings click on minecraft and then scroll down to "MAXIMUM MEMORY ALLOCATION"
Then bring the slider upto 6GB of ram unless you have less then that ,then you will not be able to play most mods :p

**Comment by tzimm16** [comment]
I have 8 so I made that change. Thank you.


________________________________

**Comment by scalda** [comment]
@tzimm16 did you get this sorted?

**Comment by tzimm16** [comment]
yes, thank you!


________________________________
