### ISSUE TITLE
Server won't start!

### ISSUE THREAD

**Issue by MagicTears123** [scalda/FoolCraft#48]
Hello,
i'm trying to set a server on a dedicated server (hosted at a company) and it just crashes, doesn't load anything. It works fine on my desktop when I run it, but I won't be able to run client and server.
And i'm getting this in my console : 

21.03 20:51:26 [Server] INFO at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
21.03 20:51:26 [Server] INFO at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
21.03 20:51:26 [Server] INFO ... 6 more
21.03 20:51:26 [Server] INFO Caused by: java.lang.ClassNotFoundException: jline.console.ConsoleReader
21.03 20:51:26 [Server] INFO at java.net.URLClassLoader.findClass(Unknown Source)
21.03 20:51:26 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source)
21.03 20:51:26 [Server] INFO at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
21.03 20:51:26 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source)
21.03 20:51:26 [Server] INFO ... 20 more
21.03 20:51:26 [Multicraft] Server shut down (starting)
21.03 20:51:26 [Multicraft] Restarting crashed server in 60 seconds
21.03 20:51:26 [Multicraft] Looks like a crash, check the server console. Return value: 1
21.03 20:51:26 [Multicraft] Server stopped

**Comment by scalda** [comment]
can you supply me with the crash report please?

**Comment by MagicTears123** [comment]
Heyy,


I managed to actually start it up, it was a java problem with the hosting company..
Don't worry!
Also I've send a bug report/dupe glitch with the Hermitron boxes, can you maybe remind Iskall to check it out?


-xJohnnyD7

________________________________
Van: Scalda <notifications@github.com>
Verzonden: dinsdag 21 maart 2017 21:01:06
Aan: scalda/FoolCraft
CC: MagicTears123; Author
Onderwerp: Re: [scalda/FoolCraft] Server won't start! (#48)


can you supply me with the crash report please?
