### ISSUE TITLE
Failed to download http://dropbox.com/s/j9wak5vzssrt71c/iskall85s-foolcraft-1.3.3.zip?dl=1

### ISSUE THREAD

**Issue by TurtleBurger681** [scalda/FoolCraft#481]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Reproduce Steps
I'm downloading Foolcraft through the technic launcher and the error message keep preventing me

**Comment by CriticalMole** [comment]
The techic version is an unauthorised clone and is not supported by the development team, if you would like to play pleaseuse the Curse/Twitch launcher

**Comment by TurtleBurger681** [comment]
I downloaded Curse but idk how to play minecraft on it

**Comment by TurtleBurger681** [comment]
nvm I'm dumb
