### ISSUE TITLE
Using an unbreakable wand to build a colossal diamond chest corrupts the world

### ISSUE THREAD

**Issue by Jupisoft111** [scalda/FoolCraft#483]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When I was building a 16x16 diamond colossal chest, using my unbreakable wand (of the first unbreakable tier), it placed a row of ghost blocks (I could see the outline of the blocks, but nothing inside), maybe caused because when I right-click with my bare hand on the colossal blocks it searches for the core, which wasn't yet placed anywhere, so doing it with the wand, placed the blocks and interacted at the same time with the colossal chest structure, causing some overlap or so. After fully restarting my game, it never loaded the world again, even after waiting 30 minutes. So I had to restore a previous backup.

## Reproduce Steps
Try to build a 16x16 diamond colossal chest wall with an unbreakable wand (with first row placed by hand), and without any core or interface placed.

**Comment by CakeArmy** [comment]
I believe this was another reason why they were disabled. I reccomend, as I do, only using wands for either: Vanilla Blocks or Decoration Materials. No Machines, Multiblock Structures etc.
