### ISSUE TITLE
Flickering trees and some types of blocks in the distance

### ISSUE THREAD

**Issue by Jupisoft111** [scalda/FoolCraft#484]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I've played the same map for some weeks without problems, but yesterday the blocks in my underground base began to flicker a lot, mainly the type of factory block with the blue mainframe or so. But when I got to the surface the trees were doing that a lot more. After looking at my graphics settings, I turned my mipmap level to the minimum and the bug went away, but any other smoothing level in the far textures starts to flicker now. I had that same bug in Sky Factory 3 for some times, but usually after restarting Minecraft it went away. Unfortunately this doesn't happen on Foolcraft and I have to choose between flickering things or blurry things with the minimum mipmap level. Other graphical options doesn't seem to affect this flickering so it might have to do with the mipmaps. If it helps I have Intel HD graphics integrated in my main mother board, and I can't play with VBO or it crashes my Minecraft (with or without mods).

## Reproduce Steps
I can't exactly reproduce it, but changing the mipmap levels I can get rid of it or have it again. And it started on it's own, without changing any graphics options before.

## Additional Information
I give 6 GB to Mineraft.

**Comment by Ravalli03** [comment]
Alot of us been having this issue and it's been reported multiple times. The only solution we have been getting to fixing it,  is turning off the mipmaping as you explained, and that it's not a Foolcraft issue. It would be nice to know if there is an actual fix.
