### ISSUE TITLE
I give 6 GB to Minecraft, it always ends up using al my RAM and pagination file space and starts to hung up

### ISSUE THREAD

**Issue by Jupisoft111** [scalda/FoolCraft#485]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I always give 6 GB to Minecraft (also tried with 5, 10, etc GB), it always ends up using al my RAM and in about half an hour of play (but often in less time), and also all the pagination file space and then my hard drive starts to make a lot of sounds and all the Windows 8.1 system starts to hung up and freeze. I usually  try to exit and restart to not loose my progress, but sometimes it's too late.

## Reproduce Steps
Start my game and play for 30 minutes or so.

**Comment by CakeArmy** [comment]
Is this with all modpacks? Does your HDD have enough space? Are you SURE its a ram issue?

**Comment by CakeArmy** [comment]
In the meantime I do reccomend armoma backups, it allows you to automatically save your world after X amount of time, by default 30 minutes but in your case I would change to 20

**Comment by scalda** [comment]
this sounds like a hardware issue, not a pack issue so i will be closing
