### ISSUE TITLE
Crashing when placing blocks from ArchitectureCraft

### ISSUE THREAD

**Issue by SpencerSx** [scalda/FoolCraft#486]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
If you have a square that has a chisel and bits block on it (So that the block isn't exactly fullsize) and place a roof tile on that gap of block, the mod seems to think it can place there when it actually can't so instead of preventing you from doing it, it just crashes your whole game.

## Reproduce Steps
Place a wood block, chisel majority of it away, attempt to place a rooftile within that block,

## Additional Information
https://pastebin.com/fbYFuw0h
Unsure if the crash logs even show it.

**Comment by legodude17** [comment]
Please report this ArchitectureCraft.

**Comment by Ravalli03** [comment]
You may have better luck posting to ArchitectureCraft github. I also don't think it has to do with chisel and bits mod either. Placing any architecture blocks anywhere that can't be placed will sometimes lead to crashes regardless on the other mods involved.

**Comment by Ravalli03** [comment]
@legodude17 I must of being type mine when you posted, sorry

**Comment by scalda** [comment]
you can't place chisel and bits stuff next to ArchitectureCraft items this is a known issue with the mods, not the pack itself so please report to the mod authors
