### ISSUE TITLE
Foolcraft 1.3.3 server crash at first start up

### ISSUE THREAD

**Issue by Gooftu** [scalda/FoolCraft#487]
- [x ] I am running the latest version of FoolCraft
- [x ] I am running FoolCraft via Curse/Twitch Launcher
- [x ] I can reproduce this issue consistently
     - [ ] In single player
     - [ x] In multiplayer
- [ x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x] I am requesting help with installing or running the pack

## Issue Description
First start up and i crash 

## Reproduce Steps

https://gist.github.com/anonymous/5c83a901dca916f5b1652e5b5c8591da

**Comment by CakeArmy** [comment]
THANK YOU FOR USING SOMETHING OTHER THAN PART OF THE DOCUMENT FOR A LOG. I WILL NOW PROCEED WITH ATTEMPTING TO HELP YOU. Jeez...

**Comment by CakeArmy** [comment]
Okay so you have not successfully started the server? Basically, it says that something took to long to do. The error seems to be from libarian liblate whilst it was trying to start. Try removing this mod?

**Comment by scalda** [comment]
this is a LibrarianLib Stage 2 crash you would have to remove that and naturalpledge which is sad as i don't understand why it crashes on some systems and not others

**Comment by Jo-Mamma75** [comment]
Closing this issue.  We have another that we're leaving open regarding Natural Pledge and LibrarianLib.
