### ISSUE TITLE
Nether ploblem when entering it.

### ISSUE THREAD

**Issue by calabazY** [scalda/FoolCraft#488]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When I enter the netehr I get stuck and cant move or see what is in front of me. I can move the hotbar but when i leave and enter again is so laggy, like rubberbanding. But there is no fps issues or memory issues. 
Please could anyone help me?

## Reproduce Steps
Enter the Nether
Leave and enter the game
![2017-05-20_18 02 45](https://cloud.githubusercontent.com/assets/27145416/26277440/a600bf00-3d87-11e7-818c-b0ca84cf0ac2.png)

**Comment by CakeArmy** [comment]
Is this all of a sudden or happened since you first went in?
are there any modded blocks in the nether
can I please have your seed.

**Comment by calabazY** [comment]
It happened all of a sudden when I uploaded to 1.3.3 I think. I have a skeleton frarm with 3 fans 1 mob grinder a restubed spawner some restone conduits a diamond chest and a vaccum from mb_grinding
the seed is:-3582729054226642244
the coodinates from the portal in the overworld are:-1011 46 -3938

**Comment by scalda** [comment]
Have you tried tick profiler to be able to see if it is an entity build up?

**Comment by calabazY** [comment]
I dont really know how to do that

**Comment by Jo-Mamma75** [comment]
@calabazY Did you ever get this issue resolved?  We have a Wiki page on the usage of the TickProfiler that Scalda suggested.

**Comment by calabazY** [comment]
This is what I got
![2017-06-23_10 59 52](https://user-images.githubusercontent.com/27145416/27475138-5fe33f24-5804-11e7-8176-497dbe20ce9d.png)
![2017-06-23_11 00 39](https://user-images.githubusercontent.com/27145416/27475214-a18eb1a6-5804-11e7-814c-671908f746dd.png)
