### ISSUE TITLE
Crash while exploring, can not reload

### ISSUE THREAD

**Issue by ChanLord777** [scalda/FoolCraft#492]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I was exploring by flying around using draconic evolution. I was over an ocean biome going a little fast for my rendering capability and the game crashed without warning. I have tried to reload 3 times and as soon as the game loads, it crashes again.

## Reproduce Steps
I am not sure what I have done to cause this but I have reproduced the issue 3 times. 

## Additional Information
[crash-2017-05-20_23.00.09-server.txt](https://github.com/scalda/FoolCraft/files/1016624/crash-2017-05-20_23.00.09-server.txt)

**Comment by CakeArmy** [comment]
pastebin.com

**Comment by scalda** [comment]
This is a moo fluids crash please search the closed issues for an answer
