### ISSUE TITLE
Crashing World - Will not load world anymore

### ISSUE THREAD

**Issue by GitHubEnt11** [scalda/FoolCraft#495]
Crashing during Startup

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
During play, game crashed.  Now world will not load past 'building terrain' screen.  Full crash.  Started a new test world that works

## Additional Information

Pastebin:

https://pastebin.com/L6QnNzZH

**Comment by janf3** [comment]
`Caused by: java.lang.NullPointerException
    at com.robrit.moofluids.common.entity.EntityFluidCow.writeSpawnData(EntityFluidCow.java:350)`

The fluid cow crash has been reported about 2 or 3 dozen times here now.
backup your world
deactivate Moo Fluids
start Foolcraft and load your world

**Comment by Jo-Mamma75** [comment]
You can also either delete the file "\saves\<world name>\region\r.-1.0.mca" or edit that file in NBTExplorer and find the entry for a Molten Dawnstone cow and remove it, save the file and launch the world again.

**Comment by Jo-Mamma75** [comment]
No response for almost a week. Closing.
