### ISSUE TITLE
Add Reworked Portal Gun to Foolcraft.

### ISSUE THREAD

**Issue by anotyp** [scalda/FoolCraft#496]
I would like to suggest to add a new mod to foolcraft. It is called Portal Gun. It has great
Aesthetics for ex. You can see through portals. To find it you can go here: iChun.me . This is a website of the second greatest modded of all minecraft (Scalda obviously has the first place).
I hope that you will ad this mod.

**Comment by CakeArmy** [comment]
1: add not "ad" as in advertisement. 2: If you want it for the teleportation side, draconic evolution, ender io, and I think progressive automation have you covered. 3: I haven't seen this version with the ability to see through the portals but wont this cause an issue for friends running on slow pc's to have that extra stuff rendered? Also, it will strain popular servers by having extra things chunk loaded, unless it somehow else gets the data from the chunk?

**Comment by anotyp** [comment]
1. The "view through portals" thing is client side only and can be to configure to be on or off. The same goes with fancy borders of portals.
2. I have done some testing and i believe that portals don't chunkload as long as your are 10-5 blocks away from them - then they activate. When you are not close to them they don't cause lag. Some appears only when they are created.
3. The showcase of the mod is here. [https://www.youtube.com/watch?v=wphLuctGvus](url). In the video you can see both that it doesn't lag much and that you can see through portals. MADE BY: Direwolf20.
4. I think that this mod should be added not because Foolcraft lacks ways of tranport but because it is an unconventional and fun way to travel.

**Comment by anotyp** [comment]
In this video you can see that it works for normal people with standard computers too. It isn't only for Pros with super machines with nvdias. [https://www.youtube.com/watch?v=J4a_0TtiVpY](url)

**Comment by anotyp** [comment]
Sorry for another comment, but I like to be precise. If the links don't work for you, paste them in your browser.

1. Direwolf20's showcase:   https://www.youtube.com/watch?v=wphLuctGvus
2. Normal player' s (ArtisticInsomniac) video:    https://www.youtube.com/watch?v=J4a_0TtiVpY

**Comment by FeikoJoosten** [comment]
From my understanding, and my own testing. The portal guns mods is NOT compatible with the modpack.

**Comment by FeikoJoosten** [comment]
To follow up on this. This is under "Known Issues":
"Incompatibility with foamfix, codechickenlib."

**Comment by anotyp** [comment]
I think that it is only your personal problem because I didn't see or hear about anyone else who had this problem too.

**Comment by FeikoJoosten** [comment]
It is actually noted on the website from the portalguns mod. This is why I added the quotation marks.

**Comment by Jo-Mamma75** [comment]
This has been added to 1.4 and was a duplicate issue as it had been requested previously.
I also do not appreciate you removing the template from the posting of the issue originally @anotyp .
