### ISSUE TITLE
FoolCraft 1.3.3 client crashes on startup

### ISSUE THREAD

**Issue by montuos** [scalda/FoolCraft#497]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When attempting to launch FoolCraft v1.3.3 using MultiMC, the game crashes during the transition from preinitialization to initialization. The crash log says it's catching an exception from B.A.S.E, and the NullPointerException is coming from minetweaker.runtime.providers.ScriptProviderDirectory.

## Reproduce Steps
1. Install FoolCraft on MultiMC using Scalda's guide here on GitHub.
2. Install Forge version 1.10.2-12.18.3.2281, as that is the version included in the server files.
3. Launch game.
4. Crash happens duing loading.

## Additional Information
Latest crash log attached.
[crash-2017-05-24_22.43.14-client.txt](https://github.com/scalda/FoolCraft/files/1027835/crash-2017-05-24_22.43.14-client.txt)

**Comment by CakeArmy** [comment]
Thank you for including a log @montuos ... Are you sure scalda has supported MultiMC? As far as I know the only supported version is on twitch/curse/ftb launcher. Either way, pastebin is the preferred way to share logs but ill download notepad++ and check it out for you. Give me a minute.

**Comment by CakeArmy** [comment]
Can I get information on your minetweaker file? What version?

**Comment by montuos** [comment]
I assume MultiMC is using the MineTweakerRecipeMaker-1.10.2-1.2.1.26.jar that's included in FoolCraft - Server files - 1.3.3.zip.  Thanks for looking at it!  I appreciate your help a lot, since my desktop runs Linux, so Twitch/Curse is not an option for me.

**Comment by scalda** [comment]
this is a MT crash i see this alot just restart the game and it should be fine

**Comment by montuos** [comment]
How many times should I expect to restart before it's fine?  I've just restarted four times in a row with the same error.  I have not yet had a single successful start.

**Comment by scalda** [comment]
reinstall the pack as it looks like a bad conflict between base and MT

**Comment by montuos** [comment]
We had already tried reinstalling the pack at least half a dozen times before my son filed this bug report for me.  We even tried installing a different version of MultiMC (from the tar file as opposed to the Ubuntu repository) in case that was the problem.  I even tried re-downloading the FoolCraft file.  None of that has helped.

**Comment by montuos** [comment]
I do not pretend to understand this.  I installed FoolCraft 1.3.3 on my laptop since I couldn't get it working on my desktop to save my life.  Then I rsync'd the instance on my laptop over to my desktop, and now it works there too.
