### ISSUE TITLE
Foolcraft 1.3.3 is lagging and all previous versions were lagging too.

### ISSUE THREAD

**Issue by spajky32** [scalda/FoolCraft#498]
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

Describe the issue:
I am running FoolCraft with 6 GB of RAM, And I have at most only 3 FPS.
Computer specs:
Graphics card: RADEON (TM) RX 480 Graphics
CPU: 4X AMD A6-3670 APU with Radeon(tm) HD graphics
RAM: 8 GB DDR3

How to reproduce:
Have the same computer as me (maybe)

**Comment by CakeArmy** [comment]
Lol, lovely description. I don't know anything about AMD, I couldn't even start to guess, but I do know ram. You computer has 8 gigs and you gave minecraft 6? 1: are you sure about the amount of ram assigned 2: You shouldn't need that much, 4 should be plentiful, especially if you are just leaving 2 for OS, music, etc. etc. (stuff adds up, I use about 16gb of ram with games running). How long has this been an issue? Is this just on one world or all worlds?

**Comment by spajky32** [comment]
It is for all worlds, and I gave it 4 gigabytes, but it is still lagging.

**Comment by spajky32** [comment]
*CPU is 6 years old

**Comment by spajky32** [comment]
Nevermind, I launched it on linux and it runs smoothly.

**Comment by CakeArmy** [comment]
Mmmmk

**Comment by spajky32** [comment]
what?

**Comment by scalda** [comment]
please make sure that minecraft is set to use the rx 480 and not the cpu

**Comment by spajky32** [comment]
And how do i do that?
