### ISSUE TITLE
How can I install this mod pack without Curse Forge Launcher?

### ISSUE THREAD

**Issue by JRSofty** [scalda/FoolCraft#5]
The problem is that I am a Linux user, and while this mod pack looks cool, and I would love to play it, there doesn't seem to be a way to install this through the old FTB client which is the last one they released that supports Linux.

So is there a way to run this without the new client? Sorry to post this here, couldn't figure out where I could ask to this.

**Comment by scalda** [comment]
If you have access to another os you could download the files via curse on that and then use a program called multimc to copy the files over to make a instance

**Comment by LunaSquee** [comment]
You could try the script I wrote for myself for this purpose: https://github.com/LunaSquee/mc_curse_modpack_downloader

It's not something that's supposed to be used reliably but it fulfilled the purpose for me. 
You'll need to have Node.js installed thought (https://nodejs.org/en/), and you need to install Forge manually.
Just run "node install_pack.js https://minecraft.curseforge.com/projects/foolcraft" and do what it tells you

**Comment by valezola** [comment]
I also wrote a very simple downloader in python:
https://github.com/valezola/mc-mod-downloader

However downloading the mods and putting them all in the "mods" folder was not enough for me.

Can you please provide some info such as:
- do some mods need to go in the "coremods" folder?
- what is the recommended Forge version?

Thank you. I really look forward to playing this.

PS: I'm also a Linux user and I've had this problem with other mods as well. I really wish there was an easy way :(

**Comment by LunaSquee** [comment]
@valezola There is no such things as "coremod" folder anymore, its a thing of the past. Well, if you really need to support ancient versions of minecraft then you might want it. Also, your script will not apply patches provided with the modpacks and I don't recommend using it.

The lowest recommended forge version is provided in each manifest file

**Comment by JRSofty** [comment]
@LunaSquee Your script works a charm, sadly my computer is still too slow for that many mods :( as the game freezes during load. Oh well, I'll have to find some other "light weight" mod pack to try. I'll probably keep using your script though that was pretty good.

**Comment by LunaSquee** [comment]
@JRSofty Alright, glad I could help :)

**Comment by scalda** [comment]
well you could always pull down the server files so you have the complete pack and then use multimc
