### ISSUE TITLE
INFINITY AMROR IS BROKEN 

### ISSUE THREAD

**Issue by Cripyc** [scalda/FoolCraft#500]
Foolcraft
INFINITY ARMOR IS BROKEN
ok
ok

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

**Comment by Cripyc** [comment]
PLS HELP ME

**Comment by Cripyc** [comment]
FFS RESPOPNEDDDDDD

**Comment by scalda** [comment]
you will need to remove your armor by nbtexploror and delete the armor pieces from your inventory.

this is a mod issue, not a pack issue

and your tone in your last message is not appreciated we all have busy lives atm
