### ISSUE TITLE
VeinMiner Rejection

### ISSUE THREAD

**Issue by spectrumization** [scalda/FoolCraft#501]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I am currently running a server with foolcraft 1.3.3 files on as well as a client with 1.3.3 on after a random amount of time sometimes straight after a restart sometimes a few hours after i try to join the server and get disconnected due to a mod rejection from vein miner here is the console code https://pastebin.com/SvKrX2ri it says that its the wrong version however both the server and client are running veinminer (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) and i have even deleted the one from the server and upload it from the client files. This is fixed when the server is restarted however it effects everyone on that server and as soon as one person gets it no one can join as they also get it until i can restart the server or it does it auto every 6 hours

## Reproduce Steps
Make a fresh server running 1.3.3
leave it running for 1min - 48hours
join the server and get disconnected due to this

## Additional Information
Full server logs up until the point of occurrence
https://pastebin.com/SbET7qt6 - latest log
fml latest log is too big for pastebin  so attached to this
[fml-server-latest.txt.zip](https://github.com/scalda/FoolCraft/files/1036360/fml-server-latest.txt.zip)

**Comment by scalda** [comment]
This is a sponge issue don't use it and it will be fine. please search the closed issues next time

regards scalda
