### ISSUE TITLE
Cannot hoe vivid grass

### ISSUE THREAD

**Issue by jrkirkley** [scalda/FoolCraft#502]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
after spreading vivid grass in my farming area i have to replace dirt and hoe it before the vivd grass spreads to make a farming area. trying to directly hoe fails constantly.

## Reproduce Steps
(1.3.3 foolcraft )using Any pasture seeds with the exception of the plain pasture seed the player cannot hoe the ground after it spreads.

**Comment by scalda** [comment]
I don't think you are suppose to be able to hoe the mutated grass, but i would take it up with the mod author as this isn't a pack related issue
