### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by Anniecat77** [scalda/FoolCraft#504]
I don't get some items in game

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

When I play the game and watch the videos of the modpack from the players and do not have some of the items they have

**Comment by jrkirkley** [comment]
a lot of those vids are earlier versions. some items were removed either because of bugginess or because they caused uintended gameplay shortcuts.

**Comment by Anniecat77** [comment]
On Wed, May 31, 2017 at 8:37 PM jrkirkley <notifications@github.com> wrote:
what about the loot bags with player names

**Comment by jrkirkley** [comment]
they only show up when killing a boss entity such as a wither.

**Comment by Anniecat77** [comment]
On Wed, May 31, 2017 at 8:40 PM jrkirkley <notifications@github.com> wrote:
thank you that was very helpful
