### ISSUE TITLE
Iskallium Reactors Broken! - Unable to make steel blocks! 

### ISSUE THREAD

**Issue by ftrocchi** [scalda/FoolCraft#505]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I am unable to craft any of the Steel (ingots/blocks) needed for iskallium reactors.

## Reproduce Steps
See video for reproduction.

## Additional Information
I recorded a video that shows what I am seeing.  
https://www.youtube.com/watch?v=XuuF3-bftW8

Thanks guys!

**Comment by scalda** [comment]
what version of the pack are you running as i know this works, there must be something wrong with your scripts

**Comment by ftrocchi** [comment]
Even though I said I think it is server related, that doesn't make sense, as it doesn't work in single player mode for me.
 
I am continuing to tinker with this here as well.

**Comment by ftrocchi** [comment]
Scalda,

I think you can close this ticket.  I completely removed the FoolCraft installation from both  client machines... and removed the curse client as well.  Basically went back and reinstalled everything.  Now I can access everything with Iskallium Reactors, so I'm good to go.

I am curious though how both of my machines had the same issue.  My only thought is that when I did the original installs and the upgrades over the past months... I had some sort of issue.   No idea what.

If you want me to keep the video up for archiving purposes let me know, otherwise I will remove it.

thanks!
