### ISSUE TITLE
draconic generator/supremium coal/ server crash

### ISSUE THREAD

**Issue by superon** [scalda/FoolCraft#506]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
putting supremium coal in a draconic generator crashes the server

## Reproduce Steps
put supremium coal in a draconic generator

**Comment by scalda** [comment]
please report this to the respective mods issues pages as this is a incompatibility between the 2 mods.
