### ISSUE TITLE
botania marimophisis flower/server crash

### ISSUE THREAD

**Issue by superon** [scalda/FoolCraft#507]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
i placed one of these flowers and the server crashed.

## Reproduce Steps
firstly i placed a builder to mine everything that isn't regular stone or marimorphosis flower (i think i forgot to include the grass/dirt block it was placed upon), i turned the builder on and placed the flower, at this point i hear something being mined and the server crashes, logging in repeatedly crashes the server so now it's running with ticking blocks being removed.
i can plant more but they either do nothing or change a few blocks before becoming inactive, removing the flower changes it into what looks like a regular rose but has a message asking the player to contact a dev about it.

**Comment by Jo-Mamma75** [comment]
It's a bug with that mod.  Follow the instructions in #423 that I posted and it should fix your world.

**Comment by superon** [comment]
ahh err, we had done this and left the settings 
B:removeErroringEntities=true
B:removeErroringTileEntities=true
for a previous error (draconic generator/ supremium coal)   also thanks for being so active

**Comment by superon** [comment]
further info, seems that it occasionally converts a few blocks before failing, if we get the server working again (broken atm bc of something to do with agricraft and 1.4, was explained as "looks like its trying to ton client con=de on the server, evey start up attempt has crashed the server" idk what that means, seems reverting to 1.3.3 still has the persisting problem) i'll attempt to give more details

**Comment by scalda** [comment]
1.4 is in beta and should be used for testing only while we work out bugs and such there is one issue with agricraft server side which is in the process of being fixed.

glad your initial issue is solved please close the issue
