### ISSUE TITLE
Startup crashes on Foolcraft 1.3.3

### ISSUE THREAD

**Issue by ajdjyt** [scalda/FoolCraft#509]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I am crashing at start up continuously i have not added any mods, though i have tried to copy over mods from ,FOOLCRAFTS MODS folder To My CUSTOM MODS folders,it may be that. i have alocated 6 GB ram to MC in the curse/twitch launcher i have only  8GB of ram in my system though.but i have been playing foolcraft since like 27th March and have had very few issues ,all of them fixed and common,
im playing on a laptop with the specs of the following
Intel I3-5005U@ 2.00Ghz
Windows 10 64 Bit (maybe update 1501 or the closest one to it) 
8 GB of RAM 
1TB HDD with 140 GB left on it

## Reproduce Steps
I have no idea it is just on start up

## Additional Information

[latest.txt](https://github.com/scalda/FoolCraft/files/1049728/latest.txt)
[crash-2017-03-27_20.00.23-server.txt](https://github.com/scalda/FoolCraft/files/1049729/crash-2017-03-27_20.00.23-server.txt)
Please help me as soon as possible i really wanna play foolcraft right now and dont want to create a new profile cause even after copying over journeymap data my waypoints dont apear ,and i dont want to play on my other profiles of foolcraft cause they on 1.2.2 on 1.2.1 and my internet this month is a bit bad. so i cant update them + the journey map issue and its just hassle copying over my worlds and recreating all my waypoints in all my worlds.
and i also dont see 1.4 availiblefor update even though it is the 3rd of june for me at the time of writing this

**Comment by legodude17** [comment]
Please put the log on pastebin.com or gist.github.com.

**Comment by ajdjyt** [comment]
paste bin doesnt work for me :p

**Comment by Jo-Mamma75** [comment]
Basically there is a problem with an ExU2 block interacting with a Malisis door somewhere in your world.  The easiest thing I can suggest to you to fix it is follow the instructions I posted in #423 .
Please do that and post back here to let us know if you need additional assistance or close the issue.

**Comment by ajdjyt** [comment]
could you please specify the world name ,if the world name is "Real Survival" Then The ExU2 block
Is a mechanical user which I had placed in 1.1
And had removed in 1.2 by removing the mod ExU2 and starting and then closing and adding the mod to get rid of it
Apparently it has come back then somehow and is a ticking identity

**Comment by ajdjyt** [comment]
I am trying your solution from Thread #423 as we speak hopefully this fixes it

**Comment by ajdjyt** [comment]
oh and this thread is why i am asking the world name cause of this 
https://github.com/rwtema/extrautilities/issues/1407

**Comment by ajdjyt** [comment]
the door is a factory door from malisis doors

**Comment by ajdjyt** [comment]
[crash-2017-03-27_20.00.23-server.txt](https://github.com/scalda/FoolCraft/files/1060087/crash-2017-03-27_20.00.23-server.txt)
My Crash After updating to 1.4 Beta and setting the Clear Entities to true and setting clear tile Entities to true in the forge.cfg file and if it matters i used notepad++ to edit the file
and my log file Is below  
[latest (2).txt](https://github.com/scalda/FoolCraft/files/1060090/latest.2.txt)
:( no  improvement what so ever _-_ i am so confused why this is not working Please help  
Jo-Mamma i think the issue is due to a chisel block in my world or it is an issue in the mod chisel and not
Chisel&bits i personally don't use that mod i have only ever used the mod to see if i could get used to it
i didn't get very fond of it so i didn't use it for except making a few letters to see how they look.

**Comment by scalda** [comment]
this is a crash with the exu user which we have disabled in the pack so i'm not sure if you have renabled them?

**Comment by ajdjyt** [comment]
no i haven't scalda because i did not know how to do so and i see iskalls videos so i knew if i did enable
them i would be crashing non stop -_-

**Comment by ajdjyt** [comment]
do  i try the fix i did ,as i had done before and mentioned in the thread i posted at extrautils2  I.e the thread i referenced here

**Comment by scalda** [comment]
Yeah it looks like it got enabled again in 1.4 but i have reverted it for 1.4.1 when a couple of mods have been updated to fixed a few issues

**Comment by ajdjyt** [comment]
ok

**Comment by ajdjyt** [comment]
i dont see 1.4.1 availible for update :(

**Comment by ajdjyt** [comment]
and by the ways scalda i got this issue before 1.4 ,and while i was running 1.3.3

**Comment by ajdjyt** [comment]
so maybe when i updated to 1.4 the issue became bigger?
So i think you should have a look at the logs i sent in the first post because that might be a colossal chests issue like i had when i was on 1.2 and got it fixed by updating to 1.3.1 ,And since i have colossal chests in all my worlds except for 3 out of maybe 6 or 7,it has a high chance to be that ,and i have no Mechanical users
since 1.2 ,though i might have had them in item form in some chests somewhere in the "Real Survival" world which was my main world until 1.3.3

**Comment by ajdjyt** [comment]
and i had no other worlds except for one i tried out the pack when mechanical users were craft able or enabled

**Comment by ajdjyt** [comment]
scalda so is there no way i can play foolcraft till after update 1.4.1 or 1.4.2 ?
If so that is just upsetting i love this modpack i want to play this pack everyday ,there hasn't been a day since April i haven't played this modpack . And i dont think i can just play skyfactory or Project Ozone 2 or FTB beyond tlll 14.1 or 1.4.2

**Comment by ajdjyt** [comment]
i really want to play foolcraft right now ,can you tell me a way i can edit a .cfg file to disable them

**Comment by ajdjyt** [comment]
do i edit Exu2s cfg file in the configs folder?

**Comment by ajdjyt** [comment]
do i make the line "User=true"" to "User=false" in the extrautils2.cfg ?

**Comment by ajdjyt** [comment]
so for troubleshooting purposes i have created a new profile on 1.4 ,and i have moved all my worlds and nei data to the new profile,
Now The steps i have taken are as follows
I changed the line "user=true" to "user=false" in the new profile ,this helped me to at least start up foolcraft
now the problem is if i start any world minecrafts memory plunges down to about 490 MB 
and a slightly weird note :- When foolcrafts finishes loading its ram is at about 1.7 GB but my RAM usage is up to 85 to 90% which means that the RAM usage is normal though im not sure what this means and
i HAVE BSOD'd while writing this luckily chrome saved my a@@ and my laptop is having driver issues and software issues ,i know this cause i looked up the error messages(from the BSOD) on microsofts website hopefully it wasn't due to minecraft foolcraft

Note:- Sorry for getting so techinical here since im a bit upset right now
Hope You can help me out

**Comment by scalda** [comment]
you did change the correct line in the config

as for the rest of the problems i have no idea where to start i'm sorry. make sure you have enough ram allocated to foolcraft it might of changed when you updated the pack

**Comment by ajdjyt** [comment]
ok

**Comment by ajdjyt** [comment]
it is still at 6GB or 6144 MB

**Comment by ajdjyt** [comment]
scalda ,do i close this issue or leave it open till i can successfully play the pack?

**Comment by scalda** [comment]
we shall leave it open for now so other people can see it

**Comment by ajdjyt** [comment]
ok

**Comment by ajdjyt** [comment]
I got it to run finally apparently my old profile seems to be corrupted and it started working in my troubleshooting profile where I turned of the mechanical users , so thanks for all the help anyways
I got my worlds transferred but couldn't get my Journey Map Data so could you specify which file folders I have to copy over for my Journey Map Data

**Comment by ajdjyt** [comment]
Scalds even after I moved the folder "nei" in my saves folder to the new profiles folder I still don't have my journey map data , which files do I copy from the old instance to the new one to get my Journey Map Data back?

**Comment by scalda** [comment]
The journeymap folder

**Comment by ajdjyt** [comment]
ok thnx scalda

**Comment by ajdjyt** [comment]
do i close the thread?
