### ISSUE TITLE
mini map doesn't work with opticien

### ISSUE THREAD

**Issue by Niksnut** [scalda/FoolCraft#51]
As the title says; The minimap no longer works after installing Optifine. Without Optifine there is no problem.

Playing on aan iMac with 8GB Ram i5 Processor

**Comment by CriticalMole** [comment]
Which version of Optifine?

**Comment by Niksnut** [comment]
Optifine 1.10.2 HD U D6, the newer one crash instantly

**Comment by Niksnut** [comment]
UPDATE: Problem fixed! It was something with the videocard. I play foolcraft at the moment on my MacBook Pro mid 2016, no problem at all!
