### ISSUE TITLE
crushing/streamlined enchants don't take

### ISSUE THREAD

**Issue by superon** [scalda/FoolCraft#511]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
the Crushing and Streamlined Enchants don't attach to swords (i have tried several) in server.

## Reproduce Steps
get a Streamlined or Crushing enchanted book, place it in an anvil with a sword and try to attach the enchant. works fine in sp

**Comment by scalda** [comment]
What mod are those enchant from?

**Comment by Jo-Mamma75** [comment]
I believe they are added from Natural Pledge.
Streamlined raises attack speed and lowers attack damage.  Crushing does the opposite.
I believe these enchantments were intended for the Fists of Thunder and Mjolnir but not sure about anything else.

**Comment by superon** [comment]
ahhha, they appear to work for regular swords in singleplayer
