### ISSUE TITLE
ender actuator - client crash

### ISSUE THREAD

**Issue by superon** [scalda/FoolCraft#512]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
i placed an ender actuator and right clicked it (wondering what it does bc i could find any in or out-game documentation on natural pledge)

## Reproduce Steps
get an ender actuator, place it in world, right click it..

**Comment by legodude17** [comment]
Please report that to natural pledge.

**Comment by scalda** [comment]
what legodude said
