### ISSUE TITLE
mca players titled "none"

### ISSUE THREAD

**Issue by superon** [scalda/FoolCraft#513]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
bc their is no crystal ball when starting with this modpack players are default to be called "none".

## Reproduce Steps
talk to villagers, wait for them to refer to you by "name".

## Additional Information
request that the pack defaults player names to the player names of the players that are named when named the names.

**Comment by scalda** [comment]
sorry, there is no option to do what you are asking as far as i can find within the config. If you know of the setting that needs changing please let me know

**Comment by sarifynna** [comment]
Hi, you would need to set this to true:
# Toggles giving the crystal ball to new players on join. WARNING: If this is false, you must spawn the crystal ball in later manually!
    B:"Give crystal ball"=false

Because the player's name, gender, and marital preference are set when you first use the crystal ball.

**Comment by scalda** [comment]
Yeah we don't want to give people the crystal ball as it can be used to get starter houses and such in the first part of the game

**Comment by superon** [comment]
right, there is no way, that i can see, this is why i'm suggesting to make it automatic;) re: get someone to make a mod to introduce that mechanic?

**Comment by sarifynna** [comment]
Yep you just have to also change this to false:
`    # True if players can have the option to spawn structures during MCA's setup on a server. WARNING: POTENTIAL FOR GRIEFING IS VERY HIGH - YOU HAVE BEEN WARNED
    B:"Enable structure spawning on server?"=true`
