### ISSUE TITLE
Reactant Dynamo Won't Accept Blaze Powder

### ISSUE THREAD

**Issue by McSassyK** [scalda/FoolCraft#514]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I made reactant dynamos and pumped in zephyreum aerotheum (fuel). Then I tried to put in the blaze powder (reactant). When I exit the dynamo's GUI, the blaze powder just pops out. I tried piping the powder in with item conduits and that doesn't work either. Both the ZA and the blaze powder are valid fuel types for this reactor.

## Reproduce Steps
Make a reactant dynamo. Add zephyreum aerotheum. Try to add blaze powder.

**Comment by scalda** [comment]
blaze powder doesn't produce any power so that is why you can't put it in the dynamo

**Comment by McSassyK** [comment]
But.... It's one of the reactant types for that dynamo? Did you look at the reactant types listed in game on the dynamo? Or watch Direwolf20's tutorial? Lemming confirms this is a valid reactant for this dynamo. He said there might be a conflict within the mod.

**Comment by scalda** [comment]
well according to my jei it doesn't produce any rf in this pack

<img src=https://i.gyazo.com/72e865f7277addd8f815332a0c64d15c.png>

**Comment by McSassyK** [comment]
My jei:
![myjei](https://user-images.githubusercontent.com/23440413/26929613-e621d276-4c1f-11e7-8570-38a400f99cdd.jpg)
Tweet from Lemming when I told him blaze powder wasn't working:
![lemming](https://user-images.githubusercontent.com/23440413/26929623-f281ba68-4c1f-11e7-9806-6a005c68ed0a.jpg)
Direwolf20 tutorial from 3 months ago: 
https://www.youtube.com/watch?v=5NYNuDpzmyc
Please note jei of reactant dynamo at 14:08 shows blaze powder producing RF.

Not sure why your jei and mine are different - my Foolcraft is just 1.3.3 with no modifications whatsoever. If I can't use blaze powder, so be it. I'll just use something else. Just wanted you to see that I'm not crazy and it should actually be an option as far as I can tell :)

**Comment by scalda** [comment]
let me check my 1.3.3 instance as that was from my 1.4 instance
 and thanks for the links

**Comment by McSassyK** [comment]
You're very welcome! Thanks for looking into it. I know you have a billion more important bugs to worry about.

**Comment by scalda** [comment]
It shows the same as yours in my 1.3.3, so at least in 1.4 it will show that it produces 0RF

thanks for bringing it to my attention though

**Comment by scalda** [comment]
i am going to close this for now, but i will try and see what is causing this
