### ISSUE TITLE
Huge Memory Problem

### ISSUE THREAD

**Issue by RezaSmith** [scalda/FoolCraft#515]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
so the problem is me and all of my friends , whenever we launch the pack everything is fine , but after 1hour or so the memory usage increase and increase to a point where my Ram uses 100% and fps drops and everything collapse , basically i have to close and rerun the pack again . i have 12gig Ram , some of my friends have 8 and 16 but all have the same problem . i've seen people in here having this issue as well.
P.S i set my ram in twitch client 6gb but it uses around 9gig (all i have) 

## Reproduce Steps
just playing for 1 hour or so

**Comment by Rahjja** [comment]
My friend and I have the same issue. I guess I should make a post as well.

**Comment by scalda** [comment]
please refer this to #467
