### ISSUE TITLE
ticking player crash - chest transporter/item conduit/infinity armour?

### ISSUE THREAD

**Issue by superon** [scalda/FoolCraft#517]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
i attempted to move a chest with an obsidian chest transporter, the chest is/was/is? connected via an item conduit, the game crashed (client crash whilst on server), i attempted moving a chest in sp with an obsidian transporter (linked with item conduit) to see if that was the issue and the similar crash occurred and the client crashed again.   i check the crashlog to see it mention "	at abused_master.avaritiaadditions.items.ItemArmorInfinity.onArmorTick(ItemArmorInfinity.java:87)" so i think maybe the armour is causing an issue but idk...  i tried this again with various combinations of that amour and couldn't reproduce the crash again:/
i am now unable to successfully log i believe due to ticking player.

## Additional Information
https://pastebin.com/wQgWpjZH

**Comment by superon** [comment]
upon revisiting this it seems i didn't crash previously bc i was in creative, setting gamemode to survival fixed this.. as in broke it making me crash again

**Comment by superon** [comment]
... and now i tested without the conduit and i think it's actually bc of the hunger debuff that the armour wants to ignore, pure guesswork there but seems more of an issue with the avaritia addition mod, will post in the appropriate place;)

**Comment by Jo-Mamma75** [comment]
@superon It is an issue with the Infinity Armor.  Not sure but that "may" be fixed in the latest update of the pack with a newer version of Avaritia.  It happens(ed) to a lot of us when hit by a wither whilst wearing the armor.
Make a backup of your world and update to 1.4 and see if the problem persists and then report back here to let us know.

**Comment by superon** [comment]
i've tested this with every current version of avaritia and it hasn't been fixed as yet: 
https://github.com/Morpheus1101/Avaritia/issues/12#issuecomment-306633788
"Morpheus1101 commented 21 hours ago
The issue had been fixed, but the same issue but different cause had appeared, hence why this was re-opened. As yet there is no new release that has a fix for this."

**Comment by Jo-Mamma75** [comment]
@superon 
According to a recent issue on the Avaritia Github, it appears that this issue may still persist in even the latest version of the mod (although the changelog says otherwise).  Just letting you know.

**Comment by superon** [comment]
ok thanks, was thinking about adding avaritia instead of avaritia additions, seems to me this may not be as simple as just adding the mod tho:/  you'd know better than i

**Comment by scalda** [comment]
fixed in 1.4.6
