### ISSUE TITLE
Memory Rising until Java is not usable in 45 minutes.

### ISSUE THREAD

**Issue by Rahjja** [scalda/FoolCraft#518]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
This is a copy of my forum post on the Tom's Hardware website. I haven't received a response in over a week so I am trying here. Originally I thought the issue was just that my system needed some tweaking relating to memory, but I have seen others having the same issue with this pack. This is not the first server I have run on this PC while simultaneously playing and I have not had a problem until now. I have seen another person on this GitHub with the same problem; however I am making a post to give more details and include crash reports. My issue is the same as his: Constantly rising memory usage. I don't know about the other guy's issue (he didn't say much) but mine rises in both the Server client and the Game client. 

Is there anything I can do to fix this?

[b]Description of the issue:[/b]

I am consistently getting a warning that my system ran out of memory and that I need to save work and close applications. Java is always listed as the program suggested to close. Sometimes I can cancel and resume as normal and sometimes I can only click okay and my PC will force close a program for me.

[b]Activities at the time:[/b]

This happens only after about 30 minutes of playing the PC Java version of Minecraft. I am hosting the server and also playing on the server on the same machine; so there are always 2 Java clients running: the Server client ( .jar launched from a .bat file), and the Game client (launched through the [urlExt=//app.twitch.tv/]Twitch App[/urlExt] ). I am also on a call on Skype.

[b]Initial thoughts/attempts to solve the issue:[/b]

My first thought was to reduce the load so to speak by adding some java parameters to the Game client since it is the one with the larger issue (it has crashed several times during the memory alerts and it is using up ~4 times the memory as the Server client is).

Parameters I added: 
-XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=20000 -XX:ParallelGCThreads=4

The parameters are (hopefully) for optimization when allocating 6G to the Game client. The only parameters on the server are to set the Xms to 128M and the Xmx to 6G. 

After I added the parameters the game was running MUCH smoother, however about 45 minutes into play I am still getting the out of memory alerts.

My next thought was then to adjust the paging file since the amount of memory being used does not add up to what my system [i]should[/i] have to offer. 

[b]Pertaining to the Paging File:[/b]

I had previously set custom values on the Paging Files on both of my disks while troubleshooting why my 2nd drive was not accessible after a repair. I had the SSD (C drive) replaced due to the old one being faulty, and when I got my laptop back my data (D drive) had disappeared. I used forums such as these to get it back, so it is possible I did something wrong in my search for renewing access to my drive. 

Regardless, I am asking for some advice in the proper settings for the Paging Files for my system to deal with the memory issue I am having. It is my understanding that more is not always better depending on what each of your drives are doing, and I cannot find a good example in forums for me to follow.

[b]Questions:[/b]

Should I have a Paging File on the SSD and the Data drives, and if so, what size should they be? If you have any advice for these sizes, please, could you tell me what sort of exceptions there may be, if any?

Also, if the Paging File is not going to solve this issue, do you have any advice for what other options I can look into?

[b]PC Details:[/b]

MSI GT72 Laptop
CPU: Intel i7-4710HQ 2.5 GHz
GPU: Nvidia 970M 
RAM: 16 GB
Drive 1: ADATA SP900NS38 | SSD 256GB (90.8 GB currently free)
Drive 2: HGST HTS721010A9E630 | HD 1TB (306 GB currently free)
OS: Windows 10

Both the Server client and the Game client are located on the SSD along with the OS. The Server is started first, then the Game client. While the Game is loading, the CPU usages peaks to 99% then drops to ~25% while playing and the Memory is never higher than around 70% even when getting the out of memory alerts. Temperatures on the CPU and GPU are around 50 degrees Celsius. 

Current Paging File settings:

http://i.imgur.com/tpgmEWW.jpg

## Reproduce Steps
Start Foolcraft Server.
Start and play Foolcraft Modpack through Twitch App.
After approximately 45 minutes of play, the memory usage has gone from ~2000 MB up to ~7000 MB and ~1500 MB up to ~ 3500 MB for the Game client and Server client respectively. 

## Additional Information

Game Client Crashes

Crash 1 Game
https://pastebin.com/9DXMQe8y

Crash 2 Game
https://pastebin.com/LpJs3wrM

Note: When the Memory alerts happen I always restart the Game client rather than let it crash so these reports may not be the best. If so, let me know and I will allow it to crash and upload another report.

Server Client Crashes

I don't recall when/where/why the server crashed but there may be useful information in the reports.

Crash 1 Server
https://pastebin.com/kL2cx269

Crash 2 Server
https://pastebin.com/CTYMn3jY

**Comment by ajdjyt** [comment]
I am not sure but it might be your GPU running out of memory? i do not know alot about graphic cards
,though if it is not  your graphic card then it must be that you have a leak or windows is not letting go of cached data .which is data stored in ram for later use. i guess windows does not expect you to use 12 GB of RAM at the same time and is not ready to let go of cached data ,i think your page file is too small though ,try experimenting with sizes though even though it is tedious and i would suggest keeping the page file on your ssd ,since i believe only windows is on your ssd , or maybe your RAM has a Faulty chip ,
I Hope This Helps

**Comment by scalda** [comment]
please refer this to #467

**Comment by scalda** [comment]
the client crashes are due to rendering please make sure that Minecraft is allocated to the dedicated GPU you have and not the CPU based one

as for the server, it is a minetweaker crash these are quite common craftweaker has been updated in the 1.4 beta version of the pack but until agricraft is fixed and updated it can't be run server side

a lot of the mods have been updated in 1.4 so we are hoping that a lot of the memory issues will go away but until agricraft is fixed not a lot of testing can be done server side

**Comment by Rahjja** [comment]
Thanks! I'll double check the GPU settings and look for the updates.

**Comment by Jo-Mamma75** [comment]
@Rahjja  I can almost guarantee that it's caused by the More Player Models mod.  Try disabling that and see how it goes.  Report back and let us know.

**Comment by scalda** [comment]
We have removed MPM from the pack in version 1.4.4 of the pack, please try this version and let us know how it goes
