### ISSUE TITLE
[suggestion]  farmable enderdragon 

### ISSUE THREAD

**Issue by redstoneguy10ls** [scalda/FoolCraft#520]
**

## SUGGESTION/HELP
- x I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
hi. so i know that you cant farm the enderdargon with the woot farm because of balancing issues, but i don"t think that"s fair because of lag. i try to fight the dragon and it takes forever because of lag. and taking 10 minuets to get a dragon egg or heart inst what I call fun. my suggestion is making it super expensive with RF and not allowing for the mass upgrade.

**Comment by Jo-Mamma75** [comment]
You are more than welcome to implement the changes in your own instance or server but we will not be implementing this in the public pack.
Thank you for the suggestion though.
Word of advice, use the Emerald Block armor when you kill the dragon manually.
