### ISSUE TITLE
Changelog not updated to 1. 4

### ISSUE THREAD

**Issue by Ravalli03** [scalda/FoolCraft#521]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

Changelog PDF not showing 1.4 version changes. Before I update, would like to see what has been changed.

**Comment by Jo-Mamma75** [comment]
That was my job last night but I was tired and went to bed early.  I will get it done when I'm able.

**Comment by Ravalli03** [comment]
No problem, just reporting in case it was forgotten. Thanks for the quick reply

**Comment by chland** [comment]
You find a lot of the changes over at Reddit -
 https://www.reddit.com/r/Foolcraft/comments/6fsrkb/foolcraft_14_beta/ 

And here are the updated/added mods (feel free to use this Jo-Mamma75 if you don't already have something like that) :

---------------------

# FoolCraft, Version 1.4

## Mod(s) Added

- Portal Gun by iChun (6.0.1)
- iExtras by Winter_Grave (0.0.7)


## Mod(s) Updated

- AgriCraft by InfinityRaider (2.0.0a15 > 2.0.0a18)
- Angel Ring To Bauble by Portablejim (0.2.3.16 > 0.2.4.19)
- B.A.S.E by lanse505 (1.3.0 > 1.4.0)
- Baconators by Baijson (3.0.5 > 3.0.6)
- Baubles by azanor (1.3.9 > 1.3.11)
- Biomes O' Plenty by Glitchfiend (5.0.0.2162 > 5.0.0.2236)
- Brandon's Core by brandon3055 (2.1.6.98 > 2.1.7.102)
- Chameleon by jaquadro (2.2.2 > 2.3.0)
- Chance Cubes by turkey2349 (2.3.5.174 > 3.0.1.189)
- Chest Transporter by CubeX2 (2.5.13 > 2.5.17)
- Chisel by tterrag1098 (0.0.9.15 > 0.0.10.22)
- CodeChicken Lib 1.8.+ by covers1624 (2.5.7.241 > 2.5.9.267)
- Colossal Chests by kroeser (1.5.0 > 1.6.0)
- CompatLayer by McJty (0.2.5 > 0.2.9)
- Concrete Mod by Dbrown55 (4.1-APRILFOOLS > 1.1)
- Cooking for Blockheads by BlayTheNinth (4.2.39 > 4.2.43)
- CraftTweaker by jaredlll08 (3.0.24 > 3.0.25)
- Cyclops Core by kroeser (0.10.0 > 0.10.4)
- DecoCraft2 by RazzleberryFox (2.4.1 > 2.4.2)
- Draconic Evolution by brandon3055 (2.0.10.199 > 2.0.12.222)
- Ender IO by CrazyPants_MC (3.1.180 > 3.1.192)
- EnderCore by tterrag1098 (0.4.1.65 > 0.4.1.66)
- Extra Utilities by RWTema (2.1.4 > 2.1.4.3)
- FTB Utilities by FTB (3.5.4 > 3.6.5)
- FTBLib by FTB (3.5.4 > 3.6.5)
- Hatchery by GenDeathrow (0.2.10 > 0.3.15)
- Hermitron by Winter_Grave (0.2.12 > 0.2.13)
- iChunUtil by iChun (6.3.0 > 6.3.2)
- InfinityLib by InfinityRaider (0.8.0 > 0.10.0)
- Inventory Pets by Purplicious_Cow (1.4.9.3 > 1.4.9.5)
- Iron Chests by progwml6 (7.0.11.797 > 7.0.15.804)
- Iskallium Reactors by Winter_Grave (0.3.8 > 0.3.9)
- IvToolkit by Ivorforce (1.3.2.1 > 1.3.3)
- Just Enough Items (JEI) by mezz (3.14.7.417 > 3.14.7.420)
- LootBags by Malorolam (2.3.7 > 2.3.9)
- LootTweaker by Daomephsta (0.0.5.1 > 0.0.6.2)
- MTLib by jaredlll08 (1.0.2 > 1.0.3)
- Mob Grinding Utils by Vadis365 (0.1.8.17 > 0.1.8.21)
- ModTweaker by jaredlll08 (2.0.11 > 2.0.12)
- More Chickens by GenDeathrow (1.0.11 > 1.1.4)
- Mystical Agriculture by BlakeBr0 (1.5.1 > 1.5.4)
- Natura by mDiyo (4.1.0.48 > 4.1.0.65)
- Not Enough Items 1.8.+ by covers1624 (2.1.3.207 > 2.1.3.220)
- Pam's HarvestCraft by MatrexsVigil (1.10.2h > 1.10.2j)
- PlusTiC by Landmaster_phuong0429 (4.3.0.2 > 5.0.1.0)
- RFTools by McJty (5.92 > 6.01)
- Railcraft by CovertJaguar (10.0.1 > 10.1.2)
- Recurrent Complex by Ivorforce (1.2.10 > 1.3.1.1)
- Shadowfacts' Forgelin by shadowfactsmc (1.4.1 > 1.4.2)
- Simply Conveyors & More by Zundrel (3.0.3 > 3.0.6)
- Storage Drawers by jaquadro (3.7.1 > 3.7.8)
- Tinkers Construct by mDiyo (2.6.3 > 2.6.5)
- TorchMaster by xalcon (1.2.1.23 > 1.2.3.27)
- Vic's Modern Warfare Mod by Vic4Games (1.9.1 > 1.10.1)
- ViesCraft - Airships! by Viesis_Gaming (4.26.13 > 4.38.42)
- Woot by Ipsis (1.3.1 > 1.4.0)

**Comment by Ravalli03** [comment]
Thanks!

**Comment by Jo-Mamma75** [comment]
And I finally got around to updating the changelog and getting it put up so the whole thing is there now.
