### ISSUE TITLE
Foolcraft 1.4 Iextra bug

### ISSUE THREAD

**Issue by Tect0nic** [scalda/FoolCraft#522]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
The iExecutor is not saving it's settings once the GUI is closed

## Reproduce Steps
Crafted the iExecutor. Placed it down to plan on milking cows. Open the GUI and set it to right click. Put in an empty bucket. Closed the GUI and put in a fluid cow. Fluid cow got killed

## Additional Information

Screenshots seconds apart
http://imgur.com/Ife7dcL
http://imgur.com/xK1NT9b

**Comment by WinterGrave** [comment]
wow, never happened during tests, checking it

**Comment by Tect0nic** [comment]
The screenshots are seconds apart with me doing nothing to the executor
