### ISSUE TITLE
Foolcraft 1.4 Hermitron case duping!

### ISSUE THREAD

**Issue by Xaero252** [scalda/FoolCraft#523]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
As the title states, with version 1.4 there is an item duplication glitch with the Hermitron cases, so far I haven't found an item they can't dupe.

## Reproduce Steps
Grab a Hermitron case, and some item.
Shift click the item into the case.
Shift click the item out of the case.
Watch the quantity of the item you are duping exponentially increase.

**Comment by scalda** [comment]
fixed in 1.4.3
