### ISSUE TITLE
agricraft error? on server startup

### ISSUE THREAD

**Issue by SHOVELL** [scalda/FoolCraft#524]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x] I am requesting help with installing or running the pack

## Issue Description
server will not startup says issue with agricraft

## Reproduce Steps
honestly just starting the serverhttps://slexy.org/view/s216QE8ugs

## Additional Information
Crash-log:
https://slexy.org/view/s216QE8ugs
fml-server-latest:
https://slexy.org/view/s20JC29cOV

**Comment by SHOVELL** [comment]
woops seems there is an issue on agricraft github
https://github.com/AgriCraft/AgriCraft/issues/987

**Comment by scalda** [comment]
yeah looks like there is no update for it yet, i am so glad i set this version of the pack to beta
