### ISSUE TITLE
[Mod Update] Good Ol' Currency 1.1.0

### ISSUE THREAD

**Issue by BeardlessBrady** [scalda/FoolCraft#525]
- [X] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [ ] In single player
     - [ ] In multiplayer
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [X] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

Hey, this is the developer for the Good Ol' Currency mod. I just missed your 'update all the mods' update which is unfortunate as I just released a new version to my mod. It fixes an extreme lag issues when any of my blocks were placed and adds a foolcraft variant for the bill textures (Which I also suggest setting on default ;)) Anyways I hope you can put out a quick update, thanks!

**Comment by scalda** [comment]
Hi no that is fine i am waiting on a bug fix from agricraft so i will add this in as well when that is ready for a .1 update

**Comment by BeardlessBrady** [comment]
Glad to hear :)
