### ISSUE TITLE
V1.4 unable to use current world

### ISSUE THREAD

**Issue by ImTheStigHonest** [scalda/FoolCraft#527]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## crash occurs immediately after the building terrain message is seen
[crash_report_fool_craft_v1.4_stir.txt](https://github.com/scalda/FoolCraft/files/1061150/crash_report_fool_craft_v1.4_stir.txt)

**Comment by scalda** [comment]
see here for a fix [wiki](https://github.com/scalda/FoolCraft/wiki/Ticking-Block-Entity-fix-for-somethings-but-not-all-like-fluidcows)

**Comment by ImTheStigHonest** [comment]
Tried the fix no help :) any other fixes

**Comment by SS396** [comment]
Same exact issue.  :(

I have a wall of nesting pens with multiples of every kind of resource chicken connected to ender io pipes.  It seems that random pens, all from that same area are causing different crashes during world loading, I've tried to load the level 4 times and each time a different nesting pen causes a crash.  I loaded up the backup and ran 1.3.3 and checked the pens in question.  They contain Constantan (twice), Draconium, and Redstone chickens.  Not sure what is causing the problem, or how to fix as deleting hundreds of nesting pens containing hundreds of 10/10/10 chickens I feel is unacceptable and if that is the suggested solution, then I will simply just quit playing this modpack altogether.   I was really hoping that 1.4 would solve the excessive memory consumption issue I've been experiencing since upgrading to 1.3.

My logs are similar except for the block ID and value:

-- Block entity being ticked --
Details:
	Name: com.gendeathrow.hatchery.block.nestpen.NestPenTileEntity // com.gendeathrow.hatchery.block.nestpen.NestPenTileEntity
	Block type: ID #1381 (tile.hatchery.pen_chicken // com.gendeathrow.hatchery.block.nestpen.NestingPenBlock)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (309,68,1411), Chunk: (at 5,4,3 in 19,88; contains blocks 304,0,1408 to 319,255,1423), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Actual block type: ID #1381 (tile.hatchery.pen_chicken // com.gendeathrow.hatchery.block.nestpen.NestingPenBlock)
	Actual block data value: 4 / 0x4 / 0b0100

**Comment by ImTheStigHonest** [comment]
I suppose we could try to remove all the chickens from the pens let them run loose as entities and see if stops the ticking block
would be a pain to have to sort them all out again afterwards

**Comment by scalda** [comment]
my suggestion is to pick the chickens up in animal nets, store them and try reloading in 1.4

**Comment by ImTheStigHonest** [comment]
Confirmed Fix
however do you think putting them back will recreate the crash?

**Comment by scalda** [comment]
there is only one way to find out

**Comment by ImTheStigHonest** [comment]
have slowly been putting chickens back into the wall of cluck so far so good
been adding 10 at a time then backing up save whilst doing other things

**Comment by scalda** [comment]
that's great to here, if all is well when your done please close this issue

**Comment by ImTheStigHonest** [comment]
New problem can't place chickens in nesting pens

**Comment by scalda** [comment]
All chickens or a certain type?

**Comment by ImTheStigHonest** [comment]
OK this is really weird. I found the chickens that vanished when shift right clicking on the nesting pen (new pens gui) the are all in my farm that is 200 blocks from the nesting pen. !!!!

**Comment by ImTheStigHonest** [comment]
Tried it twice more same result chicken doesn't appear in nest ends up roaming in my farm.
different pens tried !!
put the dislocator away as I thought that may be interacting with it

**Comment by ImTheStigHonest** [comment]
broke and replaced all nests same result.

**Comment by scalda** [comment]
Any chance you can send me a copy of your world that had the issues as i have tried 2 active worlds so far with 1.4.4 and all is fine with hatchery

**Comment by ImTheStigHonest** [comment]
Sure whats the best way? can I PM you a dropbox link?
there are some other weird things happening I was waiting to see if anyone else was experiencing them in 1.4.4

**Comment by scalda** [comment]
yeah pm me a link, and what other things?

**Comment by ImTheStigHonest** [comment]
placed items vanish randomly on placement vibrant capacitors, basic io links
progressive automation diamond planters not working with agricraft crops
ender io connections resetting (have to break and replace but this has always been an issue)

**Comment by scalda** [comment]
if on placement i would say it is lag, 
progressive automation: need to be running at least 1.4.3 of the pack,
ender io: this has been a issue since the start of the pack just make sure they are chunkloaded via chicken chunks

**Comment by ImTheStigHonest** [comment]
I'm running 1.4.4 the vanishing items are removed completely from the inventory
diamond planters stoped working after updating to 1.4.4
[https://www.dropbox.com/sh/im23f98vm8g68z8/AACJJrSHie_2ER71m-_6VlAla?dl=0(url)
couldn't find a pm so let me know when you have downloaded the link and ill delete it thanks for all you help

**Comment by scalda** [comment]
is this a single player world or did you run it on a server?

also i have got the files

**Comment by ImTheStigHonest** [comment]
single player world.
I not sure if it will be there as last night I tried it and had all the same results.
literally just tried it and the chickens placed normally!!!

**Comment by scalda** [comment]
all is ok for me to place chickens and remove them no problem, also your diamond planters are working for me that you have on the surface

**Comment by ImTheStigHonest** [comment]
if you load with the dislocated select farm the planters there are the ones not working 
you will have to switch the farm on from the control screen by the refined storage

**Comment by scalda** [comment]
Hiya, sorry for the late reply i had to go ou. but i have just checked and they are all working for me

**Comment by ImTheStigHonest** [comment]
Thanks Scalda.

Ok I'm going to delete all instances and try a fresh install as I still have all the issues.
did you look at the crash report. the ticking chuck for the nesting pens still happening.
it was either the platinum or aluminum chicken that triggered it

**Comment by ImTheStigHonest** [comment]
Fresh instal same result. very strange. could this be a platform issue? I'm not sure if java scripts can be effected that way I'm running in MAC OS X 
ill port the save into windows and try again

**Comment by ImTheStigHonest** [comment]
ok 90% worked when ported into windows. all work when I remove the red stone receivers on both Mac and windows seems the planters lock up when they get either direct or bud power signals.

original ticking block crashes still happening with some chickens

**Comment by ImTheStigHonest** [comment]
[1.4.5_crash.txt](https://github.com/scalda/FoolCraft/files/1091438/1.4.5_crash.txt)
aluminum chicken placed did not appear in the nest the above crash. 1.4.5
in the world I sent you the aluminum chickens are in the left hand hermitron case

**Comment by scalda** [comment]
ok perhaps the id has changed then if they are causing issues, is that the only chicken that you have got to that is causing issues

**Comment by ImTheStigHonest** [comment]
I will have to go through them again as I removed them until there was a fix
let me back up the world and see if it is one nest causing the issue or the chickens

**Comment by scalda** [comment]
its the pen at this location -91,52,-475

**Comment by ImTheStigHonest** [comment]
ok all the old chickens from before the update don't appear in the nests.
any new chickens can be placed

Only the aluminum chicken is causing the crash

**Comment by ImTheStigHonest** [comment]
don't know what to say now created new eggs of the ones I had and was unable to place the chickens in the nests. tried breaking the nests voiding them and adding new ones same result.
not sure if this is a chunk issue but doesn't seem to be
