### ISSUE TITLE
All mystical agriculture plants dont work with agricraft

### ISSUE THREAD

**Issue by aniserrais** [scalda/FoolCraft#529]
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
After updating to 1.4 and loading a world with Mystical Agriculture crops on agricraft crop sticks all seeds are gone and you can put the seeds on crop sticks

## Reproduce Steps
1. create a world in 1.3, place down crop sticks with something like iron seeds (Basicly any seed from mystical agriculture)
2. load the same world up in 1.4

**Comment by scalda** [comment]
This is due to agricraft implementing all of their own mystical agriculture crops now so we removed ours, but it shouldn't effect anything in world as the item ids are the same unless mystical agriculture have changed their item names to lower case. i will need to look into this. the joys of beta testing

**Comment by scalda** [comment]
also the deleting of crops is because we are now using the default crops that come with agricraft and not our own anymore

**Comment by scalda** [comment]
Please reload that same world in 1.4.3 and report back please

**Comment by Jo-Mamma75** [comment]
Closing for lack of response by original poster.
