### ISSUE TITLE
ModPack Won't load when attempting the start up game, then crashes

### ISSUE THREAD

**Issue by supertommyhd** [scalda/FoolCraft#53]
When I Start up foolcraft, it is a bit slow.  However, once it goes to the middle of the "7/7" part, it just stops at a tinker's construct crossbow file.  I wait 2 minutes and come back, but fool craft crashes

**Comment by scalda** [comment]
Please use 6GB ram

**Comment by vvolfe** [comment]
@scalda having similar issue here and verified I am using 6GB of ram.

Latest log file
http://paste.feed-the-beast.com/view/2f0fb5d5

**Comment by vvolfe** [comment]
http://paste.feed-the-beast.com/view/47f9aec1

**Comment by vvolfe** [comment]
Hey I wanted to share that updating my video drivers from ATI website resolved my issue just like yours.

**Comment by GhostMiner02** [comment]
Can i get a llink to the ATI website

**Comment by vvolfe** [comment]
As long as your card is an ati radeon card this should work. 

http://support.amd.com/en-us/download

Just had to google ati radeon drivers
