### ISSUE TITLE
[Mod Request] Add the Chiseled Me mod

### ISSUE THREAD

**Issue by DwellerBenthos** [scalda/FoolCraft#530]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I would like to suggest adding the Chisel Me mod to accompany the Chisel & Bits mod. It reduces the player to several sizes (among other things it does) so that the smallest chiseled bit now appears to be a normal sized block, and can be placed with accuracy just like placing normal blocks at normal size. There are still a few issues with the mod, but I believe they are not critical. Mod can be found here: https://minecraft.curseforge.com/projects/chiseled-me

**Comment by BloodedWine** [comment]
Agreed

**Comment by DwellerBenthos** [comment]
There seems to be an issue with some of the recipes. Some don't show in JEI, but I think that's a known issue with the mod according to it's issues page, and I think some other mod is interfering with the recipe for the pym essence (it's the most basic item in the mod, used to make pretty much everything else). If you follow the recipe, it won't make the essence, but I used Minetweaker to re-create the recipe exactly with the water bottle in the game and it works. If you try to make it without changing the recipe, it will tell you that you don't have water bottles even though you do. Whatever change is made by the other mod to water bottles makes this mod not accept them. A simple addition of the original recipe in Minetweaker fixes this.

Also, the recipe for the item to make you normal size again does not show in JEI, I don't know if this is the issue reported on the mod's issues page or if it just isn't included, which I would think isn't the case, I think it's just not shown in JEI. But you need that item to return to normal size.

**Comment by DwellerBenthos** [comment]
Correction, it's not Pym Essence but the Pym Container that can't be crafted. I'm almost positive it's the water bottle causing the issue. Using Minetweaker to add the recipe with the water bottle that's in the game then seems to make the original recipe work as well? I'm not sure, but I was getting two recipes for it after adding it.
