### ISSUE TITLE
failed to download file

### ISSUE THREAD

**Issue by tacksnbats** [scalda/FoolCraft#531]
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
i was just trying to download and play the mod and it kept giving me this error.

## Reproduce Steps 
i was able to get a few of the .ogg files to download, they had given me the same 'failed to download file' error and i restarted to try and fix it, but it won't go past this error.

## Additional Information

Failed to download file. nether1.ogg
Name: nether1.ogg
URL: http://resources.download.minecraft.net/71/71cc853556f7ca5784c9e9fc8e0bd6778d13027b
Error details: Request error -324: ERR_EMPTY_RESPONSE
Filename on disk: 71cc853556f7ca5784c9e9fc8e0bd6778d13027b
Path: C:/Users\xxxx\Documents\Curse\Minecraft\Install\assets\objects\71/71cc853556f7ca5784c9e9fc8e0bd6778d13027b
Exists: false

(removed my name and replaced with xxxx for privacy)

**Comment by scalda** [comment]
Reinstall the modpack, but make any backups of world saves

**Comment by tacksnbats** [comment]
i did as you said and it works perfectly! thank you so much for the help and the awesome modpack!

**Comment by scalda** [comment]
you are very welcome, have fun
