### ISSUE TITLE
Avaritia bug - Item Bug

### ISSUE THREAD

**Issue by NightbringerMc** [scalda/FoolCraft#532]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Hello there,
I am running the 1.3.3 version of foolcraft and found an issue.
The issue is in the mod "Avaritia".
What is happenning is that the Singularities (items) cannot be obtained in survival, because the items disappear when crafted in survival (the recipe works in creative and the items do not disappear)
It is extremely important that this issue is fixed, since it is a core part of Avaritia.

## Reproduce Steps
To get this bug, you first need to be in survival mode (on a server or in sp) and you need to craft any singularity with the Neutronium Compressor (the amount of resources needed is shown when placing any amount of said resource inside it)
Then, when you reach the specific amount of resources, you see the Singularity on the output slot of the Compressor, but it disappears instantly.
This does not happen in Creative mode. When doing the same thing in creative mode, you can craft the singularity, and take it out of the compressor without any problem.

## Additional Information
This issue does not crash the game, but makes it's most endgame mod unplayable... Which is sad.

**Comment by NightbringerMc** [comment]
Edit : I managed to get one, by adding a TON more resources, but even then they glitched out a little
(For the redstone one it was asking for 500 blocks, and I fed about 1500 blocks and it finally gave 1)

**Comment by scalda** [comment]
This has been fixed in the latest version of the mod but sadly we can't update to it as avarita additions haven't been updated yet but as soon as it is both mods will be updated
