### ISSUE TITLE
V1.4 all mystical agriculture plants deleted from world

### ISSUE THREAD

**Issue by ImTheStigHonest** [scalda/FoolCraft#533]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

went to Mystical agriculture farm all plants missing and tilled fertilized dirt had reverted to normal blocks

unable to hoe fertilized dirt
vanilla plants unaffected

Wiki ticking block fix does not work

## Reproduce Steps
placing double crop sticks crashes the world with ticking entity

## Additional Information
[crash_report.txt](https://github.com/scalda/FoolCraft/files/1065478/crash_report.txt)

**Comment by scalda** [comment]
[already reported to mod author](https://github.com/AgriCraft/AgriCraft/issues/989)

**Comment by ImTheStigHonest** [comment]
Scalda, thanks again, just to clarify for my understanding, the mystical agriculture seeds that I used are still in my system (not 10/10/10) does this mean we can no longer use them within the crop sticks? or we can't plant them at all.
just clarifying as some of my automation was constructed around the farming of these crops
