### ISSUE TITLE
v1.4 Server Run Error

### ISSUE THREAD

**Issue by P4rkerMann** [scalda/FoolCraft#534]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
Im simply trying to run the server for v1.4 given at "https://minecraft.curseforge.com/projects/foolcraft/files" and whenever i run it the server comes up with an error "Caused by: java.lang.NoSuchFieldError: DEFAULT_PLANT_ICON" and im not sure what it means

## Reproduce Steps
Ive never actually successfully ran the server. I unzipped, ran the "start" and this came up.

## Additional Information

[crash-2017-06-09_19.09.20-server.txt](https://github.com/scalda/FoolCraft/files/1065543/crash-2017-06-09_19.09.20-server.txt)
[crash-2017-06-09_19.07.14-server.txt](https://github.com/scalda/FoolCraft/files/1065544/crash-2017-06-09_19.07.14-server.txt)

**Comment by scalda** [comment]
[already reported to mod author](https://github.com/AgriCraft/AgriCraft/issues/995)
