### ISSUE TITLE
Chiseled 1.12 Concrete Blocks Textures Broken

### ISSUE THREAD

**Issue by Hunter-The-Gamer** [scalda/FoolCraft#537]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description 

1.12 Concrete Blocks that were chiseled with Chisels and Bits BEFORE 1.4, now have the texture shown below. Or, when old bits in your inventory were placed down.

## Reproduce Steps 

Chisel 1.12 Concrete Blocks before version 1.4 of Foolcraft, then update to 1.4+. Or, use old bits from 1.12 Concrete (made pre-1.4) and place them down. Finally, the bug occurs when new bits (made post-1.4) are placed using a Positive Chisel Design from pre-1.4.

## Additional Information 
![2017-06-11_20 24 16](https://user-images.githubusercontent.com/29361536/27015730-01b7184a-4ee4-11e7-9e05-d32f8d96e93d.png)
All broken textures are 1.12 Concrete blocks from pre-1.4. When new concrete bits are placed in the same block space, they have the correct texture. The problem also occurs with bits already in your inventory, that remained there when updating. Once a solid block is made, the block reverts to the normal texture.

**Comment by scalda** [comment]
Hi yes already been found please update to 1.4.3 we had to revert the
version of the concrete mod and restore tour world from backup

**Comment by Hunter-The-Gamer** [comment]
Ok thanks, I guess I was still on 1.4.2
