### ISSUE TITLE
Recipe conflict - Block armor

### ISSUE THREAD

**Issue by 71Baker** [scalda/FoolCraft#538]
## SUGGESTION/HELP
- [X] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Recipe for Framing table (from Storage drawers) produces Oak trim helmet (If made by Oak trim)

Suggest a lot of the block armors be removed from config to spare the useful ones. Now there are 10 pages of armors where maybe 1 is useful, and they show up everywhere when you search for stuff.

## Reproduce Steps
Make Oak trim pieces and try to craft a Framing table.

**Comment by 71Baker** [comment]
Tried this with Spruce, Dark Oak and Jungle wood trims also, same result.

**Comment by chland** [comment]
Just press the arrow on the right of the crafting-window to switch from the Oak Trim-Helmet to the Frmaing table: http://imgur.com/432HSG1

**Comment by Jo-Mamma75** [comment]
@71Baker This is why we added the NoMoreRecipeConflicts mod.  As @chland said, use the little arrow in the crafting grid to select the alternative recipes.  Additionally, you can use two different type of trim to accomplish the same thing.
Closing this issue for now.
