### ISSUE TITLE
1.4.1/1.4.2 Thermal expansion machines input output issue

### ISSUE THREAD

**Issue by ImTheStigHonest** [scalda/FoolCraft#539]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
All thermal expansion machines input output colors and sides are not as the GUI
Noticed when requesting auto craft items
Had to play around with random side/color combinations to get the insert and extracts to function 

## Reproduce Steps
Set up on machine and a basic input output

**Comment by Ravalli03** [comment]
Was the machine upgraded? Some of the inputs/outputs are limited using the basic machine. Upgrading it will open them up.

**Comment by ImTheStigHonest** [comment]
All fully resonant, noticed my compression dynamos were not running and all the inputs/outputs were locked up had to select different setting that made no correlation to the colors
also auto crafting stopped working for same reason

**Comment by scalda** [comment]
can you try 1.4.4 and report back please

**Comment by ImTheStigHonest** [comment]
all working now
