### ISSUE TITLE
Add Mekanism (mod addition suggestion)

### ISSUE THREAD

**Issue by supertommyhd** [scalda/FoolCraft#54]
This is a great modpack, but it is still lacking a great tech mod: Mekanism.  It has lots of machines and includes over 5 buildable multiblock structures.  From Jetpacks to balloons, Foolcraft can become much cooler!

**Comment by scalda** [comment]
sorry mekanism won't get added to the pack

**Comment by supertommyhd** [comment]
Why won't it?
