### ISSUE TITLE
Mod suggestion xnet 

### ISSUE THREAD

**Issue by ImTheStigHonest** [scalda/FoolCraft#542]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Not sure if there would be compatibility issues but xnet would allow for some fun automation options

**Comment by Ravalli03** [comment]
Yes, I agree, it's a great mod that allows lots of options using the same pipes, from items, energy, Redstone, and fluids. It's made from the same author of Rftools.

**Comment by Jo-Mamma75** [comment]
I went and looked through the Wiki a little bit and that looks like a really cool mod.  I don't know if we can get it approved for the pack by Iskall but I wouldn't be opposed to having it and at least suggesting it.
Thanks for the submission.
