### ISSUE TITLE
Foolcraft crash when RFTools is loading in in "Initializing mods phase 2"

### ISSUE THREAD

**Issue by knape89** [scalda/FoolCraft#543]
Crashing when startup giving messege "Game crash"

Foolcraft crash when RFTools is loading in in "Initializing mods phase 2"

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

##
[latestlog.txt](https://github.com/scalda/FoolCraft/files/1072799/latestlog.txt)

**Comment by Jo-Mamma75** [comment]
What type of graphics card do you have in your computer?  Do you think your issue may be similar to the following?
https://github.com/McJty/RFTools/issues/1012

**Comment by knape89** [comment]
Im using AMD Radeon 290X.
Dont think i have the same problem as i dont get that message and i dont have Nvidia GPU

**Comment by knape89** [comment]
Jo-Mamma75. Do you have any solution for me? Love the pack but cant play without rftools :(
