### ISSUE TITLE
world crashes on startup after 1.4.3 update, was AFk for 10 minutes

### ISSUE THREAD

**Issue by TonsillarRat6** [scalda/FoolCraft#545]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ X] I am requesting help with installing or running the pack

## Issue Description
my world crashes randomly after playing for a few minutes (was AFK) and now it crashes everyime I open the world

## Reproduce Steps
1. start world
2. crash

## Additional Information
https://pastebin.com/pQN1mwaq
the crash log, it probably has something to do with chickens as it says this in the crash log:
Entity Type: chickens.ChickensChicken (com.setycz.chickens.chicken.EntityChickensChicken)
	Entity ID: 399
	Entity Name: ~~ERROR~~ NullPointerException: null
	Entity's Exact location: 874.06, 66.00, 756.35
	Entity's Block location: World: (874,66,756),

**Comment by ImTheStigHonest** [comment]
[https://github.com/scalda/FoolCraft/issues/527](url)

**Comment by scalda** [comment]
Any chance you can send me a copy of your world that had the issues as i have tried 2 active worlds so far with 1.4.4 and all is fine with hatchery.

**Comment by Larkal92** [comment]
I seem to be having the same issue. Would you like a paste here or in a separate post?

**Comment by scalda** [comment]
Ok all worlds that i have tested with 1.4.5 have all had no issues while running.
