### ISSUE TITLE
1.4.3 server crash on startup caused by LibrarianLib and NaturalPledge

### ISSUE THREAD

**Issue by mcdodge34** [scalda/FoolCraft#546]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description : The server crash on startup, tried it on 4 different PC (3 real PC and 1 virtualbox) I get the same exact crash every single time

Grab latest version of server files then start it up, I get same results on 4 different machines

## Additional Information

https://pastebin.com/8aW0UQbA

I know how to solve this issue, removing LibrarianLib and NaturalPledge from the mods folder and the server starts like it should.

**Comment by mcdodge34** [comment]
Just reporting that its not fixed either in 1.4.4, I'm not sure why some people can launch this and many are like me, on my side on 3 different PC this server doesn't start and its the exact same error each time, until I remove LibrarianLib and NaturalPledge, the server refuses to start... Can't be OS related, cause here I have my main server running windows 7 64 bits pro, 2nd server is running Windows 8.1 Pro 64 bits and my main rig is running Windows 10 Pro 64 bits. All of them have the latest java installed.

**Comment by Jo-Mamma75** [comment]
Do me a favor @mcdodge34 , try disabling FoamFix on your server and see what happens and then report back please.

**Comment by mcdodge34** [comment]
Same exact error, we are troubleshooting it right now, even with just ForgeLin and LibrarianLib in the mods folder, we get the same exact crash report, updating forge didn't solve the problem either. Updating ForgeLin to the 1.5.0 version either.
