### ISSUE TITLE
Thermal dynamics servo dup

### ISSUE THREAD

**Issue by ImTheStigHonest** [scalda/FoolCraft#548]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Thermal Dynamics servos and filters duplicate after placing on pipe

## Reproduce Steps
Place servo on pipe re open inventory and the original number of servos is listed
Same issue with filter

**Comment by scalda** [comment]
What version of the pack are you using?

**Comment by ImTheStigHonest** [comment]
it was in 1.4.3

**Comment by scalda** [comment]
ok can you try 1.4.4 please and report back, please

**Comment by Jo-Mamma75** [comment]
@ImTheStigHonest 
What is the status of your issue?  If it is not resolved, please report back.  Otherwise we will close this issue as resolved.

**Comment by ImTheStigHonest** [comment]
resolved thanks
