### ISSUE TITLE
1.4.3 Download Not Passing Viescraft

### ISSUE THREAD

**Issue by KuraidoGurei** [scalda/FoolCraft#549]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
My friend is trying to install Foolcraft 1.4.3 via the Twitch/Curse Launcher. It starts downloading the mods but fails at 14 saying "Timed Out Attempting to Download Viescraft."

## Reproduce Steps
1) Install Curse Launcher
2) Launch Installing Process
3) Crash at Mod 14 (Viescraft)
 We've reinstalled the launcher and removed the created "Foolcraft" folder in the instances.

**Comment by scalda** [comment]
try 1.4.4, please?

**Comment by KuraidoGurei** [comment]
Still doesn't work. I talked to Jo and he said it was a possible issue with Curse/Twitch.

**Comment by Jo-Mamma75** [comment]
Yeah. Best thing to try is to completely remove the instance in Curse/Twitch and reinstall it.  I would suggest backing up your JourneyMap data folder and the saves folder first.  Just out of curiosity, have you checked your free hard disk space?  I know it's a simple question but you would be surprised how easily that could be overlooked.

**Comment by Jo-Mamma75** [comment]
@KuraidoGurei 
Did installing a completely new instance of the pack via Curse/Twitch resolve your issue?

**Comment by KuraidoGurei** [comment]
It did not. I believe it's an issue with their Internet not being strong enough. But weirdly it was installed before, and then trying to reinstall it again, it wouldn't work.

**Comment by Wowzabunny** [comment]
Hi I am getting the exact same error has you, I have tried reinstalling the Twitch App as well with no success. It is really frustrating.
