### ISSUE TITLE
People still having problem with natural pledge and it's library

### ISSUE THREAD

**Issue by scalda** [scalda/FoolCraft#550]
The reason that they are still in the pack is that we can't replicate the issue, we have 7 active foolcraft servers with a total of 200 players ish and not once had this problem everyone is referring to I have tested the pack on all os available and still no issues, the problems are player ends not the pack, as we can't replicate the issue in any shape or form.

We need more information if people wants this fixed but since we as devs can't find the issue or have the issue we can't actively say we can fix it. we can't just remove it from the pack as to us as it's not causing issues. 

Even all the fools can run with those 2 mods in the pack with no issues, and they don't exactly have potatoes of computers.

So please try and help us to sort this so everyone can enjoy the pack.
please provide as much info about your systems and setups as much as you can.

regards

scalda

**Comment by mcdodge34** [comment]
Ok, you want more infos, here's my 3 PC specs : 

Main Rig : 

MB : Asus Z97A
CPU : Intel I7 4790K 4.0GHZ
RAM : 16GB DDR3 (2x8GB)
GPU : Gigabyte GTX 770 OC WF3 4GB edition
SSD : Samsung 840 EVO 512GB
OS : Windows 10 anniversary update Pro 64 bits
Java 8 update 131 64 bits edition (latest available)

2nd server : 
MB : ASUS P8Z77-V LX
CPU : Intel I5 3550 3,3GHZ
RAM : 16GB DDR3 (4x4GB)
SSD : Sandisk cheap 120GB
GPU : Gigabyte GTX 770 OC WF3 4GB
OS : Windows 8.1 Pro 64 bits latest update done yesterday
Java : is same 8u131 64 bits.

3rd server : 
MB : P5Q SE Plus
CPU : Intel Q9400 2.6GHZ
RAM : 8GB (4x 2GB)
SSD : Samsung 840 EVO 240GB
GPU : PNY GeForce 9600GT 512MB
OS : Windows 7 Pro 64 bits latest updates
Java is same for all Java 8u131 64 bits

**Comment by Jo-Mamma75** [comment]
Hardware specs look pretty good to me.  I'm a little behind on this one so if you would @mcdodge34 , please post a list of everything that you've done so far and the results.  Pastebin crash logs, etc.  I'd like to see if I can offer any assistance.

**Comment by Jo-Mamma75** [comment]
Do me a favor @mcdodge34 , try disabling FoamFix on your server and see what happens and then report back please.

**Comment by mcdodge34** [comment]
Sadly same result, removed foamfix from the mods folder and get the exact same crash, or maybe its different and I didn't notice so here it is : https://pastebin.com/hKsqruLc

What I don't understand is it does exactly the same on all my PC...

**Comment by iamshift** [comment]
i'm having the same issue in my local server. 
the problem is not the pack for sure, it's LibrarianLib. 
I tried to run a server with only LibrarianLib and ForgeLin (a requirement for the Lib) and the server crash with the same error.
https://pastebin.com/XCv2jV5r

**Comment by mcdodge34** [comment]
I just did the same, brand new mods folder with only forgelin and librarianlib, it crash, here's the crash report : https://pastebin.com/zsEBLhTs

**Comment by scalda** [comment]
ok this is gonna be odd but can you guys update forge and try that for us?

**Comment by mcdodge34** [comment]
Same crash with latest forge and only LibrarianLib and ForgeLin in the mods folder, here's the crash report

https://pastebin.com/zeeXBNw4

**Comment by iamshift** [comment]
just tested changing forge versions up and down as well as both mods.
or crash due to incompatibility issues or gives the same error as before.

all tests were done with Java 8 in Windows 8.1 Pro.

**Comment by mcdodge34** [comment]
Its very mysterious cause I can launch the modpack fine, its just the server that refuses to start with theses mods.

**Comment by iamshift** [comment]
just for the purpose of testing.
I ran a MC 1.11.2 server with Forge 13.20.0.2315, Forgelin 1.4.2 and LibrarianLib 3.1.4.2.
It worked first try.

**Comment by Jo-Mamma75** [comment]
https://github.com/TeamWizardry/LibrarianLib/issues/36

**Comment by janf3** [comment]
Are you guys using the server files download or creating/updating the server using the client download?

@scalda Do you have the splash screen enabled or disabled on the server, removed any client-side-only mods maybe?

**Comment by scalda** [comment]
I run the pack as is no removal of mods or config changes on server and client across all servers i handle

**Comment by mcdodge34** [comment]
Just to report here, same issue is still there on 1.4.5, for now I gave up, I create my own pack with the configs and scripts of foolcraft, some I had to modify since I remove NaturalPledge and LibrarianLib and I added several mods to my pack (could name them here but that would be too long), modified some configs and I enjoy my adventure with several mods added to the pack, this pack is awesome, just need someone to find why we have this problem is beyond my understanding also. I even created a brand new server using the Forge download, added both mods (LibrarianLib and ForgeLin which is needed), and I get the same crash, so I know now its not something done by the pack at all)

**Comment by scalda** [comment]
Thanks for letting us know

**Comment by miksbricks** [comment]
What MC build are you running on the server? Not saying it's the cause but it seems like I first saw this issue being talked about right around the same time 1.12 and an updated launcher came out.

**Comment by mcdodge34** [comment]
Its still 1.10.2, most of the mods in Foolcraft wouldn't work in 1.11.2 or 1.12 some are done, but most aren't there yet.

**Comment by Jo-Mamma75** [comment]
I'm still at a loss as to why you (and a few others) have had so many issues with these mods but the vast majority have not.

**Comment by mcdodge34** [comment]
One thing I want to make sure, is everyone using latest version of java 8u131 64 bits edition, I know the default launcher on Twitch still use the old java 8u25

**Comment by iamshift** [comment]
After many trial and error I was able to start the server with all the mods. 
I've changed Forgelin to 1.0.4 and LibrarianLib to 1.7.1.
If anyone else with the same problem could try this solution that would be great.

**Comment by mcdodge34** [comment]
It goes much further after replacing the files with Forgelin 1.0.4 and LibrarianLib 1.7.1 I go much further, up to the world generation, then it crash with this very different crash report so maybe someone can tell me what is wrong on this one : https://pastebin.com/LkLyYShF

**Comment by mcdodge34** [comment]
Trying different things, I got the 1.4.5 server started fine with ForgeLin 1.0.5 and LibrarianLib 1.8, booting up Foolcraft instance with same files to see if it will work correctly

**Comment by iamshift** [comment]
@mcdodge34 tried that and worked ok!
@scalda if you could try it too. to see if it doesn't break in a system where it's currently working fine.
Forgelin 1.0.5
LibrarianLib 1.8
everything else from 1.4.5 update

**Comment by janf3** [comment]
Forgelin-1.4.2 does support 1.10.2
https://minecraft.curseforge.com/projects/shadowfacts-forgelin/files/2413458

I just installed a Foolcraft 1.4.5 server and copied my SSP world into it. Running just fine (apart from no flight).

Foolcraft 1.4.5
Windows 10 Pro (up to date)
Java 1.8.0_131
server and client (MultiMC) running on the same system

**Comment by mcdodge34** [comment]
janf3, I'm clueless, I'm pretty sure its not related to ForgeLin version but something in LibrarianLib 1.10.1 that makes it not work on some PC while it works on others, and you can start it fine on yours, I have exactly the same OS and java version, The thing is I can start the Foolcraft modpack and play it fine on all my PC, its just the server that crash like an idiot with that stupid crash report, now that I downgraded to ForgeLin 1.0.5 and LibrarianLib 1.8, the server starts normally and I have 0 problems to report, on all my PC it works,

**Comment by janf3** [comment]
Weird issue indeed. I'm shooting in the dark here but any old left-over Java versions on the systems? Any Antivirus (apart from Defender) which may be causing issues?

**Comment by mcdodge34** [comment]
Nope, I cleanup and uninstall any previous java versions before installing the new one. I don't have any anti-virus apart from Windows Defender, but I'm very safe against virus, I use a crap ton of plugins in Firefox and Google Chrome, I'm also behind a VPN that prevents I'll say at least 70% of attacks or virus and such,  I'm paranoid by the virus and rancomwares since I'm a PC tech support, I see a crap ton of PC that needs to be cleaned up every week that I'm using some soapbox and virtual machines when I'm not 100% sure where I'm browsing.
