### ISSUE TITLE
1.4.4 Reboot Loop

### ISSUE THREAD

**Issue by janagyjr** [scalda/FoolCraft#551]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I updated the server from 1.3.3 to 1.4.4 to take advantage of not having More Player Models. Only changes I made to default setup are:
1) Enabled awakened drac chickens (keeping it consistent on the server I help manage)
2) I copied the veinminer CFG from 1.3.3 to 1.4.4

## Reproduce Steps
1) set up to use existing world for upgrade
2) keep configs as mentioned above
3) type /fml confirm when appropriate
4) watch server go into reboot loop

## Additional Information
Full crash log:
https://pastebin.com/SsrXyW4S

**Comment by janagyjr** [comment]
Ticking tile entity, Jo helped solve it. Please ignore.

**Comment by Jo-Mamma75** [comment]
But @janagyjr said in Discord that they keep having this issue happening over and over again with chickens in nesting pens even after the initial "fix".  This may be something we need to investigate a little just to make sure it's not an isolated incident.

**Comment by scalda** [comment]
Any chance you can send me a copy of your world that had the issues as i have tried 2 active worlds so far with 1.4.4 and all is fine with hatchery

**Comment by janagyjr** [comment]
Yes, I will stop the world and give you a download of it. It's an update from 1.3.3 straight to 1.4.4. We've killed all the chickens on the server (which seemed to incrementally decrease the sever rubber banding, too but it's still pretty bad), but haven't had a chance to revert the forge cfg back to see if that solved the issue or not (which it may not have given the amount of rubberbanding we have w/ the forge.cfg settings set to remove the entities throwing the errors).

**Comment by janagyjr** [comment]
I'll also include my journey map data file so you have waypoints to find everyone's base.

**Comment by janagyjr** [comment]
Please note we have left awakened draconium chickens enabled.

https://www.dropbox.com/s/nkes8vc8aiv356f/MP%20World%20Data%20Files.rar?dl=0 (1.9GB)

**Comment by scalda** [comment]
Are you using sponge?

**Comment by janagyjr** [comment]
No, until recently could not find a sponge that worked with the forge version FC was using.

**Comment by janagyjr** [comment]
Then again, I was looking for sponge for a different reason than lag control.
