### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by bl3wis** [scalda/FoolCraft#552]
## bl3wis

Missing Textures
I am a noob, and did not know where else to go.

- [ x] I am running the latest version of FoolCraft
- [x ] I am running FoolCraft via Curse/Twitch Launcher
- [ x] I can reproduce this issue consistently
     - [ x] In single player
     - [ ] In multiplayer
- [ x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x] I am requesting help with installing or running the pack

I am running FoolCraft on a Mac.   I missing the textures for various mods since 1.3.3.  I thought this was bug on your side of things, but I have not seen anyone talk about it.

The mods missing textures include:
 Agricraft, Baubles, Extra Utilities, Mine Craft Comes Alive, Modern Warfare, Pam's HarvestCraft, RFTools, Thermal Foundation, Tiny Progressions, Torch Master, Useful Nullifiers, Waystones, Weapon Case Loot, Woot, Xp-Plus.

The blocks either have:
1)A purple and black square texture.
2) Random letters written on it.
3) Nothing at all.

I have uninstalled and reinstalled FoolCraft several times now and nothing has seemed to work. If it is something that I need to do on my end of things let me know.  If so, be gentle to with me.  It's my first time playing a mod.

Thanks

I don't know how to reproduce the issue.  Sorry.

![screen shot 2017-06-15 at 9 27 38 pm](https://user-images.githubusercontent.com/29471116/27207934-6d731046-5210-11e7-82bb-97ff5b78e0db.png)

![screen shot 2017-06-15 at 9 28 58 pm](https://user-images.githubusercontent.com/29471116/27207944-7c5c33f8-5210-11e7-9761-778d699e6efd.png)

**Comment by scalda** [comment]
My suggestion is to reinstall the pack

**Comment by bl3wis** [comment]
I have done this multiple times and the same problem occurs.   It is like the textures are not even there. Or as if the game is instructed to look at the wrong files to use as the textures.

**Comment by DwellerBenthos** [comment]
It almost looks like your video card isn't loading the textures properly, and something is causing it to repeat textures over and over. I did have a similar issue, on PC, but when I hovered the mouse over the items, the correct texture showed up, but went back to the wrong one when I moved the mouse away. It only happened once and went away when I restarted the game. Does the same thing happen when you have the item in your inventory, or hold it in your hand, or place it in the world? It might be an issue with JEI on your system, or again, video memory. I don't know enough about the Mac system to say one way or the other about what video system they use. I'd start with updating drivers.

**Comment by bl3wis** [comment]
The same thing happens when the item is placed in the world.    It is also not consistent.  I can restart a world and each time the item is different.  Once, I actual had a few blocks look like the "Matrix"   which was a cool effect, but it never happened again.

As for "updating drivers", I have no clue what that means. Sorry, I am not much when it comes to computer knowledge.

**Comment by bl3wis** [comment]
Here is what things look like when place in the world.   Also the same problem occurs if I try create the item in survival.

![2017-06-17_12 29 55](https://user-images.githubusercontent.com/29471116/27254513-cf7587fe-5357-11e7-9802-cbdfd3cbad50.png)
![2017-06-17_12 31 32](https://user-images.githubusercontent.com/29471116/27254518-e803326c-5357-11e7-8ebf-2e25953ed83c.png)

**Comment by DwellerBenthos** [comment]
OK, doing some research on the Mac system, apparently you can't update the video driver (that's the software that controls the video display) unless you update the operating system. I won't go into my thoughts on that here, but really? Anyway, look at this page

http://www.cgl.ucsf.edu/chimera/graphics/updatemac.html

And you can tell what video system you have. I'm guessing you have an older Mac with a video card with not that much memory and it just can't deal with the huge amount of textures in the mod pack. So it loads what it can, and just displays garbage for the rest. Try posting on the Minecraft forums, you might get more help there from someone who knows more about Macs than I do.

OK, looking further into it, you can get a video driver update sometimes by running a system update, see this:

https://support.runescape.com/hc/en-gb/articles/207164875-Updating-graphics-drivers-Mac

But it still might not work if your actual video memory is too low.

**Comment by bl3wis** [comment]
After you spoke to me about drivers last time, I did the some research as well.  I basically came up with the same conclusion that you did.  However, my computer is only a 1.5 years old and I keep the Operating System up to date, so I did not think my computer was out dated.

Anyway, I did some more digging and found this on GitHub from 2015.

https://github.com/MinecraftForge/MinecraftForge/issues/1829

Long story short, I saw another Mac user with the same problem. They discovered that if they reloaded the resources in game (F3 + 3)  it would temporary fix the issue.   However, when they restarted the game they would have to reload the texture each time.   

I tried this, and worked.   (I wish I knew that was a thing several months ago.) All the missing textures were fixed.  And just as the other user describe, when I restart the game I have to reload the resources.

However, I was also reading that they were trying to find a permanent solution.  In the discussion, there is a bunch of technical information that I do not understand.   My hope is now that one of you may and simplify for me.   (Again sorry, for my NOOBOSICITY).   

If not, that is ok.

**Comment by DwellerBenthos** [comment]
OK, I read that thread, and it's a known issue with the Mac OS and video drivers and the way Minecraft and Forge handles textures. I'll boil it down for you. Go to the folder you have Foolcraft installed to. Go to the config folder, look for a file called "splash.properties", it may be hidden. Open it in a text editor and find the  entry "enabled=true" and change it to "enabled=false", save the file and run Foolcraft, that should fix it. I think, though, the next time you update Foolcraft, that file will be replaced with the default one and you'll have to go back and change it again.

**Comment by bl3wis** [comment]
I found the file, but I cannot open it.   SMH

I am trying to find what I can open it with.

**Comment by bl3wis** [comment]
I am a derp.  I did not read your sentence "Open it in a text editor".   

Anyway, I did that and it has fixed the problem.   However, it seem to make the initial start up of the game slower than normal.      It also did not show the progression bar as Forge puts the pack together.  So I may actually put the entry back to "enabled=true" to get progression bar back and speed the initial start up back to normal.  It really is not a problem to "F3+T" it in game.   Ultimately, I think the solution to this problem is personal preference.

Dweller, I hope you do not mind by I am going to copy all the instructions to fix this problem in the next comment.   If there are others like me out there, maybe this will help them.

Dweller, you're awesome.  Thanks

**Comment by bl3wis** [comment]
Hey all Mac Users!   If you are having problems with seeing textures on your Mac while playing FoolCraft, these two solutions may help you.  One solution is a temporary fix while the other is a more permanent fix.  Thanks to DwellerBenthos for all the help.

1)Temporary Solution.

After starting your world, press "fn + F3 +T".   This will reload the resource packs in your game and should fix your textures.   It may lag your game for a few seconds but it should not take longer than a minute.  (At least on my computer).   You should not have anymore problems why you are playing.  However, when you close out and reload you are going to have to "fn + F3 + T" once again.

(NOTE to PC Users: That is not a typo, for MACs we have to use "fn" to get to F3 mode.)

2) Slightly more Permanent Solution

- Go to the folder you have Foolcraft installed to. 

- Go to the config folder, look for a file called "splash.properties", it may be hidden. 

- Open it in a text editor and find the entry "enabled=true" and change it to "enabled=false".

- Save the file and run Foolcraft, that should "hopefully" fix it. 

However, it is possible the next time you update Foolcraft, that file will be replaced with the default one and you'll have to go back and change it again.  Furthermore,  it seem to make the initial start up of the game slower than normal. It also did not show the progression bar as Forge puts the pack together. Now, this may not be the case with your game, but it was for mine.   

Hopefully, this helps anyone who may be having the same issue.

Thanks again DwellerBenthos!
