### ISSUE TITLE
Saltpeter Seeds Missing in Agricraft

### ISSUE THREAD

**Issue by ChromeMystic** [scalda/FoolCraft#553]
## SUGGESTION/HELP
- [x ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Saltpeter Seeds aren't added to agricraft, i fixed it by adding the attached json to the configs.

## Additional Information

> {
>   "path": "resource/plants/saltpeter_plant.json",
>   "enabled": true,
>   "id": "mysticalsaltpeter_crop",
>   "plant_name": "saltpeter Essence",
>   "seed_name": "saltpeter Seeds",
>   "seed_items": [
>     {
>       "item": "mysticalagriculture:saltpeter_seeds",
>       "meta": 0,
>       "tags": "",
>       "ignoreMeta": false,
>       "ignoreTags": [
>         "*"
>       ],
>       "useOreDict": false
>     }
>   ],
>   "description": {
>     "translations": {},
>     "default": "saltpeter Seeds."
>   },
>   "growth_chance": 0.8,
>   "growth_bonus": 0.025,
>   "bonemeal": true,
>   "tier": 3,
>   "weedable": false,
>   "aggressive": false,
>   "spread_chance": 0.1,
>   "spawn_chance": 0.0,
>   "grass_drop_chance": 0.0,
>   "products": {
>     "products": [
>       {
>         "min": 1,
>         "max": 3,
>         "chance": 0.95,
>         "required": true,
>         "item": "mysticalagriculture:saltpeter_essence",
>         "meta": 0,
>         "tags": "",
>         "ignoreMeta": false,
>         "ignoreTags": [],
>         "useOreDict": false
>       }
>     ]
>   },
>   "requirement": {
>     "min_light": 10,
>     "max_light": 16,
>     "soils": [
>       "farmland_soil"
>     ],
>     "bases": [],
>     "nearby": {}
>   },
>   "texture": {
>     "render_type": "hash",
>     "seed_texture": "mysticalagriculture:items/saltpeter_seeds",
>     "plant_textures": [
>       "mysticalagriculture:blocks/crop0",
>       "mysticalagriculture:blocks/crop0",
>       "mysticalagriculture:blocks/crop1",
>       "mysticalagriculture:blocks/crop1",
>       "mysticalagriculture:blocks/crop2",
>       "mysticalagriculture:blocks/crop3",
>       "mysticalagriculture:blocks/crop4",
>       "mysticalagriculture:blocks/saltpeter_crop"
>     ]
>   }
> }

**Comment by scalda** [comment]
thanks this is added for the next version
