### ISSUE TITLE
Shearing the top part of a large fern doesn't drop anything

### ISSUE THREAD

**Issue by Jupisoft111** [scalda/FoolCraft#554]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Shearing the top part of a large fern doesn't drop anything. The lower part does.

## Reproduce Steps
Grow a large fern with bone meal or find one and use the shears on the lower and upper part to see the difference.

## Additional Information
In Foolcraft 1.4.4 and previous versions. It's not a big bug, but it gets annoying when you work with ferns. Thanks in advance for your attention.

**Comment by Jo-Mamma75** [comment]
Vanilla Minecraft doesn't drop the fern if you shear the top half of a large fern.  Not really seeing how this is a "bug".
