### ISSUE TITLE
Good Ol' Currency Config Change

### ISSUE THREAD

**Issue by BeardlessBrady** [scalda/FoolCraft#555]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Additional Information
If you delete the current config and allow it to reload you should set the 'item textures' config to 2, for the foolcraft variant

**Comment by CriticalMole** [comment]
That is totally awesome!

**Comment by scalda** [comment]
been integrated with 1.4.5. thanks for the suggestion
