### ISSUE TITLE
FoolCraft server wont work?

### ISSUE THREAD

**Issue by yosi11212** [scalda/FoolCraft#556]
Im trying to set up a server it wont work help!

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When i open Start i get this error message: (Down in additional information)

## Reproduce Steps
1 open Start

## Additional Information
![image](https://user-images.githubusercontent.com/25132933/27284161-3df13742-5500-11e7-9656-08ba1db48ce4.png)

**Comment by ajdjyt** [comment]
could you use pastebin to send the log?

**Comment by scalda** [comment]
Can you try running this from your main c drive and run as an administrator?

**Comment by Jo-Mamma75** [comment]
A little more information would be helpful to have.
1. Are you running this as an Administrator?
2. Is the F:\ drive an internal or external drive? Does it have sufficient free space?
3. What version of Windows are you running?
4. What version of Java is currently installed?
5. What troubleshooting steps, if any, have you attempted thus far?
6. Is there anything else specific to your environment that you think would be helpful to us?

**Comment by yosi11212** [comment]
1.no
2.F:\ is an external drive im using 400 gb from it and it has 3.25 tb
3.windows 10
4.8
5.redownloading
6.Nope.

**Comment by Jo-Mamma75** [comment]
Thanks for providing the info.  Can you try launching the server and running it with administrative rights just to see if that makes any difference?  I'm just curious.  Kind of difficult to troubleshoot with only that one screenshot and a little bit of info.
