### ISSUE TITLE
1.4.5 all flight items not working

### ISSUE THREAD

**Issue by scalda** [scalda/FoolCraft#557]
need to look into this as not sure what would of changed

**Comment by chland** [comment]
Over at Reddit, MyNamesNotDave posted that Avaritia causes it. Here is the link to their issue: https://github.com/Morpheus1101/Avaritia/issues/35

**Comment by Jo-Mamma75** [comment]
Yeah, looks like he's working on it.  Have asked for an ETA so we can plan accordingly for our next update.

**Comment by scalda** [comment]
This has now been fixed in the new version 1.4.6. thanks for reporting the issue
