### ISSUE TITLE
Fool Craft Exploration Server Freeze/ suggestion

### ISSUE THREAD

**Issue by violetkitty87** [scalda/FoolCraft#559]
Fool Craft 1.4.5 Minecraft server freeze

- [x ] I am running the latest version of FoolCraft
- [ x] I am running FoolCraft via Curse/Twitch Launcher
- [x ] I can reproduce this issue consistently
     - [ ] In single player
     - [x ] In multiplayer
- [x ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [x ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

Certain areas that I explore and my friends explore makes the server freeze up with no crash. It can be replicated by going into those areas. When the server freezes i have to force close the console cause the commands will not work.

the suggestion is a mod that makes it so you can see what type of moo fluid cows they are i dont remember the name but its out there

1. spawn in
2. go to area
3. freeze up
4. time out

my report is too long for pastebin

[fml-server-latest.zip](https://github.com/scalda/FoolCraft/files/1089362/fml-server-latest.zip)

i got a crash after this report 
 
[crash-2017-06-20_16.13.54-server.txt](https://github.com/scalda/FoolCraft/files/1089575/crash-2017-06-20_16.13.54-server.txt)

**Comment by fabri2000779** [comment]
you got the same crash than me, this is a update problem, Scalda already know it so he is working on it right now

**Comment by scalda** [comment]
yeah this is a recurrent complex issue they have an open issue on their gihub

**Comment by scalda** [comment]
I will be checking out a new version that is getting pushed over night in the morning and hoping to have a new release tomorrow

**Comment by violetkitty87** [comment]
when is this update our server keeps crashing cause of this problem

**Comment by fabri2000779** [comment]
@violetkitty87 they are waiting for a mod to be updated, it going to take couple of days

**Comment by violetkitty87** [comment]
i also noticed a problem with pams only the windy garden is giving stuff all of the others dont drop anything

**Comment by scalda** [comment]
This is now resolved in 1.4.6. please update and test
