### ISSUE TITLE
lagy

### ISSUE THREAD

**Issue by bjelven217** [scalda/FoolCraft#56]
i start a foolcraft World and first its take long time to lanch and after that dose not the chunks load in so good so when i do a thing dose its freeze for some seks and thigs is like moving ore open inventory

**Comment by vvolfe** [comment]
What do you have your memory set to? It needs to be 6gb or higher.  Also make sure you are using correct version of java.  I had similar issue in even vanilla mc and changed from java 8 32 to 64 bit and that fixed it

**Comment by pkpotato** [comment]
https://github.com/scalda/FoolCraft/issues/58
