### ISSUE TITLE
1.4.5 Unable to fly w/ Angel Ring

### ISSUE THREAD

**Issue by JTKillien** [scalda/FoolCraft#562]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description After updating my single player world form 1.4.4 to 1.4.5 my Angel Ring no longer allows me to fly. I checked my Grid Power, which shows its at ~130/1000 which is about right. I broke the dragon egg mills and replaced them with dragon eggs on top but still was able to fly. I tried building a new Angel Ring that was not converted to a bauble but could not fly either. Cheats are enabled and I am the only player on the world (single player). I Started a testing world as well still unable to fly without creative mode enabled. 
EDIT: After additional testing in testing world. All forms of creative flight appear to be disabled. I grated my self a cloud pet with nether quartz. Added the Supremium Armor (full set) and even enabled an RF Tools Environmental Controller with Flight Module.

**Comment by Jo-Mamma75** [comment]
https://github.com/Morpheus1101/Avaritia/issues/35
It's an issue with the mod and has been resolved by the mod developer.  The updated version will be included in our next release.

**Comment by JTKillien** [comment]
Thanks for the info @Jo-Mamma75

**Comment by scalda** [comment]
This is now resolved in 1.4.6. please update and test
