### ISSUE TITLE
extrautils2 fool´s drum doesn't work as intended

### ISSUE THREAD

**Issue by PSILONCRAFT** [scalda/FoolCraft#563]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x] I am requesting help with installing or running the pack

the OP fools creative drum crafted in the dire crafting table can't be filled with liquid when in gamemode 0. works fine in gamemode 1

**Comment by scalda** [comment]
Ok looks like the recipe may need to be removed then as you are correct it can't be used in survival

**Comment by PSILONCRAFT** [comment]
Or make a resipi that combined the stum and a bucket with liquid to give a creative drum with that liquid

**Comment by PSILONCRAFT** [comment]
I ment drum

**Comment by CriticalMole** [comment]
I am working on something to replace the as is recipe, exactly what I do not know yet
