### ISSUE TITLE
Minor issues in 1.4.6 (Recurrent Complex, Custom Main Menu)

### ISSUE THREAD

**Issue by chland** [scalda/FoolCraft#565]
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

The current beta has some minor issues that could/should be fixed before 1.4.7 :

- Custom Main Menu: **no issue in this version** of the mod, but if you update, rename the "texts"-category to "labels" (it throws a ton of error-messages regarding this change)
- Recurrent Complex: structures are missing a row of blocks in the middle - https://github.com/Ivorforce/RecurrentComplex/issues/222 (mod-update needed)
- IDK if this can cause any problems but the manifest.json-file contains a wrong instance-name: "FoolCraft (1)" instead of "FoolCraft"

**Comment by scalda** [comment]
Hi,

custom main menu hasn't been updated so not sure why you are reporting that
recurrent complex is the latest version that was released after that last fix
and not that we are aware of and it's like that as that is the name of the dev instance in my curse for the pack

regards

scalda

**Comment by chland** [comment]
I'm reporting the CMM-issue because I get multiple

> [Client thread/INFO]: [lumien.custommainmenu.configuration.GuiConfig:loadLabels:292]: java.lang.RuntimeException: Please rename the "texts" category in your menu json file to "labels", next version "texts" will no longer work

messages in the error-log. Like I mentioned before: personally, I like it when modpacks make an effort in having as few error-messages in the error-log as possible because it makes it easier to find issues.

RC 1.4.1 still has this bug, thats why i'm mentioning that you should update RC if there is a new version before 1.4.7 is released.

![rc_bug](https://user-images.githubusercontent.com/472894/27531363-92192b0c-5a5c-11e7-88db-eafa96f41565.jpg)

**Comment by Ivorforce** [comment]
The chunk cut issue (Ivorforce/RecurrentComplex#222) has been resolved in 1.4.2, which has been released just now :)

**Comment by scalda** [comment]
sorted thanks
