### ISSUE TITLE
LootBags in 1.4.6

### ISSUE THREAD

**Issue by chland** [scalda/FoolCraft#566]
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

The Lootbags-mod throws quite a few errors because some item-names seem to be wrong.

The following items seem to not exist at all:

- blockarmor:dark_oak_stone_* (helmet, chestplate, etc.)
- blockarmor:brick_infernal_0_*
- avaritiaadditions:ultimate_stew

And the following items seem to have wrong names:

- harvestcraft:carmelappleitem -> harvestcraft:caramelappleitem
- blockarmor:brick_helmet -> blockarmor:brick_block_helmet 
- blockarmor:brick_chestplate -> blockarmor:brick_block_chestplate
- blockarmor:brick_leggings -> blockarmor:brick_block_leggings
- blockarmor:brick_boots -> blockarmor:brick_block_boots
- malisisdoors:saloon_door -> malisisdoors:saloon
- mw:HK MP5 -> mw:HKMP5
- tp:DiamondApple -> tp:diamond_apple

**Comment by CriticalMole** [comment]
Thanks for that, those will be fixed in 1.5 among other tweaks I am making to keep the bags fresh
