### ISSUE TITLE
angel ring not working

### ISSUE THREAD

**Issue by dragonianwolf** [scalda/FoolCraft#567]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Additional Information
I have made new water mills from extra utilities2 made 2 new angel rings but still no flight
the angel rings refuse to work all the other stuff using GP is working fine only the angel rings don't work
is there an error in the mod or dit I set up something wrong?
![angelringerror](https://user-images.githubusercontent.com/29719366/27566296-ad5400b2-5ae4-11e7-88af-8849a2e4f115.png)

**Comment by DwellerBenthos** [comment]
This is fixed in version 1.4.6 of the pack.

**Comment by FreeTheGamer** [comment]
Could you explain what the fix was? I am having the same problem in a different pack.

**Comment by DwellerBenthos** [comment]
According to this post, it was Avaritia:

https://www.reddit.com/r/Foolcraft/comments/6ib88j/flying_disabled/

Upgrade to the most recent version. It was also causing an issue with step assist on the Ender IO Dark Boots.
