### ISSUE TITLE
Empowered Dark Boots no longer allow walking up one block heights

### ISSUE THREAD

**Issue by DwellerBenthos** [scalda/FoolCraft#568]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I have a set of Dark Steel boots from Ender IO. They used to give the ability to walk up one block heights without jumping. They no longer do this, since either version 1.4..4 or 1.4.5 and it still does not work in 1.4.6. I had thought the same issue that blocked Angel Ring flight might also be causing this, but it still happens in 1.4.6 where Angel Ring flight now works again.

## Reproduce Steps
Create Dark Steel Boots, try to walk up single block, they should allow you to step up a single block height without jumping.

**Comment by scalda** [comment]
This needs reporting to enderio [github](https://github.com/SleepyTrousers/EnderIO/issues)

**Comment by DwellerBenthos** [comment]
Issue with Avaritia, reporting to both.

**Comment by scalda** [comment]
Looks like it has been fixed on their end will update mod when we are ready
with a new version of the pack

**Comment by DwellerBenthos** [comment]
Yes I see that Avaritia is updated to Avaritia-1.10.2-2.2.7-universal and that works.

**Comment by scalda** [comment]
i have just released 1.4.7 that fixes this issue
