### ISSUE TITLE
Foolcraft Crashing while placing architecture blocks

### ISSUE THREAD

**Issue by RezziPie** [scalda/FoolCraft#570]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x ] I am requesting help with installing or running the pack

## Issue Description
The game has been running okay for months.  I am trying to build with Architecture blocks.  I place 2-3 blocks and I get kicked out.  This happens over and over.  I reinstalled Foolcraft and even reinstalled Java.

## Reproduce Steps
I place 2-3 architecture blocks and kicked kicked.

## Additional Information
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.7.241-universal.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.6.98-universal.jar)
  IvToolkit (IvToolkit-1.3.2.1-1.10.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.207-universal.jar)
  PlusTiC (plustic-4.3.0.2.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  ForgelinPlugin (Forgelin-1.4.1.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.9.15.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156-universal.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 6/27/17 12:41 PM
Description: Unexpected error

java.lang.ClassCastException: mod.chiselsandbits.chiseledblock.TileEntityBlockChiseled cannot be cast to gcewing.architecture.ShapeTE
	at gcewing.architecture.ShapeBlock.getLocalBounds(ShapeBlock.java:152)
	at gcewing.architecture.ShapeBlock.func_185496_a(ShapeBlock.java:109)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:443)
	at net.minecraft.block.Block.func_180646_a(Block.java:375)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:433)
	at net.minecraft.world.World.func_175716_a(World.java:3161)
	at net.minecraft.item.ItemBlock.func_179222_a(ItemBlock.java:125)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:418)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at gcewing.architecture.ShapeBlock.getLocalBounds(ShapeBlock.java:152)
	at gcewing.architecture.ShapeBlock.func_185496_a(ShapeBlock.java:109)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:443)
	at net.minecraft.block.Block.func_180646_a(Block.java:375)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:433)
	at net.minecraft.world.World.func_175716_a(World.java:3161)
	at net.minecraft.item.ItemBlock.func_179222_a(ItemBlock.java:125)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:418)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['RezziPie'/160, l='MpServer', x=-2839.28, y=66.91, z=1517.63]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 07 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-247,64,-337), Chunk: (at 9,4,15 in -16,-22; contains blocks -256,0,-352 to -241,255,-337), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 10399461 game time, 11574660 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 136 total; [EntityBat['Bat'/11778, l='MpServer', x=-2813.38, y=19.03, z=1567.83], EntityBat['Bat'/11782, l='MpServer', x=-2815.12, y=20.48, z=1569.25], EntityBat['Bat'/12559, l='MpServer', x=-2877.75, y=14.22, z=1519.25], EntitySheep['Sheep'/272, l='MpServer', x=-2760.93, y=63.00, z=1460.07], EntitySheep['Sheep'/273, l='MpServer', x=-2760.71, y=63.00, z=1461.48], EntitySheep['Sheep'/290, l='MpServer', x=-2830.53, y=60.50, z=1525.45], EntityRooster['Rooster'/291, l='MpServer', x=-2921.09, y=62.71, z=1614.37], EntityRooster['Rooster'/295, l='MpServer', x=-2941.42, y=62.70, z=1623.08], EntitySkeleton['Skeleton'/5167, l='MpServer', x=-2907.50, y=21.00, z=1576.50], EntityBat['Bat'/11334, l='MpServer', x=-2832.63, y=19.21, z=1559.69], EntityFluidCow['Fluid Cow'/326, l='MpServer', x=-2790.46, y=53.00, z=1468.17], EntityBat['Bat'/11335, l='MpServer', x=-2836.39, y=19.28, z=1559.56], EntityFluidCow['Fluid Cow'/327, l='MpServer', x=-2786.46, y=53.00, z=1468.17], EntityLatchedRenderer['unknown'/2376, l='MpServer', x=-2839.28, y=66.91, z=1517.63], EntityChickensChicken['Nether Quartz Chicken'/328, l='MpServer', x=-2811.96, y=63.00, z=1475.64], EntityChickensChicken['Emerald Chicken'/329, l='MpServer', x=-2814.44, y=63.00, z=1478.32], EntityChickensChicken['Gold Chicken'/330, l='MpServer', x=-2812.50, y=63.00, z=1483.24], EntityChickensChicken['Gold Chicken'/331, l='MpServer', x=-2810.76, y=63.00, z=1475.76], EntityChickensChicken['Emerald Chicken'/332, l='MpServer', x=-2817.09, y=63.00, z=1479.07], EntityChickensChicken['Gold Chicken'/333, l='MpServer', x=-2809.49, y=49.00, z=1481.19], EntityChickensChicken['Gold Chicken'/334, l='MpServer', x=-2813.52, y=63.00, z=1472.03], EntityChickensChicken['Emerald Chicken'/335, l='MpServer', x=-2811.00, y=63.00, z=1476.39], EntityChickensChicken['Gold Chicken'/336, l='MpServer', x=-2813.33, y=63.00, z=1482.95], EntityChickensChicken['Coal Chicken'/337, l='MpServer', x=-2813.35, y=63.00, z=1479.73], EntityChickensChicken['Nether Quartz Chicken'/338, l='MpServer', x=-2811.87, y=63.00, z=1483.18], EntityChickensChicken['Gold Chicken'/339, l='MpServer', x=-2812.93, y=63.00, z=1473.10], EntityChickensChicken['Gold Chicken'/340, l='MpServer', x=-2815.37, y=63.00, z=1483.24], EntityChickensChicken['Iron Chicken'/341, l='MpServer', x=-2814.73, y=63.00, z=1472.91], EntityChickensChicken['Emerald Chicken'/342, l='MpServer', x=-2816.28, y=63.00, z=1481.82], EntityChickensChicken['Gold Chicken'/343, l='MpServer', x=-2814.47, y=63.00, z=1481.93], EntityChickensChicken['Gold Chicken'/344, l='MpServer', x=-2815.18, y=63.00, z=1473.05], EntityChickensChicken['Emerald Chicken'/345, l='MpServer', x=-2814.87, y=63.00, z=1478.08], EntityChickensChicken['Emerald Chicken'/346, l='MpServer', x=-2810.86, y=63.00, z=1472.20], EntityChickensChicken['Gold Chicken'/347, l='MpServer', x=-2812.12, y=63.00, z=1482.23], EntityChickensChicken['Gold Chicken'/348, l='MpServer', x=-2813.26, y=63.00, z=1473.59], EntityChickensChicken['Gold Chicken'/349, l='MpServer', x=-2810.79, y=63.00, z=1478.92], EntityChickensChicken['Nether Quartz Chicken'/350, l='MpServer', x=-2811.95, y=63.00, z=1478.13], EntityChickensChicken['Gold Chicken'/351, l='MpServer', x=-2811.95, y=63.00, z=1471.98], EntityChickensChicken['Gold Chicken'/352, l='MpServer', x=-2813.44, y=63.00, z=1473.03], EntityChickensChicken['Gold Chicken'/353, l='MpServer', x=-2812.72, y=63.00, z=1478.53], EntityChickensChicken['Gold Chicken'/354, l='MpServer', x=-2812.84, y=63.00, z=1475.98], EntityChickensChicken['Emerald Chicken'/355, l='MpServer', x=-2812.31, y=63.00, z=1478.67], EntityChickensChicken['Coal Chicken'/356, l='MpServer', x=-2814.89, y=63.00, z=1481.06], EntityChickensChicken['Gold Chicken'/357, l='MpServer', x=-2813.87, y=63.00, z=1474.56], EntityChickensChicken['Iron Chicken'/358, l='MpServer', x=-2815.40, y=63.00, z=1480.82], EntityChickensChicken['Coal Chicken'/359, l='MpServer', x=-2815.83, y=63.00, z=1483.11], EntityChickensChicken['Coal Chicken'/360, l='MpServer', x=-2811.38, y=63.00, z=1479.46], EntityBat['Bat'/12649, l='MpServer', x=-2873.86, y=31.32, z=1585.85], EntityChickensChicken['Coal Chicken'/361, l='MpServer', x=-2812.18, y=63.00, z=1475.15], EntityChickensChicken['Gold Chicken'/362, l='MpServer', x=-2816.91, y=63.00, z=1479.54], EntityChickensChicken['Emerald Chicken'/363, l='MpServer', x=-2811.46, y=63.00, z=1479.94], EntityChickensChicken['Gold Chicken'/364, l='MpServer', x=-2812.08, y=63.00, z=1473.27], EntityChickensChicken['Coal Chicken'/365, l='MpServer', x=-2817.10, y=63.00, z=1476.13], EntityChickensChicken['Iron Chicken'/366, l='MpServer', x=-2813.34, y=63.00, z=1481.25], EntityChickensChicken['Gold Chicken'/367, l='MpServer', x=-2811.40, y=63.00, z=1472.33], EntitySquid['Squid'/11889, l='MpServer', x=-2824.94, y=62.23, z=1561.45], EntityItem['item.item.goldNugget'/370, l='MpServer', x=-2809.88, y=49.00, z=1476.32], EntityChickensChicken['Nether Quartz Chicken'/371, l='MpServer', x=-2811.50, y=63.00, z=1476.65], EntityChickensChicken['Gold Chicken'/372, l='MpServer', x=-2816.44, y=63.00, z=1472.85], EntityChickensChicken['Gold Chicken'/373, l='MpServer', x=-2814.95, y=63.00, z=1481.52], EntityChickensChicken['Emerald Chicken'/374, l='MpServer', x=-2815.65, y=63.00, z=1479.58], EntityChickensChicken['Iron Chicken'/375, l='MpServer', x=-2814.46, y=63.00, z=1472.18], EntityChickensChicken['Iron Chicken'/376, l='MpServer', x=-2811.17, y=63.00, z=1473.10], EntityChickensChicken['Gold Chicken'/377, l='MpServer', x=-2811.47, y=63.00, z=1482.66], EntityChickensChicken['Gold Chicken'/381, l='MpServer', x=-2818.24, y=63.00, z=1471.76], EntityChickensChicken['Gold Chicken'/382, l='MpServer', x=-2817.69, y=63.00, z=1471.76], EntityChickensChicken['Gold Chicken'/383, l='MpServer', x=-2816.28, y=63.00, z=1471.76], EntityChickensChicken['Gold Chicken'/384, l='MpServer', x=-2812.87, y=63.00, z=1477.15], EntityItem['item.name.lootbags_lootbagXisumavoid'/3714, l='MpServer', x=-2777.61, y=256.00, z=1576.58], EntityChickensChicken['Gold Chicken'/387, l='MpServer', x=-2814.40, y=63.00, z=1471.76], EntityChickensChicken['Nether Quartz Chicken'/388, l='MpServer', x=-2813.02, y=63.00, z=1471.76], EntityChickensChicken['Coal Chicken'/389, l='MpServer', x=-2812.58, y=63.00, z=1471.76], EntityChickensChicken['Gold Chicken'/390, l='MpServer', x=-2810.76, y=63.00, z=1471.76], EntityChickensChicken['Gold Chicken'/391, l='MpServer', x=-2815.36, y=63.00, z=1471.76], EntityChickensChicken['Gold Chicken'/392, l='MpServer', x=-2811.36, y=63.00, z=1471.86], EntityChickensChicken['Gold Chicken'/393, l='MpServer', x=-2814.90, y=63.00, z=1471.76], EntityChickensChicken['Emerald Chicken'/394, l='MpServer', x=-2818.24, y=63.00, z=1475.77], EntityChickensChicken['Coal Chicken'/395, l='MpServer', x=-2811.89, y=63.00, z=1480.10], EntitySkeleton['Skeleton'/13964, l='MpServer', x=-2916.50, y=50.00, z=1595.50], EntityChickensChicken['Emerald Chicken'/397, l='MpServer', x=-2817.06, y=63.00, z=1480.67], EntityChickensChicken['Emerald Chicken'/398, l='MpServer', x=-2818.24, y=63.00, z=1477.60], EntityChickensChicken['Emerald Chicken'/399, l='MpServer', x=-2818.24, y=63.00, z=1480.50], EntityChickensChicken['Emerald Chicken'/400, l='MpServer', x=-2812.92, y=63.00, z=1475.50], EntityChickensChicken['Gold Chicken'/401, l='MpServer', x=-2818.24, y=63.00, z=1473.80], EntityChickensChicken['Gold Chicken'/402, l='MpServer', x=-2818.24, y=63.00, z=1480.05], EntityChickensChicken['Emerald Chicken'/403, l='MpServer', x=-2818.24, y=63.00, z=1474.21], EntityChickensChicken['Gold Chicken'/404, l='MpServer', x=-2816.74, y=63.00, z=1480.00], EntityChickensChicken['Gold Chicken'/405, l='MpServer', x=-2812.12, y=63.00, z=1472.43], EntityItem['item.item.goldNugget'/2454, l='MpServer', x=-2809.13, y=49.00, z=1481.38], EntityChickensChicken['Iron Chicken'/406, l='MpServer', x=-2811.59, y=63.00, z=1472.87], EntityChickensChicken['Gold Chicken'/407, l='MpServer', x=-2816.26, y=63.00, z=1483.24], EntityChickensChicken['Iron Chicken'/408, l='MpServer', x=-2815.99, y=63.00, z=1473.43], EntityChickensChicken['Emerald Chicken'/409, l='MpServer', x=-2818.24, y=63.00, z=1482.55], EntityChickensChicken['Iron Chicken'/410, l='MpServer', x=-2817.05, y=63.00, z=1475.19], EntityChickensChicken['Iron Chicken'/411, l='MpServer', x=-2818.08, y=63.00, z=1481.77], EntityChickensChicken['Coal Chicken'/412, l='MpServer', x=-2818.24, y=63.00, z=1475.28], EntityChickensChicken['Gold Chicken'/413, l='MpServer', x=-2817.40, y=63.00, z=1481.82], EntityChickensChicken['Gold Chicken'/414, l='MpServer', x=-2816.58, y=63.00, z=1475.76], EntityChickensChicken['Gold Chicken'/415, l='MpServer', x=-2817.31, y=63.00, z=1472.23], EntityChickensChicken['Gold Chicken'/416, l='MpServer', x=-2818.24, y=63.00, z=1473.31], EntityChickensChicken['Gold Chicken'/417, l='MpServer', x=-2815.84, y=63.00, z=1472.19], EntityPlayerSP['RezziPie'/160, l='MpServer', x=-2839.28, y=66.91, z=1517.63], EntityChickensChicken['Nether Quartz Chicken'/418, l='MpServer', x=-2817.79, y=63.00, z=1479.62], EntityZombie['Zombie'/11170, l='MpServer', x=-2908.50, y=47.00, z=1588.50], EntityLatchedRenderer['unknown'/163, l='MpServer', x=8.50, y=65.00, z=8.50], EntityChickensChicken['Emerald Chicken'/419, l='MpServer', x=-2818.12, y=63.00, z=1476.77], EntityChickensChicken['Nether Quartz Chicken'/420, l='MpServer', x=-2818.24, y=63.00, z=1474.68], EntityChickensChicken['Gold Chicken'/421, l='MpServer', x=-2817.13, y=63.00, z=1482.35], EntityChickensChicken['Gold Chicken'/422, l='MpServer', x=-2818.02, y=63.00, z=1478.81], EntityChickensChicken['Emerald Chicken'/423, l='MpServer', x=-2817.14, y=63.00, z=1482.96], EntityChickensChicken['Gold Chicken'/424, l='MpServer', x=-2815.36, y=63.00, z=1475.22], EntityChickensChicken['Coal Chicken'/425, l='MpServer', x=-2817.76, y=63.00, z=1482.34], EntityChickensChicken['Gold Chicken'/426, l='MpServer', x=-2812.67, y=63.00, z=1474.94], EntityChickensChicken['Gold Chicken'/427, l='MpServer', x=-2817.75, y=63.00, z=1473.12], EntityChickensChicken['Gold Chicken'/428, l='MpServer', x=-2815.75, y=63.00, z=1474.17], EntityChickensChicken['Nether Quartz Chicken'/429, l='MpServer', x=-2816.86, y=63.00, z=1473.01], EntityChickensChicken['Coal Chicken'/430, l='MpServer', x=-2815.37, y=63.00, z=1472.64], EntitySheep['Sheep'/178, l='MpServer', x=-2778.11, y=72.00, z=1538.86], EntityCow['Cow'/438, l='MpServer', x=-2874.47, y=53.00, z=1510.20], EntityCow['Cow'/199, l='MpServer', x=-2784.53, y=68.00, z=1527.78], EntityItem['item.item.goldNugget'/16597, l='MpServer', x=-2814.33, y=65.73, z=1480.54], EntityCow['Cow'/222, l='MpServer', x=-2779.77, y=68.00, z=1524.48], EntityItem['item.name.lootbags_lootbagDevTeam'/3807, l='MpServer', x=-2778.12, y=256.00, z=1577.49], EntityItem['item.name.lootbags_lootbagiskall85'/14050, l='MpServer', x=-2779.86, y=256.00, z=1577.55], EntityRooster['Rooster'/227, l='MpServer', x=-2744.90, y=62.67, z=1497.56], EntityBat['Bat'/12260, l='MpServer', x=-2836.63, y=20.68, z=1530.52], EntityItemFrame['Item Frame'/488, l='MpServer', x=-2900.03, y=40.50, z=1431.50], EntityCreeper['Creeper'/5608, l='MpServer', x=-2902.50, y=42.00, z=1582.50], EntityItemFrame['Item Frame'/489, l='MpServer', x=-2900.03, y=41.50, z=1431.50], EntityItemFrame['Item Frame'/490, l='MpServer', x=-2900.03, y=41.50, z=1430.50], EntityItemFrame['Item Frame'/491, l='MpServer', x=-2900.03, y=40.50, z=1430.50], EntityRooster['Rooster'/753, l='MpServer', x=-2820.82, y=73.00, z=1628.44], EntityCow['Cow'/243, l='MpServer', x=-2793.15, y=64.00, z=1521.61], EntityBat['Bat'/15605, l='MpServer', x=-2760.46, y=43.05, z=1485.08], EntityLatchedRenderer['unknown'/1783, l='MpServer', x=-2839.50, y=67.24, z=1517.68], EntityItem['item.name.lootbags_lootbagdocm77'/2553, l='MpServer', x=-2791.14, y=76.00, z=1573.51]]
	Retry entities: 2 total; [EntityLatchedRenderer['unknown'/163, l='MpServer', x=8.50, y=65.00, z=8.50], EntityLatchedRenderer['unknown'/1783, l='MpServer', x=-2839.50, y=67.24, z=1517.68]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by CriticalMole** [comment]
Its a conflict between Chisel and Bits & Architecturecraft.
You are placing the block and it is detecting C&B nearby and throwing a wobbly, nothing we can do about this, but you may be able to achieve what you want by being careful about whats placed where and when you place the blocks

**Comment by chland** [comment]
The ArchitectureCraft 1.7.3 changelog says:

> Fixed "tile entity cannot be cast to gcewing.architecture.ShapeTE" client crash caused by attempting to place an ArchitectureCraft block in a space partially occupied by another type of block having a tile entity.

I currently don't have time to test it, but updating to that version (which is included in FoolCraft since 1.4.5) **might** fix those crashes.

**Comment by scalda** [comment]
Yes please try 1.4.6 version of the pack as this has been fixed in the mod update

**Comment by RezziPie** [comment]
I will try that. Thanks for all the help
