### ISSUE TITLE
performance issues.

### ISSUE THREAD

**Issue by 989onan** [scalda/FoolCraft#572]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When moving across line in basement of created house enormous lag spike is created

## Reproduce Steps
move along line marked in vanilla bricks along cross/arrow side (logs into world on correct side of line) and move with creative flight in creative while holding Ctrl (aka fast flight) and get lag spike.

## Additional Information

WORLD FILE: (google drive link i put in a folder of things i never ever delete)

https://drive.google.com/file/d/0B6bI8jWVo2h8T2VqM2FMeWh0UUk/view?usp=sharing 

(I made the sharing settings public to web so if you don't have google account it can still be downloaded)

i have tried...
- deactivating draconic cell.
- destroying controller on refined storage system.
- getting rid of storage drawers.
- getting rid of nether star generator.
- getting rid of woot farm multi block.
- getting rid of half of growing crop field.
- getting rid of all of my diamond planters.

mods added or rid of....

added-
betterfps

removed
- moo fluid cows (caused a crash)

help with what can be causing the lag and how to get rid of will be appreciated!

**Comment by ImTheStigHonest** [comment]
I also am experiencing sever lag. only in one area,
no major lighting update or excessive ender io conduits

**Comment by 989onan** [comment]
I might have excessive ender io conduits I have some between the diamond planters if someone can see if its too much just bring up my world thats in the zip file link and see.....

**Comment by 989onan** [comment]
I think I have about 81 connections to one single output is that overdoing it?

**Comment by 989onan** [comment]
UPDATE: bringing up render distance to 17 eliminates lag spike entirely!!! that's weird but I would still like a fix

**Comment by 989onan** [comment]
i originally had it on 2

**Comment by McSassyK** [comment]
Just updated to 1.4.6 today. Everything is great except for one really weird thing. I have just a simple little vanilla 2x1 jeb door as the entrance to my base. Super basic. Yet I spike so bad every time I enter or exit my base through that door that it takes about 30 seconds to just get through the door. Even standing still in the vicinity of the door causes my frames to plummet. I tried knocking it out and rebuilding it after the update but same issue. The base itself is pretty low tech so far; not a lot running at all since it's a pretty new world. Can't imagine why a vanilla jeb door would be freaking the game out like it is :)

**Comment by Flekrad** [comment]
@989onan I can confirm (move along line marked in vanilla bricks along cross/arrow side) right at this spot there were many times I got lag moments . I pressed F3 ( as I have no other way to actually measure it) and the numbers dipped always here. It always was worse whilst looking at the draconic energy ball (whether it was on or off . When i was at end of platform where it's just stone(facing away from energy ball)  i had the highest fps . Maybe move the ball (which sux as they Look Excellent) external to base or somewhere you aren't actively playing . **Sorry** I cant offer more .
On a side note I love how you hid the door in the caution factory blocks

**Comment by 989onan** [comment]
thx and it seems to only happen on 2 chunks and i have just kept it off that so i will try moving the energy ball my game likes to freeze randomly but not a deal breaker also this was posted when 1.4 wasn't released but no prob's i have been getting very bad fps lately i think i will close and thx again for the help!
