### ISSUE TITLE
No hostile Mob spawn 

### ISSUE THREAD

**Issue by DerSoftwerker** [scalda/FoolCraft#573]
- [X] I am running the latest version of FoolCraft
- [X] I am running FoolCraft via Curse/Twitch Launcher
- [X] I can reproduce this issue consistently
     - [ ] In single player
     - [X] In multiplayer
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I run a FC server on 1.3.3 and from one day to another the hostile monsters stopped spawning. During nighttime I was flying around but no hostile spawn appeared anywhere. related server properties:

difficulty=2
gamemode=0
view-distance=10
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=10

I have tried:
- set difficulty to peaceful and back to normal
- set randomtickspeed to 3 (default)
- used /kill on certain mobs (Zombie, Creeper, etc.), no result - was only able to kill a few endermites
- used a zombie spawn egg, the zombied stayed until killed
- ensured there is no mega torch by flying long distances into unoccupied areas.

## Reproduce Steps
1.) Wait for night
2.) fly around and look for hostile monsters

## Additional Information
Only I have admin permissions on the server, no interference of other players possible. The Server ran for about 2 months (fighting with massive lagspikes though) with regular spawn of hostile monsters. The issue was pointed out to me 3 days ago.

**Comment by DerSoftwerker** [comment]
Update: 

The Mob spawning now happens randomly (e.g. had two nights without any hostile mobs around my base, then one night with). No changes in game config etc.

**Comment by frenchiveruti** [comment]
Did you check creating a new world?

**Comment by DerSoftwerker** [comment]
Can try that for sure - but any idea what in the current world could cause the problem?

**Comment by frenchiveruti** [comment]
Not a single clue, I mean if you can spawn zombies and they can spawn from spawners then something is fucked up, but I want to know if it is a global issue of the server or a thing specific of that world.
