### ISSUE TITLE
zs script error on login 

### ISSUE THREAD

**Issue by PSILONCRAFT** [scalda/FoolCraft#574]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x] I am requesting help with installing or running the pack
![skjermbilde 2017-06-28 kl 23 43 28](https://user-images.githubusercontent.com/26674039/27661751-ce5eab7c-5c5b-11e7-8f7f-08c4bcabd18c.png)

## Issue Description

my fool craft server gives me this error on login. why can't find any obvious errors other than that these blocks are dymmyblocks just for the spacing of the avaritia extreme crafting

**Comment by scalda** [comment]
What version of the pack is this?

**Comment by frenchiveruti** [comment]
Did you disable the Avaritia mod?

**Comment by PSILONCRAFT** [comment]
Actually its a edited version of the latest foolcraft pack. Added some mods to the pack. Havent disabled avatitia

**Comment by frenchiveruti** [comment]
Make sure is active, because the script error is when MineTweaker can't find an specific mod, and that disables the entire script.
Check you mods folder and make sure there's an Avaritia one.

**Comment by PSILONCRAFT** [comment]
ok. then i have to make my own script on that, do you guys know of any good guide for using minetweaker to edit recipes with avaritia?

**Comment by Semajor** [comment]
Make sure you don't have Avaritia Additions installed as well as the most current version of Avaritia. Additions is now included in the base mod, so it will cause block id conflicts and make that particular script confuse itself with which mod to resolve the ids. I had this exact problem when I was customizing the pack for single player and needed to remove Avaritia Additions to fix it.

**Comment by PSILONCRAFT** [comment]
Yes i removed avaritia additions and updated to lates version of avtaritia, and still get the same error on startup. this is a server btw

**Comment by Semajor** [comment]
In that case hit 'T' to bring up the chat window and scroll up to see where the error started. You might have a material in the script that isn't loading properly and causing the remainder of the file to not load. If it's just Avaritia resources, try deleting the mod as well as its config file, then reinstall just the mod and let it generate a new config when it loads.

**Comment by PSILONCRAFT** [comment]
Aight. thanks mate
