### ISSUE TITLE
Fool Craft not responding issue, stuck on 7/7 grandfather clock.

### ISSUE THREAD

**Issue by sukiplays** [scalda/FoolCraft#575]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
I am using the Twitch App/Curse Launcher to play Fool Craft for the first time, I am using the 1.3.3 version of Fool Craft(Twitch wont let me use the others). The issue that occurs is that after clicking the play button from the launcher, I can see the loading screen, when the bar reaches 7/7 my mine craft tells me it is no longer responding, and always gets frozen on the grandfather clock, (see additional information for image) I have tried to wait and see if it will unfreeze, but it never does, and always gets stuck on the same file while loading. In addition, my computer screen goes black for a few seconds and returns back to normal, displaying this message, (see additional information for image). I have updated all of my graphics and visual drivers, I have allocated more than six gigabytes of ram to running the mod pack, and I am using 64 bit Java 8 on a windows 8 desktop computer. I'm not exactly sure where to find the crash report but I found a file called latest and copy pasted it here : https://pastebin.com/pjHU0HQc

## Reproduce Steps
I can consistently reproduce this issue by opening the curse launcher, selecting fool craft, when the mine craft main menu appears, I select play, wait for the game to load, and it will always freeze at the same spot while loading the grandfather clock. 

## Additional Information
https://gyazo.com/4f51a1fcfcfaafb1583509024d21ccc7  <- Image when my minecraft stops responding.
https://gyazo.com/9444b4b3dbb0ac4a34adb4aaa2c92edc <- Image where my graphics driver fails and restarts itself, always occurs as the loading reaches the clock file

**Comment by scalda** [comment]
looks like you need to try updating your graphics drivers

**Comment by sukiplays** [comment]
I checked my drivers are up to date and my computer can run other large mod packs like feed the beast beyond an attack of the b team with no problem, but more importantly feed the beast beyond because it also has both biblio and deco craft with grandfather clocks yet it runs those just fine . For this reason I feel like this is a pack specific issue.
