### ISSUE TITLE
Mod Suggestion - Immersive Engineering, Immersive Petroleum & Immersive Agricraft

### ISSUE THREAD

**Issue by raxixor** [scalda/FoolCraft#578]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Additional Information
https://minecraft.curseforge.com/projects/immersive-engineering
https://minecraft.curseforge.com/projects/immersive-petroleum
https://minecraft.curseforge.com/projects/immersive-agricraft

**Comment by Necro9227** [comment]
To add a little more context; Immersive engineering would be a nice addition, having huge multiblock structures that would fit well given the overall theme of the pack and that of the city of maybe provides. The block texture look as if they are taken from the late 1800's back when machines were huge.

**Comment by scalda** [comment]
Hi unfortunately iskall doesn't want Immersive Engineering in the pack sorry,
