### ISSUE TITLE
Foolcraft Modpack (Not Launching)

### ISSUE THREAD

**Issue by TristanJonesWEB** [scalda/FoolCraft#579]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
The Foolcraft Modpack does not launch and crashes immediately upon game launch

## Reproduce Steps
1. Open Twitch,
2. Click Minecraft
3. Press 'play'
4. and then Press 'play' again.
5. game loads for a few seconds (not enough to show a window)
6. Games crashes and shows a game output

## Additional Information
**Game Output** 
https://pastebin.com/gcaGsss1

**Comment by scalda** [comment]
I have just released 1.4.7 to release status. so please try it and if the problem persists please come back and post again
