### ISSUE TITLE
Problem with starting world in FoolCraft for first time. [With Solution]

### ISSUE THREAD

**Issue by pkpotato** [scalda/FoolCraft#58]
Seeing all the issues with fool craft and getting it to launch and having this issue myself. I thought I'd go ahead and address this issue myself. I will be attaching down below a step by step on how to increase the needed RAM to run fool craft. minecraft starts with 4gb allocated RAM upon start. Make sure to set it to run with at least 6GB of ram. Here is how to set it to 6gb of RAM. If this fix does not fix your issue, please post your issue with any run time errors associated with Java.

# Step 1: Click on three lines on the top right of the launcher box.
![1](https://cloud.githubusercontent.com/assets/11284520/24225394/788e0ef8-0f1d-11e7-88d4-8f510936e8d0.png)

# Step 2: Click on "launcher options".
![2](https://cloud.githubusercontent.com/assets/11284520/24225395/788e7fa0-0f1d-11e7-828e-d5ab6e918636.png)

# Step 3: Click on "FoolCraft".
![3](https://cloud.githubusercontent.com/assets/11284520/24225629/ce6acf86-0f1e-11e7-9de1-b763d0a2ae7d.jpg)

# Step 4: Highlight 4096 next to where it says "-Xmx4096m".
![4](https://cloud.githubusercontent.com/assets/11284520/24225632/ce83e7a0-0f1e-11e7-997f-c24303bba6ab.png)

# Step 5: Change 4096 to 6144 so it now says "-Xmx6144m".
![5](https://cloud.githubusercontent.com/assets/11284520/24225631/ce821f06-0f1e-11e7-8824-766438ce71f7.png)

# Step 6: Click on save and Enjoy playing the game!  (As of right now, I have needed to change this setting every time I load into the launcher, if there is a way to make this more permanent, please post down below and I will adjust accordingly.)
![6](https://cloud.githubusercontent.com/assets/11284520/24225630/ce7fc3e6-0f1e-11e7-9976-6e8efa2de0b2.png)

Once again if this does not fix your issue, please create your own post on this with a report from Java and what happened that didn't allow Fool Craft to run on your computer.

**Comment by vvolfe** [comment]
I was so hoping this was going to work but noticed I had already set my ram even higher.. but tried your way anyways.  Still no go.

Latest Log
http://paste.feed-the-beast.com/view/2f0fb5d5

**Comment by pkpotato** [comment]
@vvolfe Looks like there might be some collision between mods and something with your version of minecraft. Where did you get your version of Fool Craft? Did you get it straight from curse? Do you have any other mods for minecraft that have heavy modification of the minecraft files that might be colliding with these mod files? If you don't get it to work. I would back up any worlds you have of minecraft. Reinstall it from fresh and then try and redownload your version of Fool Craft. If that doesn't work, let me know.

**Comment by vvolfe** [comment]
@pkpotato This is a fresh install of foolcraft.. never been able to get it to work I have the same issues with Farm Valley and Forever Stranded.. but no problems loading FTB beyond or Skyfactory 3.  all from curse.  

this my default JVM arguments.. it came like this for all 3 mod packs that fail.  Anything odd there?

-Xmx6400m -Xms256m -XX:PermSize=256m -Dminecraft.applet.TargetDirectory="C:\Users\Mike\Documents\Curse\Minecraft\Instances\FoolCraft" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US

**Comment by vvolfe** [comment]
forgot to clarfiy.  No additional mods have been added

**Comment by vvolfe** [comment]
http://paste.feed-the-beast.com/view/47f9aec1

**Comment by pkpotato** [comment]
@vvolfe Diagnosing your pastebin log with my latest successful log, I noticed the last bit of your pastebin has

**Comment by pkpotato** [comment]
@vvolfe Look at your latest Pastebin log with my most recent successful log. Looking at your pastebin I see a big difference that might or might not be significant.

Your PasteBin:
[21:30:38] [Client thread/ERROR] [FML]: Suppressed additional 2 model loading errors for domain simplyconveyors
[21:30:38] [Client thread/ERROR] [FML]: Suppressed additional 5 model loading errors for domain harvestcraft
[21:30:38] [Client thread/ERROR] [FML]: Suppressed additional 10 model loading errors for domain blockarmor

While mine only has:
[18:32:13] [Client thread/ERROR]: Suppressed additional 5 model loading errors for domain harvestcraft
[18:32:13] [Client thread/ERROR]: Suppressed additional 10 model loading errors for domain blockarmor
[18:32:13] [Client thread/ERROR]: Suppressed additional 19 model loading errors for domain mca

I would guess somewhere around here is where yours is getting hung up. All I can see from here maybe it's an issue with FTB initial files that Fool Craft pulls files from since after this point, my log shows that it goes on to load all the plugins for the server while yours seems to cut off and crash. 

Your second pastebin seems completely normal as both my successful and unsuccessful logs both have those same exact errors.

looking through this it does not seem obvious of exactly what is going on. What OS system and what version are you running?

**Comment by vvolfe** [comment]
Thanks for looking @pkpotato 

I see what you are showing me but I admit its a bit above my head. not sure why mods would conflict. its the same as anyone else would be using with current version.

This is what I get.   and I am running windows 7 SP1


![image](https://cloud.githubusercontent.com/assets/26601839/24230308/c01c5676-0f54-11e7-883f-e0a4170b7aa5.png)

**Comment by pkpotato** [comment]
@vvolfe Looks like your hanging up on loading the actual minecraft engine itself, which could be something to do with Driver updates. More specifically, graphics card driver updates. Also, support for Windows 7 is gone from windows. So updating to a newer version of windows might help to alleviate this issue. Knowing this isn't a simple nor cheap solution. I would go through and check up on all your driver updates for hard drives, graphics cards, cpu, anything you can think of. 

Overall, seems like an issue between minecraft itself, your computer and a certain mod that's getting in the way. I would try running it one more time, take the log, and report it to the makers of the Forge minecraft engine. As for what exactly is going on, I feel I am not qualified to figure out exactly what is going on with the information given. I am sorry I could not get this to work :(. I hope you find the solution!

**Comment by vvolfe** [comment]
@pkpotato I really appreciate the assist. I'll double check my drivers again. Windows claims it's up to date but perhaps there are newer drivers still for my video card. It's an older card.. But just odd how other mod packs work. And they are just as current I'd think. Skyfactory3. Ftb beyond, survival stories 3 worked.

**Comment by pkpotato** [comment]
@vvolfe I tried the other two mods you talked about, I only got forever stranded to work, but farm valley didn't work due to an issue with curse, not with loading it in FTB. Just keep looking into other strands about this issue and hope someone has the answer you are looking for.

**Comment by kboha001** [comment]
I also had to up my memory just to run this.  I was able to make the change more permanent by updating the settings in the curse launcher settings.  Those settings appear to be passed into the minecraft launcher every time.  --

as seen in the image below I just doubled what the default was.  I have the memory so why not - might be a little overkill though.

![image](https://cloud.githubusercontent.com/assets/26615963/24231428/a60c9b3a-0f52-11e7-8636-b723bc0183f0.png)

**Comment by vvolfe** [comment]
@pkpotato 

Wanted to thank you again. I resolved the issue. got updated drivers directly from ATI website and that resolved my issue.

**Comment by pkpotato** [comment]
@vvolfe Glad the driver update worked!

**Comment by scalda** [comment]
@pkpotato i have added your above guide to out wiki as it was very informative thank you
