### ISSUE TITLE
ender energy conduits not working with draconic evolution

### ISSUE THREAD

**Issue by i-hate-usernames** [scalda/FoolCraft#580]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
draconic evolution and ender energy conduits not working together i had stored 5 billion rf  and couldn't use any of it for the fusion recipes, not to mention you removed awakened draconic chickens and mechanical users even though this pack is supposed to be OP

## Reproduce Steps
try connect ender energy conduits to draconic fusion set up, they connect but no recipe can be made as if no power is being sent, and put the OP chickens and mechanical user back in dont leave it to me to change the configs all the time im trying to follow along docm77's playthrough bit of a bitch when you then find out half the stuff docs done has been removed

**Comment by Flekrad** [comment]
Maybe try cryo stabilized flux duct apparently they transfer infinite rf . I agree not having the funky chickens that Doc had was a bit of a let down but after (A LOT) of crafting the Tier8 energy ball is awesome .
![2017-07-08_10 08 32](https://user-images.githubusercontent.com/29991384/27981159-ecb5bfee-63c6-11e7-85f5-d5c36de03e42.png)
