### ISSUE TITLE
Chisel and Bits Stairs No Longer Work Like Stairs

### ISSUE THREAD

**Issue by McSassyK** [scalda/FoolCraft#582]
Chisel and Bits Stairs No Longer Work Like Stairs

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
In previous versions of Foolcraft, I made staircases from full blocks using chisel and bits. They worked just like vanilla stairs. When I upgraded to 1.4.6 the other day, the game is treating the chiseled stairs like full blocks, making me have to jump up them. I've used chisel and bits in other mods and I've always been able to make usable stairs from chiseling.

## Reproduce Steps
Set a few blocks down. Set chisel to 1/2 size cube. Make some stairs. Try to walk up them.

**Comment by frenchiveruti** [comment]
From which version do you upgraded?

**Comment by McSassyK** [comment]
I believe it was 1.3.3

**Comment by frenchiveruti** [comment]
Hmm ok, maybe it was an update on that specific mod that created the different behavior between versions, I don't have the data to check if the previous version (1.3.3) delivered a different version of Chisel and Bits against the one you're using.
You could check by manually updating the mod in your mods folder to see if that makes a difference.

**Comment by scalda** [comment]
i have just released 1.4.7 that fixes this issue
