### ISSUE TITLE
1.3.3 Game Won't Start, Issue Loading Textures

### ISSUE THREAD

**Issue by EroAxe** [scalda/FoolCraft#583]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description I have a friend who's been trying to get the mudpack to work and for whatever reason as soon as it finally reaches 7/7 on the loading screen for him, it just crashes, (he's not the best with this so I'm not sure the exact crash report) but he says it says something like this "19/55 clients$1
initializeing texture stuffed creeper".  If anyone has a fix please let me know, he's been hoping to set up a server so we can play together but he can't get it to work.

**Comment by scalda** [comment]
I have just released 1.4.7 to release status. so please try it and if the problem persists please come back and post again

**Comment by EroAxe** [comment]
The issue is scalda that my friend is trying to set up a server, and the website he's using for it will only allow 1.3.3 for the server.
