### ISSUE TITLE
Chisel  Block texture disappears after cooling in casting basin

### ISSUE THREAD

**Issue by lthaus** [scalda/FoolCraft#584]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
The metals with diagonal pattern disappear after cooling in the casting basin.  They show properly in a chest.

## Reproduce Steps
smelt 9 ingots of metal and pour into block.
watch it cool and disappear.

**Comment by scalda** [comment]
this is an old known issue it's the way tinkers choose which recipe to use we have tried to change it to something else but it just hasn't worked in the past. thanks for the issue thou
