### ISSUE TITLE
Concrete Mod crashing Server during startup

### ISSUE THREAD

**Issue by DerSoftwerker** [scalda/FoolCraft#586]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I was trying to update my server to 1.4.7 but after uploading the server files, the server would crash during the the initialization phase. I renamed my world temporarily to create a new one with the same name and still get the same crash. Only after deleting the "concreteMod-1.2.jar" in the mod folder, the server would finally start and create a new world.

## Reproduce Steps
Copy server files to server
Start server - crashing
Delete "concreteMod-1.2.jar"
Start server - not crashing

## Additional Information
https://pastebin.com/3gkznptu

**Comment by DerSoftwerker** [comment]
I also tried to upload the concreteMod and dbrownutils from the foolcraft client folder, but recieved the same crash

**Comment by scalda** [comment]
yes i am aware the server files are broke t only come to light once released my testing did not show this

**Comment by DerSoftwerker** [comment]
Concrete Mod had another update a day ago (same Version number though). I manually updated and the server is now working again for me.

**Comment by csokasg** [comment]
that's very good news, hopefully the pack will be hotfixes shortly :)

**Comment by scalda** [comment]
The pack will be updated and pushed today with the new concrete mod updated
to resolve the server starting issues

**Comment by csokasg** [comment]
i see the new pack (thanks for the quick upload) , but can you upload the server files too please? (there's no 1.4.7 version also)

**Comment by scalda** [comment]
They are in  the process of being approved
