### ISSUE TITLE
Fresh 1.4.7 server install crashing on startup

### ISSUE THREAD

**Issue by Xalveris** [scalda/FoolCraft#587]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Reproduce Steps

- downloaded and unpacked foolcraft 1.4.7 server files in empty folder
- run 'start' batch file
- server starts setup and crashes in the middle somewhere

## Additional Information

I tried removing the concrete mod as suggested by the other person having problems with server crash, and that didn't fix it.

https://pastebin.com/Qjn8HvPf

**Comment by scalda** [comment]
yes i am aware the server files are broke t only come to light once released my testing did not show this
