### ISSUE TITLE
Invisible redstone conduits from Ender IO

### ISSUE THREAD

**Issue by R13tr0t** [scalda/FoolCraft#588]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

My redstone conduits from Ender IO goes invisible when I want to click them with the wrench, so currently I cant attach them to machines. I have no idea what is causing the trouble, I relogged rebooted and I am even on the new version of foolcraft. It is not crashing so I have no crash reports.

## Reproduce Steps

![2017-07-04_16 59 45](https://user-images.githubusercontent.com/29895460/27835280-9ae53026-60da-11e7-9858-1c2e8697ac4f.png)
![2017-07-04_16 59 51](https://user-images.githubusercontent.com/29895460/27835282-9ce0b4cc-60da-11e7-837b-f4ce61929904.png)

**Comment by DerSoftwerker** [comment]
Hold control and scroll with the mouse wheel. It is a feature from EnderIO that you can highlight only the conduits you want to work with.

**Comment by Necro9227** [comment]
Holding down shift with the Yetta Wrench in hand you can use the mouse wheel to scroll through it options to show only that type of conduit, cycle through said options until you land on a green tick that shows all.

**Comment by R13tr0t** [comment]
I am such a noob, I didn't know this was a thing (I am new to modded). It worked. Thanks
