### ISSUE TITLE
Update to Fool Craft 1.4.7 causes Java Crash

### ISSUE THREAD

**Issue by AyaMayume** [scalda/FoolCraft#593]
## SUGGESTION/HELP
- [  ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ X] I am requesting help with installing or running the pack

## Issue Description

Since the update my Fool Craft Instance on the Twitch Client would complain that I had duplicate mods that had been interfering with loading Forge.

Unable to figure out how to remove the offending mod I just completely erased the instance and downloaded a fresh installation.

After everything downloaded I ran Fool Craft, however, half way though the Forge loading screen a pop-up would come up saying that Java Run-time has crashed.

As far as I know it's not generating a Crash Report, however I do admit that I wouldn't know where to find it.

Update: I tried downgrading to an older version and it still has the Java Crash. I uninstalled Java then downloaded and installed the latest version of Java, also still has the Crash.

**Comment by frenchiveruti** [comment]
Try updating the "concrete" mod to the lastest version and report back if the issue continues. :)
