### ISSUE TITLE
Changelog out of date

### ISSUE THREAD

**Issue by thefinaldegree** [scalda/FoolCraft#595]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
FoolCraft's Changelog has only been updated to 1.4.3

## Reproduce Steps
[https://github.com/scalda/FoolCraft/blob/master/ChangeLogs/FoolCraft_ChangeLog.pdf](https://github.com/scalda/FoolCraft/blob/master/ChangeLogs/FoolCraft_ChangeLog.pdf)

**Comment by scalda** [comment]
Hi yes we are aware that it's out of date we are working on it

**Comment by scalda** [comment]
https://github.com/scalda/FoolCraft/blob/master/ChangeLogs/FoolCraft_ChangeLog.md
