### ISSUE TITLE
Foolcraft keeps crashing when loading world

### ISSUE THREAD

**Issue by MayaMC** [scalda/FoolCraft#596]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

**Comment by Necro9227** [comment]
It's a common bug to do with the Moo fluids cows,

**Comment by scalda** [comment]
put all cows in nets that you want to keep then load the world with moo fluids removed and then readd the mod and then release your cows once more

or edit your player data to move your position
