### ISSUE TITLE
Draconic Evolution crafting animation and progress not showing 1.4.7-1.4.8.

### ISSUE THREAD

**Issue by Tect0nic** [scalda/FoolCraft#597]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

The crafting process of draconic evolution is not showing. like the lightning and progress of the item even inside the GUI of the crafter. The item will still craft and pull the power out of my energy bank but won't show how complete it is to finishing

## Additional Information

http://imgur.com/nk88RK7 (the recipe is ready to be crafted)
http://imgur.com/ABmIqJD (after i hit start that's what the GUI looks like)
http://imgur.com/LhlvsYY (all the items in the crafter, ignore the energy input output that wasn't from the crafting progress it's from woot farms and RF)
http://imgur.com/3SkiZCz (then after a little bit the item will be done and crafted)

**Comment by scalda** [comment]
please report this to the mod author as this is not a pack issue
