### ISSUE TITLE
Ender Bags and White Concrete Powder Broken

### ISSUE THREAD

**Issue by McSassyK** [scalda/FoolCraft#598]
Ender Bags and White Concrete Powder Broken

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I just upgraded to 1.4.8 today. I made my entire storage room out of framed storage drawers which use redwood logs as trim and white concrete powder for the sides. Logged on after the upgrade to discover that all my storage drawers are now invisible because something seems to have changed with the concrete powder. 

Also, none of my ender bags will open.

**Comment by scalda** [comment]
Yes the concrete mod has changed all it's id's, some things won't look right but others should be fine

Make a chest with the same colour and try accessing it?

please report back with any crash reports

**Comment by McSassyK** [comment]
Unfortunately it was all the framed storage blocks which needed to be put into the framing table with a newly crafted concrete block with the new ID in order to update it. Had to dump entire storage into a colossal chest and basically redo everything but... it's minecraft! ;) These things happen! Still love the mod.


Sent from Yahoo Mail for iPhone


On Saturday, July 8, 2017, 7:24 PM, Scalda <notifications@github.com> wrote:


Yes the concrete mod has changed all it's id's, some things won't look right but others should be fine

Make a chest with the same colour and try accessing it?

please report back with any crash reports
