### ISSUE TITLE
Can't place blocks and mined blocks disappear

### ISSUE THREAD

**Issue by McSassyK** [scalda/FoolCraft#599]
Can't place blocks and mined blocks disappear

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When I mine blocks, they vanish. My pick isn't connected to any chest. If I log off and back on again, the blocks show up in my inventory but I can't actually use them while they're invisible. I also can't place blocks. I took a stack of cobblestone out of storage and tried to place them and they look like they're placing, they are subtracted from my inventory, but they aren't there. If I log off and then back on again, the blocks show up in my inventory again.

**Comment by scalda** [comment]
Require more information, like logs and such?

**Comment by McSassyK** [comment]
It was any block. I ended up restarting my server 3 times and reinstalling the pack client side and that combo seemed to fix it. 


Sent from Yahoo Mail for iPhone


On Saturday, July 8, 2017, 7:11 PM, Scalda <notifications@github.com> wrote:


Require more information, like logs and such?

**Comment by AlleinSoldat** [comment]
I too am having the same issue in SSP. I found that my client spikes in lag for approximately 20 seconds. After this happens I can place blocks, but I cannot open chests or break blocks without them disappearing after they've been broken. I would provide a log, but I do not have a log mod running nor is there a crash log for it.

**Comment by ajdjyt** [comment]
i think this is TPS lag? what version are you running the server on?

**Comment by AlleinSoldat** [comment]
I'm not playing on multiplayer on a server. I am playing it on single player survival. Running it on the most current version. TPS is fine until that big lag spike, and that only happens when I'm exploring usually.
