### ISSUE TITLE
When i launch foolcraft it crashes with a report that shows me the cause is malisis doors

### ISSUE THREAD

**Issue by Lph369** [scalda/FoolCraft#6]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MalisisDoors (malisisdoors)

**Comment by Lph369** [comment]
i have no idea why it is doing this

**Comment by scalda** [comment]
Please provide a crash report.

**Comment by krisraynes** [comment]
I had that issue on another modpack , assuming you havnt tried to add optifine or any other client-side Mods then perhaps Graphics driver could resolve it?

**Comment by Lph369** [comment]
For some reason it works now??

**Comment by scalda** [comment]
so can this issue be closed now?
