### ISSUE TITLE
[Improvement] Changelog Cruseforge pdf -> md

### ISSUE THREAD

**Issue by Whazaaaaa** [scalda/FoolCraft#600]
Quick improvement to the changelogs. As of right now you always refer to the .pdf file instead of the .md file on the curseforge, etc. Perhaps change that ^^. Seeing as the md is updated more frequently than the pdf I suggest referring to that aswell in the changelogs on the websites you post the modpacks.

Probably a set copy paste for each new update that can easily be fixed :)

Thank you!

**Comment by scalda** [comment]
yeah i will do this thanks
