### ISSUE TITLE
Server 1.4.8 Crash on startup

### ISSUE THREAD

**Issue by jennykitten78** [scalda/FoolCraft#601]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Newly downloaded server, tried to run it after setting the memory settings. Crashed upon loading!
Seems to be caused by net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from LibrarianLib Stage 2 (librarianliblate)

## Reproduce Steps
Download pack, extract and run. 

## Additional Information
[Crash report](https://gist.github.com/jennykitten78/c8650717b94ed7ae87e456eb731c4f0d)

**Comment by iamshift** [comment]
same issue as #550
