### ISSUE TITLE
Game Crash Update from 1.3.3 to 1.4.8

### ISSUE THREAD

**Issue by SharkBaitRFSR** [scalda/FoolCraft#603]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
I am new to modded Minecraft, and I was playing on 1.3.3 I would like to continue with my progression and the twitch launcher would not allow me to update my profile so I created a new profile. I copied all of the things that were different from my old same to the new one and launched. The game crashed. I looked into it and people said it might be the chickens, so I netted all of the animals in my base. I also set the replace entities to true as was suggested and the save still crashes.

## Additional Information
https://pastebin.com/0zUwbMrL

**Comment by scalda** [comment]
up your ram to at least 6GB

**Comment by SharkBaitRFSR** [comment]
I just tried it and got this crash report, I upped it to 12,288.
https://pastebin.com/YMMuef9N

**Comment by SharkBaitRFSR** [comment]
@scalda  are there any files that I should not have copied over?

**Comment by scalda** [comment]
delete that new instance and just update your current one. make sure to backup the world thou. 

i think you may of messed stuff up when you copied stuff over

**Comment by SharkBaitRFSR** [comment]
@scalda Everytime I try to update on Twitch I get this error, even though nothing is running. http://imgur.com/wJmngQN

**Comment by ajdjyt** [comment]
have you tried the update after a restart?

**Comment by SharkBaitRFSR** [comment]
I have multiple times.

**Comment by SharkBaitRFSR** [comment]
Well, I tried again and I removed the fluid cows mod entirely and it worked.
