### ISSUE TITLE
Game makes everything laggy

### ISSUE THREAD

**Issue by Inzult54312** [scalda/FoolCraft#61]
I've gotten into Foolcraft, but every 10 minutes or so, the game will freeze and cause my computer to freeze itself. I don't know, I've tried to allocate more RAM etc, but it doesn't work. Even when I want to quit the game, it freezes and gets the 'Stopped working error'. 
 
How do I fix this?

**Comment by CriticalMole** [comment]
when you go into the profile options and change the allocated RAM make sure you are cllicking on the OK button at the bottom and not closing it via the x in the corner.
The OK button is the only way it saves.

**Comment by Inzult54312** [comment]
I've done that, but nothing still works.

**Comment by CriticalMole** [comment]
are you using optifine?

**Comment by Razew** [comment]
How much RAM did you allocate, and how much do you have in total (PC)?

**Comment by scalda** [comment]
@Inzult54312 hi did you get this solved?

**Comment by Inzult54312** [comment]
@scalda Yep!
