### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by TripSirch** [scalda/FoolCraft#611]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
I am new to computer and i have researched extensively but i cannot seem to get the modpack to work. I am trying to install foolcraft through the standard minecraft installer. I do not wish to use twitch. I have downloaded forge 1.10.2 and the foolcraft server files. I keep getting stuck on the screen with the anvil and hammer. It will either get stuck on ender io or ftbu. I have waited hours at a time before clicking out and retrying. I have tried copy and pasting the mods into the appdata folder under .minecraft mods and also tried changing the source file to the foolcraft server foles folder. I have no idea what im doing and need help.

**Comment by JealousBread** [comment]
Check out the [Technic launcher](https://www.technicpack.net/download) or look at the [MultiMC instructions](https://github.com/scalda/FoolCraft/wiki/MultiMC-Guide).

**Comment by TripSirch** [comment]
I will try this when i get home but my whole goal is to be able to launch minecraft through Steam due to the console controller support and play foolcraft.

**Comment by TripSirch** [comment]
I got it working thank you for the help.
