### ISSUE TITLE
Crashing every time I use Chickens mod.

### ISSUE THREAD

**Issue by jgerbert1983** [scalda/FoolCraft#612]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I keeping crashing whenever I try to use the chickens. I have tried starting from scratch. I have tried letting them free range and using the chicken coop things. I always crash.

## Additional Information
https://pastebin.com/nnGt3f7t

**Comment by bogger33** [comment]
I think you can fix this by updating the more chickens mod

**Comment by jgerbert1983** [comment]
Thank you I will try that.
