### ISSUE TITLE
Refigned Storage "Lagging"

### ISSUE THREAD

**Issue by moridos** [scalda/FoolCraft#613]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
So what happened is that rs i kinda lagging i cant use the options in the grids, the sorting doesn't work and somethimes the external storage isn't working aswell

**Comment by EmperorSuper** [comment]
works fine for me, it only lags when i craft alot of stuff with different materials then it takes to time to craft it but other then that its fine for me

**Comment by gahro-nahvah** [comment]
The only issue I've encountered with RS lagging, is due to how poorly made the mod is, causing the external storage blocks to tick insane amounts, and lag out a server.

**Comment by moridos** [comment]
When ill stumble across this issue again ill make a vid for evidence :D
