### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Yonke** [scalda/FoolCraft#623]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
The game crashes when I get to step 7

## Reproduce Steps
1. Start game
2. Wait until step 7
3. Game crashes

## Additional Information
Specs: Intel Core i5-7400, Radeon 480 RX, Windows 10 64 bit
Crash report: https://pastebin.com/pVJcMcqL
Allocated RAM: 4GB
I haven't modified any of the files either

**Comment by 16patsle** [comment]
Minecraft ran out of memory it seems. Try allocating more
