### ISSUE TITLE
Trying to get foolcraft on Linux

### ISSUE THREAD

**Issue by EroAxe** [scalda/FoolCraft#624]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I have a friend who is trying to get FoolCraft on his Linux PC and he tried to use the MultiMC guide on here.  It downloaded fine but everytime he tries to launch it, it reaches 7/7 and then freezes.  If anyone can help it would be very appreciated.

**Comment by frenchiveruti** [comment]
It would be nice to know the RAM that your friend's system has, as it seems like an issue related to RAM overdosing on textures.  
FoolCraft is a ModPack that uses a lot of RAM (at least 6GB as a bare minimum), so yeah.

**Comment by Schaefer78** [comment]
For a 3-5 person server 12GB is good =). you will still see lag when RS starts getting used by everyone. I would wait and start fresh with the new 1.5 reset.
