### ISSUE TITLE
server lag when refined storage doesnt have power

### ISSUE THREAD

**Issue by violetkitty87** [scalda/FoolCraft#625]
Server lag for refined storage

## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Whenever refined storage flickers with power the server's tps goes down to 2% tps

## Reproduce Steps
have a full refined storage system
set up auto crafters
cut power from it

## Additional Information
I suggest swapping to applied energistics 2 cause refined storage is now unsupported for 1.10.2.
I have reported this to the refined storage creator and they say it isnt supported anymore for that version

**Comment by violetkitty87** [comment]
i asked him why and apparently he doesnt care

**Comment by DingoX3** [comment]
I agree with the move to ae2 instead. If hes not going to support issues that arise and its the dominating storage/automation mod it pretty much leaves the pack dead in the water(for servers especially) should it need updates and another problem comes up that cant be fixed.
