### ISSUE TITLE
[FYI] Chisels and Bits stairs issues

### ISSUE THREAD

**Issue by BrisingrAerowing** [scalda/FoolCraft#631]
## SUGGESTION/HELP
- [X ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Just FYI (I don't use FC as I am on 1.12.1), Draconic Evolution is another mod that breaks stairs created with Chisels and Bits, as it resets the player step height to 0.5 instead of the correct 0.6.

## Reproduce Steps
N/A

## Additional Information
N/A

**Comment by FeikoJoosten** [comment]
But what is the actual issue? Is the issue related to Foolcraft?
