### ISSUE TITLE
Child addon on trying to update the pack

### ISSUE THREAD

**Issue by xXTheRavagerXx** [scalda/FoolCraft#634]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x] I am requesting help with installing or running the pack

## Issue Description
Whenever I try to update the modpack it starts downloading it but after a while it shows that it cannot find a child addon(229625)

## Reproduce Steps

![screen shot 2017-09-08 at 11 16 54 pm](https://user-images.githubusercontent.com/31775801/30224321-ef1955e2-94eb-11e7-9a3b-3c601b277e97.png)
![screen shot 2017-09-08 at 11 16 53 pm](https://user-images.githubusercontent.com/31775801/30224324-f4b65090-94eb-11e7-846d-b5bd6936b373.png)

## Additional Information

#

**Comment by svennieke** [comment]
iirc this is a issue with the Twitch launcher, i had the same issue with another modpack once toke me 3 days to actualy install the pack, ever since the Twitch launcher got the twitch integration the minecraft section went downhill, i highly suggest you to report this as a bug in the Twitch Launcher app to

**Comment by tarnega** [comment]
In the Minecraft settings, setting the build to Alpha instead of Beta or Release allowed it to go through. It's possible that one of the mods is set to Alpha, and thus is showing nothing there if looking for Beta or Release.

**Comment by scalda** [comment]
just keep trying it's because alot of people are downloading the pack

**Comment by Flekrad** [comment]
I know this is closed , but there are tons of links out there (not just for this pack ) with this issue with so many so called fixes .Twitch keep pushing the fact slow internet = biggest cause . Here in Oz we (well me personally ) have very slow internet and tried I think all the fixes . Finally the 1 that Worked was setting Twitch to BETA . Pack updated immediately 
https://help.twitch.tv/customer/en/portal/articles/2739989-switching-between-live-and-beta

**Comment by xXTheRavagerXx** [comment]
thanks for  everyones help i was able to download the pack
