### ISSUE TITLE
Pickappa does not exist - Modpack is missing Mike Dongles mod, or other relevant mod with tool.

### ISSUE THREAD

**Issue by Bazizanab** [scalda/FoolCraft#636]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## The Mike Dongles mod is not included, thus, the Pickappa mentioned in the quest "It's Not Called Vein Miner!" under the chapter "Getting Started" does not exist. This is a bug report (the pickappa is mentioned in the quest book) as well as a request (add Mike Dongles mod!).

Go to Better Questing book.
Click "Getting Started" chapter tab.
View "It's Not Called Vein Miner!" quest (dirt block).
Read description: affected text is in cyan text.

**Comment by scalda** [comment]
fixed in 2.0.1 please update to that and delete the betterquesting folder from your world folder
