### ISSUE TITLE
Bandits make it impossible to start a game.

### ISSUE THREAD

**Issue by ChromeMystic** [scalda/FoolCraft#637]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I tried multiple seeds now, and none of them can be used for survival. The Modern Warfare Bandits just slaughter me immediately at the spawn. With the Silenced pistols I don't even notice that I am shot at. This makes the game basically unplayable since the Generation of Bandits cannot be disabled in MW yet. 

## Reproduce Steps
Create a Single Player World

## Additional Information
A downgrade of MW might be in order

**Comment by scalda** [comment]
Yes we are aware we are waiting a mod update to fix this

**Comment by ChromeMystic** [comment]
Perfect! The Pack looks very promising so far.

**Comment by ChromeMystic** [comment]
It seems that Mega Torches work on them, therefore you can create a somewhat safe spawn with minmal cheatery

**Comment by Tegwen** [comment]
I am going to have to cheat in a megatorch or two.  I watch packs of them spawn in.  The landscape was littered with corpses.

**Comment by hemhem666** [comment]
i was just wondering if there is a way to disable the mobs in the meantime till the mod update?

**Comment by Minken** [comment]
This issue shouldn't exist from the beginning, thus +1 to OP and -1 to Scalda's reply. I got killed 15+ times when I didn't had the chance to craft a wooden sword. Ridiculous!

Personally, I'm looking forward to the Server files. But that's another (non-created) issue.

**Comment by scalda** [comment]
sorry @Minken you feel this way but we weren't aware of this during testing as we test via a server and it wasn't happening on there, it wasn't until i gave it to the fools that it came about and to which i let the mod devs know and they are working on it.

**Comment by JmzBlond** [comment]
Game is unplayable due to this, Modern Warfare NEEDS to be removed and a hotfix putout till it can be fixed.

**Comment by BertTF2** [comment]
Temp fix is to go to peaceful for a bit, but it sucks that this happens :/

**Comment by ChromeMystic** [comment]
I decided to add command blocks that kill the bandit and gassy with the /cofh killall commands

**Comment by BertTF2** [comment]
@ChromeMystic could I have the exact command setup please? I'm not the greatest with command blocks :/

**Comment by BertTF2** [comment]
I found out how to do it. You need 2 repeating command blocks, set both to always active. Inside one use the command 
/cofh killall mw.bandit
and in the other one use the command
/cofh killall mw.gassy
This will instantly remove the bandits and gassys as soon as they spawn. To keep the chat from getting spammed with command block messages, type the command
/gamerule commandBlockOutput false
Hope this helps!

**Comment by ChromeMystic** [comment]
That is pretty much the setup I have, not pretty but works. I have actually burried them in the Bedrock of Layer 0 below spawn.
I am not great with command blocks either, I am sure someone could come up with a very pretty solution that only spawns like 2 bandits max per player online or something like that.

**Comment by theaphexhanna** [comment]
Is there any eta on when the mod will be updated? If not I'd strongly suggest removing it for now. It truly makes it unplayable for us nubs who cant use commandblocks...

**Comment by BertTF2** [comment]
@theaphexhanna Just remove it yourself, some of us want to use the mod. On twitch in the modpack in the top right click the ... and click open folder, open the mods folder, and remove the mod (you can add other mods to this folder as well)

**Comment by ariosos** [comment]
I see it's pretty bad for everyone else, too. I veinmined a birch tree and just started bleeding (no sound). Thought it was maybe some mod adding massive splinters. lol

I don't care about the MW mod, but I don't know if any of the quests in the questbook use it, though. So, I'll try the commandblock method. Not too familiar with them, either.

**Comment by ChromeMystic** [comment]
Here is a quick guide how to use the comand block: 
You need to have cheats enabled or play on a server as OP to use it.
Type the following command:

/give @p minecraft:command_block

If that doesn't work use your player name instead of @p

You need 2 command blocks in total, Place one down and set it to repeat (it will change colour to blueish) 
You need to add one command to each of them I placed them both to a redstone block in the bedrock at 01 (fly there in spectator mode the switch to creative)
CB|RS|CB
The commands are
/cofh killall bandit
and 
/cofh killal gassy

once you add a redstone signal, they will runn the command 20 times per second and kill all the mw mobs. Also you will get a lot of spam from it. to get rod of that type the following command
/gamerule commandBlockOutput false
Now you got rid of the bandits and can actually play the game. 
I also think they shouldn't be in the pack, but since the release of the mod wasn't flagged as alpha I also feel that some blame should go to the dev of MW for releasing a broken update without a config to disable the mobs.

**Comment by scalda** [comment]
the Mod has now updated and the bandits are disabled in the next version of the pack. sorry about this

**Comment by ChromeMystic** [comment]
Thanks, any eta on the update of the pack?

**Comment by scalda** [comment]
this weekend
