### ISSUE TITLE
Cobblestone Disappearing From Inventory

### ISSUE THREAD

**Issue by EmritYR** [scalda/FoolCraft#639]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Mined or Cheated in Cobblestone disappears from inventory almost immediately after being mined. All other blocks are mined and retained fine(impossible to test all blocks but it looks like it's only cobble being affected.) If i'm quick enough to cycle to the cobble i can place it in the world. Doesn't look like it's just invis either, re-logging and restarting seems to have no effect. 

## Reproduce Steps
Pick up Cobble

**Comment by scalda** [comment]
looks to be a problem with the quest book which has now been fixed and
pushed to curse

**Comment by scalda** [comment]
fixed in 2.0.1 please update to that and delete the betterquesting folder from your world folder

**Comment by EmritYR** [comment]
Thanks! Will update as soon as Twitch shows version 2.0.1
