### ISSUE TITLE
Game Crashes on Start up.

### ISSUE THREAD

**Issue by redstoneguy10ls** [scalda/FoolCraft#640]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
when ever i start the game it loads like normal and the crashes when it gets to stage 6 (when the tope bar says loading - 6)

## Additional Information
crash report:https://pastebin.com/5ZcWbQNC

**Comment by scalda** [comment]
remove optifine, and try again, if it works with out then try the latest version of optifine
