### ISSUE TITLE
Unbreakable Tinker's Pickaxe Destroyed (Furnace Block Armour)

### ISSUE THREAD

**Issue by EmritYR** [scalda/FoolCraft#641]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Unbreakable Tinker's Pickaxe was destroyed smelting cobblestone using Block Armour Furnaces. The pickaxe was not "Broken" the pick item itself was destroyed.

## Additional Information

Also Mod Suggestion to consider adding - PSI by Vazkii

**Comment by scalda** [comment]
ok please report this to the relevant mod authors
