### ISSUE TITLE
Cobblestone Dissapearing form inventory

### ISSUE THREAD

**Issue by simon343** [scalda/FoolCraft#642]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When ever cobblestone goes into my inventory, whether in survival or creative it will stay in my inventory for 3 second before disappearing.

## Reproduce Steps
1. Create new world with default settings
2. Mine or receive cobblestone
3. It dissapears

## Additional Information

I have finished cobble gobble

**Comment by ChromeMystic** [comment]
Thats actually a quest, one of them eats your first 64 cobble without asking

**Comment by notmark** [comment]
I've claimed the quest rewards and fed it several stacks of cobble, still disappears from inventory. On the quest it says Consume: Yes with no way to change it.

**Comment by scalda** [comment]
you will need to update to 2.0.1 to fix these issues but it hasn't synced
across the curse network

**Comment by ChromeMystic** [comment]
If you cannot wait, you can import it as a custom profile

**Comment by notmark** [comment]
I don't know what that means.

**Comment by simon343** [comment]
The update seems to have fixed the issue. Thanks Scalda
