### ISSUE TITLE
Draconic Evolution

### ISSUE THREAD

**Issue by simon343** [scalda/FoolCraft#643]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I believe adding draconic evolution to this modpack would add a lot of end game content and longevity to this modpack

**Comment by scalda** [comment]
sorry it was removed due to it not being overly fun and to grindy sorry

**Comment by simon343** [comment]
All good, thanks for taking the time to respond and give me an explanation.
