### ISSUE TITLE
Game Crashing Bug (Block Smasher)

### ISSUE THREAD

**Issue by triffman33** [scalda/FoolCraft#644]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Every time I place the "Block Smasher" from MineFactory Reloaded, the game either doesn't respond until I forcefully close it, or crashes.

## Reproduce Steps
Load up a singleplayer world
Place Block Smasher
Happy Crashing!

## Additional Information
https://pastebin.com/ma6Yd9hz

**Comment by ajdjyt** [comment]
can you provide crash reports?

**Comment by scalda** [comment]
please report this to the mod author
