### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by adriaan1313** [scalda/FoolCraft#645]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

When i (try to) install Foolcraft on twitch it gets stuck on mod 36 and later it says: Addon instance has no full path!

## Additional Information
https://i.imgur.com/eJ5omhr.jpg

**Comment by ajdjyt** [comment]
I have the exact same issue i just opened a thread too

**Comment by scalda** [comment]
this is a twitch problem where there is too many people trying to grab the same thing at once so please just keep trying
