### ISSUE TITLE
I Cant Install Foolcraft 

### ISSUE THREAD

**Issue by ajdjyt** [scalda/FoolCraft#646]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [X] I am requesting help with installing or running the pack

## Issue Description
Whenever i go to twitch to update or download the mod and press update i fail with a timeout or something like a "could not find child ad-don ......." message i cant even do it in a new profile let alone all 4 of my old ones , i think this just might be my twitch ,but i was wondering if there is another way i can install the pack ? 
Do i reinstall twitch
Is there another launcher i can try?
Or do i have to reinstall twitch?

**Comment by scalda** [comment]
this is a twitch problem where there is too many people trying to grab the same thing at once so please just keep trying
