### ISSUE TITLE
Suggesting Useful Mods to Add

### ISSUE THREAD

**Issue by Dragnier** [scalda/FoolCraft#647]
## SUGGESTION/HELP
- [x ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I think any combination of the following could be useful to your pack provided they are configured properly.

Suggested Mods to Add:

[Better than Mending](https://minecraft.curseforge.com/projects/better-than-mending) - Use xp directly from your levels to repair items with mending instead of having to farm new xp.

[Swing Through Grass](https://minecraft.curseforge.com/projects/swingthroughgrass) - Never miss a mob due to grass again!

[Dungeons2](https://minecraft.curseforge.com/projects/dungeons2) - procedurally generated dungeons with configuration for loot and generation.

[Lapis Stays in the Enchanting Table](https://minecraft.curseforge.com/projects/lapis-stays-in-the-enchanting-table) Quality of life for the avid enchanter!

[Xnet](https://minecraft.curseforge.com/projects/xnet) - Full automation control for the true factory manager! Move items, power, and redstone signals with in depth logic configuration. Also, super server friendly and coded to be as non-lag inducing as possible. By the same mod author as RF Tools.

[Quark](https://minecraft.curseforge.com/projects/quark) - very configurable, can turn off anything you don't want it to do rather easily. I suggest turning off things like the alternate chest, bookshelf, and bed recipies; however a lot of the additions from this mod (like Ancient Tomes and various decorative blocks) are very useful to have.

[Dark Utilities](https://minecraft.curseforge.com/projects/dark-utilities) - Great for Farms of all kinds... And maybe even a prank or two!

[Farming for Blockheads](https://minecraft.curseforge.com/projects/farming-for-blockheads) - Brings the utility of Cooking for Blockheads to Farming! Especially useful with Pam's Harvestcraft installed; even more so if there are other plant adding mods as well.

[Reconstructor](https://minecraft.curseforge.com/projects/reconstructor) - Repair tools, armor, etc. using RF power.

[Doggy Talents](https://minecraft.curseforge.com/projects/doggy-talents) - Smarter Pets!

[The Disenchanter Mod](https://minecraft.curseforge.com/projects/the-disenchanter-mod) - Remove pesky enchants or move useful ones to books for use on another item.

[The Weirding Gadget](https://minecraft.curseforge.com/projects/the-weirding-gadget) - A chunk loader that is both efficient and server/lag friendly. Far better than the FTB Utils chunk loading in regards to lag. Can be configured to use fuel and turn off if the owner isn't online within a certain amount of time or to be permanently on with no fuel at all. Loads the chunk it is in and the 8 surrounding chunks for a 3x3 chunk area.

[Growable Storage Cells](https://minecraft.curseforge.com/projects/growable-storage-cells) - Remove the need to fall down the crafting rabbit hole for all those AE2 storage cells; Grow them in your farm instead!

[Matter Overdrive](https://minecraft.curseforge.com/projects/matter-overdrive) - Star Trek themed mod that adds a LOT of stuff from phasers to the ability to become an Android. This one is a little big, and still in development but it would be fun to see everyone mess around with some of the stuff this mod can do.

**Comment by scalda** [comment]
thanks for the suggestions but no more mods will be added at the moment
