### ISSUE TITLE
Out of the Woods quest seems to only accept oak wood part builder

### ISSUE THREAD

**Issue by DwellerBenthos** [scalda/FoolCraft#649]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
"Out of the Woods" quest requires 8 blank patterns and a part builder. Part builders can be made of nearly any wood, but it appears the quest only accepts the one made from oak. 

## Reproduce Steps
Create a part builder from any(?) other wood than oak, quest does not complete. Tried mahogany, amaranth, and jungle woods, and they didn't complete the quest, an oak wood part builder did. Had to go searching for an oak wood tree as there were none in the immediate vicinity of where I spawned.

**Comment by DwellerBenthos** [comment]
Also happens with the "Dirty Drawers" quest, Seems to only accept drawers made from oak wood. This might be intentional, but considering there are several options for wood types and all of them might not be immediately available, the quests should accept the final product made from any wood type.

**Comment by scalda** [comment]
Yes unfortunately there is no way that I have found to allow it to accept
any type

**Comment by DwellerBenthos** [comment]
OK, too bad, seems the quest mod needs some more options.

**Comment by scalda** [comment]
we have found a way and we will be fixing it for the next release
