### ISSUE TITLE
No server files

### ISSUE THREAD

**Issue by npritzer** [scalda/FoolCraft#650]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
No server files for 2.0 or 2.0.1

## Reproduce Steps
look on [this link](https://minecraft.curseforge.com/projects/foolcraft/files)

## Additional Information
I am trying to setup my server but there aren't any server files available.

**Comment by scalda** [comment]
this is because i haven't made them yet

**Comment by npritzer** [comment]
when will you be making them a I would like to get started on my server?

**Comment by tarnega** [comment]
You could set it up manually and copy the config files from the client, adjusting to your liking.

**Comment by npritzer** [comment]
> You could set it up manually and copy the config files from the client, adjusting to your liking.
I am not good at doing this type of stuff @tarnega

**Comment by npritzer** [comment]
Thank you @scalda or @WinterGrave for uploading them
