### ISSUE TITLE
Another mod to add?

### ISSUE THREAD

**Issue by Trinsdar** [scalda/FoolCraft#652]
## SUGGESTION/HELP
- x I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

I know you are not adding any mods right now, this is just for sometime in the future.
I think that Ae2 stuff should be added to the pack. It adds just a couple utilities to make ae2 items more easily automatable.

**Comment by scalda** [comment]
i have added this to my list of mods to test with the pack thanks for the suggestion
