### ISSUE TITLE
Minecraft foolcraft 2

### ISSUE THREAD

**Issue by Vblade** [scalda/FoolCraft#653]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

**Comment by Vblade** [comment]
Im getting 2 fps....don't know the cause, cant play the game like that.

**Comment by ChromeMystic** [comment]
Have you increased the RAM in the curse launcher? It isn't a lightweight pack
