### ISSUE TITLE
Foolcraft server crashes during chunk loading

### ISSUE THREAD

**Issue by Vipered** [scalda/FoolCraft#654]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Running Foolcraft 2.01 on a dedicated server.  Foolcraft has been allocated 20gb and use of 16Ghz of CPU's (4x4Ghz cores).  When 2 or more people are loading new unexplored chunks for 1-3 minutes, server shuts down.

## Reproduce Steps
Log 2+ people in to the world, Op them so they can fly, then get them to fly to different unloaded chunks

Crash report below.  I have included 2 crash reports as they are all a little different

[Crash 1](https://pastebin.com/vv6ZEZjP)
[Crash 2](https://pastebin.com/KXCqr6Jb)

**Comment by scalda** [comment]
first crash is a slime island
second is a recurrent complex structure

you need to assign max 10gb ram you have far to much which will cause problems, try reducing the ram and report back?

**Comment by Vipered** [comment]
I originally tried it with 10gb and had the same issue.  I increased to 20gb to see if that would help.
In the end, even though this was a fresh install, I deleted that server instance and made a new one with the same settings and the issue went away, so I can only assume a corruption somewhere in the transfer of the files to the server.
