### ISSUE TITLE
Can't complete the concrete quest!

### ISSUE THREAD

**Issue by cyrilrbt** [scalda/FoolCraft#656]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

I can't complete the concrete quest

## Reproduce Steps

1. Make concrete, I tried light blue and light gray
1. Go to quest book
1. Nothing happens

## Additional Information

See video: https://youtu.be/fpZR3plOR80

(Yes, I died! The Modern Warfare mod's mobs are insane! I also cheated, but I'm not really playing yet, mostly testing early game stuff)

**Comment by scalda** [comment]
you need white concrete to complete the quest, i have no idea why it doesn't state the color
