### ISSUE TITLE
Modern Warfare mobs need a timer on when they can spawn

### ISSUE THREAD

**Issue by Jackspegal** [scalda/FoolCraft#657]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Every time I try to start a new single player game, the Modern Warfare Mobs are spawned right beside me, and kill me before I can even get started.  then when I respawn, they are there to kill me repeatedly.  This is making the game very much unplayable for me, as I can't do anything without getting killed right away, unless I put the game on peaceful mode, and that make me feel like I am cheating in a way.  I don't like to play that way.  is there a way you could put in a custom script that gives those mobs a timer that makes it so that they only start spawning after a set amount of time, like say after 1-2 minecraft days?

**Comment by scalda** [comment]
yes we are aware of this, the mod authors are working on it

**Comment by BertTF2** [comment]
Here is a temp. fix to keep them from spawning entirely.
You need 2 repeating command blocks, set both to always active. Inside one use the command
/cofh killall mw.bandit
and in the other one use the command
/cofh killall mw.gassy
This will instantly remove the bandits and gassys as soon as they spawn. To keep the chat from getting spammed with command block messages, type the command
/gamerule commandBlockOutput false
Hope this helps!

**Comment by Jackspegal** [comment]
Thank you, I will try that

**Comment by Jackspegal** [comment]
it did not work.  it killed the first group of mobs that spawned, but then it did not kill the second group of mobs

**Comment by DwellerBenthos** [comment]
Do you have the command blocks set to repeating? Are they placed in a chunk that is always loaded, like the spawn chunks or a chunk that is loaded with a chunk loader?

**Comment by Jackspegal** [comment]
I set them up in the spawn chunk, and tried all the modes.  I also did have them set to always active
