### ISSUE TITLE
disappearing cobble in 2.0.1

### ISSUE THREAD

**Issue by clownbzcraft** [scalda/FoolCraft#658]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

**Comment by clownbzcraft** [comment]
do we still need to remove the mod, or was it updated

**Comment by 0Chameleon0** [comment]
clownbzcraft, After installing the update to FoolCraft 2.0.1, I removed the directory betterquesting from the save directory in the instance you are playing, then restarted the modpack and found holding and placing cobble to be fixed

**Comment by scalda** [comment]
clown you 2.0.1 shouldn't have the problem it is fixed in 2.0.1, but try what @0Chameleon0 said and then come back to me
