### ISSUE TITLE
Better Questing - Early Game Options Quest. Placeholder invalid

### ISSUE THREAD

**Issue by 0Chameleon0** [scalda/FoolCraft#659]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
In the Better Questing Book
The Quest for "fighting Back" \ "Early Game Options" has an invalod item place holder for the retrievel task. It refers to a DarkUtilities placeholder - Original ID: darkutils:trap_move/0

## Reproduce Steps
Refer to the quest book

![quest error](https://user-images.githubusercontent.com/31796508/30246748-283f0fbe-9646-11e7-8089-3fb9214ce4d1.png)

**Comment by scalda** [comment]
yes thanks for this we are in the process of fixing the book now
