### ISSUE TITLE
Players cannot join my LAN world

### ISSUE THREAD

**Issue by Itsmillertyme** [scalda/FoolCraft#661]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [X] I am requesting help with installing or running the pack

**Comment by Itsmillertyme** [comment]
Follow up: It isn't a port forwarding issue that i can tell. I've manually port forwarded the port through my firewall.

**Comment by scalda** [comment]
i would just set up an actual server on one of the machines and do it that way I have never been able to get the lan part of Minecraft ever working properly
