### ISSUE TITLE
ME Controller is missing entirely

### ISSUE THREAD

**Issue by Chachava** [scalda/FoolCraft#662]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

The ME Controller item doesn't appear in JEI and I can find no mention of other methods to obtain them. The only thing showing is the "Fool's Controller" which seems to be a renamed energy cell. 

## Reproduce Steps

Simply searching for the ME Controller should be enough. 

## Additional Information

This is my first time posting an Issue to Github so my apologies if I've messed this up somewhere

**Comment by scalda** [comment]
That's because ae2 is in easy mode

**Comment by Chachava** [comment]
Ah right, I didn't even realise it had an easy mode.....I really should look into these things more. Thank you for the very quick reply.

**Comment by scalda** [comment]
no problem

**Comment by leasoncre** [comment]
how do i disable easy mode?
&/or enable smart cables?
