### ISSUE TITLE
question

### ISSUE THREAD

**Issue by hexangle** [scalda/FoolCraft#664]
so there are bandits in the pack and i was wondering how the mod is called so i can remove it

**Comment by scalda** [comment]
mw

**Comment by BertTF2** [comment]
I have a solution that you can use without removing the mod from the pack, just follow these instructions
You need 2 repeating command blocks, set both to always active. Inside one use the command
/cofh killall mw.bandit
and in the other one use the command
/cofh killall mw.gassy
This will instantly remove the bandits and gassys as soon as they spawn. To keep the chat from getting spammed with command block messages, type the command
/gamerule commandBlockOutput false
Hope this helps!

**Comment by DwellerBenthos** [comment]
Just be sure to have the command blocks either in the spawn chunks or a chunk that is always loaded with a chunk loader.
