### ISSUE TITLE
this pack is unplayable

### ISSUE THREAD

**Issue by mcvite80** [scalda/FoolCraft#667]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

**Comment by mcvite80** [comment]
I spawn in the day and am instantly killed by mobs toting guns, then go into a death loop of no escape.  Have tried repeatedly on different world in survival and same thing. Not even hardcore players could survive this. Needs fixing yesterday tbh. will try and play it again when fixed, but as of now its unplayable in single player.

**Comment by Vettriano** [comment]
Having the same issues. This experience comes close to "advent of ascension" level hostility, where you have to do everything to avoid these gunslinging bandit mobs. They hit very hard even with iron armor and theire range gives them an incredible edge.

**Comment by scalda** [comment]
delete the MW mod from the mods folder and you will be fine, we are awaiting a mod update
