### ISSUE TITLE
Tinkers Fatal Error

### ISSUE THREAD

**Issue by TheSubMatrix** [scalda/FoolCraft#668]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Whenever I am interacting with something in Tinkers Construct, The Server kicks me saying "A fatal error has occurred, this connection is terminated"

## Reproduce Steps\
I simply tried to use the tinker tables and whenever I try to craft something, the error occurs

## Additional Information
![oops](https://user-images.githubusercontent.com/25988883/30255690-75fba00a-9673-11e7-9d3d-106516b2c609.png)

**Comment by scalda** [comment]
i would purpose reinstalling the server and the pack
