### ISSUE TITLE
Using Furnace Armor REMOVED my unbreakable Tinker's Tools

### ISSUE THREAD

**Issue by MsTaz25** [scalda/FoolCraft#669]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

As I was vein mining sand to get glass and my furnace armor ran out of durability, I noticed that my tools dissappeared.  I remade the tools and more armor, and the same thing happened.  Please fix this because it takes too long to level up certain tools to have to keep making them over and over.

Please be aware that I was not using the tools that dissappeared.  I used an empty hand or a mattock but my sword and pickaxe went missing the first time and the next time it was my excavator :-(

**Comment by scalda** [comment]
mod has now been updated and this is fixed in the next version of the pack. Thank you for the report
