### ISSUE TITLE
Incompatibility issues with iskallium reactors and rail craft

### ISSUE THREAD

**Issue by Linc1234** [scalda/FoolCraft#670]
## SUGGESTION/HELP
- [x ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
There is a current issue when creating iskallium steel blocks. By default when you make iskallium steel blocks, (using the iskallium recipe) it becomes a railcraft steel block, making it unusable for iskallium reactors.

## Reproduce Steps
Make a steel block using iskallium steel ingots

**Comment by scalda** [comment]
here is the recipe for the iskallian steel block please check JEI next time for the correct recipe

<img src=https://i.gyazo.com/d79ad27d192286142b3d4ae6bad3679c.png>

**Comment by Linc1234** [comment]
I tried this recipe with all 3 different types of steel ingots and it is still not working. The JEI has the 9 steel ingots recipe
![2017-09-11_18 09 54](https://user-images.githubusercontent.com/31842369/30264581-7689ce9e-971c-11e7-853d-c3a63231d603.png)

**Comment by Linc1234** [comment]
fixed by removing then reinstalling foolcraft
