### ISSUE TITLE
Deep Dark Portal teleportation crashing

### ISSUE THREAD

**Issue by gildiarz** [scalda/FoolCraft#672]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Crashing after teleportation to Deep Dark. Can't get there.

## Reproduce Steps
Just try to use portal.

## Additional Information
[crash-2017-09-11_14.05.05-server.txt](https://github.com/scalda/FoolCraft/files/1292460/crash-2017-09-11_14.05.05-server.txt)

**Comment by scalda** [comment]
This is because the deep dark is disabled, but clearly not the block
