### ISSUE TITLE
Quest "No I have all these bits" cannot be completed.

### ISSUE THREAD

**Issue by ChromeMystic** [scalda/FoolCraft#673]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Quest "No I have all these bits" cannot be completed. The Chiselbags aren't recognized

## Reproduce Steps
Do the quest, craft some bags.

**Comment by scalda** [comment]
ok this has now been changed to a retrieval quest which will fix it in the next version of the pack thanks for the help
