### ISSUE TITLE
Mods Adding To This Pack

### ISSUE THREAD

**Issue by AutisticMC** [scalda/FoolCraft#674]
I am running the latest version of FoolCraft
 I am running FoolCraft via Curse/Twitch Launcher
 I can reproduce this issue consistently
 In single player
 In multiplayer
 I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
 I am crashing and can provide my crash report(s)
SUGGESTION/HELP

[x ] I would like to propose an additional mod, config change, custom recipe, etc.
 I am requesting help with installing or running the pack
Issue Description

I think any combination of the following could be useful to your pack provided they are configured properly.

Suggested Mods to Add:

Better than Mending - Use xp directly from your levels to repair items with mending instead of having to farm new xp.

Swing Through Grass - Never miss a mob due to grass again!

Dungeons2 - procedurally generated dungeons with configuration for loot and generation.

Lapis Stays in the Enchanting Table Quality of life for the avid enchanter!

Xnet - Full automation control for the true factory manager! Move items, power, and redstone signals with in depth logic configuration. Also, super server friendly and coded to be as non-lag inducing as possible. By the same mod author as RF Tools.

Quark - very configurable, can turn off anything you don't want it to do rather easily. I suggest turning off things like the alternate chest, bookshelf, and bed recipies; however a lot of the additions from this mod (like Ancient Tomes and various decorative blocks) are very useful to have.

Dark Utilities - Great for Farms of all kinds... And maybe even a prank or two!

Farming for Blockheads - Brings the utility of Cooking for Blockheads to Farming! Especially useful with Pam's Harvestcraft installed; even more so if there are other plant adding mods as well.

Reconstructor - Repair tools, armor, etc. using RF power.

Doggy Talents - Smarter Pets!

The Disenchanter Mod - Remove pesky enchants or move useful ones to books for use on another item.

The Weirding Gadget - A chunk loader that is both efficient and server/lag friendly. Far better than the FTB Utils chunk loading in regards to lag. Can be configured to use fuel and turn off if the owner isn't online within a certain amount of time or to be permanently on with no fuel at all. Loads the chunk it is in and the 8 surrounding chunks for a 3x3 chunk area.

Growable Storage Cells - Remove the need to fall down the crafting rabbit hole for all those AE2 storage cells; Grow them in your farm instead!

Matter Overdrive - Star Trek themed mod that adds a LOT of stuff from phasers to the ability to become an Android. This one is a little big, and still in development but it would be fun to see everyone mess around with some of the stuff this mod can do.

JurassiCraft 2.0- Welcome to JurassiCraft!

JurassiCraft is a mod based on Jurassic Park on Jurassic World franchises, but is not only limited to it. This mod allows you to create dinosaurs by extracting DNA from fossils and amber, and putting that through a process until you get a baby dinosaur! Not only does this mod add dinosaurs, it also adds many prehistoric plants!

Confused how to use this mod? Visit our wiki! It contains all the information you will need to create your very own dinosaurs!

Currently, this mod contains only 7 dinosaurs, but more will be added in the future!

Youtuber+-
Players are similar to Youtubers but spawn naturally
Players are not as strong as Youtubers

players are cheaper to tame taking 5,000$ instead of 100,000$ for a 100% tame rate

Want To Be a Superhero- This mod adds the suit and a shooter of multiple superheroes from MARVEL and DC. From batman to spidermans web shooter, you have everything you need to save the world of mincraftia. NOW AVAILABLE IN 1.10.2

Portal Guns Mod- More information can be found at iChun's Blog.
[http://ichun.me/portal-gun-is-back-heres-whats-new-and-whats-to-come/](url)

SuperHeroes Unlimited Mod- LegendsCore
(The Legends Core is the core-mod that all the Legends Modding Team's mods run from. This mod is required to be installed in order to use any of the others. )
[https://www.tihyo.com/legends-core](url)
[https://www.tihyo.com/superheroes-unlimited](url) (Main Mod)

**Comment by AutisticMC** [comment]
What does that mean

**Comment by MCChiter** [comment]
If that's ok to add to the list:
Big reactors: because not everyone is iskal and likes turbines
Draconic evolution: We have Avarita as one pain in the rear, why don't add another one
Mechanism: more multiblocks and heavy machinery 
Immersive engineering: even more multiblocks, wiring options, etc 
i think adding even those few will make pack implode and cause singularity to form but who knows.

**Comment by AutisticMC** [comment]
sure

**Comment by Flekrad** [comment]
Some of these mods look great 
Angel ring to bauble is in the pack
Tiny progressions is in the pack 
I would love to see Draconic Evolution back in here .. Working towards filling the Tier 8 Energy Ball was a blast , plus the RF transfer network was amazing , we used it a lot with zero issues/lag running over 
a dozen rainbow generators and approx 20 Fools Power source -connected to cryo flux tubes  ( I think that's the name Im not in game atm ) 
Better than Mending - Just use the Experience obelisk and feed the fluid into a Tank with a Tap on it and stand under it and have an XP shower , all items (with mending) are Repaired. Then put xp back into Obelisk .

**Comment by MCChiter** [comment]
Well not sure, my angel ring doesn't become bauble. can't see tiny progrressians and can't check right now. Dark utils will be good

**Comment by Flekrad** [comment]
To turn angel ring to bauble , just put (completed item) into a crafting grid and it changes it to a bauble version of the ring

**Comment by AutisticMC** [comment]
Add also orespawn plz

**Comment by scalda** [comment]
ok i have added quite a few here to a potential list
