### ISSUE TITLE
The game crashed whilst tesselating block model Error: java.lang.ArrayIndexOutOfBoundsException: 78

### ISSUE THREAD

**Issue by DaBenjle** [scalda/FoolCraft#675]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
Game crashes while moving around. Gives this error: 

The game crashed whilst tesselating block model
Error: java.lang.ArrayIndexOutOfBoundsException: 78

## Reproduce Steps
Walk around for a few minutes in game.

## Additional Information
Pastebin crash report: https://pastebin.com/UaTcgiT5
Also ive seen one other with a similar error somehow fixed it but i dont know what they did.

**Comment by scalda** [comment]
you have a corrupted world, it has been badly made i have seen this a couple times

**Comment by ChromeMystic** [comment]
I had a similar error when building my own modpack, it was actually caused by optifine for me. When i uninstalled that it worked again.
