### ISSUE TITLE
Mouse Wheel issues because of Mouse Tweaks/Inventory tweaks compatibility

### ISSUE THREAD

**Issue by maham** [scalda/FoolCraft#677]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Listen to iskall85 complaining about not being able to mouse wheel items between inventory and chest etc.

## Reproduce Steps
Try to use mouse wheel to move items between inventory and chest

## Additional Information
If I disable Mouse Tweaks this issue goes away. I have yet to try to disable Inventory Tweaks alone to see if this works as well but logic states it would work. My suggestion is to remove either or find a config option where only one of them are allowed to use the mouse wheel to move items.

Edit:
After some playing around I found out that if you just disable the mouse wheel setting in Mouse Tweaks you can have both mods playing nicely side by side without loosing any of the nice features they offer.

**Comment by scalda** [comment]
thank you i have just changed this in the pack for the next release
