### ISSUE TITLE
Updating error for Foolcraft 2.0

### ISSUE THREAD

**Issue by ThaStefess** [scalda/FoolCraft#678]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

I'm trying to update my foolcraft to version 2.0 or 2.0.1. Both have the same issue. When I update the modpack in my Twitch client it stops at mod number 100 something. The client gives me an error saying: "Addon instance has no full path" or "child mod 2218... is missing".

To reproduce this issue I simple have to try and update it again. It happens every time with all versions above 1.2.2

https://i.imgur.com/XOV8pT7.jpg

**Comment by FeikoJoosten** [comment]
This is unfortunately an issue with the curse launcher itself, not related to the modpack.
