### ISSUE TITLE
Not my Precious (power of the gods quest)

### ISSUE THREAD

**Issue by daddy77gaming** [scalda/FoolCraft#679]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

not my precious task.. all but steel block part completes.. steel blocks will not complete. Made the iskallium steel blocks (i know there are 3 different ones) and detect submit doesnt complete, also storing them and putting them back in inventory doesnt work

## Reproduce Steps

http://imgur.com/gallery/cpvaF

**Comment by scalda** [comment]
i have now fixed this for the next version of the pack which is due for release this weekend
