### ISSUE TITLE
Iskallium Mod Crash When You Connect 2 Pipes To The Reactor

### ISSUE THREAD

**Issue by tbjbu2** [scalda/FoolCraft#68]
Cant find the crash report :/

**Comment by tbjbu2** [comment]
And now I cant login to my world :(

**Comment by tbjbu2** [comment]
[crash-2017-03-24_10.38.09-server.txt](https://github.com/scalda/FoolCraft/files/867166/crash-2017-03-24_10.38.09-server.txt)

**Comment by scalda** [comment]
that is a thermal expansion crash please report to them
