### ISSUE TITLE
How do you even download and install it 

### ISSUE THREAD

**Issue by funky555** [scalda/FoolCraft#680]
Download
Title

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

see additional information

by clicking "install"

## Additional Information
I have tried all versions ( in twitch) i went onto technic pack, went to the website and downloaded from there but only gave me useless overrides

**Comment by scalda** [comment]
you need to download via the twitch launcher if you get the failed child thing you just need to keep trying this is a twitch problem, not the pack
