### ISSUE TITLE
Suggestions.

### ISSUE THREAD

**Issue by SirDizarm** [scalda/FoolCraft#681]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Additional Information

Mod suggestion: Tinker I/O

**Comment by FeikoJoosten** [comment]
Duplicate? https://github.com/scalda/FoolCraft/issues/442
(Feel free to add the mod @scalda)

**Comment by scalda** [comment]
added to the potential list
