### ISSUE TITLE
Angel ring not crafting

### ISSUE THREAD

**Issue by JmzBlond** [scalda/FoolCraft#685]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

Can not craft any type of angle rings.
Have all the items in the crafting bench but ring won't show up.

Have tried using JEI to fill crafting bench and have also tried manually place item neither work.

See picture below

## Additional Information

![image](https://user-images.githubusercontent.com/31801623/30385960-ba7ef728-98fc-11e7-96de-010f8f534275.png)

**Comment by ChromeMystic** [comment]
I have crafted mine yesterday, have you tried to use a regular crafting table?

**Comment by chland** [comment]
Just a very random guess but are you sure your golden lasso contains a vanilla bat? AFAIK there is a modded bat in the game from the Statues mod that might cause issues.

**Comment by JmzBlond** [comment]
Thanks Chland, It was a  Statues mod Bat. 
Found vanilla bat ans angle ring worked.
Very confusing as JEI filled the crafting bench and auto place the lasso in.
