### ISSUE TITLE
Server not starting (java.lang.OutOfMemoryError)?

### ISSUE THREAD

**Issue by spahen** [scalda/FoolCraft#686]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x] I am requesting help with installing or running the pack

## Issue Description
Me and my friend was playing on a server but he was experiencing some lag so he sent me his serverfiles so that i could host the server since i have more ram than him. I have been trying to set the server up for a while and have been googling for different solutions for over an over. Several minutes after starting the server it just starts shutting down. I do not get any crashreport in my folder but i have pasted as much as was shown of the serverwindow prior to the crash.

## Additional Information
https://pastebin.com/ZyiuHCmw

**Comment by FeikoJoosten** [comment]
I'd say your system is out of memory. For a modded minecraft server you need quite some ram, especially if you're also using the computer that's running the server as a client. Personally I'd say at least 6GB ram for the client, and at least 8GB of ram on your server.

**Comment by scalda** [comment]
Hi you need to up the amount of ram that you have allocated if you are running this on windows just use the start.bat in the server files and that will set the correct amount
