### ISSUE TITLE
Connecting a TE Energy Cell to My Iskalium Reactor killed my server

### ISSUE THREAD

**Issue by ChromeMystic** [scalda/FoolCraft#687]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
The Server Stopped when I added a TE Energy Cell Directly to my Iskallium Reactor.

## Reproduce Steps
I placed a TE Energy Cell directly to my Iskallium Reactor (3x3x3 with 1 Iskallium) and it immediatly closed the server (Gracefully) - I have attached the Crashlogs, the first is from the running server the other two are from the restart tries. I couldn't reproduce the Steps on Single Player

**Comment by ChromeMystic** [comment]
https://pastebin.com/U2KKEpZk First Crash
https://pastebin.com/U5GMVwKN Second Crash, the Third looks the same just different timestamp

**Comment by ChromeMystic** [comment]
https://pastebin.com/diyHGwpw The Leadstone Energy Conduit Crashes it as well, will try with EnderIO cabling now

**Comment by PlerpIsaiah** [comment]
Wait dosn't it SPECIFICALLY say in the description of the iskallium reactor to only use ender IO energy conduits directly to it

**Comment by ChromeMystic** [comment]
Not on the Curse Page as far as I can tell from my mobile phone. Only thing I found was a comment that EnderIO worked. And as I said there is no Problem in SP.

**Comment by janf3** [comment]
It does say so ingame

![2017-09-16_19 35 16](https://user-images.githubusercontent.com/15951093/30514514-62e7a2fa-9b16-11e7-8b19-05910e159001.png)

**Comment by scalda** [comment]
still awaiting a update on this but i am going to close for now
