### ISSUE TITLE
Roguelike Dungeons Loottables messed up

### ISSUE THREAD

**Issue by chland** [scalda/FoolCraft#688]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

RLD-chest only contain vanilla-loot because of invalid entries in loot_level3.json and loot_level4.json

Both file contain BlockArmors that are no longer in the pack.

## Reproduce Steps
Just run 

> /roguelike settings reload

in game to see further details.

**Comment by scalda** [comment]
Thank you for this i have now fixed the problem
