### ISSUE TITLE
Modern Warfare gas grenades prevent grave formation upon death

### ISSUE THREAD

**Issue by JourneymanJ** [scalda/FoolCraft#689]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
If you die to a modern warfare gas grenade in 2.0.1, your grave doesn't appear, and you lose all your items. You drop xp orbs, but that's all.

## Reproduce Steps
Throw a gas grenade, and walk into the area it landed. If you have any items, a grave containing them should appear when you die, but it doesn't. I killed myself with fall damage afterwards, as a test, and the grave appeared normally.

**Comment by scalda** [comment]
ok thanks for the info, as i have said in other posts the bandits will be disabled in the next pack version
