### ISSUE TITLE
Questing Item missing or non existent 

### ISSUE THREAD

**Issue by 3lementalS** [scalda/FoolCraft#690]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Some of the quests seem to be out of date and have to be forced completed

## Additional Information
https://imgur.com/am0DZm3

**Comment by scalda** [comment]
these will be fixed in the next version of the pack
