### ISSUE TITLE
gas grenade makes the screen go black

### ISSUE THREAD

**Issue by redstoneguy10ls** [scalda/FoolCraft#691]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
well when ever a bandit throws a gass grenade my screen goes completely black and i cant do anything about it except when i go in f5 mode or die i cant even bring up the escape menu. and if i come back to that spot then it will happen again. the same thing happens if i aim a gun but i can move that out of my inventory to go away.

## Reproduce Steps
go into a world, get a gas grenade, go in survival, throw it, and boom your screen is forever black

**Comment by scalda** [comment]
i have disabled the bandits in the next pack version thanks to an update in the mod
