### ISSUE TITLE
Autocraft Dark Steel Balls xu2

### ISSUE THREAD

**Issue by elbim** [scalda/FoolCraft#692]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Tried to automate Dark Steel Ball crafting by using the Mechanical Crafter from Extra Utilities 2. Took some Dark Steel and put it into the crafting field, but when the recipe was complete the server crashed instantly. Restarting the server isn't possible due to this issue.

## Reproduce Steps
Take some Dark Steel and put it into the crafting field using the Dark Steel Ball recipe.

## Additional Information
https://pastebin.com/cvuXkkWf

**Comment by scalda** [comment]
Hi yes the crafter is very buggy i have disabled it in the next version of the pack
