### ISSUE TITLE
Deep Dark Portal crash

### ISSUE THREAD

**Issue by Sancho558** [scalda/FoolCraft#693]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Tried to teleport to deep dark while standing on the portal,game crashed. Tried to reenter the world,crashed again.

## Reproduce Steps
Step on Deep dark teleportal

## Additional Information
Crash report: https://pastebin.com/DYrQv3QB

**Comment by scalda** [comment]
update to 2.1
