### ISSUE TITLE
Server Crash after Killing Ender Dragon/Wither

### ISSUE THREAD

**Issue by dozerwad10** [scalda/FoolCraft#694]
[crash-2017-09-14_15.12.02-server.txt](https://github.com/scalda/FoolCraft/files/1303520/crash-2017-09-14_15.12.02-server.txt)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Ender Dragon - Simply Killing the Ender Dragon will crash the server on the killing blow, all though I can put up with this because the Ender Dragon doesn't die that often the wither is whats screwing me over

Wither - Unlike the Ender Dragon the Wither doesn't crash the server on the killing blow if you simply fight it, It seems to only crash when I turn on my Auto Wither killing farm and when the first wither dies to the Shield generator the server crashes. 

## Reproduce Steps

Rebuild my farm on a server and test it (pictures below)

## Additional Information

https://imgur.com/a/Rak4E

https://imgur.com/a/Tn4SF

[crash-2017-09-14_15.12.02-server.txt](https://github.com/scalda/FoolCraft/files/1303526/crash-2017-09-14_15.12.02-server.txt)

Also I had to remove FakeBlocks from the server files due to constant crashes if you place one on an AE System. Don't think that is what's causing this though.

**Comment by scalda** [comment]
this is a rftools shield crash

**Comment by dozerwad10** [comment]
Interesting, So is there anything else in the pack that can kill withers semi-quickly?

**Comment by Kiosomic** [comment]
Had the same problem with my auto wither killer.  removing the hermit lootbags from the wither loot fixed it for me

**Comment by scalda** [comment]
this has now been fixed please update to 2.3.1 version of the pack
