### ISSUE TITLE
Concrete Color Reset bug.

### ISSUE THREAD

**Issue by johnwolf01** [scalda/FoolCraft#696]
## SUGGESTION/HELP
- [Config Change ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ No ] I am requesting help with installing or running the pack

## Issue Description
When placing colored dyed concrete powder and it drops and land on a torch it breaks and forms white concrete. (same way sand breaks when landing on torches)

## Reproduce Steps
Place concrete powder next to a block so that it would fall onto a torch to break similar to how vanilla sand breaks when falling on torch or slabs. 

## Additional Information
Dyed Concrete changes to white (lose color) when broken by falling on torches

**Comment by ajdjyt** [comment]
this is just a vanilla bug

**Comment by johnwolf01** [comment]
ermm , A vanilla bug? I dont understand.
concrete sand falling on a torch in currnet vanilla minecraft dont lose its color. Not that I can remember.

**Comment by scalda** [comment]
Reported to the mod dev

**Comment by scalda** [comment]
still not fixed to await mod dev to fix still he is aware of the issue
