### ISSUE TITLE
Random items vanishing from inventory. (Not Cobble)

### ISSUE THREAD

**Issue by SaltymcSaltface** [scalda/FoolCraft#697]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Put simply, items will randomly disappear from my inventory. It's very slow, so I didn't realize what was happening at first, but several important items such as hermitrons, stacks of food, tools, machines, or loot bags have disappeared. It's not all confined to one mod either, items from several mods have vanished now.

## Reproduce Steps
I play on the technic launcher, so that might be an issue? I don't know of any "steps" to reproduce this effect.

**Comment by thefinaldegree** [comment]
Some players on the server I run are also experiencing this bug.
