### ISSUE TITLE
server.properties motd not updated to 2.1 in 2.1 server pack.

### ISSUE THREAD

**Issue by virtualadept** [scalda/FoolCraft#698]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
server.properties motd still shows version 2.0.1.  Might confuse people on why their clients are incompatible if the server has been upgraded.

## Reproduce Steps
1. unzip latest server zip file.
2. $ grep motd server.properties
3. ???
4. Profit!

## Additional Information
mc@minecraft:~/fc2.1$ grep motd server.properties
motd=\u00A7a\u00A7l\u2550\u2550\u2550\u2563FoolCraft - \u00A74\u00A7l\u00A7n\u00A7a\u00A7l\u2560\u2550\u2550\u2550\u00A7r\n\u00A7e\u00A7o**Pack Ver. 2.0.1**  \u00A79\u00A7o\u00A7nhttp\://foolcraftmc.com

**Comment by scalda** [comment]
This is up to you guys to change for your servers not for me to change within the pack sorry
