### ISSUE TITLE
Block Armor Deletes/ breaks Tinkers tools and other tools or armor.

### ISSUE THREAD

**Issue by johnwolf01** [scalda/FoolCraft#699]
##

## SUGGESTION/HELP
- [ Mod Fix Needed ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
While using the Furnace Armor (Autosmelt) When the armor breaks while mining, it removes / delete any other armor, tools, weapons the player is using / wearing or have in inventory. (Including Tinkers Tools, that are supposed to be repairable. )

## Reproduce Steps
Equip Furnace armor (Block Armor Mod), 
activate feature Autosmelt and go mining.
When the Furnace armor breaks, it also breaks any weapon, tool, other armor including Tinkers Tools that are supposed to be repairable when broken.

**Comment by dozerwad10** [comment]
Wow, thank you so much for posting this. Me and my friend have lost multiple tools to this bug and honestly had no clue what caused it

**Comment by scalda** [comment]
what pack version are you using as it is fixed in 2.1??

**Comment by dozerwad10** [comment]
Personally still running 2.0.1 on my server (waiting for my host to update the files) but all good on my end if it's fixed in 2.1

**Comment by johnwolf01** [comment]
Guess we can close this Report 

Thank you scalda
