### ISSUE TITLE
CPU usage above 90%

### ISSUE THREAD

**Issue by Roothus1** [scalda/FoolCraft#7]
When I try to play FoolCraft my wife and I both have 90+% for our CPU. This causes quite a bit of frame issues. I launched a new world in HermitPack to see if I could narrow it down to the mod pack its self or not, and it ran HP just fine. Just wondering if anyone had any ideas on what it could be.

**Comment by krisraynes** [comment]
I raised the Ram via Curse Profile settings upto 6gb seems to help , but can't find an Optifine to work with it  , though playing in a window helps for now, just hoping someone sets up an MP server asap ...good luck ...

**Comment by Roothus1** [comment]
Bumping to 6GB did help. I completely forgot about that during my troubleshooting. Thanks for the help
