### ISSUE TITLE
Foolcraft 2.1 chunkloading problems

### ISSUE THREAD

**Issue by xGarionx** [scalda/FoolCraft#700]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
As in Version 1.4 and now in 2.1 (2.0 too), chunkloading issues previals prior versions work fine.
The game heavy lags on loading chunks while not generation tick lack.
Performance of the PC isnt an issue for sure

## Reproduce Steps
Starting up the game the chunk loading process is extremly low fps drops to 0~2 ,when all chunks are loaded the fps goes up to 120+ again.  The chunk loading can be speed up tremendously (even on 20+ chunks) to near instant when hitting esc and go into the game again, the issue rises again as soon the game trys to load another chunk (this is true regardless if the max render distanze is 2 chunks or 20+)

**Comment by xGarionx** [comment]
Tested it rogue like is not the issue (besided that i dont had any issues with ozone 2 at all)

**Comment by xGarionx** [comment]
well who needs reaction anyway right? <<

**Comment by scalda** [comment]
I can't help with this, this would be the pack on the pc, not the pack itself otherwise I would have thousands of complaints about it sorry
