### ISSUE TITLE
Lootbags cannot be submitted through Object Submission Station (BQ Mod)

### ISSUE THREAD

**Issue by Bazizanab** [scalda/FoolCraft#702]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

Attempting to submit lootbags through the Better Questing mod's Object Submission Station block does not work.

- Open up OSS.
- Attempt to put an unopened loot bag into the slot above the inventory slots.
- ???
- Not working! :D

**Comment by scalda** [comment]
hi what quest id is this so i can check it out please?
