### ISSUE TITLE
Early Game Options is still broken - followup to #659

### ISSUE THREAD

**Issue by ChromeMystic** [scalda/FoolCraft#703]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
In the Better Questing Book
The Quest for "fighting Back" \ "Early Game Options" has an invalod item place holder for the retrievel task. It refers to a DarkUtilities placeholder - Original ID: darkutils:trap_move/0

Also see Issue #659

## Reproduce Steps
Open the Quest log

**Comment by ChromeMystic** [comment]
So is the Rock Crystal Quest from the Sky is the Limit Questline

**Comment by MCChiter** [comment]
i have the same problem, some rewards are broken too, i ended up using commands to force-complete those quests

**Comment by svennieke** [comment]
The Rock crystals and the Iron chicken egg i can explain, as those require a certain Stone or egg, this can be fixed by ignoring the nbt tag
