### ISSUE TITLE
conveyer ore dublication

### ISSUE THREAD

**Issue by CloseUpDK** [scalda/FoolCraft#704]
- [ x] I am running the latest version of FoolCraft
- [ x] I am running FoolCraft via Curse/Twitch Launcher
- [x ] I can reproduce this issue consistently
     - [x ] In single player
     - [x ] In multiplayer
- [x ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
## SUGGESTION/HELP
- [x ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
ore duplication, one ore block into enderio alloy smelter and/or sag mill will in a 64 stack of ore added.
1 ore becomes 64 ores in the sag mill, one pulverized X becomes 64 in the alloy smelter.

## Reproduce Steps
just add advanced conveyers into the machines and drop ore onto it

## Additional Information
i'm all for ore doubling but this is a bit on the high side ;-)

**Comment by scalda** [comment]
added this to the mods github issues page
