### ISSUE TITLE
Wither or Not Quest broken

### ISSUE THREAD

**Issue by cyberdjinn** [scalda/FoolCraft#707]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Wither or Not quest cannot be completed.

## Reproduce Steps
(https://user-images.githubusercontent.com/30061080/30517280-3ec5904e-9b9d-11e7-9d4b-687b6c9fbf6c.jpg)

## Additional Information
It seems to be looking for an actually additions block placer. The MineFactory Reloaded block placer is not accepted as a substitute.
![2017-09-17_11 35 53]

**Comment by notmark** [comment]
Same issue here.

**Comment by scalda** [comment]
Fixed for the next version of the pack
