### ISSUE TITLE
Better questing bug

### ISSUE THREAD

**Issue by MCChiter** [scalda/FoolCraft#708]
Quest "Sunnarium in my eye" bugged out and keeps showing over and over
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

**Comment by Ravalli03** [comment]
Also having the same issue

**Comment by scalda** [comment]
the quest line is working fine i have just tested it on pack version 2.3.1
