### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by Thedogman2003** [scalda/FoolCraft#709]
When I attempted to download this mod pack I looked in it and it has no mods in the folder? Why are there no mods in any of the files? Am I required to download everything by myself. Please answer because I've tried everything to get this pack working! Btw I'm trying to use a single player version.

**Comment by Pr0ti0us** [comment]
I am also unable to download it gets mostly through it before saying somthing about unable to get a file.
addon# 220318  file# 2452877.

**Comment by PlerpIsaiah** [comment]
@Pr0ti0us I had to change my twitch launcher to beta mode for it to work when i was getting that issue,
hope that helps!
