### ISSUE TITLE
Important Improvement: Veinminer Config

### ISSUE THREAD

**Issue by desagas** [scalda/FoolCraft#71]
It would be extremely beneficial to change the config file setting in veinminer from "SNEAK" to "KEYBIND" or whatever the other config file name is. Having veinminer set to sneaking is extremely dangerous, especially when up high, as most people use sneak to not fall off while building and breaking!

It is a very simple switch, and it will make everyone's lives so much better.

**Comment by CriticalMole** [comment]
It is on the current list of possible changes already.

**Comment by scalda** [comment]
been changed in 1.2.1
