### ISSUE TITLE
Questbook Issues

### ISSUE THREAD

**Issue by sweetsosweet** [scalda/FoolCraft#710]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

Several quests seem to be bugged or broken. Examples: 

**Ore and Farm Automating** -> "Rocket Fuel, Shaken, Not Stirred" gives an Item Placeholder as a reward "itank:tank/0" which I now have in my inventory and does nothing.

**Fighting Back** -> "Early Game Options" calls for Item Placeholder "dark_utils:trap_move/0"
**Fighting Back** -> "Wither or Not" calls for Item Placeholder "actuallyadditions:blockPlacer/0"

**Getting Started** -> "Blaster? I barely know her!" calls for Item Placeholder plateCopper x16 and plateIron x27, but only detects plateCopper (I was able to cast the Railcraft plates, and am unsure how to cast Thermal Foundation plates to see if that works)

**All Things Chisel** -> "No i have all these bits" won't detect the Chiseled Bit Bag

## Additional Information

These are the ones I've found so far, I'm not sure if there may be more yet. I did update from the previous version to 2.1 and ran the **/bq_admin default load** command

Here's an imgur album: [link](https://imgur.com/a/uXsVT)

I am playing in single player.

**Comment by syntaxer** [comment]
I can confirm I have the Fighting Back -> "Early Game Options" bug. I didn't check the rest

**Comment by JmzBlond** [comment]
Also the astral sorcery quest required a rock crystal with specific stats making it a luck of the draw and pretty much. impossible to complete

**Comment by notmark** [comment]
I'm having the same problem.

**Comment by ajdjyt** [comment]
yes i am too having all this issues

**Comment by cyberdjinn** [comment]
Cross Breeder seems to also want a specific level cross bred Iron Egg ... which would be a low probability drop (getting the exact right numbers).

I would also suggest merging the other quest-related bugs into this one over-arching issue.

**Comment by MsTaz25** [comment]
I am also running into all of the afore mentioned issues including the one with the Cross Breeder.  I obtained the proper plates from both Railcraft and Thermal Foundation and neither works.

**Comment by hippietilley** [comment]
I have also run into the Getting Started plates issue, though I haven't tried any of the others yet.

**Comment by EGJohnClark** [comment]
i seem to not be able to satisfy the requirements of quest 1533 chickens poop what, it has a pic of a flint chicken egg and i've tried having every thing from a flint chicken in a net to eggs to the poop to flint in my inventory with no luck (this is my first time using this bug reporting system if i need to make a new thread for this please let me know)

**Comment by dragonswithpizza** [comment]
If i am not completely crazy, i believe these quests are from craft of the titans. The quest descriptions and items that is errored here, is in that pack. Also the quest tabs are surprisingly alike.

**Comment by scalda** [comment]
all these issues are now fixed in the book and will be released in the next update of the pack
