### ISSUE TITLE
angelring fails at 250m

### ISSUE THREAD

**Issue by V1XTR1X** [scalda/FoolCraft#712]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
angel ring runs out of gp at 250m +from the watermills

## Reproduce Steps
simply flying away from  the watermills i dropped out of the air and hit the ground very hard not sure it this is a bug or some1s dumb idea also doesn't work in the end or nether at all 
dose the same thing with all the rings

**Comment by Schaefer78** [comment]
Use a chunkloader for your water mills. Use the JEI for a Chicken Loader

**Comment by mcion3** [comment]
I have been having the same issue. I'll have to try the Chicken Chunks Chunk Loader. I have been using FTB Utilities for chunk loading.

**Comment by Schaefer78** [comment]
the FTBu is disabled by default in the configs only loader is the chickens Chunk. =)

**Comment by scalda** [comment]
Yes please use the chicken chunks loaders as like @Schaefer78 said the ftbu one is disabled as it was to inconsistent
