### ISSUE TITLE
Severe FPS issues

### ISSUE THREAD

**Issue by Antsy555** [scalda/FoolCraft#713]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
I am getting serious FPS issues (FPS staying no greater than 2 or 3 FPS at any given time).

My specs:

AMD Radeon HD 7800 series
16GB RAM

I have 12GB of RAM dedicated (pushing this up or down has no effect)
the problem persists whatever the render distance or other video settings

With the game open and running I only get 30% CPU usage and the modpack only seems to use up to 8GB of the RAM.

Chunks insta-load when I hit the Esc key, but when I return to the game the FPS issues continue with similar hardware usage, and the chunks remain fully loaded.

**Comment by PlerpIsaiah** [comment]
That is weird, since i only have 6GB dedicated to it, and it still runs fairly smoothly.
Maybe keep your render distance at or below 8 if its above that, and clean out your temp folder, which can help with everything on your computer if mincraft isn't the only thing running slow. (search %temp% in your start menu to get to it)

**Comment by DragonSamot100** [comment]
I've been having the same problem. XFX R7 370 for graphics... 32GB of RAM... Changes in the launchers settings to allocated RAM changes nothing... 12GB runs as terribly as 4GB and 6GB. I have 0 problems with other packs, such as Sky Factory 3. But in Foolcraft I get 0-5 FPS consistently, and 120 FPS when I hit escape

**Comment by Antsy555** [comment]
Ok ...

The problem has spontaneously fixed itself. I guess it was a fix with 2.0.1 but I don't really know.

@DragonSamot100 : the only advice I can give is to make sure that minecraft is running using your graphics card rather than your CPU (you can check with f3 in the top right). It might be worth changing to windowed mode and keeping task manager open to see CPU usage while you're moving about.

Also I seem to remember reading somewhere that the optimal RAM allocation is 6-8GB so maybe only allocate to 8 GB as well?

I'm happy that it's running well now but I'd also like to know why it spontaneously did so :/

**Comment by DragonSamot100** [comment]
Nah... 8gb is the same as the others, and on the debug screen it shows my graphics card as the rednerer... but I found something interesting. In the debug profiler graph "tick" is at ~95% while gameRender and render are extremely low...

**Comment by ClashNeon** [comment]
How do you make it so that minecraft runs off your graphics card instead of your cpu. My f3 menu says that it's cpu not graphics card.
