### ISSUE TITLE
Fooldraft 2.1 OpenGL crash

### ISSUE THREAD

**Issue by shadowtam** [scalda/FoolCraft#714]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I have run the pack twice with no issue since 2.1 but after those two times I either crash with unexpected error No OpenGL context found in the current thread; Unknown error; or I get into the game and when I try to load my world (New 2.1 world) it crashes.

errors include:
 Ticking block entity java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
Unexpected error java.lang.RuntimeException: No OpenGL context found in the current thread.

## Additional Information
[crash-2017-09-19_14.30.24-client](https://pastebin.com/UGNWe1Zz)
[crash-2017-09-19_14.39.28-server](https://pastebin.com/6q03wTZ3)

**Comment by RicardoTheCoder** [comment]
@shadowtam To fix the **ticking block entity** error you can follow this [tutorial](https://github.com/scalda/FoolCraft/wiki/Ticking-Block-Entity-fix-for-somethings-but-not-all-like-fluidcows). This will not fix all **ticking block entity** errors but most of them.

**Note that** this is mostly used on servers to fix that problem (and can generate other errors, so backup the world), but should work in single player too. However as stated in the forge config file, use at your own risk.

As for the OpenGL error I may be from your graphic drivers or something related to that.
