### ISSUE TITLE
Milking fluid cows failure

### ISSUE THREAD

**Issue by PaternoX** [scalda/FoolCraft#715]
Fluid Cows changing bucket type

- [X] I am running the latest version of FoolCraft
- [X] I am running FoolCraft via Curse/Twitch Launcher
- [X] I can reproduce this issue consistently
     - [X] In single player
     - [ ] In multiplayer
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

When i attempt to milk some types of fluid cow, the bucket changes from a vanilla minecraft bucket to a minecraft forge bucket, and appears to be empty. These buckets can then not be used again. Is this a problem with some of the fluid cows? I cannot even tell what type of fluid cow they are without milking them :/

crafted a vanilla bucket, attempt to milk said fluid cows (pale white coloured) and bucket changes from minecraft to minecraft forge bucket, appearing empty but unusable

## Additional Information
![2017-09-19_10 55 18](https://user-images.githubusercontent.com/28237849/30586870-48753c2e-9d29-11e7-9eaf-c5671d413425.png)
![2017-09-19_10 55 07](https://user-images.githubusercontent.com/28237849/30586887-4bf6be2c-9d29-11e7-91bf-e0d6e5842d50.png)
![2017-09-19_10 55 01](https://user-images.githubusercontent.com/28237849/30586931-64f178b8-9d29-11e7-869e-71013eb743aa.png)

**Comment by RicardoTheCoder** [comment]
@PaternoX This is a problem with the Moo Fluids mod. So I made a fork of the mod and a fix for that, it also allows you to see the fluids of each cow and the time it takes for them to be milked again.

You can download the mod [here ](https://github.com/RicardoTheCoder/Moo-Fluids/releases) and replace it in your client (I will also suggest this to scalda). Note that all rights and credit belong to the original creator of the mod.

Besides that, I also made a fix for the buckets so you can get a working bucket back. Go to your scripts folder and edit the **00-recipes.zs** file, go to the end of the file and add this:
`recipes.addShapeless(<minecraft:bucket>, [<forge:bucketFilled>]);`

After that, any forge bucket you put on the crafting table will give you a normal Minecraft bucket. Be careful as you can lose buckets with liquids in it.

**Comment by PaternoX** [comment]
thanks very much, will get on that now :)

**Comment by Mrbysco** [comment]
@RicardoTheCoder You should make a pull request into the original repo that way Robrit can possibly pull it and upload a fixed version to curse.

**Comment by RicardoTheCoder** [comment]
@Mrbysco I will be doing that, just uploaded things to the Github to post here xD, thanks for the reminder though ;)

**Comment by scalda** [comment]
thanks for this @RicardoTheCoder i have added that forge bucket script to the pack for the next release.

@PaternoX feel free to close this if you think it's not needed anymore

**Comment by PaternoX** [comment]
might want to double check the bucket script, as the minecraft forge bucket stays in the crafting station when the vanilla bucket is removed, essentially duplicating the bucket

**Comment by RicardoTheCoder** [comment]
@PaternoX I forgot to mention that, sorry about that. Some cows were being generated wrongly, and after using the fixed mod they will be removed. It might happen to other fluids as well.

After my tests, I was able to find some of those roaming around the world. I can't guarantee that all will be spawning. If they don't perhaps there is a problem with the Fluid registration on the respective mod.

As for the script, here is an updated version that should fix that problem:
`recipes.addShapeless(<minecraft:bucket>, [<forge:bucketFilled>.noReturn()]);`

**Comment by PaternoX** [comment]
nice work :) currently in process of looking for those cows now ;)w

**Comment by RicardoTheCoder** [comment]
@PaternoX Thanks :) if you can't find those cows again, please send me a message and I will try to see if I can find the problem ;)

**Comment by PaternoX** [comment]
well ive spent all afternoon searching, n ive found everything from obsidian to mushroom stew, but no manasteel or terrasteel :/

**Comment by RicardoTheCoder** [comment]
@PaternoX I will have a look into that and try to see if something can be done within the mod or if it is a problem with the fluid registration. Also I will talk to the mod creator and see if a better solution can be found ;)
