### ISSUE TITLE
Suggesting some fixes and changes for the pack

### ISSUE THREAD

**Issue by RicardoTheCoder** [scalda/FoolCraft#716]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

### Fixes
As stated in the discussion on the issue #705 the mod EnderIO seams to be creating incompatibilities with the drops of both the EnderDragon and the Wither, as such I found a fix that works on the drops for the Overworld (it doesn't work when killing the Wither in the nether).

**How to fix it:** add to **04-Loot-entitiesbossdragon.zs** this line:
`dragon.removePool("Ender IO");`

And to the **04-Loot-entitiesbosswither.zs** this line:
`wither.removePool("Ender IO");`

**EDIT:** Apparently this actually fixes the problem in all dimensions, I had a server-side mod conflicting with it, with a clean install and this fix it seems to drop everywhere.

Also as stated in the discussion on the issue #715 moo fluids is giving some problems, to this I also made two fixes that I would like to recommend:

> This is a problem with the Moo Fluids mod. So I made a fork of the mod and a fix for that, it also allows you to see the fluids of each cow and the time it takes for them to be milked again.

You can download the mod [here](https://github.com/RicardoTheCoder/Moo-Fluids/releases). Note that all rights and credit belong to the original creator of the mod.

**Note:** This version also makes cows ready to be milked when they spawn.

> Besides that, I also made a fix for the buckets so you can get a working bucket back. 

add this to **00-recipes.zs**:
`recipes.addShapeless(<minecraft:bucket>, [<forge:bucketFilled>.noReturn()]);`

**Note that:** any forge bucket you put on the crafting table will give you a normal Minecraft bucket. This may cause you to lose buckets with liquids in it, if you are not careful. It can also be seen as a way to destroy unwanted liquids.

### Additions / Changes
A recipe for the Creative Storage Upgrade (An upgrade for drawers that makes them store infinite amounts of items):
[The Recipe](https://pastebin.com/GAACPhtk)

Change it's name to match the pack:
`<storagedrawers:upgradeCreative:0>.displayName = "Fool's Storage Upgrade";`

And if you find suitable a recipe for the end portal frame, so a portal can be created anywhere (this may still require you to go to the end), this is the recipe I would suggest:
`recipes.addShaped(<minecraft:end_portal_frame>, [[<thermalfoundation:material:167>, <thermalfoundation:material:167>, <thermalfoundation:material:167>], [<minecraft:end_stone>, <minecraft:ender_eye>, <minecraft:end_stone>], [<minecraft:end_stone>, <minecraft:end_stone>, <minecraft:end_stone>]]);`

**Comment by scalda** [comment]
I thanks for these i will get the file changes made. but as for moofluids that's not something i am going to be able to merge into the pack as the file wouldn't be available on curse. if you could get the fixes merged into the main mod then great

**Comment by RicardoTheCoder** [comment]
@scalda Just a quick update about the fix for the Wither and EnderDragon drops (I also made an edit to the main post for future reference)

Apparently, my fix actually fixes the problem in all dimensions, I had a server-side mod conflicting with it, with a clean install and this fix it seems to drop everywhere.

This server-side mod is "SpongeForge" so the "move too quickly" error gets fixed, after removing it everything works fine (the fix on the scripts it still needed).

I actually found other problem during testing, which is when killing the Wither with a "Sword of the Cosmos" sometimes it bugs with the LootBags, gives an error and doesn't drop anything, but it is a rare thing to happen. (I can make a new issue post about this if you want)

**Comment by ranmas** [comment]
The Moo fluids update here deletes at least 4 cows for some reason.  Demon Metal, Elementium, Manasteel and Terrasteel cows get nuked when using your update.  Tried loading a few different backups and each time I used the updated moo fluids those cows would get nuked and after trying for 10 minutes or so with a spawner I have yet to see one of them respawn.

**Comment by RicardoTheCoder** [comment]
@ranmas You are right, but that isn't a problem in the fix I made. The source code from the author's github isn't obtaining fluids correctly, and because of that some cows get erased when they are placed or spawned into the world. However I will be releasing an alternative to this as soon as possible. I will get back to you when I have that.

**Comment by scalda** [comment]
thanks for the help @RicardoTheCoder

**Comment by RicardoTheCoder** [comment]
@ranmas You can find a better solution to the Cow problems in this issue/suggestion I just posted #771.

**Comment by scalda** [comment]
ok all these changes have made it into the next version of the pack for foolcraft thanks again
