### ISSUE TITLE
Viaducts Crashing game

### ISSUE THREAD

**Issue by PlerpIsaiah** [scalda/FoolCraft#717]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When i try to use the thermal dynamics viaducts, my game crashes

**Comment by scalda** [comment]
please post at the correct github

**Comment by PlerpIsaiah** [comment]
How is this the wrong github???

**Comment by scalda** [comment]
Because that is mod specific not pack specific
