### ISSUE TITLE
Tinkers block

### ISSUE THREAD

**Issue by Kelitore** [scalda/FoolCraft#718]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I know it was reported under a pre-chiseled block of metal, but when I put aluminum ore into the tinkers smeltery I get caution chiseled aluminum blocks when I pour into casting basin. I don't know if this is a separate issue or the same problem with it choosing a block type (issue #584), but I thought I'd mention it in case it is different or if you need to resolve each ore that does it.

## Reproduce Steps
Pour aluminum into casting basin.

## Additional Information
![2017-09-20_09 09 09](https://user-images.githubusercontent.com/32132141/30645611-3fc854f6-9de4-11e7-892e-c3582e73e265.png)
![2017-09-20_09 09 14](https://user-images.githubusercontent.com/32132141/30645635-4cface4c-9de4-11e7-89ff-2923de03d29e.png)
![2017-09-20_09 09 44](https://user-images.githubusercontent.com/32132141/30645638-501dddf8-9de4-11e7-81ac-aef7ab1bc4b6.png)
![2017-09-20_09 09 57](https://user-images.githubusercontent.com/32132141/30645644-52e8f9c8-9de4-11e7-857e-c976e68c63e3.png)

**Comment by PlerpIsaiah** [comment]
O get that when i make electrum blocks, at least if it's a bug its still useable. Not as if it turned it into bedrock.

**Comment by Kelitore** [comment]
It is true that it is still usable, but it's better they know about it than letting it go.

**Comment by scalda** [comment]
This is just the way tinkers assigns it's block recipes
