### ISSUE TITLE
Mod Suggestion: UniDict

### ISSUE THREAD

**Issue by ChromeMystic** [scalda/FoolCraft#719]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
There are many recipes that create the same Item from difference Mods (ie Railcraft or TE Ingots/Blocks). With the small mod of UniDict (https://minecraft.curseforge.com/projects/unidict) this can be tweaked, so that the base result is the same no matter what source it comes from, this can seriously reduce clutter without having to run all ingots into Storage Drawers first.

**Comment by scalda** [comment]
this was added back in 2.3 version of the pack thank you for the suggestion
