### ISSUE TITLE
Thermal Expansion

### ISSUE THREAD

**Issue by Gh0stT3rr0r** [scalda/FoolCraft#72]
Hello,

Don't really know if this is technically an issue, but all the machines in Thermal Expansion are unable to be upgraded due to a missing "Upgrade" GUI box. I wanted to use this for creating lava since the only real method to do so is using the Magma Crucible machine, however, I can't effectively use said machine when there is no upgrade slot option. Kind of curious as to how I can go about getting said option implemented into the game.

Thanks.

**Comment by CriticalMole** [comment]
if I recall I think you are meant to hold the upgrade in your hand and Shift Right Click the machine to upgrade it

**Comment by Gh0stT3rr0r** [comment]
Shift right-click doesn't do anything unfortunately.

**Comment by CriticalMole** [comment]
ok if it isnt working properly it may be worth going to the Thermal Expansion support, as it is an issue within their mod, not the pacj as a whole :(
