### ISSUE TITLE
FPS issues (10-20 FPS MAX) in Foolcraft 2

### ISSUE THREAD

**Issue by Jaywoo2002** [scalda/FoolCraft#720]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [X] I am requesting help with installing or running the pack

Game runs consistently between 10 and 20 FPS.  I have tried with/without optifine, with without betterFPS, done multiple installs, messed with video settings and tried closing other programs.  I have AMD R9 390X Graphics Card, AMD FX9590 Black Edition processor (of which 30% or less is being used while in game) and 32 Gigs of ram 6 of which are allocated in the steam launcher. Server is 3GB hosted by cubed host.

## Reproduce Steps
Launch Foolcraft

**Comment by Jaywoo2002** [comment]
Went back to Optifine, turned Terrain Animations Off.  at a stable 60 FPS now

**Comment by scalda** [comment]
ok thats great @Jaywoo2002
