### ISSUE TITLE
Title Page displays "Pack Version 2.0"

### ISSUE THREAD

**Issue by kpeckett** [scalda/FoolCraft#721]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
On the title screen, with the options for Singleplayer, Multiplayer, .etc, the text in the lower left, underneath the list of mods loaded and installed, the pack version is listed. In 2.1, it says 2.0.

## Reproduce Steps
1. Launch Foolcraft as normal.
2. Look in the lower-left corner of the title screen

## Additional Information
From Twitch Launcher:
![image](https://user-images.githubusercontent.com/3105099/30656684-ccd09c1c-9e2c-11e7-8523-2626a94ec97f.png)

In Minecraft:
![image](https://user-images.githubusercontent.com/3105099/30656971-cbde38b8-9e2d-11e7-9d55-921fb7ded95b.png)

**Comment by scalda** [comment]
thank you this is now fixed for the next version of the page
