### ISSUE TITLE
Blaster? I barely know her! Quest is broken. Request a file to fix it so my server can be updated.

### ISSUE THREAD

**Issue by Venrexx** [scalda/FoolCraft#722]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

Blaster? I barely know her! quest is incompleteable. Would like to request the file that fixes this.

**Comment by scalda** [comment]
the book will hopefully be fixed in the next version i have had to change a load of stuff but thank you for being patient with me
