### ISSUE TITLE
Infinity liquid issues

### ISSUE THREAD

**Issue by daddy77gaming** [scalda/FoolCraft#723]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

I cant cast infinity blocks or ingots anymore in any way (thru tinkers smeltery and liquid funneled into casting bassin). Infinity in the smeltery only displaying in nuggets (which dont exist)

closed and opened game lots of times, restarted system etc.. 

## Additional Information

![2017-09-21_03 41 55](https://user-images.githubusercontent.com/31905330/30675181-5fa963be-9e7f-11e7-8c6a-c8671d8856c6.png)

**Comment by ChromeMystic** [comment]
Scalda nerfed the ingot casting for infinity with 2.1. So it is working as intended :(

**Comment by ljnskywalker** [comment]
If you want to fix it and add it back in remove two lines in the scripts folder from the file 03-tinkers.zs. 

```
mods.tconstruct.Casting.removeBasinRecipe(<avaritia:block_resource:1>);
mods.tconstruct.Casting.removeTableRecipe(<avaritia:resource:6>);
```

**Comment by daddy77gaming** [comment]
thanx, I know i have more then enough infinity blocks in current save.. just wondered if it was intentional or a bug :)
I do think its actually good, cause avaritia is supposed to be hardcore.

**Comment by ChromeMystic** [comment]
It is, but it is kinda against the rest of the pack. Most of it seems to be about being as OP as possible :) Heck I decided to build a 255x255x45 dome just to build a part of my base from y0. I had to wait 2 days with a chunkloaded builder but I had it done quite early.... So I think avarita is a bit to hardcore as it is now, but with the tic cow it might be a bit to easy.

**Comment by scalda** [comment]
These are disabled because it negates the need to do the avarita stuff so much and it will remain disabled at the request of iskall himself
