### ISSUE TITLE
Porting causes energy acceptor (AE2) to break

### ISSUE THREAD

**Issue by daddy77gaming** [scalda/FoolCraft#724]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

using the /home command and the nether pet break my energy acceptor (ae2) each and every time its being used.. 

3rd time the acceptor was gone if figured out why it happened.. did some more porting both with /home (you need to be far enough away for home chunk to be unloaded) and with the nether pet.. each time the acceptor was broken and floating waiting to despawn. Now trying to set up a chunk loader and try to reproduce again.

**Comment by daddy77gaming** [comment]
with a chunk loader setup .. didnt break on /home.. will now try and explore for 30mins, then port back

**Comment by ChromeMystic** [comment]
In general it is advisable to keep your ae system chunkloaded

**Comment by scalda** [comment]
yeah this is a chunk loading issue
