### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by hexangle** [scalda/FoolCraft#725]
is it right that the sawbench isnt availeble in this pack and on the server it is if yes why isnt it in it

**Comment by jestesared** [comment]
You kinda gave literally no information to go off of here. What sawbench are you even referring to?

**Comment by hexangle** [comment]
The one from architectural craft I sax iT in Xs video

**Comment by jestesared** [comment]
I don't think you were watching his current foolcraft series then? Because while yes, ArchitecturCraft was in Foolcraft season 1, it is no longer in Foolcraft season 2.

**Comment by hexangle** [comment]
Yeah I know but is iT possible to play that one from Seasick 1 or not

**Comment by hexangle** [comment]
Season*

**Comment by Necro9227** [comment]
Foolcraft 1.4.8 and prior Versions would be the season 1 modpack, and 2.0.0 and higher is season 2.

**Comment by jestesared** [comment]
On the launcher you would just need to select version 1.4.8

**Comment by hexangle** [comment]
Thank you Guys so much and sorry for disturbing you
