### ISSUE TITLE
Update Good Ol' Currency Mod to 1.2.2

### ISSUE THREAD

**Issue by BeardlessBrady** [scalda/FoolCraft#727]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Hey, Would just like to inform you that some major polishing has been done to make Good Ol' Currency a better experience. Thus whenever you update the pack I hope you update the mod as well. Thanks

**Comment by scalda** [comment]
hi thanks for letting me know
