### ISSUE TITLE
Mod Suggestion: Wireless Crafting Terminals (For AE2)

### ISSUE THREAD

**Issue by calmelb** [scalda/FoolCraft#729]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

I have an idea for an additional mod to be put into Foolcraft. The mod is called Wireless Crafting terminals and it adds wireless crafting terminals for AE2. (Link: https://minecraft.curseforge.com/projects/wireless-crafting-terminal)

This would work quite well with the modpack as you can now craft using the terminals instead of just accessing items.

**Comment by scalda** [comment]
added to our potential list
