### ISSUE TITLE
Cant Link colossal chest

### ISSUE THREAD

**Issue by ErnstCreemers** [scalda/FoolCraft#73]
I can link my 5x5 colossal chest with 1 core.. My tinkers tools wont connect. can anyone help me out?

**Comment by scalda** [comment]
You need to connect it to a chest interface

**Comment by ErnstCreemers** [comment]
i made a interface. chest with cobble around it. placed it into the 5x5 and shift right clicked again. no results :(

**Comment by CriticalMole** [comment]
not sure if it is a thing with the chest mod, what we devs have done on our server is link to a diamond chest which feeds into the colossal chest via a conduit

**Comment by Razew** [comment]
Did you use Alumite or Enderium when crafting your tools?
Those two materials add "Global Traveler", which allows you to create such a connection to an inventory.

**Comment by scalda** [comment]
@ErnstCreemers Have you solved this? if so can you post your solution and close the issue

**Comment by ErnstCreemers** [comment]
Have not het solved it gonna try razew methode could you perhaps give me
some more info of what my pickaxe should be made off

Op 31 mrt. 2017 12:06 schreef "Scalda" <notifications@github.com>:

@ErnstCreemers <https://github.com/ErnstCreemers> Have you solved this? if
so can you post your solution and close the issue

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/scalda/FoolCraft/issues/73#issuecomment-290673074>, or mute
the thread

**Comment by Razew** [comment]
@ErnstCreemers You need one tool part of your Tinkers tool to be made out of **Alumite**, or **Enderium**; to get the **Global Traveler** "ability".

I suggest taking a look at the Tinkers' Construct book, **Materials and You** _(in-game)_.

**Comment by ErnstCreemers** [comment]
Oké get it can be closed


Op 31 mrt. 2017 20:09 schreef "Razew" <notifications@github.com>:
