### ISSUE TITLE
UnNamedBlock causing crashes

### ISSUE THREAD

**Issue by SpeedSlider** [scalda/FoolCraft#730]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
First; yes I was an idiot and second I know it may not be the mudpack fault but a poorly coded mod that you are not responsible for. However, since I can't find unnamed item in JEI I don't know what added it and since it wasn't crashing me anymore I wanted to save it in case it was some cool future loot. Oh well.

I found an item called unnamedblock in a Roguelike Dungeon loot chest. When I pulled it from the chest into my hot bar inventory with Optifine loaded it crashed me so I disabled Optifine and it was fine. It shows up with the missing texture texture (magenta and black checker pattern). It does not crash the game in a vanilla chest or hermitron chest, but appears to crash the game in RFTools Modular Storage.

## Reproduce Steps
You have to put the unnamedblock item in an RFtools modular storage; your game should crash.
Any time you try to open up the modular storage unit your game will crash.

## Additional Information
[crash-2017-09-23_07.24.36-client.txt](https://github.com/scalda/FoolCraft/files/1326503/crash-2017-09-23_07.24.36-client.txt)

**Comment by SpeedSlider** [comment]
![2017-09-27_16 17 34](https://user-images.githubusercontent.com/25437944/30935688-6db40bb0-a39f-11e7-89e1-5a995a18c3ad.png)

I was able to remove the items from the modular storage using a hooper and normal chest. I uploaded a screenshot which shows the minecraft id number. 4918:90

**Comment by scalda** [comment]
ok looks like it was a bugged out item from the chickens mod i'm glad you could sort it.
