### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by RizZeRx** [scalda/FoolCraft#731]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
I would like to play with my friend on server that I'm bout to run but it doesn't work properly, there is an error that I put into pastebin downthere 

## Additional Information
https://pastebin.com/0mi3nn2m

**Comment by scalda** [comment]
looks like a java issue, have you been able to get this to run since you posted this issue?

**Comment by scalda** [comment]
no response in 13 days, will close the issues if the problem persists please open a new issue
