### ISSUE TITLE
InvTweaks sorting error with Colossal Chest

### ISSUE THREAD

**Issue by johnwolf01** [scalda/FoolCraft#732]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
pressing any sorting button while attempting to sort colossal chest (5x5x5)gives error and sorting fail.
Only the row 1 up to row 119 are sorted, any other rows following that is not and error are given.

## Additional Information

17:46:34 | inventorytweaks | Client thread | info | Default sorting.
-- | -- | -- | -- | --
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: java.lang.ArrayIndexOutOfBoundsException: 999
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at invtweaks.InvTweaksHandlerSorting.move(InvTweaksHandlerSorting.java:471)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at invtweaks.InvTweaksHandlerSorting.defaultSorting(InvTweaksHandlerSorting.java:436)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at invtweaks.InvTweaksHandlerSorting.sort(InvTweaksHandlerSorting.java:153)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at invtweaks.InvTweaksGuiSortingButton.func_146116_c(InvTweaksGuiSortingButton.java:64)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:320)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at org.cyclops.cyclopscore.client.gui.container.ScrollingGuiContainer.func_73864_a(ScrollingGuiContainer.java:127)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at org.cyclops.cyclopscore.client.gui.container.ScrollingGuiContainer.func_146274_d(ScrollingGuiContainer.java:111)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at java.lang.reflect.Method.invoke(Method.java:483)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaks:logInGameError:479]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
17:46:34 | net.minecraft.client.gui.GuiNewChat | Client thread | info | [CHAT] InvTweaks: [ERROR] [3] Failed to sort container: 999 (l471 in HandlerSorting.java)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: java.lang.ArrayIndexOutOfBoundsException: 999
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at invtweaks.InvTweaksHandlerSorting.move(InvTweaksHandlerSorting.java:471)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at invtweaks.InvTweaksHandlerSorting.defaultSorting(InvTweaksHandlerSorting.java:436)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at invtweaks.InvTweaksHandlerSorting.sort(InvTweaksHandlerSorting.java:153)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at invtweaks.InvTweaksGuiSortingButton.func_146116_c(InvTweaksGuiSortingButton.java:64)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:320)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at org.cyclops.cyclopscore.client.gui.container.ScrollingGuiContainer.func_73864_a(ScrollingGuiContainer.java:127)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at org.cyclops.cyclopscore.client.gui.container.ScrollingGuiContainer.func_146274_d(ScrollingGuiContainer.java:111)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at java.lang.reflect.Method.invoke(Method.java:483)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
17:46:34 | STDERR | Client thread | info | [invtweaks.InvTweaksGuiSortingButton:func_146116_c:67]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Pr0ti0us** [comment]
I too get errors from inv tweaks when trying to sort a col chest.

**Comment by scalda** [comment]
this is because the colossal chest is just too big for inventory tweaks to sort, so it throws errors instead
