### ISSUE TITLE
Lasers shoot through anything

### ISSUE THREAD

**Issue by ranmas** [scalda/FoolCraft#733]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Lasers will shoot through anything and everything all the way out to their max range.  No matter how many or how few blocks are in the way.

Tested by building a cage and putting a cow in it.  Then placing blocks down and shooting through them until the shorter ranged laser couldn't hit the cow any more.  Then continued on with a higher ranged laser.

## Reproduce Steps

Same as above, build a laser and shoot a caged target through material of choice.

**Comment by 3jlowes** [comment]
I believe this feature is working as intended.

**Comment by scalda** [comment]
this is a intended feature
