### ISSUE TITLE
My FoolCraft server will run, but then other people are unable to join it.

### ISSUE THREAD

**Issue by HeroicosHM** [scalda/FoolCraft#734]
FoolCraft Server Troubleshooting

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
I have successfully downloaded the FoolCraft server files onto my home desktop with the intention of running it for my friends to use, however neither I, from my laptop in the same house, nor my friends can join the server. I have tried many different solutions but nothing has worked for me at all.

## Reproduce Steps
1) I installed FoolCraft through the twitch/curse launcher.
2) I searched "FoolCraft Server Files" on the interwebs.
3) I found the matching server file (FoolCraft 2.1) and downloaded it.
4) Extracted zip file into a folder, and ran the server through the provided run.bat file. (The server runs completely fine on its own, and everything seems to be in order
5) Tried joining the server from the other computer, and the server is completely unable to be found when trying to connect through ip (which I am sure is correct) or localhost (which should also work).

**Comment by Schaefer78** [comment]
Firewall needs to be configured on server/desktop and most likely router if you want to achieve something like this.

Little help to start u on your way: https://www.planetminecraft.com/blog/host-it-yourself---windows-firewall/

**Comment by HeroicosHM** [comment]
I have allowed the firewall to accept incoming activity from the port, but still my computer can not find the server. Again, the server runs just fine, but the other computer I am trying to connect to it from will not recognize it, whether I connect by IP or localhost.

**Comment by scalda** [comment]
this is best for you google search not a pack problem sorry i can't help more
