### ISSUE TITLE
Foolcraft 2.0 can't choose custom world, reverts to Biomes a Plenty after I change anything

### ISSUE THREAD

**Issue by Jamesdwi** [scalda/FoolCraft#735]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

Running Latest. 

When you choose to create a custom world, and modify anything, the game goes back to biomes of plenty, can create a more vanilla type world with "Default World" but no modifications.

**Comment by scalda** [comment]
i have been able to do this as i use default/flat worlds for testing of things. so perhaps reinstall the pack
