### ISSUE TITLE
minefactory planter crashing with biomes o plenty dirt

### ISSUE THREAD

**Issue by utterablevenus1** [scalda/FoolCraft#736]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
i made a planter from minefactory and the second i powered it my game crashed and i can no longer open the world. i live in a prairie which uses silty dirt instead of normal dirt, and thats what it looks like caused it in the crash report

## Additional Information
https://pastebin.com/B817ttKF

**Comment by scalda** [comment]
yes i have found this issue as well. it looks like MFR doesn't recognise that the BOP grass can be used for planting
