### ISSUE TITLE
Duping in FoolCraft version 2.1

### ISSUE THREAD

**Issue by 3jlowes** [scalda/FoolCraft#738]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Duping is an issue. Not much detail to put here. The machine is basic.
https://gyazo.com/a54542a24307f05a95322c4fc07ad0f5
Thats the machine in action

Here is a screenshot of the machine
https://imgur.com/a/Tj2kj

## Reproduce Steps
To reproduce, follow the gif exactly. It shows you were to put the item, and where it comes out. Building is straightforward. look at the image.

**Comment by scalda** [comment]
yes this is an old bug that has not been fixed by the mod author even
though it has been reported

**Comment by 3jlowes** [comment]
@scalda is there anything I can do to temporary fix this?

**Comment by scalda** [comment]
disable the hopper belts

**Comment by Br0k3nWings** [comment]
I also have a duping to report. I am running version 2.1 single player launched via twitch.

twice now I was at the Tinker's tool station and was doing something to the tool/weapon when I had to terminate my gameplay IRL. Upon restarting later I found the item in my hotkey bar and also on the tool station. Now that I am writing this I am seeing this could be a mod issue and not a pack issue.
