### ISSUE TITLE
Constant server lag spikes, and rare time outs

### ISSUE THREAD

**Issue by 3jlowes** [scalda/FoolCraft#739]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

Ive troubleshooted, but can not find anything. My server is getting lag spikes, and all the console says is cannot keep up. I have 8gb of ram, and running on a xeon e5. specs are not the issue. Is foolcraft just a laggy pack?

Its not lag caused by exploring either. Any ideas/ help is greatly appreciated

**Comment by Schaefer78** [comment]
Have u checked the fml-server-latest.log and looked for memory leaks? could have a bad world. Other facters could be slow ram speed, i've found best cpu for a server is 4.x Ghz, SSD disk. If this is also a VPS hosted somewhere could be the issue

**Comment by 3jlowes** [comment]
[18:51:01] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save FoolCraft
[18:51:15] [Server thread/DEBUG] [FML/]: The world 70c10db3 (FoolCraft) may have leaked: seen 800 times.

[18:51:46] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save FoolCraft
[18:51:56] [Server thread/DEBUG] [NotEnoughItems/]: Unloading Player: 3jlowes
[18:52:05] [Server thread/DEBUG] [FML/]: The world 70c10db3 (FoolCraft) may have leaked: seen 805 times.

Does that mean memory leak?

**Comment by notmark** [comment]
This typically happens when you do not allocate enough RAM to Minecraft. You should allocate at least 6GB to it with this pack.

**Comment by LemADEC** [comment]
Memory leaks are not fixed by adding more RAM. There's a buggy mod in the modpack causing, we need to find it.

**Comment by scalda** [comment]
i would suggest you install tickprofiler and run it to determine what this could be, i run 3 foolcrafts servers with multiple players and I have not once seen this message pop up since FC 2.0 launched
