### ISSUE TITLE
Crash/Corrupt Worlds with Architecture Mod + Tinkers Crafting Table

### ISSUE THREAD

**Issue by mickeason** [scalda/FoolCraft#74]
**Summary**
Placing Biomes of Plenty ash block slabs created by the Architecture Sawbench into a Tinkers Construct crafting table crashes/corrupts worlds. I have been able to reproduce this four worlds in a row. Unfortunately the first one was my main world that I've put HOURS into *rip*

**Error Message After Crash**
"The game crashed whilst tesselating block in world
Error: java.lang.RuntimeException: No OpenGL context found in the current thread."

**Crash Report**
attached

**Steps To Reproduce:**
1.) Create an ash block from Biomes of Plenty (volcano biome)
2.) Architecture Sawbench - Create 2 half slabs out of the ash block
3.) Tinkers Crafting Bench - Placing the 2 half slabs into the crafting bench as if combining them back into a block crashes to desktop. The last time it happened immediately with only one slab.

[crash-2017-03-24_14.19.17-client.txt](https://github.com/scalda/FoolCraft/files/868975/crash-2017-03-24_14.19.17-client.txt)

**Comment by scalda** [comment]
If you have optifine installed remove it and reload the world, it is a
render problem

**Comment by mickeason** [comment]
Thank you for the quick reply. Your solution is 100% correct. You're a life saver.

For anyone else experiencing this, I did the following to open my world again:
1.) removed Optifine
2.) loaded world
3.) removed slabs from crafting table
4.) added Optifine back
5.) loaded world
6.) profited off of Scalda being a boss!

Take care. This issue is closed.
