### ISSUE TITLE
Foolcraft crashes on loading screen 100% of the time

### ISSUE THREAD

**Issue by Smackdye** [scalda/FoolCraft#740]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
Fool craft stops loading and crashes every time at the ModelLoader baking

## Reproduce Steps
I load it in from twitch, it loads fine then at 43/61 every time my fsp drop to 2 and crashes, I've allocated 3 gigs to minecraft, all other packs ( 1.12.1) load fine, I've tried grabbing the error code but crash report won't open. 
Latest Java loaded, latest drivers updated Ram allocated

**Comment by gildiarz** [comment]
I think you need more ram. For me, 4+gb works fine.

**Comment by hippietilley** [comment]
The pack says it requires between 6 and 8 gigs of RAM.

**Comment by Hunter-The-Gamer** [comment]
I'm having the same issue, here's the crash report:

[crash-2017-09-25_20.44.45-client.txt](https://github.com/scalda/FoolCraft/files/1331360/crash-2017-09-25_20.44.45-client.txt)
