### ISSUE TITLE
I can't open foolcraft 2.1

### ISSUE THREAD

**Issue by CroDerPanda** [scalda/FoolCraft#742]
When I try and start foolcraft through the twitch launcher it comes up with an error saying that "this app can not be run on your pc" if someone knows how to fix this issue, I  would greatly appreciate it

**Comment by hippietilley** [comment]
How much RAM do you have?

**Comment by Schaefer78** [comment]
Have Java 1.8 installed?

**Comment by Hunter-The-Gamer** [comment]
I'm having a similar problem, except it crashes towards the end of it's loading. It gives the following crash report:

[crash-2017-09-25_20.44.45-client.txt](https://github.com/scalda/FoolCraft/files/1331339/crash-2017-09-25_20.44.45-client.txt)

I have yet to modify the pack, other than the profile name

**Comment by janf3** [comment]
@Hunter-The-Gamer 

Your Foolcraft instance runs out of memory, try giving it 4-5 GB

> Time: 9/25/17 8:44 PM
> Description: Initializing game
> 
> java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by Hunter-The-Gamer** [comment]
@Jan

Ok, could you provide me with a JVM argument to do that? There are a lot of
arguments that I don't know what they do, and I don't want to mess anything
up

If not thanks for the help, it is much appreciated ☺️

**Comment by janf3** [comment]
The JVM argument for the maximum memory allocation is `-Xmx` for example
```
java -Xmx6144m
java -Xmx6g
```

If you are using the Twitch App you should modify it within the Settings under Minecraft.

**Comment by Hunter-The-Gamer** [comment]
Yay it worked, thank you so much!
