### ISSUE TITLE
Foolcraft 2 fps loading from launching game start and beyond

### ISSUE THREAD

**Issue by GenBlazkow** [scalda/FoolCraft#743]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Well i am using twitch launcher, i have made sure the mod pack has 8GB of my ram to use and run on yet i am getting 20 mins to load to main screen and about 2fps from the main load screen to creating a world and to having the world loading and it does not improve and the game loads and goes non responsive every click. i have created 3 different worlds no improvement and no crash report to post as it has not crashed. to the point i installed a extra mod "optifine" that does 0 to the problem stays the same

## Reproduce Steps

click play on twitch launcher
games loads and hangs for 20mins before entering main splash screen
game does not register mouse click and hangs on non repsonsive 
click single player
game hangs
game goes non responsive
screen changes 
game hangs on non responsive
click create new world
game dont register for 1 min ish
game hangs
screen changes 
game changes to new world options
type new name in
don't respond
game hangs
name chages
click create world
game hangs for 2 mins
world creates for 10mins
see gui and world is black
game has maybe 2fps loading
game hangs on and off some sounds play but everything stays for 20 mins 2fps no improvements 

## Additional Information

can screenshot loading lagg
or show crash log as no crash happens

**Comment by GenBlazkow** [comment]
basically for a laptop with 12gb memory the pack is unplayable :(

**Comment by hippietilley** [comment]
If you are running Windows, see if you can pull up the Task Manager and see how heavy the load on your processor is.

**Comment by GenBlazkow** [comment]
10% on cpu 80% on ram 25% on disk

**Comment by hippietilley** [comment]
Then I would uninstall Twitch and reinstall it. It looked like it might be getting hung up at the processor, but I would suspect a higher cpu use in that case.

**Comment by GenBlazkow** [comment]
alright i shall try that

**Comment by Schaefer78** [comment]
GPU? As weird as it sounds most laptops use onboard gpu's and i've experienced the same issue in the past on a MBP.

**Comment by GenBlazkow** [comment]
i have 2 gpu's on my laptop anyway i uninstalled twitch launcher and re installed it, no change at all still the same before

**Comment by mandapandapop** [comment]
I am having the same issue on my PC.  Allocated 8 GB on Twitch for Foolcraft, the world loaded and immediately started with 1-3 FPS.  I waited a while for generation but the FPS persisted fluctuating between 1 - 3 FPS.  I also tried altering the allocation between the suggested optimal levels but it didn't help.
I tried decreasing the graphics etc and lowered the render distance to 9.  I tried creating a new world, with the same issue and also gave windowed mode a try too.  
The only thing that increases the FPS is bringing up the menu, it shoots up to 60FPS and almost immediately loads in all the terrain but as soon as I click 'back to game' the FPS drops back down to 2.
I have uninstalled Foolcraft and reinstalled it.  I guess I will try the same with Twitch, but I doubt that is the issue. 

CPU hits 32% Max,  RAM is at 33%,  Disk 2%

**Comment by mandapandapop** [comment]
Uninstalled twitch and retried, no improvement. I also tried using default land generation instead of biomes of plenty but the issue remains.

**Comment by Schaefer78** [comment]
FPS in this case is most likely GPU. If you are on desktop @mandapandapop upgrade your drivers. If you are on a laptop there not much u can do besides possibly going into the java settings for 1.8 and playing with allocation for java on the laptop and making sure java on the laptop runs with more ram on the system.

**Comment by scalda** [comment]
yeah, this is a hardware issue, not a pack issue, google is your friend. sorry for the lack of help
