### ISSUE TITLE
Server Chunk Loading Query

### ISSUE THREAD

**Issue by Collzy** [scalda/FoolCraft#744]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Is there any chance you could direct me to an official list of all the blocks that chunkload servers? there are a lot of chunks that should be unloaded but are causing lag.. and i can only think of chunkloaders or independent chunk loading blocks

## Reproduce Steps
Cant Reproduce... possibly mechanical users?

**Comment by janf3** [comment]
You can use the command `/ftb loaded_chunks_list` which will open up an ingame GUI showing all loaded chunks. Clicking on one of the entries will teleport you to the corresponding location. It will however not tell/show you the exact block which is loading those chunks.

There is also the command `/chunkloaders` which will open up a second window outside of Minecraft with an overview(map) of loaded chunks (red=loaded, yellow=block that loads the chunks).

In combination it should help you track down the blocks and loaded chunks. 
In general I would say:
- ChickenChunks Chunk Loader
- RFTools Builder
- Railcraft Worldspikes

ChickenChunks allows you to set a Per-Player-Limit as well as a chunks per loader limit via the config. 
For Railcraft I would just disable the WorldSpikes all together, people rarely use them. It also has a one-time config option to delete all of them.

RFTools will just load the one chunk it is currently mining/building in and then unload it. One can disable that but then you'd have to manually load all those chunks which would probably lead to people setting up a huge Chickens Chunk area causing way more problems.

Other then that I would restart the server at least once per day to get rid of _stuck_ chunks

**Comment by Collzy** [comment]
Thankyou, we have banned all chunkloaders... the question as more geared towards any blocks that independently chunkload

**Comment by scalda** [comment]
as far as i know there are no other loaders in the pack except the chicken chunks ones
