### ISSUE TITLE
No lootbags when witherboss is killed using woot

### ISSUE THREAD

**Issue by Twan23** [scalda/FoolCraft#745]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I made the woot multiblock with the wither, it drops netherstars, xp, sulfur and inferium essence, but no lootbags of any kind

**Comment by 3jlowes** [comment]
It does drop loot bags. take off your looting upgrades.

**Comment by Twan23** [comment]
Does not work

**Comment by JonathanLowe1** [comment]
Works for me

**Comment by kugr** [comment]
I also do not get loot bags, I've the farm running with a variety of set-ups. No upgrades, efficiency, and rate. 
Still nothing.

**Comment by scalda** [comment]
this all depends on when loot bags adds it's loot to the tables and when woot scans the tables, best bet is to delete the woot file in the root of the minecraft folder and restart the game and see if you can get anything
