### ISSUE TITLE
Hidden Icons when trying to craft/search something

### ISSUE THREAD

**Issue by PandaGOD82** [scalda/FoolCraft#747]
- [X] I am running the latest version of FoolCraft
- [X] I am running FoolCraft via Curse/Twitch Launcher
- [X] I can reproduce this issue consistently
     - [X] In single player
     - [ ] In multiplayer
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [X] I am requesting help with installing or running the pack

## Issue Description
Basicaly the icons of the items dont show up most of the times, but sometimes when i over specific items, all the items show up.

Its constantly with the same problem

## Additional Information
Hidden:
![image](https://user-images.githubusercontent.com/17859543/30871957-6bd6417e-a2e0-11e7-851c-e8d9cba9d2d6.png)

Showing: 
![image](https://user-images.githubusercontent.com/17859543/30871939-63adc40e-a2e0-11e7-9471-3d78f7f8f54c.png)

**Comment by svennieke** [comment]
iirc this is something to do with the modernwarfare mod, as i noticed as soon as any of the items from that mod are supposed to show everything goes invisible untill hovered over

**Comment by Twan23** [comment]
yes, this is a problem with the modern warfare mod

**Comment by scalda** [comment]
yes this is due to Modern warfare yet again

**Comment by scalda** [comment]
just sent them another message regarding this and the other issue we are having with viaducts

**Comment by scalda** [comment]
this will be fixed in 2.5 of the pack version as MW has fixed these bugs
