### ISSUE TITLE
Server memory leak

### ISSUE THREAD

**Issue by 3jlowes** [scalda/FoolCraft#748]
My server is experiencing constant lag spikes. I check the fml-server-latest.log and I see a bunch of this. "[14:35:34] [Server thread/DEBUG] [FML/]: The world 2d95f422 (FoolCraft) may have leaked: seen 6065 times." Is it something with the pack, or is it a hardware issue?
Here is a good portion of my fml-server-latest.log
https://pastebin.com/yju6bjXg
If you need to see anything more to help out let me know.

It is really driving me crazy. And my fellow server members are getting a little mad as well. Ive hosted many modded servers over the past years and have experienced nothing like this. 

The server is being hosted on my dedicated box. Xeon E5, 32Gb of ram (12gb put into the server)
One more thing. I see a lot of recurrent complex showing up in the server latest log. Is that the mod causing the issue?

**Comment by virtualadept** [comment]
I'm also running a server and I see the:

The world 4d6d9dd1 (FoolCraft) may have leaked: seen 3240 times.

I've also seen this happen on other modpacks, so to me its more of an annoying message than anything.  Its not causing lag spikes however on my end however (at least that have been reported to me).

As for the reccomplex errors, I get those as well when people are exploring and new chunks are being generated.  It looks like its trying to place an object which isnt supported by the terrain (ie: tree in the middle of ocean).

**Comment by scalda** [comment]
this is due to the loading and unloading of dimensions, this is a base MC issue not a pack thing sorry
