### ISSUE TITLE
Suggestion for additional mods for the pack.

### ISSUE THREAD

**Issue by planetWayne** [scalda/FoolCraft#749]
## SUGGESTION/HELP
- [X] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

I would like to suggest a couple of additions to the modpack that I think make a complementary addition which brings some new lighting block types to aid for better lighting and variety for controllable light blocks and a mod to add some random 'fun' objects.

ProjectRed - Lighting (Was Illumination) - Adds numerous light sources / blocks that are typically faster and more interesting that just simple vanilla Redstone Lamps - also can be made in the full variety of the Minecraft colour pallet. Also controllable by Redstone signals
ProjectRed - Base (dependancy of above)
ForgeMultipart ( dependancy of above)

OpenBlocks by OpenMod - as they say, adds few fun random blocks with no particular theme. Nothing in this that is OP but has nice things like targets and quick elevator blocks (its the targets that mainly interest me)
OpenModsLib (dependancy of above)

As a simple test, I have duplicated the FoolCraft pack in the Twitch client and was able to add all of the mods bar the ForgeMultipart, directly with the Twitch client. Although I've not done any extreme 'battle testing' of the additions, I have not run into any issues so far.

What I do find though is with the ProjectRed Lighting and a couple of blocks in OpenBlocks, they work very well with the Programmable Rednet controller that is a part of the Minefactory Reloaded set. Again, good way to add indicator lights etc to auto machines if needed.

Thanks for considering.
Wayne.

**Comment by 3jlowes** [comment]
ProjectRed i dont agree with. OpenBlocks I do.

**Comment by Necro9227** [comment]
ProjectRed is a bit too logistical for FoolCraft.
Open Blocks would be OK but so many of the blocks and features in it such as graves and elevator blocks were made into separate mods because it took so long to update to 1.10.

**Comment by planetWayne** [comment]
The reason for the Project Red (and only really the illumination mod) was for the variety of lighting blocks and lamps. Redstone controllable. Admittedly, not 'desk lamps' or the like but more industrial type lights and lamps (although looking at the new one I see lanterns now too!). But they also work nicely with the Minefactory Reloaded PRC's - hence the request.

**Comment by scalda** [comment]
we are not adding new mods to the pack anytime soon
