### ISSUE TITLE
Replace Modern Warfare with Infernal Mobs

### ISSUE THREAD

**Issue by SpeedSlider** [scalda/FoolCraft#750]
## SUGGESTION/HELP
- [ x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I would like to propose replacing modern warfare mod with infernal mobs it you are looking for extra mob difficulty and loot :P 

## Additional Information

https://mods.curse.com/mc-mods/minecraft/227875-atomicstrykers-infernal-mobs

**Comment by 3jlowes** [comment]
I would oppose this horrendous idea.

**Comment by Necro9227** [comment]
I would also oppose this suggestion, 
The point of Foolcraft is "To have as much fun as freakin' possible", and while Infernal mobs can be a fun challenge it can get really annoying when a mob with 5 or 6 attributes comes along and keeps wrecking you.

**Comment by SpeedSlider** [comment]
forget I mentioned it... Primarily I am trying to offer an idea to get rid of Modern Warfare which is just ruining the pack in my opinion... sorry I caused an uproar.
