### ISSUE TITLE
Suggestion for additional mod

### ISSUE THREAD

**Issue by useenzhekoay** [scalda/FoolCraft#751]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I would like to recommend a mod to make FoolCraft have foods that can eat and deco in world. So Fools can make world more decorative.

This mod is [1.10.2]Heat&Climate, a mod from Japanese forum but this mod have food that I feel most interesting and also other stuff like potion effect pendants and more. Scooter also a thing like horse in minecraft but it immune tnt explosion~ 

## Additional Information

Below link are screenshot from author: 
http://defeatedcrow.sakura.ne.jp/images/hac/tops/hactop_L.png

Below link are mod page:
http://forum.minecraftuser.jp/viewtopic.php?f=13&t=30947

Below link is the wiki from author:
http://defeatedcrow.jp/modwiki/HeatAndClimate

Below 2 links is the mod and its library jar in Github:
Mod: https://github.com/defeatedcrow/HeatAndClimateMod/releases
Lib: https://github.com/defeatedcrow/HeatAndClimateLib/releases

**Comment by useenzhekoay** [comment]
Addon on missing notes. I had tried to play this mod with current FoolCraft 2.1 until today (latest by 27 September)

**Comment by scalda** [comment]
unfortunately i will not be able to add this to the pack as curse would not except the pack for release sorry

**Comment by useenzhekoay** [comment]
Okay, noted and thanks for consideration~
