### ISSUE TITLE
MultiMc Error codes

### ISSUE THREAD

**Issue by Xesu** [scalda/FoolCraft#754]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Reproduce Steps

 https://paste.ee/p/LpSG5

**Comment by janf3** [comment]
According to the log you are using Java 9 which is not supported. Uninstall it and install the latest Java 8 version.

**Comment by scalda** [comment]
what @janf3 said
