### ISSUE TITLE
[BUG]MFR Stuffed Item 

### ISSUE THREAD

**Issue by Pr0ti0us** [scalda/FoolCraft#755]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
MFR Rancher keeps reporting as item stuffed. Its not the only one either the harvester has done it as well. The full set up is contained to a single chunk so chunk boundries are not the issue.

## Reproduce Steps

set up and power a rancher. place buckets in let ir run a few cycles and itll come back as Item stuffed. Breaking it free's the stuffed item.

## Additional Information

https://imgur.com/4m5zVLp

**Comment by Necro9227** [comment]
MFR machines get stuffed (back stuffed) with items nowhere to go or the backside is blocked. 
It also doesn't seem to accept ender io item conduits for item transport. 
my suggestion is use a chest behind the MFR machines to accept items then pipe out of the chest.

**Comment by Flekrad** [comment]
Often this happens if the conduit is connected to the Wrong side , of if it's connected to the side instead of to the Top

**Comment by BrisingrAerowing** [comment]
As the others have said, the Rancher's output is on the back. This took me embarrassingly long to figure out, then I found a bug with Colossal Chests that causes them to break and not actually remove blocks from them when broken, although that mostly seems to be related to issues with World Edit and copying / pasting completed chests (NBT corruption most likely).

**Comment by janf3** [comment]
Currently, MFR doesn't really work with pipes, ducts or conduits as far as items go. Just use a chest or other inventory as a buffer in between. The side doesn't matter, it can output into a chest on the top, left, right etc...

I do have a rancher that directly outputs fluids into a  Fluiduct on top of it. I assume Fluid Conduits would work too.

**Comment by scalda** [comment]
all MFR machines will auto output so if it has nowhere to go it will get stuffed up. best thing to do is like other people have said is to put some sort of buffer item in between the machine and your end goal
