### ISSUE TITLE
Foolcraft jitter/stutter

### ISSUE THREAD

**Issue by Doublehutch** [scalda/FoolCraft#756]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [X ] I am requesting help with installing or running the pack

## Issue Description
Hi All,

I'm new to this platform, but am pulling my hair out with regards to fixing crazy Jitter/stutter issues with foolcraft. Here are some notes and any advice would be great:

Running foolcraft 2.1 in single player on my computer.
Have installed the latest version of java
Computer specs below, but it looks as if I have onboard/discrete Radeon R7 200 graphics and then a Radeon R7 340 graphics card (I haven't opened the computer case to confirm this)
It looks like Foolcraft uses the R7 200 onboard graphics (thats what the f3 screen shows)
Downloaded AMD catalyst and updated the drivers. This only shows the R7 200 graphics - I can't see the R7 340. Updated the drivers too.
When i go into the device manager and update the driver for the display adapter it downloads the driver for the R7 340 and says that it is now up-to-date (doesn't show R7 200 in the device manager, but only shows the R7 200 in the AMD catalyst).
Tried allocating various amounts of RAM from 4- 8 gb.
the monitor (my TV) is plugged into the R7 340 graphics card by HDMI.
I have tried running it from the native launcher and the Jar and get the same lag issues.
plain minecraft from the launcher seems okay - but not super.
FPS on foolcraft ranges between 10 and 50.
Computer stats - its not the best, but should be able to run Foolcraft I think...

SPECIFICATIONS
Asus ROG M32BF
AMD Dual-Core A8-7600K APU with Radeon R7 onboard discrete Graphics (3.1 GHz, 1 MB cache)
16GB 1600MHZ DDR3 Memory
AMD Radeon R7 340 2GB Video Card (DVI,VGA, HDMI) OUT
10/100/1000/Gigabits Mbps Ethernet LAN
802.11 a/b/g/n/ac WALN & Bluetooth V4.0
Front I/O Ports: 1 x Headphone, 1 x Microphone, 2 x USB 3.0
Back I/O Ports: 6 x USB 2.0 , 1 x HDMI-Out, 1 x RJ-45 LAN, 1 x Headphone (Speaker Out), 1 x Microphone
6 -in-1 card reader: SD/ SDHC/ MS/ MS Pro/ xD/ MMC
Power Cable, USB Keyboard & Mouse
Windows 10 Home 64 Bit Pre-installed

Look forward to some assistance. Thinking maybe I need to reinstall the R7 340 and then disable the R7 200.

## Reproduce Steps
Not sure how to do this...

**Comment by JonathanLowe1** [comment]
This seems like more of a hard ware issue, and not directly related to issues with the pack

**Comment by Teddicus** [comment]
Yeah same issue i have:
i5 6600k cpu @ 4.1 ghz
16gb ddr4 ram
980ti 
I don't think it's a hardware issue. I believe it's something else some help would be appreciated.

**Comment by buddicus** [comment]
6700k with 64 GB of ram, 1080ti, If it's hardware then that would be insane Jonathan...

**Comment by Teddicus** [comment]
bump

**Comment by scalda** [comment]
hi i use a i7-4790 12gb ram and a gtx 750 to create and run this pack with a steady 120 locked frames and zero issues in a SP world, so if you have any problems with the pack like fps and such then it is the way MC is using your hardware, not the pack itself. sorry to be harsh but there are loads of these problems with people saying "**i have a high-end pc and I still have problems**" then my answer is you have some settings wrong . as you can see i can create and run this pack on 4 year old hardware.

**Comment by Teddicus** [comment]
Sorry but you seemed to have left out what settings would fix this problem if at all.

**Comment by buddicus** [comment]
Scalda would you like to elaborate on what settings I need to change?
I have run it using base settings, I have modified it to have more ram, I have tried quite a bit and nothing gets rid of the studdering.

The old foolcraft ran fine client side using base settings and so does every other Minecraft mod pack I have used.
