### ISSUE TITLE
skeleton spawner in nether not spawning wither skeleton, why?

### ISSUE THREAD

**Issue by mcvite80** [scalda/FoolCraft#757]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
stress produced a video were she put a overworld skeleton spawner in the nether to spawn wither skeletons. I made the same farm in my single player survival world and all I get out of mine is regular old skeletons, is this a bug or a recent change to foolcraft 2?

## Reproduce Steps
put skeleton spawner in nether, tried in a nether fortress and normal nether, neither worked.

**Comment by 3jlowes** [comment]
You probably dont have a vanilla skeleton spawner. if it is from rogue dungeons it wont work

**Comment by mcvite80** [comment]
no it was a vanilla spawner from a dungeon.

**Comment by notmark** [comment]
Try a fresh install of the mod and see if that still happens.

**Comment by Winrylive** [comment]
IIRC, in previous packs I've played the mechanics for vanilla spawner in Nether have changed, especially for skeles. Now Wither Skeles only spawn a percentage of the time. I'm not sure if it's anything specific but maybe that's what is happening here too, just a thought.

**Comment by scalda** [comment]
i have just tested this with vanilla skeleton spawner in the nether pack V2.3.1 and it works but it is a chance to get a wither skelly thou
