### ISSUE TITLE
Sign  removing last letter issue

### ISSUE THREAD

**Issue by DJMan255** [scalda/FoolCraft#758]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Additional Information
![2017-09-28_15 13 43](https://user-images.githubusercontent.com/32351769/30950356-b9662bfe-a45f-11e7-99b3-3abc926c7032.png) 
![2017-09-28_15 13 48](https://user-images.githubusercontent.com/32351769/30950360-be668f4a-a45f-11e7-8b3c-aa55c5820f20.png)

**Comment by scalda** [comment]
please report this to the mod author
