### ISSUE TITLE
Draconic Evolution

### ISSUE THREAD

**Issue by 3jlowes** [scalda/FoolCraft#759]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
What was the reason behind the removal behind draconic evolution? The pack doesnt offer many late game mods. Also, is there somewhere that shows the mods being added / removed or some communication on whats going on with the pack? ETA on next updated etc.

## Additional Information

The crafting recipe for the draconic evolution heart was not removed thus does the mod have a possibility of coming back?

**Comment by scalda** [comment]
no it is not being added back to the pack
