### ISSUE TITLE
Agricraft Issues

### ISSUE THREAD

**Issue by svennieke** [scalda/FoolCraft#76]
any crop i plant using on the agricraft cropsticks start at 12.5% grown and they might go up to 25% grown but refuses to go beyond 25% no matter how long i wait.

along with this issue there is also the issue where NEI says that the crop is not yet analyzed even when it is.

the only agricraft tank and channels you can craft are the oak.

sorry for making these 3 issues in to one instead of making them all a separate issue

**Comment by scalda** [comment]
Please try out pack 1.2.1 for these changes

**Comment by svennieke** [comment]
plants grow now, thanks for this, but
all the wooden tank recipes is displayed with oak planks which means that you can't craft any of the agricraft tanks except for the oak one

**Comment by scalda** [comment]
You can craft the tanks and irrigation channels out of any planks

**Comment by Mrbysco** [comment]
To give proof of previous statement. Here are some screenshots:
This is the recipe JEI/NEI shows for Mahogany Wooden Water Tank:
![Image of recipe](http://i.imgur.com/GQyK4eJ.png)
Here is me trying to make the recipe that should work:
![Image of recipe](http://i.imgur.com/JsTzIFn.jpg)

**Comment by Mrbysco** [comment]
Also to comment on the analysation. This is probably a bug in Agricraft atm as it's still in Alpha
![Image of Waila](http://i.imgur.com/IK6BLJC.png)

**Comment by scalda** [comment]
works fine in mine

water tanks
<img src=https://i.gyazo.com/fa42c5a02f2d56913580f740c62d6e29.png>

Irrigation
<img src=https://i.gyazo.com/26e44053ce6760c2465457b157d75621.png>

**Comment by scalda** [comment]
Have you tried reinstalling the pack?

**Comment by Mrbysco** [comment]
you say "works fine" but can you supply screenshots of the crafting actually working? as every Wooden Water Tank shows the oak recipe. 
I am using a fresh install. Both me and Svennieke got the same issue. (I play in a server with her)

Yes JEI/NEI shows them but that doesn't mean the recipes work. Clicking on them in recipe mode shows a recipe for the Oak Wooden Water Tank and not the other versions.

**Comment by Mrbysco** [comment]
good news: The Hwyla issue is gonna be fixed (reported to the dev and was told it's fixed in the next version).

-Mrbysco

**Comment by scalda** [comment]
Will be fixed in 1.3

**Comment by svennieke** [comment]
thank you :D
