### ISSUE TITLE
FoolCraft 2.1 Modpack keeps crashing.

### ISSUE THREAD

**Issue by xthemeraldkingx** [scalda/FoolCraft#761]
The Foolcraft modpack keeps crashing whenever I do something like go mining, die and even eat!
I put 12GB and it crashed even more! So I gave myself 6GB and it was a little better. I tried to remove the additional mods I installed and even wait 10 seconds after I do something crash worthy like vein mining. I did everything in my power to stop the crashing but nothing worked. Please help me...

**Comment by 3jlowes** [comment]
Do a fresh install of the pack, set ram to 6gb and launch. I would reccomend adding additional mods one at a time (Ex. Add mekanism, launch pack. play for a bit. make sure it doesnt crash. repeat) Or just add no extra mods.

**Comment by xthemeraldkingx** [comment]
Thanks for your quick feedback. I am just wondering if I can use the same
world because I really did progress a bit before I started crashing. If no,
that will be fine

**Comment by scalda** [comment]
just copy the world from one profile to the other or copy to your desktop and then copy back to the saves folder once the pack is reinstalled
