### ISSUE TITLE
Foolcraft keeps crashing to desktop every now and again.

### ISSUE THREAD

**Issue by Henri1992** [scalda/FoolCraft#763]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

The game crashes to desktop randomly. Previous I had the newest optifine, then it crashed with rendering issues, now it crashes with some hashmap error, that is thus the one that I am reporting.

I have no further details on the crash, when I gather more information, I will add it to this post.

## Additional Information
The pastebin includes 2 crashlogs about the same issue (as far as I can decipher them)
https://pastebin.com/XEmCBWmP

**Comment by scalda** [comment]
remove optifine
