### ISSUE TITLE
Modern Warfare mod

### ISSUE THREAD

**Issue by Darkonius** [scalda/FoolCraft#764]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Modern Warfare adds at minimum 2ms of latency to a server. Before removing the mod my server was running at 18.5 to 18.75ms under the /forge tps command. After removing this mod the system latency dropped around 16.25ms to 16.5ms.

## Reproduce Steps
Move the Modern Warfare files to and from the server folder and test the latency differences.

## Additional Information
If needed I will grab some screenshots before and after removing the mod on my server but was testing methods on how to improve server performance. This one works but I am not sure why removing this has this big of an improvement on the server performance. Others were around 0.75 to 1ms difference.

**Comment by 3jlowes** [comment]
Nah fam, sounds like something else. Im running the modpack (no mods added / removed) and getting 16.170ms. even better than you without it. So it sounds like a personal problem.

https://gyazo.com/e3b7b3a25d8f8f359f27d53aac9bc7d9

**Comment by Darkonius** [comment]
This can be closed. It boiled down to corrupt files from migration and some missing JVM arguments which reduced server performance. The server now has a 3ms to 5ms delay after fixing and doing a full diagnosis of the problem. 

https://i.imgur.com/XOFnAEp.png

**Comment by scalda** [comment]
this mod is being removed in the 2.2 version of the pack
