### ISSUE TITLE
Issue with textures on OS X

### ISSUE THREAD

**Issue by Den-tsar** [scalda/FoolCraft#768]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
I have the same problem over and over on my computer (OS X) with textures in the FoolCraft modpack. This issue occurs after every launch of the modpack. Only F3+T helps for now (reloads textures), however it takes forever to reload them. It only appears with a few mods (thermal foundation, weaponcaseloot etc.)

## Reproduce Steps
After every start of the launcher

## Additional Information
Before and after reloading textures
![2017-09-30 21 32 25](https://user-images.githubusercontent.com/1503754/31048604-1f9c8e7a-a629-11e7-9e5d-dafa4c4c339f.png)
![2017-09-30 21 34 37](https://user-images.githubusercontent.com/1503754/31048605-1fc6b506-a629-11e7-8866-449c6f86df4f.png)

**Comment by SmallSansSerif** [comment]
I've had that problem with several packs on macOS with a Macbook Retina. 

I solved this problem by editing the splash.properties file which is the config folder. 

Not all Macbooks have that problem as we have a more recent Macbook that doesn't have that problem at all.

Change this option to false in splash.properties file:

enabled=false

**Comment by tehnomaag** [comment]
Good tip @SmallSansSerif, I've had the same issue with many packs, and only F3+T has resolved it before (with the loooong wait time). But this splash config change trick did it for me, no more messed up textures when loading up.
