### ISSUE TITLE
Mod Idea

### ISSUE THREAD

**Issue by austinjaymes** [scalda/FoolCraft#769]
## SUGGESTION/HELP
- [ x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

**Comment by pfgithub** [comment]
The swapping wand is already available as the [Conversion Wand](https://minecraft.curseforge.com/projects/astral-sorcery/files/2390211) and in Botania as the [Rod of the Shifting Crust](https://ftbwiki.org/Rod_of_the_Shifting_Crust)

**Comment by scalda** [comment]
what @pfgithub said
