### ISSUE TITLE
Bed Glitching

### ISSUE THREAD

**Issue by Trekkie27** [scalda/FoolCraft#77]
Hi, I just started playing FoolCraft and about half the time when I sleep in a bed, the game glitches so that I can't leave said bed, even if I try to go into Creative or Spectator mode. Any ideas how to fix this? Thanks!

**Comment by scalda** [comment]
Hi do the command /ftb kickme this is a known vanilla bug

**Comment by Trekkie27** [comment]
Thank you so much I really appreciate it! I've never experienced it in vanilla before so I'm grateful I didn't break anything!
