### ISSUE TITLE
questbook not showing quests after crash

### ISSUE THREAD

**Issue by Xisrah** [scalda/FoolCraft#770]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
minecraft crashed ones and now it doesnt want to display all of the quest, in 1 of my worlds.
when I start an other world it works fine but i want to keep playing on that world. how do i make it work again?

**Comment by Necro9227** [comment]
This has happened to me as well, you can use this command to reload the quest book but all progress may be lost.  /bq_admin default load

**Comment by scalda** [comment]
best thing todo is to just reload it
