### ISSUE TITLE
Some more suggestions

### ISSUE THREAD

**Issue by RicardoTheCoder** [scalda/FoolCraft#771]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I have made some additions to the scripts on the pack and also have some content I would like to suggest.

### Scripts
My suggestion is to add a script to craft the fool's heads and two extra heads (scalda's and herobrine's :P ). This is just a decorative addition and doesn't affect the gameplay.
Find the script [here](https://pastebin.com/xTJkFTwJ)

I also changed the Player Head name to "Fool's Head":
`<minecraft:skull:3>.displayName = "Fool's Head";`

EDIT: A Quick fix on the scripts for the Wither and the Ender Dragon, there is a non-existing loot bag being added to their loot, by commenting or removing that line it fixed a problem where the server gives an error because of the loot bags (sometimes causing a crash):
`loot.addItemEntry(<lootbags:itemlootbag:30>, 11);`

There is, however, missing a loot bag for one of the fools, VintageBeef if I'm not mistaken, that should be the bag filling that place.

### Mods
As Moo Fluids is giving problems and it seems abandoned, I decided to make a similar mod but with a different approach.

This mod is called "Mini Moos" and it is already available on Curse, it contains compatibility with Tinker's Construct to allow alloy breeding, with Mine Factory Reloaded so the cows can be ranchable, among other features (also compatible with Waila & Hwyla). You can see more about it and download the mod [here](https://minecraft.curseforge.com/projects/mini-moos)

**NOTE:** If installed with Moo Fluids, Mini Moos will convert all cows from moo fluids into the ones from the mod, and it will also prevent Moo Fluids' Cows from spawning. (This was made specially so it can be integrated with this pack without the lost of previous cows).

**NOTE 2:** This mod requires a core called "Yet Another Core" also made by me, it will download automatically but it also adds new game rules, check its page [here](https://minecraft.curseforge.com/projects/yet-another-core)

In addition to the mod above, I would also like to suggest the mod "Mine Addons" created by my brother, it adds some 1.11 & 1.12 features to 1.10.2 and also some other cool stuff. Find more about it [here](https://minecraft.curseforge.com/projects/mine-addons?gameCategorySlug=mc-mods&projectID=278694)

Based on this we made a custom recipe for the Dire Crafting Table to allow the creation of the Creative Booster, you can get it [here](https://pastebin.com/8mP8VZdJ)

**NOTE:** Mini Moos also integrates with Mine Addons for more cool stuff.

## Additional Information
You may want to remove Ranchable Fluid Cows if you install "Mini Moos" as all cows are turned into those of my mod and it already has MFR integration making Ranchable Fluid Cows obsolete.

Any issues or problems with any of the mods or scripts, please feel free to contact me or post the issue on the issue tracker on each mod respective github.

**Comment by scalda** [comment]
Thanks for this I will test it out tomorrow

**Comment by RicardoTheCoder** [comment]
@scalda No problem, any issue or problem please feel free to contact me ;)

**Comment by RicardoTheCoder** [comment]
@scalda Just made an addition to my suggestions with a fix for an error with the loot bags.

**Comment by scalda** [comment]
These changes have been made thank you
