### ISSUE TITLE
Quest Suggestions

### ISSUE THREAD

**Issue by svennieke** [scalda/FoolCraft#772]
- [ ] I am running the latest version of FoolCraft
- [ ] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [ ] In single player
     - [ ] In multiplayer
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I want to suggest a few new quests regarding the Statues mod.
**Quest one**: Just a little bit smarter: Craft/get a informative statue
**Quest two**: Chicken King: Get a King Cluck statue (informative statue should be able to give you a clue on how to get it
**Quest three**: Flood the world one bucket at a time: Get the Flood Statue: (Informative statue should help you by giving a clue)
**Quest four**: Royal Food: Get X amount of royal nuggets from King Cluck (needs a at least tier 3 king cluck statue)
**Quest five**: Mooshroom soup not mushroom stew: get mooshroom stew from a tier 3 or tier 4 mooshroom statue

**Comment by scalda** [comment]
been added to 2.4
