### ISSUE TITLE
Help Astral sorcery causes a crash loop on foolcraft servers

### ISSUE THREAD

**Issue by AnkkeMaisteri** [scalda/FoolCraft#774]
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [x] I am crashing and can provide my crash report(s)

- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack 
- Astral sorcery causes a crash loop on servers running foolcraft 2.1 so can you fix the issue or delete the mod some help would be nice

**Comment by svennieke** [comment]
can you give a crash log that way the people that are making foolcraft can take a look at it as currently there is nothing that they can look at to even try and see what is causing it, i have been playing with the mod myself and did not get any crash

**Comment by scalda** [comment]
no crash report provided closing this issue
