### ISSUE TITLE
Foolcraft 2.2 (do not) update

### ISSUE THREAD

**Issue by janf3** [scalda/FoolCraft#777]
@scalda The update on the Twitch launcher is _faulty_

It contains both, the old versions as well as the updated versions of mods. Also the mods that ought to be removed (e.g. MooFluids) are still in there.

needs a re-release

**Comment by scalda** [comment]
i'm sorry i have no idea what you are on about, there are no duplicates in the pack and moofluids needs to be in there so all current cows in the world changes over to the new ones

**Comment by janf3** [comment]
Sorry, I should have tested on my second machine before posting. 
_Twitch was being Twitch_ and left all old versions in place

![fc22](https://user-images.githubusercontent.com/15951093/31098550-40c965d2-a7c3-11e7-93dc-f2dbfdbe0259.PNG)

Update went just fine on my other machine.
