### ISSUE TITLE
Mini Moo Fool Craft Issue

### ISSUE THREAD

**Issue by killerkitt** [scalda/FoolCraft#778]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
cant breed mini moo fluid cows together with mini wheat tried with same type and differnt types of fluid mini moos

## Reproduce Steps
-mini wheat x 2 right click each cow and they do nothing

**Comment by RicardoTheCoder** [comment]
@killerkitt Already answered about this on the mod issue tracker ([here](https://github.com/RicardoTheCoder/MiniMoos/issues/2))

**Comment by scalda** [comment]
@killerkitt This might be a problem in the information I provided on the mod wiki or curse page.

I state these two things:

Mini Wheat to breed them, made with wheat and blaze powder (can only attract without Tinker's Contruct Addon)
Allows cows to be breed to give alloy fluids (it only works with alloys that only require 2 fluids)
Let me clarify that for you, you can only breed cows that have fluids that can make an alloy result. An example will be breeding a water and lava cow to give an obsidian cow.

The mini wheat does get consumed even if they don't breed, this was intended as a way to balance the breeding process when alloy cows also spawn in the world. However, I can either add a configuration for that or remove that "feature".

I will alter the description on this to make it more clear.

Hope that this helps you out ;)
