### ISSUE TITLE
Server files missing on latest v2.2

### ISSUE THREAD

**Issue by SmallSansSerif** [scalda/FoolCraft#779]
Please post the server files pack for v2.2 on CurseForge. It appears that the client files are there but server pack is not.

https://minecraft.curseforge.com/projects/foolcraft/files
https://minecraft.curseforge.com/projects/foolcraft/files/2486694

**Comment by scalda** [comment]
this is correct but i'm not sure how this is an issue for the GitHub the files will be up once they are made
