### ISSUE TITLE
Client crash when painting Travel Anchor

### ISSUE THREAD

**Issue by Furree** [scalda/FoolCraft#780]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

**Comment by Furree** [comment]
I put in 3 travel Anchors in a Painting machine and a block of Demon metal. Just as the process were to be done the game crashed client wise. When I logged in and clicked on the painter it crashed again. 3:rd time I broke the painter, tried to reset it in a crafting grid and replaced it and crashed when I clicked on it. I trashed the painter after that.

**Comment by Mrbysco** [comment]
Do you have a crash log that people can look at?

**Comment by scalda** [comment]
submitted to ender io issues page

**Comment by scalda** [comment]
iam still awaiting a fix but i doubt there will since mod devs are moving to 1.12.2 so closing for now
