### ISSUE TITLE
Wireless Terminal AE Visual Bug

### ISSUE THREAD

**Issue by nhocchip** [scalda/FoolCraft#781]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Reproduce Steps
Hold out the wireless terminal in your hand then scroll to a non-empty inventory slot.it appears as the terminal(still acts like the block however since it is only visual)

**Comment by nhocchip** [comment]
Yep,just restarted my client and this still occurs,really annoying but no function changes.seems to be that tools seem to reset this as well.

**Comment by scalda** [comment]
i can't reproduce this in pack version 2.3.1
