### ISSUE TITLE
Please Help, Game Freezes

### ISSUE THREAD

**Issue by ThePotplant** [scalda/FoolCraft#784]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

Everytime I start FoolCraft I can into like the menu where I can select Single player, multiplayer etc. the game freezes.

## Reproduce Steps

Just open the game and after the loading screen the game will freeze

https://imgur.com/Gd0Tx4K

**Comment by svennieke** [comment]
does the game freeze and never respond? asking as my game also freezes on the main menu but after a few seconds max after a minute it works fine

**Comment by ThePotplant** [comment]
Yes. I freezes for like ever. If I press a button it takes like 5 minutes
for the game to react.

**Comment by scalda** [comment]
what pack version are you using?
