### ISSUE TITLE
Bucket 4100 - White fluid cow gives no fluid and renders bucket useless

### ISSUE THREAD

**Issue by JagerVater** [scalda/FoolCraft#785]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description

A white fluid cow (similar color to tin) when milked changes the bucket ID to 4100 (normal is 325) but no fluid is gained and bucket cannot be emptied into a tank or fluid trash can, cannot return bucket to usable state.

**Comment by RicardoTheCoder** [comment]
@JagerVater By putting that bucket into the crafting table it should get fixed on the Foolcraft 2.2 version.

Also if that problem still persists in my mod "Mini Moos" it might be a problem on the fluid registration. I will look into that and see if I can make a fix to prevent that, I will try to make that before @scalda makes the new foolcraft update live.

**Comment by RicardoTheCoder** [comment]
@JagerVater I looked into this and applied a fix to both the "Mini Moos" mod and the core I use in it, to try and prevent cows from giving bugged buckets. However, this might cause some fluids not to spawn, those fluids should be the ones with registration problems.

Also, as of version 1.2 of the mod, you can milk moos with that bucket which is Forge's Universal Bucket.
