### ISSUE TITLE
Suggestion: Ability to Put MFR Rubber Wood into TE Sawmill

### ISSUE THREAD

**Issue by jestesared** [scalda/FoolCraft#786]
## SUGGESTION/HELP
- [x ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
In other modpacks, rubber tree wood from MFR can be put into a sawmill, to get jungle wood planks and a small chance for more raw rubber. I'm wondering if this is possible in FoolCraft, or at the very least the ability to put the logs in the sawmill for just planks and sawdust.

## Reproduce Steps
Try to put MFR rubber wood logs into a Thermal Expansion sawmill, it doesn't work.

**Comment by scalda** [comment]
no way to do this as TE does not have modtweaker support in 1.10.2 sorry
