### ISSUE TITLE
Casting cobalt in a casting basin produces a chiseled block.

### ISSUE THREAD

**Issue by Exobe** [scalda/FoolCraft#787]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Similar to a few other submissions I've seen but with cobalt. Produces the "caution" variant.

## Reproduce Steps
Cast cobalt in a casting basin

**Comment by scalda** [comment]
duplicater #788

**Comment by scalda** [comment]
this is tinkers for you, it grabs the first recipe it can, without going through every blockable liquid and creating custom MT scripts there is nothing to be done, at least you can chisel it plus you can convert it straight into the ingot form
