### ISSUE TITLE
Copper/Iridium/Enderium block produced but invisible

### ISSUE THREAD

**Issue by Tombacat** [scalda/FoolCraft#788]
Hi,

I am producing Copper/Iridium/Enderium with fluid cows via mechanical user -> fluid tank -> casting basin. Gathering all of them in a colossal chest. This works fine, the Copper/Iridium/Enderium blocks are counted but invisible. When I make copper ingots of a block, they are visible.

Running on MacBook Pro (Retina) with 6144mb assigned to jvm.

Am I doing something wrong?

Thx!

**Comment by scalda** [comment]
pack version please?

**Comment by Den-tsar** [comment]
I've had kinda the same problem (#768). Changing the option "enabled=false" in splash.properties in the config worked just fine.

**Comment by Tombacat** [comment]
Ah, Sorry I am new to this. 

I am running pack version 2.0 in single player mode (creative). 

There is also another thing: I seem to get a lot of copper blocks but sometimes a block of copper. These blocks of copper are visible.

And indeed with enabled = false all (!) blocks are visible. This setting is fine for me, Thx!
