### ISSUE TITLE
Lag?

### ISSUE THREAD

**Issue by 3lementalS** [scalda/FoolCraft#79]
Atm the only issue I have found is when breaking logs/dirt/sand etc. It takes a while for it to register as broken. I don't know if there is a mod that is causing it or if anyone else is experiencing the same issue.

**Comment by HazDS** [comment]
We have not reports of this, maybe try setting the memory to 6gb to help?

**Comment by scalda** [comment]
@3lementalS any new information on this?

**Comment by 3lementalS** [comment]
I had 6-8gb default when this occurred, the solution I found was to use optifine.

**Comment by 3lementalS** [comment]
Players just need to be careful of which version or they'll get a tessellating block model error
