### ISSUE TITLE
Weirding Gadget, another Chunkloading mod Suggestion

### ISSUE THREAD

**Issue by svennieke** [scalda/FoolCraft#790]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I want to suggest a different Chunk Loading mod, one that requires the player to actually be active every so often on the server (default 7 days) this could be useful to fight some lag as bases from inactive people won't be chunk loaded anymore.
https://minecraft.curseforge.com/projects/the-weirding-gadget

## Additional Information
this could realy be a useful tool, for things like patreon servers, private servers and maybe even for the official foolcraft server, it should not affect single player that much

**Comment by scalda** [comment]
added to out potential mod list
