### ISSUE TITLE
Suggestion till railcraft power is fixed

### ISSUE THREAD

**Issue by Henri1992** [scalda/FoolCraft#791]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

The railcraft power system is broken in 1.10.2, a good fix is to maybe make it possible via extreme crafting to make the perpetuum locomotive. 

This will be a good stand-in for the electric locomotive, but would not be required to stay after it is fixed.

**Comment by scalda** [comment]
hi thanks for this i have decided to add a recipe for the admin charge unit at least then you will be able to use all the RC powered stuff
