### ISSUE TITLE
AE2 networking (how to do without controller and smart cables?)

### ISSUE THREAD

**Issue by leasoncre** [scalda/FoolCraft#792]
- [X] I am running the latest version of FoolCraft
- [X] I am running FoolCraft via Curse/Twitch Launcher
- [X] I can reproduce this issue consistently
     - [X] In single player
     - [ ] In multiplayer
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [X] I am requesting help with installing or running the pack

## Issue Description
AE2
MAIN ISSUE: I've been playing for a couple weeks now, and i'm running into issues with devices going offline when i add more components to the network. (I see that channels are disabled in the AE2 config file, but this doesn't seem to be disabling channel useage entirely)
Q1: How to setup a complex network _without_ the controller or smart cables? (assuming channels still being somehow enabled even though configured to not be.)
All the videos on YT/wiki utilize the controller and smart cables.
even interfaces require a channel, with only 8 channels available, it's practically impossible to have a centralized management of the entire system
Q2: how do i disable 'easy mode' for AE2 (as mentioned here: https://github.com/scalda/FoolCraft/issues/662 ) i find it quite annoying and limiting. (i'm ligit a network engineer IRL)

## Reproduce Steps
run game, play it. 

## Additional Information
Q/A
Thanks for the help

PS. Q3: not sure where to ask this: but i can only put 47 wireless booster cards in the wireless transmitter, any more and it goes offline, not sure why. system should have plenty of power, dunno how to troubleshoot this. i haven't seen any info saying there's a power limit to the networks.

**Comment by leasoncre** [comment]
finding more related posts on the internet: (old, but seems to be similar) https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1510/

**Comment by leasoncre** [comment]
found the setting to disable 'easy mode': https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1369 , still doesn't answer why 'infinite channels' isn't working right
(dang this slang name/setting is hard to track down, burried in the internet)

**Comment by RicardoTheCoder** [comment]
@leasoncre Are you using a Fool's Controller? (It is the same as a Creative Energy Cell the name is changed in the pack).
If not you might be out of energy.

Every terminal, machine and alike on the ME (AE2) Network consumes energy even if there is no channels, you may be using more energy than what you have in the system. Also if you are moving the signal wireless or if you are too far away from your network's energy acceptor or the main point of the network, the chunk might be getting unloaded also breaking the network.

PS: Use a chunk loader from chicken chunks or similar. Do not the Forge's Chunk Loader it is not working as it should.

**Comment by leasoncre** [comment]
Chunk loader: i have the map/forge chunkloader (as i see, doesn't work..) and the ChickenChunk Loader block placed (like 5-chunks wide square) (not concerned: noticed if i login away from the loader block the chunks do not load until i return to the area)

I don't have any energy cells on the AE2 network, currently one energy acceptor with a EnderEnergyConduit (~20kRF) plugged into it from a 875M vibrant capacator bank (nowhere does any webpage say there's a limit to the acceptor's capacity) Cap. Bank shows only 2883RF in/out (source: iskall gen 3x3x3 core) and that's the only thing connected to _that_ EnderIO energy network.
do i need more acceptors? or does the AE2 system pretty much require energy cells dotted around the network(assuming with more acceptors/RF input)

(AE2 has no wiki info defining energy limitations or troubleshooting, just device x uses x power. )
Thanks.

**Comment by RicardoTheCoder** [comment]
@leasoncre From what I know (based on AE2 code), energy acceptors only transfer 10k RFs and sometimes the network bugs if you have no energy cell connected to it, because the ME Network always tries to fill the cells first.

Try adding one into the network and see if it fixes the problem.

**Comment by leasoncre** [comment]
umm.. maybe.. that might have helped, but i think i found the problem, i was treating all AE2 blocks like they would transfer ME (like other mods have done in the past) looks like i have a cell workbench between some things that was disconnecting things. noticed this as i placed an EnderIO Dense ME conduit next to it and it did not connect. (bypassing the non-connecting block)

why can't Channels=False also make all the mod's blocks ME connecting....

considering this closed. Thanks again! (now to make more mess of the network.. lol)
