### ISSUE TITLE
Server World migration

### ISSUE THREAD

**Issue by Ilaststa** [scalda/FoolCraft#793]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
I wanted to update my Foolcraft server from version 2.1 to 2.3.1, but I can't find my world file to migrate. How can I update my server?

**Comment by naproxes** [comment]
if u kept the default settings your world should be named "Foolcraft" and is placed in the server directory.
i'll try the upgrade mysell tonight at german time so expect another reply in 10 hours

**Comment by Mrbysco** [comment]
I myself have upgraded from 2.1 to 2.3.1 without any issues. 
The only message I got were about some items being missing but that is to be expected with mod removals replacements.

As long as you keep your world folder which by default is named "Foolcraft" you should not have any issues.

**Comment by Ilaststa** [comment]
It worked, I didn't realize that the world folder was named "Foolcraft".
