### ISSUE TITLE
One Item Crashes Minecraft

### ISSUE THREAD

**Issue by Shibby10** [scalda/FoolCraft#794]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
One item that is highlighted named "NoName" in my toolbar crashes minecraft

## Reproduce Steps
Every time i log in to the game, i see 1 frame and it crashes.

## Additional Information
https://pastebin.com/embed_js/3tM1cPyM

No idea if i did this right... First time ever posting here

**Comment by scalda** [comment]
this is a bad chicken spawn egg, you will have to edit your player data file
