### ISSUE TITLE
Concrete Slab Duplication [FoolCraft version 2.3.1]

### ISSUE THREAD

**Issue by AythaAquaheart** [scalda/FoolCraft#795]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Placing an upside down concrete slab from the 1.12 Concrete mod and trying to place another on from below, and it only works from below, places a double slab on the block underneath the previously placed slab instead of completing a block with the first one.

## Reproduce Steps
Simply place a concrete slab (I used white) on the upper half of a block.
Then place another one on that slab from underneath to try and form a full block.

**Comment by scalda** [comment]
thank you for this i have reported to the mod author
