### ISSUE TITLE
Gelid Cryotheum cow no-longer spawns

### ISSUE THREAD

**Issue by leasoncre** [scalda/FoolCraft#796]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
since adding mini-moo's mod i have been unable to find Gelid Cryotheum cows, i also have a fluid moo EnderIO spawner, and it has not spawned a single cryo-moo after an hour+ of spawning (with vibrant capacitor to increase spawn rate)
+the 3 i have/had before the update are still around (mini-ized)
It seems like all the other moo's are spawning passively and via spawner.

## Reproduce Steps
run FC 2.1, update to 2.2 or 2.3, no more cryo-moos spawn

## Additional Information
I looked through the cfg files, they are enabled...

**Comment by scalda** [comment]
This type of moo spawns in the end

**Comment by RicardoTheCoder** [comment]
Adding to what scalda said. Mini Moos spawn based on temperature making them alternate between the 3 dimensions. This applies to spawners also, so you will have to put the spawner on the respective dimension to get the moo you want.

**Comment by leasoncre** [comment]
oooOOOOO. ok, thanks, i didn't see that particular bit of information anywhere.
