### ISSUE TITLE
Mini Moo's or corrupted chunk issue?

### ISSUE THREAD

**Issue by ranmas** [scalda/FoolCraft#798]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Running Foolcraft 2.2
Crashing when entering chucks around my base/spawn.  I can Mcedit myself just outside the area and can load into the game, however when I move into the area the game immediately crashes.

## Additional Information
https://pastebin.com/BeEReGkP  Original Crash
https://pastebin.com/zu9214cG  Crash after Moving via mcedit and then trying to enter base again

**Comment by scalda** [comment]
Update to 2.3. 1 and retry

**Comment by ranmas** [comment]
yeah, updating solved this.
