### ISSUE TITLE
Server file crashes while opening

### ISSUE THREAD

**Issue by KappaTurtle** [scalda/FoolCraft#80]
![image](https://cloud.githubusercontent.com/assets/26662849/24321507/2aa7e418-1146-11e7-8cf5-d5289f1a3ffa.png)

**Comment by ftrocchi** [comment]
I'm having the same exact issue.  Very frustrating.  It would be nice to have it working properly before being released.  Also maybe add some sort of readme as instructions?  Even brief instructions would be helpful.

**Comment by scalda** [comment]
For one you are running the wrong jar you need to be usuing the forge jar for modded

also looks like the libaries files are missing

**Comment by KappaTurtle** [comment]
I am aware of running the wrong jar, i was messing about with them and got this issue whenever i tried to run the forge jar. so i copied the files into the minecraft_server jar and tried it, getting the same error.

**Comment by scalda** [comment]
yes i am currently uploading new files to curse to fix your issue

**Comment by KappaTurtle** [comment]
K thanks :D

**Comment by scalda** [comment]
files should be availible in the next 10 minutes

**Comment by Zx3Scorpionz** [comment]
Awesome!
