### ISSUE TITLE
Item rendering issue causes crash clientside

### ISSUE THREAD

**Issue by FallenStargazer** [scalda/FoolCraft#800]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Illuminati pet gave me an item that does not render and crashes me upon opening my inventory. The item was titled ' cover' and was possibly a banned or glitched item.

## Reproduce Steps
 Illuminati pet gave me the random item, and upon first getting the item my client crashed. It was not in my hotbar, and subsequently each time I open the inventory, it fails to render and crashes.

## Additional Information
https://pastebin.com/G8MSX1SH 

Crash report.

**Comment by scalda** [comment]
now has been fixed
