### ISSUE TITLE
Woot Wither Farm only produces Docm77 Hermit bags

### ISSUE THREAD

**Issue by Schaefer78** [scalda/FoolCraft#801]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
3 Players on my server have Woot farms for withers and they complaining they are only getting Docm77 lootbags and not getting any others.

## Reproduce Steps
Run the woot farm for wither.

**Comment by scalda** [comment]
we are currently working on fixing the lootbags for the next release please be patient

**Comment by Jo-Mamma75** [comment]
It is also a possibility that when setting up the Woot farm, when it "rolled" the loot table for the Wither, it only picked up that bag.  You can try to re-roll the farm by clearing the controller (place in your 2x2 crafting grid) and applying the prizm to it again.
