### ISSUE TITLE
N/A

### ISSUE THREAD

**Issue by Technobot7** [scalda/FoolCraft#802]
https://www.reddit.com/r/feedthebeast/comments/76cj7u/advice_foolcraft_devs_stole_craft_of_the_titans/

**Comment by Technobot7** [comment]
Oh and Fuck You devs

**Comment by Technobot7** [comment]
u idiot, ur trying to block this post

**Comment by Jo-Mamma75** [comment]
Blocking the post?  Of course.  This isn't the place for it.  Say your piece on Reddit and leave the Github for an actual issue.  Why is that so hard to understand?  Even Boolyman is being understanding of the situation and you can't seem to leave it alone.
