### ISSUE TITLE
need so many elytras

### ISSUE THREAD

**Issue by bjelven217** [scalda/FoolCraft#803]
for making the creativ energy thing from extra utilitus you need around 64 elytras and we cant Craft them and if you want to make the energy thing you need to explore then and exploring is not the best on servers so if we can get a way to Craft them it will reduce some lag and the servers does not need to lag for other players

**Comment by scalda** [comment]
ok thanks for this i will look into ths

**Comment by RicardoTheCoder** [comment]
@scalda I would suggest add it as a drop to the ender dragon, like in the hermit craft server, just make it not drop always (20 to 40% I would say). Perhaps put it as a drop from woot?

**Comment by rozenkai** [comment]
@scalda i also ran into this issue on a server i am on i would suggest maybe an extreme crafting recipe as you need around 24 to make the fool's ultimate power source and searching through the end for 3 hours yielded me 3 as many places have already been looted there is a craftable Elytra mod also if you dont want to mess with what is already there
thanks and love the pack

**Comment by scalda** [comment]
there is now a daily quest that if you kill a dragon you get a elytra
