### ISSUE TITLE
AE2 Stuff for Foolcraft

### ISSUE THREAD

**Issue by thorzy** [scalda/FoolCraft#804]
## SUGGESTION/HELP
- [ x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Additional Information

I was wondering why AE2 stuff was not included in Foolcraft it adds only a few items but it replaces some of the lag causing items in the pack such as the inscribers with advanced ones that are faster removing the need for many inscribers to mass produce processors aswell as simplify the creation of crystals wich require a kinda elaborate setup aswell as dropping rendered items in bulk into water.
Please consider adding this mod unless issues prevent it.

**Comment by scalda** [comment]
please search the closed issues as this issues as already been closed and i said it has been added to our short list for mods to be added
