### ISSUE TITLE
Stuck on "World Loading Screen", Mine/Mod Tweaker Errored

### ISSUE THREAD

**Issue by 3lementalS** [scalda/FoolCraft#805]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I was playing before I had a power outage. When I came back to finish playing I was stuck on "World Loading" screen it stalled. From what I saw in the logs (Waaayyy near the end) Mine/Mod Tweaker was errored tried to downgrade the mod, but still the same. Hoping someone has dealt with a similar issue.
(EDIT:) Downgrading FoolCraft to v2.3 works so far...

## Additional Information

[fml-client-latest.log](https://github.com/scalda/FoolCraft/files/1385147/fml-client-latest.log)
[latest.log](https://github.com/scalda/FoolCraft/files/1385148/latest.log)

**Comment by scalda** [comment]
try upgrading to 2.3.1 again and see if all is well it might of been that the files may of got corrupt

**Comment by 3lementalS** [comment]
Found the issue. The pack doesn't like actually additions apparently.
Thanks though :D
