### ISSUE TITLE
2x2 Crafting Grid not working

### ISSUE THREAD

**Issue by zwamdurkel** [scalda/FoolCraft#807]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
players on my server (including me) can't craft items with the 2x2 survival crafting grid. crafting tables and similar work fine. It just doesn't let them craft the item. I've included a gif which shows the problem if it wasn't clear. I run a foolcraft server with ~20 active members and this is really annoying especially when working with c&b blueprints :P
![giphy](https://user-images.githubusercontent.com/13705380/31607574-302df008-b26d-11e7-8c35-1c5c8526e49c.gif)

## Reproduce Steps
I do not know how to reproduce this issue, the server output and client output don't show any errors. It just happens on my server

## Additional Information
If you'd like to take a look at the server yourself, I can give you access. Just send me a msg on discord Zwamdurkel#2578 . You can also join the server to see the problem: dragonrealm.play.ai

**Comment by scalda** [comment]
this is a desync between server and client make sure both server and clients are upto date and you may need to reinstall the server in case something is missing

**Comment by andrelinslima** [comment]
![2017-11-04_22 03 49](https://user-images.githubusercontent.com/33740641/32927798-e6660a96-cb35-11e7-9f73-18ff542d31a3.png)

We had a similar problem, check if there is an error message like the one above when the player connects to the server. In our case, a sponge plugin was removing the eu2 chunkloader before the foolcraft script had a chance to do it, so no recipes added by the mod were being processed. That meant that the players had the custom recipes but the server did not accept it. causing the same behavior you are getting

**Comment by tyler489** [comment]
One version of forge had this issue. Try upgrading or downgrading.
