### ISSUE TITLE
Well-established tool + Veinmining quartz = Very Bad

### ISSUE THREAD

**Issue by jkdoug** [scalda/FoolCraft#808]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Using a Tinker's pickaxe made with copper (well-established) is causing my game to hang and disconnect when veinmining at least a dozen Nether Quartz, most likely due to the inordinate number of entities (xp orbs) spawned. The only way I'm able to recover is to restart the server, which effectively rewinds the veinmining.

## Reproduce Steps

1. Craft a Tinker's pickaxe out of copper to get the well-established modifier. Fortune and Luck are also likely to contribute to this. (My pick has Fortune I/Luck I on it.)
2. Find or build a vein or 12+ quartz ore and use veinmining on it.

## Additional Information
I did a bit of searching for any settings that could help lower the XP orb counts, combining the orbs or something, and was unable to find anything worth trying.

**Comment by jkdoug** [comment]
Built a new pickaxe without well-established, fortune, or luck, and the XP orbs can still lock it up. The message on the server is simply "[Netty Epoll Server IO #1/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException."

**Comment by RicardoTheCoder** [comment]
@jkdoug This is a bug with Clumps. That mod compiles all XP orbs into one or two to prevent massive lag. But sometimes it bugs and generates absurd amounts of orbs.

I had a similar issue both on the nether and on the overworld, upon removing that mod, it stopped happening.

**Comment by scalda** [comment]
thanks for the info @RicardoTheCoder i will have a think about removing this mod if it is causing issues
