### ISSUE TITLE
Quantum quarry or Under Deep doesn't spawn Iskalium or Astral Sorcery crystals.

### ISSUE THREAD

**Issue by demethan** [scalda/FoolCraft#809]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Quantum quarry or Under Deep doesn't spawn Iskalium or Astral Sorcery crystals.

**Comment by scalda** [comment]
this is not a bug it is intentional

**Comment by demethan** [comment]
Ok..
