### ISSUE TITLE
World bugged due to updating.

### ISSUE THREAD

**Issue by kakas123455** [scalda/FoolCraft#811]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

**Comment by RicardoTheCoder** [comment]
@kakas123455 Updating from FoolCraft 1 to FoolCraft 2 is almost the same as updating from a Modpack to another. As some mods were removed and others added, the reference to some blocks and items has changed, that is why some of those problems happened when you updated.

I would recommend opening the world in the version 1.2.1/1.2.2 and check everything you have, open another client on version 2.3.1 and see what is different, then just go into creative and fix it.

If you don't want to do that, just start playing from scratch.

**Comment by kakas123455** [comment]
I know that what you are saying is happening here,but I dont know how to fix it,and I think that there isnt a possible fix after all.I will just make a new world,thanks for trying though.
