### ISSUE TITLE
Possible cause for things flickering in the distance.

### ISSUE THREAD

**Issue by Materialize127** [scalda/FoolCraft#812]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I have seen this issue brought up before and am posting this because I may have found the cause and just want to help out. I am talking about the times when trees and tall grass in the distance flicker.
It seems to be related to the Tiny Progressions growth crystal. If one gets loaded the trees flicker until you reboot or force the renderer to get reloaded by changing your resource pack. If you don't load one everything seems fine. Could be more to it but that what we have found on my server.
I have been able to reliably reproduce this effect. This is both with and without Optifine in the pack.

## Reproduce Steps
The way we have been reproducing this issue is but logging out far from the Tiny Progressions growth crystal, restarting the game and then logging back in. The issue is then fixed until we load a chunk with that block in it then the issue returns until that chunk is unloaded and you restart the game or reload the renderer by reloading a resource pack.

**Comment by scalda** [comment]
this has been fixed in the mod and will be released in the next version of
foolcraft 2.4 monday
