### ISSUE TITLE
Market from Pam's Harvest not working very good

### ISSUE THREAD

**Issue by SoulOfHunter55** [scalda/FoolCraft#814]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

When I try buying spawn egg from the Market from the mod Pam's Harvest it gives empty spawn egg that spawns nothing.

just go to the Market block and try to buy any kind of a spawn egg and it will happen.

https://imgur.com/a/LvyVF

**Comment by scalda** [comment]
if i remember correctly the market block has always been broken in 1.10.2 and it still hasn't be rectified

**Comment by scalda** [comment]
I have just tested this in the 2.5 dev version of the pack and all works fine actually.

**Comment by HHHoegsted** [comment]
It doesn't work in 2.6, just bought several different spawn eggs - none worked. Also rabbits don't spawn (mini moos for days, no rabbits), and maloberry bushes are nowhere to be seen.
