### ISSUE TITLE
SERVER CRASH

### ISSUE THREAD

**Issue by arthurjan** [scalda/FoolCraft#815]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

Anytime I have any sort of automated wither killing system the server eventually crashes either within the minute the server was launched up to an hour later, I have tried killing it w/a shield and w/a user that has a sword left clicking.

[crash-2017-10-21_21.33.53-server.txt](https://github.com/scalda/FoolCraft/files/1404610/crash-2017-10-21_21.33.53-server.txt)

**Comment by arthurjan** [comment]
ONGOING ISSUE**
need help as soon as possible please, makes the game unplayable

**Comment by scalda** [comment]
this is a mech user trying to use the sword you place in it hitting an air block
Block location: World: (454,10,188)

you will need to either disable the user in the exu2 config reload the world to get in and then turn them back on

or mcedit out the block at the above coords

**Comment by scalda** [comment]
@arthurjan has this been resolved??

**Comment by arthurjan** [comment]
Yes it has, I completely switched out the swords (tinkers)which may have been the problem and fixed the wiring
