### ISSUE TITLE
Avaritia World Breaker Pickaxe is not breaking bedrock

### ISSUE THREAD

**Issue by bloodbath22** [scalda/FoolCraft#816]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
The World Breaker pickaxe from Avaritia isn't breaking/mining bedrock. Simple issue, idk if bedrock is locked

## Reproduce Steps
Get the World Breaker Pickaxe, try to break bedrock

**Comment by svennieke** [comment]
is this realy a issue tho? bedrock is not supposed to be broken at all.

**Comment by bloodbath22** [comment]
The world breaker is supposed to mine it though, and I'm pretty sure bedrock's used in a few recipes

**Comment by scalda** [comment]
This is disabled in the pack so it is working as intended

**Comment by johnwolf01** [comment]
The only Player crafting its used for is the Block armor and the "perks" you get from bedrock armor is less than Obsidian armor that gives Flame Resistance Extra compared to bedrock armor.

**Comment by scalda** [comment]
This is disabled in the pack so it is working as intended
