### ISSUE TITLE
Freezing on Loading World Screen

### ISSUE THREAD

**Issue by N1bel** [scalda/FoolCraft#817]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
My game seems to freeze whenever I get to the loading world screen when opening a world, it also won't let me close Minecraft without going to task manager. I've tried both reinstalling foolcraft, adn reinstalling the curse/twitch launcher, but no luck so far.

**Comment by johnwolf01** [comment]
When opening foolcraft form the Twitch launcher. 
1) On the Loading screen click on the "settings" tab.
2) Enable both "keep open Launcher" and "open output log"
the open output log should show you a detailed list of everything loading and errors.

Ignore all the errors and warnings while the game is loading, what you want to see is what the log says when opening your world.  there may be something preventing the game from loading. Faulty chunks, entities or whatever, the log may  give some indication why your world is not loading.

Assuming your computer have the needed resources. As this pack is very resource heavy. 
--------------------------------------------------------------
As said above. You will need at least 16G ram, a strong prosessor and grafix card.
6G ram is allocated by default to the game when it is loading even before you start playing.
loading the world may use another 1G (randomly) and other resources, this I have seen using a resource monitor application. 
-----------------------------------------------------

**Comment by N1bel** [comment]
![image](https://user-images.githubusercontent.com/29789887/31965124-55d56f44-b8d4-11e7-8867-6b548bdb1631.png)

![image](https://user-images.githubusercontent.com/29789887/31965139-5f99699a-b8d4-11e7-81b4-044406b0b2b0.png)

This is pretty much all of the stuff in the log, I assume the warnings are the fluid cows? Would this be a problem because of the update? 

I haven't really had any problems running the pack on my computer before, a bit of lag, but nothing unplayable, so my system can handle it it seems.

**Comment by scalda** [comment]
Have you got a crash report?

**Comment by N1bel** [comment]
My game isn't actually crashing, it just freezes on the loading screen, and I have to use task manager to close it.
