### ISSUE TITLE
rfTools Matter transmitter recipe missing

### ISSUE THREAD

**Issue by Fuxy22** [scalda/FoolCraft#818]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

rfTools Matter Transmitter, Reciever and dialing device have their recipes dissabled.

As far as i can tell from the commit log it was just initially commited like that and I was wondering if there was a reason for it to be dissabled?

Also any reason rfTools Dimensions was't included it would be a interesting way to get more iskalium by making a dimension of it?

**Comment by janf3** [comment]
If I recall correctly Iskallium only spawns in the Overworld for now?
The easiest way to get a lot of it is a RFTools builder with a storage filter card. Since the builder only uses RF for blocks mined this is very efficient and affordable power wise.

**Comment by scalda** [comment]
these have been disabled in the mod have been since FC 1.0.
as for the dimensions the reason you stated for using it is one of the reasons it is not in the pack
