### ISSUE TITLE
BetterQuest mod will not pop up that I have a quest I can complete

### ISSUE THREAD

**Issue by VonZadian** [scalda/FoolCraft#819]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
BetterQuest mod will not pop up that I have a quest I can complete. At first it would do nothing but spam that I had a quest that I had already completed to complete but now it doesn't pop up anything. I didn't change any setting and I reset to default to try and fix the issue. I looked at the config files but can't find anything out of the norm. I may be over looking something but I would like to have that pop up back LOL. Sorry to bother you with this. I know its a dumb issue and you probably have better things to do. Also I deleted all mods and reinstalled 2.4 and reset BQ. Also the first quest wont complete. This is new with 2.4

## Reproduce Steps
Start a new world with version 2.4 and see if it pops up when you get 64 wood. Should only take a second.

**Comment by scalda** [comment]
this is all working for me with 2.4

**Comment by WonderDog** [comment]
Beter Questing might be in Edit mode.  

I noticed that on 2.31 version of foolcraft a new single player world the BQ started in edit mode

Type this command **/bq_admin edit** and it will toggle edit mod on and off.

**Comment by scalda** [comment]
@VonZadian have you fixed this issue if so can you please close
