### ISSUE TITLE
Server setup

### ISSUE THREAD

**Issue by Makin3n** [scalda/FoolCraft#82]
I have tried to setup a server. Every time i try it out there is some mods that doesnt work. Can u release server file that works and it is easy to setup? it would be really nice! And if some1 have ideas how can i fix my problem let me know!

**Comment by scalda** [comment]
Well without a crash report or more information I can't do anything. I updated 5 foolcraft servers this morning with the same 1.2.1 files that are on curse and didn't have a single problem. so please provide more information

**Comment by scalda** [comment]
Hi did you get this working?

**Comment by Makin3n** [comment]
I havent tried it anymore because we made already own modpack/server. But thanks anyways, and i am sure when we get bored, we play foolcraft! love this pack.
