### ISSUE TITLE
Server Files for 2.4?

### ISSUE THREAD

**Issue by SephirothWS** [scalda/FoolCraft#820]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [X] I am requesting help with installing or running the pack

## Issue Description
Server files for 2.4 doesn't seem to exist, are there plans on creating any of those?

## Reproduce Steps
Visit [Here](https://minecraft.curseforge.com/projects/foolcraft/files/2493841)
See no server files.

## Additional Information
Mainly asking for the server files so people can update their servers easier.

**Comment by scalda** [comment]
they will be available today. i like to leave at least 24 hours before doing server files one incase reject the pack. 2 in case anything serious comes up in the pack anyone finds. I have explained this before
