### ISSUE TITLE
Hat stands are bugged

### ISSUE THREAD

**Issue by svennieke** [scalda/FoolCraft#822]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Details
The hat stands from the hat stands mod are bugged, when placing them they output a error message in chat alongside with not removing the placed item from your inventory and duplicating the item.

## Reproduce Steps
Craft and place down a hat stand, or get one from a quest and place it down

**Comment by scalda** [comment]
this is a bug in the mod that doesn't seem to be getting fixed any time soon
