### ISSUE TITLE
Molten Infinity wont drain from EnderIO Fluid Tanks into TC Casting Basins

### ISSUE THREAD

**Issue by Elapsed** [scalda/FoolCraft#823]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I have a cow farm similar to Iskall's on the FC2 server. I have EnderIO fluid tanks draining into Tinker's Construct Casting Basins directly using the "push" setting on the bottom of the fluid tanks. As of the latest patch my Infinity tank wont drain into the Casting basin below it. I made a new tank and basin and still the same issue and only with Infinity (although I only have 10 different blocks in production at the moment)

## Reproduce Steps
Put molten infinity in a EnderIO Fluid Tank over a Tinkers Construct Casting Basin and set the fluid tank to "push" on the bottom side. It wont drain

## Additional Information
![2017-10-25_17 27 12](https://user-images.githubusercontent.com/2513867/32029518-f11754ce-b9a9-11e7-83a4-785224536a15.png)
![2017-10-25_17 27 19](https://user-images.githubusercontent.com/2513867/32029519-f12a0376-b9a9-11e7-940c-2d3d1905fd62.png)
![2017-10-25_17 27 30](https://user-images.githubusercontent.com/2513867/32029520-f14126d2-b9a9-11e7-9a83-3ebfac218a99.png)

**Comment by janf3** [comment]
Casting Infinity blocks/ingots was disabled on purpose. https://github.com/scalda/FoolCraft/issues/701#issuecomment-329832568
(I believe) It was just an oversight in the last two updates to be able to do so.

**Comment by scalda** [comment]
yes this is disabled sorry
