### ISSUE TITLE
cant craft some items

### ISSUE THREAD

**Issue by HamzaNa1** [scalda/FoolCraft#825]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
cant craft some items that i need like AE2 dense cables and more (i dont see them in the NEI)
i tried to reinstall and it didnt work

## Reproduce Steps
i dont know how
it just happens and i cant fix it

**Comment by Mrbysco** [comment]
I believe AE2 is set to Easy mode which disables the need for channels. So dense cables are disabled.

**Comment by HamzaNa1** [comment]
oh what about stuff like other bags pet bags etc... that i see on the series

**Comment by svennieke** [comment]
you can't craft the pet bags and such, they are rare drops from mobs

**Comment by HamzaNa1** [comment]
cant find them in the nei tho

**Comment by HamzaNa1** [comment]
and i have a huge mob farm and i never got the ones that doesnt exist in the nei

**Comment by svennieke** [comment]
the special lootbags are hidden by default in NEI and the creative menu

**Comment by svennieke** [comment]
i get the pet , relic at a decent rate, and once in a few days i get a fools bag, just make sure that the mob dies by a player or a fake player, not by fall damage, fire or anything like that, i personaly use diamond spikes

**Comment by HamzaNa1** [comment]
does mob mashers work ?

**Comment by svennieke** [comment]
they should work
