### ISSUE TITLE
Foolcraft 2 - brutally slow framerates make game uplayable

### ISSUE THREAD

**Issue by skruface** [scalda/FoolCraft#826]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

Hey all,

Pretty new to modded minecraft. Having problems with Foolcraft 2 and brutal framerates. Posted this earlier on /feedthebeast but a mod removed it and messaged me to post it here instead.

- Have uninstalled and reinstalled twitch/minecraft/foolcraft2/java multiple times to try to find problem
- have all latest versions of the above
- have updated sound/video drivers/Win10 to latest

Framerate was abysmally low (2-3 fps) when running the Foolcraft mod, but amazingly the chunk loaded very fast when I hit the ESC key. As the menus come up, I can watch the chunk load pretty quick. As I exit the menus back to the game, loading slows right down again. In unmodded MC, everything runs fine.

I have the twitch settings at the following for Minecraft: Twitch Mod Management: on Release preference: preferred release Launcher Settings: close when game launches Launch Method: native launcher Resolutions: 1024 X 786 Memory Allocation: max recommended - 6144mb Additional java Arguments: none

When I open the Launch Options menu from the Foolcraft launcher, I see the following under jvm arguments (note: I have no idea what any of this means; I just know that Java is an important piece to running this game):
-Xmx6144m -Xms256m -XX:PermSize=256m -Dminecraft.applet.TargetDirectory="C:\Users\jamie\Documents\Curse\Minecraft\Instances\FoolCraft" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US

Once the launcher loads up FC, I have the in-game graphics options set to the following:
Grapics: fast Smooth Lighting: off 3D Analgraph: off GUI Scale: Large Brightness: moody Particles: minimal Use VSYNCH: On Use VBOs: ON Render Distance: 12 chunks Max Framerate: 120fps View Bobbing: off Attack Indicator: crosshairs Clouds: off Fullscreen: off Minimap levels: 4 Entity Shadows: off

System Specs: AMD 8320 8 core processor, MSI 970A Gaming Pro mobo w 16gb ram, Radeon R9 270 GPU (3gb), Win 10 64bit OS

Any help appreciated. I'm not tech savvy (yeah, I'm old as hell) so please be gentle..

**Comment by HamzaNa1** [comment]
you might be running your computer on power saving mode which happened to me and i got the same results (1-5 fps)

**Comment by skruface** [comment]
Thank you for the suggestion, HamzaNa1.  I did not even consider this as I play on a desktop PC.   I double checked it - it was set to balanced, but I changed it to High Performance.  It seems to have made little/no difference.  Screen shot for reference.

![image](https://user-images.githubusercontent.com/31805558/32060432-5be61292-ba34-11e7-8ad2-6043500d0295.png)

**Comment by HamzaNa1** [comment]
u have 60 fps on the screen shot .-.

**Comment by skruface** [comment]
Posted wring screenshot.  Updated.

**Comment by HamzaNa1** [comment]
because its doing nothing while you are in the main menu
btw i see that u have 400 chunk rendered which might be the problem because that's a lot of drawing

**Comment by HamzaNa1** [comment]
https://i.imgur.com/sZukgZ2.png as you can see here i have only 8 (its the C:8/5776) u have 400/10000 which is the problem i think u might have to search it up because i dont know how to fix this

**Comment by Jo-Mamma75** [comment]
I would offer to help here but it looks like @HamzaNa1 is doing it for us.  I can't think of any logical reason why you would be having the problems.  You're running it on a better machine than I'm running and I don't have the same issues.

**Comment by HamzaNa1** [comment]
@Jo-Mamma75 i think he solved it because he stopped answering or he is just busy
his problem is very clear but i couldnt find out how to solve it

**Comment by skruface** [comment]
I'm still here.  I haven't yet figured out why it's loading 400 chunks, or how to prevent it from doing so.

**Comment by DarthSpaceLord** [comment]
I am having this same problem as well, but what is odd is that it also happens on the main screen. I get very low frames through out the game, and it is almost impossible to get anything accomplished. When I am on the main screen that says FoolCraft across the top, it takes around 5 seconds for clicks to register.
