### ISSUE TITLE
New game start impossible because of Halloween Cow - Moo Fluids Mod

### ISSUE THREAD

**Issue by WonderDog** [scalda/FoolCraft#828]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

The Halloween Cow spawns in great numbers and kerb stomps the player in a new game.

## Reproduce Steps

Start a new game in or near a biome that the cows spawn in.

Get too close and you will be swarmed and killed by them.

## Additional Information

They spawn in large numbers (5+ groups of 3), are too fast and have massive HP and very hard to kill with stone or wooden weapons.

If you go peaceful they don't despawn instead you get swarmed by the herd and they get in the way of everything and push you about.  

The only to get away is boat or pillaring up which is hard to do in the first day.

The first new game I started today on Foolcraft 2.4 was in grasslands and after getting jumped and killed out of the blue (Did not even see the cows or realise that they were a danger). They were then close enough to the world spawn they camped the spawn point.  I got killed quite a few times till I turned on peaceful mode.

Also they have killed all the villages in the towns.

Is it possible to reduce the spawn rate, or reduce their agro range, or reduce their HP or disable them.

_I disabled the mod in the Twitch launcher and it removed them and mini moos are still apearing_

**Comment by datitisev** [comment]
The mod of the Hallowing cows is MiniMoos, not fluid moos. You may have disabled the wrong mod.

**Comment by janf3** [comment]
You can disable the HalloweenMoo in the `minimoos.cfg`

**Comment by RicardoTheCoder** [comment]
Halloween Cows are from Moo Fluids. Mini moos adds halloween stuff but they are called, Spooky Moo, Costume Moo and Statues Moo.

Also they dont attack so it seems like a problem with the halloween cows from moo fluids. Im also gonna check for any problem that might be happening because of my mod as soon as I can.

Also I might not be fully understanding your problem but I will try to help the best I can.

**Comment by datitisev** [comment]
Yeah. I saw a lot of costume moos, but none of them attacked. Sorry if I provided incorrect information.

**Comment by iamshift** [comment]
@WonderDog if you're starting a new world in 2.4 or updating from a 2.2+ version I advise you to completly remove MooFluids as is not necessary anymore cause Mini Moos have already replaced old fluid cows.

**Comment by WonderDog** [comment]
@iamshift I have disabled Moo Fluids and it fixed the problerms.  

I realisied since I posted that the problem is probably due to the date (October 27th) and it being close to Halloween and not a change in the mod with the updated pack.

@datitisev the problem seems to only be in new chuncks as they seem to spawn in high numbers in the apropriate biomes.  Numbers seem to be 2 or 3 times more Halloween Cows than the Mini Moos.

I discovered the Costume Moos today and I ran away till I discovered they are passive.

@RicardoTheCoder there seems to be no problems with Mini Moos.  My problem was only with the specific mob the Halloween Cow from Moo Fluids.  In my first new game I started in a grasslands with a close village and probably 20 to 30 of the Halloween Cow within sight.  None were actually at spawn but when I moved to chop trees I got stomped hard multiple times.

**Comment by Jo-Mamma75** [comment]
Actually sounds like a lot of fun. Would've made for an entertaining YT video or stream.

**Comment by WonderDog** [comment]
@Jo-Mamma75 - Yes it is giggle now.  Not so much at the time ;)

I tried that re-creating that world with moo fluids enabled and there is no issue so it is due to date and Halloween stuff.  

I will close this as it has been reported by @RicardoTheCoder to the original mod author.
