### ISSUE TITLE
Foolcraft 2.4 Server lagg

### ISSUE THREAD

**Issue by Colton-Slayden** [scalda/FoolCraft#830]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x] I am requesting help with installing or running the pack

## Issue Description
The the Foolcraft modpack is causing the server to lagg a lot. I am running it on a 8gb online host and only 3 people playing. Massive lag spikes and server says its behind.

## Additional Information
https://pastebin.com/a8b2Z0Lz

**Comment by Jo-Mamma75** [comment]
Have you tried adding TickProfiler to the server and running it to see what is causing the lag?
