### ISSUE TITLE
Slime Boots & Squid pet interaction

### ISSUE THREAD

**Issue by Dactyl49** [scalda/FoolCraft#832]
Insane speed glitch
Slime Boots & Squid pet interaction

- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## Issue Description
With slime boots equipped and the squid inventory pet in the hot bar, if I start bouncing with the boots and land in water I will accelerate exponentially until I run into a block or move into unloaded chunks.

## Reproduce Steps
Start by equipping the slime boots and have the squid inventory pet in your hotbar (fed). Then either start bouncing down a hill or launch yourself with the slime slingshot into a large body of water. An ocean biome works best.

**Comment by scalda** [comment]
this is an unexpected mod interaction nothing can be done within the pack to solve this. sorry
