### ISSUE TITLE
Malisis Doors can destroy FPS

### ISSUE THREAD

**Issue by toxie** [scalda/FoolCraft#833]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
The config option for Malisis Doors "B:config.modifyVanillaDoors=true" which enables animations for vanilla doors/gates/trapdoors can destroy ones FPS fairly easily.

## Reproduce Steps
Start flat world, place down fence gates and watch as your fps drops severely for each fence gate placed down and inside your view. (Seems to only affect fence gates)

## Additional Information
Disabling the animation feature of Malisis Doors would improve fps around villages and places with lots of vanilla door types.

**Comment by scalda** [comment]
thanks i have now turned this off for 2.5
