### ISSUE TITLE
Redstone furnace quest

### ISSUE THREAD

**Issue by kleshas** [scalda/FoolCraft#834]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
I have built a redstone furnace but HQM is not seeing the item.  I tried adding one via JEI, same problem.  I checked the quest via edit mode and re-added the item in my inventory to the 'needed' part of the quest, no effect.

**Comment by svennieke** [comment]
yeah, it is actually a issue, i will take a look at it and fix the issue, i am guessing that all the thermal quests are broken like this one, will try to fix these before next update

**Comment by kleshas** [comment]
Fix:
Edit the quest (type /bq_admin edit in-game).
Click on Tasks, then Retrieval Task.  Change Ignore NBT from false to true.

**Comment by svennieke** [comment]
yeah, this will be fixed in the next update

**Comment by scalda** [comment]
fixed in 2.5
