### ISSUE TITLE
Server crashing from AE2/Colossal Chest

### ISSUE THREAD

**Issue by greatmonkey** [scalda/FoolCraft#835]
Server crashing from AE2/Colossal Chest

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I have 2 issues...

Issues #1 My server is crashing anytime I go to make a stack of anything in the AE2 crafting GUI and it being hook up to a Colossal Chest.  My chest is 16x16x16, I am unsure if this error will be reproduce if the chest size is smaller then that.  My Colossal Chest is also mostly full.  I think it happens when it is trying to grab multiple items in a craft to refill the crafting GUI.

Issues #2 This I think is caused by the Colossal Chest and it is causing the server to lag and slow down.  right now, we have 2 colossal chest on the server, one being 16x16x16 and another one 4x4x4, 2 of these chest because there are 2 players on the server.  The server will crash after it has been running for sometime.

## Reproduce Steps
Issues#1
make a Colossal Chest and fill it with items, hook an AE2 system up to it and craft a stack of something.

## Additional Information
crash date 2017/31
https://pastebin.com/T0qG6qa7

crash date 2017/29
https://pastebin.com/1GJQLPpa
[crash-2017-10-29_03.31.19-server.txt](https://github.com/scalda/FoolCraft/files/1433010/crash-2017-10-29_03.31.19-server.txt)
[crash-2017-11-01_02.41.25-server.txt](https://github.com/scalda/FoolCraft/files/1433011/crash-2017-11-01_02.41.25-server.txt)

**Comment by scalda** [comment]
this is due to a bad incompatibility between AE and colossal chest. sorry for the inconveince
