### ISSUE TITLE
Flat Bedrock

### ISSUE THREAD

**Issue by PlerpIsaiah** [scalda/FoolCraft#836]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
I was just wondering which mod makes the bedrock flat as I was trying to make a smaller modpack for personal use that's less RAM intensive for my friend's computer. (I don't plan to publicly distribute the foolcraft modpack or anything)

## Additional Information
I apologize for posting this in issues since it isn't technically an issue but I didn't know where else to ask.

**Comment by hippietilley** [comment]
The bedrock becomes flat when you use veinminer near the naturally generated bedrock.

**Comment by PlerpIsaiah** [comment]
I just veinmined Straight down to bedrock and its still vanilla. Also, Veinminer only seems to work with certain tools on certain blocks.
![2017-11-01_21 30 32](https://user-images.githubusercontent.com/31831048/32307011-2d915fd8-bf4c-11e7-848e-192952846b49.png)

**Comment by janf3** [comment]
There are a few options/mods which can generate flat bedrock. 

For example CoFH Core which is required for all CoFH mods (e.g Thermal Expansion) has an option to generate flat bedrock. The setting is in the `cofh\core\common.cfg`.

There is also a mod called FlatBedrock for exactly that purpose.

**Comment by PlerpIsaiah** [comment]
Thanks, I found the .cfg file and fixed it. Now Veinminer will be able to be used properly!
