### ISSUE TITLE
Tinker's Cleaver FPS Drop

### ISSUE THREAD

**Issue by Dactyl49** [scalda/FoolCraft#838]
Wielding Tinker's Cleaver Sword causing FPS Drop
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
I have an upgraded Tinkers Construct Cleaver (see screenshots for reference) that causes me to experience a frame drop to a consistent 10-13fps when in my main hand. This happens even when away from my base where I average 25-30fps normally. I have not tried making a new cleaver with different materials yet. Will report info in comments below upon doing so.

## Reproduce Steps
Make same cleaver and wield in main hand??

## Additional Information
I have max recommended RAM allocated (8GB) on twitch/curse launcher, and I have the newest Nvidia graphics drivers installed that don't cause me to black screen on startup. (launching minecraft)

https://imgur.com/gallery/FsNpn

**Comment by scalda** [comment]
just an observation but you aren't using you nvidia GPU

**Comment by Colton-Slayden** [comment]
You are running on a laptop so the cpu performance at only 2.6 GHz could be taking on more load causing the drop in fps
