### ISSUE TITLE
Crash when added the Autospawner from Minefactory Reloaded

### ISSUE THREAD

**Issue by Gidmark** [scalda/FoolCraft#840]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I placed down a newly built minefactory autospawner, and i was thrown out of the multiplayer game, now whenever i try to join i get thrown back to server list. It doesn't seem to crash the server though.
[server log.txt](https://github.com/scalda/FoolCraft/files/1443882/server.log.txt)

## Reproduce Steps
1. Get a Autospawer
2. Place down the autospawner

## Additional Information
See attached file.

**Comment by scalda** [comment]
what is the error you get when you are kicked?

**Comment by Gidmark** [comment]
I got "Connection lost - A fatal error has occured, this connection is terminated - Back to server list". I uploaded the client log as well
[client log.txt](https://github.com/scalda/FoolCraft/files/1447526/client.log.txt)

**Comment by Gidmark** [comment]
Seems to be working fine in 2.5.1
