### ISSUE TITLE
Can't launch world

### ISSUE THREAD

**Issue by Jaciii** [scalda/FoolCraft#841]
When I try to launch my Foolcraft world, it just says: "Loading world, Building terrain" like normal, but it continues to do that, and don't load the world. I have dedicated enough ram. Whats the problem?

**Comment by Mrbysco** [comment]
Why did you get rid of the issue template?

**Comment by Jaciii** [comment]
What do you mean?

**Comment by Jaciii** [comment]
It's the first time I use github... I didn't know what it was...

**Comment by scalda** [comment]
please report the issue using the correct template and also please look through the closed issues to see if your questions have already bee asked thanks
