### ISSUE TITLE
Foolcraft Crash 

### ISSUE THREAD

**Issue by Ceyphe** [scalda/FoolCraft#842]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description

I was trying to give myself some items via JEI/ NEI as I lost my world and wanted to get back to where I was, but realized that JEI was locked in recipe mode with no way to change it even if I actually turn it on in the options. So I looked in the config and checked that it wasn’t locked. It wasn’t. But then in the JEI I saw a world config fodder and there I saw something that may be relevant. So I changed the glass to true for all the worlds for the cheat mode activation lines as I didn’t know which world was mine, although I had only made three and there were 20+. After that I attempted to join my world but it crashed every time consistently after flashing 0%. This only happened in my advanced high tech world not my test worlds. Thank you for reading. Sorry, English is not my first language. 

## Reproduce Steps
Change JEI config to allow item cheating
Attempt to join world

Then you crash 

## Additional Information
 This only occurred in my advanced world with high tech systems.

**Comment by scalda** [comment]
you need to make sure you have cheats enabled in a SP world or a op on a server based world
