### ISSUE TITLE
RFTools builder error - "Chunk Not Available"

### ISSUE THREAD

**Issue by BullUK1** [scalda/FoolCraft#843]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## I've used an RFTools builder quarry in the past without a problem but am running into issues now. I think this might have started when I upgraded to V2.4 but equally that was around the time I was moving out of my first base so it could be coincidence.

- I have Shape Card (Silk Quarry) which is set to 500*500 blocks
- When I insert this into the builder, the Y: value in the middle counts, showing that it's doing some work.
- After a while, that counter stops and the builder shows an error "Chunk Not Available!"
- During that time the builder hasn't placed any blocks into the chest

I thought that maybe I'd moved to the edge of my explored territory and so was hitting ungenerated chunks, so used ChunkGen to generate chunks around me (I used this command "/chunkgen radius ~ ~ 35") me but this didn't help. I've tested this with a few different builders in different spots around my world, but get the same error.

## Additional Information
Initially I posted this issue to the [FeedTheBeast subreddit](https://www.reddit.com/r/feedthebeast/comments/7b442q/rftools_builder_chunk_not_available/) where someone mentioned that it could be that the builder's chunkloading was being blocked. This reminded me of [issue 393](https://github.com/scalda/FoolCraft/issues/393) where you stated that FTBUtils chunkloading had been disabled. I'm posting this here due to the possibility that you inadvertently blocked RFTool's chunkloading at the same time

**Comment by RicardoTheCoder** [comment]
@BullUK1 Most of RF Tool stuff in 1.10.2 is not fully functioning, so I would argue that the chunk loading from the builder might be actually not done yet or simply disabled just like some shield functions. What I would suggest you do is to add another chunk loader to the place you are quarrying and see if it fixed the issue.

Hope this helps.
