### ISSUE TITLE
Iskalium seed?

### ISSUE THREAD

**Issue by Colton-Slayden** [scalda/FoolCraft#845]
## SUGGESTION/HELP
- [x ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Wondering if you guys could make a iskalium seed for mystical aquaculture

**Comment by scalda** [comment]
no sorry as the mod is supposed to make the iskallium rare since it provides basically free power once the reactor is setup
