### ISSUE TITLE
Not getting mini-moos in nether with 2.4?

### ISSUE THREAD

**Issue by EnergySmithe** [scalda/FoolCraft#847]
- [x ] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x ] I can reproduce this issue consistently
     - [x ] In single player
     - [x ] In multiplayer
- [x ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## Issue Description
Downloaded 2.4 client from Curse/Twitch along with the server files and setup fresh server. Was previously running an earlier version of the pack, but it was time to restart. Noticed that we were not getting any mini-moos in the nether on a newly generated random seed and Biomes-O-Plenty.  Created 4 single player random seeds and still do not get any mini-moos in nether, in any of them, went 2000 blocks out.

## Reproduce Steps
Download 2.4 client, create a single player map.  For our players we dont seem to be getting mini-moos in the nether.

Great pack, thanks!

**Comment by WonderDog** [comment]
I agree with this as the demon moos are all I have found in a Single Player 2.4 game.

**Comment by chimeralchimera** [comment]
I've had a similar problem that I've posted on the MiniMoos issue tracker, and I suspect I have this one too and just haven't noticed it yet, since I haven't looked for moos in the Nether yet. What I've noticed, is that in the End, only Forsaken Moos seem to spawn unless I downgrade to an earlier version.

**Comment by EnergySmithe** [comment]
So there is kind of a workaround for the fluid moos in that you can do a powered spawner in overworld and place it in the nether to get those cows.  But it does not get you the demon moos - and so far we are not seeing any of those.  Anyone know how to op spawn a demon moo?

**Comment by Jaciii** [comment]
Maybe they are disabled in the mini moos config?

**Comment by chimeralchimera** [comment]
I don't know about Smithe, but in my case they're not disabled.

**Comment by WonderDog** [comment]
I have seen many demon moos in my game but no fluid moos.

In my world there seems to be a plain of soul sand near my portal often will spawn them.  I think I have captured half a dozen when returning to the overworld.

**Comment by RicardoTheCoder** [comment]
Thank you all for commenting about this issue, @chimeralchimera did in fact presented this problem to me about them not spawning in the End.

The moos were having a problem with another mod on the pack so I remade their spawning conditions, and in my server it seems to be fixed and working, but I have a different set of configurations and stuff that might have some effect on that, or I just didn't notice the problem before.

I will check this as soon as I can, and try to find a solution for the problem. I will comment again as soon as I reach either a solution or a workaround/fix to this issue.

For now you can use a powered-spawner or a auto-spawner with a fluid moo from the overworld either on the nether or in the end to spawn those moos as @EnergySmithe said.

**Comment by RicardoTheCoder** [comment]
An update for all of you, I just uploaded a new version 1.4.1 that should fix those issues. Should be available shortly.

**Comment by EnergySmithe** [comment]
Thanks RicardoTheCoder - awesome mod!

**Comment by scalda** [comment]
I have included the update for mini moos in 2.5.1, uploading pack version to curse now

**Comment by EnergySmithe** [comment]
Thanks scalda - great pack!

**Comment by scalda** [comment]
thanks the 2.5.1 version of the pack is now released so all should be working. @EnergySmithe if you are happy would you please close the issue.

thanks 
scalda

**Comment by EnergySmithe** [comment]
It appears to be fixed in single player with 2.5.1.  How would I apply this to the server side?

**Comment by scalda** [comment]
I am working on the server files as i type this please be patient

**Comment by EnergySmithe** [comment]
Thanks scalda, appreciate all you hard work on this!
