### ISSUE TITLE
Blacked out gui

### ISSUE THREAD

**Issue by steamdemon1512** [scalda/FoolCraft#848]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Every time I go AFK in SMP and Multiplayer my GUI will turn black and become unresponsive but I can see the minecraft world around my character. When I do get a response the FPS drops to around 5 and the gui textures stay blacked out.

## Reproduce Steps
Sit AFK for about 5 to 10 minutes in either SMP or Multiplayer.

## Additional Information
https://imgur.com/a/2kAUv

**Comment by RicardoTheCoder** [comment]
@steamdemon1512 This might be a problem with your graphics drivers, so I would suggest you check if they are installed correctly and updated.

Is there any crash reports? or logs either in the client or on the server? If there is please post that.

Another thing you might check is doing the same test with no chunk loaders active and go to a new place in the world, might be some mod interfering with that and removing it's bugged block, item, stuff might help fixing the problem or finding the culprit.

**Comment by scalda** [comment]
@steamdemon1512 did you have any more info on this issue

**Comment by steamdemon1512** [comment]
I found the issue to be caused by large numbers of of structures built with
chisels n bits and worldspikes used as chunkloaders. This causes Java to do
a video memory dump and large amounts of frame lag. This can be fixed by
switching to the resetting chunkloader that was added to replace the
chunkloader and spotloaders drom chixken chunks.
You can close this but i would like to stay in contact as i will be doing
more research to see if there are any other conflicts.
