### ISSUE TITLE
Iskallium Steel is not craftable - Found (JEI Recipe is incorrect)

### ISSUE THREAD

**Issue by WonderDog** [scalda/FoolCraft#849]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

**Problem Found - JEI Recipe is incorrect see comment below with screenshots**

Can not create Iskallium Steel. Only creates Thermal Foundation steel.
![missing iskallium steel](https://user-images.githubusercontent.com/8510324/32581501-3d6d59e6-c53e-11e7-8f36-e7c436e6ea05.jpg)

## Reproduce Steps
Try to create Iskallium  Steel.  Note that there is only one version showing in the screen shot.

## Additional Information
I tried vanilla crafting table and Tinkers.

I tried to use JEI recipe loader.

I tried using chiesl.

I tried the Thermal Forge book but their is no entry for Iskallium Steel.  I was able to to convert to Railcraft steel.

Could the problem be that the recipie output for steel is 9 ingots and and 4 ingots for Iskallium Steel according to JEI?

May I sugest that you make the recipie require 1 block of Iron and 1 Block or Coal to produce 4 Iskallium Steel Ingots.

I tried cheating in the ingots but when you try to make them blocks they convert to Thermal Foundation steel blocks.

**Comment by svennieke** [comment]
you can use this steel to make the iskalium reactor steel blocks and such i did this before

**Comment by WonderDog** [comment]
Which Steel @svennieke?,  I tried both Railcraft and Thermal Foundation steel withouut sucess.

Also I did have to also cheat in the blocks as I tried cheating in the ingots but when you try to make them blocks they convert to Thermal Foundation steel blocks.

**Comment by svennieke** [comment]
Uhm for me the thermal expansion steel was able to be used to craft the iskalium reactor blocks. but it has been a while since i crafted them

**Comment by scalda** [comment]
this is because you can use other steel to make the iskalluin reactor steel block

**Comment by RicardoTheCoder** [comment]
@WonderDog I can attest to scalda's answer as this works fine on my server, also if you have some scripts on your server but not in the client (might happen because of twitch launcher bugs or if you update manually), you might not see the recipes or event the result of those recipes on the crafting table, making it impossible to actually get the item you want.

So I would say that you should also check that.

Hope this helps to fix the problem.

**Comment by WonderDog** [comment]
# Problem Found - JEI Recipie is incorect

After seeing Iskalla's Video last night I noticed the recipie he used is not the recipie in JEI.  

**JEI Recipie for Iskallium Blocks**
![jei recipe that producesthermal steel blocks](https://user-images.githubusercontent.com/8510324/32693373-2545e99a-c77e-11e7-8f96-fa7a17cac359.jpg)
This produces normal steel blocks.

**I tested the recipie used in yesterdays Yutube video**
![recipe t hat works](https://user-images.githubusercontent.com/8510324/32693390-62b7b3ee-c77e-11e7-96fd-accc83411ff4.jpg)

It works.  It works with any steel as well.

**Comment by RicardoTheCoder** [comment]
@WonderDog this might be a problem with your scripts on the client side, one of those that works with that recipe is not equal to the other. As in my JEI, the second recipe you have shown is the one that appears.

Check the recipes script on both the server and the client and compare them, if the one in the client isn't equal to the one in the server the client will render the wrong recipe on JEI, I would say your scripts are a bit bugged. If you are playing in single player, then the problem may be elsewhere.

**Comment by WonderDog** [comment]
@RicardoTheCoder I don't think it can be the scripts as there seems to be only one set in each profile.  I am in single player and I am sure that the client and internal server use the same files.

The latest screenshots were made in a new clean test 2.51 profile in a new creative testing world.  The only added mod was optifine. I did this in case it was a Twitch update problem.

My game play profile is updated from 2.4 and has optifine and your Mini Moos mod's Cooldown reduced from 40 minutes to 10 as it was way too long with most of the usefully moos now in the nether its generally not worth it as mining is faster and powerful with veinminer.

Also the I originality noticed it issue in 2.4

**Comment by WonderDog** [comment]
Ok I did another clean 2.51 install and the Iscalium block recipe was correct and there was no ingot recipe. It was working :)

I loaded my existing game profile and it had the wrong recipe.  So that profile was broke.

I spent some time and ran diff between the profiles.

_mods_		- Identical + Optifine
_scripts_ 	- Identical
_modpack_	- Identical
_config_	- all but a few files identical, the few diff's were only Timestamps, Hashes, gameplay changes and _\ChanceCubes\CustomRewards\Resourcepack\CustomSounds-Resourcepack.zip_ 

Nothing to indicate what may be causing JEI the problem.

Well I copied my game to the new profile and it now sees the correct recipe.  So the problem was my broken install.

Now when I did the clean install for 2.5, copied my save and deleted the old profile, I wonder if I deleted the wrong one. Or when I updated to a new profile from 2.50 to 2.51

Note the problem was originaly noticed in the 2.4 version.  But that was upgraded from the previous version.

Twitch is not good at multiple profiles of the same mod.  Yes you can rename the profile but unless you rename the folder you can end up with multiple _foolcraft(1), foolcraft(3)..._ folders.  And it is easy to loose track of which is the folder is which profile.

Than you @RicardoTheCoder for pointing me in the correct direction.
