### ISSUE TITLE
Java fails when I try to use RfTools

### ISSUE THREAD

**Issue by yegaG** [scalda/FoolCraft#85]
I had a loading problem were when I tried to load FoolCraft, I would get to phase 2 of initializing and every time Java(Tm) se binary would stop working.. I removed the RfTools .jar file and everything loaded fine.. Wondering if anyone knows why but as long as I dont use rftools , FoolCraft loads fine

**Comment by scalda** [comment]
do you have any sort of crash report or log for this please

**Comment by siredim** [comment]
I have the same issue, Windows 7 and latest 64 bit Java installed. Memory set to 8 gig and it crashes as soon as second initialization starts for RFTools.
[2017-03-29-3.log.gz](https://github.com/scalda/FoolCraft/files/878723/2017-03-29-3.log.gz)

(i hope that paste worked...)

**Comment by scalda** [comment]
Can you please pastebin the crashreports/logs please

**Comment by siredim** [comment]
I will do that as soon as i know which logs you are looking for...  I tried to show you the crash report.. was that a wrong paste?  if so please tell me what you need. (Just a game user here, not a real programmer)

**Comment by siredim** [comment]
ok.. i found a log folder in the modpack, and i will link all the logs in there to this thread:


[logs.zip](https://github.com/scalda/FoolCraft/files/880593/logs.zip)

hopes that helps.

**Comment by scalda** [comment]
please update you  java and gpu drivers and try again please

**Comment by siredim** [comment]
Updating Nvidia drivers seems to have done the trick. GFTools is back oin the pack :)

Thank you.

**Comment by Jo-Mamma75** [comment]
Issue appears to be resolved.  Closing because @scalda is lazy and didn't do it himself.
