### ISSUE TITLE
FoolCraft 2.5, crashing on fresh install missing [LunatriusCore]

### ISSUE THREAD

**Issue by graycatgrayhat** [scalda/FoolCraft#850]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
With a fresh install of FoolCraft 2.5 crash because of missing LunatriusCore.

## Reproduce Steps
Clean install FoolCraft 2.5, launch pack.

**Comment by JTKillien** [comment]
I am also running into this issue after recent update. See attached Screen Shot.
![2017-11-09_21 49 44](https://user-images.githubusercontent.com/29414647/32640834-9b7233fe-c598-11e7-81a3-c401c6e821e2.png)

**Comment by scalda** [comment]
I am uploading 2.5.1 with a fix now to curse

**Comment by scalda** [comment]
2.5.1 is now out so i will now close this issue
