### ISSUE TITLE
Ranchable Fluid Cows

### ISSUE THREAD

**Issue by Gunvaldfar** [scalda/FoolCraft#851]
<!-->
- [ x] I am running the latest version of FoolCraft
- [x ] I am running FoolCraft via Curse/Twitch Launcher
U have removed moofluids - is the rancheable fluid cows necessary now or have u forgotten to remove this mod also?

**Comment by scalda** [comment]
The mod is no longer in the pack so i'm not sure why you still have it

**Comment by RicardoTheCoder** [comment]
@Gunvaldfar @scalda Sometimes the Twitch Launcher bugs out when updating modpacks and it leaves some mods that were removed and sometimes older versions of already updated mods.

@Gunvaldfar I would suggest reinstalling the pack to another profile and check if the issue remains.

**Comment by Gunvaldfar** [comment]
thx - it was a twitch-glitch ;-)
