### ISSUE TITLE
Angel Ring does not work when you fly far away

### ISSUE THREAD

**Issue by chady33** [scalda/FoolCraft#852]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description 
![2017-11-10_19 15 42](https://user-images.githubusercontent.com/33556233/32674676-21a1d0de-c64c-11e7-8366-2b6ff3d82e17.png)
![2017-11-10_19 15 56](https://user-images.githubusercontent.com/33556233/32674677-21d758bc-c64c-11e7-9cba-8b21f0e16c4a.png)
![2017-11-10_19 17 53](https://user-images.githubusercontent.com/33556233/32674678-21fd0206-c64c-11e7-8cfe-3de468c25db4.png)
i have a Angel Ring to fly but when i get so far away from my base the Angel Ring runs out of GP, in the last update i got it working with chuckloader but you have remove the mod

**Comment by scalda** [comment]
Look at the witching gadget chunk loader

**Comment by chady33** [comment]
yea that works fine now with the weirding gadget thanks for your help and time
