### ISSUE TITLE
Drum cheat

### ISSUE THREAD

**Issue by Riki9811** [scalda/FoolCraft#856]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
You can cheat the Extra Utilities drum and obtain infinite amount of it. I managed to get around 26,796 drums having just 2 at the beginning.

## Reproduce Steps
1. Take at least two empty drums (any kind)
2. Fill them with every liquid you want (the must be filled with same liquid adn amount so that they stack together)
3. Put them in crafting grid to turn them into empty drums
4. Shift click the result of the crafting and you obtain a lot more!
(example: starting from 2 you get 3, from 3 to 6, and so on)

## Additional Information
![2017-11-12_21 13 49](https://user-images.githubusercontent.com/33606510/32703197-8dd48a06-c7f2-11e7-8f5f-1de93435bf89.png)
![2017-11-12_21 14 03](https://user-images.githubusercontent.com/33606510/32703183-6699df04-c7f2-11e7-8764-c8ca664a7a22.png)
![2017-11-12_21 14 27](https://user-images.githubusercontent.com/33606510/32703188-76378394-c7f2-11e7-924d-563468188d7b.png)

**Comment by BrisingrAerowing** [comment]
This was reported to Extra Utilities issue tracker already as well.
Ref rwtema/extrautilities#1688

**Comment by scalda** [comment]
i don't know how you all are doing this but i can't do it for the life of me
