### ISSUE TITLE
Placing Item from Architecture Craft crashing game

### ISSUE THREAD

**Issue by BeeDecay** [scalda/FoolCraft#858]
- x I am running the latest version of FoolCraft
- x I am running FoolCraft via Curse/Twitch Launcher
- x I can reproduce this issue consistently
     - x In single player
     - [ ] In multiplayer
- 1 I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- x I am crashing and can provide my crash report(s)

SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- x I am requesting help with installing or running the pack

Architecture Craft crashing game?
The game crashes sometimes when placing a block from the architecture craft. I stopped it previously by placing the block from a different direction then using the hammer on it. 
It seems to be happening only in certain locations. 
I can place the same block on a different location without the game crashing. I even tried pushing the block with a piston into the location but piston wouldn't push it. I even thought that it was being caused by the block I was placing it on or against so I switched out those blocks to different types but that didn't make a difference either.

REPRODUCE STEPS
Place the block Iconic Capital from the classical category on the saw table from Architecture Craft in different locations looking in different directions.

ADDITIONAL INFORMATION 
https://imgur.com/a/e9hYR

[crash-2017-11-05_08.31.35-client.txt](https://github.com/scalda/FoolCraft/files/1467191/crash-2017-11-05_08.31.35-client.txt)
[crash-2017-11-05_08.35.34-client.txt](https://github.com/scalda/FoolCraft/files/1467192/crash-2017-11-05_08.35.34-client.txt)
[crash-2017-11-05_14.05.20-client.txt](https://github.com/scalda/FoolCraft/files/1467193/crash-2017-11-05_14.05.20-client.txt)
[crash-2017-11-05_14.10.09-client.txt](https://github.com/scalda/FoolCraft/files/1467194/crash-2017-11-05_14.10.09-client.txt)
[crash-2017-11-05_14.25.30-client.txt](https://github.com/scalda/FoolCraft/files/1467195/crash-2017-11-05_14.25.30-client.txt)
[crash-2017-11-05_14.33.19-client.txt](https://github.com/scalda/FoolCraft/files/1467196/crash-2017-11-05_14.33.19-client.txt)
[crash-2017-11-05_14.38.17-client.txt](https://github.com/scalda/FoolCraft/files/1467197/crash-2017-11-05_14.38.17-client.txt)
[crash-2017-11-06_20.15.02-client.txt](https://github.com/scalda/FoolCraft/files/1467198/crash-2017-11-06_20.15.02-client.txt)
[crash-2017-11-06_20.21.57-client.txt](https://github.com/scalda/FoolCraft/files/1467199/crash-2017-11-06_20.21.57-client.txt)
[crash-2017-11-06_20.41.35-client.txt](https://github.com/scalda/FoolCraft/files/1467200/crash-2017-11-06_20.41.35-client.txt)
[crash-2017-11-06_20.46.36-client.txt](https://github.com/scalda/FoolCraft/files/1467201/crash-2017-11-06_20.46.36-client.txt)
[crash-2017-11-13_09.58.59-client.txt](https://github.com/scalda/FoolCraft/files/1467202/crash-2017-11-13_09.58.59-client.txt)

**Comment by scalda** [comment]
Is there any C&b blocks next to that block space? If so then that is your
problem

**Comment by BeeDecay** [comment]
Nope, I made sure of it. All vanilla blocks surrounding it.

**Comment by scalda** [comment]
any update on this? if sorted please close the issue
