### ISSUE TITLE
Unable to run maximized windowed mode, and Windows Magnifier in Foolcraft

### ISSUE THREAD

**Issue by ThomasGrillo1701** [scalda/FoolCraft#859]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

**Comment by svennieke** [comment]
this might not be a direct fix for your issue, but would something like borderless gaming be something that might be able to help you with the issue? this is basicly a program that puts any fullscreen game in to a fullscreen borderless windowed mode.

**Comment by ThomasGrillo1701** [comment]
Hello Scalda. I’ve not heard of that program. If it will allow Windows Magnifier to run, with the game in a near fullscreen, windowed mode, then perhaps it might help.

To get an example of exactly what I’m on about, run The Simple Life 2 modpack, which Iskall85 has been running. It does allow me to run maximized windowed mode, but there’s still a blue title bar, at the top. It will let me run Windows Magnifer, and read the in-game manuals without problems.

However, Foolcraft absolutely will NOT let me run maximized windowed mode. Only the tiny little window mode, for whatever reason, so that program won’t matter, in this particular instance.

Thanks.

Thomas Grillo

**Comment by Colton-Slayden** [comment]
https://minecraft.curseforge.com/projects/fullscreen-windowed-borderless-for-minecraft

**Comment by ThomasGrillo1701** [comment]
I have the file, but no instructions for installing it.

Thomas Grillo

**Comment by ThomasGrillo1701** [comment]
I tried the Window Borderless program. I still can’t get Foolcraft running in maximized windowed mode. This means Foolcraft is non-compliant with ADA, because I can’t use Windows Magnifier, if I can’t run maximized windowed mode. All Foolcraft does is allows a tiny little window to be displayed. All other mods I have installed, like Quark, Simple Life 2, will let me run maximized windowed mode.

Thanks.

Thomas Grillo

**Comment by ThomasGrillo1701** [comment]
I tried the FullscreenWindowed file in the mods folder for Fullcraft 2, and it won’t even let the game launch, because it wants 1.12. It won’t run in 1.10x, which is what Fullcraft uses.

Anything else that might work? That doesn’t require rocket science licenses to install?

Thanks,

Thomas Grillo

**Comment by ThomasGrillo1701** [comment]
Hello. After a bit of searching, I learned I had to simply drop the mod (jar file) into the mods folder of the mod I needed to make ADA compliant.
I also found the version that works with Foolcraft (1.10.2), and am now able to run maximized windowed mode, with Windows Magnifier, as needed to read the in-game manuals with.

Sorry about my attitude, earlier. just frustrated.

Thanks for pointing me to the FullscreenWindowed file. I now have both versions. I’m guessing it was included in a couple of other mods I have, which do allow Windows Magnifier to run.

Keep up the great works!

All the best,

Thomas Grillo

**Comment by svennieke** [comment]
No issues, i would have helped you but i was asleep during that time, i am sorry. and if you want http://store.steampowered.com/app/388080/Borderless_Gaming/ this is a app i am using, there is also a free version of this by the same developer but i can't remember the link, but this automatically will put any game in to a fullscreen borderless mode. i realy hope this might help you out.

Greetings svennieke

**Comment by Mrbysco** [comment]
^http://westechsolutions.net/sites/WindowedBorderlessGaming/ is the free version I believe

**Comment by ThomasGrillo1701** [comment]
Hello Svenieke. No worries, I forgot you’re about 7 hours ahead of me. 
I greatly appreciate all your help. I was able to get FullscreenWindowed to work, just had to use the version that was compatible with Foolcraft, was all.

I’ll certainly look into the program you’re using, too.

All the best, and thanks.

Thomas Grillo
