### ISSUE TITLE
Stops at entity render 3/7 5/5

### ISSUE THREAD

**Issue by Somewonisme** [scalda/FoolCraft#860]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
Whenever I try to load the pack it gets stopped at 3/7 5/5 entity render I am not running any additional mods I have the amount of ram required, it does not crash it just gets stopped and I am forced to close it

## Reproduce Steps
I can reproduce this crash by just loading the game

**Comment by scalda** [comment]
need a crash report to point out the problem

**Comment by scalda** [comment]
not heard anything here for 27 days so will be closing
