### ISSUE TITLE
Crash on loading the map

### ISSUE THREAD

**Issue by LordCadbury** [scalda/FoolCraft#861]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Started to crash when it goes to load the world. Loading terrain 0% then crashes

## Additional Information
 Does not work on older versions, but works if i make a new world. Last thing I done was AE2 import/export. closed game normally. now it wont load. spend 3 hours trying to figure it out, not sure what Im doing. any help would be appreciated.

<script src="https://pastebin.com/embed_js/6CAmcUra"></script>

**Comment by LordCadbury** [comment]
[crash-2017-11-16_11.44.40-server.txt](https://github.com/scalda/FoolCraft/files/1480349/crash-2017-11-16_11.44.40-server.txt)

**Comment by andrelinslima** [comment]
Based on the crash log, sounds like you have imported a WarpStone into your ME system. it is crashing your game when trying initialize the me system with information from this item.
I don`t know if removing the waystone mod would cause you other problems, but you can try to do it just to remove the item from ME system without crashing.

**Comment by LordCadbury** [comment]
Yep that done the trick. Removed the mod and it loaded up. Will test and try to reinstall tonight. 
appreciate the help.

**Comment by LordCadbury** [comment]
After removing the mod so it will load how can i remove the waystone from the system? Is there a file with all the contents of the ME system?
