### ISSUE TITLE
FC ver2.5.1 - Mini-moo Cooldown 30min+

### ISSUE THREAD

**Issue by johnwolf01** [scalda/FoolCraft#863]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

Personally I think that the cool down time of the mini moo's is a bit to long.
I do agree that the previous 2 min Cool down was fast, but 30+ mins for 8 ingots is a bit harsh.
Taking in consideration that the same materials can be produced much faster by growing crops.
This cool down time is not in balance with Mystical Agriculture and should be Reconfigured.
Currently I would avoid the cows entirely due to this. making the mod obsolete and a waste to even use it.

 I recommend (if possible)
- Base ores 5 min 
(iron, copper, tin, Aluminium exct. )
- Advanced Alloys 8+ 
 ( Energetic Alloy, Electrical Steel, Steel, exct.)

**Comment by Vertigo81** [comment]
Feels a lot more balanced this way to me.  Plus you can’t improve the times with items.

**Comment by johnwolf01** [comment]
Well I have done some testing. I can grow and craft 9 ingots in 10min using mystical essence compared to the 8 every 30 min with cows. 
_But I changed my minimoo.cfg config file from 2400 ticks to 400 ticks._ that improved it for me.

As for my reasoning in the above  _suggestion_ .. ^^
Remember you still need a good supply rate for some of the materials to craft your singularity's.
waiting 1 week AFK to gather enough resources to create maybe 1 singularity is way to long for me. 
On a server it may be fine, since the server is always running, but single player where a player occasionally load the game, play for 3-4 hrs. Those rates will extend into months.

Note this is Per Mini Moo. True I can breed a whole herd of them but that just adds to lag especially if most players do this on a server. For server TPS it is better to have fast material production rates rather than large amounts of lag causing entities.  We had similar issues regularly on Project Ozone 2 Servers, Its not nice logging into a server with 10 players online and it lags so bad and the TPS is 10-12 or less.

This Post is a "Suggestion" not a bug or error and only serve the purpose of reconsideration, Nothing more. 

Have a great great day

**Comment by RicardoTheCoder** [comment]
@johnwolf01 Actually there seems to have been a problem in the config that set that value to 2400 as it should be 120. I don't know what made it as it happened once in the dev environment and never again, it seems that same problem might have happened on the pack's config.

**Comment by scalda** [comment]
i will reset this back to default for 2.6
