### ISSUE TITLE
Mods to add for version 3.0.0 1.12.2 Version

### ISSUE THREAD

**Issue by AutisticMC** [scalda/FoolCraft#864]
## SUGGESTION/HELP
- [x ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Going add The following mods to this and hope they will be added:

1. Ruins and Constructs
2. Ruins
3. Cyclics
4. Normandic Tents
5. JurassicCraft 2.0
6. Fossil and Archeology
7. Youtuber+
8. RopeBridges
9. Ancient Warfare 2
10.  Steves Carts
11. Steve Galaxy
12. GalaciticCraft
13. GalaciticCraft Planets
14. Mo Creature
15. Blood Magic
16. Thamucraft
17. TrainsCraft
18. Adventures Backpacks
19. Biblocraft 
(1.12 Version)

## Reproduce Steps

Click on the .jar and .zip files
Here's some mods i would love to add:
[Trains world-1.0 (1).zip](https://github.com/scalda/FoolCraft/files/1528048/Trains.world-1.0.1.zip)

**Comment by Kiobito** [comment]
Buildcraft is an amazing mod that I feel would fit in well with this pack. it is compatible with most if not all of the current mods already in the pack and adds a lot of functionality

**Comment by AutisticMC** [comment]
[Ruins-1.11.zip](https://github.com/scalda/FoolCraft/files/1528008/Ruins-1.11.zip)

**Comment by scalda** [comment]
sorry but none of these mods will make it into foolcraft
