### ISSUE TITLE
Can’t get too cute to ignore quest to register cow kills.

### ISSUE THREAD

**Issue by Vertigo81** [scalda/FoolCraft#865]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Additional Information

I saw on iskall clip he was having the same issue, but eventually the kills registered after opening and closing the quest GUI.  For me it’s not the case.  Killed hundreds of fluid cows of various types, spooky, costumed, various fluids, holy, don “something” specially named ones, but the quest remains at 0\64whatever I do.  

Tried opening it to lan to make it multi player, killing them via different methods, but nothing I do seems to register.

**Comment by svennieke** [comment]
the only cows that count are the mini moo fluid cows, custume cows, maffia reference cows and others don't count

**Comment by svennieke** [comment]
also what are you using to kill them? if i know this i can test this out in my testworld

**Comment by Tegwen** [comment]
I had the same issue.  I saw someone mention that the better questing was in edit mode.  So I had to run /bq_admin edit.  Once I did that it turned off edit mode and those kill quests finally started registering for me.  Hope that helps.

**Comment by svennieke** [comment]
@Tegwen this is most likely the issue, i will do my best to try and make sure the pack does not get a update with the questing mod on edit mode still, it is just a lot of work that we tend to forget these little things
sorry

**Comment by Vertigo81** [comment]
9/10 of the kills were fluid moos of various types.  I haven’t been to the end yet, but overworked and Nether moos weren’t working.

I mostly used a shuriken, but also lots of kills with various swords, a few with bare hands, and a couple I dropped off a cliff (tried to be thorough)

I didn’t know edit mode was a thing...  I’ll try that :)

**Comment by Vertigo81** [comment]
That was totally it, all better now
