### ISSUE TITLE
Can't create a superflat world

### ISSUE THREAD

**Issue by GrandiaKnight** [scalda/FoolCraft#868]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description

For some reason whenever I try to create a superflat world for some creative testing when I click done the world type defaults to Biomes a Plenty and it resets any changes I make to the superflat world profile I make. Any advice?

## Reproduce Steps

1) Change new world to creative
2) Go to world settings
3) Choose superflat
4)Pick any preset
5) Click done
^) The world type will now say Biomes a Plenty

**Comment by GrandiaKnight** [comment]
Oh OK. Thanks. I'll check the config files.

**Comment by scalda** [comment]
i have changed this for pack version 2.6
