### ISSUE TITLE
Game crashed while I was in the nether and now the world won't load

### ISSUE THREAD

**Issue by SharkBaitRFSR** [scalda/FoolCraft#869]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I was walking in the nether. I had been building a mod farm and had died I managed to retrieve my items and was walking in a nether fortress and the game crashed. Now my game will not load it loads everything and I get to the building terrain screen and it crashes again.

## Additional Information
The first is the original crash:
https://pastebin.com/3CBf036W
the following is the latest crash report:
https://pastebin.com/HLkm79x7
at least one of the reports said that the entity was a spider.

**Comment by scalda** [comment]
the first crash is a AE storage bus and the 2nd is a issue between a AE light fixture and a themaldynamics duct

**Comment by scalda** [comment]
not heard anything here for 27 days so will be closing
