### ISSUE TITLE
Smeltery Forge Table not assembling

### ISSUE THREAD

**Issue by DkOmbres** [scalda/FoolCraft#87]
I have made all three parts to the alumite pickaxe, the forge table will not accept the binding or rod. I then made severl different types of bindings and rods, I can get the rod, pickaxe head onto the table but not the binding. I have read every website explaining proccess, watched all videos, done everything the same and it is still not working.

**Comment by scalda** [comment]
Please provided screenshots

**Comment by DkOmbres** [comment]
I'm not sure what good this will do as my post stated everything. Trying to make the Alumite pickaxe. Made all 3 pieces, can only place the pickaxe head on table but the others will not place. If I use a different rod such as Obsidian, it will place. Still no Bindings will place at all.
![2017-03-27_11 42 29](https://cloud.githubusercontent.com/assets/26676079/24365447/efa9bd56-12e3-11e7-98a0-499691108a62.png)
![2017-03-27_11 42 37](https://cloud.githubusercontent.com/assets/26676079/24365457/f47e8b04-12e3-11e7-92d2-5799d659d47d.png)

![2017-03-27_11 41 59](https://cloud.githubusercontent.com/assets/26676079/24365423/df4422da-12e3-11e7-914c-262b281a5881.png)
![2017-03-27_11 42 11](https://cloud.githubusercontent.com/assets/26676079/24365431/e50d0128-12e3-11e7-9857-f570a0f519ba.png)
![2017-03-27_11 42 18](https://cloud.githubusercontent.com/assets/26676079/24365434/e7513936-12e3-11e7-84ca-6cf9e28b1d6e.png)
![2017-03-27_11 42 24](https://cloud.githubusercontent.com/assets/26676079/24365441/eb50f8c8-12e3-11e7-9025-cda9742fe3c4.png)

**Comment by scalda** [comment]
you have used a tough binding not a normal one
