### ISSUE TITLE
The last item I put in my storage system disappears when I close the world

### ISSUE THREAD

**Issue by Xalveris** [scalda/FoolCraft#870]
## Issue Description

My current storage system setup is a minimal AE2 system linked via external storage to a 15-block colossal chest. Whenever I save and quit the world, the last type of item I put into the system disappears. Putting in more of an item that already exists removes the amount that was last put in (ex. I already have 2 sponge in the system. Putting in 32 more sponge then reproducing the issue will remove those 32 I just put in, leaving the original 2 sponge.) Putting items directly into the chest, or opening the chest after they have been put in using the AE2 system, stops the items from being removed.

After further testing in a creative world, it's being consistent with certain items and not with others. In the new world I made to test this, redstone torches will always be removed while other items will not. I don't know if this will be the same for anyone else trying to reproduce it, but it may take several tries with different items to get it to happen. Whether the size of the chest and number of other items affects this is unclear for me.

## Reproduce Steps

1. Hook up an AE2 system to a colossal chest with an external storage bus
2. Put a large amount of different items via the AE2 terminal
3. save and quit the world
4. load the world back
5. put more items in
3. quit/load
5. The last type and number of items that were put into the system are gone

## Additional Information
My survival storage setup, but this doesn't seem to matter:
https://imgur.com/oYS1uWT

Creative test setup:
https://imgur.com/a/4BBrk

**Comment by scalda** [comment]
looks like this is a bad compatibility issue between the 2 mods i would advise to move away from the colossal chest in favor of ae drives
