### ISSUE TITLE
iskallium reactor changing blocks??

### ISSUE THREAD

**Issue by Vertigo81** [scalda/FoolCraft#871]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

This is very weird, and cosmetic, but I figured I should make a note regardless.  But so far at least four times now, the smooth stone around my small iskallium reactor has changed to cobble.

I haven’t watched it happening.  In every occaision it’s happened while I was afk (single player so no one is coming by and doing it while I’m not looking).  I have a 3x3 very small reactor, occupying the space in a 3 tall room, so it’s resting on a smooth stone floor, touching a smooth stone ceiling.  If I leave it running and return hours later the 5x5 under and above the reactor has become cobblestone.

Is this intended and I just can’t find documentation?  It’s really, really strange.  I haven’t tried different materials yet, and I’m stuck in a hospital today so I can’t till tomorrow, just figured I’d file this while I’m sitting around.

**Comment by Necro9227** [comment]
Now that you bring it up, the same thing might have happened to me as well, i just thought i missed a load of cobble when filling in gaps with stone in the ceiling of the room under my reactor.

**Comment by Vertigo81** [comment]
So far it’s only happening with smooth stone.  I’ve tried chiseled stone and stone bricks, sandstone, few other things but only seems to be the one thing...

It’s just such a WEIRD thing for it to be a bug.  I can’t imagine how that would work

**Comment by Necro9227** [comment]
After doing some testing at tick speed 2000, i can confirm the reactor does indeed convert any block that is ore-dictionary with Minecraft:Stone [stone, granite, andersite, diorite and all polished variants] that is is touching (including corners) into cobblestone.

**Comment by scalda** [comment]
this is because iskallium has the ability to corrode things as to go along with the lore that has been created over the last year or so during iskalls videos and such
