### ISSUE TITLE
FoamFix and more

### ISSUE THREAD

**Issue by Inzult54312** [scalda/FoolCraft#872]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

Hey, I would like to see some more mods such as foamfix to help with lag and memory of Foolcraft. While I love to play it, I just can't for long periods of time. I wish it could be more potato friendly, but will any mods fix it?

**Comment by jkdoug** [comment]
You know foamfix is already in the pack, right?

**Comment by scalda** [comment]
foamfix is in the pack already as for anything else to make it run smother there is plenty of information if you google it. as this is not an issue relating to the pack I will be closing it
