### ISSUE TITLE
FoolCraft Questing "Bugs"? vs Working as Intended in Getting Started

### ISSUE THREAD

**Issue by DeliversKarma** [scalda/FoolCraft#873]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

I have searched for information regarding the quest system, trying to see if it's been tested and is actually "working as intended" vs. "This is FoolCraft, so of course we're expecting ridiculousness from you because of the insane mod that it is..." Since I haven't found anyone else complaining about the quest system, I wanted to try to get verification for is the FoolCraft questing still lacking testing vs. yes, it is working as intended.

On my server, I "was assigned" the task to complete the "Getting Started" quests, which ends of course with the "Create your won (own?) Kitchen" and has all those kitchen items that must be created in order to 100% complete this section. 

With the tool rack item and the milk jar (especially the milk jar), there seems to be some question on valid ingredients to actually create these objects.  The tool rack shows 2 iron nuggets and 3 wooden slabs of any kind. However, it isn't until I made "railroad iron nuggets" that it would actually accept the quest as complete.  (iron nuggets + dirt ??) 

With the milk jar, the recipe shows "Milk" surrounded by any kind of glass and 1 wooden plank of any variety, but this "recipe" appears to be super high end "tech" requiring the mystical agricultural version of "Milk" vs. milk in a bucket from a Mini Moo.    

So, I guess my question is: Did you mean for Getting Started to go this high tech route requiring mystical milk or is this an oversight and normal milk in a bucket should be accepted as valid "milk" ?  Or is it because it's "FoolCraft" that you are pushing the players to the very extreme in the first quest section, because it's the very final quest in that line?

## Additional Information

Anyways - sorry if this isn't even the right place to be questioning/commenting - but I'm really new to Mods for Minecraft altogether, so I've been struggling to find the right place. I might post this to reddit as well in hopes that I'll get an answer.   Thanks for the fun so far!

- Karma

**Comment by svennieke** [comment]
this is the right place to ask these kinds of stuff as it seems like if these things are realy not working this is in fact a bug with the questing mod itself (had a lot of issues with it so far already when creating the quests), i also want to thank you for pointing out the typo in the won kitchen questline, it should in fact be own kitchen, i will do my best to fix these quests (might even split them up in to a new questline)
The milk should have been accepted, the same with the tool rack, but this will be a thing i will take a look at, and in General i will try to make the quests not be a ridiculous grind as that is not as much fun than. Basically the "this is Foolcraft so it should be ridiculous " is something i want to avoid as much as i can, i know currently there are still some grindy quests in there but trust me i will change them at some point, making quests slowed down for a bit beacuse of school and other IRL things, so i am sorry for the issues, but i will fix them once i know about them, so please keep reporting them 
:D 

*Svennieke

**Comment by svennieke** [comment]
regarding the food items, that was just done in a way so you get some extra food, but i did not want to delete the food you made/got for the quest. there are some exceptions to this.

about the server i can't realy give you an answer to, i only know of the foolcraft server, played by the foolcrafters but i am sure @scalda can give you more info about this.

also foolcraft is not a mod itself, it is a collection of mods, that the pack makers have put together, tweaked and tested, this explains why there are bugs with certain things like the questing mod as they can not change the source code of the individual mods to fix them, there are some mod devs that work together with the foolcraft dev team, for example me with my statues mod. but the biggest issue is a lot of mods moved to 1.12 meaning it is not likely that certain bugs might get fixed.

Thank you for the Kind words, and i can only encourage you to play the pack, and to break the quests i made... wait no please don't break them ;p

**Comment by DeliversKarma** [comment]
Ahhh - thank you so very much with the explanations.  I have to admit, I am truly a mod-noob... I would have considered myself a pure vanilla girl until I got frustrated with my inability to focus long enough to "beat vanilla properly", so I decided to look into the amazing options of mods.  

Being I'm not an overly codey-type, I still think I understand the basics of how the FC combining of all sorts of mods-system works, and yes, I can also imagine that there are PLENTY of issues with trying to integrate everyone's code with XX number of different code writers and everyone invariably having their own style to an extent.  

(I don't even know what you meant about your statues mod since I'm such a noob, sooo yeah, uh, I'll have to try to check it out - unless you invite me to see a private tour of your amazing creations :)  

AND - I *did* ask some of the FC folks about getting an invite to their server, but per FalseSymmetry on Twitter, it seems like they're not inviting random guests (which I kind of got that impression) - I'm not a fangirl type, and I don't really watch or follow any streamers or YouTubers. I just look up stuff that I feel I need to look up.

I personally have never seen any real entertainment value in watching others play a game I could personally be playing, so yeah, I know that may sound strange, but I don't enjoy watching streamers XD   Which then means I wouldn't follow or donate money to them - and of course therefore don't get invitations to their parties XD 

Hey, I offered to barter out my own personal knowledge, skills and talents for an invite to the server, but -shrugs-  Guess they aren't interested in what I might be able to add.  Pity.  If they only knew what they were missing XD

THANK YOU AGAIN for being so responsive here. I really appreciate when creators are involved with their "clients" - it speaks a lot for you and your dedication. 

Cheers,

Karma

**Comment by svennieke** [comment]
Did we not all start with modded at some point not knowing what we did? i remember my first time in modded, no real tutorials, video's or other things to be found as easy as it is now, and that was a fun expirience, never thought i could enjoy modded as much as i do now years later, did not even think that i would be able (with help) to make my own mod ( https://minecraft.curseforge.com/projects/statues ) that is the statues mod btw, it is also in the pack at some point you will come across it, and it has a nice questline written by me ;p

i would offer you a private tour, but i will be honest the quests i put in Foolcraft about the statues mod could be considered a private tour, i sadly have no easy access to a server so i can't realy show you the in and out of the mod.

And i out of the bottom of my heart, thank you for the kind words, people like you make creating modpacks, mods, maps, and vanilla things more enjoyable it realy motivates others, so realy thank you a lot
