### ISSUE TITLE
Mushroom cows not spawn (only Mini Moo)

### ISSUE THREAD

**Issue by Lexon78** [scalda/FoolCraft#874]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
For quest i must kill 64 Mushroom Cows, but this cow is spawn only if world is generated. I found two Mushroom Islands and on both was only MiniMoo and no one Mushroom Cow. 
Can be this cow spawned?

## Reproduce Steps
I fond two island with same result (i use Biome finder from BoP mod)

**Comment by scalda** [comment]
this is fixed in 2.6 of foolcraft there has been a fix within minimoos
