### ISSUE TITLE
Version 2.5.1 Crashing on Startup

### ISSUE THREAD

**Issue by ItsMisterPie** [scalda/FoolCraft#875]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Every time the client loads to "ModelManager", it causes a crash. This is before even getting to the main menu.

## Reproduce Steps
1. Launch game
2. Press play
3. Crash

## Additional Information
The crash report
https://pastebin.com/w3U7vZaL

**Comment by scalda** [comment]
you instance ran out of memory you need at least 6GB ram to run the pack
