### ISSUE TITLE
Foolcraft 2.5.1 Server has suddenly started crashing on launch

### ISSUE THREAD

**Issue by joecarpita** [scalda/FoolCraft#876]
## SUGGESTION/HELP
- X I am requesting help with installing or running the pack

It's very odd but about three days ago my Foolcraft server has suddenly start crashing upon launch. This all started 3 days ago, no changes were made to the Foolcraft folder (to my knowledge) and I cannot understand the log file.

1. Start foolcraft server from start.bat

Crash Report log - https://pastebin.com/EyYASAna

**EDIT:**
Restoring the world from the last backup seemed to solve the problem, I'm able to start the Foolcraft server now no problem.

**Comment by scalda** [comment]
this was due to a bad energy cell being place somewhere, but i'm glad you got it fixed
