### ISSUE TITLE
Cant Download foolcraft please help

### ISSUE THREAD

**Issue by OGDojo** [scalda/FoolCraft#877]
- [ x] I am running the latest version of FoolCraft
- [x ] I am running FoolCraft via Curse/Twitch Launcher
- [ x] I can reproduce this issue consistently
     - [x ] In single player
     - [ x] In multiplayer
- [ x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
I have been playing fool craft for as long as the mod has been out, i have been playing with my brother and my friend and have had a lot of fun, HOWEVER! in the last 2 days i have had some bugs happen, first is that i try smelting things (Like quartz to make silicon or cobblestone to make stone) and it wouldnt smelt, even in a vanilla furnace or in the alloy smelter, yes the alloy smelter had power, also the loot bag recycler wouldnt let me set it up to make Trash Bags, THEN after i had that bug i uninstalled it, hoping to start over (Please note that i downloaded a secondary profile just to test to see if i was going crazy or not) but now i get an error pictured in the link below

And now that i have posted this it decides to re-download the mod pack....

## Reproduce Steps
its litterally i try clicking the button for install (Both in and out of the information screen) and it will still pull up the error in the link below

## Additional Information

https://imgur.com/a/PvW9b

**Comment by scalda** [comment]
did you get this sorted?? if so please close the issue

**Comment by scalda** [comment]
not heard anything here for 27 days so will be closing
