### ISSUE TITLE
Weapon loot crates and their contents come up a small dot pattern. Also copper nuggets do this. 

### ISSUE THREAD

**Issue by Xelabor** [scalda/FoolCraft#878]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
Weapon and bauble loot crates and their contents appear as patterns of tiny coloured dots. They also do it when opening the crates and the pattern changes in my hand. Copper nuggets do it too. So far the only items that I’ve found do it. Also show the same in NEI. 

## Additional Information
https://imgur.com/gallery/0fpaF

**Comment by scalda** [comment]
looks like you have a corrupt install, i would suggest you reinstall the pack and let me know if that sorted it

**Comment by scalda** [comment]
not heard anything here for 27 days so will be closing
