### ISSUE TITLE
Some quests are not completeable due to requiring removed items

### ISSUE THREAD

**Issue by TriadHero117** [scalda/FoolCraft#879]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
This has been reported and closed several times, but several quests require items from removed mods, causing them to show up as placeholders. Most immediately noticeable is the first quest for fighting back, but several others as well.

## Reproduce Steps
Open quest book
go to tab "Fighting back"
open the early game options quest

**Comment by scalda** [comment]
You must be running a old version of the quest book

**Comment by TriadHero117** [comment]
How can I update it?

**Comment by svennieke** [comment]
make sure cheats are enabled or when playing on a server ask the server owner to type **/bq_admin default load** as this is the command to reload the quest data

**Comment by scalda** [comment]
@TriadHero117 have you now sorted this if so can you please close the issue

**Comment by scalda** [comment]
not heard anything here for 27 days so will be closing
