### ISSUE TITLE
Foolcraft 2 crashing

### ISSUE THREAD

**Issue by Ceyphe** [scalda/FoolCraft#881]
Foolcraft 2 

Crashing

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
The moment i try to join my SP world it crashes after flashing '0%'
the whole game crashes and it doesn't give me a crash report or any explanation as to what happened.

## Reproduce Steps
Start MC launcher via twitch
start game
join world
crash

**Comment by scalda** [comment]
sorry need more information to help like logs

**Comment by Ceyphe** [comment]
That’s the thing, usually when I crash in modded or vanilla it gives me a ‘pop up’ crash log but it simply doesn’t with foolcraft. Is there a file where they are stored? If so I can easily find them. Thanks Scalda. 

Ps Good job on making the pack, it’s brilliant!

**Comment by Ceyphe** [comment]
[crash-2017-11-21_09.56.34-server.txt](https://github.com/scalda/FoolCraft/files/1549460/crash-2017-11-21_09.56.34-server.txt)

**Comment by liquid600pgm** [comment]
Seems like an AE2 issue.

Probably a Java Reflection class problem, where an invoked method doesn't exist or doesn't have matching arguments. Can you tell me the version of the modpack that you are using?

(trust me, i know a bit about java)

**Comment by creeperchick** [comment]
I'm getting a similar issue although I have crash logs. It starts to load in the world then crashes and has every time I reload. 
on the launcher after the crash, it says: The game crashed whilst ticking entity
The game crashed whilst ticking entity
Error: java.util.ConcurrentModificationException

[crash-2017-12-19_12.44.11-server.txt](https://github.com/scalda/FoolCraft/files/1571688/crash-2017-12-19_12.44.11-server.txt)

**Comment by Ceyphe** [comment]
I’m using the most up to date version on the twitch launcher. I tried reading through the crash log myself and it mentioned storage busses or import busses from AE2 although I don’t remember using them in the world at all.

**Comment by creeperchick** [comment]
yeah i'm all up to date and I have used AE2 but it worked perfectly yesterday night when I turned it off have done nothing since and it now won't load

**Comment by liquid600pgm** [comment]
@creeperchick yours is an issue with Java threading, are you running apps other than FoolCraft?

**Comment by creeperchick** [comment]
ah all sorted after many restarts it just happened to close what was stopping it load. thanks :)

**Comment by liquid600pgm** [comment]
@creeperchick this is still somewhat suspicious because some other app might be manipulating an object at the same time as Minecraft, either that or it was just the JVM that failed to properly bind variables (or just ran out of memory, that can happen too)

**Comment by Spharkii** [comment]
What about this crashing pattern? FC server version 2.4, loads without apparent error, then when a player attempts to join it crashes. 100% of the time. I've attempted to roll back the world by using some of the backups, and reinstalled the server files. suggestions on possible problems/solutions are greatly appreciated. Thank you. 
[crash-2017-12-21_18.04.05-server.txt](https://github.com/scalda/FoolCraft/files/1581062/crash-2017-12-21_18.04.05-server.txt)

**Comment by scalda** [comment]
for things like ticking block entitys, you can go into the config folder
locate the forge.cfg file open and change false to true on these to lines
https://i.gyazo.com/a34de209a5c25689accecda0d168c28a.png and restart the
server and that should get rid of it, if it doesn't then mcedit would have
to be used. but if it does work make sure to set those settings back to
false and restart the server

**Comment by Spharkii** [comment]
Thank you. I had to look through the crash report, find the block that was crashing the game, open the .dat file in MCEdit and remove it. now all's peachy.

**Comment by Ceyphe** [comment]
[crash-2018-01-04_20.37.33-server.txt](https://github.com/scalda/FoolCraft/files/1604656/crash-2018-01-04_20.37.33-server.txt)

just wanted to show that this is still an issue in 2.6, and i have provided a fresh crash report in case it is helpful.

**Comment by scalda** [comment]
there is a bugged waystone in your ae system not sure how i missed it the first time around. this issue has come up a few times so please search the closed issues for the solution
