### ISSUE TITLE
Suggestion - Mod To Add (Drawers & Bits)

### ISSUE THREAD

**Issue by DracoClaw** [scalda/FoolCraft#882]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I would like to suggest the mod Drawers & Bits to be added into the pack. I use it in my single player world and I love it. It's an add on to the drawers mod that is a compacting drawer for bits. It collects the bits and then turns them into solid blocks. I see that the fools always have random bits hanging around and I think this would help.

## Additional Information
https://minecraft.curseforge.com/projects/drawers-bits

**Comment by AutisticMC** [comment]
i like it

**Comment by scalda** [comment]
i have had very bad luck with this in the past hence why this is not in foolcraft and it more then likely won't make it to the pack sorry
