### ISSUE TITLE
More Quests. 

### ISSUE THREAD

**Issue by AutisticMC** [scalda/FoolCraft#884]
## SUGGESTION/HELP
- [x ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Adding more quests lines to the pack. 

## Additional Information

Kerasis's Chicken Quests (Hatchery)
Iskall's Reactions( Iskallium Reactors)
Rentdog's DerpWither's (Pink Withers) 
Stress Your wizard(astral Socerty).

**Comment by scalda** [comment]
thanks for the suggestions but there is already quest lines within the pack that does these things
