### ISSUE TITLE
Crashing when loading a world.

### ISSUE THREAD

**Issue by PaxoTheParrot** [scalda/FoolCraft#886]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Whenever I load a world, i recieve a crash error. This has happened before but I had to delete the world.

## Additional Information

Crash Log - https://pastebin.com/uhy0sQHH

**Comment by scalda** [comment]
You have a bad waystone in your me system best solution is to remove the mod run all me disks through the i/o disk thing to clear out current disks and it will also remove any items not in the game any more and then you can readd the mod

**Comment by PaxoTheParrot** [comment]
Do I remove the Waystones mod?
