### ISSUE TITLE
Unable to craft Pink Slime Block

### ISSUE THREAD

**Issue by andrelinslima** [scalda/FoolCraft#887]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Unable to craft Pink Slime Block. The recipe for Slime Block (green) is using ore_dict for slime_ball and taking precedence over it

## Reproduce Steps
1. Place 9 Pink Slimeball in a 3x3 crafting grid

## Additional Information
JEI information vs actual crafting result: https://imgur.com/a/Wi8F8

**Comment by scalda** [comment]
Plese use the little arrow next to the crafting output window to select the desired output
