### ISSUE TITLE
Placeholder item found in a dungeon crashes the game when rejoining

### ISSUE THREAD

**Issue by TriadHero117** [scalda/FoolCraft#888]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

I accidentally picked up a placeholder egg from Chickens in a dungeon. Now, my game crashes whenever I try to load.

Obtain "No Name" in a dungeon

This has been reported before, and the solution was to edit playerdata; I don't know how to is such a way that I wouldn't loose all my items.

**Comment by scalda** [comment]
you will need to load your playerdata file in a program called nbtexplorer and then find the bad item and delete from there

[NBTExplorer](http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac)

**Comment by scalda** [comment]
Also you must either be using a old version of the pack as this issues is fixed in the latest versions or it's a old generated dungeon
