### ISSUE TITLE
[Suggestion] Super Circuit Maker

### ISSUE THREAD

**Issue by Senophoe** [scalda/FoolCraft#89]
Some of the hermits are quite good at redstone. And something I feel should be add to the modpack is the mod Super Circuit Maker. It's redstone related, and something we're lacking on FoolCraft modpack.

https://minecraft.curseforge.com/projects/super-circuit-maker
https://www.youtube.com/watch?v=09hFVLKlBo4&list=PL0356053BA45C3464&index=25

**Comment by CriticalMole** [comment]
We have discussed this mod at length and have come to the conclusion that due to some bugs and the nature of the mod it isnt the right fit for FoolCraft
