### ISSUE TITLE
2.6 update changed mini moo cooldown to 2 minutes.

### ISSUE THREAD

**Issue by hvdklauw** [scalda/FoolCraft#890]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Before mini moo's took 40 minutes to "recharge", now it's 2 minutes.

## Reproduce Steps
1. Get a mini moo.
2. Milk it.
3. Look at the cooldown in the tooltip.

**Comment by Mrbysco** [comment]
The 40 minutes was a bug in the previous version as mentioned in #863 .
There was an issue in the mods code which made it bug out.

Scalda has said in that issue post that he'd reset it to default which is 2400 ticks / 20 = 2 minutes.

**Comment by hvdklauw** [comment]
Oh wow, ok. That's pretty op..
