### ISSUE TITLE
Some additional mods that may (or may not) fit with the pack.

### ISSUE THREAD

**Issue by BrisingrAerowing** [scalda/FoolCraft#891]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I'm not actually using FC itself (my 1.10.2 pack is based off of it though), but I have a few extra mods that may fit very well with the pack.

 1. [Exotic Birds Mod](https://minecraft.curseforge.com/projects/exotic-birds) - Adds a bunch of birds. Mostly for ambience
 2. [ExtraCells2](https://minecraft.curseforge.com/projects/extracells2) - An AE2 addon that adds Fluid storage support, along with a bunch of other things. Including a High Fidelity Walrus (Don't ask).
 3. [Blur](https://minecraft.curseforge.com/projects/blur) - Adds a Gaussian Blur effect to GUI backgrounds. Client Side only.
 4.  [Bottled Milk](https://minecraft.curseforge.com/projects/bottled-milk) - Adds milk bottles that have the same effect as a milk bucket, but stack to 16.
 5. [Modern Lights](https://minecraft.curseforge.com/projects/modern-lights) - Adds modern-style lights
 6. [Railcraft Cosmetic Additions](https://minecraft.curseforge.com/projects/railcraft-cosmetic-additions) - Adds a bunch of stuff to Railcraft
 7. [Swing Through Grass](https://minecraft.curseforge.com/projects/swingthroughgrass) - Hit mobs through grass (and other things with no collision box)!
 8. [AntiGhost](https://minecraft.curseforge.com/projects/antighost) - Helps fix ghost blocks.
 9. [Just Enough HarvestCraft](https://minecraft.curseforge.com/projects/just-enough-harvestcraft) - Pam's HarvestCraft / JEI integration
 10. [Ore Shrubs](https://minecraft.curseforge.com/projects/ore-shrubs) - Tinker's Construct Ore Berries reimplementation for newer versions.
 11. [AnalyzeIO](https://minecraft.curseforge.com/projects/analyzeio) - Analyze EnderIO loot capacitors and determine their various stats.

I have some other mods that may fit, and I'll gladly list them if you want. These are my favorites, though.

**Comment by scalda** [comment]
Hi thanks for the suggestions but it is very unlikely that new mods will be making it into the pack now unless there is a real reason to
