### ISSUE TITLE
2.6 Update Issues

### ISSUE THREAD

**Issue by jmac460** [scalda/FoolCraft#892]
The Quest menu seems to be unable to work for the following quest trees: Extreme Craftables, The Power of the Gods!!!,  The Sky is the Limit, and The Quest of Fools. 
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

The Quest menu seems to be unable to work for the following quest trees: Extreme Craftables, The Power of the Gods!!!,  The Sky is the Limit, and The Quest of Fools. Also, Faucet's for the Smeltery do not work along with anything related to filling/draining tanks.

By logging in and re checking quests

**Comment by scalda** [comment]
You may need to redownload the pack,i have just downloaded a clean install from curse and all is good with it i'm not having any problems with any of the issues you have submitted above

**Comment by jmac460** [comment]
I just did a clean reinstall as well. It shows up now, but some of the trees are missing... not sure why.

**Comment by jmac460** [comment]
![image](https://user-images.githubusercontent.com/34420502/33900958-d8d81b9e-df35-11e7-8d24-c19cec7d8ec8.png)

**Comment by scalda** [comment]
Well i'm not sure what to say as all quests show up for me

**Comment by svennieke** [comment]
i will take a look at this, i have set a lot of the quest to only show up when you completed the previous one. but i might have messed something up to make it only show when you actually completed the quest

**Comment by scalda** [comment]
not heard anything here for 27 days so will be closeing
