### ISSUE TITLE
AE Facades?

### ISSUE THREAD

**Issue by McSassyK** [scalda/FoolCraft#895]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I'm looking for the AE facades in JEI and they aren't showing up. The config has them set to true so I'm not sure why they don't seem to be available to craft.

## Reproduce Steps
Search facades in JEI and the only ones that come up are the conduit facades.

**Comment by scalda** [comment]
The ae facades are set to be hidden in jei as there are alot of them a
really fill up jei. You can still craft them
