### ISSUE TITLE
Can not play :(

### ISSUE THREAD

**Issue by diexo32** [scalda/FoolCraft#898]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

Hi scalda,
I would like to be part of the Foolcraft comunity by play your modpack.
Sadly it has not been possible.
The game crashes when i try to run it.
Can you help me?
[2017-12-14-5.log.gz](https://github.com/scalda/FoolCraft/files/1559005/2017-12-14-5.log.gz)

## Reproduce Steps
1. try tro run game from twitch launcher
2. game "starts" and then crasches

**Comment by Mrbysco** [comment]
Have you tried uninstalling Foolcraft and installing it again? Feels like something got corrupted

**Comment by diexo32** [comment]
did it twice.
can try again.

**Comment by diexo32** [comment]
My computer is newley built, maybe i am missing some software.

**Comment by diexo32** [comment]
[latest.log](https://github.com/scalda/FoolCraft/files/1560019/latest.log)

**Comment by Mrbysco** [comment]
![image](https://user-images.githubusercontent.com/9308260/34009634-ef31c59a-e109-11e7-9ffb-a6c2784434fc.png)
Have you tried the repair Minecraft button? (Found when you click the profile and go to the 3 stripes (menu)

**Comment by Mrbysco** [comment]
If you still have the same issue after clicking the repair minecraft button the 1.10.2 jar is corrupt should be deleted, 1.10.2 jar's folder can be the found in the following location: "C:\Users\<yourComputerName>\Documents\Curse\Minecraft\Install\versions\1.10.2"

**Comment by diexo32** [comment]
It worked. Thanks a lot!
You made my day,
