### ISSUE TITLE
Is it possible to play the modpack without the curse launcher?

### ISSUE THREAD

**Issue by Devious-Hat** [scalda/FoolCraft#9]
So I looked for the curse launcher and had some difficulty finding it. It seems to have turned into something called the twitch app. Once it was downloaded, I went to the minecraft section to finish installing everything. Long story short: I can't change the location folder for the curse app due to my current administrator profile name having a special character in it. Only way I can change the admin name is by making a new admin account and moving everything to that profile and deleting the old one. 

I'd really like to give this modpack a shot. Is there any other way to make it playable without messing with the launcher? Thanks for your time.

**Comment by Jo-Mamma75** [comment]
Download and use MultiMC and try that.  Also, you could set the Curse client to use a directory other than the %USERPROFILE% path.  I have mine set to just C:\CurseVoice and C:\MultiMC respectively.  Makes it pretty easy to navigate to the folders if I need to manipulate files.

**Comment by Devious-Hat** [comment]
Thank you so much! Setting it straight to C:\something worked.
