### ISSUE TITLE
[Sugestion] Configurations and tweaks.

### ISSUE THREAD

**Issue by Senophoe** [scalda/FoolCraft#90]
**CyclopsCore:**
Disable analytics and version checker.

**AgriCraft:**
Disable JSON writeback and AgriCraft, AgriCore and plugins logging.

**NEI:**
Disable update checker.

**CodeChickenCore:**
Disable update checker.

**ColossalChest:**
Disable analytics and version checker.

**ColossalChest:**
Disable update checker.

**Railcraft:**
Railcraft is currently allowing Poor ores generation. They cause unwanted ore generation irregularities by competing against other ores during the chunk generation process. Poor ores aren't necessary not important. They only are smelted for an ore nugget. You should disable their generation.

On the Railcraft configuration, change those

B:mineTin=false
B:mineSilver=false
B:mineLead=false
B:mineIron=false
B:mineGold=false
B:mineCopper=false

**Comment by scalda** [comment]
thanks for all these suggestions they have made there way into 1.3
