### ISSUE TITLE
Possible Mod Addition

### ISSUE THREAD

**Issue by Kiobito** [scalda/FoolCraft#907]
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [ ] In single player
     - [ ] In multiplayer
- [ ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description 
   Buildcraft is a mod that allows for exceptional item movement and sorting while also being reasonably cheap and simple to use. It also adds machines that help with mining, building and pumping fluids such as water from the source ie the ocean. the only issue is they will not create a 1.10 build but have left it open for others to do so.

## Additional Information
    Here is a link to the source site for your convenience: https://minecraft.curseforge.com/projects/buildcraft

**Comment by scalda** [comment]
sorry no more modes will be added at this stage thanks for the idea thou
