### ISSUE TITLE
[Suggestion] ChickenChunks removal

### ISSUE THREAD

**Issue by Senophoe** [scalda/FoolCraft#91]
I understand CodeChickenCore and CodeChickenLib are necessary dependencies to other mods, but what about ChickenChunks? I couldn't find amod that needs it, and the chunkloader it adds is currently beeing removed through scripts.

You're basically adding a mod that adds a chunkloader. But you're removing it afterwards.

**Comment by scalda** [comment]
This is in to allow us to use a command to see chunks that are loaded but thanks for the info
