### ISSUE TITLE
Server Crashes 

### ISSUE THREAD

**Issue by Facomen** [scalda/FoolCraft#912]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

**Comment by Mrbysco** [comment]
Could you provide a crash log?

**Comment by Facomen** [comment]
its on my other issue that i put in here with all details

**Comment by Mrbysco** [comment]
Are you talking about #913 ? if so you should close this issue in favour of the better explained one.
There's no need for duplicate issues :3
