### ISSUE TITLE
Crashes world on entry (Probably because of  a block)  

### ISSUE THREAD

**Issue by rowmjk** [scalda/FoolCraft#915]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

i was using "p455w0rdsthings" compressor. i was using a hopper as input and i was using the recipe that converts coal to raw carbon and it crashed. Whenever i enter the world i crash now.

## Reproduce Steps
Same as in description.

## Additional Information
Crash Reports:
	They should all be the same but it can't hurt.
	Crash report 1: https://pastebin.com/3LVCsXQX
	Crash report 2: https://pastebin.com/9xCj0VAV
	Crash report 3: https://pastebin.com/Lt4c3WaE

**Comment by sijn82** [comment]
Yeah I had the same issue running a chest of coal though the compressor using item conduit and extracting the carbon to another chest.  My world would crash on loading but reverting to the latest save (only losing about 30 mins of progress) fixed it for me.  The same system works fine this time so not sure exactly what upset it so much!

**Comment by scalda** [comment]
[fix](https://github.com/scalda/FoolCraft/wiki/Ticking-Block-Entity-fix-for-somethings-but-not-all-like-fluidcows)
