### ISSUE TITLE
Can't craft modded blocks on server

### ISSUE THREAD

**Issue by MIssionXmc** [scalda/FoolCraft#918]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Hi.. I'm trying to host a FoolCraft 2 server but I'm having trouble with crafting.
The issue is kinda a multipart issue understod in the way that I can't even cheat in modded blocks.
The server is saying "There is no such item with name ....."
You can see the linked image bellow for visual

## Reproduce Steps
Here is how I installed my server.
1. I downloaded the latest version "2.6" from this page: https://minecraft.curseforge.com/projects/foolcraft/files
2. Unziped the downloaded file
3. Uploaded the content from the file to the root folder of my server
4. Started the server using the file: minecraft_server.1.10.2.jar
5. Server is running with no problem using 10% CPU and 5% RAM (12GB RAM Server)
6. Logged in to the server and started playing with no problem, until I wanted to craft modded blocks

## Additional Information
https://i.imgur.com/fy5XMUj.jpg

**Comment by Mrbysco** [comment]
You're booting up the wrong file for the server. Minecraft_server.1.10.2.jar is the vanilla server jar. You need to boot the forge one which should be something like forge-1.10.2-XX.XX.XX.XXXX.jar

**Comment by MIssionXmc** [comment]
Thank you.. How I mannaged to miss that small factor that I need to be using the forge jar file, I'll newer know, but now it's all working.. Thank you again, and have a great day..
