### ISSUE TITLE
Chisel crashing on use

### ISSUE THREAD

**Issue by dxn000** [scalda/FoolCraft#92]
Chisel is crashing on use. Thought it might be better fps but it is not as I have turned it off.

**Comment by scalda** [comment]
please provide crash report

**Comment by dxn000** [comment]
[crash-2017-03-25_23.36.49-client.txt](https://github.com/scalda/FoolCraft/files/871378/crash-2017-03-25_23.36.49-client.txt)

**Comment by dxn000** [comment]
crash report added

**Comment by scalda** [comment]
This is a rendering issue, please remove any mods that you are using to better your game and try again

**Comment by dxn000** [comment]
That's the thing, I'm not. I removed  the one I had and tried again, still crashing

**Comment by dxn000** [comment]
Issue resolved. Re-installed mod, guessing it was a corrupt file on download
