### ISSUE TITLE
Does Astral Sorcery need updating for more content?

### ISSUE THREAD

**Issue by sijn82** [scalda/FoolCraft#921]
## SUGGESTION/HELP
- [ x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

I've been playing with the astral sorcery mod and have noticed some of the newer features are missing such as the 5th basic constellation Evorsio and the Iridescent Altar which opens up the 5th chapter in the journal.  Am I right in thinking the mod needs updating?  Are there any plans to do this? I suspect these were added to the 1.12 update but not the 1.10 version Foolcraft needs.  I'm not complaining :), just curious and thought I'd add this here to provide an endpoint for anyone else wondering the same thing.

## Reproduce Steps

Evorsio doesn't appear on constellation paper and iridescent altar missing from journal (knowledge -> constellation)

**Comment by drrugg** [comment]
Last 1.10 update for Astral Sorcery was July last year (1.4.4) - and they have confirmed on their Discord several times they are not supporting 1.10 any more.

**Comment by scalda** [comment]
what @drrugg said
