### ISSUE TITLE
Carbon upgrades cause crash.

### ISSUE THREAD

**Issue by Ronnie0982** [scalda/FoolCraft#923]
<!-->
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - in singleplayer
     - In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
I have looked at #897 
- [x] I am crashing and can provide my crash report(s)
java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at p455w0rd.p455w0rdsthings.recipe.ArmorUpgradeRecipe.func_77572_b(ArmorUpgradeRecipe.java:152)

**Comment by scalda** [comment]
please look here for a temp solution https://github.com/p455w0rd/p455w0rd-s-Things/issues/55
