### ISSUE TITLE
Ram problem

### ISSUE THREAD

**Issue by qSh4d0w** [scalda/FoolCraft#926]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

**Comment by MordridtheBlack** [comment]
You can tweak you allocated memory via the Twitch App.

Upper left corner of the app are 3 lines. Click that and go into File then Settings.

In the Settings is an option for Minecraft. If you scroll down in that section that is a part that says Java Settings. Along with a slider bar below Maximum Memory Allocation.

Move that bar from its current spot until it shows 6,144 MB (roughly 6GB actually). This should hopefully fix your problem.

**Comment by qSh4d0w** [comment]
I already allocated 6 GB RAM but it does not want to use it.
