### ISSUE TITLE
Server Crash "Ticking block entity"

### ISSUE THREAD

**Issue by Berisko** [scalda/FoolCraft#927]
Hello, I have searched Foolcraft issues and I can't find any that suits my problem. The problem is "**Ticking block entity**". I saw some of them here, but atleast in log files the block that causes the issue is shown, but for me it's not or I can't find it (sorry if it's like that) .

Crash Log - https://pastebin.com/gX0tMLiM

Berisko.

**Comment by scalda** [comment]
please try this and let me know if it worked https://github.com/scalda/FoolCraft/wiki/Ticking-Block-Entity-fix-for-somethings-but-not-all-like-fluidcows

**Comment by Berisko** [comment]
@scalda 
Doesn't work. Atleast before the server started and then quickly crashed. Now everything stops at these lines - https://pastebin.com/jppsC43x

It has been 30 minutes, nothing has changed.

**Comment by scalda** [comment]
ok looks like you have missing blocks in your world, have you updated the pack or something? as i think this is waiting for you to do the command /fml confirm so it can move forward

**Comment by Berisko** [comment]
Did the "/fml confirm", nothing changes, still stuck.

https://gyazo.com/771dd429fca7fd822fe78085d8b688b9

**Comment by scalda** [comment]
when running that command you need to put the / on the command or it will not work

**Comment by Berisko** [comment]
@scalda 
Just did the "https://github.com/scalda/FoolCraft/wiki/Ticking-Block-Entity-fix-for-somethings-but-not-all-like-fluidcows". I't doesn't work, although the server turned on but quickly after it crashed.

Crash Log - https://pastebin.com/Bce5giNm There is something about the Iskallium reactors and Enderio Capacitor banks, right?

**Comment by scalda** [comment]
you have placed a thermal dynamics conduit on a iskalliun reactor, that ticking block trick you tried should work if not you will have to use mcedit to remove the block

**Comment by Berisko** [comment]
Somone must have placed somewhere then... Is there a way to find every iskallium power-tap and replace it with air (in mcedit)?

**Comment by scalda** [comment]
It will tell you the block location in the crash report

**Comment by Berisko** [comment]
So... In the end nothing was resolved. Crashes kept comming and comming, opened MCEdit and deleted "Block entity being ticked" more than 20 times, no success.
I'm giving up. Thanks @scalda for your time and effort to help me fix the crash issue.

**Comment by scalda** [comment]
send me the world file if you can and i'll fix it for you

**Comment by Berisko** [comment]
@scalda Here's the map - https://www.dropbox.com/s/jkuyvf0om9ijhht/world.zip?dl=1

**Comment by scalda** [comment]
@Berisko What pack version are you using?

**Comment by Berisko** [comment]
@scalda I'm using Foolcraft 2.6

**Comment by scalda** [comment]
@Berisko What pack version did you start this world on? also did this stop working after a pack update as your world is badly corrupted

**Comment by Berisko** [comment]
@scalda We did start on 2.5.1 then we updated to 2.6
It had some problems but were quickly fixable but this problem was the biggest one that we got.

**Comment by Berisko** [comment]
@scalda Is the world completely broken/corrupted and unfixable?

**Comment by scalda** [comment]
@Berisko i would say it is my best bet would of been to restore from a backup but that is abit late now sorry i have been really busy and i don't always get a chance to check in on here
