### ISSUE TITLE
Questlines missing issue

### ISSUE THREAD

**Issue by advancedprocastinator** [scalda/FoolCraft#928]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I have recently gotten into modded minecraft through xizumavoid's foolcraft 2 series, and I have been experiencing an issue regarding better quests. From the various channels I have watched, each person has a very long list of mods, but when I boot up a world, my quest list seems severely shortened, missing quest lines such as fighting back and generating power. I have tried the /bq_admin default load command, and nothing has changed. I Have supplied pictures firstly of my list, and secondly the normal list. Maybe that's just the list for that server? Idk, I'm still new to mods. Anyways I was just wondering if anyone has also had this issue or if they have a solution or suggestion.

## Reproduce Steps

https://imgur.com/fwRGaA5
https://imgur.com/rrDp5jK

**Comment by svennieke** [comment]
uhm, the video you toke the screenshot from has a very outdated questbook, and i think that the questlines are not showing up beacuse one of these 2 reasons:
Reason 1: you need to click on a questline to see the quests, in your screenshots it does not look like you clicked one

Reason 2: you might have opend the fools quest tab wich may or may not have quests ;)

**Comment by advancedprocastinator** [comment]
Oh yes sorry I know I have to click on specific quests to open them up, I was more wondering if questlines such as "fighting back" and "generating power" have been removed, because I can go into the quests in my picture fine, but I can't seem to find those ones or many of the other quests. Am I accessing them wrong? I'm using the grave key to open up quests, is that correct?

**Comment by svennieke** [comment]
yeah those quest lines are gone, i have redone quite a lot with the questbook, those questlines got replaced with others
