### ISSUE TITLE
Crash on Start-up

### ISSUE THREAD

**Issue by waffle-universe** [scalda/FoolCraft#929]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

Whenever i try to load the modpack my game will start to load it on the mojang screen then after a while it will crash and give me a crash report

## Reproduce Steps

here is my crash report: https://pastebin.com/qxsQfkGP

**Comment by waffle-universe** [comment]
Also im using version 2.6

**Comment by klostrophobik** [comment]
There's a line in there "java.lang.OutOfMemoryError: GC overhead limit exceeded".

You need to allocate more ram to the process.

**Comment by waffle-universe** [comment]
okay, this is what i have in my JVM arguments do you know what i need to change, its a little confusing to me :/

-Xmx3072m -Xms256m -XX:PermSize=256m -Dminecraft.applet.TargetDirectory="C:\Users\harle\Documents\Curse\Minecraft\Instances\FoolCraft" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US

**Comment by waffle-universe** [comment]
i have fixed the problme thank you :D

**Comment by scalda** [comment]
@waffle-universe if you have sorted this can you close the issue please
