### ISSUE TITLE
ModernWarfare tech tree currently broken

### ISSUE THREAD

**Issue by Senophoe** [scalda/FoolCraft#93]
ModernWarfare recipes need to be remade. The ores from this mod were ignored in favor of ThermalFoundation ores. But the recipes from ModernWarfare currently only accept Modern Warfare ores, and do not accept the ones from ThermalFoundation.

Also, Railcraft and ModernWarfare removed ores (because they're duplicates of ThermalFoundation ores) should be blacklisted on JEI.

**Comment by Jo-Mamma75** [comment]
Should be resolved in FoolCraft 1.3 as it contains updated Modern Warfare.
