### ISSUE TITLE
Suggestion: Nerf carbon armor drops

### ISSUE THREAD

**Issue by generrosity** [scalda/FoolCraft#930]
## SUGGESTION/HELP
- [X] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

p455w0rd's Things includes carbon and infused carbon armor pieces. These are being randomly dropped by mobs, and are OTT Draconic Evolution scale. 

I have players who now never take damage at the cost of ~1000RF per heart, 

On the mod page it says with sk. could drop carbon chunks! I'd suggest reducing drops to the same rate as legendary loot bags, or equally rare.

**Comment by scalda** [comment]
sorry but iskall likes the pack op so this won't be changing

**Comment by generrosity** [comment]
Sweet! Thanks for the confirm
