### ISSUE TITLE
Monitor going to sleeep when searching for ''infi''

### ISSUE THREAD

**Issue by GoldenDragonHS** [scalda/FoolCraft#931]
As title says
How to fix this isue? anyone seen someting close to / same as this isue plz leave a coment. Games runs perfect for me otherwise i guess i just can't use items that starts on infi. :/ seems realy odd to me.

Edit: seems the game keeped infi in the search bar so now i cant play at all becous i can't open my inventory :(

**Comment by scalda** [comment]
please open another issue and use the template to fill out the issue correctly
