### ISSUE TITLE
Carbon Armor Upgrade crashes everytime i try....

### ISSUE THREAD

**Issue by AmroWazzan** [scalda/FoolCraft#932]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## i found that Carbon armor is way too OP to be upgraded too...
everything is done but when i wanted to upgrade it, it crashes every time i place the Armor piece in the crafting table then adding the Upgrade so you upgrade your armor
by the way, the problem is on all the upgrades, tho i tested the Chestplate only
i hope i said all what you need.....

## didnt really understand but i think its basicly how the problem started....
1-place the (Any carbon armor) in any Crafting Table even if the Inventory crafting
2-place the (Any carbon armor upgrade) in the other slot so you can upgrade your armor
3-have fun lagging a bit and crashing

## 
[crash-2018-01-13_22.25.11-client.txt](https://github.com/scalda/FoolCraft/files/1628682/crash-2018-01-13_22.25.11-client.txt)
added the Crash Log and this might will help

**Comment by Berisko** [comment]
That's a known problem. I don't know what causes it, but if you want to upgrade your Carbon armor use ME Crafting Terminal, no problems there.

**Comment by scalda** [comment]
see above closing as there is a work around
