### ISSUE TITLE
Warpstone turns player invisible

### ISSUE THREAD

**Issue by generrosity** [scalda/FoolCraft#933]
## Issue Description

When using the warp stone, sometimes the player lands with invisibility applied. It has black swirl particles presenting, but there is no status effect on the player. Once you have particles, warping further keeps the effect.

Only known way to remove status is to change dimension (eg via a nether portal).

## Reproduce Steps

No consistent reproduction steps. Teleport using warpstones back and forth.  Suggestions welcome.

Not affected by: different dimensions, chunk loading, cow pet.

## Additional Information

Has been noticed since mid Foolcraft 1 when we started - initially thought as just a random effect part of the pack, but haven't been able to google or GIT find any reference to it. Seems to have cropped up in the last week in particular?

**Comment by scalda** [comment]
don't use the waystone use the little gui interface in the unventory screen

**Comment by generrosity** [comment]
Just checking - cant use the waystone menu on this version. Warp stone gives the menu of locations. Inventory only gives "re-teleport to last destination on the list (???)".
