### ISSUE TITLE
Mechanical User - placed leads to disconnect

### ISSUE THREAD

**Issue by abandoncaptain** [scalda/FoolCraft#934]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
When I placed a mechanical user on the ground it instantly made me disconnect from the server and when I rejoin it instantly disconnects me again.

## Reproduce Steps
Place Mechanical User

## Additional Information
No Errors or anything

**Comment by scalda** [comment]
You will have to disable the use in the ExU.cfg file in the config folder
or mcedit the world and delete the block

**Comment by abandoncaptain** [comment]
@scalda I got it deleted but I need it fixed to where I can use a mechanical user

**Comment by scalda** [comment]
what version of the pack are you using, as in 2.6 they work fine

**Comment by abandoncaptain** [comment]
i'm using 2.7, i manually updated the server to work with 2.7

**Comment by abandoncaptain** [comment]
so i should backdate to 2.6?

**Comment by scalda** [comment]
then it should work fine in 2.7, i don't know of any other issues with it

**Comment by abandoncaptain** [comment]
there is an issue somewhere, I have the server hosted on host site and I can give u the login info if u want to look at it.

**Comment by scalda** [comment]
do you not get any message at all in the logs?

**Comment by abandoncaptain** [comment]
None, I looked at the logs and nothing, I know how to read logs because I develop Minecraft content for servers. Not even a null pointer or anything shows up. It's literally me disconnecting and in the logs the reason for lost connection is disconnecting.

**Comment by abandoncaptain** [comment]
@scalda what do u recommend?
