### ISSUE TITLE
modpack help

### ISSUE THREAD

**Issue by bustthenutz** [scalda/FoolCraft#935]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Additional Information
ok so how do i make a server up so i can play with friends? i rented a realm server and now i was told i cant use mods on it ? . so i'm trying to make a privater server up using the foocraft modpack to play with friends

**Comment by bustthenutz** [comment]
Hi how do i make a server up so i can play with friends? i'm using the twitch app to play on. i rented a realm server to be told i can't use modpacks on it is this true? and if so how can i play with friends using the foolcraft mdpack?

**Comment by abandoncaptain** [comment]
Realm servers are strictly vanilla only, you need to either host a server urself or purchase a hosted server from a hosting site to do mods
