### ISSUE TITLE
Issue with downloading FoolCraft from Twitch!

### ISSUE THREAD

**Issue by Akaneki25** [scalda/FoolCraft#939]
So I downloaded an older version of FoolCraft back when Twitch was Curse. Recently, I was interested in checking out the newer version and went to download 2.5.1, as that was the version my girlfriend was playing on. It downloaded it, and right before it would have said it was finished, it said "Addon Install Error: Twitch encountered a problem during this operation. Error: Object reference not set to an instance of an object." Normally I'm pretty good at following troubleshooting and errors to solve problems, but this was so vague I had no idea what it meant. I googled other people who had similar problems (could not find anyone with this exact message) and nothing worked. I allocated more memory than it needed (7 gb), made sure it allowed Twitch to use addons, made sure I had Java 64 bit, uninstalled and reinstalled Twitch and Minecraft, made sure I had all the settings correct, and tried again but still to no avail. Any help would be much appreciated!

**Comment by ajdjyt** [comment]
It is just because too many people are dowloading the pack at the moment

**Comment by scalda** [comment]
this is a twitch launcher issue not the pack please direct this question to them
