### ISSUE TITLE
java null pointer exception while updating screen events for Refined Storage Grid (v1.2)

### ISSUE THREAD

**Issue by scopiplays** [scalda/FoolCraft#94]
Hiya,
  
  Searching the refined storage system (e.g typing #luck for luck of the sea books) causes the crash.  Logging back in and just opening the grid crashes.  Breaking the controller and replacing it resets the system for a little bit.

  Please let me know if there is any other required information to help debug this.

Thank you,

-Scott 

[crash-2017-03-26_10.10.47-client.txt](https://github.com/scalda/FoolCraft/files/870808/crash-2017-03-26_10.10.47-client.txt)

**Comment by scopiplays** [comment]
Somehow I managed to obtain 6 "Augment:Invalid Item (destroy) 8104:326" items from thermal expansion. 

I have my loot bags auto opened from the mob farm and inserted into the refined storage system.  I do not know if I obtained them prior to upgrading to 1.21 or after.

Removing them from the Refined Storage system allows me to search using the # without crashing.

Thank you,
Scott

**Comment by scopiplays** [comment]
2AM Update:

I AFK'd for a few hours and got another one.  I used NBTExplorer to inspect my inventory and I found a match in the Lootbags_BagConfig.cfg

thermalexpansion:augment:326:1:1:50 is the culprit causing the crash.

NBTExplorer shows it as a idLthermalexpansion:augment with a damage of 326.

Please let me know if there is anything else I can do to help.

Thank you,
Scott

**Comment by scalda** [comment]
looks like a nbt tag got messed up somehow, thanks for the report

**Comment by CriticalMole** [comment]
Should have been fixed in 1.2.2
