### ISSUE TITLE
how to make emerald bits?

### ISSUE THREAD

**Issue by jrkirkley** [scalda/FoolCraft#941]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

Trying to make emerald bits but the recipe defaults to emerald skin. tried disabling modern warfare then recipe defaults to nuggets. i know the compressor produces bits as a byproduct but the recipe requires bits to create the compressor.

**Comment by jrkirkley** [comment]
i found out killing villagers yield a bit. tried to male a bit mold for tinkers but failed.
i would hate to kill off every village to get bits.

**Comment by TwistedGA** [comment]
Crafting table GUI should have a small button with an arrow on it to the right of the grid. When you place emeralds in the grid, use the arrow to cycle through the items that the emerald can produce. Bit's are one of these items.

**Comment by scalda** [comment]
what @TwistedGA said
