### ISSUE TITLE
I can't figure out how to run the pack

### ISSUE THREAD

**Issue by Polonium8400** [scalda/FoolCraft#943]
- [ ] I am running the latest version of FoolCraft
- [ ] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [ ] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

I cannot figure out how to get the pack to appear in the mods section of forge i've tried to create a launch option to run the pack but to no avail

I do not know how to reproduce the steps

**Comment by Polonium8400** [comment]
I have tried to run the pack via twitch but the modpacks tab wont acknowledge the existence of my minecraft launcher

**Comment by scalda** [comment]
this is a twitch launcher error sorry i can't help with that
