### ISSUE TITLE
Script Block Visible?

### ISSUE THREAD

**Issue by znxster** [scalda/FoolCraft#944]
- [x] I am running the latest version of FoolCraft (2.7)
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [ ] I can reproduce this issue consistently
     - [x] In single player
     - [ ] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## Issue Description
I was out wandering the world and I came across an island (which was clearly a structure). The island had grass, stone blocks, moss, black hardened clay and some birch planks. The island was a gravel path around a centre broken and damaged structure. Whilst wandering around the structure I came across a "Script Block". I can interact with the block and indeed break it and place it back down. The Script Block comes from Recurrent Complex and is not craftable.

I do not believe the Script Block is intended to be visible or capable of interaction but instead is meant to script an event (such as create the island in the first place).

## Reproduce Steps
Unless I can find another island like this I am unsure how to reproduce, indeed it might spawn differently and not reproduce.

## Additional Information
My seed is: 1012892759169590945
Island is at: x=-1672, z=-587

**Comment by generrosity** [comment]
Probably good to log with the recurrent issues log too - I imagine scalda just uses the standard set of models? I've seen a few (tank) with placeholder corner blocks generate too - unlikely to be a pack problem tho

**Comment by scalda** [comment]
that is just a badly loaded structure nothing really to do with the pack but thanks for the issue
