### ISSUE TITLE
Chat Override?

### ISSUE THREAD

**Issue by Thunder-Nova** [scalda/FoolCraft#945]
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [ ] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

Foolcraft v2.8

Me and the server owner are trying to figure what was the mod that is overriding the chat.
- Ranks are always white
- When using the Chat button of JourneyMap, it's not a clickable option from chat

Pretty much described above.

<img src="https://i.imgur.com/WetybnG.png" />

**Comment by chunkedelement** [comment]
Here is our FTB ranks file its like something is overriding ranks syntax, cant figure it out.
Thanks.
{
  "default_ranks": {
    "player": "player",
    "op": "op"
  },
  "ranks": {
    "player": {
      "parent": "builtin_player",
      "permissions": [],
      "config": {
        "ftbu.claims.max_chunks": 100,
        "ftbu.chunkloader.max_chunks": 10,
        "ftbu.homes.max": 1
      }
    },
    "op": {
      "parent": "builtin_op",
      "syntax": "<&c$name&r>",
      "permissions": [],
      "config": {
        "ftbu.claims.max_chunks": 150,
        "ftbu.chunkloader.max_chunks": 15,
        "ftbu.homes.max": 3
      }
    }
  }
}

**Comment by scalda** [comment]
I'm sorry i have never used the rank system so i have no idea. 

are you using sponge by any chance that is the only thing i can think of what could block it

**Comment by Thunder-Nova** [comment]
Nope

Up till now, we mostly used the FTB utilities for ranks and such, plus Discord add-on. Which from my experience with other servers and same setup which on them, nothing.

I had experienced the use of sponge/spigot add-ons which did override the chat system, which we did avoid.
