### ISSUE TITLE
Modpack Crash During Initialization 

### ISSUE THREAD

**Issue by BasketCaseSensitive** [scalda/FoolCraft#946]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

Hello first off I guess, I am running the latest version of minecraft, foolcraft, forge, and the twitch app, and have Allocated at this point 8 GB of ram to Java to run the pack. But every time I launch the game with this mod pack it crashes before I can get to the starter menu.  

I have repeatedly gotten the 

> The game crashed whilst initializing game
> The game crashed whilst initializing game
> Error: java.lang.OutOfMemoryError: GC overhead limit exceeded

error message, I have progressively allocated more and more RAM specifically to run this but no matter how much it seems to crash at approximately the same time no matter what.  And I would like to submit a crash report to help but clicking the view crash report button brings up nothing. Please help!! 

 

## Reproduce Steps
I open the twitch app through windows and click the foolcraft modpack in the my modpack section. I click play and at some point of initialization, it crashes.

Additional Information
I have No texture packs instaled, and the only mod that is installed to Minecraft is a lefthanded mod my husband installed months ago.

This is around the point that it crashes.
![image](https://user-images.githubusercontent.com/36121408/35774337-41436890-0921-11e8-84f8-b57fe4fd229a.png)

**Comment by Mrbysco** [comment]
How much ram do you have allocated? and what java arguments?

**Comment by BasketCaseSensitive** [comment]
Every time I look up the error message 

> Error: java.lang.OutOfMemoryError: GC overhead limit exceeded

The only solution anyone has given is to allow Java to run on more gigs. And since I cant get a crash report this is the only error I've had to go on.

**Comment by Mrbysco** [comment]
Do you have 32 bit or 64 bit java installed? as 32bit can only apply 4gb max

**Comment by BasketCaseSensitive** [comment]
I finally got it running thank you for your help! It wasn't Java that was the problem exactly it was the twitch app, I had no Idea that it was bottlenecking the number of gigs that it allowed java to run for Minecraft, it was restricting it to about 3, so, I raised it to 5 just to be safe and it finally went through initilization.

Posting this for someone else with this problem
![image](https://user-images.githubusercontent.com/36121408/35785171-5266349c-09d3-11e8-8225-e4106af15934.png)
