### ISSUE TITLE
MiniMoos broken spawning

### ISSUE THREAD

**Issue by 123idkwhatimdoinghere** [scalda/FoolCraft#947]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

##Okay so, whenever i start a new world in Foolcraft i seem to have the same problem. There are no alloy minimoos spawning. I always get the same ones. All Oil types, Honey, Blood, All slime types and 2 or 3 more are spawning but not the ones like iron, gold, terrasteel, copper and so on.

**Comment by generrosity** [comment]
Have you checked the nether? Most of the metallic ones are nether specific.

**Comment by 123idkwhatimdoinghere** [comment]
I have checked the nether. There werent even any MinoMoos spawning. So i had a look in the config files and swapped the moos from the overworld with thoose in the nether. It was working so most of the alloy moos were spawning in the overworld, but only the first time I played after I changed it.

**Comment by generrosity** [comment]
Sounds like the moo mod is working correctly. Might help if you post your FC version, and have a look inside your profile\logs file perhaps. If things aren't spawning after first play... that could be a bigger issue you are having ... 😨  Being how noone else is jumping all over this, it might be worth a clean new profile too.

Our guys are on 2.6 and overworld and nether are FULL of moos.

**Comment by scalda** [comment]
i would try the latest version of the pack, all liquid moos above like 1000c temp will spawn in the nether normal liquids in the overworld and really cold liquids in the end
