### ISSUE TITLE
Crash on search Since Thaumcraft introduction

### ISSUE THREAD

**Issue by TheSultryBadger** [scalda/FoolCraft#949]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

When searching for certain items in JEI the game will crash. I have experienced this searching for the letters "ste" and then going to page 4 of the results and when searching for tool, on the second "o" the game crashes. I get no error message but my Children get a message saying the game crashed while trying to render an ingredient.

Enter "ste" into JEI search and skip to page 4 of results or search for "too".

https://pastebin.com/dfV3saNr
https://pastebin.com/bEEyDC6v

**Comment by scalda** [comment]
https://github.com/Azanor/thaumcraft-beta/issues/229

**Comment by Nikolape** [comment]
I got this
The game crashed whilst rendering ingredient
Error: java.lang.NullPointerException: Rendering ingredient

**Comment by scalda** [comment]
fixed in 2.9.1
