### ISSUE TITLE
Game crashes consistently since update to 2.9

### ISSUE THREAD

**Issue by illuminoscopist** [scalda/FoolCraft#952]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [X] I am requesting help with installing or running the pack

## Issue Description
Game launches successfully. Allows me to play for approximately 5s before crashing, seems to be regardless of what i am doing.

## Reproduce Steps

Launch Game, Select my world, can play for about 5s, doesn’t appear to be linked to any specific set of actions, doing nothing will also result in a crash.

Crashes back to desktop/launcher.

## Additional Information

Crash Report : https://pastebin.com/2xH96Asb

**Comment by sijn82** [comment]
I've been suffering the same problem.

[crash-2018-02-10_21.52.32-server.txt](https://github.com/scalda/FoolCraft/files/1714246/crash-2018-02-10_21.52.32-server.txt)

**Comment by Killscreen256** [comment]
I was suffering from the same problem too, but I think I've found the cause of the crash. Near the beginning of both of your crash logs, as well as my crash log, it says "Could not initialize class thaumcraft.common.entities.monster.EntityPech". I know that this refers to the "Pech" mob in Thaumcraft. What I think is happening is that the Pech is bugged in the version of Thaumcraft in the pack, and crashes the game when it attempts to spawn. Fixing this is actually kind of easy; All you have to do is go into Thaumcraft's config files and set "spawn_pechs" to false. This should prevent the Pechs from spawning and fix the crash.

**Comment by sijn82** [comment]
Thanks for the tip!  Sadly after loading up successfully (with Pech disabled) I then searched @thaum in JEI and crashed the game again.  I see it's already logged as an issue so I'm just going to wait a few days for the kinks to get ironed out.

**Comment by generrosity** [comment]
I see two open tickets - [one tagged bug here](https://github.com/Azanor/thaumcraft-beta/issues/182), and [and a second untagged one here](https://github.com/Azanor/thaumcraft-beta/issues/296).

Stopping the spawning worked for us. Scalda's tweak to hide in JEI 2.9.1 works well for me - on session had missing textures intermittently with looking at JEI infusion pillar but not arcane stone, another time the pillar was fine, but arcane stones had no textures on breaking it.

**Comment by TheThoughtsmith** [comment]
My crash report has been the same, and I'm running the current version. I disabled pech spawning globally, and it still throws the error. I can't even log into the world for more than a second in order to use /kill @e[type=!Player].

**Comment by generrosity** [comment]
Heya Thoughtsmith ... If you are getting a crash file with "Could not initialize class thaumcraft.common.entities.monster.EntityPech", try disabling the whole mod just to prove nothing fishy is going on (like being in the wrong folder)

**Comment by TheThoughtsmith** [comment]
![image](https://user-images.githubusercontent.com/37058392/37011804-02f80168-20af-11e8-9bda-05e96264d669.png)
I clicked on this a few times, then launched the world. Error reproduced, therefore I don't know how to disable the mod beyond this button which doesn't work.

**Comment by generrosity** [comment]
I tend to open the game folder, and rename the .jar to .jar.old but I think you can do it from the curse launcher too if you unlock the pack properties

**Comment by TheThoughtsmith** [comment]
Thaumcraft doesn't show up in mods list, check.
When loading world, game warns me about all the items it thinks should be available, check.
Game loads alright, nothing's crashing so far. Looks great!

**Comment by generrosity** [comment]
Sorry to hear that the Pech fix didn't work, so unless you're particularly thirsty for thaumcraft you should be set. You can easily clone the profile and world folders next time there is an update to test thaumcraft again later (or just always leave it disabled, welcome to your custom pack experience :) )

**Comment by generrosity** [comment]
Thaumcraft is still in "beta" after all... :) Tho everyone has been hungry for it

**Comment by illuminoscopist** [comment]
thanks @Killscreen256 disabling the pech spawn has solved the crash!
