### ISSUE TITLE
Game crashes shortly after spawing in 

### ISSUE THREAD

**Issue by oofer00** [scalda/FoolCraft#954]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Whenever I spawn in my world it crashes within 3 seconds. t brings me back to the launcher and it said this The game crashed whilst ticking player
Error: java.lang.NullPointerException: Ticking player

Also just updated to 2.9 but this issue arose in 2.7

## Reproduce Steps
I can reproduce them by just spawning in

## Additional Information
My crash report
https://pastebin.com/AeYmC37u

**Comment by scalda** [comment]
this is a crash to do with a fluid registry in the better questing mod

**Comment by oofer00** [comment]
So what should i do?

**Comment by oofer00** [comment]
so what should I do?
