### ISSUE TITLE
Carbon Infused Jetpack Bugged

### ISSUE THREAD

**Issue by Dbrickster98** [scalda/FoolCraft#955]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x ] I am requesting help with installing or running the pack

## Issue Description
The game seems to crash my worlds when I add the jetpack to the carbon infused chestplate, and try to take it out of the crafting square. NOTE only happens when crafted, not cheated in from Creative.

## Reproduce Steps
Step 1: Acquire Infused Carbon Chestplate and JetPlate Armor Upgrade;
Step 2: Place the items in the crafting table in correct recipe;
Step 3: Atempt to pull it out (NOTE: This is when it crashes);

## Additional Information

[crash-2018-02-13_22.29.01-client.txt](https://github.com/scalda/FoolCraft/files/1722688/crash-2018-02-13_22.29.01-client.txt)

Also, besides this, I love the modpack. Keep up the good works devs!

**Comment by jhicks631** [comment]
Just confirming I have this issue as well. For a little more detail - It appears to be any upgrades to the carbon armor. I tried adding the enderio battery as well and it crashed. Also tested cheating in a Jetplate and added a battery to that and it crashed also.

**Comment by lemonyslash** [comment]
Same. Here's my crash report: https://pastebin.com/fLtpayMD

**Comment by Flekrad** [comment]
Try the fix suggested here
https://github.com/p455w0rd/p455w0rd-s-Things/issues/55
https://www.youtube.com/watch?v=jEdA0xO7qag
