### ISSUE TITLE
Game crashes with a "Crashed unexpectedly" on the launcher while in a world.

### ISSUE THREAD

**Issue by Nikohn** [scalda/FoolCraft#956]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Game crashes after some seconds/minutes on game with no alterations in ram usage or cpu usage.

## Reproduce Steps
Opening the game, and playing for about 1-2 minutes.

Crash Report
https://pastebin.com/mhgv754N

**Comment by reck1essSOUL** [comment]
On line 26 it mentions your graphics card memory is exceeded. For you to run FoolCraft you need at least a minimum of 6gb to run the pack. Check to make you allocated enough memory for minecraft to run.
