### ISSUE TITLE
V 2.9.1

### ISSUE THREAD

**Issue by RedstonePvP** [scalda/FoolCraft#957]
Cooked Meat Ingots Crash Game
Cooked Meat Ingots Crash Game

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Cooked Meat Ingots Crash Game, when i load up the world i take the meat ingots and move them around in my inventory, then suddenly the game crashes and i cant reload that world and i have to make a copy

## Reproduce Steps
Open a wolrd
Get meat ingots in inventroy
move item around to off-hand and game shou;d crash

**Comment by generrosity** [comment]
Hey RedstonPVP - is this still an issue in later versions?
