### ISSUE TITLE
2.9.1 crash whilst exploring (lighting potentially involved?)

### ISSUE THREAD

**Issue by CSTufts** [scalda/FoolCraft#958]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
game was crashing just flying around, the crash logs indicate something to do with light rendering
I am running on a 2014 mac book pro

## Reproduce Steps
unsure, again I was just flying about in 2.9.1
[crash-2018-02-20_04.57.56-server.txt](https://github.com/scalda/FoolCraft/files/1739624/crash-2018-02-20_04.57.56-server.txt)

## Additional Information
none

**Comment by CSTufts** [comment]
will provide world files if necessary

thanks

**Comment by reck1essSOUL** [comment]
If you look at the beginning of the log it mentions the mob from Thaumcaft called the Pech. I had a crash on my world out of no where and was informed that the Pech was bugged. To fix this is to go into the config file for Thaumcraft and set the spawn for that mob to false.

**Comment by CSTufts** [comment]
can confirm this is still a bug in the latest, I have disabled the mob as @reck1essSOUL suggested and have not had another crash with some significant exploring

thanks

**Comment by scalda** [comment]
disable the pech in the thaumcraft config. i have done this for the pack
