### ISSUE TITLE
[2.9.1] Game Crashes when exploring away from spawn chunks

### ISSUE THREAD

**Issue by K-n1ght1** [scalda/FoolCraft#959]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I play as normal, running around and exploring and such. I adventure pretty far away from the spawn chunks (maybe 1000 or so blocks or more) and when I reach a certain distance, the game just crashes. Loading back into the game in the area where I crashed at lets me play normally for a minute or two before eventually crashing again unless I go back towards the spawn chunks. It's very frustrating seeing as I need to explore to find what I need. The crash report is included.

## Reproduce Steps 
[crash-2018-02-20_18.22.49-server.txt](https://github.com/scalda/FoolCraft/files/1742285/crash-2018-02-20_18.22.49-server.txt)
Load up the game, spawn in world, travel around away from spawn chunks and the game should crash. 

## Additional Information
Looked into similar issues and tried disabling the Pech mob from Thaumcraft (which seemed to fix the issues others had for a bit), nothing changed.

**Comment by reck1essSOUL** [comment]
At the beginning of the CrashLog it tells you that the Pech mob from Thaumcraft could not be created due to it being bugged. To fix this simply go into FoolCraft config files and find the Thaumcraft config file and disable the Pech mob from spawning.

**Comment by scalda** [comment]
the pech needs to be disabled in the thaumcraft config folder
