### ISSUE TITLE
Missing server files

### ISSUE THREAD

**Issue by INTRUDER74** [scalda/FoolCraft#96]
When downloading the server files from the curse website, I'm missing the server start file. I don't know how to open it, and all I have is
Config, Mods, Resources, Scripts, Structures, forge-1.10.2-12.18.3.2254-universal.jar, minecraft_server.1.10.2.jar, server.properties

I tried making a bat file but it would close saying we needed other files.

**Comment by scalda** [comment]
your not missing a file i don't include one, you are missing the libraries folder please download 1.2.1 server files it is fixed in there
