### ISSUE TITLE
[2.10] Cannot make crucible in thaumcraft

### ISSUE THREAD

**Issue by Adrakaris** [scalda/FoolCraft#960]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
In thaumcraft, the crucible is uncraftable. Right-clicking with the salis mundis does nothing.

Go through the thaumcraft progression until you reach alchemy. Then make a cauldron, place it down and right click with salis mundis (the same process as making the arcane crafting table)

## Additional Information
Not sure if this is a bug with the mod or bad config/intergration

**Comment by generrosity** [comment]
This still a problem? It was working in 2.9 - likely working in later versions?
