### ISSUE TITLE
Game crash 

### ISSUE THREAD

**Issue by Marconium2** [scalda/FoolCraft#961]
Game crash
Game crash after few minutes

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
I just started a new world and i keep crashing after 2-3 minutes i am logged in. I noticed it is happening more often when i am exploring then when not moving. I tried creating new worlds but same thing happens.

## Reproduce Steps
Open world 
walk around
crash

## Additional Information
https://pastebin.com/5e9nxEs3

**Comment by generrosity** [comment]
Search the forum for the "disable pech" fix in thaumcraft config. That's what your error log indicates it can't spawn, good luck!

**Comment by Marconium2** [comment]
ok thx for help

**Comment by Marconium2** [comment]
i removed the mod and everything seems to work fine now thx!!
