### ISSUE TITLE
FoolCraft |  Version 2.5 | Loading Chunks Crashes Our Server.

### ISSUE THREAD

**Issue by Thewhitestmold** [scalda/FoolCraft#963]
We are running a Minecraft server from a BisectHosting, and recently installed FoolCraft. Once installed we join and begin running around and are immediately faced with a crash which forces us to restart the server and the process continues. It seems to only occur when we are generating new chunks, and we have tested a handful of worlds where some take quiet longer to crash.

First we create a new world, then we join the server and run in a direction until we encounter a crash or time out.

Here is a Crash Report, i can provide another if needed!
https://pastebin.com/k9eCiT9p

**Comment by scalda** [comment]
Go into the config folder/thaumcraft.cfg and disable the pech mob and you
will be good to go

**Comment by Thewhitestmold** [comment]
Thank you so much!
