### ISSUE TITLE
Foolcraft 2 v2.12 crashes upon world load.

### ISSUE THREAD

**Issue by Colinth22** [scalda/FoolCraft#966]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I open up the game, load a world that I just made in Foolcraft 2 v2.12, i can play in the world for up to 20 seconds and then it crashes. It did this twice, then I went into the Java arguments and doubled all allocated ram and it still happened. 

PC specs:
GTX 1070
Ryzen 1600
32gb DDR4
(I think that's all you really need on terms of specs.)

## Reproduce Steps
Open a world, do literally nothing and wait for it to crash.

## Additional Information
[crash-2018-03-17_20.28.46-server.txt](https://github.com/scalda/FoolCraft/files/1822220/crash-2018-03-17_20.28.46-server.txt)

**Comment by generrosity** [comment]
Search for EntityPech in this github. Looks like Thaumcraft config still allows for this to spawn, as it seems to be still an issue

**Comment by b52src** [comment]
disable spawning of pech in in Thaumcraft config file  seams to fix it for now. 
B:spawn_pechs=false
#964

**Comment by dragonianwolf** [comment]
I also have this problem I have already changed spawn_pechs to false but still the world keeps crashing on me when I play in biomes o' plenty
added in is my latest crash report
[crash-2018-03-19_21.40.15-server.txt](https://github.com/scalda/FoolCraft/files/1826907/crash-2018-03-19_21.40.15-server.txt)

**Comment by b52src** [comment]
you may try disabling the Hat mod as well if it is still happening, this trying to put a hat on the Pech is what causes the issue from my understanding. I had this disabled for a while until I removed the Pech spawning.
