### ISSUE TITLE
Lag when opening any GUI

### ISSUE THREAD

**Issue by aolsen96** [scalda/FoolCraft#967]
GUI lag
Lag when opening any GUI

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Whenever I open any GUI my game drops frames from 200+ to 20 and below, everything is up to date and have also messed around with different Optifine setting also without Optifine. Others are also experiencing the same issue. 

## Reproduce Steps
It happens all the time, I do not need to do anything to reproduce it.

**Comment by aolsen96** [comment]
Disabling NEI seems to remove this issue

**Comment by lemonyslash** [comment]
Yep. Worked for me as well.
