### ISSUE TITLE
Cannot open game

### ISSUE THREAD

**Issue by Dbrickster98** [scalda/FoolCraft#968]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
I am logging into the game and getting this error.

## Reproduce Steps

I just press play on both popups (Twitch and Minecraft)

## Additional Information

![image 2018-03-19 at 10 46 20 pm](https://user-images.githubusercontent.com/33787112/37635110-c53e4da4-2bc7-11e8-8c8d-b848fe7ce542.png)

**Comment by TimelordGuardian** [comment]
You have duplicates of chisel and thaumcraft in your mods folder. I suggest removing the older version of the two.

**Comment by Dbrickster98** [comment]
I tried just tried deleting the older files, and it did nothing.
