### ISSUE TITLE
Fps Issues

### ISSUE THREAD

**Issue by Ethan4350** [scalda/FoolCraft#972]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
I can play the game with ~200-500fps at Most times it often drops down to ~50 at random times then bounces back. My frame-rate drops down to ~30 whenever i open anything with a gui. I have optifine installed, graphics set to fast and particles set to decreased, My render distance is at 12, turning it down doesn't have any noticeable effect.

## Reproduce Steps
Just playing the game.

## Additional Information
My computer specs 
Intel i7 7700k
Evga gtx 1060 6gb
32gb Ram, The maximum i can allowed through twitch allocated.(~12Gb)

**Comment by aolsen96** [comment]
try disabling NEI, I had a similar issue and it helped

**Comment by kpeckett** [comment]
You might want to reopen this as it is likely causing issues for others and a fix for a future version is better than a workaround.
