### ISSUE TITLE
Equivalent Energistics Mod Suggestion to bridge Project E and AE2

### ISSUE THREAD

**Issue by b52src** [scalda/FoolCraft#973]
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Suggesting Equivalent Energistics mod to bridge Project E and AE2. mod brings in auto crafting for items with EMC and allows them to be used in recipes for items without EMC

https://minecraft.curseforge.com/projects/equivalent-energistics

**Comment by Jaciii** [comment]
I also think that equivalent energistics should be added
