### ISSUE TITLE
Crash issue

### ISSUE THREAD

**Issue by Hypenosis** [scalda/FoolCraft#975]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Every time i launch the pack, it loads properly and then crash. Sometimes it lets me enter the world, but it doesn't load and crash

## Additional Information
[crash-2018-03-23_20.21.39-server.txt](https://github.com/scalda/FoolCraft/files/1844714/crash-2018-03-23_20.21.39-server.txt)

**Comment by generrosity** [comment]
Pech issue. Do a search, you have a few options :)
