### ISSUE TITLE
Foolcraft 2.12 infinite EMC dupe glitch

### ISSUE THREAD

**Issue by Jack1Daniels** [scalda/FoolCraft#977]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Reproduce Steps
i was using the transmutation table and i had some 2 energy condenser's that i wanted to put into the transmutation table and i used my mouses scroll wheel to put the energy condenser's into the transmutation table and just like you can do with chest's and when i did it gave me the EMC but it did not take the 2 energy condenser's i had and i could keep on doing that until i had the max EMC in my transmutation table

## Additional Information

Here's my youtube video that shows me doing the glitch

https://youtu.be/H9xQsU7m-pM

**Comment by janf3** [comment]
It's a known issue in the ProjectE github. However, what you see is only "ghost" EMC. If you pull items out they will just vanish when you click on them, try placing them or log off and back on. Same if you try storing that EMC in a Klein Star, the stored energy will go back to the _real_ value.

**Comment by Jaciii** [comment]
I tried and lost EMC :(
