### ISSUE TITLE
Foolcraft crashed unexpectedly

### ISSUE THREAD

**Issue by zbobvanbob** [scalda/FoolCraft#979]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

Trying to enjoy this great pack again after some time off, but whenever I try to play (in single player), the world crashes after a few minutes and kicks me back to the launcher saying Foolcraft crashed unexpectedly, sorry for the inconvenience. I have tried starting over in new worlds. I am not sure how to read the crash report so I am unsure as to what is causing the issue. I tried to find the issue and a solution online but can't find anything.

1.Load single player world.
2.Play as normal.
3.Game freezes and Crashes.

https://pastebin.com/qDXMhJMC

**Comment by generrosity** [comment]
Could not initialize class thaumcraft.common.entities.monster.EntityPech

See - #959 & #964

You need to set B:spawn_pechs=false under monster_spawning in the config/thaumcraft.cfg file
