### ISSUE TITLE
Foolcraft 2.11 server crash plz help (with crash report)

### ISSUE THREAD

**Issue by joransyoghurt** [scalda/FoolCraft#980]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
I cannot explain why this bug or crash happens only that it crashes the server when we move too fast, I have a crash report

## Reproduce Steps 
Move faster than running or run for a few minutes happens faster when the chuncks have to be generated

## Additional Information

https://pastebin.com/raw/TbQ2Cy9C

**Comment by ButchMonkey** [comment]
> Could not initialize class thaumcraft.common.entities.monster.EntityPech

See - #959
