### ISSUE TITLE
Im crashing

### ISSUE THREAD

**Issue by Meaffjo** [scalda/FoolCraft#982]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Im keep crashing if i move or do something in the quest book

## Reproduce Steps
Moving

## Additional Information

 https://pastebin.com/Euv6DDnz

**Comment by generrosity** [comment]
Looks like your error is: java.lang.OutOfMemoryError: GC overhead limit exceeded

GC is 'garbage collection'. Do you have enough memory allocated? Using the G1GC?

**Comment by Meaffjo** [comment]
I fixed it but i crash with another error.
[crash-2018-04-03_15.18.17-server.txt](https://github.com/scalda/FoolCraft/files/1871630/crash-2018-04-03_15.18.17-server.txt)

**Comment by generrosity** [comment]
Known issue - you can disable Pech spawning in the configs. Search issues for Pech if you need more info.
