### ISSUE TITLE
Foolcraft 2.12 world crashes. Crash report inside.

### ISSUE THREAD

**Issue by iMaxeZ** [scalda/FoolCraft#984]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I'm starting my world and it's crashes. All fine with new worlds. Can't read report files properly, so I can't find the issue.

## Reproduce Steps
I think it's problem with my world so for me:
1. Run Foolcraft 2.12 from Twitch launcher;
2. Run my world;
3. Done!
You will need my save file for it. If crash report doesn't help, I can send a world file.

## Additional Information
Crash log pastebin: https://pastebin.com/zMYfKuvB

**Comment by generrosity** [comment]
Could not initialize class thaumcraft.common.entities.monster.EntityPech

See - #959 & #964

You need to set B:spawn_pechs=false under monster_spawning in the config/thaumcraft.cfg file

**Comment by iMaxeZ** [comment]
Thank you very much! Now it works:)
