### ISSUE TITLE
Server is crashing when moving into new areas/chunks

### ISSUE THREAD

**Issue by codemonkey812** [scalda/FoolCraft#985]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
The issue seems to be an entity from thaumcraft trying to spawn. When we explore a new biome the server crashes randomly, and the only way to fix it is to re-state the serve and immediately TP away when we launch.

## Reproduce Steps
Tavel into a new area
[crash-2018-04-03_23.05.17-server.txt](https://github.com/scalda/FoolCraft/files/1874278/crash-2018-04-03_23.05.17-server.txt)
[crash-2018-04-03_23.09.44-server.txt](https://github.com/scalda/FoolCraft/files/1874279/crash-2018-04-03_23.09.44-server.txt)
[crash-2018-03-28_22.53.21-server.txt](https://github.com/scalda/FoolCraft/files/1874280/crash-2018-03-28_22.53.21-server.txt)
[crash-2018-03-28_22.30.08-server.txt](https://github.com/scalda/FoolCraft/files/1874281/crash-2018-03-28_22.30.08-server.txt)

**Comment by generrosity** [comment]
Known issue - you can disable Pech spawning in the configs. Search issues for Pech if you need more info.

**Comment by codemonkey812** [comment]
Thank you. I have disabled the mod.

**Comment by generrosity** [comment]
sweet! you can 'close' the issue as you comment if everything is otherwise working

**Comment by codemonkey812** [comment]
Well, upgraded to 2.12 and the issue came back. I checked the config file and pech is still set to false but the server is crashing.

Could not initialize class thaumcraft.common.entities.monster.EntityPech

**Comment by generrosity** [comment]
I thought you disabled the mod? If you are wanting it, consider disabling hats mod maybe?

I haven't seen why disabling in the configs doesn't work for some people. I can only think maybe there is a biome added to non- BIOMSOP worlds??

**Comment by Mrbysco** [comment]
Updating modpacks re-enables mods. You need to disable it "Again"
