### ISSUE TITLE
crashing when starting new map with crash report 

### ISSUE THREAD

**Issue by mwkk11** [scalda/FoolCraft#986]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x] I am requesting help with installing or running the pack

## Issue Description
game runs smooth till about 10 mins into the game then just crashes i have started a new map and still the same thing reinstalled the modpack same thing

## Reproduce Steps
i have no idea just know it happens everytime i start a new map plays fine for a few mins and then crashes 

## Additional Information

 is my crash report 
https://pastebin.com/raw/ikMWaY1b

https://pastebin.com/raw/YC76UHHK

https://pastebin.com/raw/eYqU9dP6

**Comment by generrosity** [comment]
Heya, you have ticked the "I have searched for this issue" - search for 'pech' and how to disable them
