### ISSUE TITLE
Stuttering and freezing.

### ISSUE THREAD

**Issue by Lil-Leto** [scalda/FoolCraft#988]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Alright, so:
Getting numerous stuttering issues after about 10 minutes in. 7.5gb of ram out of 8gb was allocated due to this being far more frequent on 4gb.
After it reaches the 4gb mark ram wise, issues begin to start, with stutter occuring about every 10 seconds with framerate going from 122 to 15.

Furthermore, during one of these stutters, the entire game decided to lock up and didn't respond for about 5 minutes.

Can I get some advice on how to reduce the stutter?
Got Optifine installed too which is what made the fps manageable (terrain animations killed it to 3fps).

## Reproduce Steps
Loading the game with 6gigabytes of ram allocated (6100mb or so) seems to cause the issue after several minutes of gameplay.
Not much else I can say to help reproduce the issue.

## Additional Information
Optifine and BetterFPS are installed.
7.5gb allocated.
Running an AMD 845 quad core with an RX 460 and 8gb of RAM.

**Comment by generrosity** [comment]
Make sure you have betterfps and foamfix too.

6gig ram is the common minimum for running the world server, single player typically needs more to have client side too.

Don't over allocate ram, the OS needs some too, or you stay using slower virtual memory (having chrome etc running also really doesn't help)

Good luck! It's a hearty mod pack 😁

**Comment by Lil-Leto** [comment]
I'll try looking for a better version of foamfix, since I aren't too sure if the one in the pack is working too well. As for BetterFPS, I wasn't sure which algorithm to use, so, I guess I'll have to experiment a bit.

**Comment by generrosity** [comment]
Foamfix mod author never wanted people to use lawful, and has decom'd it since to be an option only.

Better FPS algorithms IMHO are just icing on the cake. I think you can hover / control right click and it will test all of them.

**Comment by Lil-Leto** [comment]
Alright. Swapped to the anarchy version (even if it says it's for 1.12.2, it's the same version number as the one running in the pack and the mod index doesn't give clear results for which versions are supported or not). I'll tweak with better fps to find the best algorithm.
Just need to test it all first.
