### ISSUE TITLE
Crashing at random & without warning

### ISSUE THREAD

**Issue by ineedabetterusername** [scalda/FoolCraft#989]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
In 2 separate worlds now, after I put in enough time to be needing to spread out, the game starts to crash. In my first world, I would open the world, get to walk around for a few laggy seconds, then it would crash, an annoyance, but I was getting bored with it anyway, so I didn't mind moving on to a second world, where everything was fine for a while, until I went out exploring and found a semi-decayed tower. While I was exploring the tower, I crashed for the first time in this new world. I then reopened the world, and had enough time to get most of the way back to my base before it once again froze and crashed. This is now happening with extreme and irksome regularity, particularly because it now only takes a few seconds to get to crashing.

## Reproduce Steps
All I've been doing is opening the world and playing as normal for a few minutes before getting kicked out by the crash. Location doesn't seem to matter, nor does what I'm holding, looking at, or doing, it just kind of happens

## Additional Information
Other important bits: I've already checked, the petch is disallowed from spawning, that isn't what's causing the issue here
It runs fine up until it freezes and crashes, no lag, no stuttering, nothing

[crash-2018-04-08_12.02.39-server.txt](https://github.com/scalda/FoolCraft/files/1887800/crash-2018-04-08_12.02.39-server.txt)

**Comment by scalda** [comment]
@generrosity in 2.13 the pech is disabled here is the code from my release build in the twitch launcher  
![image](https://user-images.githubusercontent.com/1837979/38492542-31918e4c-3be7-11e8-8413-6740ea597fc5.png) so i don't like the reference you have just given in your message 

> Scalda confusingly hasn't explicitly disabled Pech it in this pack

**Comment by generrosity** [comment]
Apologies Scalda - I didn't realize last week's release had it, it hasn't for a while and I haven't upgrade as was waiting for a server pack (or confirmation just to overwrite only server configs - not sure how that works either), and people were still reporting errors.

**Comment by scalda** [comment]
thats fine it just got my back up alittle bit. and sorry about the server files i will get them posted today. i have been really busy with FoolCraft 3 this last week and bit and have a long road ahead of me.

**Comment by MPapendrecht** [comment]
It seems even with the spawning of Pechs disabled I can still get the crash. I added the crash report and double checked the thaumcraft.cfg file.
[crash-2018-04-09_16.42.50-server.txt](https://github.com/scalda/FoolCraft/files/1890362/crash-2018-04-09_16.42.50-server.txt)

**Comment by generrosity** [comment]
Thanks Scalda! We are always keenly listening for your updates, and wish there was a way to donate some of my time to it. Woop! - server test and upgrade starting this weekend 👌😁

**Comment by scalda** [comment]
i am currently taking applications for testing foolcraft3 https://twitter.com/ScaldaYT/status/982968750948470784

**Comment by ineedabetterusername** [comment]
I think that disabling thaumcraft fixed it. I've only had it running for about 5 min at this point, but nothing bad has happened. I'm going to leave it like this for another hour or 2 and see if anything happens. Thanks for the help

(sorry this took so long, I set a reminder for the wrong time and I was in the middle of class when it popped up, I only got home a bit ago)

**Comment by generrosity** [comment]
Sweet @ineedabetterusername - glad that worked. If you are after Thaumcraft, disabling Hats also might work.  Do hit the "close issue" next to the "comment" button when you are sure.

**Comment by ineedabetterusername** [comment]
Yeah, I left a world running afk for a bit more than 2 hours now, nothing crashed, I think it was thaumcraft, which sucks because I was looking forward to getting into the new version. Ehh, hope that it gets fixed, but thanks for the help, you've been great
