### ISSUE TITLE
100% CPU being used

### ISSUE THREAD

**Issue by szfi** [scalda/FoolCraft#99]
The first time I ran Foolcraft I don't believe I was at 100% CPU but now it is 100% CPU.
What I recently have done:
-update java
-dedicate 2gb ram to java so my forge server can run
Specs:
GTX965m
12GB Ram
i7 6700HQ CPU @ 2.60ghz

**Comment by scalda** [comment]
You need to give client and server at least 6gb ram each

**Comment by szfi** [comment]
so i need 6gb ram on minecraft and 6gb on server? correct?

**Comment by szfi** [comment]
AH figured it out i put 6gb of ram into minecraft profile and got it to work. THANK YOU!

**Comment by scalda** [comment]
Correct
