### ISSUE TITLE
Iskallium Mini moo

### ISSUE THREAD

**Issue by hexangle** [scalda/FoolCraft#990]
- [x ] I am running the latest version of FoolCraft
- [ x] I am running FoolCraft via Curse/Twitch Launcher
- [ x] I can reproduce this issue consistently
     - [ x] In single player
     - [ ] In multiplayer
- [x ] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.

- [ ] I am crashing and can provide my crash report(s)
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x ] I am requesting help with installing or running the pack

## Issue Description
So I am running the latest version +I tried it in the previous one (2.12)
and I saw in iskall85 's video: **https://www.youtube.com/watch?v=jujdGWFy9I8**
around 5:25 - 5:30 he had Iskallium mini moos so I went searching in the world and I couldn't find them.I went in my test world and spawned like thousands of fluid minimoos and none of them was an iskallium one , also I can't like spawn it in with the name. Also important I spawned them in with the /summon command.

Is it possible that it isn't available for us yet or is there something wrong?

Thanks from Belgium.

**Comment by aolsen96** [comment]
You have to feed any mini moo iskallium to convert it to an iskallium mini moo :)

**Comment by hexangle** [comment]
OOH thank you so muchhhh :))
