### ISSUE TITLE
Keep Crashing

### ISSUE THREAD

**Issue by Jaciii** [scalda/FoolCraft#991]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
When I play Foolcraft, I often crash or get big lag spikes, that make my feel like the game will crash. I have NO idea why it happens (I don't understand crash reports). The crashes happens random. What do I need to change?

## Reproduce Steps
I play in 30-60 minutes

## Additional Information
Minecraft is crashing without crash-reports... This is also the 3rd time I have problems in Foolcraft

**Comment by hexangle** [comment]
There is one biome that lets your wotld crash could be that and otherwise maybe you shoud give it more RAM via curse launcher/twitch press 3 dots, profile options than change the memory settings

**Comment by Mrbysco** [comment]
is there anything in your logs folder

**Comment by Jaciii** [comment]
This time there was a crash report, and when I load my world it imedialty crash... I think its another reason, maybe the biome, but the crash report is https://pastebin.com/zt77jTdG

**Comment by Jaciii** [comment]
Now I crash every 5 minutes... I'm in a new area, but its REALLY anoying, cause I want to build a base in the area

**Comment by Mrbysco** [comment]
That crash is due to Thaumcraft pechs. #966 <- Read the issue/comments.

**Comment by Jaciii** [comment]
The pechs are already removed...

**Comment by Mrbysco** [comment]
Nope. Your game is still trying to find them 
![afbeelding](https://user-images.githubusercontent.com/9308260/39008027-cd3ea38e-4407-11e8-95c7-c52754bde463.png)

**Comment by Mrbysco** [comment]
I think either azanor or someone else has derped and forgot to remove the biome spawning when the pech's disabled

**Comment by Jaciii** [comment]
I would think it would crash imediatly if thats the problem

**Comment by Mrbysco** [comment]
You'd think, but apparently not. The crash log clearly states it can't find the EntityPech class. Which means something is still calling it

**Comment by Jaciii** [comment]
So the game started instant crash when I logged in (as I expected), and I tryed to remove Thaumcraft, and it stopped, but I'm not sure if that fixes the first/real problem that the issue says.

**Comment by Jaciii** [comment]
Nope it didn't help with the real/first problem

**Comment by Jaciii** [comment]
Ok it works now...
