### ISSUE TITLE
Crashing instantly

### ISSUE THREAD

**Issue by Dbrickster98** [scalda/FoolCraft#993]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x ] I am requesting help with installing or running the pack

## Issue Description

When I load my world I can do something for like 30 seconds or less and crash.

## Reproduce Steps

I do not know how someone else could repeat this. If needed I will add the world save.

## Additional Information

[crash-2018-04-14_16.25.52-server.txt](https://github.com/scalda/FoolCraft/files/1911105/crash-2018-04-14_16.25.52-server.txt)

**Comment by Mrbysco** [comment]
This issue has to do with pechs and if you had searched "pech"  you would see there are over 13 issues that all mention it. 

#966 <- Read the issue/comments.

**Comment by Dbrickster98** [comment]
I have already disabled the Pech. This is after doing that.

**Comment by kleshas** [comment]
Just happened to me as well, and I also have spawnPechs disabled.

**Comment by FooF-555** [comment]
how do you disable hats?

**Comment by kleshas** [comment]
Before you start the game, change the extension of the mod from .jar to .disabled (or something).

**Comment by FooF-555** [comment]
iChunUtil-1.10.2-6.5.0 is this the mod that I have to disable?

**Comment by FooF-555** [comment]
never mind found out the mod

**Comment by kleshas** [comment]
Have you customized any key bindings?

**Comment by FooF-555** [comment]
yes
