### ISSUE TITLE
Crash while loading minecraft

### ISSUE THREAD

**Issue by Server909** [scalda/FoolCraft#994]
# Crash

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
Minecraft keeps crashing before it even loads.

## Reproduce Steps
When I click Play on the launcher the launcher disappears and then appears saying "An unexpected issue has occured and the game has crashed. We are sorry for the inconvenience."

## Additional Information
https://pastebin.com/JeJGC0fg

**Comment by Server909** [comment]
Its fine I reinstalled minecraft addon for twitch and now it at least loads but crashes after 10 sec of joining a world. Pastebin: https://pastebin.com/8jYVV7xV

**Comment by FooF-555** [comment]
I'm crashing too, though it's when I try to load a world.
